### ISSUE TITLE
Installer: Add Option to ensure that .nvda-addon File Association is not Registered

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10019]
Currently, the installer adds a file association for ".nvda-addon" files during installation of NVDA - there's not currently any way to disable this. Could this either be added as a checkbox when a user chooses to install NVDA, or added as a command line switch?

**Comment by DrSooom** [comment]
Both (checkbox and command line flag) are needed during installation, but the default behavior shouldn't be changed.

**Comment by XLTechie** [comment]
This is one case where I think a checkbox would be "too many options". Please do 
it by a switch if it is to be done.

**Comment by Adriani90** [comment]
Why would an user need an option to disable the attribution?

**Comment by Brian1Gaff** [comment]
The only way I can think of that this can be dangerous is if a malicious 
writer made an add on that could circumvent security in some way.
I guess it depends how paranoid you are.
 Reading some of the huge holes found recently in commercial systems, I'd 
suggest this may be something to consider, but there is really no such thing 
as total security.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment]
Which exact scenario has happened rather recently.

https://nvda.groups.io/g/nvda/topic/3112828

**Comment by elliott94** [comment]
> 
> Which exact scenario has happened rather recently. https://nvda.groups.io/g/nvda/topic/3112828

This. Security is the primary reason; advanced users may not wish to have NVDA automatically register this upon installation, and as an extra security measure may choose to either install add-ons via the Add-Ons Manager, or directly paste the content of the archive into the "addons" directory of NVDA's configuration. I agree that a command line switch may be more suitable for this, but it would be a welcome security-based addition.

**Comment by josephsl** [comment]
Hi, copying add-on archive to add-ons directory… That’s a security hole, actually if not done carefully. As @DerekRiemer once mentioned, one of the most bullet-proof way to guarantee add-on security is cryptographic signatures for add-on bundles. Thanks.

**Comment by elliott94** [comment]
I understand this - for advanced users, however, they're more likely to actually take a look at the contents of the archive rather than just installing via the Add-ons Manager, and would be more likely to weigh up the risks of installing unknown packages.

**Comment by josephsl** [comment]
Hi, defining “advanced users” is subjective, and not everyone knows about file extension renaming trick or aware of archives (such as 7-zip) that can open .nvda-addon files, which are really zip files. And suppose an archive is opened, which then leads us to consider how many people know about opening Python source code, or if there is no source code, ways to disassemble .pyc/.pyo files. We can claim that we have improved security by not registering .nvda-addon extension or adding an option to do so, but there are potential avenues to break NVDA’s security – Python is a good target vector, not just add-ons. Thanks.

**Comment by Adriani90** [comment]
I think a command promt parameter for stopping NVDA to open nvda-addon files would be suitable here. However, given the warnings that are already on the addons official website, I think private users are educated enough. But for corporate environments I can imagine that security policies specify which file formats are allowed to be opened. I am quite sure that only a limited people in corporate environments are aware of nvda-addon file format. So they as admins would directly want to prevent NVDA to open such files.
cc: @JulienCochuyt what do you think?

**Comment by JulienCochuyt** [comment]
@elliott94 wrote:
> advanced users may not wish to have NVDA automatically register this upon installation

What is the use case defended here?
The typical use case for choosing file associations at installation time is to ensure a newly installed piece of software does not interfere with your current file associations. That is, being able to keep on opening the said files with your software of choice rather than the newly installed one, despite its capabilities. Eg. When installing LibreOffice on a computer that already has MS Word installed, you probably don't want to open `.doc` files with LibreOffice, despite it can.
This typical use case is fairly out of consideration here as `.nvda-addon` extension is fairly specific and the current installation mechanism does not support having two distinct versions of NVDA installed.

As NVDA always prompts for confirmation before installing an add-on - and even before loading any code from it - there is no way for a malicious add-on to execute unwanted action before being voluntarily installed. Please prove me wrong, I'd be sincerely interested.

If file association is disabled, a user can still easily install the above mentioned malicious add-on.
Thus, my point is that the security risk is not on the file association, but rather on the wisdom of the choice made by the user to install or not a given add-on.

@Adriani90 wrote:
> for corporate environments I can imagine that security policies specify which file formats are allowed to be opened.

I haven't met yet a sysadmin that disables file associations to ensure a file is not opened, as users can still open the file manually from within the application.
The only real-life cases I have encountered were disallowing `.nvda-addon` files, as unknown files, to be downloaded from the Internet via proxy policies.

@josephsl wrote:
> As @derekriemer once mentioned, one of the most bullet-proof way to guarantee add-on security is cryptographic signatures for add-on bundles.

This, to my paranoid mind, is the only way to go.
Too many users are facing enforced secure mode, which blocks them from using eg. legitimate synth or braille drivers.
Signing add-on bundles could not only help users identify an add-on has not been maliciously altered, but also allow sysadmin to select trusted sources.

**Comment by Adriani90** [comment]
I agree with @JulienCochuyt comment here. And yes, my point was refering more to the fact that system admins disable the possibility to download nvda-addon files, which of course implies also that you cannot open them. On such systems media drives are not allowed anyway.
All this being said, I am closing this issue for now because we don't really see a robust use case for this feature. If you have other arguments pointing towards implementing this, please comment on this issue and we can consider to reopen the discussion. Thanks.
