### ISSUE TITLE
Operating System Support: Devise Roadmap for Current and Future OS Lifecycles

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10017]
Firstly, apologies if this has already been discussed or logged elsewhere; I wasn't able to find it if that's the case!

I think it'd be really useful for a roadmap to be devised to give both users and developers a clear indication of when certain operating system releases will no longer be supported. As an example, Microsoft will end support for Windows 7 in January next year, but in my opinion it makes no sense to simply stop supporting it on that date; I can't imagine any big piece of software doing this eather. Similarly, if we for example stopped supporting anything below Windows 10 in the future, this is all fine and well; however, this doesn't help us if a user is still running Windows 10 build 1507 in terms of new feature planning that relies on a certain version of Windows to run. Thus, an agreed roadmap on when existing (and future) operating system releases will be depricated will be beneficial for everyone; users can plan their upgrade to future Windows releases, and developers will have time to test their code too.

**Comment by lukaszgo1** [comment]
I believe in the past the strategy was to support as many versions of Windows for as long as possible, and drop support when there was an actual reason for doing it. I can see advantages in creating a clear plan for dropping support particular releases of Windows. It however, might  make many users unhappy, when version of Windows which they are using would no longer be supported not because of some technical limitation, but because we simply  decide to do this. Something which would help in this would be to have publicly available statistics of operating systems in use. NVDA collects this info anyway. @feerrenrut Is this something which could be implemented in the NV Access website?

**Comment by DrSooom** [comment]
@lukaszgo1: Which OS is used by the user is sent to the server during checking for updates. I guess these logfiles are already used for statistics.

**Comment by lukaszgo1** [comment]
They certainly are, however it would be nice to make these publicly available.

**Comment by Brian1Gaff** [comment]
Weave the unique problem since windows 10, in that many of the older 
incarnations are not directly supported by the add on Joseph makes. However 
I strongly suspect from the people I know that there are a lot of Windows 7 
installations out there, and will be for some considerable time, since many 
large organisations do not any choice due to constraints on their rewriting 
of software or having windows 10 drivers for medical hardware.

I have not seen any change of policy on this one.
I do hope we do not get too draconian here.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by josephsl** [comment]
Hi,

As noted by many in the past, NVDA won't suddenly drop support for a Windows release just because Microsoft says so. We saw this happen with Windows XP support - support ended in 2014, but NVDA kept supporting it until late 2017. I expect the same will happen with Windows 7/Server 2008 R2 support - supporting as long as technologies we use continue to run on older releases (and this is the policy I employ for my add-ons, except for ones that will require newer NVDA version and/or Windows release to function properly).

As for statistics: I'm in favor of that - perhaps releasing it shortly after each NVDA release. I expect someone from NV Access will make a comment about that during NVDACon anyway, so I think that should take care of that.

For now, I'm closing this. Please reopen this one if folks come up with really powerful justifications.

Thanks.

**Comment by feerrenrut** [comment]
I don't think we would be in favor of publishing this information on the website, it would require quite a bit of work to decide on a useful way to present it, and is of questionable value to the public. I believe we will continue to make general announcements about the ongoing support of operating systems as necessary.
