### ISSUE TITLE
Add Secure mode system wide parameter to Force NVDA to run in secure mode

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10018]
Currently, NVDA offers several command line switches that are really useful in corporate environments; however, it'd be really useful if an extra command line switch could be added to perform a silent install, but to replace the default Desktop shortcut with an alternative that enables several of NVDA's security-conscious features by default. As a starting point, the shortcut could include the following switches:

Secure

Disable Add-Ons

No logging

We may also wish to consider adding an option to tell the installer not to register ".nvda-addon" as a file association (see #10019 for more info). The option to choose which of these features are included in the generated shortcut would also be a nice addition; these could be specified using separate switches as part of the same command line argument.

**Comment by DrSooom** [comment]
Hmm, as long as the user can change the desktop shortcut as well as the shortcut in the start menu, this makes no sense. See also: Issue #9284

**Comment by elliott94** [comment]
I disagree; for system administrators, making things as easy as possible is key. Whilst it may take effort to implement, you could argue that it's much easier to deploy NVDA with a command line switch that automatically ensures that the deployed shortcut enforces as many secure options as possible rather than having to create a separate Group Policy (or similar) to manage this. It could be argued that a more advanced user could change this shortcut, but NVDA making this easy to deploy is a step in the right direction I think.

**Comment by DrSooom** [comment]
No, as long as a user has the permission to change shortcuts on the desktop, he will do this, because he can. Your job as an administrator is to prevent the user to be able to change these shortcuts. Of course it depends where these shortcuts are located and if a domain is used.

In my opinion the only way to keep that as simple as possible is to implement an additional config file in the program folder, as I already described [here](https://github.com/nvaccess/nvda/issues/9284#issuecomment-464259471). Then the user cannot make any changes and NVDA will always start as it should. This is the securest solution. Just trusting your users isn't secure at all – it's a huge failure.

**Comment by JulienCochuyt** [comment]
> No, as long as a user has the permission to change shortcuts on the desktop, he will do this, because he can.

The desktop shortcut is located in the "All Users" directory.
A user which is not a local admin won't be permitted to change this.
It is the exact same approach for a system wide config, thus your argument does not stand.

Nevertheless, as you proposed, I'm much in favor of a system wide config, layered upon the user config. Note however that instead of a single `.ini` file, I'd rather promote a full systemConfig directory, - probably in `C:\ProgramData\NVDA` -  allowing corporate environments to much more easily deploy addons and the like.

**Comment by leonardder** [comment]
For a system wide add-on store, see #6822.

As for the --secure flag in the shortcut, it is still possible to run NVDA from a command prompt or a run dialog. Also, this parameter is meant for secure desktops, not primarily for more secure environments. For example, it is not possible to save the configuration when running in secure mode.

**Comment by JulienCochuyt** [comment]
> For a system wide add-on store, see #6822.

Thanks a lot for pointing this out.

> As for the --secure flag in the shortcut, it is still possible to run NVDA from a command prompt or a run dialog.

Good point.

> Also, this parameter is meant for secure desktops, not primarily for more secure environments. For example, it is not possible to save the configuration when running in secure mode.

Thus, shouldn't we close this issue as wontfix?

**Comment by DrSooom** [comment]
@JulienCochuyt: You are right. I forgot to mention that the Windows Desktop is built on two (or three) different paths. In most cases it's a mishmash of the user desktop folder and the public desktop folder. And the third path could come during the login into a domain by an AD configuration. In other words: If you login into a domain, all your files and folders on your desktop are copied during the login process onto the client machine. That was the case with Windows XP and Windows Server 2003. I guess that this mechanism maybe was changed in the meantime. I'm not familiar with the current Windows Server operating systems.

**Comment by Qchristensen** [comment]
Would adding a registry entry, as per https://www.nvaccess.org/files/nvda/documentation/userGuide.html#SystemWideParameters work?  Something like "AlwaysSecure": True, which would force any copy of NVDA running on the machine to run in secure mode as if --secure was specified?

Regardless of how it is implemented, I also agree that when run with --install / --install_silent and --secure together, a system admin could logically expect that the installed version of the software should run in secure mode (as evidenced by the email I just got from such a sys admin).

**Comment by elliott94** [comment]
> 
> 
> Would adding a registry entry, as per https://www.nvaccess.org/files/nvda/documentation/userGuide.html#SystemWideParameters work? Something like "AlwaysSecure": True, which would force any copy of NVDA running on the machine to run in secure mode as if --secure was specified?
> 
> Regardless of how it is implemented, I also agree that when run with --install / --install_silent and --secure together, a system admin could logically expect that the installed version of the software should run in secure mode (as evidenced by the email I just got from such a sys admin).

Sure - this would be perfect. :)

**Comment by snokas** [comment]
Registry entry would do it. Thanks!
