### ISSUE TITLE
NVDA Configuration: Clean-up of Old Values within nvda.ini when Values Depricated

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10024]
So, some background:

If a user is running an old NVDA build (let's take 2011.1 just purely as an example) and then upgrades to the current release version (2019.1.1), due to lots of changes that we've made in NVDA's config structure over the last several years there will be lots of values that are no longer used. Could we add something to core that will search the copy of nvda.ini that gets loaded, and automatically remove any values that no longer apply to NVDA? Configuration files can get pretty messy; as an example, when updating an old snapshot that I had laying around from 2012 to the latest Alpha snapshot, there were over 100 lines of configuration values that NVDA itself no longer needs/uses.

**Comment by josephsl** [comment]
Hi, technically, yes by running configobj.get_extra-values for each config section. Thanks.

**Comment by Adriani90** [comment]
Cc: @leonardder

**Comment by XLTechie** [comment]
Originally when considering this, I thought it sounded like a good idea.

However, as a general rule, I run the most recent beta on my production system. 
However, a few minutes ago, I found a bug in that beta, causing a repeatable 
focus loss in Excel. I thought "Well, I'll roll back to 2019.1.1, and see if it 
existed there", which immediately made me think of your suggestion here.

If we start pruning old configuration data, do we not risk making it difficult 
to revert to previous versions of NVDA while using the same installed 
configuration?

The most obvious way I can think to handle this in a "soft" way, is to maintain 
configuration compatibility back some arbitrary number of years. Three, for 
example. Thus allowing anyone who runs 2019.1.1 or 2019.3, to revert to 2016.1 
without losing any configuration compatibility.
When we hit 2020.1, the earliest fully compatible rollback config would be for 
2017.1.

That, I think, would give you the best of both worlds, and cover the most likely 
version reversion cases. And of course, for anyone who never runs anything newer 
than 2019.3, this will never be an issue, because they won't have the cleanup 
fix anyway.

**Comment by josephsl** [comment]
Hi, another issue to consider is that when the old values are gone, when a user reverts to an older release, default values will be assigned to “deleted” options, making it more confusing and troubleshooting difficult. I myself use the suggested idea on one of my add-ons but with a caveat that people are warned in advance that installing an older version of an add-on isn’t supported. Thanks.

**Comment by DrSooom** [comment]
We should expand this to the "gestures.ini" as well. Therefore I suggest a clean-up tool, which will be reachable via the Tools menu. Clicking on it with lead to the following question:
+ [Text] This clean-up tool will delete all deprecated entries in the NVDA configuration and in the customized gestures files. A backup of the current files "nvda.ini" and "gestures.ini" are stored in the folder "backups" in the user configuration folder of NVDA.
WARNING: If you decide to downgrade NVDA to a previous version, which isn't recommended, several settings and/or input gestures have to be configured again.
Do you want to continue?
+ [Buttons] Yes, No (has focus)
+ Note: The file name of the backed up files must contain the current timestamp (YYYY-MM-DD-hhmmss). So "gestures.ini" will be renamed to "gestures_2019-08-02-231545.ini".

Well, I already was thinking about a better backup and restore mechanism for the whole configuration folder, but this really needs a detailed preparation, before opening such an issue on GitHub.

**Comment by XLTechie** [comment]
I would love to see a configuration import/export mechanism, that maybe 
generates a zip or other collective file containing current config, and can 
re-absorb same. I think that should come before something like this.

It is not clear to me why any user (one not involved in testing, and so on) 
would invoke such an option on the tools menu, and I foresee numerous questions 
about whether they should, appearing on the users lists. It also seems possible, 
that users could become too aggressive with such an option and then regret it 
later.

I still haven't found a reason not to like my rolling cleanup idea, perhaps with 
a warning such as you described upon launch of a version that wants to do a 
cleaning.

**Comment by feerrenrut** [comment]
@elliott94 please use the gituhub issue templates in future. If you would like to start a general discussion please use the nvda developers mailing list.

**Comment by Adriani90** [comment]
Actually I agree to @XLTechie's comments above. Down grading is very useful especially if you have severe bugs in a current version. I have downgraded and upgraded several times and I didn't get any additional bugs after that. Ofcourse this might differ from system to system. But why should someone want to clean those files? Actually they are very very small and they do not have any impact on your system performance. Moreover, you can set NVDA to factory defaults if you want and I guess all the settings are gone after that.

**Comment by Adriani90** [comment]
I vote for closing this issue since I don't see any benefits from deleting those entries from the ini file. Regarding gesture mapping, I advice not to consider such a feature. Note that there are braille displays also which save their emulated keys there and there are also addons working with that file. I would not introduce a feature in NVDA which, if used accidentally, would really destroy significantly the current installed copy of NVDA.

**Comment by feerrenrut** [comment]
Rather than cleaning up the config in-place, it might be better to have an "export / import" config option.

I don't think a "messy" config is something that causes a problem, and it's even rarer that someone cares about it. Because the core use case of this and benefit isn't obvious, there isn't much point discussing the implementation details. I'll close this issue for now.
