### ISSUE TITLE
Website: Add Browsable Directory of Previous NVDA Builds

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10023]
This may link in quite nicely with #8884; for interested users, it would be nice if we had an easily-browsable list of old NVDA builds that could be downloaded - for historical reasons if nothing else. There's a really nice reference point still hosted at Source Forge (https://sourceforge.net/projects/nvda/files/releases/) - could we grab the files still hosted at SF as well as releases published since we started using GitHub, and combine them all into a nice list?

**Comment by DrSooom** [comment]
I already was thinking about creating a static HTML page with a list of all releases and their links to the Installer and Changelog back to 2012.2. Sadly I haven't the time to do that now, but it is quite easy to create such a page – including `<details>-<summary>-pairs`.

In the meantime: Please add the .htaccess file with `Options +Indexes` for [this directory](https://www.nvaccess.org/files/nvda/releases/). This helps everybody immediately.

**Comment by feerrenrut** [comment]
I believe it's intentional, we want people to be using the latest NVDA version.

**Comment by DrSooom** [comment]
@feerrenrut: That's not the point here. It is hard to find older NVDA stable versions, if they are needed for testing. Nobody said something about recommend older version to normal users. But it's absolutely not funny to search quite a long time to get an older stable version of NVDA for comparing reasons, which is required for some issues. Furthermore NVDA is open-source; therefore all stable versions of NVDA must be accessible as easy as possible. Putting them offline or hiding them from the public is an absolute No-Go!

**Comment by feerrenrut** [comment]
> It is hard to find older NVDA stable versions, if they are needed for testing.

I empathize with this, and we do want to encourage and streamline this kind of proactive investigation.

> Furthermore NVDA is open-source; therefore all stable versions of NVDA must be accessible as easy as possible. Putting them offline or hiding them from the public is an absolute No-Go

Sorry, but this is patently untrue. We release NVDA under GPL, essentially this means that upon delivery of said software the recipient is entitled to the freedom to use/modify/redistribute this software as they see fit. At the core of it, a distributor must give the recipient what is [commonly referred to as the 4 freedoms](https://www.gnu.org/philosophy/free-sw.en.html):

- The freedom to run the program as you wish, for any purpose.
- The freedom to study how the program works, and change it so it does your computing as you wish. Access to the source code is a precondition for this.
- The freedom to redistribute copies so you can help your neighbor.
- The freedom to distribute copies of your modified versions to others. By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

We are not required to continue to distribute older versions of software, we do however continue to provide access to the source code for these older version, which anyone may build for themselves.

Our concerns for people using older versions of NVDA is related to support. We can not provide ongoing support for older versions of NVDA. After the subsequent release we cease development on the older version. We expect users to be running the latest version of NVDA if possible.

This said, we have had an internal discussion around this, and have decided to provide access to older version of NVDA to allow for easier regression testing. This will also cater to those who NEED an older version to keep compatibility with older software.

We prefer to have a dedicated page over a directory listing. Because it allows us to gather simple (download count) statistics so that we can asses the extent that these releases are being used. We would also prefer to provide a professional (commercial friendly) interface.

It should be noted that NV Access is a small organization, four people and only two software developers. This requires us to heavily prioritize the work that we do, for everything we do there is some bug not being fixed or PR not being reviewed. So I'd ask you to consider how important you really think this is relative to these other tasks.

**Comment by DrSooom** [comment]
> We are not required to continue to distribute older versions of software, we do however continue to provide access to the source code for these older version, which anyone may build for themselves.

Yes, and how many people are able and have the time and skills to build such a version? Even for testing, providing the already built Installers is much easier. It's no problem for me to provide a copy of them via my website (as a mirror including SHA-256 checksums and a link to your [donation page](https://www.nvaccess.org/support-us/#donation-support)).

If you want I can create lists of most of the older stable versions of NVDA by linking them to https://www.nvaccess.org/download/?nvdaVersion=2017.3 and so on. Then you would get the statistics. Note that all required files are already stored on your web server. And it is absolutely clear that NV Access is not providing any support for previous releases. I would mention that directly below the headline "Downloading previous versions of NVDA".

I can upload the HTML file here on GitHub. Then you just have to copy it's source code into the NV Access site and add a new link below "Get add-ons to enhance NVDA" called "Get previous versions of NVDA for testing" or so on the [download page](https://www.nvaccess.org/download/).

**Comment by DrSooom** [comment]
Here is a [prototype with absolute URIs](https://github.com/nvaccess/nvda/files/3475650/10023_Prototype_2019-08-07.zip). I think I will finalize this HTML file quite soon, because it isn't difficult – until to the 2010.x and older versions. Then we have a useful page, on which all relevant NVDA versions are listed – and you still get your download statistics.

**Comment by feerrenrut** [comment]
> Yes, and how many people are able and have the time and skills to build such a version?

Yes, I'm aware of this concern. 

>Then you just have to copy it's source code into the NV Access site and add a new link below

Thanks for the interest, however, for several reasons we will build this page our self. One of these reasons is matching the branding of our site, another the more technical integration with our site means its not necessarily as simple as adding a new html file.

**Comment by DrSooom** [comment]
Well, I guess I wasn't clear enough. I already copied the `div`-container structure incl. class attributes based on the download page into the prototype html file. So after including the html code between the two `article>` tags in the prototype html file to the content area of a new page, the new page should look like the same as the download page. And every CMS should have the ability to add html code manually to a page. So give it a try. The html code was completely written from the ground up by me – excluding some `<div>` lines and one `<img>` line from your website, which I just implemented to get the same design like on the download page. And yes, you can do whatever you want with the prototype html file – it doesn't care me (incl. copyright).

**Comment by DrSooom** [comment]
I posted this comment in issue #8884 as well as in issue #10023, in the hope that it helps somebody finding certain Stable, RC and Beta versions of NVDA. You only have to change the NVDA version once or twice in the following URLs.
+ Download page with parameter:
  + 2017.3 Stable: https://www.nvaccess.org/download/?nvdaVersion=2017.3
  + 2019.1 Stable: https://www.nvaccess.org/download/?nvdaVersion=2019.1
  + 2019.1.1 Stable: https://www.nvaccess.org/download/?nvdaVersion=2019.1.1
  + 2019.1 RC1: https://www.nvaccess.org/download/?nvdaVersion=2019.1rc1
  + 2019.1 Beta 1: https://www.nvaccess.org/download/?nvdaVersion=2019.1beta1
+ Direct links to the exe files:
  + 2017.3 Stable: https://www.nvaccess.org/files/nvda/releases/2017.3/nvda_2017.3.exe
  + 2019.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1/nvda_2019.1.exe
  + 2019.1.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1.1/nvda_2019.1.1.exe
  + 2019.1 RC1: https://www.nvaccess.org/files/nvda/releases/2019.1rc1/nvda_2019.1rc1.exe
  + 2019.1 Beta 1: https://www.nvaccess.org/files/nvda/releases/2019.1beta1/nvda_2019.1beta1.exe
+ Direct links to the html changelog files:
  + 2017.3 Stable: https://www.nvaccess.org/files/nvda/releases/2017.3/nvda_2017.3_changes.html
  + 2019.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1/nvda_2019.1_changes.html
  + 2019.1.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1.1/nvda_2019.1.1_changes.html
  + 2019.1 RC1: https://www.nvaccess.org/files/nvda/releases/2019.1rc1/nvda_2019.1rc1_changes.html
  + 2019.1 Beta 1: https://www.nvaccess.org/files/nvda/releases/2019.1beta1/nvda_2019.1beta1_changes.html
+ Directories:
  + Stable/RC/Beta: https://www.nvaccess.org/files/nvda/releases/
    Note: This public directory is currently forbidden (error 403). You can download files, which are stored in this directory, but you must know their complete path. Therefore a list of all Stable, RC and Beta versions including their release dates and file sizes isn't accessible yet. This can be easily fixed by adding a .htaccess file with the content "Options +Indexes" in that directory on the NV Access web server.
  + Stable/RC/Beta until 2014.4: https://sourceforge.net/projects/nvda/files/releases/
    Note: This page lists all Stable, RC and Beta versions from 0.5 (2008-03-26) to 2014.4 (2014-11-27) including their release dates and html changelog files.
  + Latest Alpha/Beta/RC snapshots: https://www.nvaccess.org/files/nvda/snapshots/
    Note: This page lists plenty of the latest Alpha, Beta and RC snapshots including their release dates and provides direct download links. Previous versions are removed from this page from time to time.

**Comment by Adriani90** [comment]
Actually I don't really understand why people are so concerned about older versions of NVDA not being on NV Access website. There are so many possibilities to find older versions of NVDA, just googleing abit brings anyone further.
1. On filehorse.com:
https://www.filehorse.com/download-nvda/old-versions/
including even the release date
2. On github under the link "releases"
3. On Softonic or on CNet website by searching for the version desired

4. By following the tutorial on how to download old version of NVDA on accessibility central.net

and some others.

And in fact, if you go to the development snapshots page and download the last RC of any old version of NVDA, that version will be in most cases as stable as the final release.

**Comment by XLTechie** [comment]
@Adriani90 wrote:
> Actually I don't really understand why people are so concerned about older versions of NVDA not being on NV Access website. There are so many possibilities to find older versions of NVDA, just googleing abit brings anyone further.

Well, this was already settled I believe, but I will address your points anyway, since I was one of those who was concerned:

>     1. On filehorse.com:
>        https://www.filehorse.com/download-nvda/old-versions/

Do you guarantee the security of that site? Specifically, do you know that whoever uploaded the copies there, had no bad intent, and actually uploaded the original versions?

Honestly I saw that site the last time I was looking for an old version, but I have no idea who they are, what their reliability is, or if they are trustworthy. They can say anything about themselves that they want. They can even provide hashes (which are mostly irrelevant: anyone can upload a new file and generate a hash for it; and even on nvaccess.org, someone could hack the site, upload new files, and provide their own hashes).

>     3. On Softonic or on CNet website by searching for the version desired

I don't know Softonic, but CNet doesn't exactly have the best security track record. see [this article](https://www.tomsguide.com/us/CNET-CBS-Malware-Trojan-Nmap,news-13410.html), and [this other one](https://insecure.org/news/download-com-fiasco.html).

If it isn't provided by the original source, the level of trust starts to go down rapidly, and rightfully so.

>     4. By following the tutorial on how to download old version of NVDA on accessibility central.net

Which is only useful if you know about it; it doesn't show up in any google search I have done for old versions. But that aside, one doesn't need to read a tutorial to download older versions of any other major open source software I have ever used. Want an old version of Python? Visit python.org. Want a 20 year old Linux kernel? Visit [kernel.org](https://mirrors.edge.kernel.org/pub/linux/kernel).

> And in fact, if you go to the development snapshots page and download the last RC of any old version of NVDA, that version will be in most cases as stable as the final release.

Where? If you're talking about [here](https://www.nvaccess.org/files/nvda/snapshots/), where are you seeing "old versions" there? There is no date on that page earlier than this year. I must be missing something.

**Comment by DrSooom** [comment]
@XLTechie: Thanks a lot for this reply. I wanted to write exactly the same.

You cannot trust Third-Party-Websites. Furthermore there quite a lot of such software download sites on the web, which offer a super-mega useful Download Manager to download the desired software via an absolutely securely way. … Yes, of ccourse.

Furthermore I absolutely don't understand, why we MUST explain you/somebody why we want to download an older version of an open-source software. You DON'T have the permission asking for such an explanation and then based on the given explanation to decide to offer older versions of an open-source software or not. We are talking about open-source software – not a commercial one.

And I just want to note again: Most of the older versions of NVDA are already stored on NV Access' web server. Only one stupid .htaccess file is missing! I can't understand this protection policy.

And regarding SHA-256 sums: It is quite hard to modify two files which are stored on two different web servers in combination with displaying the SHA-256 sums on a html site, which is also saved by the Wayback Machine. If the end user isn't able to compare the check sums, then it's his fault. At this point I'm asking me, what will happen if somebody really modify older NVDA versions and a user download that version from a Third-party-Website – without having the option to compare that one with the one which is stored on NV Access' web server. VirusTotal could help here too, because you only need to search for the SHA-256 sum to see the scan results – if that file was already scanned in the past.

**Comment by Adriani90** [comment]
@XLTechie regarding filehorse, this is one of the safest websites when it comes to downloading software, along with softpedia and CNet. They are even more secure than websites from manufacturers because they proof the software from an independent perspective without any bad intention. The people have a full time job in which they do only software proofing, reviewing and uploading. They also have a very promt support in case someone finds a security issue, it can be reported. Not everyone can upload software on those websites. The perception of third party websites being unsecure is a bit too unfair. In germany for example there are websites like computerbild or Chip online with redactions behind them. The people know what they are doing. It is not kind of a torrent website of staff like that.
https://www.makeuseof.com/tag/9-cleanest-safest-websites-download-free-software-windows/


> They can even provide hashes (which are mostly irrelevant: anyone can upload a new file and generate a hash for it; and even on nvaccess.org, someone could hack the site, upload new files, and provide their own hashes).

Well, theoretically you are right. But then, what makes the website of NV Access more secure than filehorse? Do you know the server structures behind both websites? Are you able to assess that as a simple user? I guess not, me neither. Thus, actually every website in the world has its security lacks. But just stating that a third party website is bad perse, this is not a good choice. I would gather some information first and then build an opinion on it.

@DrSooom you write
> You cannot trust Third-Party-Websites.

Well in my opinion this statement is far too narrow. It is not as easy. There are so many organizations which created websites as meta engines for certain things. Just because it is a third party website does not mean that you cannot trust it. You must assess the people behind it and the structures and maybe after that you develop a feeling for if it is trust worthy or not.

> Furthermore I absolutely don't understand, why we MUST explain you/somebody why we want to download an older version of an open-source software.

This point has never been raised before. The question was, why should these old versions of NVDA be explicitely on the NV Access website? And as @feerrenrut already pointed out, NV Access would rather choose an alternative website with a directory of files rather than putting them on the NV Access website. In my opinion, if we have the old versions of NVDA on NV Access website, people will have the impression that those versions are still supported and will start to send tons of questions to NV Access as why they are on the website although they are not suported. If it is a website like nvda.org or so, then this would not be the case.

> You DON'T have the permission asking for such an explanation and then based on the given explanation to decide to offer older versions of an open-source software or not.

well this is quite harsh. Don't you think? Here we are not talking about permissions or not. We are talking about freedom of distributing software. This is what GPL license says. How you do that is your own strategy. If we take this strictly, NV Access already distributes its software on Github. And maybe they send the files directly to other software distributors like filehorse etc. to include them on their websites.

> I can't understand this protection policy.

Well actually it is quite simple. NV Access does not want people to have the impression that older versions of the software are still supported. That's why an alternative website would be a better choice. Further more, NV Access does not promote only this software. And on its website the focus is to promote a philosophy rather than a piece of software. The philosophy is that blind and visually impaired people should have free access to windows computers without additional costs. It is not like Python which promotes really only the python environment and its documentation.

> And regarding SHA-256 sums: It is quite hard to modify two files which are stored on two different web servers in combination with displaying the SHA-256 sums on a html site, which is also saved by the Wayback Machine. If the end user isn't able to compare the check sums, then it's his fault. At this point I'm asking me, what will happen if somebody really modify older NVDA versions and a user download that version from a Third-party-Website – without having the option to compare that one with the one which is stored on NV Access' web server. VirusTotal could help here too, because you only need to search for the SHA-256 sum to see the scan results – if that file was already scanned in the past.

Hm, assuming that every enduser knows what checksums are and how to compare them is quite utopic. But yes, this would be ofcourse an ideal way if everyone can compare them. However, good third party websites which distribute software they proove it and they make sure that it comes from the official website befor uploading it on their website. Unless we are talking about torrent websites or similar things. But that's another topic and is out of this scope.

**Comment by Adriani90** [comment]
@XLTechie regarding the development snapshot page it was my fault. I thought there were older versions too. at least in the past. Sorry.

**Comment by Adriani90** [comment]
And because the topic about hash signatures came up, please read this treat and you will understand why hash signatures are not perse the best security prove. The main reason is simple. There is no regulatory party which countersigns those things. It is like if you had your pasport signed and stamped by yourself and maybe by your neighbours. But there was no government which stamped it.
https://security.stackexchange.com/questions/186185/why-dont-websites-provide-a-checksum-of-their-downloadable-files

**Comment by lukaszgo1** [comment]
In the commend above @feerrenrut said that the web page containing older versions would be created in the future, so I personally don't see a point in continuing this discussion.

**Comment by DrSooom** [comment]
1. Visit https://www.nvaccess.org/get-help/
2. Jump to the question: "What features are you working on for the next version of NVDA? When will it be out? And can I please beta-test it?"
3. https://www.nvaccess.org/files/nvda/snapshots/ is shown in the answer.

So this is quite easy to find – even NV Access given here no support too or recommend such versions! Adding a new question on this site, a link to https://www.nvaccess.org/files/nvda/releases/ and a one-line .htaccess file for this directory solves all problems at once. But I feel like I'm talking to walls. 😒

See also:
+ https://notepad-plus-plus.org/download/all-versions.html
+ https://notepad-plus-plus.org/news/notepad-7.6.4-released.html
+ https://notepad-plus-plus.org/news/v7.6.6-with-gpg-signatures.html

**Comment by Adriani90** [comment]
> even NV Access given here no support too or recommend such versions!

NV Access actually strongly support people and encourage everyone to test Alpha, Beta and RC versions. So the development snapshots are indeed supported. Because if you find bugs NV Access or people aroung the world will look into it. This cannot be stated for old NVDA releases. If you read also the in process articles on NV Access website, almost in every third article or so NV Access advice people to test Alpha, Beta and RC versions of NVDA.

And as I said above, NV Access promotes primarily a philosophy rahter than a piece of software. Ofcourse NVDA might be their main asset but the NV Access website is not to compare with notepad++, python, CCleaner or any other websites which explicitely promote the software. Thus, in my view still an alternative website like nvda.org would be a better choice. But in the end NV Access will decide what to do here because it is its official NGO website and it is not justified to force or to push here towards something. This product is free of charge and the whole infrastructure behind it is already quite good.

**Comment by DrSooom** [comment]
> alpha
Alpha snapshots contain bleeding-edge code. These snapshots are generated straight from NVDA's mainline (master) branch. Once a feature is implemented, it will be merged straight into this branch. Although there are some automated tests, code in this branch may have not been tested at all by users. This should never be used in a production environment!
beta
Beta releases of NVDA are a chance for users to gain early access to new features in NVDA. These builds should be fairly stable as the code has already been tested for at least 2 weeks by users running alpha snapshots. However, these builds are still not recommended for production environments. Note that unlike alpha snapshots, these builds will automatically upgrade to the final stable release of NVDA when it becomes available. When betas start being published for the next version, you will need to manually download one of the new betas if you wish to test that version early.
Source: https://www.nvaccess.org/files/nvda/snapshots/

I guess that says all. I have nothing to add.

**Comment by DrSooom** [comment]
btw: https://www.nvda.org/ is the domain for the Nevada Dental Association in Las Vegas. Sometimes it's better to research before posting. The old domain http://nvda-project.org/, which redirects to https://www.nvaccess.org/, would be a possible solution.

**Comment by XLTechie** [comment]
Adriani90 wrote:

> alternative website like nvda.org would be a better choice.

Or nvda-project.org, which they already own?

**Comment by Adriani90** [comment]
@DrSooom I think we have a different understanding of support. If you will find a bug in Alpha this will be addressed. If you will find a bug in 2017.3, this will not. And this is why NV Access encourages people to test alpha. Support does not mean that they encourage you to use that version in a productive environment.

**Comment by Adriani90** [comment]
@XLTechie I agree. Nvda.org was just an example that I used to ilustrate the difference between an NGO website and a website dedicated for a software and to align my arguments. Ofcourse it was not meant as a final suggestion for this purpose.

**Comment by DrSooom** [comment]
@Adriani90: That's correct, but it doesn't give you automatically the permission to hide previous Installers/versions of NVDA – an open-source screen reader. If you are new to NVDA and install 2019.2, you will note issue #9982, if you want to use the Chinese Taiwan/Mandarin braille table. Therefore offering an easy way to get older versions of NVDA is required. Or you really have to install a Beta or RC version, as they are easier to find via the website or a Google search.

And what the hell is sooo difficult for adding this text from [my prototype website](https://github.com/nvaccess/nvda/files/3475650/10023_Prototype_2019-08-07.zip)?
> Important note: We are not providing any support for all previous versions of NVDA, which are listed on this page. We always strongly recommend to use the latest stable version of NVDA, which you get here. This page is offered for testing and historical purposes only!

**Comment by zahra21** [comment]
hi.
i agree.
i believe that nvda website should have direct download link for all of nvda versions.
many people have different needs and interest.
people should select there desired versions of nvda to download and use.
for example: 2017.3 version of nvda is the best version for me that i discovered recently and wish to use it forever.
the best version of espeak for me is espeak ng is 1.49.1.
does nvda 2017.3 have the stable version of espeak ng 1.49.1 in itself?

**Comment by feerrenrut** [comment]
Closing this issue. It was addressed a while ago with https://www.nvaccess.org/category/news/releases/
