### ISSUE TITLE
repetition when focusing a console window

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#10030]
### Steps to reproduce:
open a console window, in my case I open bash
2. open any other windows such a browser. 
3. tab back to your console window.
### Actual behavior:
I hear root@Computer name, window, terminal, selected, terminal selected
### Expected behavior:
hearing only the window name, + "console" to know the type of focused app
### System configuration
core -i7 24 gb ram, ssd drive
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-18290,7b5cd2d0
#### Windows version:
windows Version 1903 (OS Build 18950.1000)
#### Name and version of other software in use when reproducing the issue:
none
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
console work has just landed, so unrelated.

**Comment by mohdshara** [comment]
@codeofdusk

**Comment by codeofdusk** [comment]
While spurious selections are no longer reported in Windows Console, the terminal object is reported twice. This is likely due to faulty focus redirection:

* Temporarily removing the `consoleUIAWindow._get_focusRedirect` override introduced in #9674 suppresses the extra announcement.
* In a Python console invoked by pressing NVDA+control+z in Command Prompt, `nav.parent.focusRedirect == nav`, but `nav.parent.focusRedirect is not nav`.

Cc @feerrenrut @leonardder @michaelDCurran

**Comment by mohdshara** [comment]
could one of the admins re-open this so that someone can look into fixing it?

**Comment by leonardder** [comment]
This was erroneously closed with #10052.

**Comment by dingpengyu** [comment]
hi 
Does the current issue have a corresponding pr for testing?
thanks
