### ISSUE TITLE
Switching from SAPI4 to another synth still shows SAPI4 voices list

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10074]
### Steps to reproduce:
1. Select a SAPI4 synthesizer
2. From the speech panel, choose change, and in the synthesizer selection dialog, choose espeak.
3. Press ok
4. Go to the list of voices

### Actual behavior:
SAPI4 voices are shown

### Expected behavior:
ESpeak voices are shown.

### Explanation
SAPI4 also has a sync object that keeps a hard reference to the driver. I have a branch ready that fixes this, will pr it later today.

**Comment by Brian1Gaff** [comment]
Yes I knew this as well, but most Sapi 4 synths I have, ie the  bla bla in 
space, The Scandinavian English one and the via voice Eloquence almost sound 
alike have other issues  like saying things twice and  lagging, and that was 
before Python 3, so they were very seldom used these days
 I am at the moment trying to figure out why Speech platform seems to be 
ignoring the letter N!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by leonardder** [comment]
While I'm happy to fix this issue, I really feel like treating SAPI4 has 
obsolete technology. We can note that in our user guide.

**Comment by zstanecic** [comment]
Hi Leonard,

I am against this, as still there are people who use these synths

**Comment by leonardder** [comment]
That might be true. There are also people still using Windows XP. 
Sometimes, people are just sticking with a piece of software because 
they can. If we can no longer ensure the quality of our SAPI4 driver and 
people will start suffering from issues, they will find out that there 
are enough alternatives available to choose from which are actively 
maintained and/or supported. If they really can't make the switch from 
the older synthesizer, they would have to stick to an older version of NVDA.

**Comment by zstanecic** [comment]
No Leonard,

That’s called the accuracy of the synth.

The modern synths like vocalizer are not so responsive and they interpret abbreviations where these shouldn’t be read.

For example, the polish people will never switch from syntalk to something modern, just because it speaks polish in the most accurate way, although this synth is no longer maintained like eloquence.

The Croatians want to use WinTalker voice, yet another synth, just because of vocalizer reading abbreviations in the wrong context, and just because of accentuation issues.

There’s of course codefactory vocalizer, where some issues were fixed, but there were still abbreviations and strange readouts.

The same is with the microsoft one core voices

Personally i can use vocalizer, and i am testing and reporting bugs to CF.

One core voice has the problem in all available languages.

They try to put english just everywhere, which makes the synth useless, because it breaks pronounciation. 

I am against the alternatives, if these offer the wrong language pronounciation. That’s lso the reason why english people, and maybe another native speakers prefer older synths or eloquence.

For croatia, i can report that wintalker sapi 4 and vocalizer are used in the wild.

**Comment by zstanecic** [comment]
But...

If you don’t want to treat sapi 4, why don’t remove it like freedom scientific did, and or bundle the driver in an NVDA add-on and give it to the community?

The problem with sapi4 is that it is still compatible at the OS level, so it can be even installed in the new systems easily.
