### ISSUE TITLE
NVDA should render the label for a figure element in the virtual buffer

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#10083]
### Is your feature request related to a problem? Please describe.

Yes. The 2019 internet health report contains several articles that have visualizations of problems. The authors also provide descriptions via aria-label on the figure elements for these graphs, but NVDA does not render these. An example can be found in [this article](https://internethealthreport.org/2019/women-journalists-feel-the-brunt-of-online-harassment/).

1. Find the Heading 3 that is titled "Hostility to women in online news comments on The Guardian (2006-2016)".
2. Arrow down.
   * NVDA will jump straight to the female male ... gibberish text.
3. Go back up to the heading and examine the next children and siblings with object inspector, or use an inspection tool like the Firefox HTML inspector.
   * There is a figure element near the heading that contains an aria-label with a thorough and carefully crafted description of the graph. NVDA reads it when object nav finds the element.

### Describe the solution you'd like

NVDA should notice if the author put an effort into labeling the figure element like this and provide the text in the virtual buffer, like it does with graphics.

### Describe alternatives you've considered

Don't see any, if you don't know the description is there, you don't know where to look for it.

**Comment by g1nkgo** [comment]
Is this a new issue for you? We recently started having trouble getting NVDA to read alt-text for images in PDFs.

**Comment by MarcoZehe** [comment]
It is the first time I've seen someone use the figure element in HTML and trying to make it more inclusive, and NVDA failing that attempt. I had not seen the figure element used like this in the wild before. Your PDF issue is very likely something different, since I am talking about HTML on the web. PDF renders from a different code path.

**Comment by leonardder** [comment]
The way figure is most of the time, is like this as far as I know:

```
<figure>
<figcaption>some caption</figcaption>
... figure data
</figure>
```

In this case, the caption is visible. In the aria-label case, the caption is not.

**Comment by bramd** [comment]
@MarcoZehe Just tested this in Chrome. If you give the figure a `role=img` it works as expected.

I think the underlying problem is that a figure is now just treated as a block element without any semantic meaning (e.g. as a div). And yes, sometimes it is useful as a container, for example if this SVG chart would have ARIA markup to let it render as a table or if people just put an img and a figcaption in the figure. So, I think it is fair to expect that HTML authors should add a role attribute to hide the SVG subtree and let it work as an image.

That being said, it would be nice if figure has it's own semantic meaning and is treated as a container by default. So, you would get the aria-label in this case (figcaption would be nice as a label as well) and the message that this is a figure, but you would also get the whole subtree, the gibberish in this case. If we treat figure as a proper group, you could just skip over the irrelevant subtree with NVDA's hotkey to skip past the end of the container.

I would like to see this improved. A good article about figure and some screen reader/browser testing results is here: https://www.scottohara.me/blog/2019/01/21/how-do-you-figure.html

**Comment by leonardder** [comment]
I'm working on support for groupings in browse mode. The test case given by @MarcoZehe now reports its label. Its role is grouping.

I wonder whether we should treat these as graphics, or introduce a new figure role.

**Comment by bramd** [comment]
@leonardder Figures don't have to be graphics, so I think we need a new role.

Example:

```
<figure>
  <code>import this</code>
  <figcaption>Example 1: importing the most useful Python module ever</figcaption>
</figure>
```
