### ISSUE TITLE
Stop add-ons from preventing NVDA being reset to factory defaults

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10131]
### Is your feature request related to a problem? Please describe.
I recently went to reset NVDA to factory defaults.  Pressing NVDA+control+r once reset to saved configuration, but pressing three times did nothing.  I had add-on updater and focus highlight add-ons installed.  Looking at the log, it had:

DEBUG - addonHandler._getAvailableAddonsFromPath (10:45:49.650):
Found add-on focusHighlight - 6.3. Requires API: (2014, 1, 0). Last-tested API: (2020, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (10:45:49.650):
Disabling add-on focusHighlight
DEBUG - core.resetConfiguration (10:45:49.651):
initializing speech
ERROR - keyboardHandler.internal_keyDownEvent (10:45:49.773):
internal_keyDownEvent
Traceback (most recent call last):
  File "keyboardHandler.pyo", line 178, in internal_keyDownEvent
  File "inputCore.pyo", line 421, in executeGesture
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "inputCore.pyo", line 145, in _get_script
  File "scriptHandler.pyo", line 72, in findScript
AttributeError: 'NoneType' object has no attribute 'display'

### Describe the solution you'd like

Focus Highlight caused a problem when trying to execute that third keypress.  I'm not so interested in what broke with focus highlight here as in whether we can set NVDA to prevent an add-on from breaking particularly resetting to factory defaults - since a misbehaving add-on is a quite plausible reason why someone might be trying to reset to factory defaults in the first place.

### Additional context

Using NVDA 2019.2 and the most recent version of focus highlight - 6.3 I assume (I did remove it after that and before writing this up).

**Comment by JulienCochuyt** [comment]
Maybe I am missing some sleep, but I can't seem to see how the provided log states focusHighlight as the culprit here.
The error occurred in `scriptHandler.findScript` when trying to access `braille.handler.display` while `braille.handler` was `None`, hence *during* configuration reset.

The log states "initializing speech", and NVDA is probably still doing so when the error occurs.
Otherwise, the log would state next "Initializing braille".

So, to my humble understanding, the problem here is either that:
 - we do not terminate or hold off the `inputCore` during configuration reset.
 - we do not watch against `speech.initialize` taking too long.

If I'm missing the point here, please feel free to criticize my analysis.

**Comment by lukaszgo1** [comment]
I've recently experienced the same error as the one from the initial commend on a clean NVDA config without any add-ons installed, so while the issue as such is valid its title should be changed  unless @Qchristensen has any substantial evidence that this has been caused by the Focus Highlight add-on.

**Comment by Qchristensen** [comment]
It was in conversation with someone else that the suggestion of it being the add-on preventing this from working.  I can't recall the details now or what evidence there was - so on that I'd be happy to close it.

Since @lukaszgo1 can repro without add-ons there must be an issue in some situations.  Given the confusion, it might still be best to close this issue and for someone who can currently repro the issue to write up a new one with a more useful log also.
