### ISSUE TITLE
User suggestion: Add information on control+alt+n keystroke to start NVDA to the Commands Quick Reference

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10154]
### Is your feature request related to a problem? Please describe.

The commands quick reference lists NVDA keystrokes.  It does not currently list control+alt+n, the default keystroke to start NVDA.

This is noted in the User Guide (Under installing NVDA):
"3.2.3. Create Desktop Shortcut (ctrl+alt+n)
This option allows you to choose whether or not NVDA should create a shortcut on the desktop to start NVDA. If created, this shortcut will also be assigned a shortcut key of control+alt+n, allowing you to start NVDA at any time with this key stroke."

### Describe the solution you'd like

Add a line in the "Basic NVDA Commands" table in the User Guide (which would then be copied into the Commands Quick Reference) with the details:

Name: Start NVDA
Desktop key: control+alt+n
Laptop key: control+alt+n
Touch: none
Description: Starts NVDA.  This command requires the shortcut to have been created when installing NVDA (See Installing NVDA).

### Describe alternatives you've considered

This information was requested by a user who looked in the commands quick reference, expecting all NVDA (related) commands to be listed.  It is in the User Guide, although a user may, logically, expect it to be listed with the Basic NVDA Commands (near Quit NVDA for instance).

**Comment by XLTechie** [comment]
On Tue, 27 Aug 2019, Quentin Christensen wrote:

> Add a line in the "Basic NVDA Commands" table in the User Guide (which would then be copied into the Commands Quick Reference) with the details:
> 
> Name: Start NVDA
> Desktop key: control+alt+n
> Laptop key: control+alt+n
> Touch: none
> Description: Starts NVDA. This command requires the shortcut to have been created when installing NVDA (See Installing NVDA).

May I suggest replacing the word "Starts" there with "Starts or restarts"?

> This information was requested by a user who looked in the commands quick reference, expecting all NVDA (related) commands to be listed. It is in the User
> Guide, although a user may, logically, expect it to be listed with the Basic NVDA Commands (near Quit NVDA for instance).

Actually, as the first thing you have to do to even use NVDA, it would seem 
reasonable to me that it be listed before any other commands.

**Comment by Qchristensen** [comment]
Both good points.

**Comment by DrSooom** [comment]
CTRL+ALT+N is a Windows hotkey to launch shortcut icons on a desktop. It's not a NVDA specific hotkey. You also cannot change that hotkey via the Input gestures Dialog, because it's a Windows feature. You can only change it by opening the preferences dialog of the NVDA desktop shortcut. Therefore I suggest a separate section in the Commands Quick Reference html files for that Windows hotkey – otherwise users could think that they can change it via the Input Gesture Dialog as well – like they can do it for all the other hotkeys.

Maybe a new entry called "Restore NVDA desktop shortcut" in the Tools NVDA submenu wouldn't be bad too. But that would be another issue.

**Comment by Adriani90** [comment]
I wouldn't add this shortcut to command quick reference because it is deppendent on a condition, namely if the user enabled this at installation or not. If not, the shortcut would appear in the command quick reference and users might think it would work though. The command quick reference fetches the commands from the user guide, but txt2tags does not have a possibility to define a link between installer and user guide to decide when to fetch a command and when not.

@leonardder please correct me here if I am wrong.
Otherwise I would vote for closing this issue.

**Comment by Qchristensen** [comment]
My original suggestion (with the amendment suggested above by @XLTechie and also the addition of the word "Windows") of the command description:

"Starts or restarts NVDA. This Windows command requires the shortcut to have been created when installing NVDA (See Installing NVDA)."

I think covers the provision that it is a Windows shortcut you can't edit in NVDA's input gestures. I think it is worth including on the basis that not only does it start NVDA but also restarts it.  I would put it at the start of the Basic NVDA Commands Table (the first table in the document) - It's really the only Windows command we would include in the document, so I don't think it warrants its own table.

**Comment by XLTechie** [comment]
Addressing @Adriani90's comment: if we did not include commands because they 
might have been changed in some way, we wouldn't include any commands.
Does it really matter if the command could have been changed because the shortcut 
was edited, or some other command has been changed because another user of that 
computer re-mapped something in gesture config?

The manual and quick keys are a static document, making reference to a 
potentially dynamic set of key assignments. There is no guarantee that they will 
ever be listed correctly, only a best effort, most vanilla installation 
description of what can probably be expected.

So saying that we shouldn't include it because it might be inaccurate, is not a 
reasonable argument to me.

Considering that it is a Windows shortcut and not an NVDA command is more valid, 
but still not valid enough to negate this need IMO. Users want to know how to 
start the screen reader, and the quick keys list is where they go to find that 
kind of information first.

We should be happy that someone wants to try NVDA, and is attempting to find 
that information. Make it easy for them. It's a one-off, and doesn't hurt the 
document beyond including a "related" command in a list of "actual" commands.

This is a case where technical perfection should lose to ease of use for inexperienced users.

@Qchristensen you could consider changing "the shortcut" to "a desktop 
shortcut", which might make some more happy with the wording.
