### ISSUE TITLE
UIA Terminal: If the previous line output is less than two characters, output isn't spoken

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#10166]
### Steps to reproduce:

1. Open a python interpreter.
2. Write a sentense like this:

```python
x = 455
```

3. Show the result of _x_ by typing `x` and pressing <kbd>Enter</kbd>.
4. Change the value of _x_ to 45 and repeat the previous step.

### Actual behavior:

If you output x with the value of 455, the output is read out by NVDA, but 45 is not read.

### Expected behavior:

Both outputs have to be spoken.

#### NVDA installed/portable/running from source:

NVDA installed.

#### NVDA version:

alpha-18488,4b53f876

#### Windows version:

Windows 10 Pro 64bits Version 1903 (Build SO 18362.295)

#### Name and version of other software in use when reproducing the issue:

Tested python 2 and 3 interpreters, but I think that this is unrelated to python itself.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by francipvb** [comment]
CC @codeofdusk try same steps with a CMD session and echo commands, same results.

Cheers,

**Comment by michaelDCurran** [comment]
This is true for both UIA and legacy terminal support. This must be some kind of regression in liveText.

**Comment by codeofdusk** [comment]
Likely related to #9673. We need to filter out very short announcements to prevent some typed characters from being reported twice.

**Comment by codeofdusk** [comment]
> This is true for both UIA and legacy terminal support.

@michaelDCurran Yes, since both inherit from `keyboardHandlerBasedTypedCharSupport`. See #9915.

**Comment by michaelDCurran** [comment]
I think the issue is that in keyboardHandlerBasedTypedCharSupport, 
_reportNewText is the thing that filters out the single characters in 
case they are typed characters, but  that method only receives 
individual lines, even if  the new text was made up of multiple lines.

For example, if I have a terminal with just one line:

```

mick@neutrino~$

```


Then I type:

```

echo x

```

and press enter, when pressing enter,  liveText detects two new lines 
all in one go:

```

x

mick@neutrino~$

```

However, it only speaks the final line, because the first is filtered by 
_reportNewText.


Somehow,  the filtering logic needs to be moved higher up, so that it 
only filters if the diff produces only one line, and that line only 
contains 1 or so characters. If there are multiple added lines in the 
diff, then it should not be allowed to filter.


My preference would probably be to perhaps add a _reportNewLines method 
which took the new lines, and called _reportNewText on each of them, and 
then it could be overridden to filter typed characters.

**Comment by XLTechie** [comment]
Can replicate in both beta and alpha.

-- 
Luke Davis
Moderator: the new NVDA Help mailing list! (https://groups.io/g/NVDAHelp)
Author: Debug Helper NVDA add-on (https://addons.nvda-project.org/addons/debugHelper.en.html)
