### ISSUE TITLE
Javascript .focus() not working with NVDA enabled.

### ISSUE THREAD

**Issue by invisiblebear** [nvaccess/nvda#10202]
### Steps to reproduce:
1.) With NVDA enabled, navigate to https://codepen.io/jacob-mitchell/pen/BaBxrKa
2.) Select the first button to set focus to that button (should have a red outline)
3.) Tab to the 3rd button that reads 'Press Enter' and press enter

### Actual behavior: 
Nothing happens

### Expected behavior: 
List of links is revealed and focus is set to 'Link 5'

***Note:** This works when NVDA is not enabled.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2

#### Windows version:
Edition:  Windows 10 Home
Version: 1903
OS Build: 18362.295

#### Name and version of other software in use when reproducing the issue:
Mainly Chrome:  Version 77.0.3865.75 (Official Build) (64-bit) but have seen in other browsers as well

### Other questions
I thought this might be a race condition where NVDA was slowing down the display of the elements somehow and the .focus() was called before the elements were visible but I added Interval to make sure the elements were visible before attempting to set the focus and it still does not work. 

#### Does the issue still occur after restarting your PC?
Yes

**Comment by Adriani90** [comment]
@invisiblebear what happens if you press nvda+8 before reproducing this issue? Does it still occur? There is a new feature in NVDA which prevents the system focus to move to focusable elements when navigating in browse mode. This is optional and can be enabled or disabled in the advanced settings of NVDA or by pressing nvda+8. Maybe it is disabled on your side and that's why the focus is not moved.

**Comment by invisiblebear** [comment]
@Adriani90 I just tired this with it both enabled and disabled and nether worked for me.

**Comment by invisiblebear** [comment]
I should also note that I looked at the logs and other than the normal info about system versions, there was no output when the button is pressed.

**Comment by leonardder** [comment]
Are you trying this with NVDA browse mode enabled or disabled? You can disable browse mode using NVDA+space. You can also disable browse mode on page load in NVDA's browse mode settings category.

**Comment by invisiblebear** [comment]
@leonardder 
I have tried this with both browser mode enabled and disabled and am getting the same result

**Comment by Adriani90** [comment]
If I understand this correctly, you put a display:none on the container and ignore the hidden pattern via JS, but maybe I totally missunderstood this. Actually I can reproduce this in every browser but only in browse mode. In focus mode NVDA always jumps to link 5. In browse mode nothing happens.
It might be caused by the display:none pattern here. Maybe @jcsteh has further thoughts to add here.

**Comment by jcsteh** [comment]
In browse mode, NVDA overrides space and enter to click; it does not pass enter through to the web page. This is because NVDA needs to be able to activate elements which do not support space or enter and it has no way of knowing whether an element supports this. If you force NVDA to pass the enter key through, this works as expected, even in browse mode. This should have a click handler as well as a keypress handler.
