### ISSUE TITLE
Support letter combinations for the character descriptions

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#10236]
### Is your feature request related to a problem? Please describe.
It's not related to a problem in the sense of a bug.
### Describe the solution you'd like
In German, don't know about other languages, digraphs and trigraphs (two or three letters representing one sound) have their own character description. This, oddly enough, applies to only ch (Charlotte) and SCH (Schule), as I just learned at school, but to make it even more correct, this is my proposition.
### Describe alternatives you've considered
I guess you could really spell, for example, sch as "Samuel Cäsar Heinrich" instead of "Schule", but it wasn't me who came up with this inconsequent way of this! Why "AU", "EU" and "EI" don't have a different character description? I personally don't really like this idea, but I like correctness, so there you have it.

**Comment by DrSooom** [comment]
See: https://de.wikipedia.org/wiki/Buchstabiertafel#Vergleichstabelle

The file "locale\de\characterDescriptions.dic" is responsible for double-press Numpad2. I'm not sure if it's possible to define two or three characters here because Numpad2 only speaks the characters right hand the cursor.

And as German is my mother tongue, I can ensure you that these two character bindings never ever came up in my whole school time – or I just have forgotten it. Maybe that could be the case in the primary school, as "ch" and "sch" were/are spelled together as "one single letter" (no changes within the last 25 years here in Austria), but at the secondary school I and II they will be spelled as c and h respectively s, c and h separately again. So you don't find these two descriptions (ch and sch) in the wild. Therefore: Won't fix.

**Comment by hozosch** [comment]
What about NVDA+Shift+Dot (laptop)? Don't know what the appropriate desktop layout key combination is. Anyway, it would make sense there.

**Comment by DrSooom** [comment]
Report current character in review: Numpad2 (Desktop), NVDA+. (Laptop)

CC: @Adriani90: Any thoughts about this?

**Comment by hozosch** [comment]
My comment was referring to the command to spell the line under the caret. I think it would make sense there.

**Comment by DrSooom** [comment]
To be honest, I read "Charlotte" for "ch" yesterday the very first time. And "China" is also differently pronounced in Germany (Chi-na) and Austria (Ki-na). And "Schule" might be still used in primary schools, but definitively not later. How words are spelled is different between the school levels and between children and teenagers/adults. If you want I can give you some examples, even if this would be a little bit off-topic.

Source: https://www.duden.de/rechtschreibung/China

**Comment by hozosch** [comment]
Well I am at the Blista in marburg (you may have heard of this School or been there yourself) and am In grade 11, in a school branch with the main area being economy and computer science. Anyway, in the subject you could translate to English as "secretarial practice", we looked at the phonetic alphabet, and also the international one, and ch and sch where given then. However, as I see, this isn't really a thing you necessarily have to take into account when you spell, so I'm going to close this now.
