### ISSUE TITLE
When using Word Object Model in Word/Outlook, NVDA freezes and stops the keyboard from responding

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10247]
Note, this issue is similar to --#6463. 
cc @bramd  @dkager 

### Steps to reproduce:
Work with Outlook mail composition or MS Word. Seen in Office 2016, 2013 and 2010 at least. There isn't a known way to trigger this behavior, which makes this hard to reproduce reliably.

### Actual behavior:
NVDA freezes and the keyboard is locked up in such a way that it is not possible to restart NVDA. The only way to break out of this situation is signing out and back in again, however this effectively means that you're losing data. As the keyboard is locked up, it is not possible to use alternatives, like running Narrator.

### Expected behavior:
No freezes.

### Comparison with #6463
Note that since #9208 was merged, the test case from #6463 still allows me to escape/restart NVDA. However in the Word/Outlook freezing case, there is really no other way to escape than sign out/in again.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
All recent versions of NVDA< for at least a year.

#### Windows version:
Several versions of Windows 10

#### Name and version of other software in use when reproducing the issue:
Office 2010, 2013, 2016

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

**Comment by DrSooom** [comment]
There is a way to kill the nvda.exe process and then hopefully correctly closing Microsoft Outlook:
1. Press CTRL+ALT+DEL and open the Task Manager. This should be still possible – as long as you don't try to restart NVDA by pressing CTRL+ALT+N. Perhaps CTRL+Shift+ESC for opening the Task Manager still works too, but the CTRL+ALT+DEL way is the secure one.
2. Now right click with the mouse on the process "nvda.exe" and kill it. This should be also possible – even if Shift, CTRL and ALT hang because of NVDA.
3. After the process was killed, close Microsoft Outlook with ALT+F4 (if possible) or again with the mouse (left click on the X in the top right corner of the window).
4. If this doesn't work, kill the process "outlook.exe" via the Task Manager too. Unsaved e-mail drafts will get lost by this method.
5. Now you should be able to start NVDA again via the desktop shortcut by pressing CTRL+ALT+N.

I changed the auto-save draft time to 1 minute in Microsoft Outlook especially because of this random, rare freezing bug.

**Comment by leonardder** [comment]
I've created a [try build](https://ci.appveyor.com/api/buildjobs/6gxag44qdqklqt73/artifacts/output%2Fnvda_snapshot_try-wordDebug-18705%2C4c105cec.exe) that adds lots of extra logging when at the debug level.

**Comment by dkager** [comment]
Since Ctrl+Alt+Del obviously still works I wonder if there is another such hotkey that you could assign a script to to restart NVDA. It would also be interesting to know if the mouse locks up as well.

**Comment by DrSooom** [comment]
The mouse clicks could be influenced by the held down/hanging Shift, CTRL and/or ALT key. But for opening the context menu in the Task Manager and for the click on an entry there as well as on a button in a dialog, it doesn't really matter here if these keys are held down or not. You are still able to move the mouse cursor and interact with the GUI – as long as the held Shift, CTRL and/or ALT keys make no differences. This would be the case if you left or right click on an application icon in the taskbar (e.g. starting a new instance, open the context/application menu instead of the Jumplist etc.).

See also: https://en.wikipedia.org/wiki/Control-Alt-Delete#Windows_NT_family

**Comment by bramd** [comment]
@leonardder Your last commit seems to cause an error while installing add-ons:

ERROR - gui.addonGui.installAddon (21:39:39.537) - MainThread (8712):
Error installing  addon bundle from C:\Users\bram\Downloads\bluetoothaudio.nvda-addon
Traceback (most recent call last):
  File "gui\addonGui.pyc", line 539, in doneAndDestroy
  File "gui\addonGui.pyc", line 560, in installAddon
  File "gui\__init__.pyc", line 900, in __init__
  File "threading.pyc", line 1077, in name
AssertionError: Thread.__init__() not called

**Comment by lukaszgo1** [comment]
Have you tried switching users with Ctrl+alt+delete, and killing NVDA process from the second account? For me it always works when freezes occurs, however  I haven't experienced this exact problem

**Comment by leonardder** [comment]
@lukaszgo1 That's an interesting approach!

@bramd The bug you reported has been fixed.

[Here](https://ci.appveyor.com/api/buildjobs/fnapav0bhafmeqnq/artifacts/output%2Fnvda_snapshot_try-wordDebug-18771%2C91aa7508.exe) is a new try build that also logs isCollapsed property properly. Note that I found #10276 because of your debug logs, that's not going to fix the issue though.

**Comment by bramd** [comment]
@leonardder After observing many crashes over the last week it seems we have some serious issues with COM. Using the logs I can't really pinpoint where it fails exactly. My opinion for now is that we need better logging and error handling in our COM clients.

Any idea where to start with this?

**Comment by leonardder** [comment]
To make sure, I assume you mean the comtypes com calls by NVDA, not the in process com calls?

I wonder what could possibly cause this. Could it be dynamic dispatch, or may be just an issue general to the Word object model?

In any case, I think it would help to start with having comtypes logging piped into NVDA"s log.

**Comment by leonardder** [comment]
cc @EngineeringMario: who reported several other instances of this issue lately

**Comment by leonardder** [comment]
> Since Ctrl+Alt+Del obviously still works I wonder if there is another such hotkey that you could assign a script to to restart NVDA.

The [Kill NVDA](https://addons.nvda-project.org/addons/killNVDA.en.html) by @tspivey can assist with this. Note that is still an workaround.

**Comment by Adriani90** [comment]
I think these crashes might occur more often if you have lots of mails in a folder or if there are many mails with lots of flags like invitations with attachments with importance flags, emails with other different flags such as replied, atributed preview, and and and.
My guess is that NVDA tries to fetch all the flags exposed by outlook for an email or an invitation and fails at some point, ending in a crash.
This was also hapenning in MS Word earlier when NVDA fetched all the text atributes while navigating in tables with ctrl+alt+arrow keys etc.
I think the solution is
1. Limit the flags which should be fetched from Outlook when pressing up and down arrow in the message list to the most important flags
2. Provide key strokes in the outlook appmodule for the flags which are not that important so that the user can request reporting of those flags when needed while navigating through the message list

or another way would be to limit the flags only to "read" and "unread" and all other flags could be displayed in a browseable window by pressing a key stroke on a specific message in the list.

**Comment by lukaszgo1** [comment]
This happens when editing not when accessing list of messages and also according to the description occurs in Word.

**Comment by Adriani90** [comment]
Please read the title and the conversation. Thanks.

 

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Mittwoch, 29. April 2020 20:40
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] When using Word Object Model in Word/Outlook, NVDA freezes and stops the keyboard from responding (#10247)

 

This happens when editing not when accessing list of messages and also according to the description occurs in Word.

**Comment by EngineeringMario** [comment]
We have quite a few customers suffering these problems while editing in Outlook or MS Word; Not really related to any version of office.
This moment we expect is is a language related problem. The first tests will show this. Later this week we will suggest customers to only use the original language version.
Within a few weeks we’ll know for sure.
We’ll keep you informed
 
Van: Łukasz Golonka [mailto:notifications@github.com] 
Verzonden: woensdag 29 april 2020 20:40
Aan: nvaccess/nvda
CC: EngineeringMario; Mention
Onderwerp: Re: [nvaccess/nvda] When using Word Object Model in Word/Outlook, NVDA freezes and stops the keyboard from responding (#10247)
 
This happens when editing not when accessing list of messages and also according to the description occurs in Word.

**Comment by bhavyashah** [comment]
@EngineeringMario  This is a friendly reminder to provide a status update to https://github.com/nvaccess/nvda/issues/10247#issuecomment-621447311. You had said you may be able to share your updated findings in a few weeks' time. In case there is any progress on that, please do share.

**Comment by feerrenrut** [comment]
@a11y-spl We have several fixes for these issues in our latest alpha builds, we aim for these to be included in the 2020.3 release. We would be very interested in knowing if you are experiencing separate issues not yet fixed. If you are comfortable testing these changes please see the snapshots page: https://www.nvaccess.org/files/nvda/snapshots/

**Comment by a11y-spl** [comment]
When is 2020.3 planned for release ?

Amitesh
________________________________

**Comment by DrSooom** [comment]
@a11y-spl: I guess NVDA 2020.3 will be released in October 2020. If you don't want to test the Alpha builds (as portable copies), then please wait for the first Beta of NVDA 2020.3. It will be visible on the above mentioned snapshot page as well. Or just keep an eye on the [NV Access News Page[(https://www.nvaccess.org/news/).

**Comment by a11y-spl** [comment]
Nope that did not work , excel is still freezing

Amitesh
________________________________

**Comment by Adriani90** [comment]
@a11y-spl or any one else, are you still seeing these crashes in MS Office 2016 or 365 with NVDA last alpha version? I cannot reproduce them anymore.

The last NVDA Alpha can be downloaded from this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
We didn't get any updates from people that were able to reproduce this since many years, I am closing as abandoned. Please feel free to comment on this if you are still having the issue and we can reopen.
