### ISSUE TITLE
precise Announcing of the state of formatting settings when a hotkey in word is pressed

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#10271]
### Is your feature request related to a problem? Please describe.
No, not in the sense of a bug. It's just something I miss.
### Describe the solution you'd like
In word, for example, when I press the keystroke for bold, I would like to have NVDA say "bold on". Or "bold off", depending on what it is set to currently.
### Describe alternatives you've considered
Of course, I could just do it and check formating using NVDA+f, but it's just easier this way. Also I have a more direct confirmation.

**Comment by CyrilleB79** [comment]
In MS Word many common shortcut action are already announced:

* the following shortcuts already announce the new character formatting when activated : bold (ctrl+B), italic (ctrl+I), underlined (ctrl+U), subscript (ctrl+=), superscript (ctrl+shift+=), character size change (ctrl+[, ctrl+], ctrl+shift+, and ctrl+shift+.).
* Moreover some paragraph formatting such as paragraph alignment (left, right, centered, justified), line spacing (ctrl+1/2/5)
* Style change to title and normal (alt+shift+left/rightArrow, ctrl+alt1/2/3 and ctrl+shift+N) are also announced.

Can you give more information to investigate why ctrl+B does not allow you to hear bold on or bold off? This may be due to a localization issue.

* NVDA language
* NVDA version
* Word language (the language of the menu/ribbon items and dialog boxes)
* Your keyboard layout = keyboard language

**Comment by JulienCochuyt** [comment]
@CyrilleB79: I think you are right in guessing this might be a language issue.
Keyboard shortcuts in Word are often localized by country.
By example, bold is `control+b` on an English system, but `control+g` (for "gras") in a French system.
I confirm NVDA 2019.2 reports toggling of the bold attribute just fine on a French system.

**Comment by hozosch** [comment]
Yes, I can confirm that the keys you mentioned report the current settings, whether they're enabled or not. However, I mean the keys to toggle the settings. For example, when I want to toggle bold, In german, it's ctrl+shift+f for "fett", and this isn't announced, like it is in jaws.

**Comment by ruifontes** [comment]
Hello!

This must be corrected by the NVDA german localization team.

Rui Fontes


Às 10:52 de 24/09/2019, hozosch escreveu:

**Comment by hozosch** [comment]
Can we? I think we can only change the message, but not the keystroke for which the message is used.

**Comment by Adriani90** [comment]
This would only work if we localize the gesture.ini. Right?

**Comment by CyrilleB79** [comment]
Yes we can localize the gesture.ini.
To localize it, translators should add (if required) and modify the gesture.ini file in the screenreadertranslation repo.
E.g. in the case of German, translators need to add the gesture.ini (taken from last alpha) since it is not present in the repo. Then they need to:

* Add the shortcuts that differ from English ones
* Map to None the shortcuts that do not match any other shortcut

It seems that German gestures.ini file has not remapped the word shortcut whereas they seem to differ a lot from English ones according to: https://www.wintotal.de/tastenkombinationen-word/

Translator can take example on French gestures.ini file to add the section for word shortcuts.

**Comment by ruifontes** [comment]
Right!
And that is possible...

Rui Fontes


Às 11:45 de 24/09/2019, Adriani90 escreveu:

**Comment by hozosch** [comment]
Yes. thanks for that, I didn't know that. I'm going to close this now.

**Comment by hozosch** [comment]
I reopened this, because for NVDA, superscript and subscript arekinda one thing. That's not the case with word. Superscript is, for us German, CTRL+plus, and subscript ctrl+dash.

**Comment by hozosch** [comment]
I would also like NVDA to distinguish between double and single underlining. Currently, there's just one underlining action programmed into NVDA. Single underlining for us is ctrl+shift+u, double ctrl+shift+d. At the time being, I just used both keystrokes to announce the normal underlining

**Comment by hozosch** [comment]
Sorry, the thing about superscript and subscript was my fault. Could you please add the distinguation between double and single underlining though?

**Comment by CyrilleB79** [comment]
For now NVDA only announces single underlining shortcut, even in English. That's why NVDA does not announce any detail when you map toggleUnderline script to the shortcut for double underlining.

I am currently working on some word shortcut vocalization and have specially a branch regarding announcement of various types of underlining that have a shortcut in Word, i.e. double underlining (ctrl+shift+D) as well as word-only underlining (ctrl+shift+W).
I may provide a PR to fix this issue soon. However, maybe you should modify a little bit the description of this issue to give more details, i.e. the missing shortcuts.

**Comment by hozosch** [comment]
Sorry, It would seem that I can't edit my first comment, so here I go.
Shortcuts missing:
smallcap (ctrl+q)
All caps (ctrl+g)
Those are the only ones I could think of! like I say, superscript and subscript was my fault. I didn't know NVDA summarized it, until I found out that you can define multiple keys.

**Comment by CyrilleB79** [comment]
Underline description branch is now ready.

Regarding allcaps and smallcaps, the shortcuts that you have given are probably German ones; English ones are Ctrl+Shift+A and Ctrl+Shift+K. I had also begun a test branch some time ago with these shortcuts. However, I have still to investigate Word's behavior. Indeed, there is another shortcut that plays with capitalization, Shift+F3, but that differs slightly from Ctrl+Shift+A.

**Comment by hozosch** [comment]
O yes, didn't know about shift+f3,  but yes, that's first initial cap.

**Comment by XLTechie** [comment]
CyrilleB79 wrote:

> maybe you should modify a little bit the description of this issue to give more details, i.e. the missing shortcuts.

And to correct the spellings in the title as well, to make it easier for github 
to match it against similar issues, or people to find it.

"Anounce" = "Announce", and "formating" = "formatting".
Also "formating" to "formatting" in the title of the related issue: #10271.

**Comment by hozosch** [comment]
I changed the title now. Like I said, I can't edit my first comment anymore. When I change the title, it should be overridden, schouldn't it? So, don't know what's wrong with that now.

**Comment by Adriani90** [comment]
@CyrilleB79 which shortcuts are still remaining to be verbalized?
By the way, it seems Turning on underline double by ctrl+shift+d is announced properly, but turning it off is announced as if it was single underline.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 which shortcuts are still remaining to be verbalized?

The only formatting reporting shortcut listed in this thread that has not been implemented in #17197 is `shift+f3` (cycling through various capitalization modes) and its equivalent in Outlook only `control+A`. See #17197, "Known issues" paragraph for more details.


> By the way, it seems Turning on underline double by ctrl+shift+d is announced properly, but turning it off is announced as if it was single underline.

Note that toggling underline double has been correctly implemented in #17197 only. Thus it is available in last alpha builds only (landing in 2025.1). Moreover, it is only working in English or in other languages using the same shortcuts for now; the translators (maybe in collaboration with developers) will have to translate the gestures before 2025.1 if these gestures differ from the English ones.
