### ISSUE TITLE
Input gesture name for NVDA+b command is not obvious

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10301]
### Is your feature request related to a problem? Please describe.

A user asked what the command was called that was invoked with NVDA+b as they could not find it in the Input Gestures dialog.

In the User guide, it is listed as:
Name: Read active window
Description: reads all the controls in the currently active window (useful for dialogs)

In the Input Gestures dialog, it is "Speaks the current foreground object".

### Describe the solution you'd like

Change the description in the Input Gestures dialog to something like "Reads active window" or "Reads all controls in the active window".

Aside from anything else, the current name is not actually correct as it does read the whole active window and not the active object (open WINVER, leave the focus on the OK button and press NVDA+B - it reads the dialog even though the active object, is that OK button).

**Comment by JulienCochuyt** [comment]
> A user asked what the command was called that was invoked with NVDA+b as they could not find it in the Input Gestures dialog.

This user could be, as #10302 is not (yet) implemented, advised to use the Input Help to obtain the name of the command bound to any key.

Besides, I agree the naming of this command might be confusing.

**Comment by Qchristensen** [comment]
Good point - I did mention that to the user (as well as the exact wording to search for).

Just for anyone else - the wording of a command in the input gesture dialog is the same as that used when you press a keystroke which invokes that command with Input help on.

**Comment by Brian1Gaff** [comment]
This has come up before. I find this feature very illuminating. It seems to 
be able to at least indicate text on the screen and read it in situations 
where none of the navigation modes seem to be able to get at it. This is a 
pity because some very non standard applications operate some unmarked 
options just by clicking on text which is not apparently active. The latest 
Klite codec pack installer is like this. The only way to be sure these bits 
of software can be used is let a sighted person do it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
