### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10317]
Hello. I would just like to put these feature requests out there.

1. In browse mode, the option to wrap around when searching for elements such as edit boxes and level 2 headings etc. For example,, I will often want to go to the first edit box but when I press "e" I then discover that the browse focus is underneath it and I'll hear 'no next edit field'. I may then have to shift-e three times to get back to the first box, or otherwise do something to get the focus above it, before pressing "e" again. A wrap-around option would make life simpler here.

2. The option to have a pause between the reading out of different kinds of information relating to an item (the name, the menu key, its place in the list etc). I sometimes have to listen twice as the information runs into eachother. So for example, read "Anne ... a" rather than "Anna", and "pic 3 ... 2 of 7" rather than "pic3 2of7"

3. When mousing over the settings on an option screen, also include the shortcut key. I will often hover over a few sections until I hear the one I want to interact with, such as, for example, the pitch settings for your NVDA voice. But I then have to go the long way around, tab-tab-tabbing to get to that control in order to discover that the shortcut key was alt+e (for example). Whereas if I had been told alt+e on the initial mouse hover I could get there straight away.

4. An option to force NVDA to read the tooltips associated with an object even if they haven't appeared. For example in FreeFileSync if I tab through some of the options it'll just state "button". Whereas if I hover over that button a tooltip explaining what it does appears. But with less than perfect eyesight I'd rather not have to rely on judging that I am aiming correctly onsome of the smaller buttons I come across. I would prefer the option to force tooltip-reading for buttons I have tabbed to if they contain no otherdescriptive text (or even if they do).

5. Ability to use browse mode in the Win10 settings app.

Thanks.

**Comment by josephsl** [comment]
Hi,

Item 1: ah, wrap around mode. You are not the first one to suggest this, and I believe we had a discussion about it a while back.

Item 2: pauses between control properties. You might not be the first one to suggest this - I'm hoping that things being done in alpha builds at the moment would make this a reality one day.

Item 3: include hotkeys when mouse hovers over options. This depends on figuring out how to do this using the GUI toolkit we are using (wxWidgets).

Item 4: tooltip announcement when mouse hovers. Have you tried enabling tooltip announcement in NVDA (NVDA Settings/Object presentation)? If yes but if NVDA isn't announcing this, chances are that NVDA may or may not have built-in support for this yet.

Item 5: browse mode in Windows 10 Settings app. A bit tricky because apps like this does not expose the fact that they are browse mode capable at the moment. A while back there was a discussion about bringing browse mode support for universal apps but it never progressed from just brainstorming then. Since this is my area of research, I recommend first trying out Windows 10 App Essentials add-on and see if that makes a difference (perhaps not, but won't hurt to try).

As for item 5, based on recent posts, I assume this came from Narrator, correct? If yes, it wasn't until Version 1809 that this became more prominent, meaning this feature, if implemented, cannot be backported to older Windows 10 feature updates easily (Version 1803's Settings app does expose more relevant information, but at this time, I'm staying away from that version because it is nearing end of life).

Thanks.

**Comment by JulienCochuyt** [comment]
Item 1 - Wrap around: Would indeed be nice to implement both for quick nav and incremental search.
Would probably benefit from a sound hint rather than a textual announce (We took that path in WebAccess.)
An alternative approach might be first press "no more" / next press "wrap around"

Item 3 - Hotkeys announce on mouse hover. @josephsl doing it specifically for NVDA's GUI would take some effort, but is definitely feasible. Question is, could we take a broader path and attempt to provide it for most other GUIs? That would indeed be pretty useful for low vision users (Preaching for my own church here...)

**Comment by DrSooom** [comment]
@TechHorseG: Could you please open a new issue for each feature request because then these issues can be fixed in a more accurate way. Thanks.

Related: Issue #4637

**Comment by TechHorseG** [comment]
Yes, sorry. Will post a separate thread for each one, very shorttly.

**Comment by DrSooom** [comment]
@JulienCochuyt: Did you tried to press and/or hold the ALT key on such dialogs? Normally the shortcut key letter/digit/symbol should be displayed underlined in the GUI after pressing the ALT key once or only as long as the ALT key is held. In Microsoft Office 2010 these characters are displayed in squares after pressing the ALT key once. And perhaps there could be still the function in Windows 10 to display these characters all the time underlined – without having to press/hold the ALT key first.

**Comment by TechHorseG** [comment]
I have now started new issues for 2, 3 & 4. I'll leave the others as it seems they have already been discussed.

@DrSooom, I am sure you are correct but I'd probably give myself eyestrain if I attempted to see which of the characters was underlined :)

 @josephsl perhaps I wasn't clear. The new issue I raised for the tooltip request is hopefully clearer.

**Comment by DrSooom** [comment]
@TechHorseG: Thanks. Could you please edit the issue title of this issue here as well? Personally I would suggest to just talk about your first feature request point here in more detail.

Quote from [issue #4637](https://github.com/nvaccess/nvda/issues/4637#issuecomment-538052856):
> Is it possible to add a beep tone if no further result could be found and only if you press NVDA+F3 or NVDA+Shift+F3 again it will then jump to the first/last result? This is currently the method how the default object navigation (swipe one finger to the left/right) in TalkBack on Android 9 works.

It should be the same behavior on jumping between the first and last element in browse mode too – but as an option, which should be disabled by the user if he prefer speech output. Maybe we would need two checkboxes: one for the jumping and one for the beep tone instead of speech output on reaching the first/last element.

**Comment by josephsl** [comment]
Hi, actually, I’m in favor of closing this one and recommending people to fill out the template. Thanks.

**Comment by DrSooom** [comment]
@josephsl: Yep, that might be better. As far as I see it's quite seldom that someone opens one issue for multiple bugs/feature requests. So splitting them all in separate issues and closing the source issue seems to be the better solution – especially for historical reasons.

**Comment by josephsl** [comment]
Hi,

Closing. Also, in the future, please fill out the new issue template.

Thanks.

**Comment by XLTechie** [comment]
Julien Cochuyt wrote:

> Item 1 - Wrap around: Would indeed be nice to implement both for quick nav and incremental search.
> Would probably benefit from a sound hint rather than a textual announce (We took that path in WebAccess.)
> An alternative approach might be first press "no more" / next press "wrap around"

I like the second idea, although both are good.

**Comment by JulienCochuyt** [comment]
> @JulienCochuyt: Did you tried to press and/or hold the ALT key on such dialogs? Normally the shortcut key letter/digit/symbol should be displayed underlined in the GUI after pressing the ALT key once or only as long as the ALT key is held. In Microsoft Office 2010 these characters are displayed in squares after pressing the ALT key once. And perhaps there could be still the function in Windows 10 to display these characters all the time underlined – without having to press/hold the ALT key first.

@DrSooom thanks for the suggestion, but the point here was not to have the accelerator key displayed, but rather announced by NVDA on mouse hover (and ideally marked in braille too when review follows the mouse pointer)
