### ISSUE TITLE
Zemana AntiMalware flagging many NVDA components as suspect

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#10327]
This is not a bug report, per se, but something I believe you all should be aware of.

Zemana AntiMalware, while not nearly as popular as Malwarebytes, does have a significant user base.   I just installed the free version of Zemana this morning.  When a scan is run with it there are over 15 components of NVDA that are flagged as suspicious and would be quarantined.

I know and you know that this is not the case.   Someone from NVAccess may want to reach out to the folks at Zemana to have them do whatever they need to do to remove NVDA components from being detected as potentially malicious and subject to quarantine.

I installed the free version, available here:  https://www.zemana.com/?ref=producthunt

**Comment by DrSooom** [comment]
The Installer for NVDA 2019.2.1 is clean. [VirusTotal result](https://www.virustotal.com/gui/file/74fce142622c83124c0bcf2378830c8e6650eee0dead32769976a8ea13a2d165/summary)

Perhaps a false positive by Zemana AntiMalware (due to heuristic). If you are using Windows 10, you can disable Zemana AntiMalware, enable the Windows Defender and scan NVDA's program folder. btw: In most cases the Windows Defender, which is part of Windows 10, is now enough for private users.

**Comment by britechguy** [comment]
I understand that it's a false positive, which is why I reported it here.

It is generally the developers of a given product that, if they reach out to the folks who make these scanners, get the quickest results in getting the false positives resolved.

I only use Zemana or Malwarebytes very rarely, and this is the first that I've encountered Zemana identifying anything NVDA related as suspect.

**Comment by Adriani90** [comment]
cc: @Qchristensen

**Comment by Qchristensen** [comment]
I've contacted Zemena and will hopefully hear back, or at least hopefully they will update their database.  Thanks for the heads up!

**Comment by britechguy** [comment]
You're quite welcome.  If the folks from Zemana actually respond I would appreciate knowing that.  Responsiveness to issues such as this does make a difference in what products of a given class I am inclined to recommend.

**Comment by Qchristensen** [comment]
Will do.  I did get an email about 10 hours after I wrote to them.  Although it is just a "we'll get back to you" email, it does appear to be from a human rather than simply auto-generated:

New reply for the ticket #HC00032067
 
Hello Quentin,

Thank you for reporting this.
Your submission is being reviewed by our malware analysis team. As soon as we have more information, we will let you know!

We appreciate your understanding and patience!


Armagan Tugsal

**Comment by Qchristensen** [comment]
I got another email from Armagan:

"Hello Quentin,

Your submission is indicated as false positive and will be whitelisted in next virus definition updates.
Thank you for your understanding."

Are we happy to close this issue now, or would you like to confirm the fix when the next version of Zemana comes out @britechguy before closing?

**Comment by britechguy** [comment]
I'll give Zemana another run after manually "de-whitelisting" the NVDA elements I told it to exclude and report back.

**Comment by britechguy** [comment]
Just ran a Zemana scan a few moments ago and no NVDA components are being flagged.  I removed all previously flagged components from my own list of exclusions prior to running the scan, so they would have been checked.   I will try using the "Close and comment" button, but am not sure whether I have the ability to actually close the report or not.  Everything seems to be resolved.
