### ISSUE TITLE
Language and voice instead of voice and variant

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#10373]
### Is your feature request related to a problem? Please describe.
No, it's not something I'd call a bug. It's just something I would like to change.
### Describe the solution you'd like
Instead of choosing between voices and variants in ESpeak, I would like to select between language and voice, especially now that languages in ESpeak have been moved to the "lang" directory in espeak-ng-data. It's more obvious that way in my opinion. The variant setting only makes sense for the vocalizer addon, to select between the qualities.
### Describe alternatives you've considered
This is where I would like to ask a question. Who prefers the current way?

**Comment by Brian1Gaff** [comment]
Well its always been the way it is. I that what has happened in Espeak is 
that we have  dialects and voices. Thus you have, say English but you have 
Scottish east midlands etc as dialects then voices which are variants.
 I'd be happy to see some renaming as long as we do not loose dialects in 
the process.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by hozosch** [comment]
The dialect is already included in the name, for example English - lancaster or English - west midlands. So, you have no worries there.

**Comment by Adriani90** [comment]
In eSpeak there are variants which are much more pleasant to work with than others (i.e. compare variant Quinssi or variant Linda.
The common terminology between all screen readers is to use voice as language (i.e. deutsche Stimme, german voice). Even in Voice Over. So I would keep this terminology still since all people are using it.
I am closing. But if you need more opinions, please discuss this on the users mailing list.
