### ISSUE TITLE
NVDA will not read grid cells while using Chrome

### ISSUE THREAD

**Issue by blm126** [nvaccess/nvda#10447]
### Steps to reproduce:
1. Open https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html in Chrome with NVDA running.
2. Attempt to navigate one of the grids using arrow keys

### Actual behavior:
NVDA reads "selected" for every cell

### Expected behavior:
NVDA reads the contents of the cells.

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
2019.2.1

#### Windows version:
10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:
Google Chrome 78

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Installed version was tested and did not have an issue.

**Comment by JulienCochuyt** [comment]
I'll assume you swapped "Actual behavior" and "Expected behavior". (If so, please correct the issue summary)

I do not reproduce on Windows 10 version 1903 (18362.418) with an installed NVDA 2019.2.1: The cells of the three grids are read just fine.
Might be an issue specific to portable version.
Have you tried disabling add-ons?
Would you have the possibility to test installing NVDA?

**Comment by blm126** [comment]
I have tested the installed version and I can't reproduce it there. My original bug is now updated to make it clear this is apparently specific to the portable version.

**Comment by Adriani90** [comment]
@blm126 are you still hhaving this issue with NVDA 2023.2 in Chrome 117?

**Comment by Adriani90** [comment]
I cannot reproduce with NvDA 2024.1 Beta 9 in Chrome 122. I am closinng as works for me. If you are still having this issue, please comment and we can reopen.
