### ISSUE TITLE
Support opening the Elements List dialog in focus mode

### ISSUE THREAD

**Issue by JulienCochuyt** [nvaccess/nvda#10453]
### Is your feature request related to a problem? Please describe.

The Elements List dialog can currently be opened (with `NVDA+F7`) only when in browse mode.
It is confusing for beginners, and uselessly tedious for more experienced ones.

### Describe the solution you'd like

Support invoking it when in focus mode too.
I guess the lesser impact UX would be to switch to browse mode when invoking the dialog from focus mode.

### Additional context

PR on its way.

**Comment by DGartmann** [comment]
In Word 365, I have a document where this, apparently, doesn't work when I just open the document via File Explorer. I get a message asking me if I want to  turn off autocorrect suggestions (my quick and dirty translation from Danish). 

The work-around seems to be switching to Browse mode and back to Focus Mode. After that, I can open the elements list just fine from within Focus Mode.

 Is this expected behavior?

**Comment by DGartmann** [comment]
I am running NVDA 2020.4 beta 1.

**Comment by Sylvie42** [comment]
I have the same issue with Word and Office 365, NVDA 2020.4 beta 1 on Windows 10. 
After opening the document and pressing nvda+F7, I get the suggestions list for mispelled word, as if I had pressed f7 key.
After entering browse mode with nvda+space and pressing nvda+F7, the elements list appears correctly.
Returning to focus mode and pressing nvda+f7 again displays the elements list correctly.

**Comment by DGartmann** [comment]
This is still happening in beta 4 of NVDA 2020. Just noting this down here so I don't forget. Hope it can be dealt with at some point.

**Comment by Qchristensen** [comment]
Confirming I can replicate this issue.  No error or anything is recorded in the log.  For neatness, I've written up a new issue: #12050.

I think we can leave this issue closed (the feature has been implemented), but move any new conversation on the Word isssue with it, to the new issue.
