### ISSUE TITLE
NVDA Highlighter: allow customising colors, line thickness, dash style

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10521]
### Is your feature request related to a problem? Please describe.
The current NVDA Highlighter colors are chosen to be in contrast with each other. However, it is likely that some people with particular vision disabilities find it hard to recognize the different colors.

### Describe the solution you'd like
Add the ability to change line thickness, dash style and color of the lines surrounding the object/caret.

**Comment by DrSooom** [comment]
And, if possible, add transparency as well. If the contrast is too high, it could hurt in the eyes. Or if you have cataract, a white border on a dark background could glare extremely, so it's no longer possible to recognize the light-grey text in the dark area due to this white border.

**Comment by feerrenrut** [comment]
This issue is too general to be implemented as it is. Individual issues should be created for each  use case, from this we can determine how to best achieve this use case within the constraints of the system.

We can this issue can be used as an "epic" to group related issues if people wish for that, but I don't think it should be kept open. Currently there is no clear way to know when it is "done".

Note #10892 includes some reasoning.
