### ISSUE TITLE
Assign a gesture for the screen curtain by default

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10560]
### Is your feature request related to a problem? Please describe.
When introducing Screen Curtain, it was decided to add a global command for the curtain but leave it unassigned by default. Several people complained about this decision on NVDA-devel. As we now show a warning when initializing the screen curtain by default, I think apart from the question what key it should be, concerns about accidentally activating the curtain do no longer apply.

### Describe the solution you'd like
Assign a gesture by default. Suggestions:

- NVDA + ctrl + slash
- NVDA + ctrl + semicolon
- NVDA + ctrl + f12
- NVDA + ctrl + printScreen

I'd rather not assign something to an alphanumeric character, though for symbols, we need to take keyboard layouts into account.

### Describe alternatives you've considered
Leave as is.

**Comment by josephsl** [comment]
Hi, how about Control+NVDA+Print screen? Thanks.

**Comment by ruifontes** [comment]
For me it is better, since is more universal through the various 
keyboard layouts...

Only drawback: most people have no idea what what this key is


Rui Fontes


Às 11:14 de 29/11/2019, Joseph Lee escreveu:

**Comment by dnz3d4c** [comment]
I agree with Control + NVDA + F12. I think it's a very good idea.

**Comment by beqabeqa473** [comment]
for me nvda+control+/ is ok.

On 11/29/19, dnz3d4c <notifications@github.com> wrote:
> I agree with Control + NVDA + F12. I think it's a very good idea.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/10560#issuecomment-559765904


-- 
with best regards beqa

**Comment by k-kolev1985** [comment]
The drawback with keys such as slash, backslash, semicolon, period, comma, etc. is the fact that in some keyboard layouts such as "Bulgarian BDS/Typewriter", they may fail to work. And in such cases they have to be modified by the users or the translators of NVDA.

That is why I prefer something like F12, Print Screen, etc. For example:
- NVDA+Control+F12
- NVDA+Control+Print Screen

**Comment by beqabeqa473** [comment]
i don't think re-asigning a gesture for user or for translator is a big problem.
we have very good input gestures dialog nowadays.

On 11/29/19, Kostadin Kolev <notifications@github.com> wrote:
> The drawback with keys such as slash, backslash, semicolon, period, comma,
> etc. is the fact that in some keyboard layouts such as "Bulgarian
> BDS/Typewriter", they may fail to work. And in such cases they have to be
> modified by the users or the translators of NVDA.
>
> That is why I prefer something like F12, Print Screen, etc. For example:
> - NVDA+Control+F12
> - NVDA+Control+Print Screen
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/10560#issuecomment-559782420


-- 
with best regards beqa

**Comment by leonardder** [comment]
> how about Control+NVDA+Print screen?

Might be problematic for some smaller laptops without a dedicated print screen key, though most of them have a print screen behind an fn combination.

I will update the initial comment with all the listed suggestions. I like NVDA+control+f12 a lot!

**Comment by Brian1Gaff** [comment]
I don't think that is the point here. It needs to be something that works 
out of the box in case a beginner wants it and having to remap it is often a 
chore which is not needed in the other two cases, as long as the combination 
has not already been grabbed by something else.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment]
@leonardder: Well, and not all small laptop keyboards contains all 12 F-keys. They could also be behind Fn. But there is a solution especially for this already in NVDA – keyboard layouts.

Are NVDA+CTRL+Shift+S or NVDA+Shift+S already allocated? NVDA+S alone (Desktop layout) toggles between Speech off, Beep mode and Speech on. Thus it could be easier to memorize the Screen Curtain shortcut if it's similar to the one for toggling the speech modes.

**Comment by josephsl** [comment]
Hi, I imagine some add-ons took those keys already, hence the very reason for not assigning them in the first place at the moment. Thanks.

**Comment by ruifontes** [comment]
Hello!


NVDA+Shift+S is already used by NVDA to togglr the suspension mode for 
active application.



Às 03:55 de 30/11/2019, Daniel Mayr escreveu:

**Comment by codeofdusk** [comment]
NVDA+shift+F11. Intuitive for Mac users.

**Comment by josephsl** [comment]
Hi, note that what is intuitive for one platform may not be that intuitive for those unfamiliar at first. Thanks.

**Comment by davidacm** [comment]
I like NVDA + control + f12.
Some laptops need fn key to press f12. But is a key easy to find because f12 is always in the same position.
PrintScreen doesn't have a standard position in laptop keyboards and most users doesn't know where to locate it.
In my personal case, I asigned NVDA + alt + c for this command.

P.S: NVDA should have a feature to use "complex" key gestures to access the unfrequent options. E.G: NVDA + 0, f12 for screen curtain.

**Comment by Qchristensen** [comment]
Just a quick note that this is something users do request.  I think, if we can find a suitable keystroke, that it would be worth assigning a default gesture to this.

@davidacm Your P.S. would be worth opening a seperate issue for (I'm not arguing either way in saying that, just that this issue already has enough comments considering different keystrokes, your suggestion deserves its own space).

**Comment by codeofdusk** [comment]
Personally, I use <kbd>Ctrl</kbd>+<kbd>NVDA</kbd>+<kbd>/</kbd> for this. This is convenient on US keyboards (and doesn't require function keys) but might be awkward on European layouts.

**Comment by davidacm** [comment]
Hi @Qchristensen,
Thank you for bringing this issue again to me. I had forgot about it...
It's a good idea in my opinion, This can help to open the possibility for many other gestures too.

I will open a separate issue to talk about it.

Best regards, David CM

**Comment by britechguy** [comment]
I am completely agnostic as far as what the keyboard shortcut is, but I definitely believe that NVDA should have a toggle shortcut assigned for this function as it "ships from the factory."

**Comment by CyrilleB79** [comment]
To summarize there are objections for the following key proposals:
1. NVDA + ctrl + slash or any other shortcut involving punctuation/symbols:
  Not suitable on some non-US keyboard layouts where punctuation symbols are not at the same place and may not be available without a modifier. E.g.: On French layout, slash is gotten with shift+colon
2. NVDA + ctrl + printScreen:
  Not suitable because PrintScreen has no standard location on laptop keyboard and is often reachable only with Fn key. Also, since this key is rarely used, people do not know well its location.
3. NVDA + ctrl + f12:
   * Not suitable because it is behind Fn key on some laptop.
   * Not suitable because some small laptops have no F12 keys
4. NVDA+alt+C or any combination involving a letter:
   Not suitable because add-ons may take these shortcuts

I agree with objection 1 and 2.
I disagree with objection 3.
IMO there is a possibility for each user to choose if F1-F12 or multimedia keys are active (sometimes only through the BIOS); but I imagine that each blind people would take care to configure it (or ask help for it) so that he/she can use very useful F1-F12 keys. A person who would not have configured it would also miss very standard shortcut keys: NVDA+F3 (find next NVDA), F3 (find next in many applications), alt+F4 (close), etc.
Regarding the lack of F12 key: Is it still true? Is it common? Which brand/model? In this case, what is the last Fx key? I guess that it is very uncommon. So the few impacted people may still remap the gesture.
I also disagree with objection 4, especially now that there is the store and no more community check of the add-ons; there will be always more add-ons with more gestures. NVDA should be able to choose its  gestures in priority and add-ons authors will adapt

At last I suggest a fifth possibility:
5. NVDA+Escape or NVDA+shift+Escape or NVDA+control+Escape
   I think that escape key does not travel a lot on laptop keyboards and everyone knows where it is.

There is no point in waiting some more years to find a shortcut key. Please give your opinion (especially on solution 3, 4 or 5) and I will try to submit a PR in the next weeks. I'll let at least two weeks before submitting the PR so that everyone can comment.

**Comment by britechguy** [comment]
My comment is that I don't find any of the objections particularly persuasive.  Keyboards vary, period.  Any user of any computer needs to know their own keyboard.  I don't care whether a key is in a standard location or not, as if it needs to be used for something it's incumbent on the user to locate it on the keyboard or keyboards (as many laptop users attach external keyboards) that they are actually using.  And that even includes if, on certain keyboard layouts for specific languages, an extra key press is needed to produce a seldom-used character.  There is some keyboard shortcut, and I can't remember what for at the moment, that I have to use very infrequently that requires the asterisk.  I have to remember to hit SHIFT + 8 on my keyboard to produce that asterisk when I need to use that shortcut.

I agree with Cyrille regarding F12.  I have not seen a laptop in years that does not have F1 through F12 keys, so I'd have no objection to some key combination that includes F12 in it.

I'm not wild about the suggested use of Escape in combination with other keys, but would not strenuously object to it, either.  It's well nigh impossible to screw up with a key combination that uses Escape if a 3-key-press combination is required.  NVDA + Escape could work, too, as it's very unlikely for someone who uses NVDA to not know their NVDA key intimately and they're unlikely to ever hit it accidentally in combination with Escape.

**Comment by XLTechie** [comment]
I essentially agree with @CyrilleB79.

I suggest NVDA+Control+Escape.
IMO this key combination should not be easy to accidentally hit, nor should it 
be expected to be used frequently.
Thus a three key combo, and likely a two-handed combo.

I disagree, in part, with @britechguy's comments. Specifically, I think 
objections 2 and 3(A), do have merit.

I believe we should avoid combinations including keys that might need the 
involvement of FN. Those include function keys, and pause/prtscrn/similar.

FN is not a key which NVDA can detect, and using it in combination with the 
NVDA key may be impossible in some circumstances, as the insert key itself may 
change to something else when FN is in the picture.

Alternatively, if FN is required to use Insert, the function keys or other 
special keys may then transform to something else, so it becomes next to 
impossible to achieve the desired combination without an external keyboard.

FN opens up a whole pool of keyboard confusion that we shouldn't want to dive 
into.

Escape, on the other hand, is escape all the time, even when FNed, at least on 
all keyboards I've tested.

**Comment by Adriani90** [comment]
I disagree with the escape key, this suggest rather quiting something rather than starting something. Also if you set the same nvda key as narator key and start both screen readers, the nvda + escape is taken by narator to quit narator. In this case in my view people could by accident enable screen curtain while trying to quit narator while both screenreaders are running.

**Comment by Adriani90** [comment]
I like solution 4 actually.

**Comment by XLTechie** [comment]
@Adriani90 I don't think this is true. You can test it yourself by setting 
NVDA+Escape as your Screen Curtain key.

If you activate NVDA and Narrator, turn on Screen Curtain, and then press 
NVDA+Esc: Narrator completely intercepts this gesture.
That is the same reason you can not press Insert+q while running Narrator and 
NVDA, and expect it to quit NVDA.

Also, if you read a desktop item or other long string with both enabled, and 
press NVDA+esc, you will hear that Narrator shuts down, but NVDA does not even 
have its speech interrupted.

As for escape only exiting things not starting them: how do you explain 
Ctrl+Shift+Esc? Or Ctrl+Esc? (Task Manager and Start menu, respectively)

**Comment by CyrilleB79** [comment]
Grouped answers:

1. Unless a very specific use case is exhibited, I do not think that the use case of NVDA+Narrator should be considered, neither any other two-screen-reader use case. At least it has not been considered regarding all the other possible gesture conflicts in the past.

2. For @XLTechie:
If F1-F12 should not be used, do you consider NVDA+F3, NVDA+shift+F3 or NVDA+F12 being a mistake? As explained before, on computers where F1-F12 are behind Fn key, there is usually a way to configure the computer to toggle Fn behaviour for F1-F12 keys, i.e. F1-F12 are directly reachable while multimedia keys become Fn-reachable keys; this toggle configuration only toggles F1-F12 keys, but not other keys behind Fn such as PrintScreen which remains behind Fn.

3. For @britechguy :
> Any user of any computer needs to know their own keyboard. I don't care whether a key is in a standard location or not, as if it needs to be used for something it's incumbent on the user to locate it on the keyboard or keyboards (as many laptop users attach external keyboards) that they are actually using.

I agree that every user needs to know their own keyboard and configure it for their needs when possible. But favoring standard location keys when possible is a significant plus when working on someone else's computer using NVDA on an USB stick (e.g. work with colleague, holidays in family, public libraries, etc.)

4. For @britechguy:
> And that even includes if, on certain keyboard layouts for specific languages, an extra key press is needed to produce a seldom-used character.

No, it does not work this way with punctuation. Let's imagine that NVDA+slash is defined as shortcut for screen curtain. On French keyboard the slash is not directly accessible but you need to press shift+colon. In this case unfortunately, neither pressing NVDA+colon or NVDA+shift+colon will trigger the screen curtain. French translators need to redefine this shortcut as NVDA+colon or NVDA+shift+colon in the French gesture file of NVDA. And even with this specific local configuration, the shortcut may not be adapted for people of other French speaking countries that are using NVDA in French but are using other keyboard layout such as French (Switzerland), French (Belgium) or Canadian standard multilingual.
Thus IMO, shortcut involving punctuation keys should be avoided in NVDA and as such remain as free combinations for personal usage.

**Comment by surfer0627** [comment]
Hi, 

How about NVDA+9 to toggle screen curtain?

Could we consider to use two keys commands, instead of three keys combination .

Thanks.

**Comment by XLTechie** [comment]
> How about NVDA+9 to toggle screen curtain?

Personally, I would prefer if we stuck to the traditional use of number row keys 
as frequently changed navigational function toggles. Bringing something like 
screen curtain there, when it will probably only be used by a minority of users, 
and does not fit the pattern of the usual functions of those keys, seems 
questionable to me.

> Could we consider to use two keys commands, instead of three keys combination .

Again, just personally, I prefer three keys because of the probable infrequency 
of use. Thinking that other things that are more likely to be pressed many 
times per day, may need the two key combos more.

But naturally there will be no satisfying everyone with whatever is ultimately 
chosen; and everyone's usage will be different.
Something is better than nothing.

**Comment by surfer0627** [comment]
> just personally, I prefer three keys because of the probable infrequency
of use. Thinking that other things that are more likely to be pressed many
times per day, may need the two key combos more.

Agree.

**Comment by brunoprietog** [comment]
Sorry for being late to the discussion, but I still think NVDA + Shift + F11 should have been used. This is a standard gesture in Voiceover and Jaws also uses the F11 key. Shift and Escape is used to open the browser task manager, and Control + Shift + Escape is used to open the Windows task manager, which are very similar commands

**Comment by CyrilleB79** [comment]
@brunoprietog, the current issue is now closed. You have also commented in #15590 (https://github.com/nvaccess/nvda/pull/15590#issuecomment-1752152579); unfortunately, your comment has not been answered explicitly by NV Access.

Either you (or we) consider that the lack of explicit answer implicitely means that your proposal has not been accepted by NV Access.
Or you consider that an explicit answer is needed and that your comment has been overlooked. In this latter case, the best course is to open a new issue rewriting the arguments that you have provided here, also explaining why standardization around F11 is desirable, but also answering to the ones against F11, e.g. Escape is more easy to find than F11 on the keyboard.
