### ISSUE TITLE
NVDA slowing down and stopping from time to time on my pc.

### ISSUE THREAD

**Issue by audiogamer22** [nvaccess/nvda#10586]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:
Use NVDA on a webpage or desktop/file browser
### Actual behavior:
NVDA slows down and or stops completely for either a couple of minutes or a couple of seconds.
### Expected behavior:
NVDA should run smoothly.
#### NVDA installed/portable/running from source:
Installed.
####
NVDA version:
2019.2.1.
#### Windows version:
Version 1809 (OS Build 17763.864)
#### Name and version of other software in use when reproducing the issue:
Firefox, and windows folder browser.
#### Other information about your system:
Ram: 4 gigs. Processer: Intel(R) Core(TM) i3-8145U
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I've not tried any other versions of NVDA.

Please can you take a look at this audiogames.net forum thread? This isn't exactly to do with my issue with NVDA but the user doesn't know how to use github and is having troubles of their own: https://forum.audiogames.net/topic/31764/an-inexplicable-nvda-issue-that-is-starting-to-drive-me-crazy/

**Comment by audiogamer22** [comment]
[debug log.txt](https://github.com/nvaccess/nvda/files/3934322/debug.log.txt)

**Comment by Brian1Gaff** [comment]
A couple of comments.
 1. Did you launch nvda while a browser was already running?
I see you do not have the windows 10 app essentials running??
3. Is the Eloquence driver an official one?

My suggestion would be to try the default, ie one core synth. instead of 
Eloquence, or Espeak Quincy if you like the robot sound.
 Try with all add ons removed and launch firefox after nvda, and see what 
happens then. I don't know enough about windows 10 versions to advise on the 
app essentials you need, but the behaviour seems most peculiar to me and 
I've never seen an occasion where an app module is not named but  appears to 
be requesting a virtual buffer before.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by davidacm** [comment]
Maybe this issue is related with #10599 ?
Can you check that issue?

**Comment by audiogamer22** [comment]
It sounds similar but not exactly the same.

I think my issue is more to do with bluetooth headphones and nothing can be done.

I’ll try using my pc with no headphones for a couple of days and if everything is fine, I’ll close the ticket.

Sent from my iPhone

On 24 Dec 2019, at 14:04, David CM <notifications@github.com> wrote:

﻿

Maybe this issue is related with #10599<https://github.com/nvaccess/nvda/issues/10599> ?
Can you check that issue?
