### ISSUE TITLE
Project 64 Cheats Issue

### ISSUE THREAD

**Issue by Phoenix1991-lab** [nvaccess/nvda#10617]
Greetings, This is Analis. I am having major issues with the cheat menu in Project 64. You may not know this, but project 64 is a Nintendo 64 emulator. When I try to enable cheats, the menu items all appear to be checked. When I try to manipulate a cheat then close out of the cheats menu, it resets itself. What do I need to do to make this work? I really want to know. Please get back to me ASAP! Thank you!
Please thoroughly read NVDA's wiki article on how to fill in this template, including how to provide the required files.
Issues may be closed if the required information is not present.
https://github.com/nvaccess/nvda/wiki/Github-issue-template-explanation-and-examples
-->

**Comment by Brian1Gaff** [comment]
I think you might be better raising this on the development list, as odds 
are without the template somebody will  not look at this issue. Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Phoenix1991-lab** [comment]
how to I contact NVDA Developers

**Comment by DrSooom** [comment]
@Phoenix1991-lab: First, please completely fill out the bug report draft, otherwise it will be closed. And also try it here: https://nvda.groups.io/g/nvda

Please note that the NVDA main devs are currently working on the release of NVDA 2019.3, which is a very huge step in NVDA's history. Therefore this bug, if it's really one in NVDA, may get fixed next year or even later as Project64 isn't an application which is quite often used by NVDA users. And yes, I know this emulator, but I never used it in the past.

See also: project64/project64#1683

**Comment by feerrenrut** [comment]
Thanks for investigating further @DrSooom. I'm going to close this issue for now since it doesn't have anything concrete for us to go on. If something comes of project64/project64#1683 please open a new issue.
