### ISSUE TITLE
Negative dollar amounts not announced with minus symbol

### ISSUE THREAD

**Issue by JamesCatt** [nvaccess/nvda#10633]
### Steps to reproduce:
Create a web page with a negative dollar amount that uses the minus character (https://www.fileformat.info/info/unicode/char/2212/index.htm), such as `<p>&minus;$100</p>` and navigate to it with NVDA + any browser.
### Actual behavior:
Amount reads as "one hundred dollars" with no mention of the minus symbol.
### Expected behavior:
Amount reads as "minus one hundred dollars", the same as it would with a dash instead of minus symbol.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Win10 x64 Home
#### Name and version of other software in use when reproducing the issue:
Firefox 72, Chrome 79
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2, same.

Issue is likely due to only the dash character being included in the symbols dictionary, as well as the regex for negative amounts. Negative amounts were addressed by https://github.com/nvaccess/nvda/commit/0f437f0c31cd7c1924e25374f3f5ed7999cad5db but it looks like this only included the dash symbol, and not the actual minus symbol. Can also see more here: https://github.com/nvaccess/nvda/issues/3805#issuecomment-558754733

**Comment by StommePoes** [comment]
I have tried 2 synths (Microsoft Speech API and eSpeak NG) and under punctuation there's minus in a list of some punctuation (not much though and mostly emoji) where I've tried setting it to none, some, and all and tried all settings of the other dropdown (whose purpose I don't understand but tried Never, Always, and Always Below Symbol's Level).
None of these will read out any of my minuses: not the HTML named, decimal or hexidecimal character entity references, nor a direct copy/paste of the symbol directly.
I did a broad punctuation test about 2 years ago on multiple screen readers, where in all tested SRs the minus worked (the dash did not, so it was before the change in #3805), so it's more like this is a regression rather than never-added.

**Comment by JamesCatt** [comment]
> Currently the hyphen-minus is reading as "minus" in NVDA. I'm not sure if I should use this symbol instead for current math projects I'm working on or if this issue will be fixed within the current school year.
#10636 should address this, although I'm guessing the NVAccess team is busy with 2019.3 beta at the moment. Hoping they can get to my PR in time for the first 2020 release.

**Comment by StommePoes** [comment]
I need to update my comment about the hyphen-minus: it's acting exactly as the dash currently: it'll say "minus" but only when directly prefacing a number. When I did my symbols test ~2 years ago, I could get the `&minus;` symbol read out reliably in NVDA regardless of where it was in text.

This was my testing page, taken from back when I was doing some math work for an educational company:
https://stommepoes.nl/work/symboltest.html
