### ISSUE TITLE
Creating a hotkey for reading text only

### ISSUE THREAD

**Issue by tangweichong1992** [nvaccess/nvda#10648]
Hi,
I would like to suggest that the developer team to consider creating a hotkey to only read text when using NVDA in brows mode, just like older versions of window-eyes. Although the "N" key for NVDA performs the function mentioned above, it does not omit things like buttons or frames. By having such a hotkey to only read text, it will provide another alternative for faster navigation in a web browser.

**Comment by Adriani90** [comment]
For this purpose you can also use the addon textnav.
https://addons.nvda-project.org/addons/textnav.en.html
cc: @mltony

**Comment by bhavyashah** [comment]
For what it's worth, if integrated in core, I think the keyboard shortcut should be a single-letter navigation key rather than Alt+Shift+up/down arrows. However, I'll be the first one to admit that a discussion of key bindings should follow - not precede - a discussion of whether we have consensus on having this feature in core in the first place. Not to muddle this, but I think we might want to think about how "n" (skips past a block of links) might relate to a text block navigation key. Are they similar/do they serve similar purposes/ are they both likely to be used in the same sorts of webpages? Perhaps the answer is no in which case this line of inquiry may be moot. I don't regularly use TextNav myself so cannot authoritatively answer this.

**Comment by Adriani90** [comment]
Closing in favor of #12506 which contains more discussion and a potential developer who might contribute to implement it it when the expected user experience is clear enough.
