### ISSUE TITLE
NVDA and russian braille tables

### ISSUE THREAD

**Issue by Futyn-Maker** [nvaccess/nvda#10653]
Hello!
Liblouis library provides several braille tables for Russian language. By default, only 2 is available in NVDA - Computer Braille and grade 1. These tables were developed by foreigners who are not fully familiar with Russian Braille.
There are also tables created by Igor Poretsky. They are much more developed and meet Russian Braille standards.
They are present in Liblouis. They are called ru-compbrl.ctb and ru-litbrl.ctb.
Please make it possible to select these tables from the NVDA braille menu.

I know that I can change the configuration file, but I think this is a problem for inexperienced users.

Also, for some reason, character input does not work correctly. Even if I select the desired Braille table as the input table, not all characters are entered correctly, despite the fact that in the table itself such an option is indicated.

In addition, when I choose Russian literary braille, for some reason, in some cases, characters are still displayed in accordance with the rules of computer braille. This is somehow related to the position of the cursor in the document.

Thanks!

### Steps to reproduce:
Described above

### System configuration
Windows 10 X64
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Win 10 X64
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Problem is in all versions.

**Comment by DrSooom** [comment]
First of all, please completely fill out the bug report draft. Your first suggestion is NVDA related.

> Also, for some reason, character input does not work correctly. Even if I select the desired Braille table as the input table, not all characters are entered correctly, despite the fact that in the table itself such an option is indicated.

Please report these bugs against [Liblouis](https://github.com/liblouis/liblouis/issues/new) and mention there the name of the braille table file(s), the current and the expected results. Thanks.

> In addition, when I choose Russian literary braille, for some reason, in some cases, characters are still displayed in accordance with the rules of computer braille. This is somehow related to the position of the cursor in the document.

Workaround: Disable the option "Expand to computer braille for the word at the cursor" in the Braille NVDA settings.

**Comment by zstanecic** [comment]
Hi Daniel, Futin and all!

1.	Eight-dot Russian table is based on KOI8R Cyrillic standard, and it works on imput and output and Russian users, so far don’t have the problem with this table, because it works on imput and output, and Cyrillic and latin scripts can be read, according to Russian braille standards.
2.	The literary table is problematic, as it doesn’t work on imput at all.

Igor Poretsky doesn’t use eight dots braille. He wrote the tables for his own personal needs, just to display things related to programming and he wrote it only for imput. Russian table is full of bug (the literary one), and it is not recommended for imput

In the past, we had this table as the default Russian table for eight dots. In the past, we had confusion, because the table which was intended to display computer code, it was not so.

We don’t have it, as we have replaced it with working Russian eight dot braille table.

If you want to improve the literary table, please contact the Liblouis project.

The argument that tables were written by foreigners doesn’t pass here.
