### ISSUE TITLE
accessibility nvda remote in nvda 2019.3

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#10659]
Hello. Is there any news about the availability of the nvda remote add-on? for my part, I wrote letters to the add-on developers several times, but I received no answer. for me, this feature is important. So I'd like to know what's going to happen next. Thank you.

**Comment by Adriani90** [comment]
Cc: @Nardol

**Comment by Nardol** [comment]
Asking myself the same.
I am not one of the author so I'm surprized when seeing I am mentionned but I hop @ctoth and/or @tspivey will make the necessary to make it compatible with Python 3.
I read @ctoth wrote to NVAccess about that, that's all I know.

**Comment by gdata1** [comment]
@Nardol I asked them a question, but I didn't get an answer.

**Comment by feerrenrut** [comment]
NV access provided a pull request to NVDA Remote to make it compatible with 2019.3. See the now merged pull request NVDARemote/NVDARemote#211.

Since this issue is really related to NVDA remote and not NVDA, I'm going to close this issue. There is a relevant issue already on NVDA Remote (NVDARemote/NVDARemote#207) which it looks like you created, but I mention it for the benefit of others :smile:
