### ISSUE TITLE
Cannot close speech viewer with alt+f4

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10791]
### Steps to reproduce:

1. Press NVDA+n, then t, then s to open speech viewer.
2. Press alt+shift+tab to move to the speech viewer window (it starts as the last window in the alt+tab sequence).
3. Press alt+f4

### Actual behavior:

At step 3, nothing happens.  Nothing is even recorded to the NVDA log at debug level:

IO - inputCore.InputManager.executeGesture (13:33:05.596) - winInputHook (11520):
Input: kb(desktop):alt+f4
IO - inputCore.InputManager.executeGesture (13:33:08.944) - winInputHook (11520):
Input: kb(desktop):NVDA+f1

(I opened the log viewer a few seconds later)

### Expected behavior:

ALT+F4 should close the window, as happens in any other Window (including other NVDA windows).

Note that the speech viewer window can still be closed by pressing alt+n, t, s again, or by using the shortcut key (if you have defined a shortcut key to toggle speech viewer).  Creating a shortcut for speech viewer (in NVDA's input gestures dialog) is recommended for users who frequently toggle this feature on and off.

#### NVDA installed/portable/running from source:

Installed
#### NVDA version:
2019.3.1
#### Windows version:
1903 build 18362.388
#### Does the issue still occur after restarting your PC?
Yes.  Also reported by a user.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2.1 - alt+f4 closes speech viewer as expected.

**Comment by DrSooom** [comment]
@Qchristensen: Please also check this out with the new Braille Viewer window in NVDA 2019.3.1. Thanks.

**Comment by Qchristensen** [comment]
Good question, the Braille viewer DOES close with alt+f4, so this seems to be something about the speech viewer.  (Settings, speech dictionary, punctuation, input gestures, log viewer, braille viewer, python console, add-ons manager, create portable copy, welcome dialog, about dialog, configuration profile and exit dialog can all be closed with alt+f4.

The only other dialog I couldn't close with alt+f4 was the "Run COM Registration fixing tool", which can't be closed with alt+f4, or escape, you need to activate either the Yes or No button (ideally, ALT+F4, and escape, should both activate the no button on that dialog).

**Comment by bhavyashah** [comment]
I can confirm that this issue persists with NVDA version 2020.2 Beta 1. I would, however, like to request that the scope of the request in this ticket be expanded: the Speech Viewer window should not just close when Alt+F4 is pressed, but it should also have a dedicated Close button. The reason for this is that it can be reasonably expected, I think, that a substantial proportion of the users of the Speech Viewer functionality will be people with some sight. A significant subset of these will be fully sighted and may not be used to issuing commands using keyboard shortcuts at all. As such, they may not know of the Alt+F4 key command, and even if they know of it, it may not strike them since they seldom use it. Hence, having a conspicuous Close button would reduce any potential confusion for these mouse users.
In addition, I think there is a case to be made for having the usual Minimize, Maximize and Close buttons in the Speech Viewer window too. However, I think that request is distinct enough from this ticket to merit another discussion some other day.

**Comment by seanbudd** [comment]
This is due to the event being vetoed https://github.com/nvaccess/nvda/blob/release-2020.4/source/speechViewer.py#L103

**Comment by JulienCochuyt** [comment]
@bhavyashah wrote:
> I would, however, like to request that the scope of the request in this ticket be expanded: the Speech Viewer window should not just close when Alt+F4 is pressed, but it should also have a dedicated Close button. The reason for this is that it can be reasonably expected, I think, that a substantial proportion of the users of the Speech Viewer functionality will be people with some sight. A significant subset of these will be fully sighted and may not be used to issuing commands using keyboard shortcuts at all. As such, they may not know of the Alt+F4 key command, and even if they know of it, it may not strike them since they seldom use it. Hence, having a conspicuous Close button would reduce any potential confusion for these mouse users.

I fully agree. Please see PR #12328 for the addition of a standard close button on the Braille Viewer as well.


@seanbudd wrote:
> This is due to the event being vetoed https://github.com/nvaccess/nvda/blob/release-2020.4/source/speechViewer.py#L103

Indeed. Still, care must be taken to properly handle unchecking of the dedicated NVDA Tool menu entry, as is currently done with the Braille Viewer.

**Comment by TheQuinbox** [comment]
I know this issue has been closed for a bit, but thought I'd bring it up here, instead of creating a new issue.
Should I implement pressing escape also closing the speech and braille viewers? It already closes log viewer, so for consistancy, it might be good.
Thanks.

**Comment by DrSooom** [comment]
@TheQuinbox: Please open a new issue for that. Thanks.
