### ISSUE TITLE
Input Gestures Dialog: Add Checkbox to Only Display Bound Gestures

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10834]
### Is your feature request related to a problem? Please describe.

Currently, if choosing to use the Input Gestures dialog to add/remove bound actions, it can sometimes be difficult to establish which gestures are currently bound - without first having to individually go through each and every available gesture in the list.

### Describe the solution you'd like

To combat this, we could consider adding a checkbox to the dialog labeled something along the lines of "Only Display Bound Gestures" that when checked, would hide all non-bound gestures from the list.

**Comment by Adriani90** [comment]
I am not really in favor of this request due to the fact that we would actually hide features in NVDA which is not really giving a good user experience. Novice users might enable that checkbox by accident and forget about it and they will not discover possibly new features comming into NVDA with unassigned gestures.
I think there is an issue about creating a list of unbound gestures which should be automatically generated. I think that would be a better alternative.
How ever I cannot find that issue right now.

**Comment by Adriani90** [comment]
This is issue #13024.
I am closing this one in favor of #13024. If you have strong arguments for a checkbox solution though, please comment and we can reopen.
