### ISSUE TITLE
Activating HTML checkbox when navigating with the virtual cursor on its `<label>` triggers click event from label and input

### ISSUE THREAD

**Issue by zepumph** [nvaccess/nvda#10839]
### Steps to reproduce:

1. on Firefox (cannot reproduce with Chrome)
2. load the following HTML page:
<details>

```html
<!DOCTYPE html>
<html>
<body>
<div id='parent'>
  <p>something before</p>
  <label data-trail-id="input" id="label" for="input">Constant Size</label>
  <input data-trail-id="input" id="input" type="checkbox">
  <p>something after</p>
</div>
</body>
<script type="text/javascript">
  const input = document.getElementById( 'input' );
  input.addEventListener( 'click', () => {
    console.log( 'click - input', input.checked );
  } );
  const label = document.getElementById( 'label' );
  label.addEventListener( 'click', () => {
    console.log( 'click - label', input.checked );
  } );
  document.getElementById( 'parent' ).addEventListener( 'click', () => {
    console.log( 'click - parent', input.checked );
  } );
</script>
</html>
```

</details>

3. Turn NVDA on
4. tab to the checkbox
5. press space
6. Note that console logging shows that there was a click event from the input that bubbled to the parent (correct behavior)
7. Now press up arrow (to "something before") and then the down arrow back to the checkbox with the virtual cursor.
8. Press space, and see in the console that now there was a click event from the input AND a click event from the label. Both of these bubble to their parent.

#### Actual behavior:

We get a click event from the label and from the input. In this case, the parent gets two click events when only one click occurred on the checkbox. There is additional buggy behavior based on how the checkbox value (state) is not the same at the times of both callbacks. 

I cannot reproduce this in Chrome. Likely because in its Accessibility Tree, the `<label>` element does not have an a11y node, and instead it is just used to compute the accessible name for the input node. In Firefox there is a text node for the label (with the value of the label) AND there is a node for the input with its accessible name being label value. 

Out project captures all click events in a parent and dispatches them in a custom manner. Because of our structure, this bug ends up triggering the checkbox twice (toggling it then toggling it back). See https://github.com/phetsims/a11y-research/issues/156 if interested more in our context. 

#### Expected behavior:

I would expect that the console output for step (5/6) would happen if you tabbed to the checkbox, or used the virtual cursor to be on the label

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

2019.2.1

#### Windows version:

OS Name:	Microsoft Windows 10 Pro
Version:	10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:

Firefox 73.0.1 

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes I updated to 2019.3.1 while writing this and there was no change.

----------------
Thank you for all you do!

**Comment by Adriani90** [comment]
Cc: @MarcoZehe

**Comment by MarcoZehe** [comment]
CC'ing @jcsteh as well, since this has multiple avenues for solution:

1. Mimic what Chrome does and suppress labels that are associated with inputs like this. This could lead to a lot of issues I think.
2. Solve the proble on the NVDA side so the click does only occur once.

Having said that, I wonder what the web application does if you click the label, not the checkbox, with the mouse. @zepumph have you checked that? Because associating a label and input allows clicking the label to set focus to/toggle an input, thereby increasing the click surface.

**Comment by jcsteh** [comment]
When you press down arrow in step 7, the browse mode cursor is on the label, not the check box. You can confirm this by moving the cursor word by word through the line. The check box is at the end of the line. Since the label is visible, NVDA renders the label so the user can see semantics and formatting inside the label.

IMO, pruning the label from the a11y tree is wrong and causes real world problems. See the explanation and example under the heading "Ignore the label element, obviously. Duh." in [my blog post](https://www.jantrid.net/2015/12/woe-aria-surprisingly-but-ridiculously.html).

As Marco notes, clicking the label is an entirely valid (if not so common) thing to do, even for a mouse user. Not supporting this is an a11y issue for some non-screen reader users as well.

Why not use the (more semantic) change event instead of the click event?

IMO, this is invalid/wontfix.

**Comment by zepumph** [comment]
>IMO, pruning the label from the a11y tree is wrong and causes real world problems.

That seems really reasonable to me. 


>As Marco notes, clicking the label is an entirely valid (if not so common) thing to do, even for a mouse user. Not supporting this is an a11y issue for some non-screen reader users as well.

Also agreed. My issue was with the multiple events, and not with interfacing with the label in general.


>Having said that, I wonder what the web application does if you click the label, not the checkbox, with the mouse. @zepumph have you checked that? 

I used the above snippet in Chrome just now with a mouse (clicking the label instead of the checkbox) and received the exact same event structure:

```
click - label false
click - parent false
click - input true
click - parent true
```


With this in mind I think that we will pursue the use of the change event in this case to prevent the repetition. Thank you all for your time! I really appreciate the consultation.

**Comment by Adriani90** [comment]
closing as suggested by Jamie above.
