### ISSUE TITLE
Legal numbering scheme read as date

### ISSUE THREAD

**Issue by alanfluff** [nvaccess/nvda#10850]
### Steps to reproduce:
This HTML markup `<h3>1.01.02</h3>`.

### Actual behavior:
Read out as "January first 0 1"

### Expected behavior:
Read out as "one dot zero one dot zero two".

This is a numbering scheme for a legal document that is marked up in HTML. It is not intended to be a date. I have looked for ways to declare the HTML tag content type but failed to find one :/

#### NVDA installed.
As a normal app (not portable).

#### NVDA version:
2019.2.1

#### Windows version:
7 Enterprise.

#### Name and version of other software in use when reproducing the issue:
Chrome  80.0.3987.122

#### Other information about your system:
Typical government PC.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by josephsl** [comment]
Hi, how about switching the speech synthesizer to something else? If that solves the problem, then this one is yet another variant of ‘number processing” issue. Thanks.

**Comment by Brian1Gaff** [comment]
Its a bit like the way some synths seem to handle cap letter groups as 
abbreviations as well as abbreviations sometimes as the wrong expanded word 
due to the synth being US centric in other English speaking  countries.
 I am getting fed up with a UK post code like KT1 5NY being said as KT1 5 
New York!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by alanfluff** [comment]
Thanks for the suggestion @josephsl that fixed it.

I don't know about that issue. Do you know if I should comment on another thread, in case this case helps in anyway?

**Comment by josephsl** [comment]
Hi, I’m sure someone will comment on that with the actual issue number at hand. Thanks.
