### ISSUE TITLE
Does NVDA have a plan for VSCode?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [nvaccess/nvda#10863]
Hi, I know that the NVDA team is intensely interested in python 3. Maybe you may not have time.

But I wanted to ask.

Is there a solution for words that NVDA misrepresents in VSCode when navigating between codes?
Ask about this Electron, Microsoft APIs... where?

I think VSCode is a very functional editor. It has very useful properties.
It can provide all development environments.
When we think about it, we need to install a separate editor for each programming language. Not every program is accessible. There are moments when developers don't care about accessibility.
But when we make VSCode fully available with NVDA, we get the development environment of all languages.

VSCode's team pays much attention to Issues. I do not know. Maybe good communication can solve this problem.

It would be nice to be able to navigate like notepad in the code writing area.

So the code section is unavailable. NVDA says everything double.

I think we need to think about this issue. We may not be able to install Visual Studio on every computer.
VSCode is a portable, simple editor.

What can we do, the problem is not in NVDA?

**Comment by feerrenrut** [comment]
Hi @SeanTolstoyevski, we are trying to maintain support for vsCode, several of our contributors use it themselves. If you are having trouble with VS Code please open a [new bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md) and fill out the template, you may also wish to [raise the issue with the vsCode developers](https://github.com/microsoft/vscode/issues/new?template=bug_report.md). The NVDA users and NVDA developers mailing lists can also be used to ask questions like this. I'm going to close this issue since it does not clearly describe a problem.
