### ISSUE TITLE
NVDA Stops Reading Microsoft Teams Window

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#10968]
### Steps to reproduce:
1. Open Teams.
2. ALT+TAB away from it.
3. Randomly, when you come back to the Teams window, NVDA will read nothing as you tab around.
### Actual behavior:
NVDA suddenly stops reading Teams.
### Expected behavior:
NVDA should always read Teams window.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2019.3.1
#### Windows version:
1903
#### Does the issue still occur after restarting your computer?
No
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. 2019.2.1: same issue
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by lukaszgo1** [comment]
I am  also experiencing this, however this problem is reproducible not only with NVDA but  also with JAWS which suggests that it is a teams issue rather an NVDA one. As a workaround moving Teams window with Win + arrows restores it to the working order. I believe @leonardder had a conversation about it with Microsoft accessibility team on Twitter  a week ago.

**Comment by munawarb** [comment]
Hi @lukaszgo1,
Thanks for the suggestion. Next time it happens, I'll try this and see if it fixes it for me. It's quite annoying when you're in the middle of a presentation. Haha.

**Comment by leonardder** [comment]
I agree that this is pretty annoying, however Microsoft is aware of this and they are working on it. There's nothing we can do about it I"m afraid. Closing as needs external fix.

**Comment by munawarb** [comment]
For the record, @lukaszgo1's solution of pressing WIN+ARROW worked. Thanks for the help!
