### ISSUE TITLE
Apply profile handler for symbols and punctuation when changing the level in the punctuation and symbols dialog

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#10972]
### Steps to reproduce:
1. Go to the NVDA menu and create two profiles
2. Open punctuation and symbols
3. in the filter edit field, type the star sign
4. In the list with symbols, choose the star symbol
5. press tab and change the punctuation level in which this sign should be spoken. Press ok to save.

### Actual behavior:
NVDA applies this setting for the star sign to every profile.

### Expected behavior:
The setting should be profile specific. I.e. pronouncing the star sign in some applications where we read much mathematical content makes sense because the star sign is very important there. On the other hand, when reading a text with gender specific terminology, the star sign should not be reported. In German for example a star sign is used for addressing both male and female genders in a word.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.3.1

#### Windows version:
Windows 10 1909

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, I didn't found any version where this worked as expected.

#### If addons are disabled, is your problem still occurring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by DrSooom** [comment]
The "symbols-xx.dic" files are ignored by the configuration profiles such as is the case with the "gestures.ini".

But even if I would like to have tons of configurable settings, I'm suggest switching between the symbol levels via NVDA+P could be the more understandable way for most users. In other words: The end user should group the symbols levels for some Unicode characters to "Some" and "Most" and then just switch to the desired symbol level by just pressing NVDA+P.

Hmm… Maybe an additional symbol level between "Some" and "Most" could help here more. Let's call it "More".

**Comment by DrSooom** [comment]
I wrote more about the German gender TTS issue [here](https://netzpolitik.org/2020/warum-wir-geschlechtergerechte-sprache-verwenden/#comment-2526806), [here](https://netzpolitik.org/2020/warum-wir-geschlechtergerechte-sprache-verwenden/#comment-2527098) and [here](https://netzpolitik.org/2020/barrierefrei-planen/#comment-2537997). These comments are written in German.

**Comment by feerrenrut** [comment]
I tend to agree with @DrSooom. Symbol reporting should be put into a category and the config profile should be set to use the appropriate symbol level. If the granularity of this is not enough we could consider adding another level as suggested by @DrSooom. Another option which would require some early investigation into the consequences (with considerations into ux design, code design, and performance) might be to allow symbols to be put into user defined symbol levels which act like categories for symbols. My concern with this is that the configuration could become complicated very quickly. 

I'm going to close this issue since the core request is not something we would consider.
