### ISSUE TITLE
Outlook 2016: Incorrect Selection State of Folder announced when Moving a Message

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11019]
### Steps to reproduce:

The following assumes that Outlook 2016 has been configured with an Exchange account that has at least two email messages within the Inbox folder.

1. Create a new folder directly within the Inbox folder; name it "Test" or similar

2. Right-click the top email in the Inbox, open the "Move To..." submenu, and choose "Select Folder" - when prompted, choose the folder created in the previous step

3. Finally, right-click the remaining message in the Inbox, and open the "Move..." submenu

### Actual behavior:

Despite the "Test" folder automatically obtaining focus, NVDA announces that the folder is not selected

### Expected behavior:

NVDA should recognise that the folder is focused; this is confirmed by hitting enter, at which point the message is moved to the top folder in the list as expected

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

7 X64

#### Name and version of other software in use when reproducing the issue:

Office 2016 X86

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

**Comment by Adriani90** [comment]
@elliott94 the reporting is a bit confusing here, but it is correct. NVDA reports what you focused. But the folder is not selected. If you press enter, then it is selected.
cc: @Qchristensen, @leonardder this might be due to UIA in Outlook providing confusing information. Actually NVDA should report only the item which is focused, without any further information.
However, maybe some impressions from a sighted person would help here.

**Comment by Qchristensen** [comment]
Actually for me (Office 365 Version: 16.0.12730.20256), NVDA reports "Folder name, not selected" for every folder as I arrow down through that list.  I agree this doesn't need to be reported.  In submenus such as categorize and follow up, reporting "Selected" is useful because an item may have one or more categories, and it may be set to be followed up today or tomorrow or another time.  The options for "Move" don't need to be reported in that way as none of them can already be "selected" (or the message would already be in that folder and it wouldn't be listed, but the inbox would)

I think it's perhaps an error on Outlook's part to designate those menu items as having checkboxes?

Just checking with Narrator, the folders in "Move" are not reported as selected (or unselected).  Categories are only reported as checked or unchecked when they ARE checked (when they are not they aren't reported).  Each item in "Follow up" is reported as being checked or unchecked.

**Comment by Adriani90** [comment]
This happens because Microsoft defined the folders in the submenu as list items, the parent object of the folders you can move a message to is a list box object. Then NVDA handles it as such and reports not selected as this is what Outlook exposes for list boxes and tree views. Note that not selected does not mean that you didn't focus the item, it means you didn't select it. However, I understand this is redundant in this case because you can select only one items at a time. But this needs to be fixed by Microsoft.
Closing as this is not related to NVDA. Please report this to Microsoft.
