### ISSUE TITLE
Chromium browsers: selecting by paragraph is inconsistent

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11084]
### Steps to reproduce:
1. Open NVDA in Chrome or Edge Chromium
2. In an edit field with text, i.e. multiple lines, select the text with ctrl+shift+down arrow paragraph by paragraph
3. Remove the selection with ctrl+shift+up arrow backwards paragraph by paragraph

### Actual behavior:
Steps 2 and 3 show different behavior, when you remove the selection in step 3 NVDA seems not to move paragraph by paragraph.

### Expected behavior:
Steps 2 and 3 should behave the same, selecting and deselecting the same amount of text.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20097,6a573cd9

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
Google Chrome 81, Edge Chromium stable 81

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not yet

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no effect

**Comment by Adriani90** [comment]
Maybe related to #11083. cc: @aleventhal, @jcsteh

**Comment by Adriani90** [comment]
This occurs only in focus mode

**Comment by ObjectInSpace** [comment]
Paragraph deselection seems OK to me. I type "this is a test", then two line breaks, then "this is another test" Each line feed is counted as its own paragraph so it takes three presses of ctrl+shift?down arrow to select everything, and three to deselect. 

We've made a number of recent changes related to text selection in edit fields. Could you try again in canary? If the issue is the same, how many paragraphs need to be in the textbox/selected by the keyboard in order to trigger the buggy behavior when deselecting text?

**Comment by ObjectInSpace** [comment]
Gotcha! Since this does not involve any screenreader commands and occurs in focus mode, I think this is a general Chrome issue that is not specific to any screen reader. I filed https://crbug.com/1094038 to track it. In so doing, I noticed a similar bug in deselecting lines: it will always select both the bottom and the second-most bottom line if the carrot as at the beginning of the line when deselecting. I filed this at https://crbug.com/1094032.

Thanks so much!

**Comment by JulienCochuyt** [comment]
@Adriani90, I guess we can close this ticket as well, in the light of https://github.com/nvaccess/nvda/issues/11084#issuecomment-642961390.

**Comment by Adriani90** [comment]
Thanks for the comment here, I would prefer to let this open since we have Chromium bugs for this and we can track the progress. This is easier to track for NVDA users and developers who are not very often actively working on Chromium bug tracker.

**Comment by Adriani90** [comment]
I am closing this as works for me, since NVDA can now specifically handle paragraphs by itself which can be set up in the document navigatoin category in NVDA settings. The Cromium bugs have been labeled as wont fix anyway and I understand the reasoning behind it.
