### ISSUE TITLE
Integrating Orca's symbol translations?

### ISSUE THREAD

**Issue by sthibaul** [nvaccess/nvda#11105]
Hello,

On the Linux side, we are working on making the symbols processing more coherent, basically basing on the NVDA tables so we can have shared open-source effort there on fixes and translations.

There are a few symbols that Orca currently translates which are not yet in the NVDA tables, such as □, ○, ◆, ✗, ¼, ½, ¾, ⁰, ⁴, etc. with a lot of available language translations. I can easily work on providing a patch that simply adds them all to `source/locale/*/symbols.dic`, would that be enough for NVDA, or is there more to it? (e.g. to integrate with the translation process)

Samuel

**Comment by leonardder** [comment]
Interesting suggestion. You'd have to add them to the English symbols only and they would be automatically provided to be translated.

**Comment by ruifontes** [comment]
But if they are already translated, why asking the translators to translate again?
If the translations are placed in the respective locale, it will be only a question of review...

**Comment by sthibaul** [comment]
> If the translations are placed in the respective locale, it will be only a question of review...

Ok, that's what I was wondering about, whether just committing the changes in locale/*/symbols.dic will work with the translation workflow.

**Comment by lukaszgo1** [comment]
No, it would not. Translations are for now managed through SVN, so it is not as simple as that.

**Comment by sthibaul** [comment]
> No, it would not. Translations are for now managed through SVN, so it is not as simple as that.

Ok, I see the symbols.dic files in http://subversion.assembla.com/svn/screenReaderTranslations , should I then produce a patch against these?

I can adapt my script, I just need to know what makes it easiest to integrate :)

**Comment by josephsl** [comment]
Hi, I believe some of them are already part of NVDA – whatever the English symbols file contains, that will be the version translators will get. What will make it a bit harder is if some languages have these symbols translated, in which case NVDA and Orca translators must be willing to collaborate to unify their work. Thanks.

**Comment by leonardder** [comment]
Indeed, the problem is unification. NVDA always aimed at the shortest possible translation, hence the word bang and not explanation mark for `!`, question (not question mark) for `?`. Does Orca also follow this pattern?

**Comment by sthibaul** [comment]
> What will make it a bit harder is if some languages have these symbols translated

I can filter them out, that's not a problem.

> Does Orca also follow this pattern?

Orca has the same kind of users, so the same habits, yes :)

But anyway, we can inject the symbols for which there is currently nothing in NVDA, that will be better than nothing, and translators will be able to fine-tune afterwards if they want.

**Comment by josephsl** [comment]
Hi, I think the best way forward is committing to locale/en/symbols.dic. That way translators can look at differences and translate accordingly. Still, I believe we need to have a conversation between two projects, especially between translators working on these projects so we can come up with a unified approach. Thanks.

**Comment by zstanecic** [comment]
I don’t want to communicate with the Croatian orca translator, as he thinks that he knows better which comes to the accessibility terms.

And yes, I don’t plan to take over my responsibilities as involved in the project to anyone, unitl I declare so that it is needed.

There is one contributor which translated gnome and orca, he gave a good suggestions,

But the person with whom I don’t want to cooperate is Zoran Vidovic.

He wanted to enforce me his version of translations and do the purification of the language. 

I am not a language purist, sorry.

**Comment by josephsl** [comment]
Hi, for now it involves symbols – we shall see what happens next at the appropriate time. Thanks.

**Comment by zstanecic** [comment]
Sorry, but i am against this.

We should listen to our language communities.

We had a biggest innovation in the croatian translation, even we refined the symbols which we had.

The problem is that we worked hard, me and user which the handle on assembla is milotype.

Now I don’t want this to go just nowhere.

We’ve set up the strict glossary convention and users are happy with this translation which we have now.

**Comment by josephsl** [comment]
Hi, I think this strengthens the proposal that a commit to English symbols would suffice, as translators can choose to translate new symbols if needed. Thanks.

**Comment by lukaszgo1** [comment]
@sthibaul wrote:

> Does Orca also follow this pattern?
> 
> Orca has the same kind of users, so the same habits, yes :)


I don't think so. While the Orca's user's might have similar needs the translation is being managed quite differently. Last time when I looked translations were done as part of Gnome project. This in itself would not be bad except the fact that the people behind translations are not, for the most part, using screen readers themselves. The Polish translation for example is IMO hardly usable the fact that these people do not have even vague idea of conventions used  by screen readers is visible in almost every message,

**Comment by zstanecic** [comment]
And yep,

Polish translations are too long, I am speaking about orca.

Croatian translations are long too. 

Bear in mind that NVDA is also used at workplaces, in the corporate environments and universities, and that our translations should be accurate, even the symbols, respectively. 

And one more fact: NVDA is built in into the esytime braille computer, produced by eurobraille, so we should make rour translations richer and precise, which means, watch out the quality assurance processes!

I am doing this for Croatian every 3 (three months), by fixing typos, refining strings, incorporating all user feedback.

**Comment by zstanecic** [comment]
Note: The same thing i am applying for polish, in agreement with other NVDA polish translators.

**Comment by sthibaul** [comment]
Ok, I understand that we probably don't want to just commit the translations outright. I was just thinking it'd be a bit sad not to try to take benefit from them.

Instead I can produce one patch per language, put them somewhere for translators to have a look at, and let them take what they like?

**Comment by josephsl** [comment]
Hi, no need for per-language patch, as this is done as part of translations workflow. Thanks,.

**Comment by sthibaul** [comment]
> no need for per-language patch, as this is done as part of translations workflow

I mean, for providing the Orca translations, that translators can take if they like them.

**Comment by josephsl** [comment]
Hi, I see. I think a better venue for discussing this would be NVDA translations mailing list (groups.io/g/nvda-translations). Thanks.

**Comment by Brian1Gaff** [comment]
Which I changed to exclamation in all my versions as bang is not used in the 
UK any more than number is for hash.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by CyrilleB79** [comment]
Just a question: is there some guideline or some common usage to decide which symbol is added in symbol.dic and which should not? Is there a big performance penalty to add many symbols?
I raise these questions because anyone may want to add more symbol, e.g. see #11015.

IMO when one asks new symbol inclusion, he/she should give a justification. For example:
* ¼ (one fourth): seems already supported by synthesizers. So give a synthesizer example where this symbol is badly or not announced
* all subscript and superscript: give an example of real life where they are used
Maybe also the level should be justified.

**Comment by gregjozk** [comment]
As a slovenian translator of NVDA I will gladly cooperate with you and slovenian gnome/orca translator.

**Comment by bhavyashah** [comment]
I would really really really appreciate the answers to the questions posed in https://github.com/nvaccess/nvda/issues/11105#issuecomment-623928682. I am going through a Math textbook and I have come across several critical symbols some of which ESpeak-NG reads but Eloquence doesn't, some of which Eloquence reads but ESpeak-NG doesn't, and some of which neither read. Restating the relevant questions as under:
* Is there a performance penalty for adding too many symbols? If not or negligible, can we add all the Unicode symbols there exist?
* If there is a non-trivial penalty, what is the bar we set for including or excluding a symbol from NVDA itself?

**Comment by bhavyashah** [comment]
I would request someone to please answer my questions in https://github.com/nvaccess/nvda/issues/11105#issuecomment-670353382. Otherwise, I will go ahead and create a new issue about adding some critical Math symbols to NVDA.

**Comment by gregjozk** [comment]
Hi,

see PR "Added some mathematical symbols" #11467 opened by @Adriani90
maybe it would help.

best regards,
Jožef

2020-08-10 8:46 GMT+02.00, bhavyashah <notifications@github.com>:

**Comment by Adriani90** [comment]
To answer @CyrilleB79's and @bhavyashah's questions,
1. Regarding subscripts and superscripts, these symbols are often used in physics or mathematics when writing formulas or postulates.
2. Regarding performance, there is not a standard answer on this, it depends on the symbol. I think the only way to find out where the limit is, is to add important symbols in different tranches and test where the performance gets lower. With the mathematical symbols I didn't experience any performance lags.
3. Regarding the limit we set for including and excluding symbols, not every symbol is needed. But there are certain domains where important symbols can be added, i.e. mathematical symbols, musical symbols, etc. However, even in these domains, one has to assess which symbols are commonly used and which would cover the most use cases. I can speak for mathematical and physics because I absolved advanced courses in these domains, but I cannot speak for musical symbols. However, there are lots of forums where you can get a rough idea of which symbols are most important. So in the end some one who likes to implement symbols into NVDA should assess their need from a qualitative perspective.

And last but not least
4. Adding symbols to NVDA's dictionary means they will be spoken by every synthesizer. Otherwise there are some synths who suport certain symbols, and many others which do not support them. Integrating as many symbols into the NVDA ssymbol dictionary at least guarantees kind of consistency on how they are pronounced etc. How ever, as mentioned above, the qualitative assessment needs to be considered via testing and looking at the performance limits.

**Comment by bhavyashah** [comment]
Thank you so much @gregjozk  and @Adriani90 .
Here is a proposition from me: the fact that Unicode has encoded a symbol as a distinct character means that every Unicode character is used, some more than others. Given that we don't know if there is a limit to how many symbols we can add, let us assume that none exists. Therefore, let us add every Unicode symbol - regardless of our assessment of the extent of their usage - to NVDA.
* If we notice no performance penalty, then all is well and we have just resolved the issue of some symbols important to some people missing in NVDA once and for all. (Unicode could come up with new ones in the future, yes, but the point still largely stands.)
* If we notice only a slight performance penalty, we can figure out the least useful groups of these symbols and work on identifying and removing them. I think elimination of chunks would be easier than adjudecating every newly requested symbol's utility on a case-by-case basis.
* If we notice a significant performance penalty, we can revert to the status quo.
Do you think it would be too much work in terms of implementation in compiling and adding all Unicode symbols to NVDA, or can that be automated?
Please share your thoughts on the above suggestion.

**Comment by gregjozk** [comment]
Hello,

wiktionary.org has ahuge collection of symbols sorted by categories on
unicode version 13. from users perspective I adore inclusion as many
ssymbols as possible, this would be a nightmare for translators
though. so I suggest, that groups of symbols could be added to NVDA
via addon such as it has been made with emoticons addon authored by
@nvdaes.
source: https://en.wiktionary.org/wiki/Category:Unicode_blocks

best regards,
Jožef

2020-08-10 23:31 GMT+02.00, bhavyashah <notifications@github.com>:

**Comment by nvdaes** [comment]
Just to clarify: the primary author of Emoticons add-on, who added
regular expressions and emojis, is Christianlm.
me (@nvdaes) contributed and maintain this add-on, with other collaborators.

2020-08-11 5:34 GMT+02:00, gregjozk <notifications@github.com>:

**Comment by gregjozk** [comment]
Hello,

thanks for clarification. I wrote this from memory.
and I'm very sorry due to I did not mension and remember other authors.

regards,
Jožef

2020-08-11 6:03 GMT+02.00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Don't worry. :)
Thanks for mentioning our add-on.

2020-08-11 10:05 GMT+02:00, gregjozk <notifications@github.com>:

**Comment by bhavyashah** [comment]
Thanks so, so much for the Wiktionary link. I can see how this might get overwhelming for translators. To be clear though, I think just because something is difficult to translate and make available to all NVDA users, it does not follow that the feature should not be included, Eg the User Guide. Not saying that @gregjozk is advocating for that, but just clarifying preemptively. Whether included in core or in an add-on, I think the inclusion of symbols would be immensely valuable both ways. Is this request something you may be able to take care of by any chance? @nvdaes @Christianlm @Adriani90

**Comment by nvdaes** [comment]
I will reply for your mention, thanks for your confidence.
For my part, I'm not a translator, just a person who has contributed
or initially developed some add-ons included in the add-ons website
(just some of my add-ons were accepted). So, what I may do is
contributing to investigate how to develop an add-on with different
symbols, which maybe translated and installed optionally, like the
regular expressions (and emojis) created by @Christianlm.
But the add-ons translations system is not working properly and there
is nothing that community members can do. When @NVAccess has enough
time, they may work on the system. For now I think that this cannot be
managed via an official add-on, since symbols couldn't be translated.
There are people sharing and translating add-ons out of the NVDA's
official system and this maybe a solution. Personally, I prefer to
work just in an official way so that people can find add-ons easily
and in a space created to find and share bugs like the add-ons mailing
list created by @Josephsl, so I have stopped working in add-ons until
NV Access can fix issues with the translators system and others.

2020-08-12 0:19 GMT+02:00, bhavyashah <notifications@github.com>:

**Comment by Christianlm** [comment]
> 
> IMO when one asks new symbol inclusion, he/she should give a justification.
> 

I agree with @CyrilleB79. 
Furthermore, many symbols establish a diferent reading behavior, depends on the language of the synthesizer.

For example:
Superscript o, in Italian and Spanish, maybe in other languages too, is used for ordinal numbers.
E.g. 10º must be read in italian "decimo" instead of 10 superscrip o.
Same thing for superscript a character.

Another example:
In Spanish, the characters "¡" "¿" add  a slight pause by changing the intonation of the part of the sentence that precedes it.
These behaviors are part of the synthesizers like sespeak-ng, eloquence, Loquendo, Microsoft SAPI5.
I know the problems mentioned in my examples can be solved by the translators  in the symbols.dic specific for languages, 
but how many translators know the behavior of the synths used?
