### ISSUE TITLE
Several options of nvda dialogues are not translated into Brazilian Portuguese

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11138]
### Steps to reproduce:
Run nvda with the Brazilian Portuguese language
### Actual behavior:
Controls are not translated
NVDA Language (requires restart):
Save configuration when exiting NVDA
Start NVDA during sign-in (requires administrator privileges)

Start NVDA after I sign in
Use currently saved settings during sign-in and on secure screens (requires administrator privileges)

Audio output  device:

Speech interrupt for typed characters

Speech interrupt for Enter key

Beep if typing lowercase letters when caps lock is on

Speak command keys

Simple review mode

Guess object position information when unavailable

Report background progress bars

Font attributesFont attributesFont attributesSuperscripts and subscripts

Report formatting changes after the cursor (can cause a lag)

Cell borders:

### Expected behavior:
The options must be translated, this is a regression in the latest alpha versions
#### NVDA version:
alfa 20175

#### Windows version:
10 18362
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by josephsl** [comment]
Hi, possibly because translations were not merged yet into alpha (I wouldn’t worry about translations in alpha builds much as alpha builds are meant for early testers and things (including messages) can change). Thanks.

**Comment by Adriani90** [comment]
@fernando-jose-silva are you seeing this issue also in the stable version NVDA 2020.1?
@josephsl these characters are not translated in other languages as well even though there is a translation in the .po file in place. I reported this on NVDA's translations list and you said this is due to a fix in the accelerations in Python 3 and that this would affect only alpha users. For how long will this affect alpha users and will this be fixed in any stable version in the future?

**Comment by josephsl** [comment]
Hi, it will be fixed once alpha comes to beta and translators are willing to correct and commit translations. Thanks.

**Comment by Adriani90** [comment]
Thanks Joseph for the comment. I just also noticed that the milestone for that PR has been moved from 2020.1 to 2020.2.
@fernando-jose-silva if you will not see this translated in the future version, please contact the translator privately or via the translators mailing list at
https://groups.io/g/nvda-translations

I am closing this issue for now since this is related to translators, and their willingness to contribute.
