### ISSUE TITLE
IE11 + NVDA - After dialog is opened and closed next actionable element not getting triggered using enter / space key

### ISSUE THREAD

**Issue by vinaychaudhary1504** [nvaccess/nvda#11154]
### Steps to reproduce:
Open Link : https://dequeuniversity.com/library/aria/simple-dialog
Navigate using tab and open dialog box and close it through enter key then navigate to next actionable item.
So after closing dialog box next actionable item is not getting expand through Enter/Space keys.
This is not always reproducible its like intermittent issue on IE with NVDA.

### Actual behavior:
After closing dialog next actionable item not getting triggered using Enter/Space keys.

### Expected behavior:
After closing dialog next actionable item should be triggered using Enter/Space keys.

**Comment by Brian1Gaff** [comment]
Somebody is bound to ask you to fill in the other bits of the template here. 
I cannot say using IE 11 on windows 7 as I need to from time to time has 
thrown u p any issues, so its a good plan to test what the template asks and 
let us know what occurs.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by DrSooom** [comment]
Possible workaround: Press the ALT key twice.

**Comment by Adriani90** [comment]
Support for IE11 has completely ended in 2022 and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I am closing this as abandoned since I don't expect any updates for accessibility for IE11 or for the IE mode in Microsoft Edge. If you have this issue with other browsers, please open a new one with the updated steps to reproduce.
