### ISSUE TITLE
Table columns are not read correctly.

### ISSUE THREAD

**Issue by ajay1208** [nvaccess/nvda#11239]
Steps to reproduce:
1. Open test case at https://yrxvljpdjkj.angular.stackblitz.io/
2. Do read All. Tables are not read correctly

Actual behavior:
Reading extra columns and not reading as expected. And not read in correct align and reading "no" at each end of row.

Expected behavior:
Read correctly

System configuration
NVDA installed/portable/running from source:
https://www.nvaccess.org/files/nvda/releases/2020.1/nvda_2020.1.exe

NVDA version:
2020.1

Windows version:
Windows 10 Pro

Other information about your system:
Other questions
Does the issue still occur after restarting your computer?
Yes

**Comment by JulienCochuyt** [comment]
@ajay1208, browsing the provided URL, all I get is "Starting dev server"

**Comment by leonardder** [comment]
Same here.

**Comment by feerrenrut** [comment]
@ajay1208 If you are comfortable testing an in-development version of NVDA, please let us know if the following fixes the issue for you:
[PR build of #11245](https://ci.appveyor.com/api/buildjobs/1buy31ln5u63o3t4/artifacts/output%2Fnvda_snapshot_pr11245-20278%2C9fff778a.exe)

**Comment by ajay1208** [comment]
Can you try https://jlenrjrljlb.angular.stackblitz.io

**Comment by Adriani90** [comment]
@ajay1208 it's still not working. The page does not load. However, this issue is solved by #11245. I am testing with NVDA alpha-20339,975d39d1 and the table in my example above reads cell by cell as expected, without any double reading or incomplete reading.
Maybe the focus is jumping around on your example, please try to switch off automatically set focus to focusable elements by pressing nvda+8. This should solve the problem if it is still occuring.
You can download the last alpha from here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
These being said, I am closing this issue as works for me. If you are still having this problem with the last alpha version of NVDA, please comment on it and we can reopen.
