### ISSUE TITLE
The portable and temporary  versions of NVDA are unresponsive in installers

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11252]
### Steps to reproduce:
1- Open a setup program except the NVDA setup
2- Try to go through the installation process like normal
3- You will see that in the license agreement or some screen, NVDA portable/temporary copy will stop responding and begin to read the license agreement, it does not interrupt no matter which key you press
### Actual behavior:
NVDA portable/temporary copy will not respond to any key input when inside an installation window
### Expected behavior:
NVDA portable/temporary copy will respond like NVDA installed version
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2020.1
#### Windows version:
windows 10/1909
#### Name and version of other software in use when reproducing the issue:
An installer program
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I trie 2019 and it was the same
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by DrSooom** [comment]
@fatihyuksek1: This isn't a bug, it has to do with admin privileges. You can run a portable copy of NVDA as an administrator (not recommend) via the corresponding context menu entry to get also access to Installers which are asking for these privileges (UAC appears).

**Comment by fatihyuksek1** [comment]
Thanks so much for your interest

Отправлено с iPhone

**Comment by Adriani90** [comment]
We had this problem often, I also saw this in other programs using portable versions of NVDA. This problem disappears if you start the coresponding setup as administrator. Or you start NVDA as administrator. Unfortunately due to system proviledge restrictions we cannot do anything about this in NVDA so far, this is also subject to external fixes in Windows from Microsoft. Please feel free to report such issues also to Microsoft. I am closing this issue for now.
