### ISSUE TITLE
Correct pronunciation of Hawaiʻi

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11254]
### Steps to reproduce:

Have NVDA read the word:
Hawaiʻi

That is the traditional native spelling of Hawaii which uses the backward apostrophe (called okina; hex code is 02BB) like so:  Hawaiʻi.  The okina is actually part of the Hawaiian alphabet along with the macron (the horizontal line atop Hawaiian vowels when the word calls for it).

### Actual behavior:

NVDA reads Hawaiʻi as
"Ha-wee" (OneCore)
or
"Ha-wa-02BB-eye" (eSpeak-NG)

### Expected behavior:

We've had a request from a user to consider incorporating the okina as basically a glottal stop in the pronunciation, nothing more.

Although pronunciation is generally a synthesizer issue, because this is the pronunciation of a large, well known place name, I felt it was worth creating an issue to add a default dictionary entry for (and I will also raise it with eSpeak-NG and Microsoft).

#### NVDA version:
2020.1 Installed

#### Windows version:
Windows 10, 1903 18362

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but likely the same.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment]
Actually this is not easy to solve. There are many ways to pronounce Hawaiʻi, even in the native language. The w can be pronounced as a v, the first i from Hawaiʻi can be skipped so that we have Hawa...i.
So there is no consistent pronounciation out there and if we add a glottal stop there, then also the w should sound like a v when pronouncing.
Note that there are some more glottal stops used in the Hawaiian language. So I think this can be only acomplished by the synthesizers themselves by adding for example a variant for hawaiian language.

Even if we manually add a glottal stop in NVDA, some synthesizers would interpret it in their own way and the pronounciation will not be consistent.

Here is an example of how different Hawaii is being pronounced.
https://www.youtube.com/watch?v=nfbceGBSSrY

@Qchristensen what do you think?

**Comment by Qchristensen** [comment]
I got the original information as a request from someone at the University of Hawaiʻi, and I figure they know better than I do how to pronounce it.

In passing the information on to Microsoft, I got a reply from someone who said: I lived in Hawaii — you want it pronounced “Ha-why—E”

I'm happy to leave this one up to the Hawaiian linguists to resolve :)

**Comment by Qchristensen** [comment]
Clarification from eSpeak-NG that they have recently added Hawaiian language support and this should work if the language is set to Hawaiian (and if we updated to a build of eSpeak-NG newer than April: https://github.com/espeak-ng/espeak-ng/issues/773#issuecomment-643636406).  In English (which I believe this issue is reported for), the issue is still present.
