### ISSUE TITLE
NVDA reads wrong column header with table with colspan's and role="none"

### ISSUE THREAD

**Issue by Twistie** [nvaccess/nvda#11435]
When there is a table that has some cells hidden with `role="none"`, incorrect headers are read.

### Steps to reproduce:
Navigate through the table in the html file attached
[tabletest.zip](https://github.com/nvaccess/nvda/files/4991917/tabletest.zip)

### Actual behavior:
"Extra Header" is read as the header for "Table Cell 1", "Column Header 1" is read as the header for "Table Cell 2" etc
![tableread](https://user-images.githubusercontent.com/2356344/88745474-829ad300-d18d-11ea-9fcf-cedd14e23904.png)

### Expected behavior:
The headers read should be from the cell above them, not including skipped cells from role="none"
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Chrome
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
No addons added
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment]
cc: @ObjectInSpace

**Comment by ObjectInSpace** [comment]
Firefox has the opposite behavior: it reads the correct column header, but NVDA's column announcements are off. It says "column header 1 column 2 table cell 1." Whereas Chrome is saying "extra header column 1 table cell 1." The expectation would be for the screenreader to read "column header 1 column 1 table cell 1," yes? This does not occur in this example with any browser/screenreader combination I tested

**Comment by Qchristensen** [comment]
I've had another user report this.  I can replicate by modifying the W3Schools colspan example so the colspan row is under the header (it breaks reading the correct column below that):

<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>

<h1>The td colspan attribute</h1>

<table>
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td colspan="2">Sum: $180</td>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
  <tr>
    <td>February</td>
    <td>$80</td>
  </tr>
</table>
 
</body>
</html>

(If anyone is interested, the W3Schools page is at: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_td_colspan)

**Comment by Adriani90** [comment]
Yeah this is also reproducible in NVDA 2024.3 Beta. Actually the role="none" should not be exposed to the virtual document at all, similar to role="presentation". @jcsteh is this correct?

Setting role="none" on the extra header does solve this particular issue, but it is still exposed to the screen reader in the virtual document.

Also wehn using vertical navigation (assigning a gesture for it in the input gestures dialog) proves that the cell with content role="none" is vertically aligned with extra header. So in this case, if extra header doesn't have role="none", pressing ctrl+alt+down or up arrow key should report "edge of table".

cc: @SaschaCowley

**Comment by jcsteh** [comment]
I disagree with the expected results in this bug. Firefox now behaves the same as Chrome: "Table Cell 1" gets "Extra Header".

When you specify role="none" on a table cell, you're effectively saying it doesn't exist as a cell. Therefore, "Table Cell 1" really is row 2 column 1, and thus the column header above it is row 1 column 1, "Extra Header".

In the past, Firefox viewed tables more from a visual layout perspective, hence the behaviour described in https://github.com/nvaccess/nvda/issues/11435#issuecomment-666771559 where Firefox reported "column 2" instead of "column 1". But based on author demand and based on a strict interpretation of the spec, role="none" should make the table cell cease to exist for accessibility purposes. You can't have it both ways. It's either based on visual layout (in which case role="none" is meaningless) or it's purely semantics (in which case row 2 column 1 gets its header from row 1 column 1).
