### ISSUE TITLE
Error on Mozilla Thunderbird: Messages are not read

### ISSUE THREAD

**Issue by ruifontes** [nvaccess/nvda#11458]
### Steps to reproduce:
Open Mozilla Thunderbird
Select a message and press Enter to open it.
Try to read it with NVDA+down arrow or with the arrows.

### Actual behavior:
Nothing is read.

### Expected behavior:
The message should be read.

### System configuration
DELL Latitude E7470
Processor: i5-6300U
RAM: 16 GB

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
aalpha-20666,e2675e2a

#### Windows version:
Windows 10 2004 64-bit

#### Name and version of other software in use when reproducing the issue:
Mozilla Thunderbird 68.11.0 (32-bit)

#### Other information about your system:
NA
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. It just happened with the update of August, 3...

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by ruifontes** [comment]
Sorry, but strangely restarting with add-ons deactivated didn't solve the problem, but deactivating all add-ons manually solved...
The add-on that causes the not reading of messages is NVDAExtensionGlobalPlugin

Going to close the issue

**Comment by Brian1Gaff** [comment]
I've seen several Mozilla related messages around these lists since 
yesterday or maybe the day before. I suspect some code clean ups have 
compromised use with older versions of Mozilla code and some of the add ons 
nvda uses to help navigate them. I'm using Waterfox, but up to now have not 
seen any issues, even though it  is Waterfox Classic. Though slower than 
Firefox this browser is normally a bit better  on showing everything than 
latest firefox or chrome.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
