### ISSUE TITLE
Error in MS Word when pressing nvda+shift+h

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11465]
### Steps to reproduce:
1. Open NVDA
2. Open a Word document
3. Press nvda+shift+h

### Actual behavior:
NVDA plays an error sound and following error is written to the log:
```
IO - inputCore.InputManager.executeGesture (20:49:12.247) - winInputHook (11156):
Input: kb(laptop):shift+NVDA+h
ERROR - scriptHandler.executeScript (20:49:12.262) - MainThread (14468):
error executing script: <bound method WordDocument.script_reportCurrentHeaders of <NVDAObjects.IAccessible.winword.WordDocument object at 0x026340F0>> with gesture 'Umschalt+NVDA+h'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "NVDAObjects\IAccessible\winword.pyc", line 260, in script_reportCurrentHeaders
  File "comtypesMonkeyPatches.pyc", line 82, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 729, in _invoke
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2146822347, None, ('Das angeforderte Element ist nicht in der Sammlung vorhanden.', 'Microsoft Word', 'wdmain11.chm', 25421, None))
```

### Expected behavior:
The script sugerates that NVDA should report current heading. However, I don't remember such feature being implemented in NVDA ever. Expected is either reporting of current heading if any, or "no headings" in case there are no headings in the document.
Otherwise report "not supported".

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Version: alpha-20677,8f1d6c88

#### Windows version:
Windows 10 2004 update

#### Name and version of other software in use when reproducing the issue:
MÎcrosoft Word 365

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by Adriani90** [comment]
cc: @CyrilleB79, @lukaszgo1

**Comment by CyrilleB79** [comment]
This script was introduced by resolving #3110 with commit 465dce884358f21dc245d06cf6a4289d77be6bc0.
The commit's comment is as follow:

> Support for automatic row and column header reporting in Microsoft Word. Like Excel, NVDA+shift+c and NVDA+shift+r set the column headers or row headers respectively, Jaws-compatible headers are imported from the document, and these settings are stored in the word document in a Jaws-compatible format.

The script script_reportCurrentHeaders bound to NVDA+shift+H is aimed to report column and row headers when you are in a table and work in this situation. However:
* When you are not in a table, you get the error described in this issue; a user friendly message indicating that this command only works in tables should be reported instead.
* This script has no documentation for help mode and is not documented either in NVDA user guide. This should be added. @Qchristensen is there any trace of this command in the training material?
* The reported message is in English; it should be made translatable.

If agreed, I suggest to fix these 3 points in a single PR.

Also slightly linked to [this comment](https://github.com/nvaccess/nvda/issues/3462#issuecomment-155309039) in #3462 even if in the script of this issue, it is linked to Word only?.
If we choose to report cell coordinates in this script in addition to row and column headers, I would suggest a separate PR, being an enhancement.

An other option could be just to remove this script if considered not useful.

CCing @michaelDCurran the author of this script. Was it a forgotten debug script or a not completly achieved script?.

@Adriani90, just for curiosity: what was the use case when you have used such a keystroke?

**Comment by Adriani90** [comment]
@CyrilleB79 thank you for the thorough investigation, this is very helpful.
I have discovered this actually by chance, I didn't know that there is a feature which allows you to report the current heading in a table. Nevertheless, this feature would be really helpful, not only in MS Word but also in MS Excel because if you set the row and column headers NVDA reports them after the whole cell content which can be really frustrating. So such a key stroke would help anyway in many cases.
But first of all, I agree with your suggestions above.

**Comment by Qchristensen** [comment]
I wasn't familiar with this keystroke either.  Given it works in Word and not Excel, and isn't otherwise documented, I expect it was likely setup for debugging - perhaps when implementing setting row / column headers.

My personal inclination, rather than using NVDA+shift+h, is whether we could instead add this information to either NVDA+tab or NVDA+delete (given those two keystrokes are already used to find out information about where the focus is, and hopefully users already know them - rather than teaching another keystroke to find out "where you are" specifically for use in a table only).

**Comment by Adriani90** [comment]
@Qchristensen not sure if users would like this, because nvda+tab or nvda+del tells you the currently focused element or its screen coorinates. But nvda+shift+h delivers kind of a title information, like i.e. nvda+t for window title. So if possible, I would still vote for nvda+shift+h. Anyway, this would also be not far away from nvda+shift+r or nvda+shift+c which are used to assign the headers to a table. Moreover, I am sure more features regarding to table navigation will come in the future, so sooner or later users will need to learn additional key strokes for efficient table navigation anyway.

**Comment by Adriani90** [comment]
Update: the error is still occuring when not in a table and when UIA for Microsoft Word is disabled. when enabling UIA in Microsoft Word, the error seems not to appear, instead the function is overwritten by MS Word and a h is being typed. So it seems the key strok nvda+shift+h does not work in MS Word when UIA is enabled. cc: @michaelDCurran note that that when creating a table and pressing nvda+shift+h, the reporting "row empty, column empty" is not translated. So it seems this featur is not even documented in the transation system of NVDA.

**Comment by CyrilleB79** [comment]
In reaction to @seanbudd's https://github.com/nvaccess/nvda/pull/15867#discussion_r1421844244:
> would you consider implementing this?

As I have written in https://github.com/nvaccess/nvda/pull/15867#discussion_r1420171618:
> This script (`script_reportCurrentHeaders`, `NVDA+shift+h`) is a remaining debug script (see #11465). It is undocumented: no description in the User Guide, nor visible in the Input Gesture dialog. So I doubt anybody is using it.
My opinion is that it should just be deleted to close #11465.

@seanbudd, I can do it immediately  with the adapted justification in the PR if you agree with this approach.

I have also written:
> And if a script is needed to report headers in tables, it should be discussed in a new feature request, not only for word but for any table (Word, Excel, HTML). 

Have people expressed this need? The current issue has clearly not been open because the need of this feature, but because the script has been activated by chance and has produced an error in the log.

If this need has not been expressed in another issue nor on the lists, I'd recommend to do nothing else. I guess that most people who want to know row/column headers usually activate headers reporting and can hear the headers when using table navigation commands.
If this need has been expressed elsewhere than in an issue, a new issue should be opened with an adapted description.
@Adriani90, @Qchristensen any input on this? Are there existing feedback from real-life situations on this topic?

@seanbudd, if such issue is opened or already exists, I am not sure to take it over however, or at least not with a high priority.

**Comment by Adriani90** [comment]
@CyrilleB79 I agree, nothing else to add.

There is currently no issue which request calling row or column headers on demand by pressing a key stroke.
