### ISSUE TITLE
Announcing on date format (dd/ mm/yyyy) mm as millimetre and NI number as nickle number.

### ISSUE THREAD

**Issue by RituAdhikari** [nvaccess/nvda#11594]

**Comment by Adriani90** [comment]
This is an issue in the synthesizer. Please contact the vendors of the synthesizer, i.e. Microsoft in case of One core voices, or create for example an issue agains eSpeak at
https://github.com/espeak-ng/espeak-ng 
if this is occuring with eSpeak.

I am closing this issue here. Thanks for reporting though.

**Comment by RituAdhikari** [comment]
Hi

I have checked, changing the language to United States it announce
correctly.

For british eng it announce millimetre for mm in dd/mm/yyyy.
But for united states it announce correctly.
