### ISSUE TITLE
Command Line Switches: Addition of short switches for their long counterparts

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11644]
### Is your feature request related to a problem? Please describe.

NVDA offers several command line switches that can be used. Some of these switches offer both short and long versions - could we possibly consider adding short versions of the following? This would have the potential to speed up the workflows of power users/system admins when manually typing out these switches at regular intervals:

--disable-addons - consider adding a "-noaddons" switch to perform this task

--debug-logging - consider adding a "-debuglog" switch to perform this task

--no-logging - consider adding a "-nolog" switch to perform this task

--no-sr-flag - consider adding a "-noflag" switch to perform this task

**Comment by XLTechie** [comment]
> NVDA offers several command line switches that can be used. Some of these switches offer both short and long versions - could we possibly consider adding
> short versions of the following? This would have the potential to speed up the workflows of power users/system admins when manually typing out these
> switches at regular intervals:

I very much agree with the concept here.
Alternate short forms should be available for everything possible.

> --disable-addons - consider adding a "-noaddons" switch to perform this task

Regarding this and your other suggestions: that breaks the getopt/GNU standard 
of only using a single dash for single letter options.
The reason that is a thing, is a use case like the following:

You have options:
--disable-addons (-d)
--debug-logging (-D)

You could then do:

nvda -D -d

But, if you're in a real hurry you could do:

nvda -Dd

If you're passing a boatload of options, that latter format can be helpful.  It 
also doesn't work at all if multi-letter options are allowed after a single 
dash.

I don't actually know if the option combining method works with NVDA's option 
processor, but standards exist for a reason, and that's the reason for that one.

So if you're proposing single hyphen options, which I fully support, please 
consider proposing only single-letter versions.

**Comment by elliott94** [comment]
Makes perfect and logical sense - thank you too for adding info about these standards. :) So how about:

--disable-addons - consider adding a "-d" switch to perform this task

--debug-logging - consider adding a "-D" switch to perform this task

--no-logging - consider adding an "-n" switch to perform this task

--no-sr-flag - consider adding an "-N" switch to perform this task

Depending on feedback, happy to edit the initial description with these alternative switches.

**Comment by XLTechie** [comment]
First, NVDA does in fact support option combining as I mentioned (-Dd), according to user guide section 16.1.

Second, I'm not really clear on the value of the --no-logging option. That should be doable with "-l 0" or "-l 255" or something, even if it isn't now.  So I'm not sure I support a short option for that, since I don't see the need for having the switch at all.

Third, I think the --portable-path=PORTABLEPATH switch should go away, and the portable creation options should require a pathspec.

Lastly, here is my list of suggestions for short options, incorporating those of yours with which I agree:

SHORT | LONG
:---: | :---
-d | --disable-addons
-D | --debug-logging
-R | --no-sr-flag
-i | --install
-I | --install-silent
-E | --enable-start-on-logon=True|False
-p | --create-portable
-P | --create-portable-silent

Note regarding -E: it is an uncommon option, so I capitalized it.  Rather keep the lowercase for something more valuable.

@feerrenrut @josephsl : thoughts on the reasonableness of any of this?
I come from a Linux background, so it feels wrong to me if there aren't short switches for the vast majority of the CLI options.

**Comment by feerrenrut** [comment]
I would prefer only adding short switches for commonly typed options. Adding short form for all options doesn't seem to solves any specific issue. Short form is useful for regularly typed options. If an admin is configuring a script or shortcut, it would be more sensible to use the long form since it is self documenting the intent.

**Comment by Adriani90** [comment]
cc: @gerald-hartig for triaging.

**Comment by CyrilleB79** [comment]
I have the same opinion as Reef (see https://github.com/nvaccess/nvda/issues/11644#issuecomment-706166380), i.e. only adding short switches for commonly typed options.

Personally, I commonly type: `--disable-addons`, `--debug-logging` and `--lang`. If `--lang` is finally not selected in the short option subset, that's not a big problem because "`--lang en`" is not much longer than "`-G en`".

**Comment by gerald-hartig** [comment]
Closing as per Reef's comment.

**Comment by CyrilleB79** [comment]
I agree not to define a short switch for any option, especially for those only used in sysadmin install scripts.

Though, there are still commonly used options without a short switch:
* `--lang`
* `--disable-addons`
* `--debug-logging`

The actual question is: how do you define "commonly used"? Basic NVDA usage does not need to use command line. Thus the two most common usages IMO are:
1. A user has issues with NVDA and is instructed by someone else to launch NVDA with specific options. Providing a command line is much more synthetic than instructing to set or unset option X or Y.
2. An NVDA or add-on tester wants to test NVDA with settings that he does not usually uses, e.g. change language, disable add-ons, etc.

Thus, here is my proposal to introduce 3 other short switches:
* `-d` for `--disable-addons`
* `-g` for `--debug-logging`
* `-L` for `--lang`, or `-n` if we don't want or can't use case sensitive switches

All other switches are meant to be used in scripts IMO.

@gerald-hartig or @seanbudd would you accept a PR implementing this proposal?

**Comment by seanbudd** [comment]
I think switches for lang and disabling add-ons makes sense.

Wouldn't using the log short switch `l -10` be sufficient for debug logging?

**Comment by CyrilleB79** [comment]
> Wouldn't using the log short switch `l -10` be sufficient for debug logging?

Well, if I want to provide a debug log to debug an add-on, typing "`nvda -gn en`" is shorter than "`nvda -l 10 -n en`".

Reopening to implement only the 2 or 3 most common switches.

**Comment by seanbudd** [comment]
@CyrilleB79 - the debug logging switch is redundant and longer than the alternatives. `--log-level 10` and `-l 10` are both shorter. I think we would drop it if it wouldn't be a breaking change. I don't think we should be adding (minor) complexity to it.
For short switches we plan to only accept:

`-n or -g for --lang` and `-d for --disable-addons`.
