### ISSUE TITLE
Secure Screens: Consider re-enabling the Log Viewer, but keeping the ability to save a log disabled

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11646]
### Is your feature request related to a problem? Please describe.

When NVDA is run within a secure screen, we disable several elements of the GUI - one of these includes the Log Viewer. For system admins, having access to this component can be useful - for example, when diagnosing issues whereby add-ons refuse to load on secure screens, but work without issue under a standard user. Could we possibly consider re-enabling this - but keep the ability to save logs disabled so that users don't have access to browse the system folder structure when choosing to save a log?

**Comment by Mohamed00** [comment]
Doesn't the ServiceDebug registry setting do this already?

**Comment by lukaszgo1** [comment]
I don't think log viewer is disabled only due to browse  dialog being a security risk. Imagine the following scenario:
1. The configuration copied to the secure screens has the log level set to input/output therefore every keystroke even these typed into password fields are written to the log.
2.  User types his/her password and has to leave his computer for a moment before pressing enter for whatever reason.


In this case his password is present in the clear text for everyone  who knows that NVDA+F1 opens log viewer which is unacceptable security risk. If you need to enable logging for secure screens temporarily ServiceDebug is a better option.

**Comment by elliott94** [comment]
Makes logical sense to use this registry value if/when required - thank you both. :) Closing.
