### ISSUE TITLE
GUI: Consider only allowing a single dialog to be displayed at once upon initial config creation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11679]
### Is your feature request related to a problem? Please describe.

When NVDA initially creates its configuration under a user account that has no existing configuration, depending on conditions it's possible to potentially have three separate dialogs appearing on screen in quick succession:

1. The initial Welcome dialog

2. The Update dialog

3. The Gather Usage Statistics prompt

For new users, the possibility of all these dialogs appearing at once has the potential to be overwhelming. Could we possibly consider changing this behaviour so that only a single dialog can appear on screen at once? Logically, it'd probably make sense for the Welcome dialog to initially be displayed, followed by the Usage Statistics prompt second, and finally the result of an update check (if an update is found).

**Comment by Brian1Gaff** [comment]
One of the issues I get is an add on update and a program update occur 
almost at the same time, and whichever one actions, the other one will not 
return, since you are restarting nvda. Sometimes though the add on one does 
attempt to come up at restart but nvda can  fall over for some reason.
 Its a pity some kind of precedence could not be used here before confusing 
the user with two dialogues.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment]
Duplicate of issue #9174.

**Comment by elliott94** [comment]
Thank you - closing as a duplicate.
