### ISSUE TITLE
LibreOffice Writer: Statusline is not announced

### ISSUE THREAD

**Issue by peterpacult** [nvaccess/nvda#11698]
### Steps to reproduce:
1. Open Writer
2. Request announcement of status line with screenreader

### Actual behavior:
The screenreader announces  "No informatiion in status line".

### Expected behavior:
status line is announced

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.2

#### Windows version:
Edition	Windows 	10 Home
Version				1909
Operating system build	18363.1016

#### Name and version of other software in use when reproducing the issue:
LibreOffice
Version:	7.0.0.3 (x64)
Build ID:	8061b3e9204bef6b321a21033174034a5e2ea88e
CPU-Threads: 	4; BS: Windows 10.0 Build 18363; UI-Render: Skia/Vulkan; VCL: win
Locale: 	de-DE (de_DE); UI: de-DE
Calc: 	threaded

#### Other information about your system:
---
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Not tested.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not tested.

**Comment by peterpacult** [comment]
The issue has also been reported to the Document Foundation; see https://bugs.documentfoundation.org/show_bug.cgi?id=137075

**Comment by Natomaspiper** [comment]
The problem now occurs in LibreOffice 7.5.3 on Windows 11 home system using NVDA 2023.1.  the Windows restart, run NVDA com registration fixing tool, and start NVDA without add-ons were done and the problem was not fixed.

**Comment by XLTechie** [comment]
@michaelweghorn would you be able to lend a prospective on this?

**Comment by michaelweghorn** [comment]
> @michaelweghorn would you be able to lend a prospective on this?

@XLTechie : Yes, pull request: #14933

**Comment by Natomaspiper** [comment]
Since I did not get a clarifying message, I will restate my
observations.  I did some more testing with both NVDA and MS Narrator
screen readers using the LibreOffice provided download for 7.5.3.2 SDK. 
As a non developer, I am slightly concerned that when using search
engines all results direct everyone to a developers version instead of
an end user version.  Both screen readers did not "see" any control to
add a LibreOffice desktop shortcut. In version 7.5.3.2, I was unable to
find any obviously named executable in the program files folder so  I
cannot recreate the problem that I originally reported.  The problem is
now even worse as I cannot even start LibreOffice or any of its
components.  On the assumption that the previous version that I tried
was 7.5.2.X, please advise me on how to get the earlier version so I can
test with it.

**Comment by michaelweghorn** [comment]
@Natomaspiper If I understand correctly, this is about a checkbox in the LibreOffice installer not being exposed by the screenreader, which is unrelated to the issue described here.

Let's please keep that separate from the issue here to keep focus, s.a. my comment in https://bugs.documentfoundation.org/show_bug.cgi?id=137075#c9 .
