### ISSUE TITLE
Rename focus highlight feature with a more adapted name

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11700]
### Steps to reproduce:

* Open vision setting panel or NVDA user guide.
* look at Focus Highlight section 

### Actual behavior:

The feature is called Focus Highlight. But it may highlight not only system focus but also the navigator objetct and the browse mode cursor.

### Expected behavior:

A clearer name should be found for this feature. What about "Visual Highlight"?
We would lose the idea that these highlighters follow a localized object moving around the screen such as the focus or a cursor. But this would at least allow not to use the term 'focus' for the navigator object or a cursor (browse mode one).

### Notes and context
English is not my mother language so maybe there is no problem in English. In the French translated UI, it sounds strange to me that the object navigator and the browse mode cursor options belong to the Focus Highlight group.
Note that this issue is just a matter of terminology. I do not intend to change the organization of the Vision panel options. And it makes sens to me to have a group of visual highlighters containing focus, nav object and browse mode cursor.

#### NVDA installed/portable/running from source:
Instlaled
#### NVDA version:
2020.3beta2
#### Windows version:
10
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same as 2019.3

**Comment by leonardder** [comment]
It might be interesting to note that the feature was first called NVDA Highlighter. Visual highlight makes sense to me.

**Comment by feerrenrut** [comment]
Hmm yes, things seem to have gotten confused there. NVDA highlighter, Visual highlight, or just highlighter are all fine by me. Perhaps @Qchristensen has an opinion on this?

**Comment by XLTechie** [comment]
"Visual highlight" seems redundant.

**Comment by CyrilleB79** [comment]
> "Visual highlight" seems redundant.

Could you explain a little bit more? Is "visual" redundant with "highlight" or is "Visual highlight redundant with something else (e.g. the "Vision" category)?
Could "highlight" not be something not visual? E.g.:
"Raising the TTS speech allows to highlight capitalized letters."
Would this sentence be correct in English? Sorry, English is not my mother language.

The question is why the feature was renamed from "NVDA highlight" to "Focus highlight". Maybe because NVDA is a bit generic and all options could be called "NVDA xxx", e.g. "NVDA screen curtain", "NVDA synthesizer", etc.

An other proposal could also be "Cursor highlight", cursor being taken in a wide acceptance, as an entity moving around the screen. The various cursor types could be selected: focus, nav object, browse mode cursor and maybe one day text input cursor (caret), mouse pointer, etc.

**Comment by XLTechie** [comment]
>       "Visual highlight" seems redundant.
> Could you explain a little bit more? Is "visual" redundant with "highlight" or is "Visual highlight redundant with something else (e.g. the "Vision"
> category)?

I was thinking both, actually.
Highlighting in this context is an exclusively visual feature, and it seemed 
redundant to me to mention that it is visual highlighting, because there's no 
other kind of highlighting it might be.

Perhaps I am missing a nuance, but the only other use of "highlighting" I can 
think of, is to describe a more generalized bringing of something to someone's 
attention.  E.G. "This evening I would like to highlight the work of Reef Turner 
on the NVDA project.".  I don't imagine anyone would think that kind of 
highlighting is the context here.

But this is a lot of words to describe a small opinion. :)

> Could "highlight" not be something not visual? E.g.:
> "Raising the TTS speech allows to highlight capitalized letters."
> Would this sentence be correct in English? Sorry, English is not my mother language.

Probably "Raising the pitch of TTS speech allows highlighting of capitalized 
letters." would be a more exact way to say that in English if you wanted to use 
the word highlight, but I suspect most English speakers wouldn't say it that 
way.  That said, it would not be incorrect, just unusual--English is flexible.

"Raising the pitch of the speech provides an indication that a letter has been 
capitalized.", might be a more common English form of the same thing.

> The question is why the feature was renamed from "NVDA highlight" to "Focus highlight". Maybe because NVDA is a bit generic and all options could be called
> "NVDA xxx", e.g. "NVDA screen curtain", "NVDA synthesizer", etc.

Also my thinking.

> An other proposal could also be "Cursor highlight", cursor being taken in a wide acceptance, as an entity moving around the screen. The various cursor types
> could be selected: focus, nav object, browse mode cursor and maybe one day text input cursor (caret), mouse pointer, etc.

I do like that one.  It is descriptive of the feature, non-redundant, and makes 
clear both what is being high-lit, and what sense of the word highlight is being 
used.

**Comment by Qchristensen** [comment]
I think "Visual Highlight" is less redundant in the context of a screen-reader than elsewhere.  EG the main use I have seen on the PC for "highlight" is what we would otherwise call select (which could then be followed by copying, deleting or formatting the higlighted or selected text).  In this case what we are talking about is something which is purely visual and has no effect on behaviour.  Because most of what NVDA does is NOT specifically visual, I don't think it's a problem to, er, highlight, the few features which are.

I am happy with NVDA Highlight or Visual Highlight.  I would be interested to know though, does anyone recall why NVDA highlight was renamed Focus highlight in the first place?

**Comment by CyrilleB79** [comment]
Thanks @Qchristensen for commenting. Could you also comment on the 'Cursor highlight' proposal?

**Comment by CyrilleB79** [comment]
For all: just to remind that 'Marked (highlighted text)' is now an option in Document formatting settings. I do not think there is a risk of confusion, but I wanted to mention it, just for completeness.

**Comment by Qchristensen** [comment]
A lot of people might associate cursor particularly with the text cursor (caret) - with that concept in mind, it could be confusing trying to associate it (mentally) with higlighting things like where the focus is in the start menu or in a settings screen.

**Comment by CyrilleB79** [comment]
To summarize, there are 3 proposals (almost 4 with current one) for now:
1. Focus Highlight: current term used in NVDA and also the name of the add-on used before this feature was integrated in NVDA.
  * pro: users are already used to this term
  * cons: the feature is named with 'focus', but it applies not only to system focus but also to other tracked objects: nav object and browse mode cursor. In the future, could also apply to mouse pointer and text input caret?
2. NVDA Highlight: this was the old term but was replaced by 'Focus Highlight'
  * cons: using 'NVDA' in the name of an NVDA feature is redundant and does not convey any additional information.
  * cons: do not inform about what is highlighted, i.e. tracked bojects such as focus, nav object, BM cursor.
3. Visual Highlight:
  * pro: more generic, so applies correctly to any tracked object (focus, nav object, BM cursor)
  * cons: do not inform about what is highlighted, i.e. tracked bojects
  * cons: 'visual' term is redundant
4. Cursor Highlight:
  * pro: indicates the nature of highlighted tracked objects (focus, nav obj and BM cursor) as being objects moving around the screen
* cons: 'cursor' term may be understood as referring only to text input cursor or maybe also BM cursor; so we turn back to the same issue as the term 'Focus Highlight'.





Also Cc @nishimotz, author of Focus Highlight add-on.

If nothing better is found, I would personally prefer 'Visual highlight' (proposal 3). among these 4 proposals. But I regret that the idea of ​​highlighting a tracked object moving around the screen is not conveyed by this term.
So if someone has a 5th proposal fulfilling this criterion, I would be happy.



  miss the mention

**Comment by feerrenrut** [comment]
One further perspective to consider: Focus can refer not to a technical term, but to the users area of interest. EG the part of the screen that has the users attention. As developers it is easy to get caught up in technical jargon, which isn't necessarily how the words are interpreted by end users. Being technically correct is not as important as being easily understood by the majority of users.

**Comment by nishimotz** [comment]
I'm not against this proposal.
My add-on initially highlighted only focus.
I later realized that it was useful to visualize the navigator object, but I didn't rename the add-on.
