### ISSUE TITLE
Emulated system keyboard keys: setting Alt key combinations do not work

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#11730]
STR:
1. Open input gestures to emulated system keyboard keys category.
2. Add a gesture to emulate. In my case, I tried the Mute key.
3. Add two gestures for this emulation, one with an Alt key as part of the combination, and one without. In my case, I tried both NVDA+Alt+0 and NVDA+J.
3. Press the Ok button and close.
Expected: Both combinations should work.
Actual: The combination without the Alt (in my case NVDA+J) worked, while the other with the Alt key (NVDA+Alt+0) didn't.

NVDA version in use: NVDA 2020.3beta4, cannot try with older version of NVDA as this behaviour is not present.
Windows version: Windows 10 1909 (64-bit) build 18363.1082

**Comment by CyrilleB79** [comment]
The user guide indicates:
> An input gesture with modifier keys may not be able to be mapped to an emulated gesture without modifier keys. For instance, setting the emulated input 'a' and configuring an input gesture of 'ctrl+m', may result in the application receiving 'ctrl+a'.

So I think that when you map NVDA+Alt+0 to emulate Mute, NVDA actually emulates NVDA+alt+Mute or alt+Mute.

I agree that this behaviour is strange, overall if you have not read the User Guide before.

This was already discussed in https://github.com/nvaccess/nvda/pull/11402#issuecomment-664448667.
@feerrenrut clearly wanted to first merge the big amount of work done in #11402.
> > 2- Issue in key emulation:
> I won't try to fix this in this PR. But I'll attempt to write something in the user guide shortly.

This issue seems a good place to discuss this point now that the main work has been merged.

**Comment by fisher729** [comment]
Follow-up:

Tried the same steps with Control+Shift+N (New folder shortcut), to Alt+Shift+1, and it doesn't work. However, tried mapping Alt+F4 to Alt+F2 and it does work. Therefore, I suggest this issue be investigated more thoroughly.

**Comment by CyrilleB79** [comment]
> Tried the same steps with Control+Shift+N (New folder shortcut), to Alt+Shift+1, and it doesn't work.

Yes, this is expected according to the refs I cited. Because alt modifier does not belong to the emulated key (control+shift+N). Thus this will emulate control+alt+shift+N instead of control+shift+N.

> However, tried mapping Alt+F4 to Alt+F2 and it does work.

Yes because the alt modifier of the gesture (alt+F2) is also present in the emulated key (alt+F4). So no problem.

> Therefore, I suggest this issue be investigated more thoroughly.

Investigation is already done and everything can be explained.

I agree however that the current behaviour is not something that is expected by someone who has not read the user guide. Looking at the UI, the user is given the impression that he can map any gesture to any emulated key combination.

At least, the user guide should be reworded, e.g. as follow:
> An input gesture with modifier keys may not be able to be mapped to an emulated gesture without at least the same modifier keys. For instance, setting the emulated key press 'control+shift+n' and configuring an associated gesture of 'control+alt+1', would not work because the 'alt' modifier of the associated gesture is not part of the emulated key press; this would result in emulating 'control+shift+alt+n' instead.

An implementation removing this limitation would of course be better, but I do not know if it is so easy. There are some comments on this point in #11402..

**Comment by fisher729** [comment]
Hi.

Confirmed. This is certainly a weird caveat, and certainly would confuse even the most advanced of users, let alone someone on the intermediate spectrum. However, because it works as it should, I shall close the ticket.

**Comment by CyrilleB79** [comment]
You may instead let this ticket open / re-open it since you noted that it would confuse many people.

Yes this topic was discussed in #11402. And it was decided to merge the PR even if there is this strange behaviour. But IMO, it let open the possibility to change it in the future.
