### ISSUE TITLE
I would like to be able to use the down and up arrow keys 'n browse mode to be able to nav'gate paragraphs 'nstead of l'nes

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11747]
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
I want a setting, for example, when I press up and down arrow while in browse mode, NVDA can navigate by paragraphs instead of lines on demand. I do not want to hold the ctrl key down when I want to navigate paragraph by paragraph

**Comment by DrSooom** [comment]
Your suggestion sounds very odd and isn't common. Why do you need such a feature?

**Comment by Brian1Gaff** [comment]
The only reason would be that he has issues with dexterity on one hand 
maybe?
 I'm sure some kind of sticky keys combination might work, or maybe a 
special navigation mode using a single letter like we see for headings 
landmarks etc.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by fatihyuksek1** [comment]
The only reason that I request this kind of feature is I got used to this from nnarrator. It made reading more fluent fluent 

iPhone’umdan gönderildi

**Comment by leonardder** [comment]
I guess this should be easy to accomplish by decorating the several scripts in cursorManager, so they come up in the input gestures dialog.

**Comment by feerrenrut** [comment]
It would be really helpful to know "why" you want this? Typically we want this answered under the "Is your feature request related to a problem? Please describe." heading. The more "whys" ([see 5 whys on wikipedia](https://en.wikipedia.org/wiki/Five_whys)) you can answer the better chance we have of providing a good solution.

As @leonardder suggested we could probably achieve this, but without justification for the intent I'm hesitant to do so.

Is there any chance "Allow skim reading in Say All " option in the keyboard settings panel of NVDA helps to solve this for you?

**Comment by Adriani90** [comment]
I think it could be nice to have a resolution of up and down arrow movements in browse mode, similar to mouse resolutions.
This would help one handed people to use navigation efficiently as well.
I propose two settings in the browse mode settings called something like 
* "resolution of movement for up and down arrow key combo box: Line; sentence; paragraph"
* "resolution of movement for right and left arrow key combo box: character; word"

If the same resolution could apply for browse and focus mode, then we could have these two settings in the keyboard settings category instead of browse mode.

**Comment by Adriani90** [comment]
For paragraph reading, now in NVDA 2024.2 the command p and shift+p can be used to navigate between plain text paragraphs. Since these can be used with one hand, I think this is fixed now. Closing as works for me.
Regarding different behavior of arrow key, please open a new issue with a clear justification for it.
