### ISSUE TITLE
Unable to simulate function keys using braille. 

### ISSUE THREAD

**Issue by jcoffin1** [nvaccess/nvda#11750]
<!-- Please read the text in this edit field before filling it in.
Please thoroughly read NVDA's wiki article on how to fill in this template, including how to provide the required files.
Issues may be closed if the required information is not present.
https://github.com/nvaccess/nvda/wiki/Github-issue-template-explanation-and-examples
Please also note that the NVDA project has a Citizen and Contributor Code of Conduct which can be found at https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.MD. NV Access expects that all contributors and other community members read and abide by the rules set out in this document while participating or contributing to this project. This includes creating or commenting on issues and pull requests. 
Unable to simulate  function keys using a braille display.

**Comment by DrSooom** [comment]
@jcoffin1: Please try it with [NVDA 2020.3 RC1](https://ci.appveyor.com/api/buildjobs/9ov8sop7xk797u33/artifacts/output/nvda_2020.3rc1.exe) as there is a new feature to add keyboard keys in the Input Gesture Dialog. If this solves your issue, then please close this issue. Otherwise please completely fill out the bug report draft. Thanks.
