### ISSUE TITLE
Grave accent and comma are not narrated 

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#11773]
### Steps to reproduce:
1. Navigate to the simple table JSFiddle example 
https://jsfiddle.net/kolaps33/4qcgu7ds/27/
2. Navigate to the table "shortcuts" in the example
3. Navigate to the each cell in the table 
4. Observe narration

### Actual behavior:
NVDA narrates:
row 2  Open Settings
Ctrl 
row 3  Open apps flyout 
Ctrl 

### Expected behavior:
NVDA narrates:
row 2 Open Settings
Ctrl ,
row 3 Open apps flyout
Ctrl `

### Comment
We would expect that NVDA narrates "comma" and "Grave accent".
The comma and grave accent is part of the shortcut.
If we don't narrate comma and grave accent then we are not able to tell user what is the shortcut. 

I tested NVDA + Chrome and NVDA + Firefox, for both I got the same result. 

I probably understand why NVDA doesn't want to narrate the "comma" and "Grave accent", as it could cause really mess if each comma would be narrated. 
But in this case we need to narrate it explicitly. What would be solution? :) or is there some special trick? :) Thank you. 

#### NVDA installed/portable/running from source:
installed 

#### NVDA version:
2020.3

#### Windows version:
win version 10.0.19042

#### Name and version of other software in use when reproducing the issue:
chrome Version 86.0.4240.75 (Official Build) (64-bit)
firefox 81.0.2 (64-bit)

**Comment by CyrilleB79** [comment]
To have more or all punctuation reported, you may increase the punctuation / symbol level (shortcut NVDA+P).
HTH

**Comment by kolaps33** [comment]
@CyrilleB79 
Thank you that is great tip and tested and it works :) when I changed to symbol level most. 

Just I think how user will be aware they should increase punctuation/symbol level?, because they are not aware what the shortcut dialog contains "special" symbols. Or should we mention it into the user in some way ? 
Thank yo very much. :)

**Comment by CyrilleB79** [comment]
On websites/documentations, a common way to write the shortcut is 'ctrl+,', with the '+' indicating that both keys have to be pressed simultaneously. Since the '+' symbol is reported also at the default 'some' level, the user can hear 'control plus'. This seems enough to warn the user that a part is missing. Thus, the user may:
* make NVDA spell out the line (here, the cell content) by pressing NVDA+UpArrow
  OR
* go across this piece of text with arrow keys to have it read character by character
  OR
* modify punctuation level as explained before

Some other websites (maybe for visually impaired especially) add the name of the character between brackets, e.g.:
`ctrl+, (comma)`

**Comment by kolaps33** [comment]
@CyrilleB79
thank you for your detailed explanation. It helps me to fix it in some way :) 
Closing the bug.

**Comment by Brian1Gaff** [comment]
Could it be set up as a profile for just that dialogue?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
