### ISSUE TITLE
Emphasised text is not reported according to its setting in IE

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11808]
### Steps to reproduce:

In Internet Explorer, open this file: [ExEmphasisAndMarkedText.html.txt](https://github.com/nvaccess/nvda/files/5490739/ExEmphasisAndMarkedText.html.txt) after having removed its txt extension.

1. In Document formatting settings, disable Emphasis and Marked
  Then read the page.
2. In Document formatting settings, disable Emphasis and enable Marked
  Then read the page.
3. In Document formatting settings, enable Emphasis and disable Marked
  Then read the page.

### Actual behavior:

1. No formatting info read in the 3 first lines.
2. The words "Reef" and "Quentin" are read respectively as emphasized and marked.
3. No formatting info read in the 3 first lines.

### Expected behavior:

1. No formatting info read in the 3 first lines (same result).
2. Only "Quentin" is read as marked in the 3 first lines.
3. Only "Reef" is read as emphasized in the 3 first lines.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.3
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Internet Explorer 11
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.2 has no issue regarding emphasis. This is a regression probably introduced by #11436. Note that reporting of marked content has been introduced only in 2020.3.

#### If addons are disabled, is your problem still occuring?
No tested.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by btman16** [comment]
Hi,

In NVDA 2020.4beta3, the text under the "Bug Fixes" section of the What's New file says that the reporting of strong and emphasis tags in Internet Explorer can be suppressed from being reported by returning off emphasis in the Document Formatting settings.

instead of this, I feel that it should say that reporting of strong and emphasis tags in Internet Explorer can be suppressed from being reported by turning off emphasis reporting from the document formatting dialog.

To me, saying "turning off" instead of "returning off" sounds better.

Thank you very much for your time and I look forward to any input you may have.

Sincerely,

Brandon Tyson
