### ISSUE TITLE
Outlook: NVDA continues to jump to the last graphic within an email message when the letter G is pressed

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11907]
### Steps to reproduce:

Tested with Outlook 2016; I'm unsure if this can also be observed with other builds.

1. Open an email that contains at least one graphical image; it's important that NVDA jumps to this element when hitting "G"

2. Navigate to the top of the message, and hit the letter "G" to jump to the first graphic

3. Assuming that this is the only graphic in the message, hit "G" once again

### Actual behavior:

NVDA once again outputs the same graphic

### Expected behavior:

As can be observed within web browsers, in this case NVDA should output "no next graphic"

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.3

#### Windows version:

7/10

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by CyrilleB79** [comment]
Hello

This issue is not confirmed  as described here on Outlook 2016.
I have one message with only one graphic and if I press G again, NVDA tells me there is no more graphic.
In another message with one visible graphic however, I find that G jumps to the visible graphic and then to 4 or 5 invisible graphics.
@elliott94, could you check that NVDA does not jumps to invisible graphic instead when you press G again? You can check if the graphic is visible or not by pressing NVDA+F1 to get the dev info of the navigator object. In my case, the invisible graphic had a location of (0, 0, 0, 0).
Does the issue occur only on some messages ? Or in any message containing graphics?
Also, are you able to create such problematic message, e.g. by inserting a graphic in a message that you send to yourself?



I have found however another message with one visible graphic but also

**Comment by Adriani90** [comment]
We didn't get the infor requested from the initial author since many years. I am closing this as abandoned. if you are still having this issue with NVDA 2024.2 Beta, please comment and we can reopen.
