### ISSUE TITLE
Warning when using OCR when screen curtain is enabled

### ISSUE THREAD

**Issue by artindk** [nvaccess/nvda#11911]
### Is your feature request related to a problem? Please describe.
For a long time I thought that the OCR function (Windows 10 OCR) just didn't work properly, because I got no results every time. Today I found out that I had turned on the screen curtain feature of NVDA, so the OCR only saw a black screen. After I turned off the screen curtain, the OCR worked fine.
### Describe the solution you'd like
If that's technically possible, I'd like it when NVDA warns you when you try to use the OCR feature while Screen Curtain is on.
### Describe alternatives you've considered
I don't know any alternatives, this seems to me the easiest solution.
### Additional context
I am using Windows 10 1909 (64-bit) build 18363.1198 and NVDA 2020.3.

**Comment by leonardder** [comment]
I'd say it would makes sense if OCR simply refuses to work when the screen curtain is on.

**Comment by CyrilleB79** [comment]
> I'd say it would makes sense if OCR simply refuses to work when the screen curtain is on.

Agree with this. I am preparing a PR that includes:
* do not perform OCR when screen curtain is on; inform the user instead to disable it to perform OCR
* add a note to the user guide indicating that:
  * OCR cannot be performed with screen curtain enabled
  * OCR may give unpredictable results with visual aids (Windows Magnifier, Visual Highlight (=Focus Highlight), maybe Zoomtext)

I still need to perform tests on the last point and will be able to propose this PR tonight (UTC+1) or tomorrow.

**Comment by ABuffEr** [comment]
> • do not perform OCR when screen curtain is on; inform the user instead to disable it to perform OCR

I'd like a lot if there is the choice between inform only and perform OCR disabling and re-enabling OCR when done.

**Comment by CyrilleB79** [comment]
@ABuffEr wrote:
> > • do not perform OCR when screen curtain is on; inform the user instead to disable it to perform OCR
> 
> I'd like a lot if there is the choice between inform only and perform OCR disabling and re-enabling OCR when done.

I thought there were already an issue for this, but I may have confused with #10576.

Anyway my goal would rather be to have a quick fix on this topic already present for one year, so that people do not just imagine that NVDA's OCR is not working. Ideally, if NVAccess agree, this could be integrated quickly in 2020.4.

On the contrary your proposal probably requires more discussion. Just look at all screen curtain issue in GitHub, mostly related to enabling/disabling it and to privacy, and you will realize that it is difficult to find a consensus and to progress on these topics.
Thus I would recommend to open a separate issue for the solution you describe. This could be included later in NVDA.

**Comment by britechguy** [comment]
> I'd like a lot if there is the choice between inform only and perform OCR disabling and re-enabling OCR when done.

Do you mean that you'd like NVDA to automatically disable Screen Curtain, perform the OCR, and then re-enable Screen Curtain when done?   While I love that idea in theory, there are security considerations to this if the end user is using Screen Curtain to prevent "shoulder surfing" when in public places.  I suspect there would be a tendency to forget that the automatic sequence involves displaying the screen, running OCR while it's visible to the world, and putting screen curtain back in to effect.  But if there is a setting that makes this an option, it makes perfect sense.

But at the very least if NVDA can interrogate whether screen curtain is active prior to initiating an OCR, and telling the user that they have to disable Screen Curtain before OCR can be done, that needs to happen.  This is the kind of "little detail" that a very great many of us would forget, and think OCR isn't working when that's not really true.

**Comment by CyrilleB79** [comment]
> But at the very least if NVDA can interrogate whether screen curtain is active prior to initiating an OCR, and telling the user that they have to disable Screen Curtain before OCR can be done, that needs to happen. This is the kind of "little detail" that a very great many of us would forget, and think OCR isn't working when that's not really true.

That is exactly what #11921 is implementing. I hope it to be merged soon. The reste of the discussion (disabling screen curtain to perform OCR, validating privacy issues) could probably be achieved later.

**Comment by bhavyashah** [comment]
A few comments in regards to the privacy considerations in disabling screen curtain for the duration of OCR:
* Even on a slower than average machine, how many seconds does it take to disable screen curtain, perform Windows 10 OCR, and then re-enable screen curtain? Windows 10 OCR seems blazing fast at my end. If the answer to this question is <1 second, then that seems like a defeasible concern. I invite comment from sighted people as to how much of a screen a prying eye could actually catch in this time period.
* I think the issue of a user forgetting about the impact of running OCR on the state of screen curtain can be significantly alleviated. This is because everytime OCR is performed, the user will be reminded of this nuance by the screen curtain disabled, recognizing OCR, and screen curtain enabled announcements along with the screen curtain swoosh sound effects. I would imagine that the repeated occurrence of this would reinforce this oddity well. Having said that, I acknowledge that so much speech and sound feedback in such a short while could be jarring for a user.

**Comment by ABuffEr** [comment]
>     * Even on a slower than average machine, how many seconds does it take to disable screen curtain, perform Windows 10 OCR, and then re-enable screen curtain? Windows 10 OCR seems blazing fast at my end. If the answer to this question is <1 second, then that seems like a defeasible concern. I invite comment from sighted people as to how much of a screen a prying eye could actually catch in this time period.

in addition, I'm not sure, but I think that the "locked" part is the (very fast) screen/image acquisition, not the (slower) recognition process.
Anyway, considering also #11270 pr, inform user to disable curtain during OCR (regardless his screen curtain warning settings) is surely the priority.
