### ISSUE TITLE
PDF files longer than 49 pages loose their ability to navigate with NVDA commands in Acrobat Reader/Pro. The Element List only shows Headings on Current Page.

### ISSUE THREAD

**Issue by Ribinski** [nvaccess/nvda#11960]
### Steps to reproduce:
**Produce a pdf file with 49 pages or less** in Word/InDesign export to accessible pdf. 
It navigates ok in NVDA.
**The Element List shows ALL Headings in the document, as expected.**

**Produce a pdf file with 50 or more pages**. 
It does not navigate correctly in NVDA.
**The Element List only shows Headings on _Current Page_.**

I have used an outsider (person) who also has NVDA installed, she certified this same behaviour.

Please test the attached PDF files generated from Word files, also attached.
[Word_NVDA_test_document_exactly_49_pages.docx](https://github.com/nvaccess/nvda/files/5724422/Word_NVDA_test_document_exactly_49_pages.docx)
[Word_NVDA_test_document_exactly_49_pages.pdf](https://github.com/nvaccess/nvda/files/5724425/Word_NVDA_test_document_exactly_49_pages.pdf)
[Word_NVDA_test_document_exactly_50_pages.docx](https://github.com/nvaccess/nvda/files/5724426/Word_NVDA_test_document_exactly_50_pages.docx)
[Word_NVDA_test_document_exactly_50_pages.pdf](https://github.com/nvaccess/nvda/files/5724427/Word_NVDA_test_document_exactly_50_pages.pdf)

### Actual behavior:
If one tries to use NVDA to navigate in Adobe Acrobat DC Pro/Reader with commands like next heading, next table, next graphic, list etc. and so on, NVDA responds with: "No Next Heading/item".
Same goes with the previous command variants.

### Expected behavior:
Should jump to next item.

#### NVDA version:
NVDA 2020.3

#### Windows version:
Windows 10, all updates per 12/21/2020, 

#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat DC Pro

#### Other information about your system:
Tested on intel-based and AMD-based systems
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Have not tested, do not know if I have any add-ons installed, not a professional user of NVDA.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by CyrilleB79** [comment]
Did you test with another screen reader (Jaws, Narrator)?

I did not test neither with NVDA, nor with another screen reader. However, I recall that in Acrobat reader, you may specify a maximum number of pages to read so that the reader does not get stuck during many minutes when you open a very large document. This can be specified in the wizard when you open a document (if you did not disable it) or in the options.
In my Acrobat Reader's options (Edit -> Preferences), in the "Reading" section, I have the following item: "Minimum number of pages in a large document:". I did not test but it is probably this value that controls the number of read pages.

Notes: My computer is in French, so maybe the name of the menus and options are not exactly what I wrote.

**Comment by Ribinski** [comment]
Wow, this was quick.

I am happy to inform that your advice was correct!
It worked!
An I have go through these settings for accessibility settings in Acrobat .... I am new to the topic and NVDA.

I thank you from the **_bottom of my heart_** and wish you a Merry Christmas!
