### ISSUE TITLE
NVDA reader read page content in between read modal on displaying modal popup

### ISSUE THREAD

**Issue by Thomas5588** [nvaccess/nvda#12082]
Hi @feerrenrut 

### Steps to reproduce:
I have welcome Modal popup and its getting displayed when redirect to the Home page.

`<div class="modal fade" id="modelpage" tabindex="-1" role="dialog" aria-labelledby="modelLabel" aria-hidden="true">`
    `<div class="modal-dialog" role="document">`
        `<div class="modal-content">`
            `<div class="modal-header">`
                `<div class="modal-title" id="modelLabel"></div>`
                `<button type="button" class="close" data-dismiss="modal" >`
                    `<span class="fas fa-close" ></span>`
               ` </button>`
           ` </div>`
            `<div class="modal-body">`
           ` </div>`
            `<div class="modal-footer">`
                `<button  type="button" class="btn">Done</button>`
            `</div>`
       ` </div>`
   ` </div>`
`</div>`

### Actual behavior:
the NVDA reader read Home page content in between reading the model content, when modal popup is displayed 

### Expected behavior:
NVDA reader should read only modal content when modal is displayed. Home page content should not be read out when modal popup is displayed.

**Comment by Adriani90** [comment]
@Thomas5588 Please provide a minimal test case in codepen or an updated html code. This one does not really work. the modal has aria hidden="true" and is not focusable with the keyboard due to the tabindex="-1". I guess NVDA reports first things that get the focus and then the modal dialog after it is focused.
Could you also try to enable cancellable speech when focus event expires in NVDA advanced settings? Please report if you still have this issue with NVDA 2023.2.

**Comment by Adriani90** [comment]
setting tabindex to "0" and removing the aria hidden atribute seems to work properly here.
We need a real minimal test case to work with in codepen or so, and we need exactly the actual and the expected reporting of NVDA.
Since we didn't get any updates from the initial author since years, I am closing as abandoned. Please provide the requested info in case you are still having this issue and we can reopen.
