### ISSUE TITLE
nvda does not enter focus mode when you press enter in the google search field 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12118]
### Steps to reproduce:
on nvda uncheck the option
autofocus mode when focus changes
open chrome
enter the site
www.google.com
nvda announces that it is in the field
search combo box
press enter to have nvda enter focus mode 
### Actual behavior:
nothing happens 
### Expected behavior:
when pressing enter in the search box combo box the nvda must enter focus mode 

comments:

this only occurs when opening the browser.
If with a open browser you open a new tab with google the problem does not happen. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-21810,db664bef

#### Windows version:
10.0.19043.844
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 88.0.4324.190

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no
log:
[chrome.txt](https://github.com/nvaccess/nvda/files/6085537/chrome.txt)

**Comment by fernando-jose-silva** [comment]
I believe I made some discoveries:
nvda does not enter focus mode, as the focus is not on the search combo box.
The focus is on a place that nvda reads as
clickable, if I press an arrow below then I am over the search combo box.
I was deceived because when pressing nvda + tabe the nvda informs search combo box, even if the focus is not on the search combo box.
I discovered another problem that I believe is nvda's fault, even if the focus is on any other field on the page, nvda continues to inform the search combo box by pressing nvda + tabe.
You can do the test:

on the google search page of that one with the arrows until:
Input tools
now press nvda + tab and nvda will say:
search combo box, I would expect it to speak up
Input tools

**Comment by Adriani90** [comment]
@fernando-jose-silva your focus discoveries are intentional, this is because the system focus is not moved automatically to focusable objects by default when using browse mode. You can change that behavior by pressing nvda+8 but then this could cause uncontrolled cursors movements while you navigate the website with arrow keys.

If enter does not work, i suggest to use nvda+space bar, then the focus is dragged automatically to the field.
But please also try the COM registration fixing tool in NVDA menu 7 tools and report back the results after that. I cannot reproduce your issue on my macines.

**Comment by fernando-jose-silva** [comment]
Thank you very much for the explanations.
Even after running the registry correction tool the problem continues.
Pressing nvda + space made the search combo box receive the typed text.
Setting the focus to clickable elements aloud did not make a difference.

**Comment by ehollig** [comment]
I believe this is intentional. Focus is automatically placed on the search region when the page loads. Pressing enter does not activate the search field, but NVDA+Tab announces the present of the search field. Please let me know if this issue still exists for someone else or I have misunderstood the issue.
