### ISSUE TITLE
NVDA doesn't disable assistive technologies after uninstall (java apps can't run and show java.awt.AWTError)

### ISSUE THREAD

**Issue by JayDi85** [nvaccess/nvda#12159]
You can find workaround at the end

### Steps to reproduce:
* Install NVDA in Windows
* Ensure that it works with java's GUI applications
* Uninstall NVDA
* Now you can't run java applications due one of the errors:
  * `java.lang.UnsatisfiedLinkError: D:\SOFT\Programming\ETC\JAVA\openjdk-11.0.2\bin\javaaccessbridge.dll: Can't find dependent libraries`
  * `java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge`

### Actual behavior:
* Java apps with GUI are broken.
* Full java error example:
```
java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
        at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
        ...
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at de.sciss.syntaxpane.DefaultSyntaxKit.<clinit>(DefaultSyntaxKit.java:105)
        at com.xk72.charles.gui.lib.UIUtils.<clinit>(Unknown Source)
        at com.xk72.charles.gui.Main.GSXJ(Unknown Source)
        at com.xk72.charles.Main.FwRs(Unknown Source)
        at com.xk72.charles.gui.Main.main(Unknown Source)
        ...
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
```

### Expected behavior:
* Java apps with GUI must work;
* NVDA must disable assistive technologies before uninstall, reset it to "before install settings" or add information in the uninstall wizard about potential problem (checkbox like "disable assistive technologies after uninstall");

#### NVDA version:
2020.4

#### Windows version:
Windows 7

### Workaround
* Find access bridge settings: `C:\Users\current_user\.accessibility.properties`
* Delete it or comment each line with starting text: `#`
* It will disable assistive technologies and fix a broken java apps.

**Comment by christopherpross** [comment]
Hey, after my first PR regarding thisss bug, which had not a good approach, I want to start here a  discussion about the fix of this issue. Any thoughts?

**Comment by JayDi85** [comment]
Best UX solution is improve of uninstall wizard: 
* add special step with "disable access bridge" check box and warning message

I don't know details about NVDA source code, but can find [NSIS](https://nsis.sourceforge.io/) source files (installer developer software). It supports custom [pages](https://nsis.sourceforge.io/Show_custom_page_when_a_section_has_been_selected), so I think it can be implemented by installer.

**Comment by XLTechie** [comment]
I agree with the uninstaller idea.

Perhaps with a default of disable, if it is detected that NVDA did the 
enablement (by the registry flag that @leonarder mentioned).

**Comment by christopherpross** [comment]
Hey,
Yeah this should be easiely to implement, my question is whether this registry flag already exist? Because I don't find that in the code, or should I implement that too?

**Comment by christopherpross** [comment]
Hey guys,
@XLTechie and @leonardder, I marked you because we had already talked in the PR, so maybe you will have an idea?

i am not sure, whether I could do that. Because we need for this to work, an uninstaller gui, which would have the following limitations (correct please if I am wrong):
- The UI is not translable with gettext
- It exist a work arround for that, but requires to build for each language own NSI files
- This would result in a new build-pipeline for the uninstaller, where gettext files are merget with the NSIS-scripts

The only way arround this, is to write a GUI dialog in python and call from there the uninstaller, with commandline arguments. The interesting thing is, the uninstaller.nsi calls also nvda_slave.exe to perform the uninstaller task. This way would result then in:
python gui -> NSIS -> nvda_slave.py -> installer.py
Maybe you see, that this way leads to the idea that we should write the uninstaller complete in python, because the part of NSIS is not nessecary.
Of curse I could be totaly wrong, so I ask here to do this.

**Comment by Adriani90** [comment]
This is not reproducible in Windows 10 or higher, and I guess Windows 8.1. is very very rarely used nowadays. Since support for Windows 7 and 8.0 in NVDA officially ended, I am closing as abandoned. If you are still facing this issue, please comment and we can reopen.
