### ISSUE TITLE
NVDA does not play the buzzer sound  in word when a speeling error is made

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#12161]
### Steps to reproduce:
1. Open word
2. Enable "use UIA automation when accessing word documents" under NVDA settings/advanced
3. misspell a word and press space
4. NVDAS doesn't play the buzzer sound to indicate that you've made a mistake
### Actual behavior:
NVDA doesn't play the buzzer sound to indicate a spelling error
### Expected behavior:
NVDA will play the buzzer sound when a spelling error is made when it is enabled under document formatting settings
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
windows 10 2004
#### Name and version of other software in use when reproducing the issue:
Words 365 latest version
#### Other information about your system:
I have the report spelling errors setting checked under the document settings diolog. Previously NVDA would play the sound but now it doesn't. I have the uia automation turned on under the advanced settings category as well
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by burakyuksek** [comment]
Turning off UIA fixes the issue but then we lose the performance improvements it causes.

**Comment by CyrilleB79** [comment]
I hope it can bee fixed in NVDA 2021.3.

If not, (or if there is another regression using UIA), there are two path:
* Revert the commit forcing UIA use for recent versions of Word
* Modify the option "Always use UI Automation to access Microsoft &Word document controls when available" to "use UI Automation to access Microsoft Word document controls" and a combobox with the following choices (as per Edge/Chromium):
  * Yes
  * No
  * Only if necessary
  * Default (only if necessary)
