### ISSUE TITLE
NVDA takes an incredibly long time to load this page in Firefox

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#12185]
### Steps to reproduce:

Visit https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core

### Actual behavior:

It takes multiple minutes for the page to load (I don't know how long exactly, I went for coffee while waiting and it was done when I came back)

### Expected behavior:

The page loads in a reasonable amount of time

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21802,5678c8be

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Firefox 86.0.1

#### Other information about your system:
Running on a T14s AMD Gen 1 (Ryzen pro 7 4750U)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by MarcoZehe** [comment]
Not surprised. 4,111 links, 179 headings on level 0 in the list, with many of them having over 20 sub headings, and that's just looking at level 1.

I'm out sick, and pinging @jcsteh to take a look.

**Comment by jcsteh** [comment]
I agree this is really bad. On my relatively high powered developer laptop, the virtual buffer takes about 75 seconds to render. The document is absolutely massive, though, with a lot of elements.

While Chrome is sometimes better with massive documents like this, in this case, it seems to be just as bad if not worse.

I honestly don't know that we can make this case better while virtual buffers are still a thing. Worse, Chrome seems to spend a long time pushing the document across process boundaries (before NVDA can even start rendering it), so even getting rid of buffers might not help this, especially since Firefox is moving more towards an approach similar to Chrome's in this respect.

**Comment by Neurrone** [comment]
I agree that pending the removal of buffers, this is going to be at least linear time in the best case.

I was just curious if there are certain attributes of that page which causes particularly long loading times, e.g the presence of many links, headings or tables.

Another idea could be to allow NVDA and Firefox to be more responsive while a tab is taking a long time to load. It would help immensely if I could switch to another tab and continue to work while the tab with a big page continues to load, or if trying to access its contents while the page loads says loading or something to that effect.

I'm not sure how difficult this would be to implement though.

**Comment by jcsteh** [comment]
> I was just curious if there are certain attributes of that page which causes particularly long loading times, e.g the presence of many links, headings or tables.

Many objects in general, regardless of what they are, will increase load times. That is, a single object with lots of text will be relatively fast, but the same amount of text spread across many objects will be much slower. Tables are particularly problematic because cells are usually very small, but there tend to be a lot of them. Long lists can be similarly problematic.

> Another idea could be to allow NVDA and Firefox to be more responsive while a tab is taking a long time to load. It would help immensely if I could switch to another tab and continue to work while the tab with a big page continues to load

Yeah, I've given this some thought in the past. It's very tricky to implement, though:

1. All buffer rendering has to be done in the browser's main thread, so background threads aren't an option.
2. That means that in order to be responsive, the buffer render has to be interruptible. Right now, the entire framework is centred around recursively traversing the tree. Rendering in chunks would thus require some way to abort the render, keeping track of the previous point and somehow resuming from there, not an easy thing to do with a recursive algorithm. Or you'd have to make it iterative instead of recursive, but that'd be a massive re-architecture. Or maybe we could use C++ coroutines, but that opens up many questions. :)
3. We can't know when the client will interact with the UI, so we can't interrupt in response to specific signals; we'll just have to suspend on some time interval for some amount of time. That could end up making renders significantly slower. We could tweak the timers based on whether the tab is a background tab, etc., but the concern still stands.
4. While we're suspended, the document might mutate. We then have to figure out what to do with those events. Do we finish the interrupted render and then process the events? Or some other strategy?

**Comment by bdorer** [comment]
well, even loading German userguide without addons takes 16.217 sec
using latest firefox and NVDA alpha. Just as a reference.

Am 22.03.2021 um 03:20 schrieb James Teh:

**Comment by zersiax** [comment]
This can be an issue when there is literally no other way to get at information though.
Another example I can think of off the top of my head is the Microsoft Skype History Viewer which essentially lets you read your data retrieved from Skype. This is a massive JSON blob which, after it has been loaded into this index.html file, lets you pick a conversation. Clicking one then renders the full conversation.
At that point there's two options:

- Wait and pray. I have tried several loads for this; a 9000 message conversation eventually renders, but NVDA locks up entirely while it's doing so, which makes sense given the above comments. For fun, I also threw a 66000 message conversation at it, which didn't render after 15 minutes of waiting.
- - Do whatever is required to load the page then quickly alt+tab out and let the browser do it's thing. This will prevent NVDA from locking up while the browser does it's thing, but when you subsequently try to alt+tab back into the application, the window refuses to gain focus.
Either way, the information isn't readable. The example page in this issue is massive but eventually loads. If pages get bigger than that , waiting for them to load might not be feasible and I think this happens more often than might be realized. Question is, what workarounds even exist in the case of a page just not loading because the amount of objects is too massive? We can't chunk it, pretty sure Narrator at least does some kind of virtual buffering to make their scan mode work, so at that point people are out of options. And if such a page is what people need for their job ...that is an issue.

**Comment by Neurrone** [comment]
@zersiax thanks for articulating the issues this could cause. I meant to follow up on this but I forgot to.

I recognize its not going to be easy to fix this though, perhaps short of getting rid of the concept of needing virtual buffers entirely.

/CC @feerrenrut or @michaelDCurran for any thoughts on whether addressing this could be on the roadmap?

**Comment by jcsteh** [comment]
We're currently undertaking a major re-architecture of Firefox's multi-process accessibility support using a cache. With this enabled, the page referenced in the first comment here takes about 5 seconds to load. This is still very much under development and won't be ready for production use for several months yet, but I thought it worth providing an update here regardless.

**Comment by jcsteh** [comment]
We're currently undertaking a major re-architecture of Firefox's multi-process accessibility support using a cache. With this enabled, the page referenced in the first comment here takes about 5 seconds to load. This is still very much under development and won't be ready for production use for several months yet, but I thought it worth providing an update here regardless.

**Comment by jcsteh** [comment]
I'm pleased to announce that Cache the World, our major re-architecture of the Firefox accessibility engine to significantly improve performance, is now ready for preview on Windows in Firefox Nightly. If you're interested in testing, see this blog post for details and testing instructions: https://blog.mozilla.org/accessibility/cache-the-world-opt-in-preview/

**Comment by jcsteh** [comment]
Cache the World is enabled by default in Firefox 113 release.
