### ISSUE TITLE
Odd behavior with a particular checkboxe, not browser specific

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#12204]
### Steps to reproduce:

1. Open this page in a (private) browser window: [My Social Security Terms of Service Agreement Form](https://secure.ssa.gov/RIR/CatsView.action)
2. Attempt to select the "I agree" checkbox with the space key.
3. Re-read the line with up/down arrow or other means.
4. Try to select the box again.
5. Perhaps try using mouse routing.

### Actual behavior:

The I agree checkbox reacts when selected, but speaks as if it's always unchecked when reviewed.
Furthermore, the first time I tried this, NVDA would not speak at all when pressing space for this--It never stated checked or unchecked.
After restarting NVDA a few times, and killing and restarting Firefox, it now only fails to speak check/unchecked the first time space is pressed. Subsequently it does speak the state, but still says "unchecked" in review.

I mainly tested this in Firefox, but also tried it in Brave for completeness, and the results were the same.

### Expected behavior:

NVDA should indicate "checked", when this box is first checked with space.
NVDA should correctly indicate the state of the checkbox as "checked" if it has been checked.

### System configuration

NVDA Installed: alpha-22012,3c1693dd

#### Windows version:

20H2 (OS Build 19042.867)

#### Name and version of other software in use when reproducing the issue:

Firefox: 86.0.1 (64-bit)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I tried a portable of 2019.3.1, with identical results.
Actually, until I ran that, the alpha reported nothing when I pressed space to check/clear the box, no matter how many times I tried it. After i ran 2019.3.1, and it was able to speak on the second and subsequent presses, re-running the alpha now had that result as well. Very strange.

#### If add-ons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes.

### A log of my latest attempt

IO - inputCore.InputManager.executeGesture (19:51:31.331) - winInputHook (15172):
Input: kb(desktop):x
IO - speech.speak (19:51:31.347) - MainThread (15304):
Speaking ['main landmark', 'form', ' ', 'I agree to the Terms of Service.', 'check box', 'not checked']
IO - inputCore.InputManager.executeGesture (19:51:33.935) - winInputHook (15172):
Input: kb(desktop):space
IO - inputCore.InputManager.executeGesture (19:51:37.194) - winInputHook (15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:37.211) - MainThread (15304):
Speaking ['and benefit.']
IO - inputCore.InputManager.executeGesture (19:51:37.552) - winInputHook (15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:37.572) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:38.233) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:39.462) - winInputHook (15172):
Input: kb(desktop):space
IO - speech.speak (19:51:39.531) - MainThread (15304):
Speaking ['not checked']
IO - inputCore.InputManager.executeGesture (19:51:41.458) - winInputHook (15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:41.475) - MainThread (15304):
Speaking [BeepCommand(220, 80, left=50, right=50), 'no indent', 'and benefit.']
IO - tones.beep (19:51:41.479) - MainThread (15304):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:41.675) - winInputHook (15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:41.684) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:42.376) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:43.927) - winInputHook (15172):
Input: kb(desktop):space
IO - speech.speak (19:51:43.987) - MainThread (15304):
Speaking ['checked']
IO - inputCore.InputManager.executeGesture (19:51:46.685) - winInputHook (15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:46.702) - MainThread (15304):
Speaking [BeepCommand(220, 80, left=50, right=50), 'no indent', 'and benefit.']
IO - tones.beep (19:51:46.707) - MainThread (15304):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:46.972) - winInputHook (15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:46.992) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:47.673) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50

### Developer info for navigator object

name: '\uf14a I agree to the Terms of Service.'
role: ROLE_CHECKBOX
roleText: None
states: STATE_CHECKABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x06974670>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=476, top=998, width=288, height=42)
value: None
appModule: <'appModuleHandler' (appName 'firefox', process ID 4340) at address 373afd0>
appModule.productName: 'Firefox'
appModule.productVersion: '86.0.1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 722576
windowClassName: 'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
extendedWindowStyle: 256
windowThreadID: 6680
windowText: 'Social Security — Mozilla Firefox'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x52b532c at 6be4610>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=722576, objectID=-4, childID=-184549857
IAccessible accName: '\uf14a I agree to the Terms of Service.'
IAccessible accRole: ROLE_SYSTEM_CHECKBUTTON
IAccessible accState: STATE_SYSTEM_MARQUEED, STATE_SYSTEM_VALID (8192)
IAccessible accDescription: ''
IAccessible accValue: None
IAccessible2 windowHandle: 722576
IAccessible2 uniqueID: -184549857
IAccessible2 role: ROLE_SYSTEM_CHECKBUTTON
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT (5120)
IAccessible2 attributes: 'margin-left:0px;checkable:true;text-align:start;text-indent:0px;id:agreementLabel;tag:label;xml-roles:checkbox;margin-top:0px;margin-bottom:0px;margin-right:0px;display:block;formatting:block;'

**Comment by XLTechie** [comment]
CC: @jcsteh

**Comment by XLTechie** [comment]
> After restarting NVDA a few times, and killing and restarting Firefox, it now only fails to speak check/unchecked the first time space is pressed.
> Subsequently it does speak the state, but still says "unchecked" in review.

I should note that upon page reload, the next press of the checkbox will not 
speak.

**Comment by Brian1Gaff** [comment]
This is a similar issue I get with the British wireless for the blind upload 
site in which you can select a box and hit delete to delete all old files. 
It will say checked, but then it will say unchecked if you cursor over it 
again, but if you move several lines up and then back it is in fact checked.
 I think it needs someone to check these things with edge and other browsers 
not based on mozilla, as to me this feels like a problem in their code.
Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Luke Davis" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, March 20, 2021 12:15 AM
Subject: [nvaccess/nvda] Odd behavior with a particular checkboxe, not 
browser specific (#12204)



### Steps to reproduce:

1. Open this page in a (private) browser window: [My Social Security Terms 
of Service Agreement Form](https://secure.ssa.gov/RIR/CatsView.action)
2. Attempt to select the "I agree" checkbox with the space key.
3. Re-read the line with up/down arrow or other means.
4. Try to select the box again.
5. Perhaps try using mouse routing.

### Actual behavior:

The I agree checkbox reacts when selected, but speaks as if it's always 
unchecked when reviewed.
Furthermore, the first time I tried this, NVDA would not speak at all when 
pressing space for this--It never stated checked or unchecked.
After restarting NVDA a few times, and killing and restarting Firefox, it 
now only fails to speak check/unchecked the first time space is pressed. 
Subsequently it does speak the state, but still says "unchecked" in review.

I mainly tested this in Firefox, but also tried it in Brave for 
completeness, and the results were the same.

### Expected behavior:

NVDA should indicate "checked", when this box is first checked with space.
NVDA should correctly indicate the state of the checkbox as "checked" if it 
has been checked.

### System configuration

NVDA Installed: alpha-22012,3c1693dd

#### Windows version:

20H2 (OS Build 19042.867)

#### Name and version of other software in use when reproducing the issue:

Firefox: 86.0.1 (64-bit)

### Other questions
#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their 
behaviors.

I tried a portable of 2019.3.1, with identical results.
Actually, until I ran that, the alpha reported nothing when I pressed space 
to check/clear the box, no matter how many times I tried it. After i ran 
2019.3.1, and it was able to speak on the second and subsequent presses, 
re-running the alpha now had that result as well. Very strange.

#### If add-ons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes.

### A log of my latest attempt

IO - inputCore.InputManager.executeGesture (19:51:31.331) - winInputHook 
(15172):
Input: kb(desktop):x
IO - speech.speak (19:51:31.347) - MainThread (15304):
Speaking ['main landmark', 'form', ' ', 'I agree to the Terms of Service.', 
'check box', 'not checked']
IO - inputCore.InputManager.executeGesture (19:51:33.935) - winInputHook 
(15172):
Input: kb(desktop):space
IO - inputCore.InputManager.executeGesture (19:51:37.194) - winInputHook 
(15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:37.211) - MainThread (15304):
Speaking ['and benefit.']
IO - inputCore.InputManager.executeGesture (19:51:37.552) - winInputHook 
(15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:37.572) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, 
left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:38.233) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:39.462) - winInputHook 
(15172):
Input: kb(desktop):space
IO - speech.speak (19:51:39.531) - MainThread (15304):
Speaking ['not checked']
IO - inputCore.InputManager.executeGesture (19:51:41.458) - winInputHook 
(15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:41.475) - MainThread (15304):
Speaking [BeepCommand(220, 80, left=50, right=50), 'no indent', 'and 
benefit.']
IO - tones.beep (19:51:41.479) - MainThread (15304):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:41.675) - winInputHook 
(15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:41.684) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, 
left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:42.376) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:43.927) - winInputHook 
(15172):
Input: kb(desktop):space
IO - speech.speak (19:51:43.987) - MainThread (15304):
Speaking ['checked']
IO - inputCore.InputManager.executeGesture (19:51:46.685) - winInputHook 
(15172):
Input: kb(desktop):upArrow
IO - speech.speak (19:51:46.702) - MainThread (15304):
Speaking [BeepCommand(220, 80, left=50, right=50), 'no indent', 'and 
benefit.']
IO - tones.beep (19:51:46.707) - MainThread (15304):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:51:46.972) - winInputHook 
(15172):
Input: kb(desktop):downArrow
IO - speech.speak (19:51:46.992) - MainThread (15304):
Speaking ['check box', 'not checked', BeepCommand(226.44649206156825, 80, 
left=50, right=50), 'space', 'I agree to the Terms of Service.']
IO - tones.beep (19:51:47.673) - MainThread (15304):
Beep at pitch 226.44649206156825, for 80 ms, left volume 50, right volume 50

### Developer info for navigator object

name: '\uf14a I agree to the Terms of Service.'
role: ROLE_CHECKBOX
roleText: None
states: STATE_CHECKABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 
0x06974670>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 
'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 
'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, 
<class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, 
<class 'baseObject.AutoPropertyObject'>, <class 
'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=476, top=998, width=288, height=42)
value: None
appModule: <'appModuleHandler' (appName 'firefox', process ID 4340) at 
address 373afd0>
appModule.productName: 'Firefox'
appModule.productVersion: '86.0.1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 722576
windowClassName: 'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
extendedWindowStyle: 256
windowThreadID: 6680
windowText: 'Social Security — Mozilla Firefox'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x52b532c at 6be4610>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=722576, objectID=-4, 
childID=-184549857
IAccessible accName: '\uf14a I agree to the Terms of Service.'
IAccessible accRole: ROLE_SYSTEM_CHECKBUTTON
IAccessible accState: STATE_SYSTEM_MARQUEED, STATE_SYSTEM_VALID (8192)
IAccessible accDescription: ''
IAccessible accValue: None
IAccessible2 windowHandle: 722576
IAccessible2 uniqueID: -184549857
IAccessible2 role: ROLE_SYSTEM_CHECKBUTTON
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT (5120)
IAccessible2 attributes: 
'margin-left:0px;checkable:true;text-align:start;text-indent:0px;id:agreementLabel;tag:label;xml-roles:checkbox;margin-top:0px;margin-bottom:0px;margin-right:0px;display:block;formatting:block;'



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/nvaccess/nvda/issues/12204

**Comment by Adriani90** [comment]
@XLTechie are you still having this issue in NVDA last alpha with Firefox 112? I cannot reproduce and the design of that website changed. There is no checkbox "I agree" or smething similar on that link.

**Comment by seanbudd** [comment]
Closing this as can't reproduce. Please provide another sample if this is still an issue
