### ISSUE TITLE
Fix a load of linting issues

### ISSUE THREAD

**Issue by Robin66** [nvaccess/nvda#12261]
I am analysing the NVDA codebase for a university course and I noticed there are many linting issues such as whitespaces that show up when you run Flake8 on the whole source folder instead of the diffs.

### Is your feature request related to a problem? Please describe.
There are many linting issues in the source code that can be fixed with auto-formatting.

### Describe the solution you'd like
Apply an auto-formatter on all or the most important files. 

### Describe alternatives you've considered
Not all Flake8 erros are fixed with auto-formatting, so you could fix all the auto-format warnings in one go and leave in the other problems, or you could focus file by file and fix the other issues manually. In that case it would probably be a good plan to focus on important files first.
Regardless of that, it might be more practical to do only a couple of files at a time, since other people are also working on changes of course.

### Additional context
Currently linting is only checked on the diffs. When you check the full project, it is full of old linting issues. If a large batch of these are fixed in one go, it would become easier for others to contribute, since they will not have to deal with as many existing issues they are asked to fix, just because they had to change those lines.
I would be happy to take up this issue if the community thinks this is a good thing to do. If so, my main question is if I should focus on a couple of files and any thoughts on what files would be the most important.

**Comment by MarcoZehe** [comment]
I think this is a great idea. Two suggestions:

1. Do it on all files at once if possible, minimizing friction.
2. Do it at the start of a new cycle, e. g. after 2021.1 has been merged to RC or has just been released and all issues fixed during the beta/RC cycle have been merged back to Master. That way, all contributions for 2021.2 will start from the newly formatted code.

It may impact a few open merge requests which would have to merge Master anyway, but generally, this is how I would do it, not in the middle of a cycle.

**Comment by Robin66** [comment]
@MarcoZehe that timing thing sounds like a good idea. Is there any form of timeline estimate for 2021.1?

**Comment by lijianwei2019** [comment]
@feerrenrut

**Comment by CyrilleB79** [comment]
Hello Robin

It seems that's your first contact with NVDA project. Welcome to you.

I am just a single contributor. Eventually it will be up to NVAccess people to decide if it is relevant to submit a PR on this topic.

I want to highlight some points to take into consideration:
* Using `git blame` to know who has written a line of code and in which commit/PR will point to the foreseen code linting commit. Maybe an additional argument may be used to ignore this commit, but in any case, I think it would make `git blame` more difficult to use. Maybe git has an repo-wide option to ignore a commit when blaming. In this case, it should be considered.
* Regarding timing, NVAccess is currently trying to reduce PR's backlog (cf #11006). I would recommend to wait that this backlog be substantially reduced (i.e. #11006 be closed) before merging this PR in order to minimize conflicts.

**Comment by XLTechie** [comment]
> It seems that's your first contact with NVDA project. Welcome to you.

**Indeed, welcome!**

> Using git blame to know who has written a line of code and in which commit/PR will point to the foreseen code linting commit. Maybe an additional argument may be used to ignore this commit, but in any case, I think it would make git blame more difficult to use. Maybe git has an repo-wide option to ignore a commit when blaming. In this case, it should be considered.

@CyrilleB79 I am unclear how this would be any different than somebody doing an 
unrelated PR, and having to fix somebody else's line of code's bad linting, in 
order to get their code to validate.
It happens all the time. Does that not also damage the blame process?

Eventually, most unlinted code will have to be linted, and in, I suspect, the 
vast majority of cases it will be by someone other than whoever wrote it in the 
first place.

Unless I am missing some factor.

The benefits of having major portions of the project correctly linted to project 
standards would seem to outweigh this concern, since it will happen eventually 
anyway.

<p>&nbsp;</p>

My only suggestion on this topic, might be to do the linting and subsequent PRs 
module-by-module, so that they can be accepted when no outstanding merges are 
waiting for the newly linted modules; and so that each might individually have 
fewer merge conflicts if they are not accepted immediately.

Of course it is all ultimately @nvaccess decision, but that's my small opinion.

**Comment by josephsl** [comment]
Hi,

I tend to favor issue by issue strategy. Based on my experience with linting several NVDA add-ons last year (StationPlaylist, for example), resolving one linting error causes others to show up, or even bugs to surface. Because a linting error can span multiple modules, I think it would be more efficient to describe and mitigate a lint error, test changes, and package them as separate PR's, one per issue or a family of them. For example, using Flake8, several issues with spacing can cause E501 (line too long) to be recorded.

You can of course perform a module by module PR. But there are lint issues that spans multiple modules, or causes lint fixes made in one module to cause problems for others. For example, I gave up fixing Flake8 F401/F403 error in UIA handler (private and public module) as it may cause unexpected bugs with app modules, NVDA objects and such.

In fact, I tried both approaches when I researched Python 2 to 3 conversion way back in 2016. I first tried module by module approach, but learned that issues such as print statement versus print function, xrange versus range, and a host of other issues were found everywhere (well, in multiple modules). In 2019, I and other contributors shifted to submitting issue/PR combos, one per issue or a family of them (so when you read NVDA master branch log from say, June to July 2019, you'll notice commits for specific Python 2 to 3 issues).

I can tell you that linting the whole source code (or a majority of it) is a noble thing, and I can see you succeeding in doing it. I also caution that this will take months to perfect it - it took me several months to check, add, and verify translator comments for NVDA source code (I believe it was done in 2013), and spent three years just working on wxPython 4 compatibility, even longer for Python 3 transition. A final note: it is not the tools and strategies, but your willpower and willingness to understand the disability and screen reader culture, that will ultimately determine the success of this project.

Some advice:

1. As others stated, I agree that it would be best to target this as a summer project (hopefully by then NVDA 2021.2/2021.3 development would be under way).
2. Try replicating a typical NVDA development environment, complete with Visual Studoi 2019, NVDA source code, Python 3.8.9, and the latest Flake8 or whatever linting tool you'll be using. I advise standardizing on Flake8 to align with what NVDA people are using.
3. Before doing any linting work, be sure to create a report on issues found. You can do this by copying the Flake8 config file used by NVDA project, run "flake8 --config=configfile source" from the top-level NVDA source code directory, then pipe the output to a text file for reference.
4. Record ALL linting issues as reported by tools such as Flake8, as it then allows us to come up with a more concrete strategy (after all, you can't travel to a different place without knowing directions to it).
5. I think it would be best to resolve Flake8 E501 error first so line lengths become reasonable, including for comments.
6. When dealing with errors such as E225 or E226, be sure to keep E501 in mind as adding spaces (or reducing spaces) can cause Flake8 to emit this error.
7. Don't worry too much about F401/F402/F403/F405 errors.
8. YOU MUST VERIFY THAT LINT CHANGES DO NOT INTRODUCE REGRESSIONS!

Let us know if you need help.

Thanks.

**Comment by Robin66** [comment]
Thank you @josephsl, you raise some good points.

> I tend to favor issue by issue strategy. Based on my experience with linting several NVDA add-ons last year (StationPlaylist, for example), resolving one linting error causes others to show up, or even bugs to surface. Because a linting error can span multiple modules, I think it would be more efficient to describe and mitigate a lint error, test changes, and package them as separate PR's, one per issue or a family of them. For example, using Flake8, several issues with spacing can cause E501 (line too long) to be recorded.
> 
> You can of course perform a module by module PR. But there are lint issues that spans multiple modules, or causes lint fixes made in one module to cause problems for others. For example, I gave up fixing Flake8 F401/F403 error in UIA handler (private and public module) as it may cause unexpected bugs with app modules, NVDA objects and such.

I don't mean to make any changes that could impact functionality. I was not planning to change variable names or tackle method complexity or anything like that (I know I don't know enough about how things work for that), instead focussing on whitespaces, indentation and line length. With such changes I don't see how fixing them for one module breaks things in another.

> Some advice:
> 
>     1. As others stated, I agree that it would be best to target this as a summer project (hopefully by then NVDA 2021.2/2021.3 development would be under way).
> 
>     2. Try replicating a typical NVDA development environment, complete with Visual Studoi 2019, NVDA source code, Python 3.8.9, and the latest Flake8 or whatever linting tool you'll be using. I advise standardizing on Flake8 to align with what NVDA people are using.

I was indeed planning on working out the Flake8 errors, but with help of the PyCharm auto-formatter. I will make sure to update everything before I start.

>     3. Before doing any linting work, be sure to create a report on issues found. You can do this by copying the Flake8 config file used by NVDA project, run "flake8 --config=configfile source" from the top-level NVDA source code directory, then pipe the output to a text file for reference.
> 
>     4. Record ALL linting issues as reported by tools such as Flake8, as it then allows us to come up with a more concrete strategy (after all, you can't travel to a different place without knowing directions to it).

These two points work together and it should not be an issue to provide before and after Flake8 reports.

>     5. I think it would be best to resolve Flake8 E501 error first so line lengths become reasonable, including for comments.

I have already noticed that the automatic fixing of this by PyCharm does not happen for comments (maybe I am overlooking a setting) and for code it does not create the right style for multiline statements, so I would have to fix those manually but if we don't take on the whole source code at a time, that should be manageable.
In that case I would however fix the whitespace issues first to do it in one go instead of two.

>     6. When dealing with errors such as E225 or E226, be sure to keep E501 in mind as adding spaces (or reducing spaces) can cause Flake8 to emit this error.
> 
>     7. Don't worry too much about F401/F402/F403/F405 errors.
> 
>     8. YOU MUST VERIFY THAT LINT CHANGES DO NOT INTRODUCE REGRESSIONS!

I will of course run NVDA from the changed code and run the tests. I am however not very familiar yet with how NVDA is supposed to work, so I might need some help checking if no expected behaviour changes. The chances of that happening with the type of changes I am expecting to make are, as far as I can see, quite small though.

**Comment by feerrenrut** [comment]
Hi @Robin66, and welcome!

This is something that we at NV Access have been considering for a long time, but as you can imagine it hasn't been a high priority. Assuming a high level of care is taken, I don't see any reason to hold this back. It would be fantastic if you were able to make this happen!

Some thoughts:
- I personally use pycharm, it gets most of the formatting right, however I have found there are edge cases that are at odds with our Flake8 preferences, even after spending time on pyCharm configuration. In particular, preferring hanging indent over visual alignment. It also seems to double indent for hanging indent `if` conditions.
- I'd like to see the auto-format tool integrated with our build system, so that it can be easily run by developers.
- It's true we are trying to get through a backlog of PR's, however this is taking a long time, and doesn't look like it will be done soon. A change such as this will likely introduce merge conflicts with those PR's. Please highlight what will need to happen with these PR's (documented when creating a PR for the reformat is fine).
- I believe we can work around the `git blame` issue by using a file listing the ignored commits. A [blog post about --ignore-revs](https://akrabat.com/ignoring-revisions-with-git-blame/). Even if we can't work around this, I don't think it is an issue that should hold a reformat back, developers will just have to follow the blame one commit further into history. (@CyrilleB79)

I agree with you that whitespace and line length changes should be safe, and are responsible for the majority of flake8 errors in the code base. This should also make new work for developers easier.

**Comment by seanbudd** [comment]
I've had to do a lot of linting on #12251 due to a code restructure. Here was the process so far - I imagine some of the manual steps could be automated a bit more if this was to be applied across modules or code bases. https://github.com/nvaccess/nvda/pull/12251#issuecomment-815385670

**Comment by josephsl** [comment]
Hi,

To @TheQuinbox, please read the discussion from start to end, as it should tell you things you need to know.

To others: as NVDA 2021.2 dev cycle is under way, I think it would be best to at least let folks work on small lint issues first as a proof of concept. Also, please ping me if you do come across a file I have worked on so I can assist you in linting my work from the past.

Good luck.

**Comment by leonardder** [comment]
To be very honest, the lack of auto code formatting for NVDA is slightly pissing me of, being acustomed to write in languages where this is no problem at all (such as C# or Rust). It just works.

It looks like there are three possible options:

* Black: hardly configurable, so not an option really

* Autopep8: Is able to parse Flake8 configuration but doesn't care about Flake8Tabs and there doesn't seem to be a way to tell the thing that it should do tabs all the way. I've seen it introducing mixed indents

* Yapf: This one looks interesting as
    * It supports tabs
    * it has about 120 configuration options

  However, it has issues:
    * It merges split lines into a single line, e.g. function calls when it is not necessary to split them
    * It positions closing brackets as a hanging indent instead of at the same indentation level as the opening bracket

**Comment by feerrenrut** [comment]
@leonardder I think you are referring to auto-formatters, which removes the need to manually fix linting errors.
Another option is "Tan" a fork of "Black", but with support for tabs.

Using an auto-formatter would require that the whole working-tree is first reformatted. The concerns raised on this issue will need to be resolved.
