### ISSUE TITLE
Reading comboboxes editable in QT applications

### ISSUE THREAD

**Issue by CoBC** [nvaccess/nvda#12296]
### Steps to reproduce:
- Open a QT application
- Go to a field using a combobox with editable attribute set to true
- Try to read combobox content with left and right arrows
### Actual behavior:
- NVDA say nothing, braille cursor is not moved
### Expected behavior:
- NVDA should speak letters, and cursor braille should moved
#### NVDA installed/portable/running from source:
- Installed
#### NVDA version:
- Alpha
#### Windows version:
- 10.0.19042.928
#### Name and version of other software in use when reproducing the issue:
- TeamTalk 5.7
- All other QT applications
#### Does the issue still occur after restarting your computer?
- Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- No
#### If add-ons are disabled, is your problem still occurring?
- Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- Yes

**Comment by CoBC** [comment]
@leonardder is this something you can look?

**Comment by seanbudd** [comment]
We can try looking at TeamTalk, but a minimal sample application will make reproducing and investigating this easier.

**Comment by CoBC** [comment]
I cannot make a GUI for example now. Can you test with TT beta (bearware.dk/beta) and use Stream dialog (CTRL+S) to reproduce this?

**Comment by michaelDCurran** [comment]
When the combo box gets focus, QT needs to fire focus on the inner QLINEEdit widget. so that ATs understand that it is the edit field that is being interacted with, not the combo box.
However, it will be important that the focus event for the QLINEEdit be fired after (or instead of) the focus event for the combobox, otherwise if the events appeared in the cincorrect order, the AT would still think that the final focus was on the combo box.

the alternative is for the Combobox itself to expose the UIAutomation TextPattern, but this would be duplicating functionality.

Finally, NVDA could add specific functionality for these combo boxes, looking for a QLINEEdit child and internally redirecting focus to that. But if this issue affects other ATs then obviously it is better to address it in QT.

**Comment by CoBC** [comment]
@michaelDCurran No answer from Qt devs for now for this issue. JAWS and Narrator reads correctly comboboxes editable. Can you implement a fix on the NVDA side as you envisioned in your last post.

**Comment by CoBC** [comment]
Finally fixed on the Qt side: ([QTBUG-107572](https://bugreports.qt.io/browse/QTBUG-107572))
