### ISSUE TITLE
Consider Cythonizing When compiling

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#12338]
### Is your feature request related to a problem? Please describe.
Not necessarily a problem, but it certainly would make NVDA run faster, possibly also allowing us to remove certain things from nvdaHelper that needed it for the speed.
### Describe the solution you'd like
Cythonize the NVDA codebase when building, thus majorly improving speed.
### Describe alternatives you've considered
Just keep it the way it is is the only one I can think of.  As I said, it's not necessarily a problem, but would be interesting and nice if it could happen.
### Additional context
There's a tool for Python, called Cython.  Pip install Cython.  It turns your Python modules into native C DLLs that Python can handle, with a file extension .pyd.  Very similar to the .pyc files, but native C.  Having all this be compiled to C code when running would improve speed by a lot.  I'm not sure how Cython interfaces with SCons, however.

**Comment by josephsl** [comment]
Hi, some issues to consider, namely performance under ARM64 (x86/x64 binaries will be emulated in Windows 10 on ARM), Cython being optimized for scientific computing and other critical tasks, and compatibility with C extensions and other Python libraries (such as wxPython). Thanks.

**Comment by lukaszgo1** [comment]
I believe this has been discussed with @michaelDCurran during one of the NVDA conferences where he said that either this has been attempted and speed improvements were negligible or he don't believe it would make  NVDA faster. Obviously the best way to measure this would be to actually try Cythonizing and see what happens.

**Comment by JulienCochuyt** [comment]
Another point to consider is how cythonized modules behave in the context of monkey-patching as quite a few addons use it for different purposes.

**Comment by leonardder** [comment]
I did some research into this and cythonizing the whole codebase takes a massive amount of time. This would be quite problematic with our current workflow.

**Comment by ethindp** [comment]
@leonardder It may take a while, but it could most likely be automated. What exactly has to be done? Cython can take raw Python input and can generate code from that; my preferred invocation is something like: `cython --embed -3 --capi-reexport-cincludes --fast-fail -Werror -Wextra` for release or `cython --embed -3 --capi-reexport-cincludes --fast-fail -Werror -Wextra --gdb` for debug.
I'd strongly encourage that this be done. The architecture issue, as pointed out by @josephsl, is not actually a problem because Cython only generates C code and does not actually compile anything. The visual studio tools would take care of generating the architecture-specific code.
Monkey-patching also shouldn't be a problem, I don't think. Cython will still embed the Python interpreter since that's required to even run Python modules.
Finally, as for performance, the only way to actually see if there's a gain would be to try it using the highest optimization settings. The dependencies might be a problem, but I've never been a fan of the fact that the NVDA source code repository ships with (already compiled) libraries. I understand that this is to make it easier to run snapshots or the code itself, but that isn't much of a justification. If your so eager to run the bleeding edge code, then its reasonable for the developers to expect you to know how to set up and build all the necessary dependencies on your own. [vcpkg](https://github.com/microsoft/vcpkg) would probably help with them, though we'd need to push ports to it for those that it doesn't have.
Hope this isn't harsh or anything.

**Comment by Adriani90** [comment]
cc: @gerald-hartig for triaging.

**Comment by ethindp** [comment]
My opinion has, over the last few years, been significantly changed on this issue, and I no question any benefit this may have. Cythonization of code only has a significant benefit if the code isn't just transformed into some Frankenstein C-python monster. This works fantastically well for things like NumPy projects, where I definitely have seen a performance improvement, but for regular Python that hasn't been rewritten into the Cython language I question whether it will actually do anything. Mainly because unless Cython has dramatically changed how it works, ordinary Python is just transformed into a C version but using the Python API from what I've seen of it in the past.

**Comment by gerald-hartig** [comment]
If there is a specific part of the code that will benefit from cython, and this code is also causing a bottleneck, then we should look further into this. 

My understanding however is that:

1. Much of the user-facing performance concerns are related to interacting with windows API and accessibility libraries.
2. Cython has the most impact on CPU bound code like tight loops, heavy data processing or complex calculations like matrix inversions.

Given the level of effort to do this, both for direct code changes and the increased complexity for our build process, I would prefer if someone could first point to a part of the code that will benefit from using cython before we go further. We can then reopen this issue.
