### ISSUE TITLE
Shortcut key for skipping between messages in Outlook

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12438]
### Describe the solution you'd like

I found a very interesting idea to apply to nvda.  provide a shortcut key to jump between messages in Microsoft Outlook.
 Since the shortcut keys are missing, this can be a feature with no shortcut key assigned by default.

**Comment by josephsl** [comment]
Hi, isn’t this idea from JAWS 2021 May update? Can we get more justifications, perhaps a route to test this with Outlook Extended add-on first? Thanks.

**Comment by fernando-jose-silva** [comment]
yes, i am using this feature on jaws and i really liked it, it is making my daily life a lot easier, i believe it would be a good idea for nvda users.  it is worth mentioning that i am also a nvda user.

**Comment by XLTechie** [comment]
I guess control+. and control+,
or control+[ and control+]
don't work for this?

I'm not an outlook user, but those are from the Outlook keyboard shortcuts 
list at:
https://support.microsoft.com/en-us/topic/keyboard-shortcuts-for-outlook-3cdeb221-7ae5-4c1d-8c1d-9e63216c1efd

**Comment by Adriani90** [comment]
@fernando-jose-silva did you consider the comment by @XLTechie above?
Do the Outlook shortcuts ctrl+dot or ctrl+comma work for you? Note that the shortcut could be different depending on which language you use Outlook. You can research for the Outlook shortcut in your language.

I am closing this issue as won't fix.

The only thing that I see here is that NVDA does not report the new focused message when pressing these shortcuts, but this issue is already covered on Github in #10734.
