### ISSUE TITLE
Feature request: Automatically close inactive issues and pr using actions/stale

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#12492]
### Is your feature request related to a problem? Please describe.
There are currently 2384 issues of NVDA's GitHub repository that are open.
Another 8206 issues have been closed.
### Describe the solution you'd like
It is recommended to use [actions/stale](https://github.com/marketplace/actions/close-stale-issues) to manage obsolete pr and issues.
### Describe alternatives you've considered
No better alternative is found for the time being by
### Additional context
Here is a github Actions workflow file for [actions/stale](https://github.com/actions/stale/blob/main/action.yml)

**Comment by feerrenrut** [comment]
We've talked about this internally a few times. It isn't clear how the community would respond to this, it also isn't really clear how this actually helps the project other than perhaps a different (and perhaps misleading) first impression.

Something like `actions/stale` makes the assumption that an inactive issue or PR is obsolete. However there are plenty of perfectly valid feature requests and bug reports for NVDA that are open and inactive. They may be lower priority for a variety of reasons.

One suggestion would be to label these issues when closing them, using something like "closed/inactive". I'm not entirely sure this gets us anything, it may even make it harder to find issues. 

I also want to avoid creating busy work, for instance people bumping their pet issues to prevent them being closed.

**Comment by XLTechie** [comment]
I would not like to see this for the NVDA project.

If new issues are opened that are duplicates of old ones, the issue is 
closed and the user is directed to the old issue.

In the majority of cases, those users do not then comment on the old 
issue, it just stays open and gets older and older, presumably now with 
one more person watching it.

But just because it is well aged, doesn't mean it is an irrelevant issue. 
It may have had 20 newer duplicates over the years, that were closed in 
favor of the old one.
It simply means that nobody has taken the time to work on it yet, or it 
is dependent on some other feature or fix that hasn't happened yet.

I think auto-closing such issues would be bad for the project, leading to 
bugs and feature requests being overlooked.

At least for NVDA, the age of an issue does not indicate that nobody will 
or doesn't plan to ever work on it. That may be different for a project 
with a less community driven style.

**Comment by Brian1Gaff** [comment]
And that would happen of course. Its human nature.
  You almost need a system of triage where items cannot be closed if a flag 
is set by somebody, but then if it is going to need somebody to check them, 
then it is obvious that they could close them, so why automate it?
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment]
>But just because it is well aged, doesn't mean it is an irrelevant issue.

The counterargument to this might be issues can become irrelevant **because** they are old. For instance, issues that are specific to Windows XP are no longer in scope to fix. There could easily be vast numbers of issues that don't have a recent check to see if it still reproduces, or if the issue is even relevant. If we set the auto close inactivity time limit to a long enough time (eg 1 or 2 years) and added excluded issues with certain labels from being closed perhaps that would be ok?


>I think auto-closing such issues would be bad for the project, leading to bugs and feature requests being overlooked.

The same is true for too many issues.

**Comment by XLTechie** [comment]
> The counterargument to this might be issues can become irrelevant because they are old. For instance, issues that are specific to Windows XP are no longer
> in scope to fix. There could easily be vast numbers of issues that don't have a recent check to see if it still reproduces, or if the issue is even
> relevant. If we set the auto close inactivity time limit to a long enough time (eg 1 or 2 years) and added excluded issues with certain labels from being
> closed perhaps that would be ok?

I'm not sure it's much different. The issue triage folks are still going 
to have to tirelessly patrol through issues, only instead of looking for 
ones that are for unsupported versions of Windows, or that can no longer 
be replicated, now they would be looking for ones that they need to flag 
as needing to remain open. Furthermore, now they would be on the clock to 
finish going through all issues before the policy was implemented.
I'd rather see a push to find and close out of date issues.

Unless it's preferable to just start with a clean slate?

> The same is true for too many issues.

I can see that angle, of course. Issue overload, or important issues 
getting swept up in an automated process--different versions of the same 
problem.

But one leans in the direction of caution.

If this were to be done, I would suggest that the policy of directing 
people to old issues when they post a duplicate, must be abandoned. Now 
the new issues should take precedence, unless someone first confirms that 
the old issue has been flagged for non-closure. Which seems like slightly 
more work for issue triage team.

CC @Adriani90

**Comment by alexarnaud** [comment]
I just share my experience with the LibreOffice project which request to bug reporter to confirm their bug every year. This create a lot of unproductive work for bug reporter. It makes me personally stopping confirming every year after some year.

On the Mozilla project, they keep bugs opened. When a bug is opened, except for experimented people the bugs are marked unconfirmed and need to be confirmed by someone else to ensure it is possible to reproduce the issue and their are no unexploitable issues.

@feerrenrut What do you want to do for bug which need a fix somewhere else, for example those with label "label:blocked/needs-external-fix "? Should we keep them open indefinitely or not as we don't have any impact on them?

**Comment by XLTechie** [comment]
> I just share my experience with the LibreOffice project which request to bug reporter to confirm their bug every year. This create a lot of unproductive
> work for bug reporter. It makes me personally stopping confirming every year after some year.

That's exactly what I hope to avoid. Let's face it. For all its enormous 
impact on the blind community, this is actually a small project. We just 
don't have the coder hours to fix every bug, implement every good feature, 
etc. in a timely manner. So some issues are going to get very old while 
still being entirely valid.

> On the Mozilla project, they keep bugs opened. When a bug is opened, except for experimented people the bugs are marked unconfirmed and need to be confirmed
> by someone else to ensure it is possible to reproduce the issue and their are no unexploitable issues.

Personally I have no problem with auto-closing a bug report after three 
months or something, if nobody confirms it. For the most part I think we 
do that now, only in a manual way. I say that, even knowing that a few of 
my bug reports would be closed because nobody has claimed to even try to 
replicate them.

With features though, people would have to campaign to get upvotes for 
their pet issues or something, which seems annoying.

**Comment by lijianwei2019** [comment]
1. Find and clean up issues that are not supported. (Such as: Windows XP, Flash, etc...).

2. Find and clean up duplicate issues , pinned and solve duplicate issues .

3. Strengthening the label issue, classification, statistics, establish project ...

4. Find and clean up resolved or invalid issues. 
@feerrenrut

**Comment by josephsl** [comment]
HI, regarding duplicate issues, I think it is important to come up with a strategy to better educate the public about searching for things before posting a new issue. Thanks.

**Comment by ABuffEr** [comment]
> regarding duplicate issues, I think it is important to come up with a strategy to better educate the public about searching for things before posting a new issue.

About it, recently I have the impression that some users should be redirected to discussion spaces, like nvda-devel or nvda-addons lists or repo discussions, instead of opening new issue. Maybe it could be suggested in bug/feature template.

**Comment by Malvoz** [comment]
I'm not a huge fan of closing out issues only because they didn't receive enough attention in period of time, but NVDA has almost 3k issues. How many of these are still relevant today?

When I find a problem with NVDA I'm always discouraged from opening a new issue, because there are too many similar issues, I have to choose between ignoring existing issues and opening (probably) duplicates and just not report it at all.

[keyword: stale bot]

**Comment by Malvoz** [comment]
> Something like actions/stale makes the assumption that an inactive issue or PR is obsolete.

Could it perhaps ignore issues with e.g. an "accepted/confirmed" label?

**Comment by feerrenrut** [comment]
>Could it perhaps ignore issues/PRs with e.g. an "accepted/confirmed" label?

@Malvoz yes, this is something we would configure. We tend to use the `triaged` label for this.

**Comment by Adriani90** [comment]
I realized that I never responded to this, thanks @XLTechie for tagging me.

In my view, we should not close automatically issues which are inactive unless there was at least one request to provide updates. If the time between the last update and the first update request is more than one year, and the update request is being ignored for at least some weeks, then we close the issue / pr as abandoned. Sometimes we request an update and tag other users who might have the same issues, and hope for feedback from users other than the initial author of the issue. There is no way to automatically do this due to following reasons:
* End of NVDA support for third party applications is a qualitative decision taken by humans, particularly by NV Access
* End of life for third party software or discontinued software needs to be found out in the coresponding articles / ressources of the third party software or in forums, this is a task better done by humans because it is a qualitative decision as well.
* The update request on an issue / PR cannot be automated because NVDA is changing. over time. When we request for the updates, we are not just asking whether an issue is reproducible or not, but in many cases we also give some new indications. If the issue is affecting the community obviously on a larger scale, we tag users who might have the same issue, or developers who might take over the inactive PR  etc.

This is my experience with the triaging over the last 5-6 years, and this process led to many fruitful discussions and valuable input.
Closing inactive issues without any qualitative human based communication will just throw away potential for new input, and will rather hamper the progress towards better accessibility.

I rather suggest to join community forces and test, provide updates, tag users that you might know etc. on old issues. Be proactive and participate in this activity, you don't need to wait for someone to ask you to provide updates.

This being said, I am closing as wont fix.
