### ISSUE TITLE
latest version of Dual voice not compatible with NVDA 

### ISSUE THREAD

**Issue by Afik-souffir998** [nvaccess/nvda#12567]
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
the latest version of the Dual voice addon is not compatible with NVDA. 
any way to fix it?

Afik

**Comment by zstanecic** [comment]
Developer stated that it will be fixed.

Please close this issue.

 

От: Afik Souffir ***@***.***> 
Отправлено: 19 июня 2021 г. 10:00
Кому: nvaccess/nvda ***@***.***>
Копия: Subscribed ***@***.***>
Тема: [nvaccess/nvda] latest version of Dual voice not compatible with NVDA (#12567)

 


Steps to reproduce:


Actual behavior:


Expected behavior:


System configuration


NVDA installed/portable/running from source:


NVDA version:


Windows version:


Name and version of other software in use when reproducing the issue:


Other information about your system:


Other questions


Does the issue still occur after restarting your computer?


Have you tried any other versions of NVDA? If so, please report their behaviors.


If add-ons are disabled, is your problem still occurring?


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


the latest version of the Dual voice addon is not compatible with NVDA.
any way to fix it?

Afik

**Comment by Afik-souffir998** [comment]
I want to keep it open, until it'll be fix.
Thanks


נשלח מהאפליקציה 'דואר<https://go.microsoft.com/fwlink/?LinkId=550986>' עבור Windows 10

מאת: Zvonimir ***@***.***>
נשלח: שבת 19 יוני 2021 11:10
אל: ***@***.***>
עותק: Afik ***@***.***>; ***@***.***>
נושא: Re: [nvaccess/nvda] latest version of Dual voice not compatible with NVDA (#12567)

Developer stated that it will be fixed.

Please close this issue.



От: Afik Souffir ***@***.***>
Отправлено: 19 июня 2021 г. 10:00
Кому: nvaccess/nvda ***@***.***>
Копия: Subscribed ***@***.***>
Тема: [nvaccess/nvda] latest version of Dual voice not compatible with NVDA (#12567)




Steps to reproduce:


Actual behavior:


Expected behavior:


System configuration


NVDA installed/portable/running from source:


NVDA version:


Windows version:


Name and version of other software in use when reproducing the issue:


Other information about your system:


Other questions


Does the issue still occur after restarting your computer?


Have you tried any other versions of NVDA? If so, please report their behaviors.


If add-ons are disabled, is your problem still occurring?


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


the latest version of the Dual voice addon is not compatible with NVDA.
any way to fix it?

Afik

**Comment by leonardder** [comment]
As this issue deals with an add-on and not with NVDA itself, I have to close this.
