### ISSUE TITLE
Say all stops at the positions with the symbols 3 dots and right tick in word documents

### ISSUE THREAD

**Issue by Surveyor123** [nvaccess/nvda#12599]
### Steps to reproduce:
open a word document preferably consisting several lines of text.
insert at some point, of course before the last line,  ...’ 3 dodts and 1 right tick
Navigate to a position before inserted symbols and give say all command.
### Actual behavior:
NVDA stops speaking at the position of the given symbols that is ...’
### Expected behavior:
NVDA should skip to the next text after the symbols.
#### NVDA installed/portable/running from source:
Tested with both installed and portable copies.
#### NVDA version:
NVDA 2020.4 and 2021.1 beta 5
#### Windows version:
Wİndows 10
#### Name and version of other software in use when reproducing the issue:
Microsoft Office versiyon 16.0.14026.20308
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the same.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
@Surveyor123 could you please test with Microsoft Word 2016 or 365 last update and with last alpha version of NVDA? You can download the last alpha version at this link:

https://www.nvaccess.org/files/nvda/snapshots/

**Comment by CyrilleB79** [comment]
Not yet tested with newer version of Office. But with NVDA 2023.1 and Office 2016 version 16.0.5383.1000, the bug is still there.

One thing to note is that, when say all stops speaking, the cursor is located between the three dots and the right tick. But visually it is blinking very fast and irregularly. Then, when I press control key, the cursor blinks as usual, i.e. each second. This lets me think that say all does not stop until I press control, but it tries to move forward without success, sticking at the same position forever.

**Comment by Surveyor123** [comment]
Yes, the issue is not reproducible with the last alpha. It can be closed.

________________________________

**Comment by Surveyor123** [comment]
@Adriani90 I've tested with NVDA version alpha-28022,5f340be5 and Microsoft Office version 16.0.16130.20332 with success.

**Comment by CyrilleB79** [comment]
In my previous comment, I had performed my tests with Word using legacy object model to access documents. However, testing with UIA, the issue cannot be reproduced.

@Surveyor123 would you mind testing using legacy doc access for Word, i.e. setting "Use UI automation to access Microsoft Word document controls" option on "Only where necessary" in advanced options?

If it is confirmed that the issue is still present with Word object model, this issue should not be closed since it is still used by default by Windows 10 users.

@seanbudd, @Adriani90, would you mind reopen until this last point is clarified?

**Comment by Adriani90** [comment]
@Cyrille can you reproduce also with braille display disconnected?I also think object model is going to be used a lot longer. I very much still prefer it also on Windows 11. UIA still has a lot of bugs.This needs more investigation. I think reopening makes ***@***.*** could you also test with last alpha? Von meinem iPhone gesendetAm 05.04.2023 um 09:42 schrieb Cyrille Bougot ***@***.***>:﻿
In my previous comment, I had performed my tests with Word using legacy object model to access documents. However, testing with UIA, the issue cannot be reproduced.
@Surveyor123 would you mind testing using legacy doc access for Word, i.e. setting "Use UI automation to access Microsoft Word document controls" option on "Only where necessary" in advanced options?
If it is confirmed that the issue is still present with Word object model, this issue should not be closed since it is still used by default by Windows 10 users.
@seanbudd, @Adriani90, would you mind reopen until this last point is clarified?

**Comment by CyrilleB79** [comment]
These tests were already made with no braille display connected. On this computer, I am running Windows 10 (21H2) and Office 2016 version 16.0.5383.1000. So UIA is not recommended (and not enabled by default) due to both the old (but still supported) Office version and the windows version.

**Comment by Surveyor123** [comment]
@CyrilleB79 You're right. It can be reproduced with NVDA 2023.1 and with the recent alpha with Word using legacy object model. And with UIA it's not reproducible for both release of NVDA.
