### ISSUE TITLE
Implement copy HTML format

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1260]
**Reported by taicute on 2010-12-06 13:15**
I want to suggest that NVDA include the ability to copy HTML text or webpage, while retaining the original format like links, headings, table etc. this is a great enhancement for NVDA.

**Comment by leonardder** [comment]
You can already do this by disabling browse mode. Closing as invalid.

**Comment by leonardder** [comment]
Hmm, might have been a bit too quick here, since it is not very easy to copy parts of the website content. You can do a select all though. Issue is still abandoned though, but if someone can file a valid use case for this, I'm happy to reopen

**Comment by jcsteh** [comment]
This could be very useful; e.g. when copying a specific section of a page with headings, links, tables, etc. for pasting into another document or an email. However, it requires significant refactoring of our web support; it's not possible with our current virtual buffers.

@MichaelDCurran, is there any reason we can't do this for Edge, since we don't use buffers there already? Can we make selection set the real selection in Edge and then copy can do a real copy?

**Comment by leonardder** [comment]
Closing this again, this time in favour of newer duplicate #5354, which already has a priority assigned and contains more discussion.
