### ISSUE TITLE
NVDA opens right-click events for left-hand mouse users on Windows 10

### ISSUE THREAD

**Issue by anevins12** [nvaccess/nvda#12642]
### Steps to reproduce:

1. Open native mouse settings
![mouse settings](https://user-images.githubusercontent.com/2318561/125423001-9bdea4aa-316a-4bf5-95cd-2cfa0a78c2ae.png)
2. Change the windows "Select your primary button" to be "Right"
3. Open Chrome or FireFox
4. Go to a web page with a plain text heading. Here's one I created on [CodePen](https://codepen.io/anevins12/full/dyWOKJG)
5. Navigate to the heading
6. Press the 'Space' or 'Enter' key

### Actual behavior:
NVDA right clicks on the page and shows a dialog.
![right-click-event](https://user-images.githubusercontent.com/2318561/125423584-ed666294-de09-47bf-bcc2-76adaeeaa8da.png)

### Expected behavior:
NVDA should respect the Windows mouse configuration for primary keys. As a result, NVDA should trigger the left click in this scenario.

#### NVDA installed/portable/running from source:
Not sure what to put here.

#### NVDA version:
NVDA 2020.4

#### Windows version:
Windows 10 Pro, 20H2

#### Name and version of other software in use when reproducing the issue:
* Firefox 89.0.2
* Chrome 91.0.4472.124

#### Other information about your system:
I am using a Kensington mouse with Logitech software, however I have tested this with the native touchpad or a standard mouse.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Haven't been able to find such an option in NVDA.

**Comment by CyrilleB79** [comment]
I can reproduce this issue on my side (Chrome).
This bug also affects the Enter/Space shortcut in a content recognition result (OCR with NVDA+R) since Enter opens the context menu instead of activating the object at the position of the review cursor.

If totally blind person usually do not use the mouse, this bug may affect:
* left handed accessibility testers
* left handed visually impaired persons

@anevins12 could you modify the title for better visibility? 'mice' -> 'mouse'

**Comment by anevins12** [comment]
Title amended. 
In addition to visually impaired and accessibility testers, I believe people use screen readers that may not have visual impairments. Screen readers can be useful for everyone regardless of ability and can be particularly helpful for people with cognitive and reading disabilities.

**Comment by feerrenrut** [comment]
This behavior should be improved, I suspect it won't be very hard to address. However, this behavior has been around for a long time, fixing it is not urgent.

We'll consider fixing it for 2021.3 if we have time. Otherwise it will be bumped to a subsequent release.

**Comment by feerrenrut** [comment]
Note to anyone considering picking this up. 
Use [GetSystemMetrics](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics?redirectedfrom=MSDN) with the `SM_SWAPBUTTON=23` constant to find out if the buttons are swapped.

To click the mouse: ultimately `winUser.mouse_event` is used. However, in NVDA's python code it is always called via `mouseHandler.executeMouseEvent`. I couldn't find any C++ code referring to the mouse.

I'd suggest adding a property to `mouseHandler` for `primaryMouseButton` and for `secondaryMouseButton`. Then find all usages of `executeMouseEvent` and use either the primary or secondary constant as appropriate.

**Comment by lukaszgo1** [comment]
> I'd suggest adding a property to `mouseHandler` for `primaryMouseButton` and for `secondaryMouseButton`. Then find all usages of `executeMouseEvent` and use either the primary or secondary constant as appropriate.

This approach has some disadvantages:
- Add-ons would not benefit from this by default.
- I can imagine a situation in which someone uses the old `MOUSEEVENTF` constants directly in a patch and it is missed during the review.

Wouldn't it be better to introduce `__getattr__` in winUser` which when someone requests one of the constants related to left / right click returns the value as appropriate for the current buttons placement?

**Comment by feerrenrut** [comment]
Maybe, but it does mean that the context won't be considered. There may be reasons to specifically require left or right mouse button rather than primary secondary. Our primary concern is to fix the core application. Once this is done we could go on to override behavior in add-ons, but this seems more risky.

**Comment by lukaszgo1** [comment]
> 
> 
> Maybe, but it does mean that the context won't be considered. There may be reasons to specifically require left or right mouse button rather than primary secondary. 

With your  design this is still a problem since `MOUSEEVENTF_LEFT`  cannot be relied to be a left mouse button but its meaning depends on the buttons being swapped or not. Perhaps I'm just not understanding what you wanted to say.

**Comment by feerrenrut** [comment]
No, `MOUSEEVENTF_LEFT` would continue to be the same constant. Within NVDA all uses of `MOUSEEVENTF_LEFT` or `MOUSEEVENTF_RIGHT` would be replaced with  `mouseHandler.primaryMouseButton` or `mouseHandler.secondaryMouseButton` as appropriate. Eg

```python
mouseHandler.executeMouseEvent(winUser.MOUSEEVENTF_LEFTDOWN,0,0)
mouseHandler.executeMouseEvent(winUser.MOUSEEVENTF_LEFTUP,0,0)
# becomes
mouseHandler.executeMouseEvent(mouseHandler.primaryMouseButtonDown, 0, 0)
mouseHandler.executeMouseEvent(mouseHandler.primaryMouseButtonUp, 0, 0)
```

Actually, given how often this exact code is used. I'd suggest the following is added as well:
``` python
mouseHandler.clickPrimary()
mouseHandler.clickSecondary()
```

**Comment by lukaszgo1** [comment]
> 
> 
> No, `MOUSEEVENTF_LEFT` would continue to be the same constant.

And that is what worries me. What is the point of keeping a constant which does not behave reliably i.e. we cannot assume `MOUSEEVENTF_LEFT` indeed clicks a left mouse button since it depends on Windows settings. What I've proposed above, aside from being nicer for add-ons, makes sure that constant used for left mouse button indeed clicks a left mouse button regardless of buttons being swapped or not.

**Comment by feerrenrut** [comment]
Using MOUSEEVENTF_LEFT does click the left button, when Windows has the "SwapButtons" set the left button isn't the "primary" button anymore. I'd preserve the current behavior meaning of that constant to avoid confusion, but also because the majority of the impact will be resolved. This has been configurable in Windows for a long time, I doubt it comes up often. With this change will fix all occurrences within NVDA that could potentially get this wrong. That just leaves add-ons. Changing the value of the constant has the potential to break add-ons. Instead, what I'm suggesting gives them a pathway to update to explicit behavior.

**Comment by michaelDCurran** [comment]
I agree with the proposed approach by @feerrenrut 
Note that no matter what that setting is, MOUSEVENTF_LEFTBUTTONDOWN still always refers to the left mouse button. It is up to each application in question to honor the SM_SWAPBUTTON system metric.
So logically, if NVDA wants to click something to activate it, it should send the button set as the primary button.
The winuser constants themselves should never be changed in my opinion.

**Comment by feerrenrut** [comment]
Given the mouse button situation has existed for a long time, I don't think this needs to block the 2021.3 release. Removing the label.
