### ISSUE TITLE
nvda jp read latin when I read english characters

### ISSUE THREAD

**Issue by nuttapalsolo** [nvaccess/nvda#12640]
when I use nvda 2020.4 with windows home in Synthesizer: Microsoft Speech API version 5 I move Arrow keys , but reading latin character such as a = alpha etc I want to know how to read english character please help me. thank you

**Comment by zersiax** [comment]
This appears to be a bit of an oddity with the way the Japanese NVDA's character description mode works. Given its purpose you'd think it would only describe Japanese characters, but it actually describes all of them.
So, the way to fix your issue is to turn off Character Description mode, nvda+. 3 or 4 times in laptop mode, and only turn it on for Japanese content or use the " read current character"  gesture more than once to get only that character described.

**Comment by ehollig** [comment]
It appears @zersiax has provided a solution in https://github.com/nvaccess/nvda/issues/12640#issuecomment-882473084 to @nuttapalsolo's question. Closing as worksforme
