### ISSUE TITLE
Some buttons in calculator are inaccessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1269]
**Reported by peter on 2010-12-10 21:25**
Some buttons in windows calculator are inaccessible by object navigation. Steps to reproduce:
1. run calculator under windows xp
2. choose scientific view
3. try to access e.g. sinus button. Most buttons are inaccessible by object navigation when is the simple review mode activated.

**Comment by ehollig** [comment]
I am able to access all buttons in scientific calculator using Windows 10, although the original author states use of XP. Can anyone replicate?

**Comment by josephsl** [comment]
Hi, in order to reproduce this, someone should try this with Windows 7. Thanks.

**Comment by derekriemer** [comment]
I can access a fare amount of the buttons, but I don't know if all.

**Comment by ehollig** [comment]
@Brian1Gaff, can you test this on Windows 7?

**Comment by leonardder** [comment]
Since this issue clearly states the Windows XP calculator being used and there haven't been reports about the scientific part of the Windows 7 calculator yet, I"m closing this as a won't fix. If there is an issue regarding Windows 7 calculator, please create a new issue providing steps to reproduce.
