### ISSUE TITLE
Give NVDA the ability to automatically detect braille displays.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1271]
**Reported by jkenn337 on 2010-12-11 15:50**
When a braille display is connected to the computer and brltty is installed, NVDA should scan for and automatically detect and start using the connected USB or bluetooth display. This way the user does not have to mess about with choosing their display and things. Orca and the mac already do this. This enhancement should be across all operating systems. 
**Blocking #1555, #3648**

**Comment by leonardder** [comment]
Regarding the Hims driver, it seems that NVDA is currently unable to detect when a display is disconnected. This has the advantage that, when removing and re-inserting the device, the driver automatically picks up the display again. However, this conflicts with @bramd's desire to switch from one manufacturer's display to another's.

**Comment by jcsteh** [comment]
I'm not going to get to work on this before I leave NV Access :(, so here's a brief brain dump.

Most of the ideas (and even a lot of the code) in the t1271a2 branch should still apply. Here are some things that should probably be changed (based on new functionality added since the last work on this branch):

1. We should only support detection for displays which are declared as thread safe (`isThreadSafe`).
2. Rather than `bdDetect` using its own thread to probe, it should use the same background thread that is used for background writing to thread safe displays (`braille._BgThread`). Note that APCs can be used to queue functions to run in that thread. See `braille._bgThread.queueApc` (and its callers). This means we can initialise displays in the background thread, rather than queuing this to the main thread.
3. Previously, we had to check whether Bluetooth ports could be opened in the `bdDetect` thread before initialising the display in the main thread. This is because we didn't want to block the main thread if the device wasn't present. This could result in the display "flickering" before connecting, as well as taking longer to connect. If the init is done in the background thread (as per point 2), we can just init the display without the other probe, since we don't have to worry about it blocking.
4. Some displays use generic USB ids which might also be used by other displays, so the code needs to support trying more than one driver per USB id, which it doesn't currently support.
5. If we're doing the init in the background thread, trying multiple drivers (as required by point 4) should be a lot easier.
6. Rather than having a `CustomWindow` in `bdDetect` which handles `WM_DEVICECHANGE`, we should consider watching for this message in `core.CustomWindow` and using an `extensionPoints.Action` to report that there was a hardware change. This way, other components/add-ons can be easily notified about hardware changes.
7. In order to support detection, a driver must fail to initialise if a device is not present and must report an error when trying to write to the display once it is disconnected. Several drivers don't do one or both of these (e.g. Handy Tech). They either need to be updated accordingly or they must be excluded from support for detection.
8. More data (USB ids and Bluetooth names/addresses) needs to be added to `bdDetect` for various displays. BRLTTY is generally a good source of info, failing good docs on this from the manufacturer.

**Comment by leonardder** [comment]
Thanks for your brain dump, @jcsteh, that will be helpful.

@MichaelDCurran, is this likely to be picked up by NV Access in the near future? If not, how about other contributors interested in making Jamie's brain dump a reality? cc @dkager @bramd

**Comment by michaelDCurran** [comment]
Sadly it is not on the roadmap for now.


However, as always, contributions are welcome, especially with this as 
there is existing code and thoughts from Jamie.

**Comment by leonardder** [comment]
Here is @jcsteh's list in a task list

1. [ ] We should only support detection for displays which are declared as thread safe ( isThreadSafe ).
2. [ ] Rather than  bdDetect  using its own thread to probe, it should use the same background thread that is used for background writing to thread safe displays ( braille._BgThread ). Note that APCs can be used to queue functions to run in that thread. See  braille._bgThread.queueApc  (and its callers). This means we can initialise displays in the background thread, rather than queuing this to the main thread.
3. [ ] Previously, we had to check whether Bluetooth ports could be opened in the  bdDetect  thread before initialising the display in the main thread. This is because we didn't want to block the main thread if the device wasn't present. This could result in the display "flickering" before connecting, as well as taking longer to connect. If the init is done in the background thread (as per point 2), we can just init the display without the other probe, since we don't have to worry about it blocking.
4. [ ] Some displays use generic USB ids which might also be used by other displays, so the code needs to support trying more than one driver per USB id, which it doesn't currently support.
5. [ ] If we're doing the init in the background thread (point 2), trying multiple drivers (as required by point 4) should be a lot easier.
6. [ ] Rather than having a  CustomWindow  in  bdDetect  which handles  WM_DEVICECHANGE , we should consider watching for this message in  core.CustomWindow  and using an  extensionPoints.Action  to report that there was a hardware change. This way, other components/add-ons can be easily notified about hardware changes.
7. [ ] In order to support detection, a driver must fail to initialise if a device is not present and must report an error when trying to write to the display once it is disconnected. Several drivers don't do one or both of these (e.g. Handy Tech). They either need to be updated accordingly or they must be excluded from support for detection.
8. [ ] More data (USB ids and Bluetooth names/addresses) needs to be added to  bdDetect  for various displays. BRLTTY is generally a good source of info, failing good docs on this from the manufacturer.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [30 aug. 2017 07:32 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-325886101 "2017-08-30T05:32:38Z - Replied by Github Reply Comments"):

> 1. We should only support detection for displays which are declared as thread safe (`isThreadSafe`).

Are Alva BC640 and Freedom Scientific considered tread safe, even though this property is not yet declared on them?

> 7. In order to support detection, a driver must fail to initialise if a device is not present and must report an error when trying to write to the display once it is disconnected. Several drivers don't do one or both of these (e.g. Handy Tech). They either need to be updated accordingly or they must be excluded from support for detection.

Done in #7458. Also, #7459 will support this.

> 8. More data (USB ids and Bluetooth names/addresses) needs to be added to `bdDetect` for various displays. BRLTTY is generally a good source of info, failing good docs on this from the manufacturer.

This is actually part of your current implementation I tend to disagree with. Personally, I belief usb ids and bluetooth names shouldn't be placed in bdDetect itself, but rather as properties on the braille display driver classes. E.g. for Baum:

```
deviceIds={
	hwPortUtils.DEVICE_TYPE_BLUETOOTH:
	lambda m: any(m.name.startswith(prefix) for prefix in (
		"Baum SuperVario",
		"Baum PocketVario",
		"Baum SVario",
		"HWG Brailliant",
		"Refreshabraille",
		"VarioConnect",
		"BrailleConnect",
	),
	hwPortUtils.DEVICE_TYPE_HID: {
		"VID_0904&PID_3001", # RefreshaBraille 18
		"VID_0904&PID_6101", # VarioUltra 20
	}
}
```

This also takes away the need for a globalPlugin as part of a custom braille display driver, among other benefits.

**Comment by jcsteh** [comment]
Neither alvaBc6 or freedom-Scientific have been verified as being thread safe. First, at least one of them relies on a windows message loop and the background thread doesn't currently run one, so that possibly won't work. Even if it works now, it will probably fail once displays get init in the background thread, since the window will get created in the init thread. Second, because these both use a proprietary dll, we can't know anything about thread safety without testing.
Regarding your dislike of the bdDetect approach, having this info in the driver itself is a lovely idea... until you realise that requires all drivers to be imported. That's pretty hideous and wasteful, especially since some of these might load dlls at import (though you could move that into the constructor to avoid that particular issue). My first attempt at this suffered from this exact problem before I realised this. :)

**Comment by jcsteh** [comment]
Btw, yes, we do import all drivers when you open the braille settings dialog. However, a user won't always do that and I think it's reasonable in that instance. In contrast, importing every driver on startup seems pretty ugly to me.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [1 Sep 2017, 22:20 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326675240 "2017-09-01T20:20:34Z - Replied by Github Reply Comments"):
> Neither alvaBc6 or freedom-Scientific have been verified as being thread safe. First, at least one of them relies on a windows message loop and the background thread doesn't currently run one, so that possibly won't work. Even if it works now, it will probably fail once displays get init in the background thread, since the window will get created in the init thread. Second, because these both use a proprietary dll, we can't know anything about thread safety without testing.

Does that mean you belief these displays should be excluded from auto detection, in contrast to your initial implementation? Or should we support non-trheadsafe displays and just initialize them on the main thread?

> Regarding your dislike of the bdDetect approach, having this info in the driver itself is a lovely idea... until you realise that requires all drivers to be imported. That's pretty hideous and wasteful, especially since some of these might load dlls at import (though you could move that into the constructor to avoid that particular issue). My first attempt at this suffered from this exact problem before I realised this. :)

Hmm, sounds reasonable. However, it feels extremely ugly to me to have hardware identifiers declared twice, once in the display driver and once in bdDetect.

How about creating an additional module called hwDefs, which would basically contain the code for hardware identification which is now in bdDetect? This way, braille display drivers can be modified to get their hardware id's from the new hwDefs module instead of declaring the identifiers in the braille display modules themselves. Having said that, I don't think that there's a problem with having hw ids declared twice for the initial implementation, as long as we agree that hw ids in the braille display modules should be phased out when auto detection has landed.

**Comment by leonardder** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [2 Sep 2017, 09:14 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326727641 "2017-09-02T07:14:59Z - Replied by Github Reply Comments"):
> How about creating an additional module called hwDefs, which would basically contain the code for hardware identification which is now in bdDetect?

Ah, forget this. We can just give bdDetect a broader scope, not just for auto but also for manual detection.

**Comment by leonardder** [comment]
@jcsteh: I'm intending to change the behavior of hwPortUtils.listUsbDevices to yield dictionaries (like listHidDevices) instead of regular strings, which takes away the need to dive into the registry in order to get the device path, for example in the case of Hims devices. listUsbDevices is currently used nowhere in the code of NVDA, however I'd like to know what you think about this before I make this decision and incorporate it in the code of my i1271 branch.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [2 Sep 2017, 17:14 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326727641 "2017-09-02T07:14:59Z - Replied by Github Reply Comments"):
> Does that mean you belief these displays should be excluded from auto detection, in contrast to your initial implementation? Or should we support non-trheadsafe displays and just initialize them on the main thread?

I don't think we should support non-thread safe displays. They either need to be made thread safe (which requires testing and maybe some windows message loop code for the background thread) or they need to be excluded (which, yes, would be contrary to my initial implementation). We can't keep maintaining backwards compatibility layers forever.

> Hmm, sounds reasonable. However, it feels extremely ugly to me to have hardware identifiers declared twice, once in the display driver and once in bdDetect.

Agreed. I think we could have some utility functions in bdDetect that drivers could call to get relevant identifiers. I do recall thinking about this, so I guess I just never got around to it.

Regarding your concerns about a global plugin being needed for a braille display driver add-on, perhaps we could allow identifiers to be specified somehow in the manifest. However, this gets a bit messier when you need a lambda to match Bluetooth ports, for example.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [3 Sep 2017, 03:10 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326757205 "2017-09-02T17:10:20Z - Replied by Github Reply Comments"):
> @jcsteh: I'm intending to change the behavior of hwPortUtils.listUsbDevices to yield dictionaries (like listHidDevices) instead of regular strings, which takes away the need to dive into the registry in order to get the device path, for example in the case of Hims devices.

I never imagined that device path would be useful, since it is the raw device path, rather than the path associated with some sort of communication layer such as HID or serial. However, your HIMS work makes it clear this wasn't a valid assumption on my part. :) So yes, this makes sense.

> listUsbDevices is currently used nowhere in the code of NVDA

True enough. I also doubt any add-ons use this, so we shouldn't need to worry about backwards compat. Please make sure to mention this in the "Changes for Developers" section of your What's New entries, though.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [4 Sep 2017, 01:26 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326838427 "2017-09-03T23:26:27Z - Replied by Github Reply Comments"):
> I never imagined that device path would be useful, since it is the raw device path, rather than the path associated with some sort of communication layer such as HID or serial.

How about the braillant BI? Is the raw device path somehow related to the device path that is retrieved in the driver for this display?

**Comment by jcsteh** [comment]
brailliantB is either HID or serial. For serial, you need the com port, which you get from the registry, but you never use the USB device path.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [4 sep. 2017 01:22 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-326838271 "2017-09-03T23:22:56Z - Replied by Github Reply Comments"):
> ... and maybe some windows message loop code for the background thread

Could you elaborate on this? What would be a good starting point to implement this?

@dkager, would you be able to test thread safety of the Alva BC driver?

**Comment by dkager** [comment]
I would argue that testing can only prove that something is thread unsafe, not that it is thread safe.

**Comment by leonardder** [comment]
[**@dkager**](https://github.com/dkager) commented on [5 Sep 2017, 18:34 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327232197 "2017-09-05T16:34:59Z - Replied by Github Reply Comments"):
> I would argue that testing can only prove that something is thread unsafe, not that it is thread safe.

I agree. However, there will probably be one point in time where we can safely assume thread safety. for example, I'm using the current handy tech driver as a thread safe driver, and it actually improves both speed and stability.

**Comment by dkager** [comment]
Multi-threading is a notoriously evil subject, though. Seems safer to write a native driver at some point, or at least ping Optelec to see what they have to say (very little I assume).

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [6 Sep 2017, 00:48 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327199528 "2017-09-05T14:48:29Z - Replied by Github Reply Comments"):
> > ... and maybe some windows message loop code for the background thread
> 
> Could you elaborate on this? What would be a good starting point to implement this?

1. You first want to identify whether this is actually an issue, though I'm pretty sure it is. If you can't write or read from the display when it's initialised in the background thread, it's almost certainly this problem.
2. In `braille._BgThread.func`, we call `SleepEx`, which is an alertable wait. That needs to be changed to be an alertable wait that also dispatches window messages. To do that, you use the [MsgWaitForMultipleObjectsEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684245(v=vs.85).aspx) function (though you don't actually need to wait on any handles).

**Comment by jcsteh** [comment]
[**@dkager**](https://github.com/dkager) commented on [6 Sep 2017, 05:09 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327273669 "2017-09-05T19:09:54Z - Replied by Github Reply Comments"):
> Multi-threading is a notoriously evil subject, though.

Certainly. However, if the driver works during normal usage when initialised and written to from our background thread, it's reasonable to assume it will be okay for our purposes.

> Seems safer to write a native driver at some point

There are several good reasons to write a native alvaBc6 driver (avoidance of probing all serial ports, direct access to braille keys, etc.). We do have the tech docs to manage this (and we have a display as well). However, I don't think anyone has the cycles to work on it right now, so that is a factor worth considering.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [30 aug. 2017 07:32 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-325886101 "2017-08-30T05:32:38Z - Replied by Github Reply Comments"):
> 2. Rather than `bdDetect` using its own thread to probe, it should use the same background thread that is used for background writing to thread safe displays (`braille._BgThread`). Note that APCs can be used to queue functions to run in that thread. See `braille._bgThread.queueApc` (and its callers). This means we can initialise displays in the background thread, rather than queuing this to the main thread.

Could it be that you overlooked the fact that the bg thread is also used during initialization? hwIo queues an async read on the bg thread during initialization. However, when display probing is active on the bg thread and it initializes a display from that same thread, the async read doesn't take place since it is queued after the currently running initialization, and the thread won't also take action on completed i/o. So, it will result in no processing of received data from the display, and eventually in a no display found runtime error.

**Comment by jcsteh** [comment]
Oh. Yes, i certainly overlooked this. :( I think it should be easy enough to fix, though. When a driver wants to wait on a response during init, it uses `hwIo.IoBase.waitForRead`. `waitForRead` should be changed to wait on a Windows kernel event (not a Python event) using [`WaitForSingleObjectEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687036(v=vs.85).aspx) with `bAlertable` set to true. That way, it will allow async io completion callbacks to execute while waiting.

You can create a Windows kernel event with something like this:

```
evt = winKernel.kernel32.CreateEventW(None, False, False, None)
```

Don't forget to close it with `winKernel.closeHandle` when cleaning up.

**Comment by leonardder** [comment]
This would mean that waitForRead would return for any i/o, right? SO, also for writing?

**Comment by leonardder** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [7 sep. 2017 07:28 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327690568 "2017-09-07T05:28:10Z - Replied by Github Reply Comments"):
> This would mean that waitForRead would return for any i/o, right? SO, also for writing?

Update: a, got it. waitForRead will now return True if waiting was ended by the event as previously. Returning False now means either a time out or waiting has ended due to an apc queued to the thread. The reason is appropriate logged.

**Comment by jcsteh** [comment]
Well, WaitForSingleObjectEx will return for a write or APC, but I don't
think waitForRead should necessarily return in this case, since it's
intentionally blocking until either the read is completed or the timeout is
exceeded. In other words, I don't think it needs to return early for writes
or APCs. That means you might need to re-trigger the wait in your
waitForRead implementation.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [7 sep. 2017 08:28 CEST](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327700011 "2017-09-07T06:28:03Z - Replied by Github Reply Comments"):
> Well, WaitForSingleObjectEx will return for a write or APC, but I don't
> think waitForRead should necessarily return in this case, since it's
> intentionally blocking until either the read is completed or the timeout is
> exceeded. In other words, I don't think it needs to return early for writes
> or APCs. That means you might need to re-trigger the wait in your
> waitForRead implementation.

Is there something better than subtracting time.time() before the wait call from time.time() after the wait call to calculate the remaining time for a next wait?

**Comment by leonardder** [comment]
After some thinking, I'm not sure whether this fixes our issue.

When initializing a display from the background thread, that thread is currently busy with initializing, and in the initializing process, it calls waitForRead, which makes the background thread itself block. I assume that when queueing an overlapped completion routine when initializing, the initialization (which is the current apc) should have returned in order for the overlapped completion routine to be executed. However, we want to execute that routine during initialization, and not after it, as at that point, initialization has already failed.

Or, and may be I'm just missing this, will the completion routine just interrupt the current running APC? I should study computer science one day.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [7 Sep 2017, 19:26 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327745100 "2017-09-07T09:26:46Z - Replied by Github Reply Comments"):
> Is there something better than subtracting time.time() before the wait call from time.time() after the wait call to calculate the remaining time for a next wait?

That's the only way I can think of. You might want to use Windows' [`GetTickCount`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408(v=vs.85).aspx) instead of Python's `time.time`, as `GetTickCount` returns milliseconds.

[**@leonardder**](https://github.com/leonardder) commented on [7 Sep 2017, 20:14 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327757142 "2017-09-07T10:14:10Z - Replied by Github Reply Comments"):
> When initializing a display from the background thread, that thread is currently busy with initializing, and in the initializing process, it calls waitForRead, which makes the background thread itself block. I assume that when queueing an overlapped completion routine when initializing, the initialization (which is the current apc) should have returned in order for the overlapped completion routine to be executed.

That's a good question. I actually had to go look this up myself. From the documentation for [QueueUserAPC](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684954(v=vs.85).aspx):

> If you perform an alertable wait inside an APC, it will recursively dispatch the APCs. This can cause a stack overflow.

I think the stack overflow bit is only relevant if you have too many levels of this, but we should only ever go two APCs deep, so we should be fine. There's no reason we should ever run another init function within the first init function.

Btw, the documentation confirms that this also applies to IO completion functions:

> Note that the ReadFileEx, SetWaitableTimer, and WriteFileEx functions are implemented using an APC as the completion notification callback mechanism.

However, we want to executethat routine during initialization, and not after it, as at that point, initialization has already failed.

> I should study computer science one day.

This probably wouldn't be taught in computer science. :)

**Comment by jcsteh** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [7 Sep 2017, 21:03 GMT+10](https://github.com/nvaccess/nvda/issues/1271#issuecomment-327767329 "2017-09-07T11:03:01Z - Replied by Github Reply Comments"):
> You might want to use Windows' [`GetTickCount`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408(v=vs.85).aspx) instead of Python's `time.time`, as `GetTickCount` returns milliseconds.

Bleh, ignore that: the timeout is passed in seconds, so `time.time` is better. Sorry for the confusion.

**Comment by leonardder** [comment]
Thanks for elaborating!

I've successfully ported probing to the bg thread, only one nut left to crack:

```
DEBUGWARNING - WX Widgets (18:59:17.417):
..\..\src\common\timerimpl.cpp, line 60:
assert wxThread::IsMain(): timer can only be started from the main thread
Stack trace:
  File "C:\Python27\lib\threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "braille.py", line 1923, in func
    winUser.MWMO_ALERTABLE,
  File "bdDetect.py", line 213, in _bgScan
    self._callLater.Start(POLL_INTERVAL, self._startBgScan, bluetooth=True)
  File "D:\NVDA_source\nvda\miscDeps\python\wx\_core.py", line 16816, in Start
    self.timer.Start(self.millis, wx.TIMER_ONE_SHOT)
  File "D:\NVDA_source\nvda\miscDeps\python\wx\_misc.py", line 1324, in Start
    return _misc_.Timer_Start(*args, **kwargs)
  File "core.py", line 233, in OnAssert
    log.debugWarning(message,codepath="WX Widgets",stack_info=True)
```

This is the wx.CallLater that executes a back ground scan every 10 seconds. Although it should only be started from the main thread, it seems to run just fine, but it shows this debug warning every 10 seconds, which is well, not what we want.

Do we want to have the timer run in the background thread? If not, which is the easiest method, we can just wrap the wx.CallLater in a wx.CallAfter in such a way that we can still stop the CallLater if desired. It executes _startBgScan which itself queues the actual probing apc in the background thread anyway. However, if we have a special background thread, why not have the timer run on that thread. I'm not sure how to do this though, probably using a waitable timer, which executes apc functions.

**Comment by jcsteh** [comment]
> assert wxThread::IsMain(): timer can only be started from the main thread

Oo. Yes, this is bad and definitely needs to be fixed. While starting timers from background threads does seem to work, the fact that it causes wx assertions suggests it could have nasty side effects. We fixed several instances of this last year and suspect this may have led to unexplained crashes in the past.

> This is the wx.CallLater that executes a back ground scan every 10 seconds. Although it should only be started from the main thread,

Not sure if you mean it's only ever started from the main thread or that wx requires that it only be started from the main thread. This part of the stack confirms it's definitely being started in the background thread:

> ```
>   File "bdDetect.py", line 213, in _bgScan
>     self._callLater.Start(POLL_INTERVAL, self._startBgScan, bluetooth=True)
> ```

As you suggest, I think having the timer in the background thread makes the most sense, since the thread is already there. I think using a waitable timer makes sense. Note that you'll need to set the timer in the background thread in all cases so that it gets executed there. Also, ensure it is a one shot timer (lPeriod 0) to avoid the timer accidentally running during a `waitForRead`, which would be... very bad.

**Comment by leonardder** [comment]
I consider the code in the @babbagecom i1271 branch to be feature complete, but before I file a pr, here is an overview of the changes since @jcsteh worked on this. Several things have changed, as @jcsteh's implementation was pre hwIo. Most notably:

1. hwIO.IoBase._recvEvt is no longer a Python event, since threading.Event.wait blocks the calling thread, including queued APCs.

2. hwIO.IoBase.waitForRead no longer waits for hwIO.IoBase._recvEvt to be set, but waits using the kernel32.WaitForSingleObjectEx method. This allows braille display initialization on the background thread. If this change wasn't made, waitForRead would be run on the background thread but would also block all background read attempts, effectively causing no reading to occur at all. :)

3. Bluetooth polling is now every 5 seconds instead of 10. In practice, probing ports that represent devices out of range will cause an increase of this delay, so it will hardly be five seconds in reality.

4. Braille display auto detection no longer uses its own thread but makes use of braille._BgThread. Display driver initialization, instead of being queued to the main thread, is now done entirely on this background thread. Since the background thread now knows about a succesful or failed display initialization, support for one USB identifier being defined for multiple drivers should theoretically be guaranteed. I've actually seen one case of this, namely Hims SyncBraille and Baum VarioPro. The latter is not yet supported by NVDA.

5. In the old situation, a braille display could have USB and Bluetooth definitions. In the current situation, USB definitions are split up between USB HID, USB Serial and USB Custom. The latter will be used for native Hims (#7712) and Freedom Scientific drivers, both work in progress. It will also be fairly easy to add Bluetooth HID support to bluetooth probing.

6. The bdDetect module introduces a new concept called a device match, a namedtuple with several pieces of relevant information to make a connection to a device. In the old situation, we had two types of device matches:

	* UsbDeviceMatch(id)
	* BluetoothComPortMatch(address", name, port)

	In the current situation, we have only one device match named tuple: DeviceMatch(type","id, port, deviceInfo). Here, type is one of HID, Serial or Custom. Bluetooth device matches currently have type Serial, but you can easily check whether it is a bluetooth port by checking "bluetoothName" in match.deviceInfo.

	Note that it has been discussed with @JCSTeh to subclass DeviceMatch, rather than adding a type slot to the named tuple. I have eventually made the decision not to do this, as per the following reasons.

	A. USB definitions are split up into three categories, and these three categories are saved in a dictionary using the same key constants that are used in the named tuples as the device type. So, whatever we do, unless I'm missing something, we need type constants.
	B. Due to the point above, using subclasses would require tieing subclasses to type constants as well as multiple isinstance checks, and thus would require several additional lines of code, which is unnessesary if we just use type constants within the named tuples.

Additional ideas are welcome, though.

7. Alva and Freedom Scientific displays are excluded from auto detection for now, since we aren't sure whether they are thread safe. In contrast, Handy Tech has been added. The new native drivers for Eurobraille, Hims and Freedom Scientific displays will support bdDetect in the future.

8. The following methods have been added to the braille.BrailleDisplayDriver class:

	* _newWithSupportedKwargs: Creates a new instance of a BrailleDisplayDriver, but only with the keyword args it supports. This, although officially unsupported, might ease downgrading to drivers without a port setting in the future. See https://github.com/nvaccess/nvda/pull/7590#issuecomment-334080120 and surrounding comments.
	* _getAutoPorts: Returns possible ports to connect to using L{bdDetect} automatic detection data. Either USB, Bluetooth or both.
	* _getTryPorts(port): Generic function that yields device matches based on the provided port. Port is either a deviceMatch or a string. If a string, should be one of "automatic", "usb", "bluetooth" or a specific Com port. This method yields device matches. To give an example of its functionality, see the below code snippet from the Baum driver.

	```
	def __init__(self, port="auto"):
		super(BrailleDisplayDriver, self).__init__()
		self.numCells = 0
		self._deviceID = None

		for portType, portId, port, portInfo in self._getTryPorts(port):
			# At this point, a port bound to this display has been found.
			# Try talking to the display.
			self.isHid = portType == bdDetect.KEY_HID
			......
	```

	Subclasses can of course extend this method, which is currently the case for the brailliantB driver. It is very likely that the brailliantB override can be removed, though.

9. hwPortUtils.listUsbDevices now yields dictionaries instead of just strings containing the USB ID. The yielded dictionaries contain the USB ID, Hardware ID and device path. The latter is useful for USB Bulk devices.

**Comment by leonardder** [comment]
@michaeldcurran: I forgot to mention that your feedback on the above comment would also be appreciated. Also @qchristensen, @josephsl and others, it would be great if you could share your opinion on how you think braille display detection would fit into the current documentation (e.g. should we just list the supported displays in a separate paragraph, or should we add a note to every specific display paragraph)?

**Comment by zstanecic** [comment]
hi,

i think, that the separate paragraph " supported autodetection braille 
displays" will be a better option


W dniu 07.11.2017 o 10:58, Leonard de Ruijter pisze:

**Comment by jcsteh** [comment]
For what it's worth, I'd suggest:
1. Having a general paragraph noting that NVDA can auto detect many displays and that the display specific section will note if detection is not supported for that display; and
2. Having a sentence in a display section if auto detection is not supported.

Reasons:
1. This means a user doesn't need to read through a huge list to work out whether their display is supported for detection;
2. The eventual aim is for as many displays as possible to support detection, so a list is just going to get longer and longer; and
3. Users can just read the section about their display for display specific info.

Having said that, you should totally ignore my opinion here in favour of NV Access staff. :)

Also, I'd like to publicly thank Leonard for taking over this work, adopting my somewhat incomplete code. I'm really glad to see it live on and finally come to fruition. :)
