### ISSUE TITLE
Support Microsoft project 2007-2010

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1297]
**Reported by jkenn337 on 2011-01-04 17:09**
Please create AppModules for microsoft project 2007 and project 2010 if possible. I and others studying for a bachelors in Information Technology need access to this software to complete college classes.

**Comment by ehollig** [comment]
Since the original poster did not reply to @jcsteh's comment in https://github.com/nvaccess/nvda/issues/1297#issuecomment-155286868, information was not provided on what is not currently supported in the programs, the ticket is over 6 years old, and we are unable to contact the original author, closing
