### ISSUE TITLE
In Firefox, a lot of the time, links and buttons don't click.

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13010]
### Steps to reproduce:
I can't get this to happen reliably, but it is quite frequent. Sometimes  when in Firefox, clicking on a link will cause one of three things to happen.
1. nothing.
2. If a window like Notepad is open, it will atke focus.
3. It will click the wrong link.
### Actual behavior:
Links don't click a lot of the time
### Expected behavior:
It should work just fine, like it does in something like Chrome.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.2
#### Windows version:
Windows version: Windows 10 2004 (64-bit) build 19041.1288
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox (93.0)
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
### Editional Information.
Here's the object information when pressing NVDA f1 on an element that won't click.
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (19:00:59.776) - MainThread (6944):
Developer info for navigator object:
name: 'Citizen Soldier - Thank You for Hating Me (Official Lyric Video) by Citizen Soldier 2 months ago 3 minutes, 10 seconds 1,105,099 views'
role: ROLE_TEXTFRAME
roleText: None
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x071A9EF0>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: 'Citizen Soldier - Thank You for Hating Me (Official Lyric Video)'
location: RectLTWH(left=1408, top=169, width=303, height=60)
value: None
appModule: <'firefox' (appName 'firefox', process ID 2100) at address 710a3d0>
appModule.productName: 'Firefox'
appModule.productVersion: '93.0'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 9701018
windowClassName: 'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
extendedWindowStyle: 256
windowThreadID: 7724
windowText: 'Motionless In White - Voices [OFFICIAL VIDEO] - YouTube — Mozilla Firefox'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa36b0ac at 719a350>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=9701018, objectID=-4, childID=-50337218
IAccessible accName: 'Citizen Soldier - Thank You for Hating Me (Official Lyric Video) by Citizen Soldier 2 months ago 3 minutes, 10 seconds 1,105,099 views'
IAccessible accRole: 'span'
IAccessible accState:  (0)
IAccessible accDescription: 'Citizen Soldier - Thank You for Hating Me (Official Lyric Video)'
IAccessible accValue: None
IAccessible2 windowHandle: 9701018
IAccessible2 uniqueID: -50337218
IAccessible2 role: IA2_ROLE_TEXT_FRAME
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT (5120)
IAccessible2 attributes: 'margin-bottom:4px;explicit-name:true;display:-webkit-box;id:video-title;text-align:start;text-indent:0px;margin-top:0px;margin-right:0px;margin-left:0px;tag:span;class:style-scope ytd-compact-video-renderer;'
Pressing NVDA Shift N, routing the navigator object to the mouse, seems to fix it. I tried to create an add-on to automate this, but it would consistently throw this.
ERROR - eventHandler.executeEvent (18:51:32.645) - MainThread (6944):
error executing event: gainFocus on <NVDAObjects.Dynamic_ButtonMozillaIAccessible object at 0x070E56F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "C:\Users\quinm\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 458, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 107, in next
  File "C:\Users\quinm\AppData\Roaming\nvda\addons\firefix\appModules\firefox.py", line 12, in event_gainFocus
    nextHandler()
  File "C:\Users\quinm\AppData\Roaming\nvda\addons\firefix\appModules\firefox.py", line 17, in focusMouse
  File "api.pyc", line 256, in setNavigatorObject
  File "review.pyc", line 124, in setCurrentMode
  File "review.pyc", line 26, in getObjectPosition
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 108, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 220, in _findContentDescendant
AttributeError: 'NoneType' object has no attribute 'helperLocalBindingHandle'

**Comment by Brian1Gaff** [comment]
Has anyone encountered the random disappearance of Firefox or waterfox on 
clicking some links, ie I had thought it just went into the back ground, but 
actually seems to close the tab.
 Its random, and really hard to get to happen, until, as often happens its 
an important link!

Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Quin" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, November 01, 2021 1:10 AM
Subject: [nvaccess/nvda] In Firefox, a lot of the time, links and buttons 
don't click. (Issue #13010)


### Steps to reproduce:
I can't get this to happen reliably, but it is quite frequent. Sometimes 
when in Firefox, clicking on a link will cause one of three things to 
happen.
1. nothing.
2. If a window like Notepad is open, it will atke focus.
3. It will click the wrong link.
### Actual behavior:
Links don't click a lot of the time
### Expected behavior:
It should work just fine, like it does in something like Chrome.
### System configuration
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.2
#### Windows version:
Windows version: Windows 10 2004 (64-bit) build 19041.1288
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox (93.0)
#### Other information about your system:
N/A
### Other questions
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their 
behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing 
Tool in NVDA's tools menu?
Yes
### Editional Information.
Here's the object information when pressing NVDA f1 on an element that won't 
click.
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo 
(19:00:59.776) - MainThread (6944):
Developer info for navigator object:
name: 'Citizen Soldier - Thank You for Hating Me (Official Lyric Video) by 
Citizen Soldier 2 months ago 3 minutes, 10 seconds 1,105,099 views'
role: ROLE_TEXTFRAME
roleText: None
states:
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 
0x071A9EF0>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 
'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 
'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, 
<class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, 
<class 'baseObject.AutoPropertyObject'>, <class 
'garbageHandler.TrackedObject'>, <class 'object'>)
description: 'Citizen Soldier - Thank You for Hating Me (Official Lyric 
Video)'
location: RectLTWH(left=1408, top=169, width=303, height=60)
value: None
appModule: <'firefox' (appName 'firefox', process ID 2100) at address 
710a3d0>
appModule.productName: 'Firefox'
appModule.productVersion: '93.0'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 9701018
windowClassName: 'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
extendedWindowStyle: 256
windowThreadID: 7724
windowText: 'Motionless In White - Voices [OFFICIAL VIDEO] - YouTube — 
Mozilla Firefox'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa36b0ac at 719a350>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=9701018, objectID=-4, 
childID=-50337218
IAccessible accName: 'Citizen Soldier - Thank You for Hating Me (Official 
Lyric Video) by Citizen Soldier 2 months ago 3 minutes, 10 seconds 1,105,099 
views'
IAccessible accRole: 'span'
IAccessible accState:  (0)
IAccessible accDescription: 'Citizen Soldier - Thank You for Hating Me 
(Official Lyric Video)'
IAccessible accValue: None
IAccessible2 windowHandle: 9701018
IAccessible2 uniqueID: -50337218
IAccessible2 role: IA2_ROLE_TEXT_FRAME
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT (5120)
IAccessible2 attributes: 
'margin-bottom:4px;explicit-name:true;display:-webkit-box;id:video-title;text-align:start;text-indent:0px;margin-top:0px;margin-right:0px;margin-left:0px;tag:span;class:style-scope 
ytd-compact-video-renderer;'
Pressing NVDA Shift N, routing the navigator object to the mouse, seems to 
fix it. I tried to create an add-on to automate this, but it would 
consistently throw this.
ERROR - eventHandler.executeEvent (18:51:32.645) - MainThread (6944):
error executing event: gainFocus on 
<NVDAObjects.Dynamic_ButtonMozillaIAccessible object at 0x070E56F0> with 
extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File 
"C:\Users\quinm\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", 
line 458, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 107, in next
  File 
"C:\Users\quinm\AppData\Roaming\nvda\addons\firefix\appModules\firefox.py", 
line 12, in event_gainFocus
    nextHandler()
  File 
"C:\Users\quinm\AppData\Roaming\nvda\addons\firefix\appModules\firefox.py", 
line 17, in focusMouse
  File "api.pyc", line 256, in setNavigatorObject
  File "review.pyc", line 124, in setCurrentMode
  File "review.pyc", line 26, in getObjectPosition
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 108, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 220, in 
_findContentDescendant
AttributeError: 'NoneType' object has no attribute 
'helperLocalBindingHandle'


-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/nvaccess/nvda/issues/13010

**Comment by TheQuinbox** [comment]
Yup, seen that one too, only like twice though.

**Comment by msviolafangirl** [comment]
I'm having the exact same issues as you with Firefox which is why I recently switched to Chrome and Brave as my main browsers. I also like MS Edge but I'm just more used to chrome for some reason. I used Firefox exclusively for 4-5 years and loved it until this stuff started happening a few months ago and have since switched to other chromium based browsers. I'm not entirely sure if this is just an NVDA specific issue. I could supposedly try with either Narrator or a JAWS demo but I'm really not sure.

**Comment by TheQuinbox** [comment]
I was using brave until quite recently, when I kept having issues of the window dying when I alt tabbed away from it. And not sure if it's specifically an NVDA issue, but NVDA does seem to see the objects as TEXTFRAMES,  until you manually route the navigator object to the mouse. I would create an addon to do it, but I kept getting weird errors, and NVDA's lack of developer documentation makes it quite annoying. Might ask on the dev list, though.

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
Are there specific sites or scenarios in which this is more likely to happen? If so, could you provide details? This is not something I have seen for a long time.

If another app sometimes takes focus, that would suggest it is obscuring Firefox (or Firefox is a very small window). Is Firefox maximised? Does maximising it help?

One other thing to check is whether the page is zoomed. You can accidentally do this if you inadvertently press control+- or control+=. This shouldn't break things - it's a bug if it does - but it's a factor to consider (and an easy workaround if this is the problem). To return the page to normal zoom, press control+0. Note that zoom settings persist for a domain.

**Comment by TheQuinbox** [comment]
The clicking the wrong link/nothing happening happens more on YouTube, but taking to a different window normally happens in google search results. And, routing the mouse only works when the issue of the link doing nothing happens, at which point the role changes from ROLE_TEXTFRAME to ROLE_LINK. The incorrect links thing seems to be totally NVDA, because arrowing to the link after it happens fixes it entirely, while simple web navigation doesn't.

**Comment by jcsteh** [comment]
> And, routing the mouse only works when the issue of the link doing nothing happens, at which point the role changes from ROLE_TEXTFRAME to ROLE_LINK.

When you say the role changes, do you mean when you look in NVDA's dev info for the object? Note that dev info is based on the review cursor. Do you have the review cursor set to follow the mouse cursor?

> The incorrect links thing seems to be totally NVDA, because arrowing to the link after it happens fixes it entirely, while simple web navigation doesn't.

I don't quite follow. When you say "simple web navigation", what do you mean? To activate a link, I'd normally arrow or quick nav to it and press enter. What else are you trying that fails?

**Comment by TheQuinbox** [comment]
I mean the info in NVDA's dev console. Yes, I have that setting on.

What I mean is, quick navigation (e.g. pressing l or h) and then clicking on the link doesn't work, but arrowing to it then pressing it does.

**Comment by msviolafangirl** [comment]
Yeah, this is pretty tricky to diagnose because it's not consistent, but, for example, when I perform a google search and go near the bottom of the page to click the next link, the link doesn't seem to click. Just tried this with Narrator as well and I can get the link to click with Narrator even though NVDA still works better in Firefox by a lot.

**Comment by TheQuinbox** [comment]
Have been using Firefox for a number of months and haven't had this issue, so assuming it was fixed.

**Comment by jcsteh** [comment]
Yes, this was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1395181, included in Firefox 102. I commented on #11185 with this info but missed this issue.
