### ISSUE TITLE
Google Sheets: NVDA does not obey cell coordinates reporting toggle

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13027]
Preface: I think this ticket may have the potential to be expanded to cover as much as the entire set of issues about NVDA's document formatting toggles not working in web-based office suite apps. 

### Steps to reproduce:
1 Open an existing or new sheet in Google Sheets.
2 Make sure that cell coordinates reporting is toggled off by unchecking the corresponding check box in NVDA's Document Formatting Settings dialog.
3 Arrow around the sheet.

### Actual behavior:
NVDA reports everything including the cell coordinates.

### Expected behavior:
NVDA should report everything but the cell coordinates.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA 2021.3 Beta 1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Microsoft EdgeVersion 95.0.1020.40 

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
This issue is occuring only when Braille support is disabled in Google Sheets Accessibility settings under "Tools" Menu.
It is advised to use both screen reader support and braille support in Google products. This ensures that the screen reader works correctly. When both check boxes are enabled, NVDA works as expected. I am closing this issue as works for me.

In case you expect the screen reader support to work differently, you have to contact Google for that.
