### ISSUE TITLE
estoy diceñando una linea braille de bajo costo  alguien aquí que hable español 

### ISSUE THREAD

**Issue by discapacidad5** [nvaccess/nvda#13069]
disculpen que escriba en español pero es que tego un proyecto de línea braille a bajo costo para desarrollar con Arduino y esp32. me gustaría hacerla de código libre que cada quien pueda fabricar su propia línea braille de bajo costo de una forma muy fácil el problema que tengo es que no se como hacer los controladores para que funcione con NVDA  tengo el diseño de la parte de hardware pero me falta el software. y como no hablo ingles necesito alguien dispuesto a apoyarme  que hable español gracias

**Comment by Qchristensen** [comment]
English translation:

"Sorry to write in Spanish but I have a low-cost braille display project to develop with Arduino and esp32. I would like to make it open source so that everyone can make their own low-cost braille display in a very easy way.The problem I have is that I don't know how to make the drivers so that it works with NVDA I have the design of the hardware part but I software is missing. and since I don't speak English I need someone willing to support me who speaks Spanish thanks"

**Comment by Qchristensen** [comment]
Just noticed #13070 is the same in English.  I'll mark this one as a duplicate.
