### ISSUE TITLE
Inconsistent reporting of address bar suggestions in Chrome

### ISSUE THREAD

**Issue by adkurz** [nvaccess/nvda#13145]
### Steps to reproduce:
Open Chrome and focus the address bar. Write some address already opened in Chrome and saved in the history.

### Actual behavior:
NVDA doesn't speak the new suggested address on every written letter, only on some of them. The selection (suggestion) is not updated on every change of it. Not tested with braille.

### Expected behavior:
NVDA should read the new suggested address on every pressed letter, like in Mozilla Firefox.

Example: The address is github.com
g: ithub.com (selected instead)
i: thub.com (selected instead)
t: hub.com (selected instead)

But NVDA only say the selection on one or two letters. The selection is not updated correctly.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Latest alpha
#### Windows version:
Windows 10 21H2 x64, German
#### Name and version of other software in use when reproducing the issue:
Google Chrome 96 x64
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2021.2
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
I tested this with NVDA 2021.3rc1.

I'm not sure I can reproduce the behavior described. Can you please copy from the speech viewer to provide a concrete example?

When I start typing the address `sheets.google.com` I get the following output, I believe this is the expected behavior. NVDA initially tells you the full suggestion (only because it is selected automatically by chrome), as you type each letter that is part of that suggestion that letter is no longer part of the suggestion, and is no longer part of the selection. NVDA reports the letter is unselected. If I type two letters quickly, both letters are reported as unselected at once:
``` 
s
heets.google.com selected
h
h unselected
e
e unselected
e
e unselected
t
t unselected
s
s unselected
dot
dot unselected
g
g unselected
o
o unselected
o
o unselected
g
g unselected
l
l unselected
e
e unselected
dot
dot unselected
c
c unselected
o
om unselected
m
```

I did find a strange situation when the selection changes mid way through typing. NVDA should report "selection changed" and the new selection, instead I got the following:
The first selection was `github.com/nvaccess`, I deviated from this suggestion towards `github.com/nvdaAddons/`. I got the following output:
```
nvaccess selected
n
n unselected
v
v unselected
d
ns/ selected
d unselected
```
Visually `aAddons/` was selected. This seems like an issue to me.

**Comment by nidza07** [comment]
Hello,
this is certainly not what I would consider expected or at least consistent behaviour.
What I expect is for NVDA to always report full selection, rather than saying which letter is no longer a part of the suggestion and is now unselected.
For example, here is this same output in Firefox:
"Search with Google or enter address  edit  collapsed  has auto complete  blank
expanded
g
ithub.com/ selected
thub.com/ selected instead
i
t
hub.com/ selected instead
h
ub.com/ selected instead
u
b.com/ selected instead
b
.com/ selected instead
github
dot
com/ selected instead
c
om/ selected instead
o
m/ selected instead
m
slash selected instead"
In addition to the output being much more clear and always allowing you to know which suggestion is currently selected without you having to manually check, the biggest annoyance for me with this bug in Chrome is that if I were to quickly type two letters, in this case gi, NVDA only says "i unselected", so the autofill suggestion is not even spoken at all.
I don't know if this is a bug with Chrome or NVDA, but I would certainly like to see it consistent with other areas. I would also like to clarify that this used to work in Chrome and the full selection was always spoken, but it broke at some point and as far as I recall, that happened as a result of a Chrome update rather than NVDA, though I could be wrong.
Hope that makes it more clear.

**Comment by feerrenrut** [comment]
The behavior with both browsers seems sub-optimal in my opinion.

>This is certainly not what I would consider expected or at least consistent behaviour.

When we say "expected behavior", we mean "NVDA is operating as it is designed to, given the information presented to it".
Please note that NVDA can only act according to the information that is exposed to it. Firefox and Chrome are different applications, which may expose entirely different UI patterns. In contrast, the document contents are much more likely to be the same, there are standards for how to interpret documents, and (in theory) identical documents are given when requesting the same URL regardless of the browser. However, for the controls/UI around the document there can be more variation.

We may look at providing a more specific experience for the Chrome address bar and suggestions in the future.

**Comment by nidza07** [comment]
I understand that, hence why mentioning that it might be a Chrome bug as well.
However, it is also important to note that Jaws behaves as expected in this area, with an additional feature of announcing the suggested page title for the first time as well, though this is less important to me personally.
What I mean by suggested page title is, if you start typing G into Chrome's address bar, Jaws will say something like: "nvaccess/nvda: NVDA, the free and open source Screen Reader for Microsoft Windows " as long as the suggestion selected is indeed the NV Access GitHub repository. If you continue typing subsequent letters, Jaws only announces the selected address and not this title repeadetly, and from that point it behaves just like NVDA does in Firefox as described above.
So either this is an NVDA bug or a Chrome bug where Jaws is somehow implementing a workaround.

**Comment by feerrenrut** [comment]
See also: https://bugs.chromium.org/p/chromium/issues/detail?id=1184888

We are working with Google to resolve this on our end, we'll get to this as soon as we can.
