### ISSUE TITLE
Nvidia screen reader is not reading full content, it's reading only half

### ISSUE THREAD

**Issue by SravaniChatragadda** [nvaccess/nvda#13148]
Nvidia screen reader is not reading full content, it's reading only half.
Actually, my content is like Tax information and services.
 But it reads like Tax information…
In Drupal

**Comment by Brian1Gaff** [comment]
Is this on the newly installed new version. Try restarting the machine. For 
any bug report to be investigated it is very helpful to fill in the info 
required by the template. It will then prompt you for the needed information 
for debugging it.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "SravaniChatragadda" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Thursday, December 09, 2021 7:00 AM
Subject: [nvaccess/nvda] Nvidia screen reader is not reading full content, 
it's reading only half (Issue #13148)



Nvidia screen reader is not reading full content, it's reading only half.
Actually, my content is like Tax information and services.
 But it reads like Xat information…

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/nvaccess/nvda/issues/13148

**Comment by SravaniChatragadda** [comment]
Hi  Brian,
Nvidia screen reader version 2021.2
Windows 10 Version 21H1 for x64-based Systems

**Comment by zahra21** [comment]
hi. did you test with previous versions of nvda?
i confirm this behaviour since the beginning of nvda but i know a workaround for it that we can read even hundreds of pages using SayAll command.

**Comment by seanbudd** [comment]
Welcome @zahra21 and @SravaniChatragadda ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need a sample of text or an application to test this. We also need clear steps to reproduce the problem.
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers
