### ISSUE TITLE
NVDA CRASHING OUTLOOK WHILE USING CONTACTS

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1315]
**Reported by dharvey on 2011-01-11 08:54**
Hi,

I've conducted a test on my machine using Win XP Pro and Outlook 2007 while using contacts, speech stops and Outlook exits.

STR:
1.  Start Outlook 2007.
2.  Go to Contacts with CTRL+3.
3.  Create a new contact then save.
4.  Find the contact you just created and open it.
5.  Try moving around to edit the contact.  If you get no speech, just hit Escape and Outlook should come back to where it left off.

Problem doesn't occur while using Narator or JAWS.

**Comment by bhavyashah** [comment]
Since @josephsl seems unable to replicate this issue on more recent builds of software, we shall need to retest this issue. Can Outlook 2007 users please aid us in this diagnosis?

**Comment by ehollig** [comment]
@Qchristensen, I do recall you said you have a copy of Office 2007 available. Could you please test the reported issue?

**Comment by Qchristensen** [comment]
I also can't reproduce this using NVDA 2017.3 on Windows 7 SP1 and Outlook 2007.  Quite likely whatever the issue was has been rectified as part of other work since the original issue was filed.  I'm going to close as worksforme, but if anyone can reproduce this, feel free to reopen.

**Comment by stickbear2015** [comment]
I can reproduce this interesting crash with outlook 2016 and windows 10.
I'm reopening this issue because when I get home I can perform more testing, and determine if it's NVDA specific or not.
If it turns out to be I won't need to file another issue on it.

**Comment by Qchristensen** [comment]
@stickbear2015 Interesting, do you mean you can get to step 5 in the original issue in Outlook 2016?  Mine stops responding when I press CONTROL+3 because of #7556 

I hadn't tested in Outlook 2016 originally, but doing it now and substituing:
a) Press control+tab to get to the navigation bar
b) Arrow to "people"
c) Press enter

in place of the original step 2 (press control+3 to go to people / contacts directly), and I can create a contact, then edit without hitting a crash.

**Comment by stickbear2015** [comment]
This issue seems to be specific to NVDA and outlook. to reproduce.
1. open outlook.
2. enter any imap e-mail account's inbox  with ctrl+y..
3. outlook may or may not crash at this point. Most likely will.
4. Attempt to switch to anything else, another folder with ctrl+y, contacts, calendar, etc.
what should happen.
Outlook should switch without a problem.
what actually happens.
Outlook freezes initially than completely crashes, may restart, or completely crash and not self-recover.
Testing performed.
Outlook 2016, NVDA 2017.3 and NVDA next snapshot, outlook and JAWS or windows 17 and 2018 Beta.
Other comments
This crash only happens with NVDA loaded.

**Comment by Qchristensen** [comment]
Note, @stickbear2015's updated description is a duplicate of #7556, so I'll leave it closed and mark it as a duplicate.
