### ISSUE TITLE
Request to snap package or deb for Linux Sistem

### ISSUE THREAD

**Issue by albanobattistella** [nvaccess/nvda#13196]
We ask for the possibility of having .deb or snap packages for a simplified installation for Linux systems.
This would serve to bring this beautiful software to people with specific disabilities.
Thanks for your attention.

**Comment by prater-devin** [comment]
NVDA is compatible with Windows only.  It is much too involved in Windows accessibility API's to be converted to Linux. For a Linux screen reader, see [orca](https://gitlab.gnome.org/GNOME/orca).

**Comment by albanobattistella** [comment]
Thank you for your answer.
Orca is not at the level of NVDA, and since it is open-source I was expecting a version for Linux.
This would be nice to close the gap between proprietary and open source systems.
Regards, Albano

**Comment by lukaszgo1** [comment]
As explained above NVDA relies heavily on Windows specific API's and cannot be converted to run under Unix based systems without a lot of work. Given how small NVDA development team is spending time on making NVDA work under Linux at a level at which Orca works currently would take years and mean much less development for the version for Windows. In short the more reasonable course of action is to spend time on improving Orca or other Linux screen readers rather than porting (which in practice would mean almost rewriting from scratch) NVDA to run under a non Windows system.

**Comment by Brian1Gaff** [comment]
Unless of course one of the desktops available wishes to implement Microsoft 
api in its entirety.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by feerrenrut** [comment]
As explained above, this is not currently a realistic goal for the NVDA project.
