### ISSUE TITLE
NVDA not selecting button in browse mode

### ISSUE THREAD

**Issue by GeraldJ4** [nvaccess/nvda#13234]
### Steps to reproduce:
![image](https://user-images.githubusercontent.com/92549700/149166735-b8048ea5-ca49-4826-aba8-22d1865240f4.png)
When in browse mode, button and span are being read on the same line, and I am unable to open the button via the keyboard. Sample HTML: 
`<div><span>1 like</span><button type="button">Reply</button><div>`

### Actual behavior:
Button is read on the same line as the likes, but I am unable to activate the button in brrowse mode. 
### Expected behavior:
To be able to navigate to the button directly in browse mode. 
#### Name and version of other software in use when reproducing the issue:
Chrome Version 94.0.4606.81

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Hello @GeraldJ4

When you are on the line containing the button, just press tab or move with the left/right arrows to the button to have it selected. Then press Enter to activate it.
I hope I have understood you correctly.

If this answer solve your issue, please close it. Else, try to be more specific:
* Do you really want to activate the button (i.e. press it to trigger the associated action)? Or do you just want to focus it?
* What happens if you tab, or arrow left/right to the button and press Enter. And what did you expect instead?
* How can you see that the button is activated or not? Your code snippet does not have an action associated to this button; thus it is normal that nothing happens. You may want to provide a more complete example (e.g. CodePen)
* etc.

Please note that it seems that your issue is more a general question on how to use NVDA in browse mode than a bug report. For such questions, you'd rather use the NVDA mailing list nvda@nvda.groups.io (see [this page](https://nvda.groups.io/g/nvda)), whereas GitHub is used for bug reports or new feature requests.
