### ISSUE TITLE
On focused table element with tabindex="0", Javascript Keyevent for home key is not triggered. When I close the application,NVDA, It is working as expected

### ISSUE THREAD

**Issue by KondaManjunathSaiPradeep** [nvaccess/nvda#13246]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:
1. Create sample table. on the table element set the tabindex=0 so as to receive the focus. As a prerequisite, attach event-listener on the element. 
2. Once the focus is on the table element, press home key. The keyevent with home key is not fired. when i use ctr+shift+7 on the numpad that is an alias for home key. The keyevent is fired.

### Actual behavior:
NVDA hijacking the keys on keyboard

### Expected behavior:
NVDA should not hijack the keys on the keyboard.

### System configuration
windows 11

#### NVDA version:
2021.3

#### Windows version:
11

#### Name and version of other software in use when reproducing the issue:
webpage with sample table

### Other questions
Does the issue still occur after restarting your computer?
yes

Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. Both of them produced same results
 If add-ons are disabled, is your problem still occurring?
yes.

**Comment by CyrilleB79** [comment]
NVDA overrides the numpad when numlock is off; that's a feature of NVDA.
To solve your issue, you may:
1. Use Home key from the alphanumeric keyboard reather the one on the numpad; note that it may require to press the Fn key on some laptops.
2. Press NVDA+F2 before using home, end, arrows, pg up and pg down on the numpad.
3. Use [Numpad Nav Mode](https://addons.nvda-project.org/addons/numpadNavMode.fr.html) extension and the laptop keyboard layout.
HTH

**Comment by KondaManjunathSaiPradeep** [comment]
Sorry if I interpret the problem worngly.

when I press the home button ,not on numpad but right above the arrow keys, the keyevent is not fired.
when I press the home button on numpad with control+shift+7 which is a shortcut for Home key, the home key event is fired.

**Comment by feerrenrut** [comment]
> NVDA hijacking the keys on keyboard

When NVDA is in browse mode, this is a very intentional feature. 

By default, when changing to browse mode you hear a "boop" sound, changing to focus mode you hear a "click" sound. These can be replaced with speech via the option in NVDA settings, browse mode, "Audio indication of focus and browse modes  check box". A user can manually change between browse mode and focus mode with `NVDA+space`
- Focus mode may be called applications or forms mode in some other screenreaders, in this mode key presses are passed through to the underlying application.
- Browse mode allows a screenreader user to navigate with "quick nav" keys, eg 'h' jumps to the next heading. Keys presses aren't passed through to the underlying application.

**Comment by ehollig** [comment]
As @feerrenrut mentioned in https://github.com/nvaccess/nvda/issues/13246#issuecomment-1015046126, this is because, although the table receives focus by pressing tab because of the tabindex=0, NVDA is still in browse mode. Browse mode allows a screen reader user to navigate using quick navigation keys such as T for next table, H for next heading, etc. Key presses aren't passed through to the underlying application unless NVDA is not in browse mode.

Based on this explanation, this sounds as if it is working as expected. Please provide more information if I have misinterpreted the issue.
