### ISSUE TITLE
NVDA does not follow wia-aria principles for the data grid https://w3c.github.io/aria-practices/#grid

### ISSUE THREAD

**Issue by KondaManjunathSaiPradeep** [nvaccess/nvda#13249]
Is your feature request related to a problem? Please describe.
wia-aria created design pattern and keyboard interaction for the role grid layout. please find the link in the description:
https://w3c.github.io/aria-practices/#grid

 Describe the solution you'd like
Since NVDA only designed for windows operating system, mac or linux users will have to follow the standard approach by
sticking to wia-aria-practices, since web is universal across all the platforms. If you provide the keyboard interaction designed for grid layout like mentioned in the above url. It will help users ward off the confusion.

**Comment by feerrenrut** [comment]
This does not adequately describe a problem, I'm going to close this issue.
It seems there is a misunderstanding here about how to use NVDA, when in focus mode, the interactions with the grid are as described.

Browse mode provides a UX overlay, giving screen readers a consistent interface to interact with documents, there is specific table navigation commands. These are consistent with documents outside the web, eg Office applications.

In the example I tried, NVDA does not automatically swap to focus mode, the user must manually do this. When focus enters elements with certain roles NVDA will enable focus / applications / forms mode. In this case keys will be passed through to the browser. However, the web developer must put a lot more consideration to the keyboard UX in order to make this a good experience. Even then it is difficult for users, they will have to discover/learn all new patterns of interaction.
