### ISSUE TITLE
Start and stop Braille viewer via a configurable command/Input Gesture

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#13258]
### Is your feature request related to a problem? Please describe.
For deaf-blind users, who are interacting with the computer via a refreshable Braille display, the information given via speech is often not available. What is on the Braille display is what matters. The Braille viewer is aimed at sighted assistants who will then be able to get a visual Braille representation of the information the user is getting.

According to the user guide in NVDA 2021.3.1, it is only possible to turn the Braille Viewer on and off via the Tools menu. This is something that can be a bit complicated to quickly explain to a sighted helper.

### Describe the solution you'd like

A configurable command in the Input Gestures dialog to toggle the Braille Viewer similar to what we have for the Speech viewer.

### Describe alternatives you've considered

Using the Speech viewer instead. Is it the same as what is given in Braille? I haven't been able to get sighted verification, so if this is the case then the issue may be closed.

### Additional context

 As stated above, this issue may be irrelevant if the Speech viewer can be used instead.

**Comment by CyrilleB79** [comment]
> According to the user guide in NVDA 2021.3.1, it is only possible to turn the Braille Viewer on and off via the Tools menu. This is something that can be a bit complicated to quickly explain to a sighted helper.

You can explain it this way to sighted people:
"Right click on NVDA icon in the systray to open NVDA menu and click Tools, then Braille viewer"
Does it fit your needs?

> A configurable command in the Input Gestures dialog to toggle the Braille Viewer similar to what we have for the Speech viewer.

I agree however that it seems strange to have a shortcut for speech viewer and not for braille viewer that are quite similar. I do not know if it was a deliberate choice. If it was deliberate, maybe it's because the speech viewer window is bigger and covers a larger screen area, thus disturbing more often the activity on the screen.

> Using the Speech viewer instead. Is it the same as what is given in Braille? I haven't been able to get sighted verification, so if this is the case then the issue may be closed.

No: the speech viewer shows a list (or actually an edit field) which is appended with the spoken text each time something new is spoken. The Braille viewer on the contrary only shows what is currently brailled on the braille display. Moreover, what is brailled is not the same thing as what is spoken, e.g. "Button" is spoken when "btn" is brailled.

**Comment by DGartmann** [comment]
Thanks for explaining the difference between the viewers. Come to think of it, I think I would leave the Braille viewer on for this user, but for consistency and configurability, I agree that it is a bit odd not to have a script for toggling the Braille viewer on and off.

**Comment by feerrenrut** [comment]
If there is a use case for a command to open close the braille viewer, I'm happy for that to be added.

I didn't add this because I didn't expect toggling it to be a common action, and the `NVDA+n, t, b` shortcut was quick enough for me. That sequence may be difficult for some.

**Comment by CyrilleB79** [comment]
@feerrenrut do you know what was the use case for the speech viewer shortcut?

@DGartmann let us know if leaving the braille viewer always on causes some issues, e.g. masking an area of interest on the screen.

**Comment by DGartmann** [comment]
It is going to be very difficult for me to get visual verification from that user. But I would be interested to know the reason for adding a shortcut key to the speech viewer and not to the Braille viewer. An unassigned script/command would also work in my scenario.

**Comment by feerrenrut** [comment]
@CyrilleB79 I don't know, sorry. I'm happy for a command with no assigned gesture to be added. This should be fairly straightforward to add.
