### ISSUE TITLE
NVDA announcing graphics clickable when event delegation is attached to the root

### ISSUE THREAD

**Issue by DarioR01** [nvaccess/nvda#13262]
### Steps to reproduce:

1. Download the following html file [test.html.zip](https://github.com/nvaccess/nvda/files/7904830/test.html.zip).
2. Open the test.html page in Firefox.
3. With NVDA running, navigate the page with down arrow strokes.
4. Notice how NVDA announces 'clickable graphic test text'.

### Actual behavior:
NVDA announces graphic elements as clickable when the event delegation is attached to the root.
### Expected behavior:
NVDA should not announce graphic elements as clickable when the event delegation is attached to the root.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
release 2021.3.1
#### Windows version:
Windows Pro 10.0.19043 Build 19043 
#### Name and version of other software in use when reproducing the issue:
Firefox esr version 91.5.0 (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

- NVDA 2021.2 also announces clickable.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
#### Further informations
A very similar bug was reported to [Facebook React](https://github.com/facebook/react/issues/20895).

#### Further investigation
The bug seems to occur only on img tags. No other tags seems to be affected.

If we inspect the provided test.html page in the accessibility tab we can notice the graphic element having a keyboard warning in the accessibility tree.
We can also notice a click action attached to the graphic element in properties' dropdown.

Image showing the Firefox accessibiliy tab containing keyboard warnings and click action in Properties dropdown:
![Accessibility tree](https://user-images.githubusercontent.com/90621252/150339487-ba7a198f-46ff-49c3-b819-26479e69f72c.png)

#### log file
[nvda.log](https://github.com/nvaccess/nvda/files/7905141/nvda.log)

**Comment by feerrenrut** [comment]
Please note that if you click the image, the console log message "click" is triggered. This image IS clickable, NVDA is doing the right thing here.

Assuming (in more complicated code) you had some way to identify the click was on the image and not perform the click action, how is NVDA supposed to differentiate that situation from some other web app with the handler on the root and the image is a valid clickable? Putting the clickhandler on the root is a loss semantics, the intention of the clickhandler is no longer communicated well to AT. This might be similar to using `div` everywhere and just using styling to make things look like other elements.

Note: that the browser is exposing the element as clickable. Accessibility tech (AT) such as NVDA consumes the accessibility API exposed by the browser. This isn't something that NVDA or any screen reader should make a unilateral decision on.

**Comment by DarioR01** [comment]
Thank you for the quick and awesome reply.

That is true, the example I have above has a click event firing. But the issue comes when we have events that should not modify the user experience. To make an example, click tracking events for statistical analysis should not have an impact on the user experience.

A 'quick' solution would be to attach all these types of event handlers to the document node instead of the root DOM container. For instance if we attach the event to the document  node:
`` document.addEventListener('click', () => { console.log('click') }) ``
NVDA does not announce clickable anymore and the event gets fired.

Unfortunately, I and my team are using React, which from version 17 started delegating events to the root DOM. [React Event Delegation Article](https://blog.saeloun.com/2021/07/08/react-17-event-delagation.html)

I am already trying to reopen this [issue](https://github.com/facebook/react/issues/20895) with React, hopefully they change their mind or give us a way to add event handlers to the document.

I just have one last question: Can NVDA provide a workaround, or a specific implementation that allow Authors to specify when a listener should be treated as event delegation, or peraphs force NVDA not to say clickable on click events?

Thank you for your time!!!

**Comment by feerrenrut** [comment]
>Can NVDA provide a workaround, or a specific implementation that allow Authors to specify when a listener should be treated as event delegation, or peraphs force NVDA not to say clickable on click events?

I'm not aware of any way currently. We try to avoid unnecessary verbosity for users of NVDA, but not at the expense of vital information. I had a look through this list, and didn't notice anything that may help in this situation.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques

Given that, I don't think there is anything we can easily do without buy in from browsers. This is something to bring up with the standards bodies (W3C Aria working group). Once there is an issue there, please link to it and I can bring it up with our contacts. It sounds like this could become a more frequent problem due to the changes you highlighted in react.

Just some background on why this needs to go via the standards group / browsers, in case it is helpful:
NVDA doesn't consume HTML, it consumes the API exposed by the browser. The browser interprets the page, and builds an accessibility tree. This accessibility tree is exposed via the APIs that are appropriate for the platform.
The "right way" for AT to get access to a new concept is to have it supported in the web/aria standards, implemented in the browser and exposed via the API. Note that the API has it's own process for getting updated. There are a lot of layers and different parties involved, it's not usually a quick process.

**Comment by DarioR01** [comment]
I opened the issue with the W3C Aria working group:
https://github.com/w3c/aria/issues/1684

As mentioned I am also trying to re-open the issue with React:
https://github.com/facebook/react/issues/23170

Thank you for the amazing help 👍.

**Comment by DarioR01** [comment]
I spoke with my team about this issue and we have some more questions about this:

Technically you can ‘click’ the image though when you click the image nothing happens in the user experience, as it’s not an interactive element, it’s just an image. It is not an element user can ‘click’ to perform an action. So why announce this? What value is there to an NVDA user in announcing ‘clickable’ if the element is not interactive?
NVDA can tell that the element isn’t interactive from the accessibility API/tree and therefore could not announce ‘clickable’ it would be assumed?

**Comment by DarioR01** [comment]
Also, elements that are announced as clickable should be focusable and have interactive semantics as explained [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard#clickable_elements_must_be_focusable_and_should_have_interactive_semantics).
In our example the image is neither focusable nor interactive, therefore why is clickable announced?

**Comment by feerrenrut** [comment]
Ok, I've looked into this some more, and consulted with people who have worked on this in the past.
Some important things to note that I didn't cover:
- Reporting clickable is an optional feature in NVDA. It is included as a fallback for sites that don't follow web accessibility best practice. There are still plenty of these sites, many users choose to have "clickable" announced.
  - For completeness I want to mention that the motivation for silencing clickable should also be considered. Specifically, considering whether this is feedback from users or not, there may be more urgent accessibility issues.
- Typically, the nature of interaction with an element should be conveyed via it's role. NVDA shouldn't have to say clickable. If NVDA reports clickable AND the name of a role that already indicates interactivity (eg 'link'), then it is an NVDA bug.
- The [MDN advice](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard#clickable_elements_must_be_focusable_and_should_have_interactive_semantics) is targeted at web authors, rather than AT developers. This is an important distinction.
  - As a web author, if making something clickable, it should also be made focusable, and have keyboard interaction.
  - This is to ensure that AT users can interact with the element. It isn't the minimum requirements for an AT to consider the element as interactive. After-all the application DOES monitor clicks, the click handler may provide user observable behavior.
  - NVDA can detect clickable, and focusable, but not key handlers. They aren't exposed by browsers.
- Finally, using `role=presentation` on the click handler `div` will prevent that `div` from being presented in NVDA and therefore will not report clickable. However, this `presentation` element should not be responsible for exposing other accessibility information because it will be removed from the tree. Example to follow.

### Using presentation role
Extending the example provide in the description of this image:
- I have added a button before to make it easier to focus out and into each graphic.
- There are two examples, first is the test case on this issue, second modifies that to include `role="presentation"`
- The second example also has an extra nested `div` to ensure that the graphic is spoken as its own line.
[Code pen](https://codepen.io/reefturner/pen/LYOPKza) and [full page view](https://codepen.io/reefturner/full/LYOPKza)
```html
<button>before first</button>
<div id="root1">
        <img src="https://picsum.photos/200/300" alt="test text">
</div>
<button>before second</button>
<div id="root2" role="presentation">
  <div> <!-- for display:block to create consistency of reading in NVDA -->
        <img src="https://picsum.photos/200/300" alt="test text">
   </div>
</div>
<script>
    // event delegation
    document.querySelector('#root1').addEventListener('click', () => { console.log('click1') })
    document.querySelector('#root2').addEventListener('click', () => { console.log('click2') })
</script>
```

Result: speech from NVDA, navigating with down arrow in browse mode:
```
button    before first
clickable  graphic    test text
button    before second
graphic    test text
```

This may be a solution for react.

To answer your specific questions:
> It is not an element user can ‘click’ to perform an action. So why announce this? What value is there to an NVDA user in announcing ‘clickable’ if the element is not interactive?
NVDA can tell that the element isn’t interactive from the accessibility API/tree and therefore could not announce ‘clickable’ it would be assumed?

In a perfect world announcing clickable wouldn't be required, every element would have an appropriate role. However, there are many examples in the wild that don't conform e.g. a clickable span in a paragraph, these would become inaccessible.

**Comment by eps1lon** [comment]
> However, there are many examples in the wild that don't conform e.g. a clickable span in a paragraph, these would become inaccessible.

I'm not arguing that ATs should stop doing that i.e. they should continue patching up author errors. But authors also need some tools where this patching up produces false positives. Here: How to convey that a click handler is used for event delegation?

It seems to me that NVDA is just using a11y APIs. So the next step would be to escalate this to browser vendors as far as I can tell.

**Comment by feerrenrut** [comment]
@eps1lon Did you look at the `role=presentation` approach I suggested.

**Comment by greenc05** [comment]
Many thanks for your thorough reply @feerrenrut 

>     * Reporting clickable is an optional feature in NVDA. It is included as a fallback for sites that don't follow web accessibility best practice. There are still plenty of these sites, many users choose to have "clickable" announced.
May I suggest that if this is an optional feature, that this feature should be off by default for NDVA users, accessible sites should not suffer because of inaccessible sites.
 
>     * Typically, the nature of interaction with an element should be conveyed via it's role. NVDA shouldn't have to say clickable. If NVDA reports clickable AND the name of a role that already indicates interactivity (eg 'link'), then it is an NVDA bug.
Does this not also imply that if an element has no role such as that of a div, then no nature of interaction should be conveyed from it, including ‘clickable’. And if it is, then this is an NVDA bug? As stated yourself AT users can’t interact with elements that aren’t focusable etc therefore the element cannot be ‘clicked’ by AT users.

>       * After-all the application DOES monitor clicks, the click handler may provide user observable behavior.
Please provide an example of user observable behaviour announcing ‘clickable’ without any other semantics on a non focusable or interactive element

>     * Finally, using `role=presentation` on the click handler `div` will prevent that `div` from being presented in NVDA and therefore will not report clickable. However, this `presentation` element should not be responsible for exposing other accessibility information because it will be removed from the tree. Example to follow.
Thanks for the role presentation suggestion, I will look into this, however I am not sure that the responsibility for fixing this issue should fall to web authors of accessible code.

**Comment by eps1lon** [comment]
> @eps1lon Did you look at the `role=presentation` approach I suggested.

Sorry I completely missed this. Tried in https://codesandbox.io/s/holy-meadow-y8xfy and it does seem to work for this minimal repro.

Will recommend this in https://github.com/facebook/react/issues/20895 and the see if we can somehow upstream this into React. Either via warning or automatic resolution.

**Comment by feerrenrut** [comment]
@greenc05 

>May I suggest that if this is an optional feature, that this feature should be off by default for NDVA users, accessible sites should not suffer because of inaccessible sites.

Again, NVDA should err on the side of excess verbosity rather than loss of information. Newer sites have to contend with the constraints that already exist. This means working around legacy behavior. There are ways for these newer sites to do the right thing, using `role=presentation` appropriately allows newer sites to provide a better experience for AT users.

>Does this not also imply that if an element has no role such as that of a div, then no nature of interaction should be conveyed from it, including ‘clickable’. 

I don't think so. No role is different from duplicate semantics. EG announcing "clickable button" or "clickable link" is certainly reporting duplicate affordances. A button implies clickable, so does a link. Whereas a missing role, or a role that does not imply clickable, but has a click handler is meaningful and useful for a user to know about.

> And if it is, then this is an NVDA bug? As stated yourself AT users can’t interact with elements that aren’t focusable etc therefore the element cannot be ‘clicked’ by AT users.

I think you misunderstood me here. I said "This is to ensure that AT users can interact with the element. It isn't the minimum requirements for an AT to consider the element as interactive." Different AT have different requirements to be able to cater to the varied abilities of their users. NVDA is primarily catering to vision impairment, but other AT may have different requirements. This set (clickhandler, focusable, keyHandler) ensures that all AT have a way to interact (ie via mouse, via system focus, via keyboard).

>Please provide an example of user observable behaviour announcing ‘clickable’ on a non focusable or interactive element

I think this is getting away from the point. Taking the example given initially on this issue, currently the clickhandler appends the word "click" to the console. Instead it may fetch and insert an explanatory paragraph for the image.

>Thanks for the role presentation suggestion, I will look into this, however I am not sure that the responsibility for fixing this issue should fall to web authors of accessible code.

It's a mistake to think of an application / web page as accessible or not, rather a continuum of how easy it is to use for people relying on various AT. In this case, I'd say it negatively impacts accessibility to have a click handler without explicitly declaring it as "presentation only".  Think of this an opt-in for web-authors to say "yes, I know what I'm doing, users don't need to know about this click handler". 

Since the conversation may go in this direction, note this is different from `aria-hidden`, [from MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden):

>On the surface, the `aria-hidden="true"` and the `role="presentation"` and its synonym `role="none"` seem similar, but the intent behind each is different.
>`aria-hidden="true"` will remove the entire element from the accessibility API.
>`role="presentation"` and `role="none"` will remove the semantic meaning of an element while still exposing it and its content to assistive technology.

With `aria-hidden` the graphic would not be exposed to AT at all.

**Comment by greenc05** [comment]
Thanks for your time on this @feerrenrut, always good to have disucssions and challenge opinions, hopefully we have an outcome to this issue now with https://github.com/facebook/react/issues/20895#issuecomment-1021175889

**Comment by DarioR01** [comment]
Awaiting React Investigation https://github.com/facebook/react/issues/20895#issuecomment-1021175889

**Comment by feerrenrut** [comment]
Yes, thanks @greenc05 @eps1lon @DarioR01 and others. Fixing this in React is important, and will have a large impact.
