### ISSUE TITLE
Provide a way to avoid loading incompatible app modules

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1327]
**Reported by vtsaran on 2011-01-19 22:54**
When installing the fresh copy of NVDA, the installer, or the program itself, should verify that the user-contributed app modules do not conflict with the new code. Most recently I encountered a situation with one of the app modules, modified by me, where I was getting errors from NVDA due to my code being incompatible with the latest changes within the software. It did not immediately occur to me that the errors were produced by my faulty module, and not by NVDA.
I am not sure if the check has to be done by NVDA itself or by the installer though.

**Comment by leonardder** [comment]
@JCSTeh: Do you have anything to add to your last comment?

**Comment by jcsteh** [comment]
1. Any changes relating to compatibility checks should be done for add-on packages, rather than app modules, as directly copying app modules was deprecated long ago.
2. If we change public API, we do our best to deprecate it for at least one version so authors have time to update their add-ons. We document any deprecations or removals in the What's New.
3. Users should ensure they're running the latest version of any add-ons they're using. This will be made easier once we get automatic add-on updates.
4. Add-ons can do version or API checks when installing (in installTasks), though there is no such facility when NVDA updates.
5. It has been proposed that we specify version requirements in add-on manifests. The problem with this is that when an author publishes an add-on, they can't know in what future release something they depend on might be removed.
6. Overall, I don't think there is a programmatic way to deal with this. However, I think clear documentation of deprecations and removals for developers (as we're already doing) and automatic add-on updates should sufficiently mitigate this.

Closing.
