### ISSUE TITLE
Windows 11 Notepad version 11.2111.0.0 speaks penultimate line of file twice if it is followed by a blank line

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#13275]
### Steps to reproduce:
Using the latest Notepad available to Windows Insiders on Windows 11, type some text, such as "this is line 1" followed by a carriage return. Move to the top of the file, and using the up and down arrow keys, note that the line is spoken twice, and the blank line is ignored. This behaviour is not present in JAWS or Narrator.

#### NVDA version:
2021.3, but latest Alpha has been tested with same result.

#### Windows version:
Windows 11 Home, 64 bit
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Recent Alpha builds  with same behaviour
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, does this issue occur even after installing Windows App Essentials add-on? If so, I will give this highest of highest of priorities before releasing the next add-on release as Notepad 11 is not ready for the general public yet i.e. the app module is ready for use but I’m waiting for Notepad 11 to go live for everyone else. Thanks.

**Comment by josephsl** [comment]
Hi,

Turns out it does occur even with the add-on installed. One workaround is pressing Enter twice, which will then allow NVDA to see blank lines as far as UIA text info is concerned. Also, it turns out Narrator is not completely immune to this issue - if focused on a document with just one line, or perhaps a line of text followed by a blank line, Narrator will say "end of line" when moving to the blank line, and moving up causes Narrator to announce only the first character of the line. This indicates something odd is going on with Narrator or UIA implementation issue with Notepad app itself.

Technical: NVDA does detect caret movement, and when moving to the next line, a different text info expansion is returned, and it appears the blank line text info expansion is not returning an empty text info; rather, the expanded text comes from the line above it. However, when two blank lines exist after the entered text, NVDA does say "blank". Too early to say, but looks like UIA text info (for editable text) may need tweaking, or it is time to report this (and Narrator announcement issue) to apps team at Microsoft.

As for Windows App Essentials add-on, since the issue may as well lie with the Notepad app itself, I'm taking this issue off high priority list.

Thanks.

**Comment by josephsl** [comment]
Hi,

Partly resolved with Windows App Essentials 22.02 - had to bring in the old logic from Windows 10 Start menu where NVDA is told to not announce the just entered text when Enter key is pressed. Did anyone report this issue to Microsoft? If not, let's do that so a future Notepad 11 update can fix it (might be too late for the upcoming release as it is gearing for public debut soon).

Thanks.

**Comment by mwhapples** [comment]
Seems like a similar issue to #13551 and I have created the following feedback request with Microsoft https://aka.ms/AAgkp9i

**Comment by josephsl** [comment]
Hi,

And resolved in Notepad 11.2203.10 (tested by Windows Insiders at the moment). This should be tested once the new Notepad update comes to beta and release prview Insiders and considered for closure once it makes to retail (pubic release) channel as early as May or so.

Thanks.

**Comment by josephsl** [comment]
Hi,

Indeed, if I'm reading Microsoft Store update history correctly, as of April 27, 2022, Notepad 11.2203.10.0 is being deployed to stable channel users. therefore let's close it - please reopen if issues recur (happen again).

Thanks.
