### ISSUE TITLE
Web page content disappear after a few seconds due to unreported subscribe form

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#13358]
### Steps to reproduce:
  1. Open the following URL on either Firefox or Edge: https://www.ntwrightonline.org/
  2. As soon as the page finishes loading, quickly verify that it has regular links and text.
  3. After around 5 seconds, verify again.
  ### Actual behavior:
  Content have disappeared, and page is blank or contains the URL only.
  ### Expected behavior:
  It should tell the user that, actually, a dialog box containing a subscribe form has appeared.
  ### System configuration
  #### NVDA installed/portable/running from source:
  Installed.
  #### NVDA version:
  2021.3.1
  #### Windows version:
  Windows 11 Pro, version 21H2
  #### Name and version of other software in use when reproducing the issue:
  Firefox 97.0
  #### Other information about your system:
  
  ### Other questions
  #### Does the issue still occur after restarting your computer?
  Yes.
  #### Have you tried any other versions of NVDA? If so, please report their behaviors.
  
  #### If NVDA add-ons are disabled, is your problem still occurring?
  Yes.
  #### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
  Yes.

**Comment by tiago-casal** [comment]
Hi! I tested in other browsers and the same strange behavior is happening: in addition to Edge 98, in Chrome 98.0, Internet Explorer 11, Firefox 91.6.0ESR; I used NVDA 2021.3.1 on Windows 10 21H2.

**Comment by ehollig** [comment]
Although this dialog contains aria-hidden="false", the parent div contains an aria-hidden="true".
`<div class="avada-footer-scripts" aria-hidden="true">`
`<div id="pum-5443" class="pum pum-overlay pum-theme-5437 pum-theme-default-theme popmake-overlay pum-click-to-close auto_open click_open pum-active" role="dialog" aria-hidden="false" aria-labelledby="pum_popup_title_5443">`
This would have to be fixed by the website author. Removing the aria-hidden from the above line properly announces the dialog.
