### ISSUE TITLE
When reading a message in Outlook, NVDA says there are no tables to jump to, even if it reports tables in browse mode

### ISSUE THREAD

**Issue by geoffshang** [nvaccess/nvda#13356]
Note that I reported earlier that NVDA seems to be showing layout tables for me in Outlook.  However, this issue seems to happen in messages that also have genuine tables.

### Steps to reproduce:

1.  Open an email in Outlook.

2.  Cursor up and down in Browse mode to verify that NVDA is reporting the presence of tables.

3.  Press t or shift-t

### Actual behavior:

NVDA reports No next table" or "No previous table" as appropriate.

### Expected behavior:

NVDA should jump to the next or previous table, as shown in browse mode.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2021.3.1

#### Windows version:

Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎10/‎10/‎2020
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

#### Name and version of other software in use when reproducing the issue:

Microsoft Outlook 16.0.14326.20784

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Have not tried

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Have not rebooted since running it, doubt it would make a difference

**Comment by CyrilleB79** [comment]
Hello
This issue is lacking information.
If the message where the issue occurs is not confidential could you do the following two actions:
1. Attach to this issue a log at debug level where you reproduce the steps described in the issue description.
2. Copy/paste the whole content in a Word document, try to reproduce the issue in the word document, and attach the Word document to this issue.

Also could you indicate the value of the following options in your config:
* Table information -> Table in Document formatting settings
* Include layout table in Browse mode settings
* Use UIA to access Word documents in Advanced settings

**Comment by mdyer1** [comment]
Hi I am wondering if you have UIA enabled as this is supposed to help with html messages.  As a side note, I receive news letter s written in html and find that messages with headings are handeled the same way.Matthew  / Sent from Mail for Windows From: geoffshangSent: Thursday, February 17, 2022 6:48 AMTo: nvaccess/nvdaCc: SubscribedSubject: [nvaccess/nvda] When reading a message in Outlook, NVDA says there are no tables to jump to, even if it reports tables in browse mode (Issue #13356) Note that I reported earlier that NVDA seems to be showing layout tables for me in Outlook. However, this issue seems to happen in messages that also have genuine tables.Steps to reproduce:Open an email in Outlook.Cursor up and down in Browse mode to verify that NVDA is reporting the presence of tables.Press t or shift-tActual behavior:NVDA reports No next table" or "No previous table" as appropriate.Expected behavior:NVDA should jump to the next or previous table, as shown in browse mode.System configurationNVDA installed/portable/running from source:InstalledNVDA version:2021.3.1Windows version:Name and version of other software in use when reproducing the issue:Microsoft Outlook 16.0.14326.20784Other information about your system:Other questionsDoes the issue still occur after restarting your computer?YesHave you tried any other versions of NVDA? If so, please report their behaviors.NoIf NVDA add-ons are disabled, is your problem still occurring?Have not triedDoes the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?Have not rebooted since running it, doubt it would make a difference—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by geoffshang** [comment]
I will try to find a message that is suitable (i.e. that doesn't contain 
anything sensitive.

Regarding the settings:

* Table information -> Table in Document formatting settings

This was on.  Turning it off hid the table start and end lines from the 
email presentation but did not change any behaviours.  I can still use 
table navigation commands to navigate genuine tables but I'm unable to 
jump to any of the tables in an email.

* Include layout table in Browse mode settings

This is off.

* Use UIA to access Word documents in Advanced settings

Pretty sure this is also off, I've not touched any of the advanced 
settings.

**Comment by Adriani90** [comment]
This issue is still lacking information and we cannot investigate further. We didn't get further updates from the author upon request since more than 2 years. i am closing as abandoned. if you are still having this issue, please comment and we can reopen.
