### ISSUE TITLE
create a shortcut that will read information

### ISSUE THREAD

**Issue by levilibegas** [nvaccess/nvda#13424]
Hi, I would like to suggest that a new shortcut be created. When I move the cursor through a list of elements (files, for instance), all details of each file will be red aloud as I set that in settings. However, I don't know how to make it read information of file where I am sitting on, as it will only will be spoken if I move the cursor arrows. Could it be created a shortcut to read aloud info of current file. Can it be made? thanks 

### Additional context

**Comment by Qchristensen** [comment]
Concentrating JUST on file explorer / Windows explorer, I can see the issue / resolution here.  It's fairly specific so I'll forgive not following the template as the information is there:

Issue:
When you navigate through a list of files in details view, NVDA reads the file name, size, date, type, etc.
If you want to hear that again, you have to move the focus away and back - eg up arrow then down arrow.
- Pressing NVDA+delete (report review cursor location) reports the object position relative to the screen (not very useful)
- Pressing NVDA+tab (Report current focus) reads the item name and its position in the list.
- NVDA+up arrow / NVDA+a, numpad 8 / NVDA+shift+. both simply re-read the file name only.

My proposed resolution:
I don't think we need a new shortcut, but I feel several existing keystroke behaviours could be improved here:
- NVDA+tab (report current focus) should read the information as if you had just arrowed to this file (name, size, date, type, etc).
- NVDA+delete (report review cursor location) should read the file name and location in the list (10 of 123)

Other information:
You can also find out this information by using the right and left arrows, though I do also think the behaviour of NVDA+tab and NVDA+delete can be improved here.

My system information:
NVDA 2021.3.3 
Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1526

**Comment by Qchristensen** [comment]
Sorry I had explorer set to show "details" view which presents that information (size, date, etc) in a grid and you can use the left and right arrow to move around it.  Press control+alt+6 to change the view to details.

If you are using a view which only lists the file names (icons, tiles or list) then, you are right, this information appears as a tooltip.

In that case, I'm actually even more inclined to suggest adding this information to NVDA+tab because it would then consistently report that information to the user with that command.  A sighted user can either see the same information on screen (if using details) or by hovering over the file with the mouse to view the tooltip, so it is avialable there either always or via a "gesture", and adding this information to NVDA+tab would give the same functionality to an NVDA user.

It would also allow the user to reliably get that information without needing to worry about what view explorer is set to, and given how many different views explorer has and how hard it is to try to set one consistent view across the board, I don't think it is reasonable to expect a user to know what the current view is for any given folder.

**Comment by XLTechie** [comment]
@Qchristensen Even in detailed view, the tooltip presents different information.

If on a folder, it will tell you some of the folder's contents. You can't get 
that with left/right arrow. Not sure if it's on the screen, but if so we can't 
get at it with left/right.

If on an MP3 file, the tooltip will get you artist and other ID3 tags, and the 
file size in MB. Left/right won't get you the ID3 information, and gives the 
size in annoying KB.

**Comment by Qchristensen** [comment]
So it does, I must admit I don't usually read the tooltips (clearly).

Windows does display some folders differently, eg music or photo folders.  Details view on these folders CAN be set to show information such as artist, length or ID tags, although (on my system at least), this information isn't shown by default.

(Note for those playing at home wondering how to do all this:
- To show different columns: TAB to the folder list headings - one tab past the folder list itself, it will read something like: "name split button collapsed sorted ascending".  Open the context menu and you can select the columns which are shown.
- To change how Windows treats a folder, select a folder in either the tree view or list view, press alt+enter to open the properties, control+tab to "Customize" pane.  The first option on this screen is "Optimise this folder for", documents is the default but there are a couple of other options suitable for folders of different type files.)
-

**Comment by levilibegas** [comment]
Hi. Thanks for all these enlightening comments. If data of a file are tooltips, can them be red if I am using any review or if I navigate by objects? I tried and I cannot figure how to read them, appart from moving arrows up and down. It would be great to add this information to the shortcuts you mentioned... Another thing, I wish I could fill out the template but I cannot find my way, I am using windows 7 and last version of firefox. Thanks

**Comment by levilibegas** [comment]
Sorry I made a mistake and closed it unwillingly

**Comment by feerrenrut** [comment]
So just to summarize:

- The extra information being read is due to the tooltip (reporting tooltip information may not be enabled in NVDA settings). The tooltip is shown in Windows when the selected item changes (after pressing down arrow).
- The tooltip information seems to be dependent on the file type and the metadata contained in the file.
- Crucially, the information in the tooltip does not necessarily match the configured columns in the windows explorer details view. Note that the columns in Windows Explorer are customizable.

Recommended way for users to interact:
Use the right arrow to read the column values for each file. I.E. press down arrow to select the next file, the file name is reported, then press right arrow to report the first column information.

Note, pressing down arrow again stays in the same column, to get back to the start the user needs to press left arrow until the file name is reported.

I'd like to close this issue, but I'm happy for a new feature request to be created based on @Qchristensen's comment:

>In that case, I'm actually even more inclined to suggest adding this information to NVDA+tab because it would then consistently report that information to the user with that command. A sighted user can either see the same information on screen (if using details) or by hovering over the file with the mouse to view the tooltip, so it is available there either always or via a "gesture", and adding this information to NVDA+tab would give the same functionality to an NVDA user.
