### ISSUE TITLE
Create an add-on manifest key to specify whether an add-on should be available on secure screens

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#13429]
### Is your feature request related to a problem? Please describe.

Currently, when configurations are copied to secure screens, add-ons are copied along with them.
However there are some add-ons, where this is pointless. These include speech drivers (the Vocalizer add-on was presented as an example) which rely on external software or libraries which can never be available in the administrative copy of NVDA.
They may also include add-ons such as Add-on Updater, which is likely not appropriate to have running on the administrative copy.

Some such add-ons will self-disable, rather than allow themselves to be run in the administrative copy, but as has been indicated in the thread linked below, some of the methods currently in use for that, do not succeed in fully disabling the add-on.

It would be better for such add-ons not to be copied in the first place.

Even when some version of #6305 is implemented, it will be useful to have such add-ons, the authors of which know that they can not or absolutely should not be available on administrative copies of NVDA, fail to be offered to the user for copying.

### Describe the solution you'd like

A new boolean add-on manifest key should be created.

* I propose that it be called "`addon_useWithAdminCopy`". Alternatives include "`addon_availableToAdminCopy`", "`addon_mayRunWhenSecure`", "`addon_canRunAsAdmin`", and "`addon_worksInAdminCopy`".
* Initially, this should be an optional key, to allow add-ons time to start including it.
* This key should default to True, if not included in the manifest.
* The recommendation to add-on authors should be that they set this to True, unless they know that their add-on either can not work in the administrative copy, or if they know that there is never a set of circumstances where a normal user would want or expect the add-on to work there (again, I am thinking of Add-on Updater as an example).
* When a mechanism is developed that allows the user to choose which add-ons are copied to the admin copy of NVDA, add-ons with this manifest key set False will not be listed.

### Describe alternatives you've considered

We could, of course, not do this.

### Additional context

This issue is pursuant to a recent [discussion](https://nvda-addons.groups.io/g/nvda-addons/topic/89522879) on [nvda-addons list](https://groups.io/g/nvda-addons), and an old [suggestion](https://github.com/nvaccess/nvda/issues/6305#issuecomment-526814496) by @JulienCochuyt  on #6305.

**Comment by CyrilleB79** [comment]
Thanks Luke for having opened this issue.

> A new boolean add-on manifest key should be created.

I agree with it.

>     * I propose that it be called "`addon_useWithAdminCopy`". Alternatives include "`addon_availableToAdminCopy`", "`addon_mayRunWhenSecure`", "`addon_canRunAsAdmin`", and "`addon_worksInAdminCopy`".

I would instead suggest the following ones:
* canRunOnSecureScreen
* availableOnSecureScreen

I would not mention admin since technically you may run NVDA as an administrator from a user section, even if not recommended.
I would also not use the "word secure" without "screen" since NVDA can be run with the "--secure" command line parameter in other situations (cf. https://github.com/nvaccess/nvda/issues/6305#issuecomment-581215877)
I would not replace "secureScreen" with "logonScreen" since these secure screens comprise logon screen but also lock screen and UAC screen.

>     * Initially, this should be an optional key, to allow add-ons time to start including it.

Yes, I agree.
Provided there is a default value, it can even remain optional forever. But the add-on template should add it with the default value.
Anyway, that's not the point for today, it may be discussed later, even much after this manifest key is implemented.

>     * This key should default to True, if not included in the manifest.

No, I partly disagree.
Ideally this key should default to False to guarantee that add-ons running on secure screens are only the ones for which the author has explicitly certified that his add-on work on secure screens by setting it to true.
However since it would be an API-breaking change, I would recommend that:
* The key value in the add-on template be set to False immediately to force authors of new add-on to certify it for secure screen only if needed
* A missing value be considered True during a certain period of time to avoid breaking compatibility with existing add-ons
* A missing value be considered False when an API-breaking release occurs (e.g. 2023.1) to force author of existing add-ons to certify the compatibility with secure screens.

>     * The recommendation to add-on authors should be that they set this to True, unless they know that their add-on either can not work in the administrative copy, or if they know that there is never a set of circumstances where a normal user would want or expect the add-on to work there

As explained above, I totally disagree with this approach and would recommend the opposite, that is:
The recommendation to add-on authors should be that they set this to False unless they know that their add-on can work on secure screens and if they know that there is a set of circumstances where a normal user would want or expect the add-on to work there
I recommend this way to do rather than the opposite because we can see in various add-ons that the use case of secure screen has not been considered by add-on authors (I have informed some of them for which it can be a security issue). My recommendation provides:
* an easy way to disable add-on on secure screens
* a way to force add-on author to consider the secure screen use case
Your recommendation instead only provides the first point, i.e. easy way to disable the add-on on secure screen.

> (again, I am thinking of Add-on Updater as an example).

I do not understand. Do you mean add-on updater can or should run on secure screens? For now it is not the case and I think that it should remain like this.

>     * When a mechanism is developed that allows the user to choose which add-ons are copied to the admin copy of NVDA, add-ons with this manifest key set False will not be listed.

I agree.

One thing to note: the current issue and #6305 want to resolve the same problem, i.e. add-on management on secure screens. But they propose two distinct and not mutually exclusive solutions. Thus they can both be implemented separately.

**Comment by Brian1Gaff** [comment]
Actually, surely one could easily over ride a manifest just like we did on 
the change to different versions of nvda/python, by directly editing the 
text of the manifest using a different copy of nvda, then copying the new 
one to the old one.
 I'm not suggesting that people will do it, but merely pointing out that the 
user is able to circumvent it easily.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment]
Brian, it is already self-evident in open source software, that users with 
certain knowledge can bypass any safety mechanism the developers put in place. 
That is the nature of open source, and I hardly think that means we should not 
bother including protective measures.

Such things as this are not targeted to protect hackers from themselves. They 
are intended to protect the average user from defects that we are able to 
prevent.
Defects the user introduces on his own, by hacking the manifest or any of the 
add-on's code, or NVDA's code, are expressly not NVDA's responsibility.

You are free to break any protections that are put in place. You assume the risk 
of the results, and that is the nature of open source. But we must start with 
sane protections, and assume that the vast majority of users won't try to bypass 
them.

**Comment by cary-rowen** [comment]
Hi,
Is it okay to let the user freely choose which plugins appear on the security screen? Some plugins are not absolutely unsuitable for the security screen, and whether these plugins appear on the security screen may not be up to the add-on developer to decide, but ultimately users to decide.
Thanks

**Comment by CyrilleB79** [comment]
@cary-rowen you write:
> Hi, Is it okay to let the user freely choose which plugins appear on the security screen? Some plugins are not absolutely unsuitable for the security screen, and whether these plugins appear on the security screen may not be up to the add-on developer to decide, but ultimately users to decide. Thanks

Did you read this in my previous comment:
> One thing to note: the current issue and #6305 want to resolve the same problem, i.e. add-on management on secure screens. But they propose two distinct and not mutually exclusive solutions. Thus they can both be implemented separately.

I need to clarify things on how I view the things:
1. For an add-on to be available for secure screens, the add-on author should certify that his add-on is useful on such screen and that it meets security requirements, e.g. does not allow to open a Windows n Explorer. We can not expect from any user to determine if an add-on meets security criteria. The implementation of such a check is the object of the current issue (#13429).
2. In any case, the user should be able to choose the add-on he want on secure screens. That's the object of #6305.

As explained before, the current issue and #6305 can be implemented in either order and, even if they apply to the same problem, one does not depend on the other.

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 

oh, have to say sorry, I overlooked your previous statement, so I totally agree with it now.

Thanks again!

**Comment by feerrenrut** [comment]
We aren't comfortable with this approach. This relies on trust in the add-on. Rather than protecting/empowering users. We are actively looking into this area: See #13686

I'm going to close this issue.
