### ISSUE TITLE
Strange behavior regarding font color reporting by NVDA

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13458]
### Steps to reproduce:
1. enable font color reporting in document setting of nvda
2. open a word file and create a table, and filled it with some text
3. move between table cells using left or right arrow, even though the color of the fonts has no change, NVDA will still report the color

### Actual behavior:
after moving from one cell to another cell, Nvda will report the font color as well as background color, even the font color and the backgorund color between the texts of the two cells are the same

### Expected behavior:
NVDA will not anounce such info if the colors are the same

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
nvda 2021.3.3
#### Windows version:
Windows home ed, 21H1

#### Name and version of other software in use when reproducing the issue:
Microsoft Office 365 installed version

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No 
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tried
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

**Comment by Qchristensen** [comment]
A couple of notes fom my testing of this:

1) This happens in Word with UIA enabled, but not with that setting (in NVDA's advanced settings) disabled.

2) This only happens when you navigate with arrows / control+arrows etc, but not when using the table navigation commands (control+alt+arrows) or tab.

3) It also happens when reading with NVDA+down arrow / NVDA+a, although interestingly not on every cell, but on the second cell in each row I think?

4) Nothing odd in the log.

My system:
- NVDA 2021.3.3
- Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1586
- Office 365 (64-bit) Version: 16.0.14931.20118

**Comment by LittleStar-VIP** [comment]
Another place which this issue will occur.
1. enable reporting of font color in nvda
2. open any word file, either blank or with some text
3. press ctrl and end, 
4. press up arrow, nvda will report the color

**Comment by Qchristensen** [comment]
Re moving to the end of a document and up one line - I can replicate only when the last line of the document is blank.  IE, if there is text on the last line and no new line afterwards, it does not report the colour if it hasn't changed.

**Comment by LittleStar-VIP** [comment]
Sorry, I have reframed the issue into a bigger picture and is posted as a new issue #13459
As you have already commented here, so I have not edited this issue, and so I posted a new one.
I am not sure how to handel merging or deleting one of this issue, may you please take necessary action if needed, thanks.

**Comment by CyrilleB79** [comment]
Please change milestone to 2022.1 instead of 2022.2.
