### ISSUE TITLE
Mathml plus (+) operator prununciation with italian language

### ISSUE THREAD

**Issue by sharkboyto** [nvaccess/nvda#13474]
### Steps to reproduce:
- for example, download the attached txt file;
- rename the file in xhtml format ;
- open the xhtml file with Google Chrome, Edge or Firefox;
- in NVDA, change the verbosity of punctuation to "all";
- listen to the italian tts .
### Actual behavior:
- NVDA Speech: 
   ````
   Speaking [
   BreakCommand(time=53), '5 ', BreakCommand(time=31), 'x ', BreakCommand(time=79), "piu' ",
   BreakCommand(time=79), '2 ', BreakCommand(time=31), 'ipsilon ', BreakCommand(time=79), 'meno ',
   BreakCommand(time=530), '3 ', BreakCommand(time=493), 'per ', BreakCommand(time=493), 'inizio frazione ', 
   BreakCommand(time=42), BreakCommand(time=223), 'x ', BreakCommand(time=31), 'meno ', BreakCommand(time=79), '2 ', 
   BreakCommand(time=31), 'ipsilon ', BreakCommand(time=79), "piu' ", BreakCommand(time=31), '4 ', 
   BreakCommand(time=106), 'fratto ', BreakCommand(time=53), BreakCommand(time=159), '5 ', BreakCommand(time=31), 'x ', 
   BreakCommand(time=79), "piu' ", BreakCommand(time=31), '3 ', BreakCommand(time=42), 'fine frazione ', 
   BreakCommand(time=530), "piu' ", BreakCommand(time=31), 'z ']
   ```
- you will notice that after the plus (+) symbol, the synthesis will pronounce apostrophe;
- this happens after each plus (+) symbol, in mathml expression;
- i have selected several tts engines;
- I have tried many mathematical expressions containing the plus  (+) symbol;
- if punctuation verbosity is set to "none", "some" or "a lot", the reading of the formula is correct.
### Expected behavior:
- in mathml expression, the apostrophe must not be read after the plus (+) symbol.

I think the problem is that the word "più" in Italian is write with the accented ù. Reading the NVDA summary log it says "piu'". With the apostrophe character. I think it's a mistake that needs to be corrected.

### System configuration
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.3.1
#### Windows version:
Versione	10.0.19044 Build 19044
#### Name and version of other software in use when reproducing the issue:
MathPlayer 4.0
#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes: 2019.3 , 2020.1 and 2021.1
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
 yes

[nvda-mathml-plus-bug.txt](https://github.com/nvaccess/nvda/files/8245899/nvda-mathml-plus-bug.txt)

**Comment by CyrilleB79** [comment]
@sharkboyto I make the hypothesis that this issue comes from MathPlayer rather than from NVDA.

Would you have the opportunity to test with Jaws to see if the issue also occurs. Or with Narrator in case it supports MathML and symbol verbosity levels, but I am not so sure.

I make this hypothesis since reading normal text (i.e. not part of MathML) containing the plus symbol with NVDA does not cause the issue. Moreover, NVDA's symbol processing takes place after the speech is logged whereas in the log you have provided, the plus symbol is already translated as the word "piu' ", probably directly by MathPlayer.

Also just to confirm with you: if you read the following line with symbol level set on "all", do you confirm that you expect to have the apostrophe pronounced?
Il Po è piu' lungo del Tevere.

In Italian, you could write "più" (with accent) rather than "piu'" (with apostrophe). If you confirm all the points above, you could then report the issue to MathPlayer and ask to send "più" with accent rather than "piu'" when the "+" (plus) symbol is encountered.

And a last question to understand the issue:
Why do you set symbol level on "all" to read math expressions? I would expect that MathPlayer already translates the symbol in text to be read by the screen reader; thus I would have imagined that it is not necessary to increase NVDA's symbol level. Maybe I have missed something however.

**Comment by sharkboyto** [comment]
I set verbosity on "all", because not using braille bar and I rely completely on the output of speech synthesis. 
It is a personal choice.
thanks for the suggestion, I'll try to contact the MathPlayer developers

**Comment by feerrenrut** [comment]
Thank @CyrilleB79, your analysis seems reasonable. We'll leave it to @sharkboyto to contact the mathplayer developers.

**Comment by Adriani90** [comment]
@sharkboyto are you still having this issue in NVDA 2023.1?

**Comment by CyrilleB79** [comment]
@sharkboyto: And have you have an answer from MathPlayer regarding this issue?

**Comment by Adriani90** [comment]
We didn't get any update from the initial author since more than 2 years upon request, closing as abandoned. if you are still having this issue, please comment and we can reopen.

**Comment by CyrilleB79** [comment]
Also, MathPlayer is being discontinued. Another math reading provider should be used: MathCAT or Access8Math.
