### ISSUE TITLE
Exclude unnecessary modules from py2exe bundle

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1351]
**Reported by jteh on 2011-02-03 00:31**
It seems there are quite a few unnecessary modules in our py2exe bundle (library.zip); e.g. distutils, email, unittest, BaseHTTPServer, etc. It's possible that some of these modules are unconditionally imported, in which case there is nothing we can do. However, py2exe does include modules that are conditionally imported, so it's possible that quite a few of them aren't actually ever used. We should figure out which ones aren't used and exclude them so they don't waste space.

**Comment by leonardder** [comment]
@JCSTeh: seems that this is still a valid issue, but it probably doesn't have much priority due to the abandoned state of this.

Since we are talking about library.zip here, I wonder, is it possible for people to inject malicious modules in this file? Or is there some hidden place where Py2exe checks for md5sums or the like on library.zip?

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [15 Jul 2017, 19:30 GMT+12](https://github.com/nvaccess/nvda/issues/1351#issuecomment-315516598 "2017-07-15T07:30:26Z - Replied by Github Reply Comments"):
> @JCSTeh: seems that this is still a valid issue, but it probably doesn't have much priority due to the abandoned state of this.

Agreed. If anything, people want more modules rather than less and the space gain from doing this is probably minimal, so not much point in investing resources into it.

> Since we are talking about library.zip here, I wonder, is it possible for people to inject malicious modules in this file? Or is there some hidden place where Py2exe checks for md5sums or the like on library.zip?

I don't think there is. Ideally, there should be. This should be filed as a separate issue.

Closing.
