### ISSUE TITLE
Notepad++ 64 bit crashes with NVDA 2022.1 Beta 3 and earlier versions

### ISSUE THREAD

**Issue by GeorgeKerscher** [nvaccess/nvda#13628]
### Steps to reproduce:

Install Notepad++ 64 bit latest version.
Select a text file and open with Notepad++
Type in anything or move focus.
Notepadd++ crashes.
This occurs with NVDA 2022.1 Beta 3 and earlier versions of NVDA.

### Actual behavior:
Notepadd++ eexits.

### Expected behavior:
Notepadd++ should operate properly.
#### NVDA installed/portable/running from source:
NVDA 2021.3.5 and also installed NVDA 2022.1 Beta 3.
#### NVDA version:
It occurs with NVDA 2022.1 Beta 3. I heard that this version of NVDA resolved this problem, and I want to report that it is not fixed.
#### Windows version:
Windows 2011
#### Name and version of other software in use when reproducing the issue:
Nothing

#### Other information about your system:
I have a 64 bit Lenovo. two years old.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This started with the latest Notepadd++, because the 64 bit version supports files larger than 4 gig. The 32 bit version of Notepad++ is the probable workaround.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

I did not run the com fixing tool.

**Comment by lukaszgo1** [comment]
Please specify the exact version of Notepad++ you're using. For me NPP 8.3 X64 does not crash with the same version of NVDA. Also make sure you've disabled all add-ons.

**Comment by GeorgeKerscher** [comment]
Hi,

 

I am using  Notepad++ 64 bit 8.3.3

 

I installed the NVDA 2022.1 beta three. I did have addins running. I have now uninstalled 2022.1 Beta 3 and went back to 2021.3.5 and reconfigured my system to how it was.

 

I was thinking that going to Notepad++ 32 bit was a much easier path. I don’t edit huge files anyway.

 

Best

George

**Comment by LittleStar-VIP** [comment]
I am using nvda 2022.1 beta 3 and notepad ++ 8.2.1 64 bit, I have not experienced crashing of the notepad++

**Comment by GeorgeKerscher** [comment]
It happened to me when I upgraded to 8.3.3, which has the ability to edit files larger than 4 gig. On install, there is a warning about some plugins.

 

Best

George

**Comment by lukaszgo1** [comment]
@GeorgeKerscher When I asked about disabling add-ons I mend NVDA  add-ons i.e. by restarting with an appropriate option from the exit. dialog. Would you be able to verify that Npp 8.3 crashes only when NVDA is running - it is possible that these crashes are caused by a NPP plugin rather than being caused by NVDA?

**Comment by GeorgeKerscher** [comment]
Hi,

I have uninstalled Notepad++ 64 bit and went to Notepad++32 bit. I have no problems with this version. Also, I have reverted to NVDA 2021.3.5.

Sorry I cannot help.
Good luck.

**Comment by alexarnaud** [comment]
Hello @GeorgeKerscher,

Thanks a lot for reporting this issue to the NVDA project.

We've requested more details to help us understand where the problem comes from and how to solve it. Reverting is a temporary solution but without your help, we wouldn't be able to solve the problem and the time you gain now, you'll loose it later when you're problem will come up again.

Also, if no one reproduce the issue and without help from you, we'll have to close this issue because an issue we can't reproduce, we can't solve it. The only way to be able to work on an issue we can't reproduce is by having the help of the person reporting it.

Thanks in advance.

**Comment by GeorgeKerscher** [comment]
Hi,

I am sorry, but to go back to the old configuration, It would cost me about eight hours.

For somebody who does not use Notepad++ it would be simple to try and reproduce. Do the following:

Install Notepad++ 64 bit version, 8.3.3 or later.

Open notepad++ with NVDA and type something in. If Notepad++ does not crash immediately, It would have to be something with theNVDA addins or Notepad++ plug ins. I had dspellcheck, nencrypt, and xmltools in my plugin list.

**Comment by mazen428** [comment]
It's probably something either in your Notepad++ plugins or NVDA addons, Notepad ++ 8.3.3 64 bit doesn't crash for me in 2022.1 beta, but it does crash in 2021.3 and older which is expected.

**Comment by CyrilleB79** [comment]
As for now, the reporter of this issue is the only one to experiment this issue. He does not intend to provide the result for requested tests, i.e. run NVDA with disabled add-on and Notepad++ with no plugin. To latest news, he has found a satisfying solution downgrading NVDA and using Notpad++ 32-bits; probably only one of these two action would have been enough actually.

Since other persons have not reported this issue, it's very likely that the issue comes from Notepad++ plugins or (a bit less likely) from NVDA add-ons.

I suggest to close this issue and to re-open if @GeorgeKerscher can provide additional results or if someone else reports the same issue.

@seanbudd if you agree, can you close it?

**Comment by GeorgeKerscher** [comment]
I downgraded to the 32 bit version and have no problems. Because I do not plan to upgrade to the 64 bit and test, I'll close this.
