### ISSUE TITLE
Incorrectly reporting of 'editing configuration xxx' when navigating in nvda setting window

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13629]
### Steps to reproduce:
1. On top of current configuration profile, create at least another profile, say I here created a second profile called 'code editing'
2. set the second profile to be automatically triggered in windows explorer 
3. make file explorer as the current focused window
4. press nvda+n > preferences > setting and press enter
5. press down arrow, nvda say 'editing configuration code editing speech 2 of 13'
6. press up arrow nvda says 'editing configuration default general 1 of 13'
7. If I change the current focused window to a different application, like google chrome, I will not hear those words 'editing configuration xxx' when navigating in the setting window

### Expected behavior:
nvda should not say 'editing configuration xxxx' when navigating in the nvda setting window
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2022.1 beta 3
#### Windows version:
win 10 home ed 21h2
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This problem seems to be existed in nvda 2021.3.5
#### If NVDA add-ons are disabled, is your problem still occurring?
this is a clean version without any addon
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried

**Comment by XLTechie** [comment]
It seems that what you describe is what is supposed to happen. Either you are 
reporting expected behavior, or I am misunderstanding what you think is wrong.

When you activate a profile, and then go to change NVDA settings for that 
profile, NVDA will announce that you are editing that profile by listing it in 
the title of settings panels.

For some panels, like general, there are no profile-specific settings, so it 
tells you that it is editing the default profile.

Can you explain further what is wrong with the behavior you are describing?

Is there some other way you would like NVDA to indicate to you that the settings 
you are changing are only effective for a particular profile?

**Comment by LittleStar-VIP** [comment]
Oh, it is an expected behavior?
Then I must have missunderstood.
Originally I wonder why moving the focus in the setting will have such an announcement.
But as what you said, the general setting is applied to all configuration, and that is why it is saying editing configuration default.
Thanks.

**Comment by XLTechie** [comment]
Yes.  I think your misunderstanding might be on how profiles work.

You can change settings in a profile by pressing keys like NVDA+P to change 
punctuation, or NVDA+M to turn mouse tracking on or off.

But all those do is change settings in the settings panels, without having to go 
there.
So you can also change settings in the panels themselves, and for that to work, 
it has to tell you whether the settings you are changing can be saved in the 
profile.
