### ISSUE TITLE
Automatic language switching fails with eSpeak

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#13727]
### Steps to reproduce:
1. Go to http://forum.audiogames.net
2. Switch to a different language other than English, make sure automatic language dialect switching is on
3. Read through the page.
### Actual behavior:
NVDA does not switch languages
### Expected behavior:
NVDA must switch languages automatically, as it used to do in the version before 2022.1.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1
#### Windows version:
Windows10 21h2
#### Name and version of other software in use when reproducing the issue:
NVDA, Google Chrome
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the version before 2022.1, I forgot.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
@burakyuksek your initial description is lacking of details. So maybe what I have reported is not the same issue. If this is the case, sorry for hijacking your issue. Just let me know and I will open a new dedicated issue.

To clarify your issue, could you precise the following points:
>     2. Switch to a different language other than English, make sure automatic language dialect switching is on
* Which synthesizer and language are you using?
* Which option do you enable in speech settings? Only "Automatic language switching", only "Automatic dialect switching" or both?

> NVDA does not switch languages
And what does it do? Read nothing instead of what should be read? Or read with wrong voice/language the website's content?

**Comment by ChrisDuffley** [comment]
Hey all,

It's important to note that not all synthesizers will support the switching of languages/dialects. For example, a synth I use on a daily basis is RHVoice (they're compatible with 2022.1 by the way). Language and dialect switching, at least to my knowledge, does not work correctly at all, even with both those options checked. The synth you'll want to try out for automatic language/dialect detection is eSpeak because it can natively switch languages.

Also, this page is a bad example of reproducing automatic language/dialect detection because of the HTML code I just saw when viewing the page source; It has no markup to say what language the homepage was in, so the synth couldn't switch to it either way.

I'd suggest using a site that you know can change languages (for example, a site in a language outside of English, perhaps), or, alternatively, probably using Google Translate as that also switches language tags for the translated text.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 23, 2022, at 16:24, Cyrille Bougot ***@***.***> wrote:


@burakyuksek <https://github.com/burakyuksek> your initial description is lacking of details. So maybe what I have reported is not the same issue. If this is the case, sorry for hijacking your issue. Just let me know and I will open a new dedicated issue.

To clarify your issue, could you precise the following points:

2. Switch to a different language other than English, make sure automatic language dialect switching is on
Which synthesizer and language are you using?
Which option do you enable in speech settings? Only "Automatic language switching", only "Automatic dialect switching" or both?
NVDA does not switch languages
And what does it do? Read nothing instead of what should be read? Or read with wrong voice/language the website's content?

**Comment by ChrisDuffley** [comment]
Following up...

After trying the Google Translate site, automatic language detection does appear to work correctly in NVDA (at least with ESpeak). If anyone else cannot reproduce this, I'd be happy to see this issue closed.

Thank you!

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 23, 2022, at 19:00, Christopher Duffley ***@***.***> wrote:


Hey all,

It's important to note that not all synthesizers will support the switching of languages/dialects. For example, a synth I use on a daily basis is RHVoice (they're compatible with 2022.1 by the way). Language and dialect switching, at least to my knowledge, does not work correctly at all, even with both those options checked. The synth you'll want to try out for automatic language/dialect detection is eSpeak because it can natively switch languages.

Also, this page is a bad example of reproducing automatic language/dialect detection because of the HTML code I just saw when viewing the page source; It has no markup to say what language the homepage was in, so the synth couldn't switch to it either way.

I'd suggest using a site that you know can change languages (for example, a site in a language outside of English, perhaps), or, alternatively, probably using Google Translate as that also switches language tags for the translated text.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 23, 2022, at 16:24, Cyrille Bougot ***@***.***> wrote:


@burakyuksek <https://github.com/burakyuksek> your initial description is lacking of details. So maybe what I have reported is not the same issue. If this is the case, sorry for hijacking your issue. Just let me know and I will open a new dedicated issue.

To clarify your issue, could you precise the following points:

2. Switch to a different language other than English, make sure automatic language dialect switching is on
Which synthesizer and language are you using?
Which option do you enable in speech settings? Only "Automatic language switching", only "Automatic dialect switching" or both?
NVDA does not switch languages
And what does it do? Read nothing instead of what should be read? Or read with wrong voice/language the website's content?

**Comment by seanbudd** [comment]
@CyrilleB79 - would you be able to open a new issue if this is separate from @burakyuksek's issue.

@burakyuksek - can you confirm what synthesizer you are using?
Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

**Comment by burakyuksek** [comment]
I am using espeak, the primary language I use is Turkish. I toggle both automatic language and dialect switching on. When I enter the site I mentioned, in previous versions, NVDA would automatically switch to English, but now it does not. The log is attached.
[nvda.log](https://github.com/nvaccess/nvda/files/8761809/nvda.log)

**Comment by seanbudd** [comment]
This was broken in espeak by this commit https://github.com/espeak-ng/espeak-ng/commit/e91d0a58612a01954687d34c7417cf0fbd3cadaa.

An issue should be written on [the espeak repository](https://github.com/espeak-ng/espeak-ng/issues/new).

**Comment by burakyuksek** [comment]
I have written an issue.
https://github.com/espeak-ng/espeak-ng/issues/1200

**Comment by seanbudd** [comment]
@burakyuksek - could you please test this PR and confirm the behaviour is fixed: https://ci.appveyor.com/api/buildjobs/nc5srl7o445sk222/artifacts/output%2Fnvda_snapshot_pr13739-25486%2C9f1b92d9.exe

**Comment by burakyuksek** [comment]
@seanbudd the pull request you sent works correctly.
