### ISSUE TITLE
NVDA portable crashes

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#13786]
This issue is a regression in 2022.2 dev cycle. Thus it should be addressed in the same cycle. And probably before the first beta is out since many persons test the beta release as portable versions.
Cc @feerrenrut , @seanbudd 

Issue raised according to https://github.com/nvaccess/nvda/pull/13779#issuecomment-1151549715.

### Steps to reproduce:
* From the installer, create a portable copy of NVDA
* Start the newly created portable copy of NVDA.

### Actual behavior:
NVDA does not start successfully.
[nvda-old.log](https://github.com/nvaccess/nvda/files/8877060/nvda-old.log)

### Expected behavior:
NVDA starts successfully.

#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
Last alpha (nvda_snapshot_alpha-25538,f3445949.exe)
#### Windows version:
Windows 10 20H2 (x64) build 19042.1706

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.1 portable is OK.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes. Tests run without add-ons.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, but probably not related.

**Comment by feerrenrut** [comment]
Thanks for raising an issue @CyrilleB79.

The error snippet is:
```
CRITICAL - __main__ (21:31:20.470) - MainThread (12520):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 390, in <module>
  File "core.pyc", line 469, in main
  File "NVDAHelper.pyc", line 519, in initialize
  File "ctypes\__init__.pyc", line 442, in LoadLibrary
  File "ctypes\__init__.pyc", line 364, in __init__
OSError: [WinError 126] Le module spécifié est introuvable
```

This error is `Cannot find the specified module.`

Can you attach a file listing for the NVDA portable copy, the following will output to a `results.txt` file, run in `cmd.exe` `dir /b /s /a:-D > results.txt`

We'll need to investigate why this doesn't work on your system, the portable copies seem to work fine on our machines. This answer has some suggestions on how to debug the problem: https://stackoverflow.com/a/14362289

**Comment by feerrenrut** [comment]
I should add that it is trying to load `nvdaHelperLocal.dll` (see code: `localLib=cdll.LoadLibrary(os.path.join(versionedLibPath,'nvdaHelperLocal.dll'))`

This should have a path (within the portable copy): `lib\alpha-25546,4eb30c91\nvdaHelperLocal.dll`

**Comment by lukaszgo1** [comment]
Is this reproducible on more than one machine - From the fact that the Windows version in log posted here, and in #13779 are different it looks like it is?
I have the same build of Windows installed on one of my machines as the one in the log from #13779 and I cannot reproduce the problem there.
It is just a hunch, but could you try with the following Alpha builds:
- [The last Alpha version before AppVeyor upgraded Visual Studio to the latest build](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-25478,841925b7.exe)
- [The first version compiled with the latest VS 2019](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-25500,12e17fc1.exe)


While this won't explain why the behavior between portable and running from the launcher is different if my suspicion turns out to be true we would at least have a way forward for 2022.2 by reverting to the previous worker image on AppVeyor.

**Comment by CyrilleB79** [comment]
Yes the issues appears on both my systems (work and home).

But actually, I have found that Update Channel selector add-on is responsible for this issue (cf. https://github.com/nvda-es/updateChannel/issues/5)

I had run the portable copy without add-on (since it was just created), but the launcher automatically uses my personal profile where the Update Channel Selector add-on was present. Sorry for this imprecision.

Since NVDA is not in cause, I am closing this issue.
