### ISSUE TITLE
NVDA skips elements with zero width or height

### ISSUE THREAD

**Issue by patrickhlauke** [nvaccess/nvda#13897]
### Steps to reproduce:

* open https://getbootstrap.com/docs/5.2/components/progress/#how-it-works
* read through the content of that section - it includes examples of (ARIA-fied) progress bars
* the first example is a progress bar with a value of `0`. the actual element itself uses CSS styling to show the progress bar, and in that case has a width of `0` as well

### Actual behavior:

The zero-value progress bar is completely omitted from NVDA's output, despite being exposed correctly by the browser's accessibility tree. Presumably, this is an NVDA-specific heuristic?

Video recording of the current behaviour - note how the first progress bar is completely skipped

https://user-images.githubusercontent.com/895831/178756768-4dc6db85-b3b5-438f-96fe-1b3bf1c448a3.mp4

Happens in Chrome and Firefox.

JAWS correctly announces the zero-value (and visually zero-width) progress bar.

![Screenshot from Chrome's Developer Tools, showing that the ARIA-fied progress bar is correctly exposed in the accessibility tree](https://user-images.githubusercontent.com/895831/178758105-41389a31-39d5-42a0-9325-5f49bbfe6fc6.png)

### Expected behavior:

I'd expect the CSS width not to influence whether or not the content is announced - not going by heuristics, but just by what is exposed explicitly in the accessibility tree.

#### NVDA installed/portable/running from source:

NVDA installed

#### NVDA version:

2022.1

#### Windows version:

Windows 10.0.19044 Build 19044

#### Name and version of other software in use when reproducing the issue:

Chrome 103.0.5060.114
Firefox 102.0.1 (64-bit)

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by patrickhlauke** [comment]
Note that currently, those example progress bars based on ARIA lack an accessible name. However, even after adding an accName (see https://github.com/twbs/bootstrap/pull/36732) NVDA still omits the zero-width element from its output.

**Comment by feerrenrut** [comment]
In short, this is intentional.
See the aria-hidden spec: https://w3c.github.io/aria/#aria-hidden

Exposing non-visible elements to screen reader users would result in a noisy and difficult user experience.
Historically, it has been common to visually hide elements that aren't there for user consumption.

There is more discussion on https://github.com/nvaccess/nvda/issues/12501

You can use [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) to provide an alternative name/text for an element.
If it really is desirable to make some elements only available to screen reader users take a look at:
https://webaim.org/techniques/css/invisiblecontent/

**Comment by seanbudd** [comment]
Please read the linked specs, specifically:

>User agents determine an element's [hidden](https://w3c.github.io/aria/#dfn-hidden) status based on whether it is rendered, and the rendering is usually controlled by CSS.

from the aria-hidden spec: https://w3c.github.io/aria/#aria-hidden

**Comment by patrickhlauke** [comment]
"User agent" in this case being the browser, which in this case has determined that the element is indeed considered "rendered", since it's exposing it via the accessibility API. NVDA then runs extra heuristics on top of what the browser deems rendered.

**Comment by seanbudd** [comment]
Yes, this is an intentional behaviour for the reasons discussed earlier.

>Exposing non-visible elements to screen reader users would result in a noisy and difficult user experience.
Historically, it has been common to visually hide elements that aren't there for user consumption.

`aria-hidden` has historically been determined differently across browsers. It is up to the screen reader to provide a consistent user experience.

**Comment by patrickhlauke** [comment]
fine, if you can't see the problem of "browsers are inconsistent, so screen readers will apply their own inconsistent heuristics to patch that" and how that doesn't actually make things more consistent...

**Comment by feerrenrut** [comment]
@patrickhlauke in this discussion care should be taken when using the term "rendered", the meaning of this can easily be open to interpretation, there are different render targets. One target may be MSAA/IA2 (a simple version of this tree is shown in the dev tools), another render target is the visual picture displayed by the browser.

If something is not visible, it is not important to sighted users. If it is not important to sighted users, then why should it be important to screen reader users.

The example given is a progress bar with zero width. It couples the visual presentation with the semantic information. The progress bar should have separate elements for the visual presentation

**Comment by feerrenrut** [comment]
The problematic sample from Bootstrap is:
```HTML
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
</div>
```

Moving the semantics onto the always visible element resolves the issue:
```HTML
<div class="progress"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
  <div class="progress-bar"></div>
</div>
```

**Comment by feerrenrut** [comment]
I'm not sure that I agree that a zero width or height is merely a heuristic for visibility, it seems logically direct to me.

When considering whether this should be a browser or AT decision there's also the hugely variable nature of disabilities to consider. It can't be a one size fits all, to cater to this the decisions about final presentation does need to be left to the AT/users. The current reality is that a browser does not dictate how AT to should present information or even which information is important, it only attempts to make the information available.

I can sympathize with difficulty of testing many combinations, NVDA has to work not only with web tech (unfortunately the browser layer does not abstract many of the details required), but also several other APIs for applications and the OS itself.

Thanks for raising an issue and participating in the discussion.

**Comment by feerrenrut** [comment]
>I'm not sure that I agree that a zero width or height is merely a heuristic for visibility, it seems logically direct to me.

To prevent confusion for anyone reading this issue, I'm referring to the width and height of the object as it is exposed by the browser via the accessibility API (in this case IA2), rather than the CSS width and height, NVDA does not parse CSS or HTML.

**Comment by BlindGuyNW** [comment]
I tend to agree with @patrickhlauke here. NVDA should render the contents of the accessibility tree as presented. I just encountered this with an interactive component (radio buttons) which are hidden visually but ought to still be  visible with the screen reader. I feel like NVDA is overstepping because the author didn't explicitly hide the controls with aria-hidden, all they did was set CSS width to 0. The controls are still in the DOM and accessibility trees, but can't be interacted with by an NVDA user.

**Comment by Adriani90** [comment]
> but that's notorious for doing that sort of "we know best" approach).

> anyway, i'll leave it at that here, clearly not going to move the needle here on why the heuristics should be left up to browsers rather than ATs...

@patrickhlauke I totally understand your point here. However, browsers still expose things via the accessibility API in a very inconsistent way. In your case it might happen that it is exposed consistently and that ATs applied their heuristics because there was a time when this was not the case. But still, we don't have any committments from browser vendors that they all will apply the rendering standards as to comply with the best accessibility requirements.
In my view we still need a lot of independent heuristics in order to make as many different browsers accessible as possible but also not breaking user experience or making browsing through the interent very inefficient.
Can you please elaborate more on the advantages of an user having such elements being red out by the screen reader? We need some clear practical use cases.


@BlindGuyNW wrote:
> I just encountered this with a few interactive components (radio buttons and checkboxes), which are hidden visually but ought to still be visible with the screen reader. I feel like NVDA is overstepping because the author didn't explicitly hide the controls with aria-hidden, all they did was set CSS width to 0. The controls are still in the DOM and accessibility trees, but can't be interacted with by an NVDA user. A mouse user can click on the labels for the components, which are visible and work as expected.

If the control and the label are associated and only the control is hidden, then NVDA should see the label though. In browse mode when pressing enter, NVDA calls a mouse click event as far as I know. So pressing enter on the visible label should still work for an NVDA user as well. Can you please provide an example?

**Comment by BlindGuyNW** [comment]
@Adriani90 Please see [this codepen](https://codepen.io/blindguynw/pen/MWLXKvB). Niehter the radio buttons nor the label are exposed to nVDA. If you Tab into the frame and navigate with browse mode off it behaves a bit better but surely we want to expose things in browse mode to avoid confusion?

**Comment by ramoncorominas** [comment]
@BlindGuyNW  I cannot reproduce the issue, if I go to that Codepen I can tab to the options and they are read as "radio button" checked or unchecked, and I can use arrow keys to change the selected option as always. I'm using NVDA 2023.3, both with Firefox or Chrome the behavior is the same

**Comment by BlindGuyNW** [comment]
I would like to understand why our experiences, or perhaps expectations, are so different. When I navigate to the codepen preview frame, I hear "grouping select a maintenance drone." I would expect to then be able to down-arrow in browse mode to read the radio buttons for selection. Instead, when I hit downarrow I am simply taken to the end of the grouping with no radio buttons or labels of any kind.

**Comment by Adriani90** [comment]
Ok sorry it seems I can reproduce in Chrome as well.
According to this docs, it seems opacity:0 is explicitely not treated as invisible, so NVDA should definitely render this in browse mode as well.
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/accessibility/browser/offscreen.md

@jcsteh why is this working in Firefox but not in Chrome? Any idea? Focus mode works in both browsers as expected.

Regarding the progress bar without any CSS width or heighth atributes, I am still not convinced this should be exposed to NVDA. I guess there are a lot of people using such elements without width or heighth. Adding opacity:0 should make it visible I guess but still not consistent in every browser.

**Comment by BlindGuyNW** [comment]
I note that removing opacity: 0 has no impact on what is rendered with NVDA. The radio buttons still are not shown in browse mode. Removing width: 0; and keeping opacity: 0; on the other hand, puts them in as expected.

**Comment by ramoncorominas** [comment]
@BlindGuyNW  You are right, I did not test it properly on Google Chrome. It works as expected in focus mode but not in browse mode.

**Comment by seanbudd** [comment]
NV Access supports making this a setting.
When we fetch height/width information in our virtual buffers, we will pass that on as an attribute rather than immediately filtering.
We'd encourage making this a feature flag, where reporting these zero-size elements are enabled on default.

**Comment by jcsteh** [comment]
I'm not really sure how this can be filtered in the Python code. If such elements are included, that changes the text that is rendered in the buffer. There is currently no mechanism to ignore text rendered in the buffer. Fixing that would require fundamental changes to the way virtual buffer TextInfos work. As far as I understand, the only way this could be a setting is if we pass a flag to the virtual buffer when it is created, which raises two further problems:

1. There is no current mechanism for passing such configuration to the buffer.
2. Changing the setting wouldn't take effect until all buffers were destroyed and recreated.

**Comment by seanbudd** [comment]
@jcsteh Couldn't we do something similar to layout table suppression?

**Comment by jcsteh** [comment]
Layout table suppression doesn't suppress the rendering of any text. It just suppresses field metadata (table with n rows and n columns, row n column n, etc.). The problem here is that we would need to potentially suppress rendering of actual text, which changes the offsets in the buffer.

**Comment by jcsteh** [comment]
Example:
`data:text/html,before<div role="radio" aria-label="control"></div>after`
Note that this doesn't render any text into the buffer for the div, not even a space. If we now give that a width and height:
`data:text/html,before<div style="width: 10px; height: 10px;" role="radio" aria-label="control"></div>after`
Now it renders the text "control".

We could potentially change this so that 0 width/height controls render labels as metadata instead of text. But we'd still need to render at least a space in the buffer to make this work, and that space would cause blank lines for block elements even if we ignored the metadata when we choose to ignore the metadata.

**Comment by Simon818** [comment]
Could it be a feature flag that requires an NVDA restart to take effect?

I believe the impact of the current approach is much higher than we realize. This behaviour is not well-known even if someone does have the technical knowledge to inspect the code of a page. I've been an NVDA power user basically since day 1, and had no idea why some controls weren't rendering in browse mode, but I can think of countless examples over the years. If there is no easy way to toggle the feature on and off, I really feel the impact of hiding usable controls on-the-fly is worse than the impact of showing redundant controls.

**Comment by Simon818** [comment]
I'm just going to add that Wise (formerly TransferWise) is now liberally using 0-size radio buttons, or at least radio buttons that render as such in Firefox. If I hadn't accidentally noticed it in focus mode, I would have just thought they were clickable controls with no role whatsoever.

**Comment by Simon818** [comment]
Today I had to fill out a medical intake form hosted on a third-party site. At the end, the form asks for a signature and provides a drawing canvas--a design we're probably all familiar with.

The platform helpfully provides a hidden screen-reader-only button to "Enter your name instead." But since it is rendered off-screen and Firefox collapses those off-screen controls, NVDA didn't read it. Even when I tabbed to the button, NVDA simply said "Section".

I was 98% of the way to video-calling someone and having them remote into my machine and squiggle the mouse when I accidentally pressed space on it and found myself in a "Full Name" field. It was pure, 1000% good luck. NVDA didn't identify this as a button--why would I ever think to try and activate it?

This issue came within a hair's breadth of preventing me from receiving necessary medical care today. And regardless of the fact that off-screen controls are a poor design choice, NVDA's code transparently made this page less accessible in a very critical way. NVDA essentially lied about what was in the DOM.

I would like to know what we need to move forward on this nine months after NVAccess has agreed that this behaviour is problematic. I'm seeing increased use of these off-screen controls in my daily life--and I've doubtless missed many examples, because I'm not always going to open another browser to check if the blank line is actually a button--and this makes the current approach increasingly problematic. I understand that there are historical reasons why this was put in place, but this is now well into the territory of needlessly user-hostile.

**Comment by jcsteh** [comment]
As a matter of interest, do you know for certain that this particular case was an off-screen button that was exposed in the accessibility tree and not aria-hidden (and thus missing from the tree altogether)? I only ask because I had to deal with the same problem on a medical intake form recently, and in that case, the necessary control was (ridiculously) aria-hidden, so even the width/height fix wouldn't have helped.

**Comment by Simon818** [comment]
Actually, no, I'm not sure.

I did make an effort to do my homework here--I contacted the provider and asked for another form, opened it in edge, confirmed that the button showed up there, and confirmed that the "Enter your name instead" text did not show up in OCR. I didn't see any code in the inspector that looked like it was aria-hiding the button. The margins are all set to 0 PX.

However, if I open it in Firefox and I use AxsHammer to kill aria-hidden, the button reads correctly. If I open it in Edge, it reads correctly with no intervention whatsoever.

So now I'm just confused.

**Comment by Simon818** [comment]
Found the ARIA-hidden. It was on one of the containing elements. I guess Edge just ignores that attribute under certain conditions? I can't decide if that's a good thing or not.

Thanks for making me look more thoroughly--that is a truly weird design choice and now I get to follow up with them by e-mail again.

I do wonder if this hiding of 0-size controls causes more problems than it solves now, but I think you're right that it wouldn't have helped here. The fact that Edge revealed the button is pure coincidence.

**Comment by jcsteh** [comment]
There are a couple of possibilities:

1. The site is sniffing the browser and using aria-hidden for Firefox but not Chromium. I don't know why it would do that, but it'd be far from the first time a web author has done something utterly ridiculous.
2. Chromium has a "repair" to automatically remove aria-hidden if something aria-hidden ever gets focus. That is not yet part of the spec, but it's being discussed. But in order for that to be triggered, the button would have to get focus at some point; i.e. it wouldn't appear in browse mode until it got focus by some other means. That might have happened if you tabbed around though.

**Comment by Simon818** [comment]
> Chromium has a "repair" to automatically remove aria-hidden if something aria-hidden ever gets focus. That might have happened if you tabbed around though.

you're good. Apparently that feature has been implemented in Edge stable. The button does remain hidden until I tab to it, at which point it shows up in the virtual document.

Apologies for the comment derailment. It's certainly useful to know that there is another explanation for controls which remain invisible in Firefox but not in Edge, though. Thanks @jcsteh.

**Comment by jcsteh** [comment]
Oh, I totally agree NVDA shouldn't be ignoring 0 width/height controls now. Unfortunately, I can't get traction from the core devs to do this without a configuration option and doing it with a configuration option is going to require significant new architecture that NVDA doesn't have yet, and I don't have the time to implement it.

I did just spot that Chromium seems to have a special off-screen case here. A 0 height on-screen control still gets a height of 0. However, a 0 height off-screen control gets fudged to have the height of its nearest container. I was always a bit reluctant to fudge the height for all 0 height controls, but I might be able to justify this for off-screen controls. I still think this would ideally be fixed in NVDA, since the browser would ideally give the most accurate information and then let clients decide how they want to use it, but my tolerance for this particular issue is pretty much at its limit and I have more chance of getting this fixed in Firefox.

**Comment by jcsteh** [comment]
> It's certainly useful to know that there is another explanation for controls which remain invisible in Firefox but not in Edge, though.

Yeah. If this aria-hidden focus repair does get finalised in the spec, we will implement it in Firefox too. Unfortunately, there are some edge cases that still need to be ironed out and this kind of repair has the potential to cause its own problems where edge cases are concerned, so I'm reluctant to commit just yet.

**Comment by Simon818** [comment]
Perhaps this is a bit bold for a GitHub thread, but can any of the people pushing for a configuration option name any concrete examples of where hiding the 0-size controls in the virtual buffer would actually benefit the user? I ask that out of genuine curiosity, but also with the knowledge that you are very tuned into this space and I feel like your opinion holds a whole lot of weight. I feel like the suggestion to make this a configuration option is just being made out of an abundance of caution, whereas it's very easy to come up with many scenarios where the current behaviour could actually block a user from getting something done. I'm acutely aware that most users--including me, until you replied to my post--have no idea NVDA was deliberately hiding anything. I have no doubt that many other users experience the effects of this behaviour on websites they use every day, and do not benefit from the knowledge of how web designers try to hack accessibility and the specifics of NVDA's handling of these controls. So I believe the impact of this behaviour is growing, immeasurable, and has a very high potential ceiling. And this thread is quiet because we may be some of the only people who know about it.

**Comment by jcsteh** [comment]
To be fair, an abundance of caution is generally a good idea for a screen reader. The argument goes that changing something that has literally been this way for over a decade is risky. It could fix a bunch of cases as described here, but it could also theoretically break things that have been working for years that we don't even know about. A setting helps mitigate that risk, even if we turn on the new behaviour by default.

The problem is that in this instance, the work involved to add a setting is pretty significant, enough that clearly no one is able or willing to do it. That means this issue will just likely never get fixed, impacting an increasing number of real world cases. Also, NVDA is the only major screen reader that does this now, which further mitigates the risk, since the path has already been charted.

**Comment by BlindGuyNW** [comment]
It seems to me that if we're the only major screen reader to do it, and the real-world problems with this approach become increasingly obvious, surely it would be in the best interests of NVDA to get ahead of those risks? Sent from my iPhoneOn Oct 24, 2025, at 9:54 PM, James Teh ***@***.***> wrote:﻿jcsteh left a comment (nvaccess/nvda#13897)
To be fair, an abundance of caution is generally a good idea for a screen reader. The argument goes that changing something that has literally been this way for over a decade is risky. It could fix a bunch of cases as described here, but it could also theoretically break things that have been working for years that we don't even know about. A setting helps mitigate that risk, even if we turn on the new behaviour by default.
The problem is that in this instance, the work involved to add a setting is pretty significant, enough that clearly no one is able or willing to do it. That means this issue will just likely never get fixed, impacting an increasing number of real world cases. Also, NVDA is the only major screen reader that does this now, which further mitigates the risk, since the path has already been charted.
