### ISSUE TITLE
Emulating applications key / shift+f10 does not work everywhere

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13920]
### Steps to reproduce:

(Note: Updated description as the keystroke used it important to replicating)

1. Add an emulated system key for shift+f10 (the applications key) - and assign the shortcut shift+` (shift+grav - as per Cyrille's note, you need shift because the original keystroke uses shift)
2. Open Chrome and in Browse mode try using the assigned key on any element
3. Open a document in Word, set NVDA to browse mode, and try using the assigned key at any point in the text

### Actual behavior:

While the key works in other places (desktop icons, Firefox, notepad, etc), in Word and browsers (it happens in Firefox as well as Chrome), the emulated shortcut key does nothing when NVDA is in Browse mode.  Looking at the log (debug), it records two lines (I used control+\ as the key combination here):

IO - inputCore.InputManager.executeGesture (08:05:31.955) - winInputHook (3772):
Input: kb(desktop):shift+`
IO - inputCore.InputManager.executeGesture (08:05:31.985) - MainThread (12732):
Input: kb(desktop):shift+f10

Then nothing after the shift+f10 line, simply whatever is next recorded in the log following.

My theory is perhaps because the result of shift+` is a printable character, in Browse mode, unable to use it as a quick navigation key is NVDA dropping it?

If that is the case, the workaround is to ensure the keystroke does not result in a printable character, but also worth noting.

### Expected behavior:

Ideally the emulated system key will work in any location.

#### NVDA version:

NVDA 2022.2rc1 installed
(Also reported by a user with 2022.1)

#### Windows version:

Windows 11 (64-bit) Version: 21H2 (2009), Build: 22000.795 

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.15330.20218 
Firefox version: 102.0.1 
Chrome Version: 103.0.5060.114 

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2022.2 rc1 and 2022.1

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

**Comment by CyrilleB79** [comment]
This limitation is documented in the [user guide](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#InputGestures) with the second note in the paragraph 12.3:
> An input gesture with modifier keys may not be able to be mapped to an emulated gesture without modifier keys. For instance, setting the emulated input 'a' and configuring an input gesture of 'ctrl+m', may result in the application receiving 'ctrl+a'.

This means that you cannot map control+\ to emulate shift+F10, because the control modifier is pressed and thus it will be sent to the system during the keypress emulation. Thus, pressing control+\, you actually emulate control+shift+F10.

At the time this note was added in the user guide, you had [reviewed and accepted it](https://github.com/nvaccess/nvda/pull/11402#pullrequestreview-456518781), even if this seemed a bit hard to understand, since no better wording was found.

Thus I would suggest that you convert the PR in one of the following way:
* ask that this limitation be removed

or

* ask a better wording for the user guide

**Comment by Qchristensen** [comment]
Thanks again Cyrille!  Ok I should have kept thinking - I was halfway through the thought process to work it out!  Either way, here is still a useful place to leave this knowledge for the next person who comes along with the issue.  Once again, closing as works for me (as it does once I uncheck that setting).
