### ISSUE TITLE
Use shorter startup sound for NVDA launcher

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14068]
### Is your feature request related to a problem? Please describe.

The startup music played by the NVDA launcher (the file you download from https://www.nvaccess.org/download/ ) is relatively long.  On fast computers, this may take longer to play than the time taken to load the temporary copy of NVDA.

### Describe the solution you'd like

A shorter intro sound, could either play once, or loop for as long as it takes to load NVDA.

### Describe alternatives you've considered

We could play the progress bar sound, or a short intro sound followed by the progress bar sound, although this may be confusing for new users, as the same progress bar sound is used later when installing NVDA..

**Comment by britechguy** [comment]
Question:  Is the playing of this sound part of a step-by-step process where nothing else happens until it finishes, or is it asynchronous, that is kicked off to play and then whatever comes afterward goes merrily on its way?

If the issue is that the NVDA temporary copy is taking too long to load because it's waiting for the sound to finish, the playing of that sound could be made asynchronous, as its only real purpose is to alert the user that the NVDA install has begun.

**Comment by josephsl** [comment]
Hi,

Async from my tests - I just updated a portable copy of NVDA from 2022.2 to 2022.2.2 and the update commenced before the logo sound finished playing.

Thanks.

**Comment by britechguy** [comment]
Thanks for the confirmation.  Since it's asynchronous, and given how little processing power is needed to play sounds, you could probably kick off a symphony recording without any significant reduction of speed for the NVDA installer.

Nothing should be waiting if the sound is played asynchronously.   So the lag shouldn't be related to this.

**Comment by feerrenrut** [comment]
The sound blocks NVDA from being started, if the unpacking stage of the launcher happens faster than the length of the sound then the launcher will be blocked waiting for the sound to complete.

If there is anyone willing to create a replacement sound we'd be happy to work with you.
Please get in touch (info@nvaccess.org) and we can discuss the requirements.

**Comment by denizsincar29** [comment]
The sound was great and I'd like to be able to turn it back on
