### ISSUE TITLE
Ability to adjust volume of sounds

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1409]
**Reported by KevanGC on 2011-03-09 06:12**
Hi,

I've noticed that when you're browsing the web and you switch between Browse and Focus mode, NVDA plays these sound-effects. The sound-effects are very loud and sometimes they get annoying. It would be cool if you could add a feature for users to adjust the volumes of sound effects and progress-bar tones?
**Blocking #892, #2978, #3100, #4590**

**Comment by ctoth** [comment]
This is still giving a terrible user experience for the default case in 2016.
I often turn down my synthesizer volume when I need to turn up my system volume to hear something quiet. If then an NVDA UI sound plays, it is actively painful.

Please stop hurting my ears.

**Comment by Laughingthunder** [comment]
I agree with this. I think there should definitely be an option to tie 
the UI sounds to the speech volume.

**Comment by jcsteh** [comment]
I provided details on the problems with the current patch in these [two](https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288375) [comments](https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288376). I don't have time to work on this right now, but I'm very happy to discuss if someone can propose a solution which deals with the problems I outlined.

**Comment by bhavyashah** [comment]
Merely introducing another option in the Voice Settings dialog or the Synthesizer Settings dialog to configure both the sounds and tones of NVDA combined would suffice, in my opinion. An average user would not differentiate between NVDA's sounds, tones and beeps, and thus rolling all of their customizability into one control should not be restrictive at all. Splitting this proposed option into sounds and tones, on the other hand, may seem unnecessary clutter and an overkill for some. Upon reading the discussion on this ticket though, I reckon I agree that merging this proposal into the Voice Volume option itself would be counter-intuitive. Could this ticket, if possible, please also be prioritized since there seems enough demand for this facility viewing the number of other tickets it blocks or at least assigned a priority?

**Comment by feerrenrut** [comment]
Its hard to prioritise this above the current core projects. The demand is clear, and this seems to be an important problem to solve. On the other hand, at this stage, it is not clear what the preferred UX or implementation would be. This makes the implementation cost high. I'll set this as a P3 for now. If we can become more certain about the UX and try to simplify the issue and thus the cost of implementing this then we may be able to make it a P2.

**Comment by fernando-jose-silva** [comment]
I would just like to put my point of distress.
I resuscitated the voice of the nvda to use the voices of windows onecore, this to be able to use the functionality of reading of the emugis.
The voice in Brazilian Portuguese is very low.
One thing that's bothering me a lot is how I had to add to the sound of nvda. The sounds of nvda were almost unbearable when wearing headphones.
So I would suggest almost that in the form of a plea (laughs), it would be a way of lowering the sounds of the nvda individually, so it could make the sounds low and the synthesizer's voice louder.
I would like to add two more points.
I went to do a lecture showing the assistive technologies, and I connected the sound of the computer in sound boxes, and the difference between the voice of the onecore synthesizer was low, in contrast to the sounds of the nvda, but within the settings of the nvda The voice volume is at 100%.
And finally, I was experimenting with Joseph Lee's Object Location Tones add-on (and I would like to congratulate him), the idea was great, and the possibility of finding out where each object on the screen was, there was not an idea Visual of how it was organized the screen of a computer, however I was almost obliged to disable the complement again for the reasons above, I had to increase the overall volume of the nvda due to low onecore voice, and the sounds of the nvda were almost unbearable mainly The beeps used in the snap-in, and the progress bars.
Many thanks for the great work, and the comments are just from a constant user of nvda.

**Comment by bhavyashah** [comment]
A few thoughts:
* @derekriemer notes in https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288369 that the volume of tones (such as the beeps for progress bar updates) increases as it goes higher. This is undesirable since a user only expects the pitch to increase and the volume of the tones to remain constant. However, @brian1gaff's 
https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288370 and @jcsteh's agreement expressed in a later comment together suggest that this is a fallacy resultant of the varying frequency responses of different audio playback equipment. Derek, do you still maintain your original stand or do you agree with Brian and Jamie's explanations? Regardless, as Jamie notes in https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288375, if this actually turns out to be an existent issue, it would require a separate ticket.
* I am of the opinion that a single volume control for all NVDA (.wav) sound schemes should be controlled by one slider. While counter-intuitiveness may be a concern, placing this slider in the Synthesizer Settings dialog or in the Voice Settings dialog sounds equally fine to me. I do agree that the proposed sound volume option should be synth specific so that a user can customize the sound volume relative to the loudness of every speech synthesizer individually. The current Volume slider in the Voice Settings dialog can be renamed to Voice Volume and another slider named Sound Volume can be added. This would allow for it to be accessed by the Synth Settings Ring.
* I am not too sure I agree with the implementation of or understand the need for a "Volume of NVDA sounds follows voice volume" option. This sounds unnecessary to me.
As noted in @feerrenrut's https://github.com/nvaccess/nvda/issues/1409#issuecomment-273780316, we must discuss the UX completely so as to facilitate this ticket's reprioritization to potentially a P2. CC @fernando-jose-silva @ctoth  @Laughingthunder @leonardder and others

**Comment by fernando-jose-silva** [comment]
Perfect, thank you, I agree with the proposal of two volume controls, one for the synthesizer, and one for all nvda sounds, including beeps and all sounds of adons including beeps. This new volume setting, can stay within the voice setup window.

Enviado do meu iPhone

> Em 24 de ago de 2017, às 07:31, bhavyashah <notifications@github.com> escreveu:
> 
> A few thoughts:
> 
> @derekriemer notes in #1409 (comment) that the volume of tones (such as the beeps for progress bar updates) increases as it goes higher. This is undesirable since a user only expects the pitch to increase and the volume of the tones to remain constant. However, @Brian1Gaff's
> #1409 (comment) and @jcsteh's agreement expressed in a later comment together suggest that this is a fallacy resultant of the varying frequency responses of different audio playback equipment. Derek, do you still maintain your original stand or do you agree with Brian and Jamie's explanations? Regardless, as Jamie notes in #1409 (comment), if this actually turns out to be an existent issue, it would require a separate ticket.
> I am of the opinion that a single volume control for all NVDA (.wav) sound schemes should be controlled by one slider. While counter-intuitiveness may be a concern, placing this slider in the Synthesizer Settings dialog or in the Voice Settings dialog sounds equally fine to me. I do agree that the proposed sound volume option should be synth specific so that a user can customize the sound volume relative to the loudness of every speech synthesizer individually. The current Volume slider in the Voice Settings dialog can be renamed to Voice Volume and another slider named Sound Volume can be added. This would allow for it to be accessed by the Synth Settings Ring.
> I am not too sure I agree with the implementation of or understand the need for a "Volume of NVDA sounds follows voice volume" option. This sounds unnecessary to me.
> As noted in @feerrenrut's #1409 (comment), we must discuss the UX completely so as to facilitate this ticket's reprioritization to potentially a P2. CC @fernando-jose-silva @ctoth @Laughingthunder @leonardder and others
> —

**Comment by derekriemer** [comment]
No, of course that is an audio illusion.

**Comment by derekriemer** [comment]
I think the follow checkbox might be useful, so that NVDA sounds and synth sounds remain the same if the user turns down the synth, the user also turns down the speech.

**Comment by rokit** [comment]
Here is my two cents as a user. The UX cost for not having this feature in place is greater than the UX cost of a wrong implementation. People who rely on audio to move about on a computer should be able to set audio levels that are comfortable.

**Comment by fisher729** [comment]
Hi.

A suggestion. In the synthesizer dialog for NVDA, present a combo box labelled "NVDA sound volume for progress bars and audio", and make it impossible to set this value to 0, as other options in NVDA settings allow for these to be toggled off.

**Comment by bhavyashah** [comment]
If #8711  gets implemented first, I propose including the sound volume adjustment options requested in this ticket in the Sound Settinggs dialog as opposed to elsewhere in NVDA's Settings.

**Comment by Carlos-EstebanM** [comment]
Hi all.
A user in the Spanish Community requests a feature for change the volume of sounds to start and exit.
Now, the Add-on Tony's enhancements add commands for change the volume of NVDA (voice and sounds). I think that the slider for volume of sounds is a good idea, but also is possible have an individual slider. The solution for change the individual volume in these moments is open the files of waves folder with an audio editor, change, save and replace.
NVDA can have various sliders, like volume of sounds to start and exit, volume of sounds for focus and browse mode in a category of options.
Regards.

**Comment by Cleversn** [comment]
I'd like a slider to control NVDA sounds' volume as well, especially the progress bar beep, preferably apart from the voice volume.

**Comment by zepumph** [comment]
From https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288371:

>going in to a form field which is shockingly, terribly loud.

I couldn't agree more, I am an accessibility developer and tester at PhET Interactive Simulations and I get a headache after just a few minutes because of the enter/exit forms-mode sounds. This would be a wonderful improvement to your amazing project! Thanks!

**Comment by valiant8086** [comment]
My biggest one is the progress beeps. If I turn speech down the beeps 
don't go with it and become too loud.


Cheers:
Aaron Spears, AKA Valiant8086 General Partner at Valiant Galaxy Associates "we make (VERY GOOD AUDIOGAMES) for the blind comunity" http://valiantGalaxy.com

**Comment by beqabeqa473** [comment]
there was 12 years passed and no solution was done.

Maybe we can revisit overal thing, and provide a solution.
I can try to work on this, but before we should identify what we want to see.

**Comment by Adriani90** [comment]
I think I am with Derek, turning down speech volume should turn down sounds volume as well. otherwise the settings would be to granular and people would get overwelmed by having to adjust tones of volume settings depending on how many profiles they are using.

Maybe using other wav sounds with a softer texture would improve the user experience.

I propose to also change the checkbox "play sounds" in NVDA general settings to a list with checkboxes, where people can mute and unmute different sounds in NVDA, i.e. progress bar, browse and focus mode, start and exit. The individual sound muting settings are mainly changed on a global scale rather than on a specific profile.

**Comment by ctoth** [comment]
I'm just sad that it's 12 years since the original bug report, I implemented something that would have at least worked, and we're still discussing this.

Rather than blocking patches that aren't perfect until a perfect solution has been developed, I feel this project would make far more progress if it were willing to iterate and make improvements as they came, even if they weren't perfect.

I know that for me, every time my ears are blown out by the inappropriately-loud form field sound when the speech volume is turned all the way down, I think negatively about this.

It would be a good idea to replace all NVDA Sound Output, in fact, using something like https://miniaud.io/

Then all sound volume could be unified and we wouldn't have to worry about odd quirks of WaveOut.

Whatever we end up doing, I hold this truth to be self-evident:
We don't need a million more options.

**Comment by jcsteh** [comment]
In the WASAPI backend in #14697, I've just added support for configuring specific audio sessions (007b6fc). Tones and wave files have been split into a separate "NVDA sounds" session, which means this volume can be set independently using the system Volume Mixer. Undoubtedly, this won't be good enough for some people, since it isn't configurable from within NVDA's own UI and it doesn't change with the volume of the voice. However, changing the two together isn't desirable for everyone either. And having too many options is difficult to maintain and too complex for some people. So we can't win whatever way we go. Regardless, this at least partially addresses the concern, since users will now have some way of adjusting the volume of sounds, even if they don't love it.

This change also makes it possible to set the session volume via nvwave, so a check box could be added to make the volume of sounds follow the voice volume if so desired.

**Comment by jcsteh** [comment]
> Rather than blocking patches that aren't perfect until a perfect solution has been developed, I feel this project would make far more progress if it were willing to iterate and make improvements as they came, even if they weren't perfect.

There's truth in that. On the other hand, the only solution thus far would have suited one use case (tying sound volume to voice volume) and regressed another use case (users who absolutely don't want sound volume tied to voice volume). The comments on this issue have made it pretty clear that both use cases are real and not imagined. As it is, I suspect you're not going to like the solution I've come up with above because it doesn't tie the two together and because you have to open the system Volume Mixer to use it. It's not perfect, but at least it doesn't break people who depend on them remaining separate.

> Whatever we end up doing, I hold this truth to be self-evident: We don't need a million more options.

And yet, as noted above, there are multiple use cases we have to address here, some of which negatively impact others. One person's "not perfect but workable" is another's "this breaks me on a daily basis".

**Comment by beqabeqa473** [comment]
NVWave still does not have a possibility to simply set a volume of sounds, not talking about adjusting it from an ui.

I have an addon and wanted to adjust volume of playWaveFile with my own addon UI but as i understand, nvwave doesn't have such possibility.

@ctoth Do you still have that patch around? I was searching on my pc such piece of code but unfortunately was not able to find and that dropbox link is not working anymore.

**Comment by jcsteh** [comment]
nvwave currently doesn't, but the WASAPI version of nvwave in #14697 now does. @ctoth's original patch only set the volume for the entire application, not individual streams/sessions. See https://github.com/nvaccess/nvda/issues/1409#issuecomment-155288376.

**Comment by XLTechie** [comment]
@jcsteh
> This change also makes it possible to set the session volume via nvwave, so a check box could be added to make the volume of sounds follow the voice volume
> if so desired.

If that checkbox being set true was made the default, so it didn't take a 
technical user to know what had to be done to make it work like most people 
expect, I think that would go a long way to making this a non-issue.

**Comment by Adriani90** [comment]
I agree with @XLTechie on the checkbox suggestion. Jamie huge thanks to you and the guys from NV Access for working on the audio output stuff, writing more than 1,000 lines of code in this project is really a huge talent. Really amazing.

@ctoth I understand totally your frustration. On the other hand, I also understand the developers who want to provide a solution that is really improving user experience and does not result in lots of additional issues or important functionalities being broken.
To be realistic, this is the nature of open source projects. Many people contribute to this project volutarily, and structural funding sources for open source projects is still a challenge, even in 2023. So imo even if we have to wait many years to see significant improvements in certain cases, it is really incredible how far this project came given the small team at NV Access and many people working in their spare time for this project.

I'd say don't loose your motivation, even when things take long time to happen. This is the only way we can stand out against purely commercial solutions that often do as much as open source solutions or even less.

**Comment by jcsteh** [comment]
Looking at all the comments here, I'm still not convinced that having this check box (once implemented) default to enabled is actually "what most people expect". This is largely because there is no guarantee that a given voice will have an equivalent volume to the sounds; see the comments above regarding some OneCore voices, for example. Thus, I think the correct approach here is to get the check box implemented, default it to disabled and then see where we land. This minimises risk while giving users an option if they want it.

**Comment by beqabeqa473** [comment]
Personally for me it does not matter will it be enabled by default or not.
Of course, from an nn-advanced user's view it would be better to make this checkbox disabled by default, but having this as an option is more than appreciated.

It would be better to find a way to implement concrete volume control in nvwave itself.
I understand @jcsteh said that it is now possible to control volume from system mixer, but having it controled from the code also would be great for winmm if wasapi won't be enabled by default for a while.

**Comment by jcsteh** [comment]
We need WASAPI for controlling both via the System Volume Mixer and via nvwave. It just isn't worth implementing it for WinMM at this point. The intention is now to get WASAPI enabled by default in alpha as soon as possible to get maximum possible feedback.

**Comment by beqabeqa473** [comment]
Yes, that makes sense if it will be enabled by default

**Comment by seanbudd** [comment]
@jcsteh - can this be closed given #14697 was merged?

**Comment by jcsteh** [comment]
This issue got a bit conflated. There were two requests here: the ability to control the volume of sounds in general, and the ability to link the volume of sounds to NVDA's speech volume. The former is implemented by #14697. The latter is implemented by #14896. Thus, I think this should be closed by #14896 for completeness.
