### ISSUE TITLE
Home/End are nonfunctional in NVDA menu

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#14103]
### Steps to reproduce:

1. Press NVDA+N.
2. Attempt to jump to the top or bottom of the menu using home or end.

### Actual behavior:

Nothing happens

### Expected behavior:

Home/end should move you to the top/bottom of this menu, like in any other Win32 menu.

### NVDA logs, crash dumps and other attachments:

N/A

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2022.2.1

#### Windows version:

Windows 11 21H2 (64-bit) build 22000.856

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

Processor	AMD Ryzen 9 5950X 16-Core Processor, 3401 Mhz, 16 Core(s), 32 Logical Processor(s)
Installed Physical Memory (RAM)	128 GB

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by cary-rowen** [comment]
> like other win32 menu?
Does using Home and End work as expected in Windows Notepad's menu?

**Comment by TheQuinbox** [comment]
It does, and that's exactly how I tested it. My bad, I should've probably made that a bit clearer.

**Comment by lukaszgo1** [comment]
If you've tested with Notepad in Windows 11  it is important to point out these are not standard Win32 menus any longer, but a component written in XAML or something similar. I failed to find any standard Win32 menu where Home and END works.

**Comment by josephsl** [comment]
Hi, one place Home and End keys work is Firefox menus but the menu item itself uses a Mozilla widget class as window class. As for Windows 11 Notepad, it uses WinUI controls (ultimately derived from XAML). To make progress, we need definitive examples from ones other than what folks have listed already (Windows 11 Notepad does not qualify). Thanks.

**Comment by ruifontes** [comment]
It works in Thunderbird menus...


Rui Fontes


Às 15:18 de 04/09/2022, Łukasz Golonka escreveu:

**Comment by ruifontes** [comment]
WordPad of Windows 21H2 (Build 22000.918)


Rui Fontes


Às 15:51 de 04/09/2022, Joseph Lee escreveu:

**Comment by josephsl** [comment]
Hi, Home and End keys do not work in Windows 10 Notepad even though menu items have the class name of “#32768”. This raises a follow-up question: what makes some menus respond to Home and End keys while others do not? If it turns out this is GUI toolkit dependent, then the issue morphs into whether or not wxWidgets supports the suggested behavior and if that is even the standard. Thanks.

**Comment by josephsl** [comment]
Hi, actually, only the File menu for Windows 11 WordPad as it uses ribbons, and it is actually a .NET application (not a pure classic Win32 app as some may say). Thanks.

**Comment by Qchristensen** [comment]
I've never even thought to try using home and end in a menu!  And it looks like now I know, I'm coming in after it's  going out of fashion...

Meanwhile, I think it's worth proceeding with this issue as a request for such functionality, whether or not it happens in every other program.

FWIW, home and end also seem to work in Slack's menu, and the Windows start menu in Windows 11 (eg all apps)

**Comment by jcsteh** [comment]
Win32 menus do not support home/end and never have. Notepad++ and REAPER use classic Win32 menus, for example. For something bundled with Windows, you can try the Explorer context menu, which is still a Win32 menu even though Explorer uses ribbons for its main menus. That context menu doesn't support home/end either.

wxWidgets uses Win32 menus. I don't think it's actually possible to extend key handling in Win32 menus. You can't even do something hacky with NVDA's key hook because Win32 menus don't support setting focus via window messages or accessibility APIs.

Wordpad, Windows 11 Notepad, Firefox and Thunderbird all use something other than Win32 for their menus.

**Comment by jcsteh** [comment]
In other words, as far as I know, it's not possible to implement this without using a different GUI toolkit.

**Comment by TheQuinbox** [comment]
Ah, okay makes sense. Thanks for the information :)

**Comment by Brian1Gaff** [comment]
This effect has always been flaky in Windows controls, some wrap some don't 
some work with end  etc, som don't, quite why there are so many different 
types in Windows escapes me, but add third party software and well, good 
luck.
 One might also ask why do some menus respond to the key of the first letter 
and some do not.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
