### ISSUE TITLE
my request is especially for nvda 2017.3!

### ISSUE THREAD

**Issue by zahra21** [nvaccess/nvda#14142]
hi.
a few month ago, i edited persian documentation for nvda 2017.2 and 2017.3. i asked Mohammadreza rashad for permission that my changes becomes available in nvda 2017.2 and nvda 2017.3. i am very glad that i became a little familiar with html and wish to help nvda. but the best versions for me are 2017.2 and 2017.3. for nvda 2017.3 i spent several days and i really wish that we can download nvda 2017.3 with Mohammadreza's rashad translation with my changes and edits!
since it does not require changing source codes, i believe that its a very simple for nvda developers. you just need visual studio community 2017 see nvda 2017.3 changes for developers.
God bless you and His especial mercy i pray for you!

**Comment by josephsl** [comment]
Request should (and shall) not be honored as it pertains to an older version of NVDA.

**Comment by josephsl** [comment]
Hi,

In all seriousness, translation changes will target NVDA 2022.3 and later. Sorry.

**Comment by Brian1Gaff** [comment]
Might I ask why you need that particular version of nvda
I do myself have some old xp machines with older versions of NVDA on them, 
but not expect any software company to do any modifications to them, they 
are set in time and I doubt many have a legacy system to test it on either 
and very few would need a version that old unless there is a specific 
reason. You might stand a better chance on a more general list for those who 
are using older software, but its very much a niche situation. I encounter 
it with Windows 7, but I am aware of some medical devices which have to use 
old drivers running on  Windows XP due to the company either no longer 
existing or they want to  sell you new hardware.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Zahra Ayat" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, September 13, 2022 8:11 PM
Subject: [nvaccess/nvda] my request is especially for nvda 2017.3! (Issue 
#14142)

**Comment by zahra21** [comment]
hi brian.
since it does not need require changing source code, its a very simple request from developers and i was sure that they accept it.
since its without changing source code, it does not cause issues, crashes, instabilities, or other problems in the software. its a very small change!
nvda 2017.3 is the best version for me.
its espeak is the best,
also, its a last version that even supports windows xp and vista.
i love a version that supports all operating systems and 2017.3 is that version!
i asked someone to test it even in windows 11 for me and he replied: 2017.3 is compatible with windows 11 in non professional and simple tasks.
i am not professional and dont know and dont use terminal, cmd command line programs at all, and for simple and daily tasks, 2017.3 is compatible with all versions of windows since xp sp2 until windows 11!
these are only two of the reasons that why i love 2017.3 and not newer versions.
i have more reasons that i dont like 2019 and above.

**Comment by CyrilleB79** [comment]
Hello
NVAccess has never provided an update to a version that is not the most recent one. And I do not think they will spend time for it in the future.
If you have issues with newer versions (eSpeak or others), you'd better open issues for it so that it be tracked and fixed by NVAccess or eSpeak in future versions.

If you still want to update NVDA translation in 2017.3, you are free to compile your custom updated version of NVDA 2017.3 since NVDA is free and open source software.
