### ISSUE TITLE
PROBLEMS WITH DIALOG BOXES ON WEB PAGES IN FIREFOX

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1418]
**Reported by dharvey on 2011-03-18 11:57**
Hi,

Has anyone noticed when using some websites EG Facebook when interacting with the site IE replying to an event or message, or sending a friend request an inaccessible dialog box pops up when using Firefox 3.6.15? IE isn't affected by this issue.

STR using FB.
1. Log into your Facebook account.
2. Go to the Events page and find the Respond button and clikc it.
3. Find the series of radio buttons, noticed the dialog box that pops up?
4. Try sending a message to someone, go to a friend's profile and try to send a PM, the same dialog box pops up.

Try the same instructions in IE, notice there's no change? You can still review the page as normal and jump to elements IE Radio button, form field ETC, but using FF has the dialog problem, and has domedone resets to see if it was my browser that was causing it.

**Comment by ehollig** [comment]
I was not able to reproduce this using the STR provided in https://github.com/nvaccess/nvda/issues/1418#issue-116026084, step 4, as I believe the events page has changed since this was created. @jcsteh, does NVDA treat ARIA dialogs any differently since this was created?

**Comment by jcsteh** [comment]
Before #7433 (which has only happened in the last couple of weeks), dialogs in all browsers (except Edge) did not use browse mode. Due to changes in ARIA 1.1 and the prevalence of web dialogs relying on users being able to browse document content (including Facebook), PR #7433 (issue #4493) changes this so that browse mode is used for dialogs.

Closing as a duplicate of #4493.
