### ISSUE TITLE
error: Couldn't terminate existing NVDA process, abandoning start:

### ISSUE THREAD

**Issue by MesterPerfect** [nvaccess/nvda#14251]
## General information
Sometimes when I restart nvda after installing an add-on or after any action I get this error message

```
Error

usage: nvda.exe [-h] [-q] [-k] [-f LOGFILENAME]
                [-l {10,12,15,20,30,40,50,100}] [-c CONFIGPATH]
                [--lang LANGUAGE] [-m] [-s] [--disable-addons]
                [--debug-logging] [--no-logging] [--no-sr-flag]
                [--install | --install-silent | --create-portable | --create-portable-silent]
                [--portable-path PORTABLEPATH] [--launcher]
                [--enable-start-on-logon True|False] [--copy-portable-config]
                [--ease-of-access]

error: Couldn't terminate existing NVDA process, abandoning start:
Exception: [WinError 5] Access is denied.

OK   
```

### Steps to reproduce:
Restart nvda and nothing else

### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/9789991/log.txt)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
release 2022.3

#### Windows version:
Windows 10 Version 10.0.19042 Build 19042

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
release 2022.2

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
@MesterPerfect Can you please supply [debug level log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behavior for this issue, we would like both:
- `nvda.log`
- `nvda-old.log`

This will allow us to see what the pre-running NVDA process is doing and the NVDA process that should replace it. Debug level logs are important so that we can see the details of what NVDA is doing.

Can you also please confirm that this issue happens when all add-ons are disabled. Please disable the addons through the add-on manager to ensure they do not run again in the new NVDA process (after restart).

**Comment by MesterPerfect** [comment]
The thing that makes me unable to determine the error is that it does not repeat
It happens very randomly
Yesterday and today, I did not encounter this problem
But before yesterday I came across 3 times
This is what made me open the issue here
Anyway, how do I get nvda.log and nvda-old.log
Even if the problem occurs again I will post them here for you

**Comment by MesterPerfect** [comment]
@feerrenrut
good morning
I encountered the problem again while working with poedit
Required files are attached
[nvda.log](https://github.com/nvaccess/nvda/files/9815829/nvda.log)
[nvda-old.log](https://github.com/nvaccess/nvda/files/9815830/nvda-old.log)

**Comment by MesterPerfect** [comment]
The problem has been repeated a while ago, and these are the required files

[nvda.log](https://github.com/nvaccess/nvda/files/9905856/nvda.log)
[nvda-old.log](https://github.com/nvaccess/nvda/files/9905857/nvda-old.log)

**Comment by MesterPerfect** [comment]
The error reappeared after updating an add-on and restarting
[nvda-old.log](https://github.com/nvaccess/nvda/files/9951682/nvda-old.log)
[nvda.log](https://github.com/nvaccess/nvda/files/9951678/nvda.log)

**Comment by feerrenrut** [comment]
Thanks, unfortunately there isn't a relevant error in these logs. We might need to make some changes to how NVDA logs this situation in order to get information we need to understand the cause. Given this does not appear to affect others, it is likely something specific to your machine. Are you comfortable exporting registry information? It might be helpful to see the contents of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Accessibility\ATs\nvda_nvda_v1`. Exporting this folder and attaching it (in a zip file) might tell us something.

**Comment by Adriani90** [comment]
@MesterPerfect This might have to do with your addons environment which contains unofficial addons. Python might be broken in this addons and it is not possible to track where the error comes from. Did you update the addon updater itself? Could you try to reproduce this error without the addon whatsapp +? This seems to be an inofficial addon.

Here is a treat on this error:
https://stackoverflow.com/questions/26091530/permissionerror-winerror-5-access-is-denied-python-using-moviepy-to-write-gif

I personally think it could be some privileges problem or your anti-virus software blocks some python installations, especially if they register something into your Windows registry. I recommend to try reproducing this problem with official addons only, that means with addons registered on www.addons.nvda-project.org.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since more than two years. I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
