### ISSUE TITLE
Appveyor: build using Visual Studio 2022 image

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#14338]
Hi,

Follow-up to #14337:

### Is your feature request related to a problem? Please describe.
Now that Visual Studio 2022 can be used to build NVDA locally, try applying it to Appveyor. Among other things, this allows the project to use Windows 11 SDK 10.0.22621.

### Describe the solution you'd like
Edit appveyor.yml and specify Visual Studio 2022 image.

### Describe alternatives you've considered
Leave it as is.

### Additional context
Windows 11 SDK 10.0.22621 may introduce new features and changes, so note them in the process.

**Comment by josephsl** [comment]
Hi,

Note that standardizing on Visual STudio 2022 locally and on Appveyor means developers must use Windows 10 Version 1809 (October 2018 Update) or later when building NVDA localy since that's what Visual Studio 2022 wants (system requirements).

Thanks.

**Comment by michaelDCurran** [comment]
See comment on pr #14313 as to what is currently blocking us from moving to VS 2022 on appveyor:
"The VS 2022 image on appveyor is Windows 11. As Notepad has been modernised with a richEdit control on Windows 11, this causes inconsistancy for our system tests between win 10 and 11.
In order to progress this pr further, we'll need to find a replacement for notepad that provides the same control on both win 10 and 11.
However, we should at least take the first commit from this pr as it does enable full compilation of NVDA with VS 2022 locally, without requiring the VS 2019 build tools."

**Comment by seanbudd** [comment]
closed via #14313
