### ISSUE TITLE
Broader support for announcing text emphasis

### ISSUE THREAD

**Issue by A11yGeek** [nvaccess/nvda#14381]
### Is your feature request related to a problem? Please describe.
Many websites and documents, especially learning materials and instructions, rely on bold or, in the case of websites, semantic markup, such as `<em>` and `<strong>` tags to emphasize words and phrases in text. This information should be accessible to blind people. Especially people who are totally blind do not necessarily assume text to be emphasized in any way, so it might not occur to them at all to check it. W3C considers `<em>` and `<strong>` tags to fulfill the requirements of the criterion Info and relationships (1.3.1, Level A). According to WCAG, bold or italics alone are not enough to fill the requirements. Some organisations such as SiteImprove suggest that content authors should convey the emphasis through text (e.g. repeating and rephrasing), but that can slow down and add clumsiness to the reading experience. Also using ARIA to get the screen reader to announce the emphasis is not in line with accessibility best practices. In MS Office documents, bold should be announced automatically because HTML tags are not available there to improve accessibility. I would consider announcing bold also in web pages because it so frequently used.
NVDA has some settings related to announcing emphasized text, but they are under "Document formatting". By default, the emphasis is not checked, highlighted (marked) text is checked, and style is not checked. Checking the check box emphasis does not affect the reading experience on a web page that has text emphasized with `<em>` or `<strong>`. Also checking the styles checkbox does not change the web experience on the page that has bolt text nor cause NVDA to announce bold in a Word document.
### Describe the solution you'd like
I suggest that NVDA should announce that a word or phrase is emphasized when the text is bolt (using style or semantic element) or tagged with `<em>` or `<strong>`. This setting should be default and cover both websites and documents. The user could change these options in the settings. A better place for these settings could be under "Speech", not "Document formatting", if the settings cover more contexts than only documents.
### Describe alternatives you've considered
NVDA could say for example "emphasis start" and "emphasis end" around the emphasized `<em>` text, and "important start" and "important end" around text tagged with `<strong>`.
### Additional context
NVDA version used: 2022.3.2
Operating system: Windows 10.0.19044
Example used of WCAG compliant emphasis:
[https://www.w3.org/WAI/WCAG21/working-examples/semantic-text/](url)
Example used of bolt text on a web page:
[https://www.w3schools.com/html/html_formatting.asp](url)
[Bold example.docx](https://github.com/nvaccess/nvda/files/10032331/Bold.example.docx)

**Comment by A11yGeek** [comment]
I noticed that the tags were missing. I'm talking about `em` and `strong` tags whenever I mention tags.

**Comment by A11yGeek** [comment]
I found the setting that enables reading strong and emphasized text. The setting is Document formatting -> Font attributes. In any case, my original feedback still makes sense: the setting was very difficult to find for me as an accessibility specialist, so probably it is difficult for an average user as well. The location of the setting (document formatting) is not logical, and the name of the setting (font attributes) does not tell very much to an average user.

**Comment by feerrenrut** [comment]
To start with, it's important to differentiate `em` and `strong` from `italics` and `bold` the former are the intended semantics of the author, the later are presentation details.
- Reporting `<em>` and `<strong>` is controlled in NVDA via the `Document formatting -> Report emphasis`.
- `Document formatting -> Font attributes` reports the presentation details of the font used.

As for enabling this by default, it is a fine line to walk. The feedback we've had from users is that hearing bold / italics (presentation details) by default is overly verbose. Creating difficulties for comprehension of the content.
We have tried enabled `em` and `strong` and had strong feedback that it was not preferred.

Additionally, it should be noted that currently only Internet Explorer exposes the semantic `em` and `strong` to screenreaders. Firefox, and chromium-based browsers would need new implementations to support this.

There may be less intrusive ways for this information to be reported in the future (I.E. voice changes, earcons), these are yet to be developed in NVDA, and would need to be tested with real world users.

If you have ideas about how to arrange these settings in a more intuitive way, please [open a new discussion](https://github.com/nvaccess/nvda/discussions), since that is a more appropriate format.

I'm going to close this issue now since it is not actionable.
