### ISSUE TITLE
Browse mode is not available in some electron apps running on Windows 11 ARM

### ISSUE THREAD

**Issue by rperez030** [nvaccess/nvda#14397]
I have observed this problem with the 64 version of 1Password 8, the RIM app by Pneuma solutions and the version of Slack that can be obtained from the Microsoft store running on a virtual machine with Windows 11 ARM. The problem does not occur with the 32 bits version of Slack, the ARM64 version of Visual Studio code or Teams. All the apps work as expected with Narrator. Executing the command focus.devInfo in the Python Console while focus is inside any of the non-working apps shows the IAccessible2 properties related to the object with focus.

### Steps to reproduce:

1. Download and run Slack from the Microsoft Store.
2. While focus is on the app, try turning on browse mode by pressing NVDA +the space bar.

### Actual behavior:

Nothing happens. The following gets added to the lock when the electron app receives focus:

DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (18:55:41.302) - MainThread (4072):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.

### Expected behavior:

NVDA can switch between focus and browse mode.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2022.3.2

#### Windows version:

Edition	Windows 11 Pro

Version	22H2

OS build	22621.819

Experience	Windows Feature Experience Pack 1000.22636.1000.0

#### Name and version of other software in use when reproducing the issue:

N/a

#### Other information about your system:

Windows is running on a Parallels VM

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi,

Can you report the results of:

1. From the affected app, press Control+NVDA+F1 and see if says something.
2. Again from the affected ap, press Control+NVDA+Z, then type "focus.appModule.appArchitecture" and see if it says "AMD64" or something similar.

If it says something other than "AMD64" for the app architecture, chances are that this is an emulation compatible (Arm64EC) application with a mixture of x64 and ARM64 code included. CC @MichaelDCurran, do you think we should update our building logic to support injecting code into AMD64/Arm64EC processes in Windows 11 on ARM?

Thanks.

**Comment by rperez030** [comment]
@josephsl Results from 1password:

 1password module is loaded.  1Password.exe is currently running.

focus.appModule.appArchitecture: ARM64

Results from the RIM app:

 Remote Incident Manager.exe is currently running.

focus.appModule.appArchitecture: ARM64

**Comment by rperez030** [comment]
Looking at the devInfo output for 1Password I found the following:

appModule: <'1password' (appName '1password', process ID 4760) at address 80feef0>
appModule.productName: exception: processHandle is 0
appModule.productVersion: exception: processHandle is 0

**Comment by michaelDCurran** [comment]
Yes, we definitely want to support injecting into AMD64 / ARM64EC 
processes if we can.

The quickest fix here is to change NVDAHelper.py to start an 
nvdaHelperRemoteLoader process for both AMD64 and ARM64 on ARM. 
Currently it only starts an ARM64 nvdaHelperRemoteLoader process. This 
change will then allow injecting into AMD64 processes on ARM.

As for ARM64EC: just a guess, but I'm pretty sure that starting an 
nvdaHelperRemoteLoader process for AMD64, and therefore registering the 
needed AMD64 injection winEvents, will also cause us to automatically be 
also injected into ARM64EC processes for free, as they are fully 
compatible with AMD64. However, for performance reasons we could also 
provide ARM64EC builds of our injection DLLs, and use them on Windows 11 
for when registering in nvdaHelperRemoteLoader AMD64. Which would 
provide greater performance on AMD64 and ARM64EC processes.

However, there is no need, and in deed it would be detrimental to, 
provide / run a nvdaHelprerRemoteLoader specific for ARM64EC at the same 
time as running an nvdaHelperRemoteLoader for AMD64, as this will cause 
us to inject two lots of DLLs into both of those process types at the 
same time.

Somewhat related: the appArchitecture property on appModules currently 
reports ARM64 for AMD64 processes on ARM which is incorrect. This is 
because we only detect WOW64 (I.e. 32 bit emulation). On Windows 11, we 
need to instead call GetProcessInformation, giving it the 
ProcessMachineTypeInfo constant.

**Comment by josephsl** [comment]
Hi,

As for GetProcessInformation function call, I think it would be best to split this into a separate issue/PR pair (wish we can get Microsoft ARM development kit to test this scenario more fully).

Thanks.

**Comment by josephsl** [comment]
Hi,

Possible solution based on Mick's comment:

1. Change the Remote Loader 64-bit class by adding a keyword argument to the constructor, taking lib64 directory. By default, it will use whatever lib64 variable gets set to.
2. In the initialize function, run an additional remote loader executable for AMD64 processes if this is Windows 11 on ARM (cannot be done for Windows 10 on ARM because it does not support running AMD64 processes). Be sure to termiante BOTH processes in Windows 11 on ARM (to do this, define another variable just to hold a reference to the second remote loader executable class).

Ideally someone using a Windows 11 on ARM device should come up with a pull request.

Thanks.

**Comment by michaelDCurran** [comment]
NV Access has just purchased a 2023 Windows Dev Kit which means we are 
now again in a position to be able to test on ARM. So, I'll look into 
these changes in the near future.

**Comment by rperez030** [comment]
I don't feel like I have the skills to send a PR for something like this at this point but I'm happy to test with my Windows ARM VM. I'm running NVDA from source so I can checkout any PR as soon as it become available.


On Nov 26, 2022, at 8:16 PM, Michael Curran ***@***.***> wrote:

﻿

NV Access has just purchased a 2023 Windows Dev Kit which means we are
now again in a position to be able to test on ARM. So, I'll look into
these changes in the near future.

**Comment by josephsl** [comment]
Hi, thanks. As a starting point, can you test #14404 and see if an AMD64 app is recognized as an AMD64 app on Windows 11 on ARM please? That can provide something for us to look at once a pull request is created to resolve this issue. Thanks.

**Comment by michaelDCurran** [comment]
Yes, I'm planning on taking on all of this project.
And as I mentioned before, On ARM, AMD64 apps are incorrectly reported 
as ARM64 in NVDA. Thus we need to fix AppModule.appArchitecture, as well 
as fix the logic with nvdaHelperRemoteLoader.

**Comment by rperez030** [comment]
Done. @josephsl  i left a comment on #14404.
