### ISSUE TITLE
Update the documentation about the CONTROL+SHIFT+NVDA+f1 key shortcut to copy a log selection to the clipboard

### ISSUE THREAD

**Issue by thgcode** [nvaccess/nvda#14410]
### Is your feature request related to a problem? Please describe.
No. I learned yesterday about this key shortcut, a friend pressed it by accident, thought it would be useful and shared it with me.

### Describe the solution you'd like
Update the key commands guide and manual to include this gesture, optionally see if there are other gestures not present on the documentation.

### Additional context
This keyboard shortcut marks the start of the log to copy to the clipboard. It might be useful for developers since then wouldn't need to search the log for the start of the text, select it and copy.

**Comment by seanbudd** [comment]
This should be updated in the user guide in the log viewer section, using the `kc:include` commands and new table.

**Comment by Adriani90** [comment]
This behavior is still buggy in NVDA. When I use this command NVDA does not only copy the real content that I am going through with the carret, but also the arrow key presses that I do between the starting position and the ending position. This is definitely not expected since my key presses are logged at the end of the log file.
NVDA does also copy the message confirmation of the starting position when pressing the command, and not the first line of the content. The first line of the content that I want to copy is alway skipped and replaced by the NVDA message.

Exmaple comparisson between usual copy and the NVDA specific copy feature:
Content selected with shift and arrow keys and copied with ctrl+c:
```
DEBUGWARNING - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (00:14:30.503) - MainThread (2948):
AppModule does not have a binding handle
INFO - globalCommands.script_navigatorObject_devInfo (00:14:30.556) - MainThread (2948):
```

Content marked and copied with NVDA+shift+control+f1:
```
IO - speech.speech.speak (00:15:33.766) - MainThread (2948):
Speaking ['Log fragment start position marked, press again to copy to clipboard']
IO - inputCore.InputManager.executeGesture (00:15:35.657) - winInputHook (11044):
Input: kb(laptop):downArrow
IO - speech.speech.speak (00:15:35.673) - MainThread (2948):
Speaking ['AppModule does not have a binding handle\r']
IO - inputCore.InputManager.executeGesture (00:15:36.263) - winInputHook (11044):
Input: kb(laptop):downArrow
IO - speech.speech.speak (00:15:36.276) - MainThread (2948):
Speaking ['INFO - globalCommands.script_navigatorObject_devInfo (00:14:30.556) - MainThread (2948):\r']
IO - inputCore.InputManager.executeGesture (00:15:40.915) - winInputHook (11044):
Input: kb(laptop):control+shift+NVDA+f1
```

In the second example, the first line is not copied. Should the content not be the same in these two examples? Why is there a "\r'" at the end of the last speech uterance?

I was thinking to document this in the user guide but we cannot do it as it stands.

**Comment by Adriani90** [comment]
See #9844 for more details. cc: @JulienCochuyt

**Comment by CyrilleB79** [comment]
> This behavior is still buggy in NVDA.

No, the behavior is not buggy. But it is clearly badly documented. And the examples in your previous comments show that you do not seem to have understood how this gesture works.

You seem to think (as documentation also seem to say), that this command should be used when the log viewer is opened. This is not at all the case and this command is meant to be used from anywhere (hence being a global command).

Let's imagine you want to test what happens when you read the current line and you want the log for this action:
* Press NVDA+shift+control+F1 to identify the start point of the action in the log
* Press NVDA+UpArrow to read the current line
* Press NVDA+shift+control+F1 to copy to the clipboard the log from start point to current point.
And you have done all this without opening the log viewer.

Since this command is not intended to be used in the viewer and given the misunderstanding of its usage demonstrated in your previous comment, I think that it is not a good idea to put it in the log viewer section: it would make it more confusing.

Maybe while updating the user guide for this command, you may also update its description in input help mode and in the Input gesture dialog to make it clearer so that people understand that this command is intended to be used from everywhere and not in the log viewer.

**Comment by Adriani90** [comment]
@CyrilleB79 thanks very much for your good explanation. Now I got it. :-)
