### ISSUE TITLE
NVDA in Microsoft Store is grossly out of date

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#14504]
### Steps to reproduce:
N/A - The current version of NVDA offered by the Microsoft Store is 2019.3 and the store page shows a release year of 2017, which is not even accurate for NVDA 2019.3.  I do not know if it's a better idea to pull the Microsoft Store distribution entirely or not.  But something needs to be done if it is to be kept such that the latest version of NVDA is always presented there.
### Actual behavior:
N/A

### Expected behavior:
N/A

**Comment by cary-rowen** [comment]
This should be removed from the 2023.1 milestone

**Comment by michaelDCurran** [comment]
I have now made NVDA hidden / unavailable in the Windows Store. NV Access currently has not got the time / resources to sufficiently test this package alongside our normal updates unfortunately, and I'm sure the community would agree that there are other much higher priority issues. We can very easily revisit this decision in future.

**Comment by RuturajL** [comment]
Hi @seanbudd , @michaelDCurran,
I realize this issue was closed a while back. However, Microsoft store has started to allow treditional apps in Microsoft store, things like Google Chrome, Firefox, are already there.
With that, I would request you all to reopen this issue, as having NVDA on Microsoft store can greatly simplify deployment on corporate devices using Microsoft's device management solutions.

**Comment by seanbudd** [comment]
@RuturajL - given this issue was about the Store version being out of date, can you please open a new issue requesting a Microsoft Store version?
we're willing to reconsider it in future, but at the time it was better to have no Store version than an extremely dated version

**Comment by RuturajL** [comment]
@seanbudd , understood, I am opening a new issue as you suggested.
Note that my intention behind this is also to ensure that the store version is also kept up to date, so that all devices where it's deployed to would have updated version of NVDA based on the device management policies configured.
I believe now it's feasible, as treditional apps are being allowed on Microsoft store, which would eradicate the painpoint highlighted above, that maintaining a store version is not feasable.
Not having NVDA on store causes the IT teams to constantly pull installers from NVAccess website manually, make that file go through lot of checks and evaluations etc. This often results in very outdated versions on managed devices.
