### ISSUE TITLE
Add ability to report destination URL of a link

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14535]
### Is your feature request related to a problem? Please describe.

Links on web pages and in emails are often denoted with human-friendly text.  Particularly in an era where users need to be aware of and careful to avoid malicious sites and phishing attempts, it is important to check suspicious URLs before activating them.

### Describe the solution you'd like

I envisage the workflow as:
1. Moving focus to a link in an email or on a web page
2. Press a keystroke.
3. NVDA reports something like "Destination is <url> <title>", eg "Destination is https://www.nvaccess.org/download/ NV Access | Download NVDA"

### Describe alternatives you've considered

It used to be possible to query the status bar of the browser for information like this but this is generally not possible now.

The main workaround I can think of is:
1) Move to the link
2) Press the applications key to open the context menu
3) Activate the "Copy link", "Copy link address" or similar item.
4) Press NVDA+c to read the clipboard.

This is an additional step, and also overwrites the clipboard which isn't always ideal.

**Comment by FelipeZanabria** [comment]
A few months ago, I didn't know that you could open a link in another tab, (CTRL+Enter( and open in a new window (Shift+Enter), so I created a script that copied the link's address by looking at its value. The link value is exposed, but it has been programmed not to be spoken in NVDA, since it is a lot of text.
If you press NVDA+f1 with the navigator object on the link, you can see its address.

**Comment by XLTechie** [comment]
While this is at least seemingly easy to achieve, I wonder what should be the braille experience? I am not a braille user, so have very little idea what would be best here.

**Comment by XLTechie** [comment]
I have implemented this in what I think is a reasonable way. However, I do not want to do a PR for it, until I get an answer to the following question:
What should be the braille experience? I am not a braille user, so have very little idea what would be best here.

Separate commands for braille and speech?

Presumably, it would take longer to read a long URL in braille. So a vanishing message wouldn't be appropriate there, while a ui.message might be fine for speech users.
Would a ui.browseable message be preferable for braille users?
@josephsl @Qchristensen, others . . .

**Comment by josephsl** [comment]
Hi,

Perhaps recycle NVDA+D (announce details) command to announcing anchors? This raises the question about what to do if the link contains annotations.

Thanks.

**Comment by ruifontes** [comment]
For me it will be good a browseable message .

**Comment by XLTechie** [comment]
Should it be a different command for braille, or the same command with 
configurable behavior?

As it stands, I have it done in such a way that if you press the key sequence 
once, it will speak an ephemeral message with the URL and link title.
But if you press it twice, it shows in a browseable message.

For braille, you would have it jump straight to the browseable message.

If it's the same command, it would either need something to configure it, or 
perhaps I would need a second un-mapped command that went to the browseable 
message only, and braille users could re-map the key according to their needs, 
while speech users could retain the two-press functionality.

**Comment by josephsl** [comment]
Hi, I think it would be best to keep the commands the same with both speech and braille presenting the message o the first press and a browsable message on the second press. Thanks.

**Comment by ruifontes** [comment]
I agree with @j

**Comment by Cleversn** [comment]
I know this feature has been implemented already, but for Firefox users, there's always been a keystroke to report a destination: NVDA+numpad 2, which speaks the child object of the focused URL, which contains its destination.

**Comment by XLTechie** [comment]
Not always.
In Firefox, go to, for example: https://letsencrypt.org

Press G, so that you're on the first graphic, which is also a link.

Press NVDA+Numpad2. "No objects inside"

Press NVDA+k in latest alpha. "https://letsencrypt.org/"

**Comment by Cleversn** [comment]
Hi Luke, NVDA+numpad 5 does the job at the graphic link you suggested.

Just to clarify, the only reason I decided to comment is because I got surprised when I saw this new command, as I've always used the object navigator to get the destination of URLs, not trying to diminish your work. In any case, in MS Edge this new command will be quite useful.

**Comment by XLTechie** [comment]
True enough. However, that's different commands for different kinds of elements. 
And in different places, since that doesn't work everywhere. For example, one of 
those works on graphics links, but not on actual links. The first one you 
pointed out works on actual links, but not graphical links.

So while it is true that this information was available before, at least some of 
the time, as @Qchristensen pointed out when opening this issue, it hasn't 
been available in a standardized way. Nor in a way that was very friendly to new 
users.
