### ISSUE TITLE
Feature request: 'Reports the text of the comment where the System caret is located.' supports opening in a browsable dialog

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14628]
### Is your feature request related to a problem? Please describe.
Sometimes the text of comment is too long, in order to understand, we may need to navigate by sentence or by word.
### Describe the solution you'd like
Press NVDA +Alt +C twice to display a browsable dialog to contain the text of comment.
### Describe alternatives you've considered
None
### Additional context
I would like to open a PR myself to contribute to this.

**Comment by Adriani90** [comment]
I just specify, this is for Microsoft word. Right? Because in Microsoft Excel you can press shift+f2 to read the comment. I think this might be also a good work around in MS Word, but you always right click or press the application key on the position of system carret and edit the comment, which brings you into an accessible edit field where you can read the comment.

**Comment by cary-rowen** [comment]
You are right, and the new version of sidetrack (alt+f12) in Word can also be implemented, but obviously more steps are required.
If this is implemented, it should also be implemented in Excel for consistency, otherwise it may cause confusion for users, ie: why doesn't it work in Excel?

**Comment by dkager** [comment]
I would really like this feature. Do you still plan to do a PR? Else I might pick it up. One caveat is that reporting of Modern Comments isn't very useful right now, because it only reports the author and date.

**Comment by Adriani90** [comment]
@dkager    There is #15987 but still in a draft stage and I think it adresses only the old style comments.
