### ISSUE TITLE
What should multi line break do in the Document paragraph function

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#14638]
### Is your feature request related to a problem? Please describe.
It is related to a behavior which may not be what is desired.
Currently, when document paragraph is set to multi line break single line breaks are also stopped at.  Thus, there is no way to know except to check at every stop whether you are stopping at a multi line or a single line break.  This makes the feature, as implemented redundant, as far as I can tell..
### Describe the solution you'd like
The multi line setting should only stop at two or more blank consecutive blank lines.  There may be a reason I am unaware of that the feature works as it does so this is a suggestion and a question as to the change I am suggesting.
### Describe alternatives you've considered
I haven't considered any.

**Comment by Qchristensen** [comment]
Which program have you encountered this in?  And can you clarify exactly what you are doing please?  I just did the following:

1) Set paragraph style to "Multi-line break"
2) Open Notepad
3) Type "The quick" then press enter once.
4) Type "brown fox" then press enter twice
5) Type "jumped" then press enter
6) Type "over" then press enter
7) Type "The lazy" then press enter twice
8) Type "Dog" then press enter

Press control+up arrow, and the caret will stop at "Dog", "Jumped" and "The quick".  This is the expected behaviour.  In order to create that "single blank line", you need to press enter twice in a row.

If paragraph style was set to "Single line break" then it would stop at every line, because I pressed enter at the end of every line of text.  This "single line break" paragraph style is similar to how Microsoft Word behaves.  "Multi-line break is similar to how many people "expect" paragraphs to work.

Is that the behavious you are encountering?  If so, it is working as expected.

**Comment by Gene703122** [comment]
The behavior you described is correct.  I didn't understand how the feature was supposed to work and it was clarified on an NVDA users' list.  I am not familiar with documents where one return indicates a paragraph and I thought multi line referred to more than one blank line.  I will close the ticket if I can.  I haven't used Github enough to know if I can.
