### ISSUE TITLE
Add link to "Get Help" page to NVDA help menu

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14631]
### Is your feature request related to a problem? Please describe.

Some users don't know resources such as the mailing lists or training material exist.  Having these available from NVDA"s Help menu might make them easier to find for more users.

### Describe the solution you'd like

The Help menu currently contains:
- User guide
- Commands quick reference
- What's new
- NVDA web site
- License
- Contributors
- Welcome dialog
- Check for updates
- About

This is already quite a bit.  My suggestion is:

- "About" already mentions the license, with a suggestion that you can view the license from the help menu.  I propose removing "License" and "Contributors" from the help menu, and adding buttons or links for them on the about page.
- Note the presence of the Quick Start Guide in the User Guide entry
- Note the presence of the license and contributors in the "About" entry
- Add a new entry "Get Help (Training and support)" which links to https://www.nvaccess.org/get-help/

The Help menu would then contain:
- User guide (with Quick Start Guide)
- Commands quick reference
- What's new
- NVDA web site
- Welcome dialog
- Get Help (Training and support)
- Check for updates
- About (version, license, contributors)

This does make some menu items long, however the pertinent information ("User Guide" and "About") is still read first by NVDA.  In quick testing, for low vision / magnification users, the magnification level would need to be over ~800% before that length of text won't fit on screen.  At that level of magnification, they will be experiencing that in many places.

### Describe alternatives you've considered

There are numerous ways this menu could be changed.  These are about the simplest, and most immediate I can think of which are likely to have the most positive impact.

**Comment by NZGene** [comment]
It would make sense, from a new users perspective, if under the help section in NVDA there was a get-help menu. People are always enquiring about email groups, synthesisers, addons, training material and so on as these questions come up quite often.

The thing that I would say that is also missing from the get-help page is about NVDA certification; so that people can find NVDA certified people from around the world who may be able to help them.

The closest thing at the moment is the NVAccess menu that points to the NvAccess website, but people don't necessarily look around on the website to get help. It needs to be very easy to find, such as being able to click on the get-help section in NVDA, which takes you straight through to the NvAccess get help page. In NVDA, you want to be able to go to help, then go to a get-help page (rather than poking around on the website for this same information). For example, when looking for information on email groups, synthesisers, addons and training material it would be so much easier to simply click on help, and then NvAccess get-help and be taken straight through to the NvAccess get-help page.
