### ISSUE TITLE
Error using eSpeak-ng on NVDA2023.1beta1 in Italian language.

### ISSUE THREAD

**Issue by Christianlm** [nvaccess/nvda#14650]
I'm not sure if this problem affects other languages...

### Steps to reproduce:

1. From voices settings switch to eSpeak-ng synthesizer.
2. Select Italian language.
3. try writing and reading the single number 0 in any text field: e.g. in notePad digits the number 0 and press up or down arrow.

### Actual behavior:

the following error occurs and speech synthesis stops:

ERROR - synthDrivers._espeak.BgThread.run (15:21:50.131) - synthDrivers._espeak.BgThread (900):

Error running function from queue

Traceback (most recent call last):
  
File "synthDrivers\_espeak.pyc", line 196, in run

  File "synthDrivers\_espeak.pyc", line 223, in _speak

OSError: exception: access violation reading 0x0000000B

IO - inputCore.InputManager.executeGesture (15:21:52.548) - winInputHook (6588):
Input: kb(laptop):NVDA+f1

### Expected behavior:

The synthesizer should read the digit zero correctly without errors

#### NVDA installed/portable/running from source:

NVDA Installed and portable.
#### NVDA version:
NVDA2023.1 BETA 1.
#### Windows version:

Windows 10 2004 (AMD64) build 19041.1348
#### Does the issue still occur after restarting your computer?

Yes.
#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes.

**Comment by nvdaes** [comment]
Hello: I cannot reproduce this in Italian neither in Spanish using Windows 11 22H2 (10.0.22621) workstation AMD64

Of course I assume that you don't have dictionaries affecting eSpeak-NG or custom variants. These are things not considered specifically in NVDA issues, but just to discard possible causes you may want to reply about this.
Also, I wonder if this also happens when using continue reading or just when pressing arrow keys, and if speech symbols may affect this, and what happens if language detection is active and you try to type in an edit box if English is detected.
Also if you see differences if Italian is set as the language itself and if you set language to Windows default using Windows in Italian.
I don't have any knowledge about eSpeak, so apologies if some of these questions are not relevant.

**Comment by Christianlm** [comment]
@nvdaes each aspect is relevant in this case, thanks to point out.
I tried a clean installation of NVDA, so no dictionary or variant is in use.
Yes, the error  happens in continue reading too.
I changes the language from italian to Default Windows language in general settings, the error still ocour.

**Comment by nvdaes** [comment]
Tomorrow I"ll test on Windows 10.Enviado desde mi iPhoneEl 19 feb 2023, a las 15:01, Chris ***@***.***> escribió:﻿
@nvdaes each aspect is relevant in this case, thanks to point out.
I tried a clean installation of NVDA, so no dictionary or variant is in use.
Yes, the error  happens in continue reading too.
I changes the language from italian to Default Windows language in general settings, the error still ocour.

**Comment by CyrilleB79** [comment]
I can reproduce this issue (Windows 10 2004 (x64) build 19041.388).

I have tried eSpeak with more than 20 languages and only Italian seems affected.

* The error occurs when the TTS encounters a 0 digit that should be read "zero", i.e. in strings such as "0 files", "stage 0" or just "0".
* The issue does not occur if "zero" is written with letters instead of a digit.
* The issue does not occurs either if the digit 0 is included in an expression where it is not pronounced "zero", e.g. in numbers containing 0 such as "10", "300", etc.

Cc @seanbudd: this issue is affecting current beta.

**Comment by nvdaes** [comment]
I've test this on Windows 10 22H2 (10.0.19045) workstation AMD64. And the error happens when Italian voice of eSpeak-NG is selected, regardles of the language of NVDA interface, at least if it's set to Spanish.
This doesn't happen when reading a single character, for example, with right arrow.
I think that this will also happen on Windows 11 setting the voice to Italian, regardless of tthe language of NVDA.
I'll test this later on Windows 11.

**Comment by nvdaes** [comment]
Hello:

Finally, I confirm this error on Windows 11 22H2 (10.0.22621) workstation AMD64:

- It doesn't deppend on NVDA's language. However it's related to the Italian voice of eSpeak-NG.
- - Id doesn't happen when 0 is read as a character, for example, when pressing right arrow. Instead it occurs when 0 is read as if it was processed by dictionaries, that is, when it's not read as a single character.

**Comment by josephsl** [comment]
Hi, if all of this is true, I guess we might as well alert eSpeak NG project. Thanks.

**Comment by seanbudd** [comment]
An issue has been created: https://github.com/espeak-ng/espeak-ng/issues/1660
