### ISSUE TITLE
Punctuation when you read per word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1468]
**Reported by AlexTrial91 on 2011-04-21 15:12**
Currently, when you read per word, if symbol level is on "none" or the other new level as "some", when we are trying to read comma and colon NVDA says nothing as if a symbol which doesn't understand and forces user to press left arrow then right arrow to read this or use the NVDA cursor.
It would be wonderful if you could develop an option and yet better if it could be by default in NVDA. This we would permit to read all punctuation per word although the symbol level is on "none" or "some".

**Comment by bhavyashah** [comment]
@jcsteh The original author of this ticket is now out-of-reach, but he did provide counter-arguments to your initial stand in his follow-ups https://github.com/nvaccess/nvda/issues/1468#issuecomment-155289552 and https://github.com/nvaccess/nvda/issues/1468#issuecomment-155289555. Could you please highlight your present stand on this ticket and triage it accordingly? CC @brian1gaff

**Comment by jcsteh** [comment]
I still think this is counter-intuitive. Obviously, when dealing with characters, reading all symbols is the only thing that makes sense, since otherwise, nothing would be read. However, I don't see why words should be special.

Note that we already read symbols if the word only contains one character and that character is a symbol, since otherwise, we'd report nothing. However, this doesn't work if there are trailing spaces. That's covered by #5133.

Closing as won't fix.
