### ISSUE TITLE
Contributors file do not open

### ISSUE THREAD

**Issue by ruifontes** [nvaccess/nvda#14725]
### Steps to reproduce:
1 - Open NVDA menu;
2 - Go to Help submenu;
3 - Choose Contributors and press Enter.

### Actual behavior:
Is displayed a message informing that "Bloco de Notas", the portuguese name of notepad, is not a valid file name
or an error stating that file C:\SESSION:BnVnonDQhUCUNfDwgxtw+QE6QzpcUHJvZ3JhbSBGaWxlcyAoeDg2KVxOVkRBXGRvY3VtZW50YXRpb25cY29udHJpYnV0b3JzLnR4dAAAAQUAAAAB3FvMAgAAAAAAAA==.txt was not found.

### Expected behavior:
The contributors.txt should be open in notepad.exe

### NVDA logs, crash dumps and other attachments:
The only reference to notepad is the same that happen when opening the notepad app and is:
DEBUGWARNING - RPC process 300 (Notepad.exe) (16:19:29.306) - Dummy-6716 (11240):
Thread 12908, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 169:
Not installing IA2 support as  process is suspendable

#### NVDA installed/portable/running from source:
Only happens in installed versions.

#### NVDA version:
Only tested with NVDA 2022.4, 2023.1 RC and last alpha-27830,d2d4bfce (2023.2.0.27830)

#### Windows version:
It seems that only occurs on Windows 11 22h2 build greater 22621

#### Name and version of other software in use when reproducing the issue:
NA
#### Other information about your system:
NA
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NA
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by CyrilleB79** [comment]
Thanks Rui for opening this issue.

As an additional information, this was discussed in [this thread](https://groups.io/g/nvda-devel/topic/tesseract_ocr_addon_doesn_t/97605313?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,97605313,previd%3D1678971409405815056,nextid%3D1653319225872143015&previd=1678971409405815056&nextid=1653319225872143015) on NVDA devel mailing list.
The issue comes from the use of `os.startfile` to open text files with Notepad. This issue was first discovered in some add-ons using the same technique to open text files (Tesseract OCR, NVDAExtensionGlobalPlugin and Thunderbird+4).

Cc @paulber19, @RPTools-org.

**Comment by Adriani90** [comment]
Note that a similar issue is also happening when trying to open the license file from the help menu. The file is not being found and it asks me if I want to create a new one. If I press "yes", the editor opens but the license file is empty.

**Comment by XLTechie** [comment]
Note that this issue was discussed in some detail, with tests being done to narrow its possible causes and range of effected cases, in this [mailing list thread](https://nvda.groups.io/g/nvda/topic/98159402). See there for testing examples and results.

**Comment by ruifontes** [comment]
It seems that solution only is valid for text files created by Notepad, like the attached file.
For text files created by NVDA, like NVDA.LOG, it will not work.
[test.txt](https://github.com/nvaccess/nvda/files/11200426/test.txt)

**Comment by paulber19** [comment]
Sorry Rui, but I don't see the same thing.
I placed the test.txt file under "c:\" and ran the command:
os.start(r"c:\test.txt, operatio="edit") in NVDA's python console.
I got the error.
Putting the file in "c:\Programm files (x86)" I don't get the error.
Best regards.
Paul.

**Comment by paulber19** [comment]
Another information.
The error does not occur if the command is run in Python's python console.
For my add-on, While waiting for a solution, I chose to use "wordpad" to 
open text files and the run command from the subprocess module.
It would still be easier if the installed NVDA was run with 
administrator privileges, since in this case the error does not occur.
Best regards.
Paul.
