### ISSUE TITLE
if we have 4E57 it says 4 power 10 – 57

### ISSUE THREAD

**Issue by pradnya13705** [nvaccess/nvda#14730]
Hello NVDA Team 

our team is facing issue related to GUID number. below is the screen shot
![image](https://user-images.githubusercontent.com/84022908/226567480-9d784e37-24ed-488f-93d7-d148319fddac.png)

In highlighted number if we have 4E57 it says 4 power 10 – 57 and this id system generated.

we are using below version of NVDA
![image](https://user-images.githubusercontent.com/84022908/226568578-6ef751ce-13aa-4dc4-9a71-435b6797a76b.png)

Can you please  look in to this 
Thanks

**Comment by CyrilleB79** [comment]
Hello @pradnya13705 

And welcome to NVDA.

If you want your issue to be looked at, you should follow the [issue template](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=bug_report.md); you may modify your initial description to conform with this template.
Also, keep in mind that many NVDA developers (from NVAccess or contributors) are blind. Thus please provide the requested information as a text description and not only through screenshots. Thanks.

Regarding this issue, you should also indicate the speech synthesizer and the voice used.
It's very llikely to be an issue with the speech synthesizer and thus has to be reported to them.
This type of issue has already been reported with Microsoft for OneCore English voices (David, etc.). If you are in the same situation, please report the issue directly to Microsoft.

Note: If you confirm that the issue is coming from the voice you should have the same issue with Microsoft Narrator.

**Comment by seanbudd** [comment]
Welcome @pradnya13705 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images.
- This is very likely a problem with the implementation of the speech synthesizer, as a starting point please submit feedback to the authors of the synthesizer to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
Yeah this is most probably an issue comming from the vendor of the synthesizer, not related to NVDA. I cannot reproduce with eSpeak for example.
