### ISSUE TITLE
Improve documentation for "Enable loading code from developer working directory"

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#14773]
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
due to my lack of knowledge I changed the configuration:
Enable code upload from developer working directory
and I tried to use the code I had pasted in the folder.
What I expected to happen did not.
After trying several alternatives I remembered that it was only necessary to restart nvda for the code to run.
Several curious users like me are delighted that shat gpt can create codes for nvda, and with a few adjustments this becomes a feature for nvda, but for not even one experience they are caught in this small trap, but think that their homemade experiment did not work.
I'm laughing now at my quote.
### Describe alternatives you've considered
I would like just a little text in the option:

Enable code upload from developer working directory

to inform that the option takes effect after restarting nvda.

You can change this misspelled text at will.

**Comment by CyrilleB79** [comment]
You write:
> this setting takes effect after restarting nvda

That's not completely true. What is more exact is that that setting takes effect whenever NVDA loads plugins, code that is when NVDA starts or whenever you press NVDA+control+F3.

**Comment by fernando-jose-silva** [comment]
thank you very much, thank you for teaching me one more shortcut key. I believe the help message is very important, feel free to suggest the most suitable text.Enviado do meu iPhoneEm 2 de abr. de 2023, à(s) 17:13, Cyrille Bougot ***@***.***> escreveu:﻿
You write:

this setting takes effect after restarting nvda

That's not completely true. What is more exact is that that setting takes effect whenever NVDA loads plugins, code that is when NVDA starts or whenever you press NVDA+control+F3.

**Comment by CyrilleB79** [comment]
Explaining when/how code can be loaded would overload the advanced settings panel in my opinion. It may be expected that advanced settings options may require a more detailed description. But I think that this detailed description would better fit in the User Guide (easily reachable with context help F1). Moreover, for this option, it would be the opportunity to rewrite its description since the description is still comparing with the old (pre-2019) behavior when the scratchpad did not exist.

@fernando-jose-silva , would you be satisfied if the information you are requesting goes in the user guide's description of this option rather than directly in the option's label in the advanced panel?

**Comment by fernando-jose-silva** [comment]
Yes, thank you.
