### ISSUE TITLE
Braille: switch showing selection with dots 7 and 8 on/off

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#14948]
### Is your feature request related to a problem? Please describe.
Selected text is shown with dots 7 and 8 in braille. Problem is that reading of selected text is quite slow and difficult.
### Describe the solution you'd like
Possibility to switch selection on/off from settings and with input gesture.
### Describe alternatives you've considered
Adding new braille setting with feature flag and input gesture.

**Comment by irrah68** [comment]
I have noticed that when I press NVDA+Down and try to read from my Braille display at the same time when the speech synthesizer is talking, it is quite a difficult to read Braille because of these extra dots 7 and 8 being up all the time. It is a good idea to add a new feature, where an user can decide and choose if she/he wants to read Braille without dots 7 and 8 when reading contiguously.

**Comment by burmancomp** [comment]
I can try to implement this.
