### ISSUE TITLE
Spans within divs that have ids will move scroll the page down when using navigational arrows

### ISSUE THREAD

**Issue by scollinsepic** [nvaccess/nvda#14944]
### Steps to reproduce:

Code with id on div:
`<div id="Weird">`
`    <div>`
`          <a href="#">Back</a>`
`    </div>`
`    <span>"Hey"</span>`
`    <div></div>`
`</div>`

Example with id on div:
<div id="Weird">
    <div>
          <a href="#">Back</a>
    </div>
    <span>"Hey"</span>
    <div></div>
</div>

Code without id on div:
`<div>`
`    <div>`
`          <a href="#">Back</a>`
`    </div>`
`    <span>"Hey"</span>`
`    <div></div>`
`</div>`

Example of without id on div:
```
<div>
    <div>
          <a href="#">Back</a>
    </div>
    <span>"Hey"</span>
    <div></div>
</div>
```

When a span is placed within a div that doesn't have an id attribute id attribute. The page must be large enough to have some sort of scrolling behavior. 

### Actual behavior:
When using the down/up arrow keys to navigate, when the focus is on the span, the screen will move to a lower spot on the page. When focus is off the span, the screen will move back to the previous spot on the page where focus should have been.

### Expected behavior:
The screen should not scroll down/"jump" to a different spot on the page when reading the span element.

#### NVDA version:
2022.2.2

#### Windows version:
Windows 10 Enterprise

#### Name and version of other software in use when reproducing the issue:
Chrome and Firefox

#### Does the issue still occur after restarting your computer?
Yes

**Comment by seanbudd** [comment]
Welcome @scollinsepic ,

We are unable to process this issue.
It is unclear what the issue is with the behaviour. NVDA is expected to scroll with navigation.
Could you please provide a sample [codepen](https://codepen.io/) that we can use to test with, and more clear steps to reproduce? Where exactly does the scroll move to, and what is the expected position instead?

**Comment by Adriani90** [comment]
I think this is due to the way scrolling is implemented in NVDA browse mode. I cannot proove whether the screen scrolls or not because I cannot see it, but I guess this is intended behavior.
@jcsteh, @gerald-hartig maybe you have any suggestions here, or update the triaging. I am not sure the example provided in the description is a valid minimal test case.

**Comment by jcsteh** [comment]
1. The test case provided is insufficient to reproduce the bug.
2. The expected and actual behaviour is not sufficiently clear.
3. The reporter was asked to provide this information over 18 months ago, but there has been no response.

Therefore, I would suggest that this should be closed, though I don't know what the triage policy is in this case.
