### ISSUE TITLE
Add-on Store: First press of Ctrl+Tab shouldn't be improperly announced

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#14986]
### Steps to reproduce:

* Open the Add-on store.
* Press `Ctrl+Tab`.

### Actual behavior:

NVDA speaks:
```
tab control
panel
```

### Expected behavior:

NVDA should speak:
```
Updatable add-ons  tab  selected
```

Since that's the tab that has been changed to.

### Additional note:

Subsequent presses of `Ctrl+Tab` do speak the selected tab, but the first one is never spoken.

### System configuration

NVDA portable, version alpha-28372,94715243
Microsoft® Windows® Operating System version 10.0.19041.2311

**Comment by seanbudd** [comment]
This could potentially be fixed by always manually focusing the selected tab's control when performing `ctrl+tab`, but this would make #14987 invalid

**Comment by XLTechie** [comment]
IMO, it's the result that matters. My first solution in #14987 is a better end 
result than solving this would be.

**Comment by CyrilleB79** [comment]
For reference in Windows Explorer files properties dialog, we have:
* if an item in the tab page is focused (e.g. Hidden checkbox, or Read-only checkbox), alt+tabbing put the focus in the new tab page
* if the tab header (e.g. General, Shared) is focused, alt+tabbing put the focus on the next tab header and not in the tab page.

IMO, this behaviour is a good UX and should be copied in the add-on store.

**Comment by CyrilleB79** [comment]
@seanbudd would this PR deserve being integrated in NVDA 2023.2? For now it is not included in its milestone.

Of course it's not a critical bug at all.

However, I imagine that ctrl+tab may be the preferred way to change tab in the store. Leaving this bug in NVDA 2023.2 make the discovery of the store less easy for general users and would also lead to a bad first impression.

**Comment by XLTechie** [comment]
I agree with what @CyrilleB79 describes in https://github.com/nvaccess/nvda/issues/14986#issuecomment-1600916872. This is the desirable behavior.
(Although I believe ctrl+tab is meant in the comment, where alt+tab is used)

**Comment by CyrilleB79** [comment]
> I agree with what @CyrilleB79 describes in [#14986 (comment)](https://github.com/nvaccess/nvda/issues/14986#issuecomment-1600916872). This is the desirable behavior. (Although I believe ctrl+tab is meant in the comment, where alt+tab is used)

Thanks. I have updated my previous comment for clarity.

**Comment by seanbudd** [comment]
This is a minor bug with no clear solution or easy fix - I don't think it should hold up the release

**Comment by ABuffEr** [comment]
Hi,
it's not resolved yet. And it'll continue to give a bad impression in incoming 2024.1.
Personally I agree with Cyrille's observations, but add also that Windows Explorer not keeps focus moving among tabs. So I suppose that we'd like to get focus on add-on list, as when opening the store.
This result, though, seems not so trivial to get working, because adding self.addonListView.SetFocus() to page changed handler NVDA reads the list names inconsistently, and nothing else of the updated panel.
By contrast, adding self.addonListTabs.SetFocus() seems to work well, always focusing on tab title (instead of say "tab control panel").
Moreover, due to filters presence before the add-on list, and the fact those always resets their status, I'm not totally convinced that focusing on add-on list when opening the store is the best choice, but it's irrelevant at this stage.

**Comment by Adriani90** [comment]
The filter reset issue is not ideal at all, I filled #15947 for that. 

In my view it would be an improvement to redirect the focus automatically to the tab area when pressing ctrl+tab if this is the only way of solving this particular issue.

**Comment by XLTechie** [comment]
I agree with @Adriani90. Any solution is better than now.

**Comment by Adriani90** [comment]
Closing as fixed in #15988.
