### ISSUE TITLE
Add-ons can be run when last tested version is major than last existing NVDA version

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#15050]
### Steps to reproduce:
1. Install an add-on.
2. Set last tested version to 9999.0.0.
3. Restart NVDA.
### Actual behavior:
The add-on will work.
### Expected behavior:
The add-on should be disbled so that it can be easily removed.
### NVDA logs, crash dumps and other attachments:
n/a
#### NVDA installed/portable/running from source:
All
#### NVDA version:
All
#### Windows version:
All
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This happens in all NVDA versions.
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by nvdaes** [comment]
Discussed with @Qchristensen 
I proposed this since there are people sharing add-ons with versions like 2025.1, greater than the current NVDA API version. This may cause that someone install these add-ons without considering that they may cause issues. Now, it's possible to skip compatibiluty, so these addons should be disabled.
I may work on this.

**Comment by seanbudd** [comment]
Can you explain why this should force an add-on to be disabled?
What determines a valid last tested version?

Note that the case described in the title is not valid. NVDA 2023.1 should be able to run add-ons with the last tested version of 2023.2.

**Comment by nvdaes** [comment]
Another possibility is tho show these ad-ons as incompatible but without the possibility of enabling them. I'll try to create a PR and I'll see what I can do seeing the code.

**Comment by seanbudd** [comment]
>
Another possibility is tho show these ad-ons as incompatible but without the possibility of enabling them. I'll try to create a PR and I'll see what I can do seeing the code.

Again, the case described in the title here does not describe an incompatible add-on. A version such as 2025.1 or 9999.0 can be valid from the view of an older version of NVDA.
Please provide a clear definition first on what you consider an invalid "last tested version" that should be marked as incompatible.

I would hold off on a PR - we are yet to triage and support this change. A case on why this is necessary or should be handled by NVDA is required.

**Comment by nvdaes** [comment]
OK Sean. I'm thinking how to write this here.

**Comment by nvdaes** [comment]
There are add-ons declaring that they have been tested with non existing versions of NVDA, like 2025.1. If they are installed, they will be presented as compatible add-ons but 2025.1 is not an API version. This may encourage people to release add-ons, or even changing the manifest for add-ons published by othe people, so that they can be installed and presented as compatible when in fact the API version doesn't exist.
If an add-on declares that the last tested version is 2023.1, it should work when NVDA 2023.2 is released, but in this case the last tested version will be minor than API current version.
Hope this is better explained.
I won't make a PR if this is not valid.

**Comment by seanbudd** [comment]
@nvdaes - but how can NVDA determine what is a released version of the NVDA API without a network connection to fetch a list of available API versions?

**Comment by XLTechie** [comment]
@nvdaes How does NVDA 2023.2 know, that NVDA 2025.1 isn't available?

E.g. Somebody in 2025 decides to use an old version of NVDA 2023.2, with an 
add-on which Has minimum of 2019.3.0 and lastTested of 2025.1.0.
This is perfectly valid from the add-on's point of view. Why should NVDA 2023.2 
not be able to run this add-on?

I think the only way you could test this with validity, would be to have NVDA 
compare the current system date idea of the year, against the first part of the 
lastTested key.

That way, if the lastTested said 9999.1, but it was only 2023, NVDA would know 
that version 9999.1 of NVDA hadn't been released yet. This only works, as long 
as NV Access never releases a next year's version in the current year.
That is, as long as 2024.1 can not possibly be released before January 1, 2024.

**Comment by nvdaes** [comment]
I said api current version but I should say last existing api version, and in fact nvda would need to connect to a network.Enviado desde mi iPhoneEl 23 jun 2023, a las 6:46, Sean Budd ***@***.***> escribió:﻿
@nvdaes - but how can NVDA determine what is a released version of the NVDA API without a network connection to fetch a list of available API versions?

**Comment by nvdaes** [comment]
for flexibility and bc independent of years, nvda should consult the addondatastore transform repo. If this is expensirve, this can be closed.Enviado desde mi iPhoneEl 23 jun 2023, a las 6:55, Luke Davis ***@***.***> escribió:﻿
@nvdaes How does NVDA 2023.2 know, that NVDA 2025.1 isn't available?

E.g. Somebody in 2025 decides to use an old version of NVDA 2023.2, with an 
add-on which Has minimum of 2019.3.0 and lastTested of 2025.1.0.
This is perfectly valid from the add-on's point of view. Why should NVDA 2023.2 
not be able to run this add-on?

I think the only way you could test this with validity, would be to have NVDA 
compare the current system date idea of the year, against the first part of the 
lastTested key.

That way, if the lastTested said 9999.1, but it was only 2023, NVDA would know 
that version 9999.1 of NVDA hadn't been released yet. This only works, as long 
as NV Access never releases a next year's version in the current year.
That is, as long as 2024.1 can not possibly be released before January 1, 2024.

**Comment by seanbudd** [comment]
It's not expensive - it's just not valid behaviour. NVDA shouldn't require an internet connection to install add-ons.

**Comment by XLTechie** [comment]
I'm not necessarily opposed to this, assuming that the fallback is that when NVDA is running offline, it should accept installation of these add-ons.
It shouldn't be that expensive to load the JSON on NVDA start-up, with a secondary check (if that one failed) at time of installation attempt.

Of course, any user who is really determined to install one of these, can activate airplane mode for a minute.

**Comment by XLTechie** [comment]
@nvdaes I just re-read the issue, and it seems you are talking about checking at every runtime, not just on install.
**I do oppose that.**

Once a user goes through the trouble to change something in his own installation of the software, trying to fight against it is intrusive, and ultimately fruitless. NVDA is open source. At best, you're just moving the goalpost--there will always be another workaround that someone will make available, that will overcome anything you try to do.

__________
I am in favor of blocking installation for these (if we can, and only to the extent that we don't go crazy with it), but not in favor of keeping them from running if a user manages to get them installed, or changes the manifests after installation.

**Comment by nvdaes** [comment]
Luke wrote:

> @nvdaes I just re-read the issue, and it seems you are talking about checking at every runtime, not just on install.

My goald is to prevent that people who has installed an add-on shared with an invalid version can be protected against this. Many people may think that this is not bad or dangerous.
But I think that this would require an internet connection and, as Sean wrote, this is not a valid behavior.
@seanbudd Feel free to close this as not valid if you think that there's not a better solution.

**Comment by nvdaes** [comment]
Another approach maybe just adding a checkbox to enable the button to install add-ons from external sources, and making a warning if someone click on an add-on not installed from the store, since add-ons sent to the store have valid versions when they are published.
I know that this maybe things considered silly or non valuable since they don't prevent to install add-ons, but this is just what comes to my mind now, and may inform people that external sources, in some cases, maynot be secure. This may also encourage authors to send their add-ons to the store.

**Comment by nvdaes** [comment]
Or an easier solution maybe to add, in the label of the External source button, a text explaining that add-ons from external sources may contain invalid API versions.

**Comment by nvdaes** [comment]
Also, a tab to show add-ons installed from enxternal sources maybe added, since an addonid.json doesn"t exist in the addons folder.

**Comment by ruifontes** [comment]
@nvdaes, Tiflotecnia release all Vocalizer voices as add-ons with last tested version set to 2099.4.0.
The reason is the absence of any code in those add-ons... They contain only voice data...
Other way, we have to modify more than 250 add-ons each year...

**Comment by nvdaes** [comment]
I think that there"s nothing I can add until NV Access evaluates this question.

**Comment by josephsl** [comment]
Hi,

The following is quite philosophical:

The issue being discussed has to do with the practice of declaring a far future date/year as last tested NVDA version in add-on manifests, which was introduced in 2019 when minimum and last tested version manifest keys were introduced. This practice stems from the belief that add-on code can survive future NVDA changes such as Python version upgrades with little to no problems, something that was tested before (2019) and will be tested again in a few months.

In our minds, the image of a screen reader code that allows add-ons from different eras to coexist without problems is a "gift" from heaven. But humans seek change and wants to experiment, creating new ideas and improving existing practices, and transform and redefine the idea of what is acceptable and can coexist. Developing NVDA itself and its add-ons is a good example of humans seeking change.

Suppose a system somehow says, "from now on I'm going to restrict how something operates." How will components (people, for example) react? Some would go with the flow, some would leave the system, and some would find workarounds. Would the system know and anticipate these reactions? Yes and no: yes, because some components of the system would create backup plans, knowing that other parts may not like the idea of restricting things. No because unless the system is so perfect, it cannot predict the function and form of all possible and real resistance. Because the idea of a perfect system is ideal at best (some societies tried replicating a perfect utopia where everything worked exactly as planned but didn't last long), there are bound to be issues and flaws that can be used to undermine its goals.

NVDA is not a perfect system, and so are add-ons. If we do restrict add-on manifest keys and how NVDA operates (in this case, do not allow add-ons with far future dates as last tested version key to be used), we can communicate a message that says, "we are perfectionists and so should be our creations." We cannot guarantee perfection because first and foremost, humans are imperfect, and because of our own imperfection, our creations and defenses will be imperfect and inaccurate at times. Our imperfection is a major (philosophical) reason why we find issues with NVDA and submit pull requests, because deep within, we know that software is both wonderful and imperfect (no software, including screen readers, apps, and operating systems are perfect).

Why do then add-ons exist? Because it helps fill a gap within a system (NVDA screen reader) it intends to reside within, assist, and sometimes resist. And because add-ons are created by humans, they also come with and communicate their intentions, ideas, and imperfections. Telling NVDA to not run add-ons marked as "compatible" with far future releases, or the solution of marking add-ons from external sources as potentially insecure is an attempt at masking NVDA's own imperfections.

Therefore, I'm opposed to the proposal. Some would say that having a store is better than nothing or it is better (in the long term) to manage add-on manifests better. But restricting add-ons solely based on manifest keys, a human creation (really) can negatively affect NVDA's reputation - striving for perfection, only to be shown the system can be resisted and overcome by patching NVDA code at runtime (let us not forget that Python code can be patched easily at runtime, and this fact is literally used by some add-ons to do their work).

Thanks.

**Comment by nvdaes** [comment]
@josephsl, note that my last proposal is not to restrict the execution of any add-on, but just let people know that maybe bad or dangerous to install add-ons with last tested version that doesn"t exist when the add-on was published. This doesn"t allow that the corresponding addon is marked as incompatible and shown in the incompatible addons tab. Addons installed from source can or not have invalid or non existing last tested version, that is, they are a superset of potential addons which contain invalid metadata according with store requirements. This may not be known by some people. As far as I know, even operative system may ask users if they should be informed when installing software whose origin is not an official store. Since addons installed from external source may contain invalid last tested version, and then they may not be presented in the incompatible tab, my proposal is to show them in an External source tab so that they can be removal, and add info in the button or in the user guide warning that the security offered from the store is not the same that external sources may provide.

**Comment by nvdaes** [comment]
Hi, I realise that the enternal source is a channel and addons can be filtered by this characteristic, so providing an extra tab is useless. Sorry. But I think that some kind of jaring in the button or in the user guideabout security maybe good.Enviado desde mi iPhoneEl 23 jun 2023, a las 20:42, Noelia Ruiz Martínez ***@***.***> escribió:﻿
@josephsl, note that my last proposal is not to restrict the execution of any add-on, but just let people know that maybe bad or dangerous to install add-ons with last tested version that doesn"t exist when the add-on was published. This doesn"t allow that the corresponding addon is marked as incompatible and shown in the incompatible addons tab. Addons installed from source can or not have invalid or non existing last tested version, that is, they are a superset of potential addons which contain invalid metadata according with store requirements. This may not be known by some people. As far as I know, even operative system may ask users if they should be informed when installing software whose origin is not an official store. Since addons installed from external source may contain invalid last tested version, and then they may not be presented in the incompatible tab, my proposal is to show them in an External source tab so that they can be removal, and add info in the button or in the user guide warning that the security offered from the store is not the same that external sources may provide.

**Comment by seanbudd** [comment]
Closing this as won't fix
