### ISSUE TITLE
NVDA does not provide any information when you tab out of a fieldset. 

### ISSUE THREAD

**Issue by dkminimal** [nvaccess/nvda#15052]
### Steps to reproduce:
When a form has a combination of fieldsets and individual input fields. If I tab out of a fieldset  and end up in an input field that is not in another fieldset, the screen reader does not tell me that I am leaving the fieldset. So the screen reader user does not know that they have already left the fieldset. Everything works fine when I tab through the fieldset. The user is informed that they have left a fieldset. 
```html
<form>
  <fieldset>
    <legend>Your address</legend>
    <div class="control">
      <label for="first_name">First name</label><input id="first_name" type="text">
    </div>
    <div class="control">
      <label for="last_name">Last name</label><input id="last_name" type="text">
    </div>
    <div class="control">
      <label for="street">Street</label><input id="street" type="text">
    </div>
    <div class="control">
      <label for="city">City</label><input id="city" type="text">
    </div>
  </fieldset>
    <div class="control">
      <label for="hobbies">Hobbies</label><select id="hobbies" multiple="">
        <option>
          Playing game
        </option>
        <option>
          Travel
        </option>
        <option>
          Swimming
        </option>
      </select>
    </div>   
</form>
```
<img width="748" alt="Form with a grouping and a separate input field" src="https://github.com/nvaccess/nvda/assets/37480671/f96e17e6-ed74-4051-96d9-84083bc40504">

### Actual behavior:
After leaving a fieldset with the Tab key, NVDA doesn't say "Gouping end".

### Expected behavior:
After leaving a fieldset with the Tab key, NVDA should say "Gouping end". This should be the same behaviour as in Browse mode, where NVDA informs you that you have left the fieldset.

#### NVDA version:
2022.4

#### Windows version:
Windows 10
Version 1809

#### Name and version of other software in use when reproducing the issue:
Chrome Version: 114.0.5735.91
Firefox Version: 102.11.0er

#### Other information about your system:
64bits
#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
The experience in focus mode is similar to all other windows applications (e.g. groupings in the ribbon menu of MS Office). NVDA always announce when entering them, but not when leaving them.
In my view this is enough verbosity, there is no useful information for an user from the reporting of "leaving grouping x" in focus mode when pressing tab or shift+tab. This is just unneeded verbosity.

In browse mode though this makes more sense because we can use screen layout to check the visual representation of elements on a page, and for that hearing when entering and leaving a grouping is very useful.

Thus, closing as won't fix.
