### ISSUE TITLE
The caret symbol "^" is not read by default.

### ISSUE THREAD

**Issue by rjjiii** [nvaccess/nvda#15066]
### Steps to reproduce:
1. Start NVDA with default settings.
2. Have NVDA read this sentence: "This is ^not the worst I’ve seen."

### Actual behavior:

1. NVDA does not say "caret" unless the specific symbol is highlighted. 

### Expected behavior:

1. NVDA would say, "This is caret-not the worst I’ve seen." ( https://www.elevenways.be/en/articles/screenreaders-special-characters )
Because the caret symbol was previously said by all major screen readers, it has been recommended as an accessible glyph in tables and lists for notes. For example, this is one of very many pages on the English-language Wikipedia where the symbol is used to indicate a note: https://en.wikipedia.org/wiki/Sgt._Pepper%27s_Lonely_Hearts_Club_Band

### System configuration
Windows 10

#### NVDA version:
2023.1.0.27913

#### Windows version:
Windows 10

**Comment by seanbudd** [comment]
Are you using NVDA for testing?

This is expected behaviour for most symbols. I'd encourage you to read the [symbols pronunciation section](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#SymbolPronunciation) of the user guide.

If you want to change this, you can change the symbol to symbol level "all" and set the symbol to always be sent to the synthesizer.
