### ISSUE TITLE
Add ability to silence NVDA installer startup sound when updating NVDA (request from user)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15110]
### Is your feature request related to a problem? Please describe.

Reporting user (on Mastodon - https://fosstodon.org/@Brynify@dragonscave.space/110685946192113063 ) indicates they don't like having the installer startup sound while updating and would like an option to silence it like the startup sound option.

### Describe the solution you'd like

Could possibly bundle this WITH the startup sound option?

**Comment by josephsl** [comment]
Hi,

One possible way is for core.main function to detect that an update is in progress and disable startup sound, akin to the existing check on whether minimal (-m) startup option is present.

Thanks.

**Comment by Brynify** [comment]
Yes. I was thinking maybe in the general settings, alongside the play sounds when starting or exiting NVDA, another checkbox, play sound when update begins, or something to that effect. This would be a very welcome change.

**Comment by josephsl** [comment]
Hi, as for configuration interface, I think a checkable list would be a good option as it allows people to configure exactly when startup and exit sounds should be played under one settings control. Thanks.

**Comment by ultrasound1372** [comment]
Being able to control them separately would be useful, as I personally do rely on the NVDA startup and shutdown sounds, my own replaced variants of course, for a few purposes including dealing with hangs. But the update sound is quite loud and no amount of sndvol trickery can fix it due to it being a different executable every time. We know that it loads user configuration as the updating NVDA prompt and the installer's UI uses those settings, so being able to adjust this in the general settings dialog should find a way to reach the installer. Or NVDA can pass a CLI option to the launcher to avoid this like it does to automatically engage the update.

**Comment by XLTechie** [comment]
A lot of what I do involves updating installed and portable copies, sometimes 
several times in one session.
I live in an apartment with thin ceilings, and my laptops are plugged into nice 
speakers.

Not a problem for speech (eSpeak, which is rather mid/high heavy), but that 
little song is much more full range, and as I work after what other people 
consider normal hours (i.e. middle of the night), I do worry about waking my 
neighbors.

Unfortunately, if you just hit the keyboard mute while the installer sound 
plays, NVDA fails to update/install.

So I definitely understand and second this request.

**Comment by michaelDCurran** [comment]
Would people be happy if NvDA never played the installer launch music if auto updating from NVDA? I.e. Is this the scenario that is the most concerning? Because in that case we can pass a cli option to the launcher to do this always for updates. Otherwise, if we are talking in broader terms, then we should add the extra UI option.

**Comment by ultrasound1372** [comment]
I think that would make the most sense. If you're auto-updating from NVDA NVDA is already running, which means it reads the dialog about how the setup is loading. Hell you could possibly suppress that too but I think leaving it there makes sense otherwise it might look like something broke, and then suddenly NVDA gets yanked. Hell unless I'm missing something you already pass a CLI option to engage auto-update in the first place, so you could bake this behavior into the handling of that option depending on where exactly you handle it.

**Comment by josephsl** [comment]
Hi, there are two options passed into the new launcher when NVDA update begins: -m (minimal) and –install/--create-portable depending on installed/portable copy flag. I’ thinking we could tweak the launcher code that plays the launcher sound to do something about this situation rather than creating a setting just for launcher sound. Thanks.

**Comment by FelipeZanabria** [comment]
Something that has been forgotten is a request to change the startup sound of the launcher, make it shorter. While that doesn't happen, I can tweak the logo.wav down by about 3 or 4 dB, so it's more level with the rest of the sounds.
If I want to produce a new sound for the launcher, are there any specific requirements?
What I know is that NVDA wavs are mono at 22.5khz. Thank you.

**Comment by Brynify** [comment]
I personally would prefer no sound, not a changed or lowered sound but no sound.

**Comment by XLTechie** [comment]
I think part of the point of the installer sound, is to provide feedback while 
the installer expands its files. For that reason, its length makes some sense.

Many computers are faster now, so it can start talking instantly upon completion 
of the sound playback, but that probably wasn't, and maybe isn't, always the 
case.

**Comment by FelipeZanabria** [comment]
In my latitude 2120 it is not like that

**Comment by haruncetinkaya306** [comment]
I think it would be better not to have such a voice. It does nothing for me.
