### ISSUE TITLE
NVDA is not working properly on Edge and Chrome browsers reads it as Unknow everytime

### ISSUE THREAD

**Issue by VinjamurySatyaPrasad** [nvaccess/nvda#15144]
Hi Team

I am using Win11 OS and NVDA 2023 version. When ever I open my chrome or edge browser and starts NVDA tool its always reads as UNKNOWN --- UNKNOWN it would read the contents properly. However it reads the content perfectly on Firefox browser.

I tried to check this on accessibility enabled sites like www.bbc.com or www.godaddy.com
-->

### Steps to reproduce:
Open any accessibility sites like www.godaddy.com or www.bbc.com and open your NVDA tool and press tab key over the browser(Chrome/Edge) over the above URL's
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
No
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Welcome @VinjamurySatyaPrasad ,

Please fill out the issue template fully. What versions were the browsers you tested this with?

You say here:
>If NVDA add-ons are disabled, is your problem still occurring?
No

Can you confirm you only see this issue when you have no add-ons running? If so, that means this is an issue with your add-ons.

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software

**Comment by VinjamurySatyaPrasad** [comment]
Following is the log file which is in debug mode for your reference.


Can you confirm you only see this issue when you have no add-ons running? I don’t have any addons showing up on my machine.

If NVDA add-ons are disabled, is your problem still occurring? Yes




***@***.***






Thanks and Regards,
V K Satya Prasad

**Comment by Brian1Gaff** [comment]
Do you by any chance have the browser nav add on? This seems to be the 
source of a lot of very bizarre effects.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "VinjamurySatyaPrasad" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, July 14, 2023 5:53 PM
Subject: [nvaccess/nvda] NVDA is not working properly on Edge and Chrome 
browsers reads it as Unknow everytime (Issue #15144)


Hi Team

I am using Win11 OS and NVDA 2023 version. When ever I open my chrome or 
edge browser and starts NVDA tool its always reads as UNKNOWN --- UNKNOWN it 
would read the contents properly. However it reads the content perfectly on 
Firefox browser.

I tried to check this on accessibility enabled sites like www.bbc.com or 
www.godaddy.com
-->

### Steps to reproduce:
Open any accessibility sites like www.godaddy.com or www.bbc.com and open 
your NVDA tool and press tab key over the browser(Chrome/Edge) over the 
above URL's
### Actual behavior:


### Expected behavior:


### NVDA logs, crash dumps and other attachments:

### System configuration
#### NVDA installed/portable/running from source: Installed

#### NVDA version: 2023

#### Windows version: Windows 11

#### Name and version of other software in use when reproducing the issue:

#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their 
behaviors.
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
No
#### Does the issue still occur after you run the COM Registration Fixing 
Tool in NVDA's tools menu?
Yes

-- 
Reply to this email directly or view it on GitHub:
https://github.com/nvaccess/nvda/issues/15144

**Comment by VinjamurySatyaPrasad** [comment]
Hi Brian,

We don’t have privileges to add an extension of NVDA on browser. NVD was working absolutely fine until last Tuesday 11th July.  All of sudden this issue cropped up. If you want to get on to a call do let me know I can send you the meeting invite. I can walk you through the issues.

Thanks and Regards,
V K Satya Prasad

**Comment by Akshay268** [comment]
I am facing the same issue with NVDA tool from last week. I tried to run the tool in few sites but it is reading as "UNKOWN" every time. Below are the version details.
 
NVDA tool version : 2023.1 
OS : Window 11 
Chrome browser version : Version 114.0.5735.199 (Official Build) (64-bit)
Edge browser version : Version 114.0.1823.82 (Official build) (64-bit)

Just to confirm , no browser extension was used while tool was ran. I tried in incognito/private window on chrome and edge respectively but no luck.

**Comment by seanbudd** [comment]
Your work machine seems to be blocking NVDA from working correctly. Can you please discuss this with your IT administrator. Can you confirm that NVDA works correctly on your machine with security software disabled?

**Comment by seanbudd** [comment]
Can you also please confirm that you have run the COM registration fixing tool, as mentioned in the issue template

**Comment by seanbudd** [comment]
@Akshay268 - can you confirm if the issue still persists after updating Chrome and Edge?

**Comment by Akshay268** [comment]
@seanbudd  Thanks for getting back on this. I had tried to run "COM registration fixing tool" and restarted the machine post that but no luck. Issue still persists. NVDA tool reads as "UNKNOWN" for all the web elements 

Note : I used the updated version of chrome browser - Version 115.0.5790.102

**Comment by seanbudd** [comment]
Is this a work device? Do you have any special antivirus software running?

**Comment by Akshay268** [comment]
yes , it is a work device. I tried by disabling the antivirus software but it didn't help to resolve the issue. Please let me know if you want to connect over a call to check the issue

**Comment by seanbudd** [comment]
Is it possible that other corporate software could be interfering with NVDA? e.g. security or software to restrict device usage?

Does chrome/edge/firefox all not work?

Have you updated to the latest versions of these browsers?

Can you use web browsers when running the NVDA installer?

Can you use web browsers when running NVDA as a portable copy?

**Comment by Akshay268** [comment]
Is it possible that other corporate software could be interfering with NVDA? e.g. security or software to restrict device usage?
-----> I am not very sure about that but tried disabling security and antivirus software , didn't help much

Does chrome/edge/firefox all not work?
---> I don't have firefox in my machine . Tried in latest versions of chrome and Edge , seeing same issue in both the browsers

---> I can use web browsers when running the NVDA

**Comment by Adriani90** [comment]
@Akshay268 you say in the issue description if NVDA addons are disabled, the problem is not occuring anymore. is this correct?

Could you please do following to make sure the issue is really comming from NVDA core?
1. Press windows+r
2. Type following:
"nvda -c %tmp%\nvda_browserTest"

This will create a clean test version of NVDA
3. Validate the start dialog, but don't change any settings
4. Try to use Chrome and Edge with NVDA and see if the issue is still occuring.
Afterwards please report the results.
You can also delete the temporary NVDA test folder from %temp% after you did the test.

**Comment by Akshay268** [comment]
you say in the issue description if NVDA addons are disabled, the problem is not occurring anymore. is this correct?
---> @Adriani90  I have not created this ticket , it was created by someone else . I added comments in this ticket as I was also facing the same issue. To answer your question , there's no addons available in NVDA tool. 

I followed the steps to create a clean test version of NVDA and checked again in both chrome and edge browser , still getting same issue. 

NVDA version - 2023.1 
Chrome - 115.0.5790.102
Edge - 115.0.1901.183

Let me know if any more details are needed from my end. I am happy to discuss this issue over a call.

**Comment by VinjamurySatyaPrasad** [comment]
Hi All,

I followed all the steps which were mentioned in the email chain. Run the com tool option as well post restarting the system NVDA partially worked on Edge browser however issue remains to be the same on Chrome browsers. I think the issue is with Organization policies related to cyber security etc.. My IT team is currently working on it to resolve the this issue. I don’t think its related NVDA anymore. However thanks for everyone for chipping in and provided your support. You can close this ticket now.

Thanks and Regards,
V K Satya Prasad

**Comment by seanbudd** [comment]
> ---> I can use web browsers when running the NVDA

Hi @Akshay268 - it seems your comment was partially cut off in https://github.com/nvaccess/nvda/issues/15144#issuecomment-1651166892

**Comment by Akshay268** [comment]
Thank you all for you support in checking this issue. I am following up with company IT team to resolve the issue.

@VinjamurySatyaPrasad  Please let me know if you come across any workaround or solution for this issue. Thank you.

**Comment by suhridsingh** [comment]
NVDA is not reading any content of websites

Tried different websites on different browsers & incognito tabs as well
Tried last two NVDA versions ie. 21.2 & 23.1, doesn't work
NVDA Speech reader in Windows 10 having version 21.2 NOT reading content at all.
Re-Installed - installed multiple times to do troubleshoot
Nothing works
Sys Conf.
Wind 10/ Chrome Version 114.0.5735.248 (Official Build) (64-bit) / Edge Version 115.0.1901.183 (Official Build) (64-bit)

also tried on friend's computer having Windows 11, NVDA Speech reader version 23.1
-> Thre it is reading the content as "UNKNOWN",

No add on nothing I am using

**Comment by Qchristensen** [comment]
@suhridsingh Have you gone to the NVDA menu (NVDA+n) then tools, (T), then "Run COM registration fixing tool"?

Also, are you able to answer Sean's questions from [This comment](https://github.com/nvaccess/nvda/issues/15144#issuecomment-1651081741) please?

**Comment by Akshay268** [comment]
Hi All, I have an update about the issue I was facing i.e. NVDA tool was reading "UNKNOWN" every time for all the elements. 

Tool was not working in Chrome and Edge browser and it is still not working in these 2 browsers.  **It is working in Firefox browser (115.0.3 ).** 

Though Firefox browser is vulnerable and not allowed in some organization , it can be used as a workaround to use NVDA tool.

**Comment by Adriani90** [comment]
Maybe is Edge or Chrome running in a sandbox due to security reasons. Did you check on that?Is it ok for you to post here a list of all software programs which are installed on your device?Skype for business for example is known to unregister dlls which are relevant for accessibility when installing and uninstalling it. As far as I know the COM registry fixing tool still cannot fix them, but I might be wrong.Von meinem iPhone gesendetAm 28.07.2023 um 15:40 schrieb Akshay268 ***@***.***>:﻿
Hi All, I have an update about the issue I was facing i.e. NVDA tool was reading "UNKNOWN" every time for all the elements.
Tool was not working in Chrome and Edge browser and it is still not working in these 2 browsers.  It is working in Firefox browser (115.0.3 ).
Though Firefox browser is vulnerable and not allowed in some organization , it can be used as a workaround to use NVDA tool.

**Comment by XLTechie** [comment]
Firefox is vulnerable to what? You are free to hold that opinion, but I am 
curious on what evidence you base it.

**Comment by seanbudd** [comment]
Please don't reopen this issue until the requested information is provided.
Our current belief is that this is caused by corporate sandboxing software, not NVDA.
The following information is still needed.

Is it possible that other corporate software could be interfering with NVDA? e.g. security or software to restrict device usage?
Please check with your system administrator.

Can you use Chrome/Edge when running the NVDA installer?

Can you use Chrome/Edge  when running NVDA as a portable copy?
