### ISSUE TITLE
Currently NVDA is no longer able to read Instagram messages being sent and received.

### ISSUE THREAD

**Issue by titet11** [nvaccess/nvda#15217]
This problem has been going on for about a week.
It does not matter which version of NVDA is used. it is impossible to read instagram messages.

**Comment by seanbudd** [comment]
Welcome @titet11 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully. https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&projects=&template=bug_report.md
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
@titet11 please fill the issue template properly, people that are active on this platform do not automatically follow the NVDA users mailing list.
Without the issue template filled correctly it is not possible to investigate this issue.
Are you using a client for accessing instagram? Or an app? Or the website? Which are the exact steps to reproduce this issue?
You see, the issue template has been developed with the purpose to clarify alot of questions that otherwise would need to be addressed via comments which cost a lot of time and energy. So when you report an issue, please take the effort on yourself and answer the questions the developers need for investigating.
