### ISSUE TITLE
Change log level of garbageHandler messages

### ISSUE THREAD

**Issue by ultrasound1372** [nvaccess/nvda#15356]
### Is your feature request related to a problem? Please describe.
Sometimes, especially when working with certain office apps like power point and alt tabbing, NVDA logs in total hundreds of deletions of unreachable objects. Currently, these are logged at the level WARNING, which means at the INFO level, a reasonable default, these produce an error tone in non-release builds and fill the log with not only the total number of deletions, but two lines for every single such object. As the average number of these is anywhere from 50 to 80 per flush and this happens repeatedly, this results in an extremely verbose log that buries anything else relevant.
### Describe the solution you'd like
Change the log level of `garbageHandler.notifyObjectDeletion` and perhaps `garbageHandler._collectionCallback` to something like debug warning, so that these can still be logged for actually reducing such occurrences but don't bother everyday users by flooding the log. Perhaps the `notifyObjectDeletion` events could be made debug warning and `_collectionCallback` changed to warning, so that we only get one message with the count rather than the dozens of messages brought about by individual collection notifications.
### Describe alternatives you've considered
The obvious alternative is to prevent so many objects from being left unreachable in the first place, and indeed that should be the long term goal unless I'm mistaken. This issue serves more as a short term fix to an inconvenience for everyday users. I wonder if it could make it into the 2023.2 milestone given how small a change it would actually be, although I'm aware we're late enough in the release cycle that it might not and don't expect it to be high priority.
### Additional context
While I was typing this issue, I received a log message that it found 186 unreachable objects in run. This would have produced a total of *374* lines in the log for something that is otherwise inconsequential to anyone that isn't debugging performance and resource usage. That's why I request the level of these messages be changed, so people with reasonable defaults that still read the log occasionally won't have to sift through these massive dumps of irrelevant info.

**Comment by XLTechie** [comment]
I usually run my logs at debug all the time, and so even at warning or similar 
they would be a pain to me (are, when they start happening a lot).

What about making these a special log category which must be enabled?

NV Access folks have expressed a reluctance to worry about debugging and 
rectifying these in the past, if they do not cause any determinable impact on 
usability. Given that, since they do pollute the logs quite significantly at 
times, if nobody is going to fix them maybe they should be just made to go away 
unless somebody is looking for them specifically?

**Comment by ruifontes** [comment]
Agree 100% with Luke!

**Comment by ultrasound1372** [comment]
That would work as well, like the other debug categories.

**Comment by Brian1Gaff** [comment]
I'd agree with that, it would make it easier for those who are simply reporting errors via logs be more confident they are reporting errors that matter, particularly when a problem is hard to get to happen to order.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by amirsol81** [comment]
I also support this.

**Comment by ultrasound1372** [comment]
Should I revise the issue or open a separate one then to describe that approach? I don't know enough about NVDA's internals to make a PR.

**Comment by seanbudd** [comment]
>NV Access folks have expressed a reluctance to worry about debugging and
rectifying these in the past, if they do not cause any determinable impact on
usability. Given that, since they do pollute the logs quite significantly at
times, if nobody is going to fix them maybe they should be just made to go away
unless somebody is looking for them specifically?

I'd just note that this is due to many p2 level issues being open, and a matter of prioritization.
These are still serious issues that imply a performance problem underneath, however they are still going to be lower priority to issues with a clear user impact. I do think it's worth keeping the error sound for relevant builds, even if these logs could be suppressed further somehow.

**Comment by ultrasound1372** [comment]
I think simply the message listing the number of unreachable objects found in run could be logged, at warning level, which would still generate such a tone. That way if something did get truly out of hand even if you had individual deletion messages suppressed, via being a checkbox in the debug category, you would still know as you would see a spike in such summary messages. Seems a good compromise. Although I admit to being curious, when you create temporary objects, which often has to be done, what other way is there to get rid of them? Even using del doesn't actually clear the object it just unbinds it, and then the garbage collector finds it. So isn't garbage collecting unreachable objects really the only way to deal with anything that needs temporary objects?

**Comment by seanbudd** [comment]
An option to suppress these messages should be okay, as long as it is disabled by default. The current behaviour of logging for garbage handler warnings should remain by default.

**Comment by leonardder** [comment]
Fixed by #15778
