### ISSUE TITLE
Speech viewer no longer has a shortcut key in the tools menu in 2023.2

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15362]
### Steps to reproduce:

With NVDA 2023.2 installed:
- Press NVDA+n, then t to open the tools menu.
- Arrow through the options and note the keys associated with each.
- Press S (the key used to open this feature in 2023.1).

### Actual behavior:

Speech viewer no longer has an associated key, and S now opens the add-on store ("A" opened the add-on manager in 2023.1).

### Expected behavior:

There should be a shortcut key to toggle speech viewer.

It may be worth considering making "A" the key for add-on manager and leaving S for speech viewer (S still works in temporary copies so the shortcut hasn't been removed, it has just been overridden by the add-on store).

#### NVDA version:

2023.2 installed

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.2134  (although this is likely irrelevant).

**Comment by jcsteh** [comment]
My guess is that this was never defined with an access key (`&S`). When there was no other item with that access key, that was fine; Windows chose S as the first letter. Now that we do have something with that access key (Add-on store), that clobbered the (non-explicit) Speech viewer access key.

As a matter of interest, why did we choose s for Add-on store instead of a (as was previously the case before the store)?

**Comment by Brian1Gaff** [comment]
Yes that does seem a trifle odd, as the average user is more likely to need the add on store than the speech viewer, it would have made more sense to use A as before for add ons. Unless of course somebody merely hit s instead of a as they are next to each other on the keyboard.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment]
>As a matter of interest, why did we choose s for Add-on store instead of a (as was previously the case before the store)?

For a certain period of development, both the manager and the store was available. This was an artifact that got mistakenly retained.

I think we can reassign it to a and make the speech viewer key explicit as well
