### ISSUE TITLE
In the add-on store, if an add-on is already installed, it isn't shown in the list of available add-ons when working in that category

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#15374]
### Is your feature request related to a problem? Please describe.
At present, if you use the available add-ons category, add-ons already installed are not shown in the list.  I am assuming for this discussion, that the user is using the correct category such as all or stable when looking for the add-on.
### Describe the solution you'd like
All add-ons in the category, such as all stable add-ons, should be shown in the list when in available add-ons.  Available doesn't mean only uninstalled.  It means all add-ons offered in the store in the category..
### Describe alternatives you've considered
None.
### Additional context
The current method is going to cause a lot of confusion.  I check, from time to time, to see if there is an add-on for something someone asks about on a users list.  If I already have an add-on installed, such as Clipspeak and I look in available add-ons, I won't see it.  I may conclude that it is no longer offered in the store.
The correct way to do this is to show all add-ons in a category, then if someone mistakenly tries to install one that is already installed. bring up an error message that the add-on is already installed.  Or the add-on could show that it is installed next to the name such as, Clipspeak, installed.

**Comment by day-garwood** [comment]
If all addons were listed in "available" then it would be hard to find just addons that aren't installed.
On the other hand I do feel that an "all" tab would be useful as well.

**Comment by britechguy** [comment]
I'm agnostic as to whether a separate All tab should be created, or a installed/available status column be added in the Available tab, but there should be some way to see all available add-ons in one place regardless of whether one has already acquired them or not.

I do think that even if a separate All tab were to be created, an installed/available status column should be included there.

**Comment by josephsl** [comment]
Hi, I think a “status” column in “available add-ons” tab would be a better solution as creating an “all” tab can be confusing – the add-on store opens to “installed add-ons” list for compatibility with add-ons manager user experience and interface from the past. Thanks.

**Comment by XLTechie** [comment]
I too, support some version of this proposal.

I would be content with any solution that provides the desired functionality, but 
I think I lean more in the preference direction of @josephsl's suggestion 
(status column), rather than an all tab.
Maybe some sorting option can take care of hiding or de-prioritizing already 
installed add-ons, for those who want that.

Consider, that if this were a web based store, such as Firefox uses, there would 
be no way to tell that an add-on was installed, so they would all be listed.
While I don't use the Microsoft store enough to remember how it does this, the 
various Apple/iOS stores also show already installed apps as available, but with 
an i "open" button instead of an "install" button, or an "update" button if an 
update is available.

While app stores are not entirely analogous, they are similar enough in concept 
that i think we can take the lesson.

**Comment by josephsl** [comment]
Hi,

In Microsoft Store, when I do search for an app that is installed, I do see the installed app and other suggestions. For installed apps, Store says "own" or "installed" depending on cost. For ones not instlaled, search results will say "free" or the cost of the app. Both installed and available apps are grouped under a single list.

Thanks.
