### ISSUE TITLE
Make "line feed" and "carriage return" symbol names more user friendly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1539]
**Reported by ink on 2011-05-31 21:35**
Although most people are today quite familiar with computer terms, I would like to suggest that there is still room for modifying how NVDA handles it. For instance, NVDA could simply say, "Line" for "Line Feed".

**Comment by bhavyashah** [comment]
Does anyone have more user-friendly alternatives to line feed and carriage returned at present? Also, even before considering any proposed alternatives, we must keep in mind the fact that these two terms have been in NVDA since many years now and changing them may result in potential confusion. If no one disagrees, I would like to kindly suggest closing this ticket as invalid. @ehollig

**Comment by Adriani90** [comment]
Closing as invalid since the user can configure it for his or her needs.
