### ISSUE TITLE
PDF Converter 7 Professional support.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1545]
**Reported by ink on 2011-06-02 15:21**
It would be nice to have NVDA starts supporting PDF Converter 7 Professional; a competing product to Adobe Acrobat provided by Nuance. Some of the issues found in Adobe Acrobat are not in PDF Converter 7 Professional. It is thus far the best alternative to Adobe.

**Comment by bhavyashah** [comment]
@jcsteh Since the original author did respond to your request for further details and specifics in https://github.com/nvaccess/nvda/issues/1545#issuecomment-155290532, do you have any follow-up to make or priority to assign to this ticket (P4 perhaps)?

**Comment by Adriani90** [comment]
Is anyone who can test this with the most current version of this software?
@ink

**Comment by Adriani90** [comment]
According to my research PDF converter professional is discontinued. Last release (version 8.1) was in 2013. We do not have an udate from the initial author and do not have any further requests from users. I am closing this as abandoned. Please comment on it if this issue is important for you and we can reopen the discussion. Thanks.
