### ISSUE TITLE
Feature request: Ability to prevent screen curtain from being used

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15508]
### Is your feature request related to a problem? Please describe.

This is a request from a teacher who needs to be able to prevent students in the classroom from using screen curtain, so the teacher can monitor how students are using the PC.

### Describe the solution you'd like

Possibly a registry value - a command line switch could be overridden simply by launching NVDA without it.

**Comment by CyrilleB79** [comment]
Is there really a need for a technical solution to this issue? Couldn't the teacher just forbid to use the feature? In one look, the teacher is able to check that the student conforms to the rule.

Even if less intuitive and less perfect than a screen curtain, there would still be a way to hide one's activity on the screen:
* start Windows Magnifier
* in the parameters disable all tracking features (follow focus, follow mouse cursor, follow text caret and even follow Narrator cursor)
* Zoom at maximum level (1600%)
* Press many times control+alt+downArrow and control+alt+rightArrow so that the bottom right corner of the screen be in the magnified view
At this point, almost nothing can be seen on the screen: only the notification icon, a part of the clock and maybe a part of the status bar of the active application if it is maximized. Less perfect than the screen curtain but still very annoying for the teacher.

**Comment by cary-rowen** [comment]
Hi,

I agree with @CyrilleB79, this doesn't necessarily require a dedicated technical solution.
Teachers can easily see who has opened the screen curtains.

Thanks

**Comment by CyrilleB79** [comment]
As an addition to the Magnifier's trick, there are many other and simpler solutions to hide more or less the screen:
* switch off the screen (desktop computer only)
* lower the brightness and contrast to minimal values
* close the computer (laptop only) if you are using an external keyboard or a braille keyboard
* put a paper sheet or a book in front of the screen

**Comment by leonardder** [comment]
I second @CyrilleB79's concerns and would like to vote for a won't fix.

**Comment by codeofdusk** [comment]
I'd also like to vote for a won't fix here.

**Comment by seanbudd** [comment]
Be able to prevent one easy method of an "exploit" is still better than taking no action.

There's also the case here that someone would want to prevent a shared device from having the screen turned off (e.g a kiosk).

In the planned "kiosk mode" of NVDA, screen curtain usage will be disabled.

**Comment by codeofdusk** [comment]
A kiosk is a situation where a screen curtain would be most useful. Most ATMs and voting machines in the US have a built-in screen blanking option when using the audio interface.

**Comment by seanbudd** [comment]
Closing for reasons outlined in comments above
