### ISSUE TITLE
A check box to tell NVDA to update to stable builds if no R C or beta is available

### ISSUE THREAD

**Issue by GeorgeWu3** [nvaccess/nvda#15586]
### Describe the solution you'd like
It will be nice to have an option to add a check box in the general or the advanced settings where users can choose to tell NVDA to update to the final stable release if no beta or RC builds are available.
### Additional context
It is an advantage for us users.

**Comment by XLTechie** [comment]
> It is an advantage for us users.

No offense, but given that you have opened this feature request, it is obvious 
that you would think so. But just saying it does not help us understand why *we* 
should think so.

So please explain *why* this would be an advantage?

If a user is running a beta or an RC, presumably that user is comfortable doing 
so. Since the final release version is the same as the last RC, there is no 
difference--other than version name--between the version the user will be 
running, and the final release version.
And, it will then be easier to upgrade to the next version's beta when it first 
comes out, since the user won't have to do anything other than check for update 
and agree to install it.

Given those things, why would this feature be advantageous?

**Comment by Brian1Gaff** [comment]
I think of more use might be to downdate to a previous working version, but this could end in giving ones self a whole lot of pain if it happens to be a file that tracks add ons or other parameters as these may or may not be  deleted or recreated afterwards. 
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by GeorgeWu3** [comment]
I think it would be advantageous for those who may just want to try one beta version or they just want NVDA to update to stable after the release candidates are done. An option for that would be great as it would be there for those who want to take advantage of it or for those who use the release candidates only.

**Comment by seanbudd** [comment]
Closing as won't fix. The current behaviour is intentional. If we are to introduce something like this, it would be a proper channel selector to opt into alpha/beta/rc/stable channels explicitly.

**Comment by seanbudd** [comment]
I.e this has been closed in favour of #10679
