### ISSUE TITLE
Revert change of one shortcut introduced in 2023.3

### ISSUE THREAD

**Issue by tmthywynn8** [nvaccess/nvda#15588]
### Is your feature request related to a problem? Please describe.

This change originated in pull request #15364.

### Describe the solution you'd like

Change "Run COM Registration Fixing tool" to "T" and "Reload plugins" to "R" for two reasons:

1. "T' could be the mnemonic for "tool" and "R" for "reload". This makes way more sense than "E" not being a mnemonic for anything.
2. Users of the Remote add-on have been used to the "E" mnemonic for years, and while this is not part of NVDA core, making change for change's sake is not that great of a reason (see [this thread][1] and [this other thread][2] for a few disgruntled users).

[1]: https://dragonscave.space/@simon/111086060399049348
[2]: https://dragonscave.space/@Brynify/111184847640354095

### Describe alternatives you've considered

Even without the Remote Support add-on, "E" doesn't make any sense while "T" is at least the first letter of a word in the "Run COM Registration Fixing tool" entry.

### Additional context

The Remote Support add-on has been in existence since 2015 and is likely used by many in the community, least of which is evident by the fact its development was crowdfunded. Changing muscle memory without thought and reason may have an adverse impact on users of this add-on. Mnemonics also help in this case because you could at least remember "R" for "reload" and "T" for tool which at least makes some logical sense. I understand that conflicts will eventually exist, however these keybinding has been unchanged for over eight years.

**Comment by CyrilleB79** [comment]
In understand and agree that "T" is a good menemonic for the COM reg fixing tool. However, in  #15364, it has been explicitly decided to keep "R" for "Run COM Registration Fixing tool" to avoid invalidating existing support instructions; see https://github.com/nvaccess/nvda/pull/15364#discussion_r1315648958 and associated discussion for details. Thus, unless there should be a strong argument to come back on this decision.
 Cc @XLTechie for information.

Usually, NVDA defines the shortcut keys and the add-ons should adapt to it. Given the popularity of NVDA Remote and it's age in the community though, NV Access may accept this case as a valid exception to this rule.

The following letters are already used in the Tools menu: l, s, b, a, p, c, i, r. Thus among the letters of "Reload plugins", the following letters are remaining: o, d, u, g, n.
There is no possibility to use the first letter of a wor, so, what about G? (less common than a vowel)
In any case, the mnemonic for reload plugins item is not very important since there is already the NVDA+control+F3 gesture.

@tmthywynn8 would this solution satisfy your need?

@seanbudd or @Qchristensen would NV Access accept such a change to take into account the use of a popular extension used for a long time?
In this case it should go in NVDA 2023.3 so that accelerators not be changed back and forth in each release, which would be the worse thing.

**Comment by XLTechie** [comment]
I was the one who objected to changing R from Run COM Registration Fixing Tool, 
and my reasoning from the linked comment hasn't changed.

E, however, I would think, could change. It is both new, and as Cyrille has 
said, less important because it has a mapped gesture outside the menu. I would 
be fine changing it to G.

I too have found the E conflict with Remote, to be a bit annoying.

**Comment by tmthywynn8** [comment]
My apologies. I did not see the discussion found in https://github.com/nvaccess/nvda/pull/15364#discussion_r1315648958/ until now. Thanks for highlighting it.

I also write up instructions, and like @XLTechie, provide mnemonics where possible. I am not sure how much of a negative impact this would actually have because end users should know why they are using the shortcut key in the first place, i.e., they are running the COM Registration Fixing tool, rather than mindlessly pressing a series of keys like an incantation. That, and they would also need to restart the computer for it to take full affect.

That said though, I certainly have no strong objection to keeping the "R" mnemonic for "run". The problem then becomes what mnemonic should be used for "reload plugins"? While "I" is also unused and would be the first letter of the "ins" compound, "G" probably would work just as well because neither are the first letter of a word. "R" Is the mnemonic for "reload" and "P" "Python". I don't think making even more changes to shortcuts would be a good idea, i.e., "C" for "console" because of the aforementioned "making change for change's sake" argument.

So to conclude, if "R" has to be kept because of prior instructions given, whether "G" "I" or some other letter is used to reload plugins, I have no strong opinion about any of that. This is, of course, an English-centric discussion, and I do not know what other design or user experience principles would apply here. I initially started this discussion because of the threads linked above so have no strong feeling about the "E" shortcut except that I feel that mnemonics are important for both memory and training purposes.

**Comment by CyrilleB79** [comment]
> My apologies. I did not see the discussion found in [#15364 (comment)](https://github.com/nvaccess/nvda/pull/15364#discussion_r1315648958) until now. Thanks for highlighting it.

No problem. It was not directly visible anymore (hidden) since this discussion was a comment in my code that has been resolved.

> The problem then becomes what mnemonic should be used for "reload plugins"? While "I" is also unused and would be the first letter of the "ins" compound, "G" probably would work just as well because neither are the first letter of a word. 

No, "I" is not available, since it is already used by "Install NVDA"; this item is only available in the menu of portable NVDA to install it on your system.

> This is, of course, an English-centric discussion, and I do not know what other design or user experience principles would apply here.

Only English needs to be considered here. The translators for each language will then adapt the mnemonics in their own languages.

Note: I have finally opened the PR for this issue (#15589); let's see what NV Access thinks of it.
