### ISSUE TITLE
When installing updates to a portable copy, the button should not be called "install update"

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#15720]
### Is your feature request related to a problem? Please describe.

After checking for an update in any copy of NVDA, one eventually reaches a dialog asking whether you want to perform the update.

The button to perform that update is called "**Install update**".

NVDA can operate as either an installed application, or as a portable application.

But when performing the update of a portable copy, the button is still called "install update".

I posit that this may lead to confusion among some users--who have both portable and installed copies--that the update to a portable copy, will instead be installed.

### Describe the solution you'd like

I would like to change the "Install update" button, so that its name is instead "Update now", or "Perform update".

I think this simple change is generic enough to cover updating both portable and installed copies, without evoking the specter of installation when considered in the context of portable copies.

### Describe alternatives you've considered

Leave as is.

### Additional context

Obviously this is a small concern, but it is also an easy fix, if others share it.

**Comment by Brian1Gaff** [comment]
I'd agree, though I'm pretty sure this has arisen from one of the very earliest nvda versions, when install was the only game in town, so to speak.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by SaschaCowley** [comment]
I can see a few options here:

1. Change the install button to say "Update" rather than "Install" in all cases. Optionally, add a note stating that the running copy is what is being updated.
2. Keep the install button as is, and add a note explaining that the currently running copy is what is being updated.
3. Come up with a new label for the install button when running a portable copy, such as "Update NVDA portable copy".

The problems I can see with options 1 and 3 are minor, but are that new translation strings need to be provided, and that users may have muscle memory of the accelerator keys to use in these dialogs, which they will need to relearn. Option 2 would not have this disadvantage, but I suspect would not reduce confusion very much, as many users do not read dialogs carefully, and may just rely on titles and button text (I know I do this when I see repeated dialogs and am in a bit of a rush).

Is there a strong preference for which way we go with this?

**Comment by Adriani90** [comment]
Maybe an option is to change the label of this button in general to "aply update" which should appear both for installed and portable copy of NVDA.

**Comment by XLTechie** [comment]
@SaschaCowley I think your concern with option 2 is the most serious, and to me 
invalidates that option.

The muscle memory in this instance is probably the enter key--I know it is for 
me--so I'm not sure that would be a problem for most users.

I think either "Update now", or @Adriani90's idea of "Apply Update", would be 
acceptable in all cases (option 1).
