### ISSUE TITLE
Windows Explorer in Windows 11. Context menu not accessible: NVDA is redirected to an offscreen not navigable popup window when attempting to open the context menu of any file

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15733]
### Steps to reproduce:
1. With NVDA running, open the Windows explorer
2. Focus any file or folder
3. Press shift+f10 or right mouse click or the application key to open the context menu

### Actual behavior:
In most cases the system focus is redirected to a non accessible UIA popup window and the context menu is not accessible. It seems sometimes it works though, especially when you focus a submenu with the mouse before.
Here is the developer info for the popup window:
```
INFO - globalCommands.script_navigatorObject_devInfo (17:11:07.444) - MainThread (6204):
Developer info for navigator object:
name: 'Popup'
role: WINDOW
processID: 1000
roleText: None
states: FOCUSABLE, OFFSCREEN, FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x00C0B0D0>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=0, top=0, width=0, height=0)
value: None
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: AppModule(explorer, appName='explorer', processID=1000)
appModule.productName: 'Betriebssystem Microsoft® Windows®'
appModule.productVersion: '10.0.22621.2428'
appModule.helperLocalBindingHandle: c_long(107867880)
windowHandle: 788454
windowClassName: 'Microsoft.UI.Content.DesktopChildSiteBridge'
windowControlID: 0
windowStyle: 1342177280
extendedWindowStyle: 2097152
windowThreadID: 27592
windowText: ''
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x66ab3b0 at c170d0>
UIA automationID: 
UIA frameworkID: XAML
UIA runtimeID: (42, 788454, 4, 196)
UIA providerDescription: [pid:1000,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:Microsoft.UI.Xaml.dll)]
UIA className: Popup
UIA patterns available: ScrollItemPattern, WindowPattern, LegacyIAccessiblePattern
```

And here is the log snipped when attempting to open the context menu.
```
IO - inputCore.InputManager.executeGesture (17:19:22.096) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - speech.speech.speak (17:19:22.461) - MainThread (6204):
Speaking ['Popup', 'Fenster', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:22.464) - MainThread (6204):
Speaking ['Ausschneiden', '1 von 4', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:22.468) - MainThread (6204):
Speaking ['Ausschneiden', '1 von 4', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:19:23.261) - winInputHook (28988):
Input: kb(laptop):escape
IO - speech.speech.speak (17:19:25.355) - MainThread (6204):
Speaking ['Heute', 'Gruppierung', 'ausgeklappt', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:25.360) - MainThread (6204):
Speaking ['aria-labelledby-issue.html', '1 von 71', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:19:26.650) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - speech.speech.speak (17:19:27.203) - MainThread (6204):
Speaking ['Popup', 'Fenster', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:27.210) - MainThread (6204):
Speaking ['Popup', 'Fenster', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:19:28.061) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:28.512) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:28.849) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:30.187) - winInputHook (28988):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (17:19:30.348) - winInputHook (28988):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (17:19:30.508) - winInputHook (28988):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (17:19:30.732) - winInputHook (28988):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (17:19:30.902) - winInputHook (28988):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (17:19:31.080) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:31.277) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:31.464) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:31.704) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:31.980) - winInputHook (28988):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:19:32.960) - winInputHook (28988):
Input: kb(laptop):escape
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (17:19:33.003) - Dummy-3 (27352):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
IO - speech.speech.speak (17:19:33.034) - MainThread (6204):
Speaking ['Elementansicht', 'Liste', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:33.036) - MainThread (6204):
Speaking ['Heute', 'Gruppierung', 'ausgeklappt', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:19:33.042) - MainThread (6204):
Speaking ['aria-labelledby-issue.html', '1 von 71', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:19:33.871) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - inputCore.InputManager.executeGesture (17:19:34.880) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - inputCore.InputManager.executeGesture (17:19:36.436) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - inputCore.InputManager.executeGesture (17:19:37.469) - winInputHook (28988):
Input: kb(laptop):shift+f10
IO - inputCore.InputManager.executeGesture (17:19:40.846) - winInputHook (28988):
Input: kb(laptop):shift+f10
```

### Expected behavior:
NVDA should always land on the context menu and be able to navigate the menu items with the arrow keys every time when pressing shift+f10 or the right mouse click or the application key when focusing a file or a folder in Windows explorer.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.3 and NVDA last alpha

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, 2023.2 has the same issue.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by Adriani90** [comment]
There seems to be a registry hack which restores the legacy context menu, so this works as a temporary workaround but for novice users this is probably heavy to be aware of.

https://answers.microsoft.com/en-us/windows/forum/all/restore-old-right-click-context-menu-in-windows-11/a62e797c-eaf3-411b-aeec-e460e6e5a82a

**Comment by Qchristensen** [comment]
I am hitting a similar issue.  Using:

NVDA 2023.3
Windows 11 (64-bit) Version: 22H2, Build: 22621.2715 

I open the context menu and visually it appears, but I can't navigate it, and after a couple of seconds all explorer windows, including the taskbar close, and five or ten seconds later, explorer restarts and the taskbar appears.  I can confirm that I can prevent it from crashing by EITHER:
- opening a submenu with the mouse 
- repeatedly pressing down arrow immediately after releasing the applications key and before the menu is even visible

Not sure there's anything new in my log fragment, but here it is:

Input: kb(desktop):applications
IO - speech.speech.speak (09:37:07.932) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Pop-up', 'window', CancellableSpeech (still valid)]
IO - speech.speech.speak (09:37:07.942) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Cut', 'T  Ctrl+X', '1 of 5', CancellableSpeech (still valid)]
IO - speech.speech.speak (09:37:07.952) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Cut', 'T  Ctrl+X', '1 of 5', CancellableSpeech (still valid)]
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:08.480) - watchdog (4052):
Potential freeze, waiting up to 10 seconds.
IO - inputCore.InputManager.executeGesture (09:37:08.961) - winInputHook (29800):
Input: kb(desktop):upArrow
IO - inputCore.InputManager.executeGesture (09:37:10.226) - winInputHook (29800):
Input: kb(desktop):downArrow
DEBUG - speech.manager.SpeechManager._handleIndex (09:37:13.896) - MainThread (21288):
Unknown index 773, speech probably cancelled from main thread.
DEBUG - UIAHandler.shouldUseUIAInMSWord (09:37:14.011) - MainThread (21288):
Using UIA due to suitable Office version: (16, 0, 17029)
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:14.053) - watchdog (4052):
Recovered from potential freeze after 6.0722352999999885 seconds.
IO - speech.speech.speak (09:37:14.063) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Blah 2\t1\r']
DEBUG - appModuleHandler.cleanup (09:37:14.191) - MainThread (21288):
application explorer closed
DEBUG - appModuleHandler.cleanup (09:37:14.191) - MainThread (21288):
application startmenuexperiencehost closed
IO - speech.speech.speak (09:37:14.636) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Foxit PDF Reader Updater', 'dialog', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (09:37:14.692) - MainThread (21288):
Potential unimplemented child class: <NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObject object at 0x016F1F70>
IO - speech.speech.speak (09:37:14.692) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'edit', 'read only', 'multi line', CancellableSpeech (still valid), 'blank']
DEBUG - appModuleHandler.cleanup (09:37:15.606) - MainThread (21288):
application searchhost closed
DEBUG - appModuleHandler.cleanup (09:37:15.606) - MainThread (21288):
application shellexperiencehost closed
INFO - watchdog.waitForFreezeRecovery (09:37:16.118) - watchdog (4052):
Starting freeze recovery after 0.5003644000000236 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (09:37:16.118) - watchdog (4052):
Listing stacks for Python threads:
Python stack for thread 14328 (Dummy-4):
  File "synthDrivers\oneCore.pyc", line 481, in _callback
  File "nvwave.pyc", line 892, in feed

Python stack for thread 16416 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x0676F288>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 8340 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 455, in _run
  File "winUser.pyc", line 459, in getMessage

Python stack for thread 4052 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 165, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 6192 (touchHandler.TouchHandler):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "touchHandler.pyc", line 245, in run

Python stack for thread 29800 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 18208 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6932 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "concurrent\futures\thread.pyc", line 78, in _worker

Python stack for thread 13948 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 21288 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "wx\core.pyc", line 3407, in <lambda>
  File "core.pyc", line 747, in processRequest
  File "core.pyc", line 763, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "eventHandler.pyc", line 84, in _queueEventCallback
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 139, in setFocusObject
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1986, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 656, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1972, in _get_parent
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyc", line 274, in _get_parent
  File "NVDAObjects\__init__.pyc", line 250, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyc", line 105, in getPossibleAPIClasses
  File "UIAHandler\__init__.pyc", line 1187, in isUIAWindow
  File "UIAHandler\__init__.pyc", line 1115, in _isUIAWindowHelper

INFO - watchdog.waitForFreezeRecovery (09:37:16.728) - watchdog (4052):
Recovered from freeze after 1.1103289999999788 seconds.
DEBUGWARNING - RPC process 14680 (explorer.exe) (09:37:16.883) - Dummy-9 (27828):
Thread 21264, build\x86_64\remote\sysListView32.cpp, nvdaInProcUtils_sysListView32_getGroupInfo, 43:
LVM_GETGROUPINFOBYINDEX failed

IO - speech.speech.speak (09:37:16.908) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Desktop', 'list', CancellableSpeech (still valid)]
IO - speech.speech.speak (09:37:17.207) - MainThread (21288):
Speaking [LangChangeCommand ('en_GB'), 'Work']
DEBUG - UIAHandler.shouldUseUIAInMSWord (09:37:18.028) - MainThread (21288):
Using UIA due to suitable Office version: (16, 0, 17029)
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:18.193) - watchdog (4052):
Potential freeze, waiting up to 10 seconds.
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:18.698) - watchdog (4052):
Recovered from potential freeze after 1.013897199999974 seconds.
DEBUG - UIAHandler.shouldUseUIAInMSWord (09:37:19.042) - MainThread (21288):
Using UIA due to suitable Office version: (16, 0, 17029)
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:19.408) - watchdog (4052):
Potential freeze, waiting up to 10 seconds.
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:37:19.918) - watchdog (4052):
Recovered from potential freeze after 1.0096098999999867 seconds.
DEBUGWARNING - RPC process 3036 (SearchHost.exe) (09:37:20.098) - Dummy-10 (8264):
Thread 10012, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 177:
Not installing IA2 support as  process is suspendable

IO - inputCore.InputManager.executeGesture (09:37:24.333) - winInputHook (29800):
Input: kb(desktop):NVDA+f1
DEBUG - gui.contextHelp.bindHelpEvent (09:37:24.365) - MainThread (21288):
Did context help binding for LogViewer
INFO - globalCommands.script_navigatorObject_devInfo (09:37:24.618) - MainThread (21288):
Developer info for navigator object:
name: 'Desktop'
role: Role.LIST
processID: 14680
roleText: None
states: State.FOCUSABLE, State.FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.sysListView32.List object at 0x04E26B50>
Python class mro: (<class 'NVDAObjects.IAccessible.sysListView32.List'>, <class 'NVDAObjects.IAccessible.List'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=0, top=0, width=2560, height=1440)
value: None
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: AppModule(explorer, appName='explorer', processID=14680)
appModule.productName: 'Microsoft® Windows® Operating System'
appModule.productVersion: '10.0.22621.2428'
appModule.helperLocalBindingHandle: c_long(91202424)
windowHandle: 1115910
windowClassName: 'SysListView32'
windowControlID: 1
windowStyle: 1442855488
extendedWindowStyle: 0
windowThreadID: 26152
windowText: 'FolderView'
displayText: 'd2 Run Personal\nTo Do\nCoins -Shortcut\nGetVersionsMicrosoftMovavi SuiteEdge\nMonthlyServer ...NVDA Secure NVDA Recycle Bin WriteMonk... desktop.ini'
IAccessibleObject: <POINTER(IAccessible) ptr=0x42ea4e0 at 4e2f260>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1115910, objectID=-4, childID=0
IAccessible accName: 'Desktop'
IAccessible accRole: ROLE_SYSTEM_LIST
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by zstanecic** [comment]
This was fixed in the latest windows 11 cumulative update KB5032288

**Comment by zstanecic** [comment]
reference from:
https://support.microsoft.com/en-us/topic/december-4-2023-kb5032288-os-builds-22621-2792-and-22631-2792-preview-538fbe4a-e9de-4312-85cd-d870444341d0
In this article we can read:
This update addresses an issue that affects File Explorer. When you press Shift + F10, the shortcut (context) menu does not open.

**Comment by beqabeqa473** [comment]
These fixes are not related to explorer crash. there are written about
shift+f10 only.
Explorer is still crashing, and i am not able to find a reliable steps
to reproduce.
I was experiencing this for several years on windows 10 and now on
windows 11 with latest updates.

On 12/5/23, Zvonimir Stanečić ***@***.***> wrote:
> reference from:
> https://support.microsoft.com/en-us/topic/december-4-2023-kb5032288-os-builds-22621-2792-and-22631-2792-preview-538fbe4a-e9de-4312-85cd-d870444341d0
> In this article we can read:
> This update addresses an issue that affects File Explorer. When you press
> Shift + F10, the shortcut (context) menu does not open.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15733#issuecomment-1840758859
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by CyrilleB79** [comment]
There are two issues described here:
1. The context menu does not appear (or is not focused): this is the initial description of @Adriani90. Looking at the log, there is no NVDA freeze, nor Windows Explorer crash. From other reports (lists), it appears that it is due to a quite recent Windows 11 Update.
2. NVDA freeze and Windows Explorer crash / restart. It's the issue described by @Qchristensen. According to @beqabeqa473 who describes the same symptoms, the issue seems much older.

For clarity it would be better to close the current issue if @Adriani90 confirms that it is solved. And to open a brand new issue for Explorer crash/restart; @beqabeqa473 or @Qchristensen would you mind open one?

**Comment by Adriani90** [comment]
This is better in the last update of Windows 11 23 H2, however it is not fully solved. It still occurs very often that the context menu does not open and NVDA lands on a offscreen popup window as mentioned in the issue description. Especially if you have groupings of files such as "today"., "last week", etc. the context menu on the first two or three files of each grouping does not open when pressing shift+f10 or the right mouse click.

And even when the context menu opens, NVDA seems to report this popup window which does not allow for interaction.

**Comment by Adriani90** [comment]
However, this seems to occur in 1 of 10 times or so, and I guess it is rather a Windows bug than a NVDA bug. So let's close this for now and report it to Microsoft.
