### ISSUE TITLE
Request to revert #15688 and reorganize the structure of the help menu.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15749]
### Is your feature request related to a problem? Please describe.
#15688 Created a "Documentation" submenu in the NVDA menu, contains:
- User Guide
- Commands Quick Reference
- What's new
- License
- Contributors

I think this breaks the user experience and is counter-intuitive for new users.

1. The goal of #15688 is to solve #14631. Let's revisit:
  - #14631 is to add an online "Get Help" entry,
  - The suggested solution for the problem of too many entries in the Help menu is to redesign the About dialog.
2. The new "Document" menu caused confusion:
  - Experienced NVDA users' memory of accelerator keys is broken
  - Path descriptions for NVDA User Guide menu items in some external tutorials are broken. e.g. #15737.
  - When new users encounter confusion, the first thing they may think of is to go to the "Help" menu to view the "User Guide", but they cannot find it at all in the Help menu.

### Describe the solution you'd like
In my opinion, "Documentation" is still an important part of help and has a subordinate relationship.
[Comment from @CyrilleB79](https://github.com/nvaccess/nvda/pull/15688#issuecomment-1793147077) in #15688 and upvoted by other community users (including me).

1. Move User Guide, Commands Quick Reference, What's new back to the "Help Menu".
2. Remove "License" and "Contributors" from the Help menu and add their buttons or links on the "About" page.
3. For non-English native users, adding too many NV Access website items provided in pure English may not seem useful, but these can be placed in a secondary menu.
### Describe alternatives you've considered
None yet
### Additional context
None yet

**Comment by wmhn1872265132** [comment]
Support this PR. Another problem not mentioned is that there may be many audio tutorials that also mention how to get help. For these tutorials, it is almost impossible to modify the steps.

**Comment by CyrilleB79** [comment]
Quoting rephrasing and extending here my comment initially in https://github.com/nvaccess/nvda/pull/15688#issuecomment-1793147077:

IMO, the existence of a separate documentation menu does not bring anything interesting. Specifically, in many applications, the help doc (user guide) can be found in the Help menu. I feel that separating Help and Documentation may lead to confusion, i.e. "I do not remember if User Guide is in Help or in Documentation".
Maybe the scope for splitting the help menu was to avoid a menu with too much items? In this case, a submenu "Useful links" under the Help menu can group all the links on NV Access website; for example that's the choice made in Jaws with a submenu "Web Resources" under the halp menu.

I agree that the User Guide should not be put in a 2nd sublevel menu; but for links on NV Access website, I think that it may be acceptable.

At last, I note that adding more items pointing on NV Access website may not be so interesting for non-English speaking users of NVDA; this issue was already present with the link on the main page of NV Access website, but adding these new links makes it more noticeable.

**Comment by Adriani90** [comment]
actually if we are at this point, I propose following for the NVDA menu:
1. Under Prefferences sub menu, rename the "settings" item to "configuration" and make it also a submenu. The configuration sub menu should include following items:
* "settings"
* configuration profiles
* Revert to saved configuration
* Reset configuration to factory defaults
* Save configuration
* Welcome dialog...

Benefits: the startpage of the NVDA menu gets cleaner and easier to understand for beginners, and the items in the configuration sub menu would not really break user experience because more advanced users use rather the key commands to display them (e.g. ctrl+nvda+p for the profile dialog).

2. Under help menu, following items should be included
* User guide
* Commands quick reference
* Whats new
* Get help and support (webpage only in english)
* Check for updates
* Info

3. The info dialog should contain following elements:
* A read only edit field with the information about NVDA
* License button
* Contributors button
* Go to NV Access website
* Ok button

So if implemented, the start page of the NVDA menu should look like following:
* Prefferences sub menu
* Tools sub menu
* Help sum menu
* Donate
* Exit

**Comment by Adriani90** [comment]
> Support this request. Another problem not mentioned is that there may be many audio tutorials that also mention how to get help. For these tutorials, it is almost impossible to modify the steps.

@wmhn1872265132 I would not restrict the design of a software in such a hard way. Otherwise this results in lots of opportunities for improvements. Actually we already had a total redesign of the NVDA in the past. Tutorials need to be updated then, and the user guide of NVDA has precedence over other tutorials out there. The user guide is translated in so many languages, so people will be able to update tutorials accordingly.

Look for example how Windows or Microsoft Office changed over the last years and to be honnest, I am glad that we are not sticking with the Windows XP design or the Office 2003 design. Although they certainly had also some advantages, the new designs are by far more accessible, especially the settings area of windows compared to the old control pannel.
