### ISSUE TITLE
NVDA with wasapi does not reload current audio device on enter in audio settings panel

### ISSUE THREAD

**Issue by cyrmax** [nvaccess/nvda#15759]
### Steps to reproduce:
* Switch NVDA to wasapi mode;
* In audio settings panel select not default audio device;
* Disconnect this audio device;
* NVDA should fall back to default device;
* Reconnect selected audio device again;
* Open audio settings panel and see that your custom audio output is still selected;
* Press enter to re-apply settings.

### Actual behavior:
NVDA does not switch back to custom audio device when it reconnects and does not try to reapply custom audio device setting when opening audio settings panel and pressing enter.
When not using wasapi, NVDA automaticaly tries to switch back to custom device when it reconnects or at least recovers it when pressing enter in audio panel.

### Expected behavior:
Wasapi behavior should be identical to the old audio behavior.

### NVDA logs, crash dumps and other attachments:
[nvda2023-11-08.log](https://github.com/nvaccess/nvda/files/13300555/nvda2023-11-08.log)

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
alpha-29899,cb356535 (2024.1.0.29899)

#### Windows version:
Windows 11 23H2 (AMD64) build 22631.2506

#### Name and version of other software in use when reproducing the issue:
N/A.

#### Other information about your system:
N/A.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Any NVDA version with wasapi.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
Implementation thoughts:

1. Change wasPlay_getDevices so that it lists all devices, not just active ones.
2. This will mean that WasapiPlayer is created with the device id of the preferred device, even if that device is unavailable, allowing us to manage that in the C++ code.
3. Change WasapiPlayer to detect whether the specified device is unavailable, either by using error codes or by explicitly checking the device state.
4. If the device is unavailable, fall back to the default device, but keep track of the preferred device id.
5. In NotificationClient, track device state change notifications in the same way we track default device changes.
6. In WasapiPlayer::feed, handle device state changes similar to how we handle default device changes.
7. If a device state change occurs, check if the preferred device is available. If it is, switch back to that.
