### ISSUE TITLE
Firefox: Reviewing characters in edit field Sometimes Repeat

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1582]
**Reported by kevinchao89 on 2011-06-17 14:37**
Snapshot 4457
Firefox 6 Nightly 7.0a1 (2011-06-17)

When in GMail, NVDA dev New ticket, text edit fields, reviewing text by characters using LEFT/RIGHT ARROW will sometimes result in NVDA repeating characters. 

While, this doesn't occur all of the time, resulting in it being difficult to reproduce, it does occur to a high enough regularity that it results in editing out wrong characters. 

A factor that seems to have some influence is if Firefox isn't maxamized, this double speaking of characters when reviewing may occur.

**Comment by leonardder** [comment]
@DerekRiemer: As you use GMail daily, would you like to treat this ticket?

**Comment by jcsteh** [comment]
This should be addressed by #6424. Closing as duplicate.

**Comment by zahra21** [comment]
hello.
i downloaded nvda 2017.3 and tried my gmail to see whether some bugs about typing and etiting texts in edit boxes are fixed or not.
after installing nvda 2017.3, i realized repeating some characters, words line when i wanted to navigate in the message which i typed in my gmail is not fixed.
so, i think this bug is not duplicate of bug 6424 and should not be closed as duplicate.
because i confirm that the issue is still persists!
i forgot to mention that i have this issue in using other edit boxes in firefox and the problem is not specific for composing emails in gmail!
God bless you all and his infinite mercy and blessings i pray for you in my five times obligatory daily prayers and other times!
