### ISSUE TITLE
Math expressions not read in browsers

### ISSUE THREAD

**Issue by Molitvan** [nvaccess/nvda#15829]
### Steps to reproduce:

- Find a website with a mathematical expression on it e.g. [this one](https://chat.openai.com/share/e5a8a32c-a357-45fa-87e1-2620429aa71d)
- Navigate to the part where the expression should be

### Actual behavior:

When you navigate to the expression, NVDA pauses like something is there, but doesn't actually read anything. I've tested this with multiple websites and browsers (both Firefox and Chromium based).

### Expected behavior:

NVDA should read the expression like it would any other text.

### NVDA logs, crash dumps and other attachments:

N/A

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.3

#### Windows version:
Windows 11 23h2

#### Name and version of other software in use when reproducing the issue:
Firefox 120
Chromium 107

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by thgcode** [comment]
Hello!
I'm not a part of the NVDA development team, but I use [the access8math addon](https://addons.nvda-project.org/addons/access8math.en.html) to read math equations. I tested on the website you provided and it works. However, I think this issue is very critical because on NVDA's current state without the addon, NVDA will speak nothing. It would be nice if NVDA could include a math reader builtin or offer the option for the user to download one, the access8math addon for example, so the user could read the equation without NVDA being stuck.

**Comment by seanbudd** [comment]
Have you set up [MathPlayer](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ReadingMath) yet?

**Comment by Molitvan** [comment]
Thank you. It works with the Access 8 Math add-on.

**Comment by seanbudd** [comment]
@Molitvan - does it worth with MathPlayer set up, and without the add-on?

**Comment by mitchellevan** [comment]
> @Molitvan - does it worth with MathPlayer set up, and without the add-on?

For what it's worth: my NVDA announces MathML content after I've installed MathPlayer 4 per [NVDA documentation for adding math support](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ReadingMath).

However, the setup documentation has an issue. https://github.com/nvaccess/nvda/issues/16036

**Comment by Adriani90** [comment]
Closing as invalid since it works when Mathplayer is installed properly.
