### ISSUE TITLE
Unavailable is announce when an element like a Button gets disabled property.

### ISSUE THREAD

**Issue by tovimx** [nvaccess/nvda#15870]
Steps to reproduce:

Open NVDA
Go to https://codepen.io/tovias-torres/pen/poGQewj
Position the focus using tab key on the button element.
Press "enter" key.

Question: is it expected that NVDA states "unavailable" for disabled elements?

Actual behavior:
```
Click me! button
unavailable
```

Expected behavior:
` 
Click me! button
`

NVDA logs, crash dumps and other attachments:

System configuration

NVDA installed/portable/running from source:

NVDA version:

2023.3.029780 but it was also happening in previous version.

Windows version:

11 pro

Name and version of other software in use when reproducing the issue:

Firefox

Other information about your system:

Other questions

Does the issue still occur after restarting your computer?

yes

Have you tried any other versions of NVDA? If so, please report their behaviors.

I believe is just in last recent version. No tested in others versions.

If NVDA add-ons are disabled, is your problem still occurring?

not tested

Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

no

**Comment by hwf1324** [comment]
If there is no status of the report button, how would a person without vision know the status of this button?

Of course, in Chromium, the behavior of NVDA 2023.3 seems to ignore disabled buttons.

**Comment by Brian1Gaff** [comment]
Well, say for instance that you are on nextdoor.com where you have created a message, the reply or whatever button is unavailable, since youhave just done a reply.
 Is this the kind of thing you mean?

To me it seems logical.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: Tovias Torres 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Sunday, December 03, 2023 5:26 AM
  Subject: [nvaccess/nvda] Unavailable is announce when an element like a Button gets disabled property. (Issue #15870)



  Steps to reproduce:

  Open NVDA
  Go to https://codepen.io/tovias-torres/pen/poGQewj
  Position the focus using tab key on the button element.
  Press "enter" key.

  Question: is it expected that NVDA states "unavailable" for disabled elements?

  Actual behavior:

Click me! button
unavailable
Expected behavior:
  Click me! button

  NVDA logs, crash dumps and other attachments:

  System configuration

  NVDA installed/portable/running from source:

  NVDA version:

  2023.3.029780 but it was also happening in previous version.

  Windows version:

  11 pro

  Name and version of other software in use when reproducing the issue:

  Firefox

  Other information about your system:

  Other questions

  Does the issue still occur after restarting your computer?

  yes

  Have you tried any other versions of NVDA? If so, please report their behaviors.

  I believe is just in last recent version. No tested in others versions.

  If NVDA add-ons are disabled, is your problem still occurring?

  not tested

  Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

  no

**Comment by Emil-18** [comment]
It is supposed to say unavailable, because the buttons state changed from available, AKA the user can interact with the button, to unavailable, AKA the user can't tab to or activate the button

**Comment by tovimx** [comment]
Thank you closing the issue since this seems to be expected.
