### ISSUE TITLE
nvda alpha: error-stderr when we change tabs in the "add-on store" dialog

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#16065]
### Actual behavior:

Open "add-on store" dialog,
- type "control + tab" enough times to get the error.

This happens with or without add-ons enabled (see logs).
Also reproducible with nvda 2024.1beta.
### Expected behavior:

No error
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
NVDA version alpha-30663,3c7504eb
#### Windows version:
Windows 10 22H2 (10.0.19045) workstation AMD64
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same problem on nvda 2024.1beta
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
No tested
[nvda alpha with add-ons.log](https://github.com/nvaccess/nvda/files/13980447/nvda.alpha.with.add-ons.log)

**Comment by paulber19** [comment]
[nvda alpha without add-on.log](https://github.com/nvaccess/nvda/files/13980649/nvda.alpha.without.add-on.log)
the second log[nvda alpha without add-on.log](https://github.com/nvaccess/nvda/files/139
80625

**Comment by paulber19** [comment]
Hoping to have attached the logs this time

**Comment by CyrilleB79** [comment]
@paulber19 did you close this issue on purpose?

If not, you can reopen, But also update your initial description since some paragraphs are empty; maybe you have written in HTML comments? And a part of what should have remained commented or been deleted is visible. Thanks.

**Comment by CyrilleB79** [comment]
There are actually two issues here. I will close this issue in favor of the two following ones (@paulber19, sorry for the confusion):
* #15670: reopened because it contains more history, and more specifically the description of the issue before being impacted by #16070.
* #16070: opened for clarity after some investigations instead of the current one so that the issue related to writing to `sys.stderr` in another thread remains unrelated to any issue in the store.
