### ISSUE TITLE
Speechviewer not displaying content 

### ISSUE THREAD

**Issue by tapper82** [nvaccess/nvda#16175]
### Steps to reproduce:
Open Speechviewer you will not get any text displaying 
### Expected behavior:

You should get feed back in the Speechviewer 
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-3i030,421fe4ef (2024.2.0.31030)
#### Windows version:
windows 23h2 build 22635.3140
#### Does the issue still occur after restarting your computer?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by hwf1324** [comment]
Can you do more tests? For example how is the behavior of the portable version?

At least the temporary copy seems to work fine on my computer.

**Comment by Adriani90** [comment]
Please fill the request template with more details on how you came to this issue. I cannot reproduce.

**Comment by tapper82** [comment]
Why is this closed? I need some time to sleep you know!

**Comment by tapper82** [comment]
Speech viewer is working in the portable  build. Is there some debug  logs I can get my hands on for you?

**Comment by hwf1324** [comment]
How about with add-ons disabled? Maybe it's a problem with your config file?

**Comment by CyrilleB79** [comment]
@tapper82, for clarity, could you edit the initial description so that no section is empty?

Also, in the "Steps to reproduce", could you give more details? E.g. how do you know that the speech viewer is empty ? Are you sighted, or do you move the focus / cursor to read it ?

Then, could you try with a clean config, i.e.:
* press Windows+R
* type "nvda -c %tmp%\nvdaFolderThatDoesNotExist" (without quotes)
* press Enter
* Answer to the welcome and the stat dialog boxes
* Try to reproduce the issue

If the issue is still reproducible this way, could you provide a log at debug level ?
Thanks.

**Comment by tapper82** [comment]
So if I run a fresh config the speach viewer works as it should. Now I need to work out what is makeing it brake.

**Comment by tapper82** [comment]
So I have reset my configs. It is now working again. I don't know why it stopped working. sorry about the noise.
