### ISSUE TITLE
Add-on Store: "Community reviews" action should be available in Installed add-ons tab too

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#16179]
### Is your feature request related to a problem? Please describe.
"Community review" action is now available in beta for some weeks. Though people do not seem to use it.

There are two use cases to use it:
* read reviews from other users to decide to install (or update) an add-on or not
* write a feedback to let other people know what you think of an add-on that is already installed.

Or maybe sometimes people open the reviews page to gather opinions on an add-on but these pages are desperately empty.

I wonder if one reason why the feature is not used is that it is not visible enough.

### Describe the solution you'd like

To encourage the second use case, i.e. writing feedback, I'd ask that the action also appears in the context menu of add-ons in the "Installed add-ons" tab.

Indeed, if I am satisfied with the add-on, I will interact with it in the "Installed add-ons" tab.
If I am not satisfied, I will also launch the removal from the Installed add-on tab.
At last, the Installed add-ons tab is the most important because it's the one that open when starting the add-on store.

### Describe alternatives you've considered
Other solutions to promote the feature may be:
* a better integration of the feature in the store, i.e. have the review page displayed in the store, without the whole GitHub menu
* An automatic translation of the reviews page with a translation widget, automaticially using NVDA's language.
* advertising the feature on the lists or in In-process

### Additional context
The feature will be launched generally with NVDA 2024.1. I'd suggest that this request be integrated as soon as the feature is available, i.e. have it implemented in beta (cc @seanbudd). Indeed, it would mitigate the risk of a bad first impression.

Also cc @nvdaes

**Comment by nvdaes** [comment]
I think that the main reason because this is not used is that reviewing add-ons implies a great responsibility and it's something hard to do. Furthermore,there's no standardized process and people may not be sure about what to include in reviews.
For me, the best way to promote this is to participate in add-ons review. I reviewed Windows App Essential and MathCAT.
But imo this shouldn'tbe included in the installed tab,since add-ons from externalsources cannot be reviewed in the store. GitHub has buttons to translate discussion.This maybe promotedin In-Process, @Qchristensen . Anyway, for example I use just a few add-ons, and many of them are maintained by me, so I shouldn't review other add-ons. I think that this won't be very used since reviewing add-ons is really difficult. But regarding your request I think that the only tabs where it can be implemented for all add-ons are Available and updatable.

**Comment by CyrilleB79** [comment]
I am not sure to understand what is expected in this reviews discussion:
* opinions on the add-on, such as the comments that we can find on Google Play Store
* or an add-on review, such as what was required a few years ago to accept an add-on on the community website

**Comment by nvdaes** [comment]
according to the user guide, users can provide feedback, so this is not anything technical. In the Windows App Essential addon I left an horay reaction,, and in mathCath, I higligted the support for braille CMU. But imo putting this in the installed add-ons tab maybe confussing, since an add-on maybe deleted, in addition to be installed from external source, so we may be sure that the reviewed add-on is available (or updatable).Enviado desde mi iPhoneEl 15 feb 2024, a las 22:05, Cyrille Bougot ***@***.***> escribió:﻿
I am not sure to understand what is expected in this reviews discussion:

opinions on the add-on, such as the comments that we can find on Google Play Store
or an add-on review, such as what was required a few years ago to accept an add-on on the community website

**Comment by CyrilleB79** [comment]
OK, thanks. So I had understood the concept correctly.

My proposal is that the action also appears in the Installed add-on tab, but also still remain in the available tab (and the updatable tab). To summarize, I want to add it in one more tab.

**Comment by nvdaes** [comment]
Imagin that I"m interested in reviewing charInfo (probably I"ll do it this weekend), and you decide to remove it from the store. Even if the add-on metadata has a reviewUrl, I think that the add-on doesn"t need to be reviewed if it"s not longer available, and the only tabs that provide info about currently available add-ons are available and updatable. So I"m not sure how this can be implemented to select the add-ons that should show the review option in the installed tab, and if the cost of implementing this, without a previous strategy to promote this feature, is useful in terms of prioritization.Enviado desde mi iPhoneEl 15 feb 2024, a las 23:04, Cyrille Bougot ***@***.***> escribió:﻿
OK, thanks. So I had understood the concept correctly.
My proposal is that the action also appears in the Installed add-on tab, but also still remain in the available tab (and the updatable tab). To summarize, I want to add it in one more tab.

**Comment by XLTechie** [comment]
@nvdaes I would suggest, that even if an add-on is removed from the store, past 
reviews should not be deleted.

The add-on may be re-added to the store at a later time.
In fact, if there are bad reviews, this may be a method for an author to cause 
bad reviews to be deleted and start over with a clean review history.

They will not be linked from anywhere if an add-on is removed, but a record 
should be kept to re-associate the old reviews with a new add-on of the same 
name and submitter.
This may have to be a manual process, but this situation should be rare.

**Comment by nvdaes** [comment]
of course reviews aren"t deleted: they remain forever on the GitHub discussion page. But here we discuss if the review action should appear in the installed add-ons tab. I argue that this may not be very convenient, since this tab can include add-ons installed from external sources, and add-ons removed from the store, that in fact cannot be reviewed, since reviews are related to the store, not to external add-ons, and so if an addon is not longer available, I think that the review action shouldn"t be presented. So, imo this maybe closed as not planned. Anyway, we may promote this feature, that in fact I contributed since i read complains on a mailing list about the lack of security of the store due to add-ons submitted without reviews. people previously complained about the slow flow of the previous system, probably due to reviews, so these complains shouldn"t be the main reason to implement a feature, but this was also requested by constructive people years ago, and if we want to promote it, the best way, imo, is to participate in reviewing add-ons ourselves.Enviado desde mi iPhoneEl 16 feb 2024, a las 7:23, Luke Davis ***@***.***> escribió:﻿
@nvdaes I would suggest, that even if an add-on is removed from the store, past 
reviews should not be deleted.

The add-on may be re-added to the store at a later time.
In fact, if there are bad reviews, this may be a method for an author to cause 
bad reviews to be deleted and start over with a clean review history.

They will not be linked from anywhere if an add-on is removed, but a record 
should be kept to re-associate the old reviews with a new add-on of the same 
name and submitter.
This may have to be a manual process, but this situation should be rare.

**Comment by XLTechie** [comment]
@nvdaes either we have a failure to communicate, or I am confused.

If an add-on has been removed from the store, what prevents a user from 
*reading* reviews of it?

If the answer is "nothing"--that is, if the action would still work in that 
circumstance--then I do not understand that as a reason to disapprove of this 
feature request.

That would leave only the external add-on question. For that, I think the answer 
is simple: don't offer the action if the add-on is external.

**Comment by nvdaes** [comment]
> If an add-on has been removed from the store, what prevents a user from
*reading* reviews of it?

Nothing. You have convinced me with this argument.
Anyway, we should promote this feature, since working on it if the existing feature is not very used may not be grateful. And for me the main reason cause people don't use this is that it's a very difficult task.

**Comment by CyrilleB79** [comment]
@nvdaes you write:
> I think that the main reason because this is not used is that reviewing add-ons implies a great responsibility and it's something hard to do. Furthermore,there's no standardized process and people may not be sure about what to include in reviews. For me, the best way to promote this is to participate in add-ons review.

and:
> according to the user guide, users can provide feedback, so this is not anything technical. In the Windows App Essential addon I left an horay reaction,, and in mathCath, I higligted the support for braille CMU.

and also:
> And for me the main reason cause people don't use this is that it's a very difficult task.

Could we clarify what is difficult in the task of writing reviews? @nvdaes have you something very specific in mind?

Having an opinion on an add-on does not seem something very difficult: there are many people talking of add-ons on the mailing lists, and why they love them or not.

**Comment by nvdaes** [comment]
> Could we clarify what is difficult in the task of writing reviews? @nvdaes have you something very specific in mind?

Maybe my own experience from about 2013. Maybe comment from people saying that they didn't want to receive comments about how to write add-ons, or people making bad criticism about reviewers who say that a particular add-on maybe dangerous. Maybe my own experiences. Hope I'm wrong. But the fact is that this is not used, I think.
For me reviewing add-ons is difficult since I try to look at the code, total or partially, though I don't provide technical opinions. I have dedicated many hours to review add-ons in the past, so I may be talking about myself 😃

**Comment by CyrilleB79** [comment]
But we are mixing two things here.
I was not active in 2013 in NVDA add-ons community; but I guess it was more a matter of technical review. The community reviews action instead is meant to be opinions from user, as I understand it.

**Comment by nvdaes** [comment]
> The community reviews action instead is meant to be opinions from user, as I understand it.

Yes, but if a person can analize the source code, it may be considered in the opinion.
At least personally I look at the code, in case performing the proposed commands, for example, has something not expected and not shown inmediately.

**Comment by nvdaes** [comment]
Also, if a person doesn't like an add-on, probably she or he won't use it and so it won't be reviewed.
I'm thinking about an add-on that for me would get a bad review, but simply I won't use it. Hope this feature can be more used.

**Comment by lukaszgo1** [comment]
IMO the main barrier to reviewing add-ons is the simple fact that they are done on GitHub. For a standard user this means they have to create an account on the website they will never use, which also is not in their mother tongue for many. In other cases i.e. Apple or Google stores the entire reviewing interface is localized, but you also have to create an account to use the store at all, so there is less intermediary steps before reviewing.

**Comment by nvdaes** [comment]
Anyway, users that have GitHub accounts seem not to use this feature now, and Iwonder if creating a server infrastructure to review add-ons from the store should be prioritized if people who may review add-ons in the same platform where NVDA is developed are not leveraging this.
BTW, I'mlooking at the source code, and I don't understand why the review action and details are not presented in the installed add-ons tab. For me was logic thinking that just available add-ons should show the reviews action, but now that I'm thinking in this issue, I don't know what's roducing this, since I tried to implement this in a similar way respect the license URL, which is also optional.

**Comment by XLTechie** [comment]
I think looking at the code is a minority problem though. I think most people 
will be thinking of user experience in these kind of reviews.

I've been both busy and sick repeatedly since Christmas, so I have lost track of 
how NV Access has promoted this feature on mailing lists and such, as mailing 
lists have not been a priority.

But if the promotion has not been high, I wouldn't expect much up-take of the 
feature yet. The store interface itself is new, I don't think we can expect too 
much yet.

Also, many many people have an unwarranted, but very real, fear of using GitHub. 
They find it baffling and can not seem to grasp doing even the most simple 
things on it.
As developers, I think that is hard for us to see, because we are on it nearly 
every day, and understand the format of the site.
but that is not the case for people who are on it maybe once per year.

That is why I have objected to doing reviews on GitHub from the start, and that 
is one of the reasons I believe it has not gotten much used.

I do not say that I have a better way, because various cross boarder laws 
make a review system difficult, so out-sourcing the compliance to GitHub is very 
understandable. But I doubt it will ever get the kind of acceptance that a 
dedicated, simple, reviews website would get.

I even started work on one, using cloud infrastructure and applets, at the same 
time you were developing the current reviews system. However (1) you were 
working faster than me; (2) nobody even responded to my suggestions about not 
doing it on GitHub; and (3) I realized that collecting usernames and such might 
be a problem with the U.S. Know Your Customer law, and the EU's GDPR.

**Comment by XLTechie** [comment]
@nvdaes wrote:
> Also, if a person doesn't like an add-on, probably she or he won't use it and so it won't be reviewed.

If a person doesn't want to try (doesn't need) an add-on, sure. However if a 
person uses, and doesn't like, an add-on, they are probably more likely to leave 
a review than if they used it and liked it.

That is something found in reviews in all contexts: a bad experience is much 
more likely to provoke someone to write a review, than if the thing does what 
the user expects of it based on its description.

Please read: 
https://rizereviews.com/why-people-are-more-likely-to-leave-a-negative-review-than-a-positive-review/

**Comment by nvdaes** [comment]
Hi Luke, first of all, hope you're well.
I'll read your suggested article. Personally, maybedue to my experience, I'm quite reluctant to leave bad reviews. Generally I'm not a person with a special fear to receive criticism from people that don't provide enough arguments, but I consider that add-ons are diverse, and people with low experience  can participate to introduce themselves in NVDA's development, so I try to understand if someone seems to have submit an add-on to the store just for testing, like the add-on that I have in mind, which seems to have copied code from other add-on without too much criteria, just a piece and with dirty code, at least under my impression. I would leave a bad review since there is a better add-on, but please this is just an example and I looked at this months ago, and something may have changed from then, or I may have missed something. But you are probably right and bad reviews are more frequent.
In issue #15776 , Sean wrote:
>  Though, the best way to do this would be if NV Access creates our own server backend and reviews exist within the store.
However, this would be a major piece of work and is unlikely to be completed in the near future.

Also, GitHub is where NVDA is developed and even some tutorial has been shared about how to create issues, since users may want to report erros about NVDA. But I think that this feature hasn't been promoted.

**Comment by Nael-Sayegh** [comment]
Hello,
I just read this issue.
I feel like 2 concepts are being mixed up, the act of revising an add-on's code, and the act for a user to give their feedback.
From what I understood, the function is rather intended for users to give their feedback.
I get the impression that @nvdaes  is talking about his experience as a developer and not as a user.
Indeed, this function is not very used at the moment, for 2 reasons in my opinion:
-There hasn't been a publication about it on mailing lists, at least in France no one has talked about it
-The creation of a GitHub account which can pose a problem, but since GitHub allows you to connect with a Microsoft account, many people will be able to easily connect because the majority of people have a Microsoft account
Going back to the initial topic, I agree with @CyrilleB79 's suggestion to add the option in the tab for installed add-ons, I actually think it will make this option more popular.
And for external add-ons, it is just a matter of not displaying it for them.

**Comment by Adriani90** [comment]
@Nael-Sayegh Re external add-ons, it is not that trivial. In the installed add-ons tab, the user should actually know imediately when focusing an add-on whether there is a review page for it or not. I mean for people who have 30 add-ons installed, where 15 are external, they would have to open the actions menu for each of them to see if there is a review page available.
Maybe it makes sense to split the installed add-ons tab into two lists, one with reviewable add-ons, and one with add-ons without a review page.
Maybe called "submited add-ons list" and "external add-ons list".
Or even better, there could be a new filter combo box in the installed add-on tab called "source" where users can filter their list of add-ons between submited add-ons and external add-ons to find easier those with review page.

**Comment by CyrilleB79** [comment]
> @Nael-Sayegh Re external add-ons, it is not that trivial. In the installed add-ons tab, the user should actually know imediately when focusing an add-on whether there is a review page for it or not. I mean for people who have 30 add-ons installed, where 15 are external, they would have to open the actions menu for each of them to see if there is a review page available.

If you want to read a review or leave a comment for a specific add-on, you select it in the list, open the context menu and check if there is a review item in this menu:
* if yes, click it and read/write comment
* if no, you will not be able to do anything; wether you are in the installed add-ons tab or in the available add-ons tab does not matter nor change anything.

@Adriani90, what is the problem?

**Comment by Nael-Sayegh** [comment]
@Adriani90 I don't understand the problem you are talking about. Generally, the user knows whether the installed add-on is an external add-on or not, otherwise, the information is also indicated in the add-on's summary, so the user has all the elements to know the origin of the add-on. What do you think?

**Comment by Adriani90** [comment]
Well you have to check for every add-on in its actions menu whether there is a review feature available or not. I wonder if there could be a status column or a filtering possibility to find easier add-ons with and without review feature. So just making it an item in the context menu is one thing, but the easy way of finding such reviewable add-ons is not there yet. But yeah, that’s probably a different issue.Von meinem iPhone gesendetAm 05.04.2024 um 14:12 schrieb Cyrille Bougot ***@***.***>:﻿

@Nael-Sayegh Re external add-ons, it is not that trivial. In the installed add-ons tab, the user should actually know imediately when focusing an add-on whether there is a review page for it or not. I mean for people who have 30 add-ons installed, where 15 are external, they would have to open the actions menu for each of them to see if there is a review page available.

If you want to read a review or leave a comment for a specific add-on, you select it in the list, open the context menu and check if there is a review item in this menu:

if yes, click it and read/write comment
if no, you will not be able to do anything; wether you are in the installed add-ons tab or in the available add-ons tab does not matter nor change anything.

@Adriani90, what is the problem?

**Comment by Adriani90** [comment]
Yes, but if we assume all submited add-ons have review features and external add-ons don‘t, maybe it is easier to filter the list to see only reviewable add-ons for an user who has 30 add-ons or more installed. Maybe I can explain this better in a separate request after the review action is added to the installed add-ons.Von meinem iPhone gesendetAm 05.04.2024 um 14:30 schrieb Nael Sayegh ***@***.***>:﻿
@Adriani90 I don't understand the problem you are talking about. Generally, the user knows whether the installed add-on is an external add-on or not, otherwise, the information is also indicated in the add-on's summary, so the user has all the elements to know the origin of the add-on. What do you think?

**Comment by Nael-Sayegh** [comment]
@Adriani90  One can already filter add-ons by channel, in the list of channels one can choose among all/stable/dev/beta/external which allows for grouping the add-ons. Also, one can see the channel of an add-on in the list of installed add-ons directly like this: ObjectStudies, IA, IA2; Status: Enabled; Installed version: 2.1; Channel: External; Author: Pierre-Louis R This way one can see that the add-on is external and that there's no discussion to leave a review. Is this what you were talking about?

**Comment by Adriani90** [comment]
Kind of yes, but you cannot filter out the external add-ons so that the list contains only submited reviewable add-ons. Or am I wrong?Von meinem iPhone gesendetAm 05.04.2024 um 17:35 schrieb Nael Sayegh ***@***.***>:﻿
@Adriani90  One can already filter add-ons by channel, in the list of channels one can choose among all/stable/dev/beta/external which allows for grouping the add-ons. Also, one can see the channel of an add-on in the list of installed add-ons directly like this: ObjectStudies, IA, IA2; Status: Enabled; Installed version: 2.1; Channel: External; Author: Pierre-Louis R This way one can see that the add-on is external and that there's no discussion to leave a review. Is this what you were talking about?

**Comment by XLTechie** [comment]
Keep in mind, that external add-ons often do have a review page. For example, 
anything installed through add-on updater currently shows as external, even if 
it was originally internal.
Many of those will have review pages.

Also, anything installed from a link will show as external, even if the same 
version is in the store.

I am starting to wonder if we should add a manifest item to provide the reviews 
URL, so that external add-ons can direct people as well.
This is a separate issue however.

**Comment by nvdaes** [comment]
I think that we should exclude external add-ons from the review action, since add-ons in the store should have a unique name for the same add-on. Instead, an external add-on can have a name equal to other completely different add-on available in the store. If an author want to provide a page to review an external add-on, the add-on may provide a mechanism to do it even if it is not published in the store. What do you think, Luke?

**Comment by XLTechie** [comment]
@nvdaes
> Hello, this is triaged. Seems I've fixed this locally. I'll create a PR for this. External add-ons will be excluded.

Oh good. I took a stab at fixing this a few weeks ago, but ran out of time 
before figuring out where the reviewURL was being excluded from the install 
section's picture of the add-on metadata.

**Comment by nvdaes** [comment]
Great @XLTechie . Then I'll proceed now with the PR to be tested by the community.

**Comment by cotaskitsolutions** [comment]
I fully support the inclusion of the Community reviews action in the Installed add-ons tab as well. It would undoubtedly improve UX by making it simpler to access a review while not having to navigate back to the store. It would also enable users to make more informed decisions about whether to keep or remove add-ons. [cotask ](https://cotasks.com/why-you-should-analyze-customer-reviews-and-how-to-do-it/)can helpful! but some of the technical constraints are that are stopping this from being implemented.

**Comment by FreedomSEO** [comment]
IMO the main barrier to reviewing add-ons is the simple fact that they are done on GitHub. For a standard user this means they have to create an account on the [website](https://www.freedomseo.ca/) they will never use, which also is not in their mother tongue for many. In other cases i.e. Apple or Google stores the entire reviewing interface is localized, but you also have to create an account to use the store at all, so there is less intermediary steps before reviewing.
