### ISSUE TITLE
disable screen saver while NVDA is reading longer pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1617]
**Reported by cardsfan22 on 2011-06-27 22:41**
Other than disabling the screen saver, is there a way to have the screen scroll while NVDA is reading a longer website or document?  This would prevent the screen saver from popping up and interrupting the reading.  This would come in handy for reading books online or lengthy documents.  Thank you for your continued dedication.

**Comment by bhavyashah** [comment]
@jcsteh Since cardsfan22 has answered your initial questions in https://github.com/nvaccess/nvda/issues/1617#issuecomment-155291204, could you please triage this ticket?

**Comment by Adriani90** [comment]
This will impact performance since the screen has to scroll in web documents which can cause lags. Especially in webpages with dynamic web content.

Screen safer can be disabled in Windows, in most cases in energy settings. If someone implements this function though, this needs thorough testing on different systems.

**Comment by Adriani90** [comment]
But I would prefer to disable screen safer in Windows rather than having performance issues on complex websites.

**Comment by Adriani90** [comment]
@leonardder I recall that you submited a PR to solve something like this, I think it was related to braille but maybe it fixed also this issue. Can you confirm?

**Comment by Adriani90** [comment]
Closing this in favor of #14036 which is newer and requests the same feature.
