### ISSUE TITLE
speech modes. When unchecking the talk speech from the list, in the alert that showes up, there is no checkbox to for don't show this again, and we have to see that alert always

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#16190]
### Is your feature request related to a problem? Please describe.
when we uncheck the "talk" option from the available speech list, a dialog contaning a question appears, but we are forced to see that dialog everytime we uncheck that
### Describe the solution you'd like
like all other dialogs, besides the yes and no buttons, in that dialog, there should be a checkbox, called don't show this again checkbox
### Describe alternatives you've considered
there are currently no alternatives, and sadly we are forced to have this dialog always
### Additional context
if possible, please do this in next beta, so we will have this in 2024.1 releace. This is not a feature request, it's something because i don't want to see this dialog everytime i uncheck the talk checkbockx

**Comment by lukaszgo1** [comment]
How often you're unchecking the 'talk' mode? This dialog was kept pretty simple intentionally, as we thought 'talk' mode will be unchecked very infrequently.

**Comment by amirmahdifard** [comment]
@lukaszgo1 i uncheck it a lot, as so many difrent family members happen to use my computer. In those cases, i only keep off and on-demand mode checked, and uncheck the others

**Comment by lukaszgo1** [comment]
Just to be clear I fully understand your use case: why you need to change the list of modes available in the `NVDA+S` command when passing your computer to, I assume sighted, family members? Isn't it sufficient to always have the 'no speech' and 'talk' modes enabled and switch between them as needed?

**Comment by amirmahdifard** [comment]
@lukaszgo1 i told you how this works in my sichooation and why i need this, but the thing you asked me is personal, so sadly i cannot tell you that, just if you are willing to implement this, you can do it, and if you can't, you can close this issue. I just told you my need as an NVDA user. Thanks.

**Comment by josephsl** [comment]
Hi,

Intervention: I think the way the last comment was phrased says something different. Asking people to do it if they are willing, along with the issue be closed if people can't implement it is, to me, amounts to asking people to simply do it. While I, too, see the benefit of this feature request, may I suggest that we give folks a chance to gather data before deciding if they can do it rather than just asking people to give us whatever we want and need?

Thanks.

**Comment by lukaszgo1** [comment]
@amirmahdifard  Quite often users assume that whatever solution they have in mint is the best one, without providing the full context. Doing so is helpful, because when discussing we may come up with a different solution completely. When implementing the list of available speech modes it was assumed that this is something which is going to be set just once, and that almost no one is going to disable the 'talk' mode. Your report seems to invalidate these assumptions, so we would like to understand what is the use case. As an example: it was assumed that only  group of user for whom disabling the 'talk' mode will be useful are magnification users, and since they will do that once the warning will not be annoying. It also was considered not to warn at all, which may or may not be better in your situation. If you are unwilling to provide more context that is obviously fine, but it also means this is very likely not to get implemented. At last while I don't consider my question (as it was simple 'why you are changing list of speech modes so often') very personal, I would like to apologize if it crossed a boundary for you, it certainly was not my intention, as I'm myself not too kin on sharing too much about myself over here, as GitHub bug tracker is not a right place for personal confessions.

**Comment by amirmahdifard** [comment]
@josephsl i'm sorry if my comment made you to mis understand me. I didn't mean to do that, i just couldn't provide more information for this, and i won't force or hound anyone for anything. As like other users, i also opened a suggestion and i won't force anything. after i opened this, then staff members and developers can decide what will they do with it. Again, i'm sorry for the mis comunications.

**Comment by amirmahdifard** [comment]
@lukaszgo1 it's ok, if you think so, i can close this issue, because i sadly can't provide more information, and i don't wish to cause problems or mis understandings

**Comment by CyrilleB79** [comment]
To implement this, we need to understand exactly which problem it is trying to solve, and what would be the use case for this. Personally, with the information provided in this issue, I am not yet able to answer these questions.

@josephsl, since you too can see the benefit of this feature, would you be able to describe it as a use case, a user story and a description of the problem being solved?

@amirmahdifard, you are not forced to give personal information of course. If you wish (and can), you can describe use cases a user stories to help us understand. In the user story, you can just indicate "Sighted user 1", "sighted user 2", "blind user 1", "visually impaired 2", etc. without indicating if it corresponds to you, to friends you are helping or to imaginary persons.

**Comment by XLTechie** [comment]
While I too can see value in this idea if we can better understand why users 
would need to do this frequently, I do have an alternative thought.

@amirmahdifard Have you considered turning on sleep mode when your family is 
using the computer? That would be a better experience for them anyway, I would 
think.
NVDA+Shift+s on a desktop keyboard.

**Comment by amirmahdifard** [comment]
yeah actually, i was requesting this because i thort this dialog should be able to be skipped, to provide  eas usage. But now i'm convinced that it's ok for me to just press yes button quickly to skip that dialog, rather than waisting developer's times for implementing this, as they can spend that time to implement more useful things, as we have a lot of nvda users with a lot of their needs, as we have over 2400 issue open here, and so i fully understand this. Thanks everyone for your help, i'm going to close this issue, because i don't think that this issue is worth developed
