### ISSUE TITLE
Expand scope of Speech on Demand

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#16328]
### Is your feature request related to a problem? Please describe.
More a limitation than a problem.  I have found the Speech on Demand setting to be potentially very helpful when a page constantly updates.  It would be more helpful if a wider range of review commands would speak.  
### Describe the solution you'd like
Commands for switching review mode would speak, together with the full range of review commands.  These include previous and next lines of the navigator object and previous and next objects in a flattened view.
### Describe alternatives you've considered
Perhaps a setting for adjusting which features talk, but that is adding complexity.
### Additional context
Nothing comes to mind.

**Comment by XLTechie** [comment]
CC @CyrilleB79

**Comment by CyrilleB79** [comment]
Hi @andrew-l-d 

At first glance, I would not be in favor of adding review commands such as next/previous char/line/word to on-demand mode because it would add confusion for users to know which commands are available in on-demand mode and which are not.

However, I acknowledge that you have a use case where the current modes are not satisfactory and this needs to be addressed. To help us understand this use case, have you examples of such webpage to provide?

Before describing a new feature, it would be very valuable to describe the limitation of existing features:
* why can't you simply use normal speech mode on such pages? What is the drawback?
* why can-t you use current on-demand mode on such pages? What is the drawback?

**Comment by XLTechie** [comment]
>  *  why can't you simply use normal speech mode on such pages? What is the drawback?

Including NVDA+5, to silence live regions?

**Comment by andrew-l-d** [comment]
Yes, there are ways of working around the issue I raised specifically.  However, as it stands the Speech on Demand offers very little.  Why just some NVDA commands are available and others are not is more confusing than including most or all.  But I admit defeat and will close the ticket.

**Comment by CyrilleB79** [comment]
> However, as it stands the Speech on Demand offers very little. Why just some NVDA commands are available and others are not is more confusing than including most or all.

Maybe the use case of speech on-demand is not clear for you. While in on-demand mode, you should be able to perform all actions without any speech feedback, e.g. because you want to hear something else such as a conference call. Only the commands that perform no action speak in this mode. This means that in this mode, if NVDA speaks, it's because you have asked it to explicitly. When using on-demand mode, you should be able to perform the majority of actions without audio feedback, e.g. because you have some sight remaining, or because you are able to execute known commands blindly.

Note that the commands where on-demand mode is available is more or less the same as the ones available in the equivalent Jaws feature.

If you think that the use case of this mode is not clearly described in the User Guide, maybe we should rephrase it. Feel free to ask for explanations on this feature so that you understand well the use case and to provide suggestions to rephrase the documentation.
