### ISSUE TITLE
Add a displayName field or reuse addonName for title in addonStore

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#16634]
### Is your feature request related to a problem? Please describe.
There is a missunderstanding how addon titles are beeing displayed inside addonStore.
This question was arised in the addons mailling list in this [discussion](https://nvda-addons.groups.io/g/nvda-addons/topic/106345030).
 lots of things were discussed, but the main problem is that if titles are allowed to be translated, it becomes very hard to browse an addonStore for the people who previously knew, that for example, addon names Instant translate or Weather plus, after several years, was translated into some language, and because of using summary as displayName in addons store, it will be like "Мгновенный перевод" or "Погода" in russian, when users past experience is gone, and they will need time to understand what happened, because first letter navigation for instant translate or weather plus (i and w) correspondigly won't work anymore.
### Describe the solution you'd like
Instead of displaying addon summary in the first place, I propose to add an additional displayName, or reuse addonName field, however the former would be better, because addonName is meant to be an addonID, to be displayed before translatable summary, in an untranslatable, original form.
### Describe alternatives you've considered
None

**Comment by nvdaes** [comment]
I support this proposal for the mentioned reason.
Imo, the add-on id maybe displayed in the first column, if an additional field seems cumbersome.

**Comment by CyrilleB79** [comment]
I'd prefer not to add a new name. There are already two concepts of name:
* the "ID" (in the store), formerly known as "name" in the manifest
* the "name" (in the store) formerly known as "summary" in the manifest

Adding a third "display name" would only add confusion. Moreover, if you add an untranslatable display name, there is no point in keeping the translated one.

Using the ID as main (displayed) name is not an option either. This field is before all an internal ID, and there are probably constraints on the characters used, e.g. do not use characters that are forbidden for file names. Many add-on authors would probably want to change their ID if it becomes the main name of the add-on (e.g. AVC, decimal2fraction, navsound, NotepadPlusPlus, objLocTones, pcKbBrl, thunderbirdPlusG5, winMag), and probably many of them would want to add spaces (if allowed) instead of CamelCase to make the add-on's name nicer and more appealing.
Also, it's worth noting though that using the ID in the search field will provide results, e.g. try to search for "instant" in the search field and you wil get Instant Translate.

There are two options in my view:
1. Keep things as they are today and ask translators not to translate the name of add-ons that are already known for long with their English name
2. Do not translate the add-on's name anymore and display the original name in the store. By the way, this original name may not be English in all cases, e.g. there are add-ons with no translation and a Spanish or a French name.

My personal preference goes for solution 1. Because the displayed name may record the name of an application which is translated on the user's system, e.g. "Windows Magnifier" is "Loupe Windows" in French because there is nothing called "Magnifier" on a French system, it's called "Loupe". Also, as written in the discussion, other stores (Google Play Store or Apple Store) already use translated names and it has not been a big problem.

**Comment by beqabeqa473** [comment]
As i pointed out, providing google playstore or apple appstore as an example is not good. It has its drawbacks, like two similar app names and if for sighted person icon can sort out things, for blind person, it could be a challenge.
We cannot tell do or not to do for translators and controll this for all addons.
There is problem in terminology, summary is short description and not a title for addon, and ideally this should be displayed just after title, which should be displayName.
For best view for all of us, it would be better to display addon display name in an original unchaged way, and for the short description, addon summary.

**Comment by britechguy** [comment]
I also don't support this concept, as stated.

The Add-On ID, while not presented in the main table in the add-on store, is shown in the pane specific to the add-on itself.  I would not object if Add-On ID were added as a column, but I don't even know if that's necessary though it might be preferable.

The Add-On Store search is described as follows in the NVDA User Guide: 
----
To search add-ons, use the "Search" text box. You can reach it by pressing shift+tab from the list of add-ons. Type a keyword or two for the kind of add-on you're looking for, then tab to the list of add-ons. Add-ons will be listed if the search text can be found in the add-on ID, display name, publisher, author or description.
----

Personally, I do think it would be helpful were the Add-On ID included in the "results table" in the Add-On store as an additional column, simply because many people are, in reality, searching on an add-on ID (whether they realize it or not) and not having that in the main results table makes it more difficult to determine whether you've found what you were searching for or not.

**Comment by josephsl** [comment]
Hi, another option, if a separate column is undesirable, is append add-on ID after add-on summary/title text (for example, Instant Translate (instantTranslate)). Thanks.

**Comment by britechguy** [comment]
> add-on ID after add-on summary/title text (for example, Instant Translate (instantTranslate)). Thanks.

A perfectly reasonable option, too.  The only change I'd make is that I don't prefer it as a parenthetical, Iid rather see something like (sans the square brackets, used here simply as delimiters): [Instant Translate | instantTranslate]

One could, of course, change order such that it would be presented as [instantTranslate | Instant Translate].  I worry, however, that any add-on ID that is in a language foreign to the reader, as opposed to the Display Name that has been language localized, coming first has the potential to make things more confusing, not less so.

**Comment by nvdaes** [comment]
I think that the add-on id should be placed before the add-on summary:

- This would ensure that a set of add-ons would be presented in the add-ons list always in the same order, regardless of the chosen NVDA language in different moments for the same person.
- Since the add-on id can be used to search add-ons, if it appears in a column (separate or in the same column that the add-on summary, people may know what to type if they want to search by add-on id, without going to the details panel, and they would know what an add-on appears in the search results if the add-on id was typed even unintentionally.
- In extreme situations, two different add-ons may have the same add-on summary, but the add-on id will be unique, so it makes sense that add-ons can be ordered and presented in the list according to the add-on id.
- The same add-on maybe translated in different ways, so we may have the same add-on with different translated add-on summaries if the add-on version changes, or translators decide to change the translation.

**Comment by britechguy** [comment]
Again, I see a terrible lack of precision here.    Here is what the respective "parts" of any Add-On Store tab are, and contain, with optional items or context dependent items enclosed in square brackets:
----- Results Table contains -------
(Display) Name
Status
[Installed Version]
[Available Version]
Channel
[Author | Pubisher]

---------  The individual pane for the add-on contains --------
Summary
Publisher
Author
ID
Installed Version
[Available Version]
Channel
Homepage
License
License URL
Download URL
Source URL
[Reviews URL]
-----------------------------------------------------------------

The Add-On Summary is not a part of the Results Table in any of the various Add-On Store Tabs.  It is always part of an individual add-on's pane content.

I have to presume add-on IDs must be unique, or else they're not IDs in any meaningful sense.  While it is remotely possible that a Display Name might end up being translated the same way for two different add-ons, the presence of the Add-On ID, whether concatenated with Display Name or in its own dedicated column, removes all possiblity of thinking that two add-ons that might have the same Display Name are one and the same.

The summary is "it's own thing" and is linked to one, and only one, add-on and that's the one that one has focus on in the results list at that moment.  In the event of multi-selection, all content in the pane section of the add-on store is removed.

**Comment by beqabeqa473** [comment]
The main problem in your suggestion is that first-letter navigation will stop working as soon as someone translates title.

**Comment by Adriani90** [comment]
What about letting a funtion detect your NVDA language and use a way to translate the titles automatically, similar to language names in NVDA general settings? This should be doable via a function in the manifest file I guess, maybe by importing an offline translation service like e.g. https://github.com/argosopentech/argos-translate

Not all languages are supported yet, but it seems people can request new languages to be added.
But for this NVDA would have to use it as a dependency.

**Comment by seanbudd** [comment]
Closing this as not accepted, given reasoning in https://github.com/nvaccess/nvda/issues/16634#issuecomment-2139549114 from @CyrilleB79
