### ISSUE TITLE
NVDA is not working properly on Chrome browsers reads it as Unknow or Chrome Legacy Window everytime

### ISSUE THREAD

**Issue by amiller157** [nvaccess/nvda#16700]
I am trying to use NVDA with Chrome all I hear either "Unknown" or "Chrome Legacy Window." I don't have any extention running. I can get Edge and Brave browsers to work with NVDA. I need to test a e-learning course on Chrome. I have turned off my anti-virus and I still have this issue. I don't have an IT department to help me; I am with a small company.

**Comment by Adriani90** [comment]
You need to open the NVDA menu e.g. with right click on NVDA icon in the system tray, then go to tools, and run the COM registration fixing tool. This will make sure the DLL files related to communication Object Model will be registered properly on your Windows system. NVDA needs properly registered COM DLL files in order to get information from Accessibility APIs.
I am closing this issue as invalid. If you still have this issue after running the COM registration fixing tool, please comment and we can reopen.
