### ISSUE TITLE
NVDA2024.3 - extremely slow in VS Code editors while in focus mode

### ISSUE THREAD

**Issue by kianoosh-shakeri** [nvaccess/nvda#17039]
### Steps to reproduce:

- Open a file in Visual Studio Code
    - The larger the file, the more obvious this issue becomes. In my case, the file is exactly 1526 lines
- Make sure that NVDA is in focus mode
- Simply navigate through the content of the file with the arrow keys

### Actual behavior:

Extremely slow responsiveness in VS Code editors. The larger the file, the slower it becomes.  
I have included a log file where I enabled the debug logging mode + time since input. My navigation through the opened file's content starts from line 265. Sometimes, the responsiveness is as slow as over 400 MS!

### Expected behavior:

Normal responsiveness in VS Code's editors.

### NVDA logs, crash dumps and other attachments:

[log.txt](https://github.com/user-attachments/files/16692221/log.txt)

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2024.3 Stable Release

#### Windows version:

Windows10 64-bit Version 22H2 (OS Build 19045.4239)
Also tested with the same result on Windows 11 24H2 (AMD64) build 26120.1350

#### Name and version of other software in use when reproducing the issue:

Visual Studio Code Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0

#### Other information about your system:

System with the Windows10 build:

- Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 CPUs), ~2.9GHz
- Memory: 12288MB RAM

System with the Windows11 build:

- Processor: 12th Gen Intel(R) Core(TM) i5-12400 (12 CPUs), ~2.5GHz
- Memory: 32768MB RAM

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

This issue does not exist in version 2024.2 Stable Release

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by SaschaCowley** [comment]
I'm unable to reproduce this with either NVDA 2024.3 or NVDA alpha-33464,df6bd077 (2024.4.0.33464). Attempted to repro by viewing [`source/NVDAObjects/IAccessible/__init__.py`](https://github.com/nvaccess/nvda/blob/df6bd0770db12ff73905251054d12f01911030dd/source/NVDAObjects/IAccessible/__init__.py) (2637 lines) in VS Code, using the same version of VS Code as you.

Can you try running VS Code with extensions disabled to see if it is an extension causing the issue? `code --disable-extensions .` in your project directory.

**Comment by kianoosh-shakeri** [comment]
Hi there,
Yes. I did try running VS code with all extensions disabled while I was running NVDA with no add-ons enabled, yet the issue persisted.

**Comment by antonshusharin** [comment]
I am also experiencing this issue. I have run a bisect and discovered that the culprit is most likely commit 03364662. I'm attaching logs from NVDA alpha snapshots 32590,9afb6fc5 and 32599,03364662, in which I navigate around line 1491 of the aforementioned source/NVDAObjects/IAccessible/__init__.py. The difference in latency is quite clear.
The line number here is significant, because it turns out that performance gets worse as the caret approaches the end of the page that is exposed to a11y clients. So on line 1501, there is no lag.
[nvda-9afb6fc5.log](https://github.com/user-attachments/files/16738036/nvda-9afb6fc5.log)
[nvda-03364662.log](https://github.com/user-attachments/files/16738037/nvda-03364662.log)

**Comment by michaelDCurran** [comment]
I can reproduce this with @antonshusharin's example.
In this case, for me IAccessibleText::textAtOffset with IA2_TEXT_OFFSET_CARET takes at least 60 ms to execute the first time, when initially getting the caret, and then waiting for the caret to move, each extra call takes around 30 ms.
 In this example, the character offsets we are dealing with are in the range of 16000 or so, which is very large. No doubt the underlying issue here is VS code / Chromium simply taking a long time to look up / calculate the caret offset. In principle I don't think pr #16745  is doing anything inappropriate. But, at the end of the day it does cause a significant slowdown in VS code.
@jcsteh  when I set VS Code to Word wrap and move to the end of a wrapped line, NVDA reads the wrong line, I.e. for VS Code / chromium, pr #16745  does not improve things. In this case, would it be possible to only do caret offset checking for Mozilla Gecko where it actually works? Then we can avoid the slowdown?

**Comment by jcsteh** [comment]
> @jcsteh when I set VS Code to Word wrap and move to the end of a wrapped line, NVDA reads the wrong line, I.e. for VS Code / chromium, pr #16745 does not improve things. In this case, would it be possible to only do caret offset checking for Mozilla Gecko where it actually works? Then we can avoid the slowdown?

1. Just to check my understanding, I assume this is still going to be a bit slow and get slower the larger the file regardless? That is, we still have to call caretOffset first, which is still going to be slow. We just avoid double slowness by effectively doing it twice.
2. We could certainly restrict this to Gecko. I was kinda hoping we might be able to convince Chromium to implement better line wrapping support, though, at which point we would need this again. But that's probably a problem for the future, so yes, we could do this to stop the bleeding now.

**Comment by michaelDCurran** [comment]
Yes, we'd still call IAccessibleText::caretOffset.
