### ISSUE TITLE
aria-live is not workiing properly today my my system windows 11 while using NVDA

### ISSUE THREAD

**Issue by mehtaramesh70** [nvaccess/nvda#17077]

**Comment by XLTechie** [comment]
@mehtaramesh70 Your issue has no content. It is impossible from the title, to analyze your issue.
Please open a new issue, and properly fill out all of the questions in the template, so that we may help you more successfully.
Follow this link to submit a bug report with the proper template: [NVDA bug report](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&projects=&template=bug_report.md)
