### ISSUE TITLE
Create an option to start/restart NVDA with all user dictionaries disabled

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#17129]
### Is your feature request related to a problem? Please describe.
Just as there are times where add-ons can interfere with NVDA's behavior or each other, the same is true of dictionary processing when it comes to what NVDA hands to the synth to speak.  Since NVDA's dictionary processing does not "fall out" after the first match and replace, but continues the process with what's been replaced as the string to match in the dictionary entries that follow, there is the potential for significant confounding of what, precisely, has happened.  (See issue: https://github.com/nvaccess/nvda/issues/11823, for detailed explanation).
This issue is being created in response to this comment https://github.com/nvaccess/nvda/issues/13660#issuecomment-2334924921
on issue https://github.com/nvaccess/nvda/issues/13660
suggesting that the ability to do a full disabling of dictionary processing on demand is easier to implement than doing so for individual entries (which would be akin to the ability to enable/disable add-ons in the Add-On Store)

### Describe the solution you'd like
The ability to run NVDA, on demand, with all dictionary processing suspended for the purposes of debugging whether a dictionary entry or entries are causing something to be announced in an unexpected way by NVDA (or the synth, in reality).

### Describe alternatives you've considered
None, other than possibliy having the ability to enable/disable at the individual dictionary entry level.

### Additional context
For a real world example of a situation where this could be helpful, see the NVDA Group Topic: [Issues with how the Tiflotecnia Voices for NVDA add-on reads headings with dates written in a particular way.](https://nvda.groups.io/g/nvda/topic/108309879)

**Comment by hwf1324** [comment]
Why not consider restarting NVDA with a temporary default userConfig directory?

**Comment by britechguy** [comment]
> Why not consider restarting NVDA with a temporary default userConfig directory?

I've considered (and even tried) a number of workarounds.  We need a formal troubleshooting method where we can say to an end user, "Start with dictionary processing disabled," just as we have for, "Start with add-ons disabled."

Dictionary processing, as implemented, has the potential, and I've seen it happen, to give results that no end user (or even others) is likely to understand "how I got here," and where blame is placed incorrectly for the result.  It's something that needs an easy way to be cut out of the equation that doesn't require workarounds (from the end user side).

This could be implemented a number of ways, one of which would simply be not loading the user dictionary files on demand.  You could move them prior to NVDA firing up, you could do as you proposed.  It's not about "the how" but giving an easy and straightforward way for a user to make it happen.

**Comment by marlon-sousa** [comment]
Hello @britechguy ,

I do agree this switch would be apreciated.

So that you know, using [enhancedFind
Dialog]() you could create a specific profile to use dictionaries and as other profiles are activated these entries wouldn't be considered.

The existence of this addon, however, does not solve the problem. I agree NVDA should have a way of disabling dictionaries.

I have created PR #17132  which should address this issue precise and elegantly.

It is in draft because I need at least a signal from NVAccess that it would be considered. However, feel free to test it. Only thing missing is the changelog edit, which will be written last when and if the pr is set to be accepted.

**Comment by britechguy** [comment]
> I do agree this switch would be apreciated.

As do I, but it shouldn't only be a command line switch, as far too many users will never, ever invoke NVDA that way.  There also needs to be a parallel way for them to do this on NVDA restart, just as there is for restarting with add-ons disabled.

**Comment by CyrilleB79** [comment]
Regarding dictionaries, why should this option be a start option (command line switch) or a restart option? Couldn't this switch be a control or a menu item in the GUI? E.g. a checkbox in the dictionary window as the one in Profile window to disable all triggers.

But before suggesting a solution, let's look at the issue.
When assisting people, it's difficult to know if the issue encountered by the user comes from something specific in their configuration (add-ons, dictionaries, etc.) or something in NVDA or Windows.

To discriminate, I usually launch NVDA with the `-c` flag pointing to an empty folder to start with a brand new test configuration. It would be nice to have rather an option to restart with no configuration if we were to adde a new restart option.

**Comment by marlon-sousa** [comment]
Hello,,

Considerations below:

1. Dictionaries are important and can really break a flow, so for me a flag disabling them makes sense. If you know there might be something wrong with dictionaries, you shouldn't have to giv up all other settings.
2. This command line flag does no arm, it helps, it does not cause a big impact on the system maintenance.
3. As for putting something in the gui, @britechguy  ... I suppose everyome playing with regexp are advanced enough to read documentation and to know what a command line switch is, as well as knowing how to use it.

I do agree that we should provide a gui way of selecting switch options on restart, but this is subject for another issue.

Complex systems do this kind of thing just before restarting, and letting the user choose which flag to use when restarting is desirable,, like an advanced restart dialog where all switches would be presented and the user could easily choose the switches that should be sent.

We would have to parse the args class and offer a dynamically gui with options to activate, deactivate or fill values but this is another functionality that gors beyond this possible flag here.

For me, the command line switch solves the problem.

**Comment by britechguy** [comment]
> I do agree that we should provide a gui way of selecting switch options on restart, but this is subject for another issue.

Why?

The issue here is focused on being able to selectively disable dictionary processing.  There is no earthly reason for another issue if both a command line option and a restart option akin to that for disabling add-ons can be reasonably added at the same time.  If they can't, then a spin off issue would be needed.

It makes no sense to "subdivide" this because of the possibility of using more than one way to activate it.  It's only if technical reasons dictate that only one can be provided in a reasonable timeframe and the other would need more extensive reworking that a spin-off issue should be considered.

I'm perfectly happy with the command line option for myself, but it's not all about me or "power users" as advanced users are often styled.  Giving the "more typical user" a UI-based method of doing this is, to me, part and parcel of the issue.

**Comment by marlon-sousa** [comment]
This is not about this issue, the functionality of providing options to enable or disable switches before restarting is a whole topic by itself, and when we start to provide options, we should have a dedicated dialogue for  that. The topic of offering a graphical user interface for enabling or disabling switches is itself a distinct topic, and, in my opinion, should be addressed separately. If and when this switch here is accepted, it would make part of the group of switches which can be enabled or disabled before restarting..Obrigado,MarlonEm 9 de set. de 2024, à(s) 19:24, Brian Vogel ***@***.***> escreveu:﻿

I do agree that we should provide a gui way of selecting switch options on restart, but this is subject for another issue.

Why?
The issue here is focused on being able to selectively disable dictionary processing.  There is no earthly reason for another issue if both a command line option and a restart option akin to that for disabling add-ons can be reasonably added at the same time.  If they can't, then a spin off issue would be needed.
It makes no sense to "subdivide" this because of the possibility of using more than one way to activate it.  It's only if technical reasons dictate that only one can be provided in a reasonable timeframe and the other would need more extensive reworking that a spin-off issue should be considered.
I'm perfectly happy with the command line option for myself, but it's not all about me or "power users" as advanced users are often styled.  Giving the "more typical user" a UI-based method of doing this is, to me, part and parcel of the issue.

**Comment by seanbudd** [comment]
Closing this.
We don't believe the use case required is valid.
If you are trying to test if a speech dictionary is effecting your speech output you can:
- change synthesizers
- open the speech dictionary dialog to disable them temporarily
- restart with a temp default config folder

**Comment by britechguy** [comment]
Then I would strongly suggest the trick of opening the speech dictionary dialog to temporarily disable dictionary processing be formally documented in the User Guide.

I have just looked in the User Guide for 2024.4 beta and can find nothing to this effect.  I was surprised (pleasantly) when I was told that merely opening the speech dictionary dialog would temporarily suspend all dictonary processing.  This needs to be documented somewhere that any given user could find it should the need arise.

**Comment by seanbudd** [comment]
@britechguy - can you open a new issue to cover this?
