### ISSUE TITLE
Use a more descriptive label for the top UI option of feature flags

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#17170]
### Is your feature request related to a problem? Please describe.

As @Adriani90 and others have pointed out, the proliferation of feature flags in the UI (outside of the Advanced panel), was unexpected by those of us who thought they were mainly for beta testing experimental features.

The current user experience of the combo box used for feature flags, may not adequately make users understand the difference between the default choice, and that same choice listed further down without the "default".

### Describe the solution you'd like

If these things are more and more replacing checkboxes for new features, then I posit that a more explanatory term than "default" should be used, to explain what the top option does.

If the choices were:

* Default (Never)
* Never
* Always

Perhaps it would be slightly clearer, if the top option was more along the lines of:

* NV Access Default (currently: Never)

Or:

* Let NV Access Decide (currently: never)

### Describe alternatives you've considered

I have an alternative proposal explained in #17171.
But this proposal is much easier to implement, meaning it could be done quickly.

**Comment by Adriani90** [comment]
the simplest solution would still be to let feature flags do the job as part of the advanced settings pannel which already has a disclaimer. In my view experimental options should not be part of other settings pannels.
That being said, a change in default behavior of settings other than advanced settings should always be covered by the community / users first, and not induced by developers without any justification.
The options of settings in the advanced settings pannel can change the default values without having any request in advance, because they are officially experimental. But also in this case, a feature flag is only needed when the developer has a reason to test something, e.g. enabling a setting only partially or what so ever.
Just producing duplicate options in a combo box does not really help anyone.

By the way, instead of default value, the developer induced option could be called something like "experimental (xxx)"

e.g. a setting with feature flag and three options would look like:
* Enabled
* Disabled
* Experimental (enabled only on Windows 10)

cc: @ABuffEr, @nvdaes, @jcsteh, @michaelDCurran 
maybe you can bring also some thoughts and more clarity on the feature flag, some of you were directly or indirectly involved from the start in this process.
cc: @gerald-hartig maybe there could be an official statement from NV Access in this regard so we can explain it better to other users and developers along the conversations.

**Comment by seanbudd** [comment]
Closing as won't fix. We don't understand the issue raised here. Combo-boxes are not particularly confusing to use, and the term of default is quite common and easy to understand.
