### ISSUE TITLE
Let NVDA read aria-label of th

### ISSUE THREAD

**Issue by venlahy** [nvaccess/nvda#17213]
### Is your feature request related to a problem? Please describe.

I have a table like this:

```
<table>
    <thead>
        <tr>
            <th>First header</th>
            <th>
                Second header
                <button>Open additional info to second header</button>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Value 1</td>
            <td>Value 2</td>
        </tr>
    </tbody>
</table>
```

That table has an accessibility problem with the button. When I use a screen reader and step to the "Value 2" cell, I hear the screen reader saying also the text "Open additional info to second header" which I do not need to hear in the "Value 2" field. The screen reader says:
"Second header and Open additional info to second header Value 2, column 2 of 2".
but I would like the screen reader to say:
"Second header Value 2, column 2 of 2".

With VoiceOver, this problem can be fixed by adding an aria-label to the th. But to prevent VoiceOver from reading the "Second header" twice when stepping to the header cell, an aria-hidden attribute can be added. Like this:

```
<table>
    <thead>
        <tr>
            <th>First header</th>
            <th aria-label="Second header">
                <span aria-hidden="true">Second header</span>
                <button>Open additional info to second header</button>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Value 1</td>
            <td>Value 2</td>
        </tr>
    </tbody>
</table>
```

However, this solution does not work with NVDA, since NVDA does not read aria-labels of th elements. NVDA does not read the text "Second header" at all in the cell, so I cannot use this solution at all.

### Describe the solution you'd like

I would expect NVDA to behave simirlarly to VoiceOver. I would expect NVDA to read the aria-labels of the table headers.

**Comment by Adriani90** [comment]
cc: @SaschaCowley, @jcsteh maybe you have any thoughts on this as well, I think this approach might produce also redundant verbosity if aria label on th elements is misused in some circumstances. In this case the question is why should the user not get any information about the button?

**Comment by seanbudd** [comment]
This is intended behaviour, what part of the HTML/ARIA spec leads you to the reasoning for expected behaviour? Note VoiceOver might not be following the spec, or there could be multiple valid implementations within the spec.

**Comment by JoseAntonioNavasSolutia** [comment]
https://w3c.github.io/aria/#columnheader.  aria-label admited

**Comment by afercia** [comment]
> This is intended behaviour, what part of the HTML/ARIA spec leads you to the reasoning for expected behaviour? 

As already pointed out by @JoseAntonioNavasSolutia, `aria-label` is allowed on a `th` element.

For what is worth, we are going to implement such a pattern in the WordPress.org codebase. The use case there is to reduce the amount of redundant information when a row header is announced while navigating other columns. Example:

- A table of posts with many rows and columns.
- The row header `th` contains the post title. Unfortunately, it also contains other things like action links and the like that we can't remove for backward compatibility reasons. Still, all this extra content in the row header contributes to its accessible name, making it extremely long and terribly noisy.
- We did try the `abbr` attribute on the `th` element, but supoort is poor.
- We did then try `aria-label` on the `th` element and it works except on NVDA.

For reference, here's the WordPress Trac ticket and the related PR:
https://core.trac.wordpress.org/ticket/32892
https://github.com/WordPress/wordpress-develop/pull/9761

Regarding the concerns of misuse, anything can be abused but in this specific case I would say there are more pros than cons. It would be great to see this reconsidered and have NVDA aligned with what other screen readers do. Cc @Adriani90 @seanbudd thank you for your time in reading this comment.

For what is worth, in WordPress we are going to implement the aria-label on the th element, because it is better than what we have now. NVDA users will still get all the additional extra noisy content. Not a huge barrier I guess but a little annoying.

**Comment by josephsl** [comment]
Hi,

I assume you have also tested this scenario across web browsers/rendering engine combos? I think claiming that this scenario is supported by all screen readers except NVDA might not be an effective argument - to make the case strong, please do test with screen reader + web browser/rendering engine combinations to really make sure NVDA across ALL browsers is not supporting reporting of ARIA label on table header elements.

Thanks.

**Comment by afercia** [comment]
- On macOS, all major browsers expose the name provided via aria-label.
- VoiceOver announces it correctly.
- I can't test on Windows. On [the linked WordPress Trac ticket](https://core.trac.wordpress.org/ticket/32892#comment:24), @joedolson reported that the aria-label works with JAWS. He didn't detail the tested browsers, I'm sure he can provide more details when he has a chance.
- Narrator, Orca, TalkBack were not tested.

**Comment by joedolson** [comment]
All browsers were tested on their most recent standard releases as of 7/23/2026.

Tested NVDA 2026.1.1 + Chrome, Firefox, and Edge - No pairing read the `aria-label` on the `th`.
Tested JAWS 2023 + Chrome, Firefox, and Edge - All pairings read the `aria-label` on the `th`. 
Tested VoiceOver + Chrome, Safari, and Firefox - All pairings read the `aria-label` on the `th`. 

In none of the successful pairings did the `aria-label` impact reading the rest of the contents of the cell.

**Comment by josephsl** [comment]
Hi,

I see. Could you mind testing the following setups:

* JAWS 2026 + browsers
* Narrator with at least Edge

That way all screen readers + browser combos are up to date (JAWS 2023 works, but I am concerned that Vispero may have changed things a bit between 2023 and 2026).

Thanks.

**Comment by guenterhanke** [comment]
Hi, JAWS 2026 and Narrator under Win 11 are reading the aria-label at the th when in the ohter lines rathter than the text.
One common usecase is when you can sort by columns and the sort order as well as the button to change the order to top to bottom is in the header.
Then when reading the headline these information is very important.
But when in the data cells (other than the headlines) you don't want to hear the sort order and to change it.
So this feature is very important.
guenter
