### ISSUE TITLE
Regression with NVDA 2011.2 on Thunderbird 3.1.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1721]
**Reported by aleskis on 2011-08-13 17:09**
With Thunderbird 3.1 and NVDA 2011.2, NVDA often lost the focus between the list of messages and a message. For example, go in a message, then close it with ctrl+W. NVDA still display the body of the message and not the list of messages. However, it's not systematic but a regular case.
Also, in a list of message, when you select one of them to read it, NVDA lost the focus for the braille only. The speech rread the correct line but the braille stay on the object list. When closing the message and down arrow or up arrow, the braille it not refresh.
With the snapshot 4346, no problem.

**Comment by ehollig** [comment]
CC @leonardder

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster, as far as I am aware, and we do not have reliable steps to reproduce the issue as stated in https://github.com/nvaccess/nvda/issues/1721#issuecomment-155292048. This issue is also 6 years old, so it is possible that this issue has resolved itself over time. It is also possible that this could be related to #5035
