### ISSUE TITLE
Logically group documentation of settings child dialogs

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#17238]
### Is your feature request related to a problem? Please describe.
In the user guide, there is a section for the NVDA settings dialog. The child sections for this include each panel of the settings dialog.
Some of these panels have child popup dialogs. The documentation for these panels and child dialogs are grouped under the same heading and share the same heading level.
It might be better to logically group these child dialogs under a separate heading.

The following child pop-up dialogs are grouped closest to their relevant parent.
These are proposed to be moved to a separate heading.
- Set Mirror Dialog
- Select Synthesizer
- Synth settings ring
- Select Braille Display

### Describe the solution you'd like

Re-group these child dialogs under a subheading "Settings helper dialogs"

### Describe alternatives you've considered

Moving them to miscellaneous settings.
Leaving as-is.

### Additional context
Refer to https://github.com/nvaccess/nvda/pull/17228#discussion_r1780354065 for more discussion

**Comment by seanbudd** [comment]
cc @Qchristensen for feedback

**Comment by CyrilleB79** [comment]
I'd request that #17229 be discussed in depth before proceeding with any change in the User Guide.

**Comment by Adriani90** [comment]
I don't think moving these dialogs to separate headings will improve the situation, because they are specifically part of the coresponding settins category (e.g. speech or braille settings). In my view, in order to avoid confusions, they should stay into the propper settings category also in the user guide.
Note that these dialogs are not settings categories, nor sub categories. They are just a layer on the coresponding settings category because as far as I understand it was not possible to integrate all controls into the main settings pannel.

Maybe an improvement would be to investigate whether these additional dialogs are needed at all? Maybe with WX python 4.2.2 it is possible to get rid of them and automatically adjust the settings pannel according to a value chosen in the combo box.
E.g. adjust the braille settings pannel when selecting a certain braille display from the combo box, without having a separate dialog. We do this already e.g. for WASAPI which displays new controls depending whether WASAPI is enabled or disabled.
The same could apply for the synth setting.
1. Move  the combo box out of the synth selection dialog to the voice settings pannel
2. Rename the whole pannel to "synth settings"
3. Organize the synth settings pannel into two groupings (synthesizer, and voice)
4. Make NVDA+ctrl+s the only gesture to open the renamed synth settings pannel, while ctrl+nvda+v is not needed anymore.

**Comment by CyrilleB79** [comment]
@michaelDCurran, I wonder:
If paragraphs are just moved in the user guide, without being modified, do they need to be translated again by translators? I.e. probably if if the context id changes?

**Comment by seanbudd** [comment]
Closing due to negative feedback

**Comment by CyrilleB79** [comment]
Even if the issue is closed, @michaelDCurran, could you answer to https://github.com/nvaccess/nvda/issues/17238#issuecomment-2390741488? It would be good to know in the future in any case.
