### ISSUE TITLE
Say All Randomly Fails in IE 9/FF 4+

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1726]
**Reported by tkeenan79 on 2011-08-18 23:14**
Sometimes, when pressing Say All (NVDA+downarrow,) to read large amounts of text, NVDA will only read a relatively small portion of the text before stopping. The cursor will then be placed several lines before it leaves off.  This usually happens when reading straight text with no links.

**Comment by bhavyashah** [comment]
If none of us are able to reproduce failures and inconsistencies in say alls, since tkeenan79 unfortunately did not respond to https://github.com/nvaccess/nvda/issues/1726#issuecomment-155292075, and given that we have no way of contacting the original author, can this ticket be safely closed? @ehollig

**Comment by Adriani90** [comment]
@tkeenan79 can you still reproduce it?

Or can anyone reproduce it?

**Comment by ehollig** [comment]
As it seems that no one has been able to reproduce this in a very long time, I am going to close this issue. If someone experiences this in the future, please open a new issue with the exact steps you took to reproduce the issue, the text you were reading, and the synthesizer you were using.
