### ISSUE TITLE
NVDA wont stop audio ducking

### ISSUE THREAD

**Issue by BlindMerican** [nvaccess/nvda#17349]
### steps to reproduce
 just turn on nvda and turn off audio ducking. reduce voice fade to "0" go into win 10 sound setings and turn off audio enhancements set to "do nothing" disallow all audio outputs to take over device. enable l;oudness equ;alizer. turn all apps to 100% volume. restart computer and use any communication app such as skype, discord, signal 
### NVDA logs, crash dumps and other attachments:
I cant do this while nvda isnt speaking the nvda menu

#### NVDA version:
NVDA 2024.4

#### Windows version:
 windows 10 pro 64 git

#### Name and version of other software in use when reproducing the issue: 
win 10 pro + nvda + dicord or any communication app

#### Other information about your system: 
Microsoft accessibility remoted in and  said it was an NVDA problem as it did not occur with narrator or JAWS. Microsoft has refused to open a ticket on this as I requested and directed me to NVDA

#### Does the issue still occur after restarting your computer? 
the  issue will stop temporarily only after restarting but begins again with using any communication app  or after the computer powers off completely or after a windows update
#### Have you tried a oany other versions of NVDA?
 I have only used the most recent version of nvda currently availa
[nvda log](https://github.com/user-attachments/files/17609011/nvda.log)
ble on the website 

#### If NVDA add-ons are disabled, is your problem still occurring?
i dont have any addons

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? 
using the com fixing tool does nothing to fix it

**Comment by Adriani90** [comment]
Let's take it one by one, because your setup seems very complex and we need to understand what is going on. It is probably a sound card issue:
* Are you sure this occurs only when audio enhancements is turned off?
* are you sure this occurs only when you disallow all outputs to take over the device?

I think this issue is rather related to #10441 and #7797.

cc: @jcsteh maybe you have some suggestions here as well.

**Comment by BlindMerican** [comment]
yes, all enhancements turned off. windows set to "do nothing" on ducking. all outputs disallowed. (there are only two, the speakers i'm using for main default and the computer speaker which nothing plays through) i have disabled nvda ducking and sound split. I have disabled kiscord ducking and set attenuation to 0. At the moment i'm having to restart nvda everytime the ducking returns. i know for sure of the settings because i have vision and i'm looking right at it

**Comment by Adriani90** [comment]
So if you allow outputs to take over device, does the issue disapear? Von meinem iPhone gesendetAm 07.11.2024 um 01:28 schrieb BlindMerican ***@***.***>:﻿
yes, all enhancements turned off. windows set to "do nothing" on ducking. all outputs disallowed. (there are only two, the speakers i'm using for main default and the computer speaker which nothing plays through) i have disabled nvda ducking and sound split. I have disabled kiscord ducking and set attenuation to 0. At the moment i'm having to restart nvda everytime the ducking returns. i know for sure of the settings because i have vision and i'm looking right at it

**Comment by BlindMerican** [comment]
no, it occurs whether allowed or disallowed on allowing audio output to be taken over. tried both, didnt help either way. audio ducking still kept occuring

**Comment by Adriani90** [comment]
Does this occur also with sound enhancements is enabled?Von meinem iPhone gesendetAm 07.11.2024 um 09:32 schrieb BlindMerican ***@***.***>:﻿
no, it occurs whether allowed or disallowed on allowing audio output to be taken over. tried both, didnt help either way. audio ducking still kept occuring

**Comment by BlindMerican** [comment]
those two tickets arent applicable. i have already tried using both microsoft audio mapper and mapping nvda through the speakers that i'm using. it doesnt matter. it still ducks. the main audio source are my usb speaker as i am using a desktop with only the speaker output. it's not feasible to to purchase TWO sets of speakers, one for windows and one for nvda

**Comment by jcsteh** [comment]
Just to clarify, are you saying that NVDA's own speech is ducked or that NVDA is ducking other apps? These are two very different things, so it's important we get that clarified.

I do know that communication apps are treated specially by Windows and they are allowed to duck all other apps, including NVDA. There is a setting to turn this off on the Communications tab of the Windows Sound properties. It's labelled "WhenWindows detects communications activity:". The default is "Reduce the volume of other sounds by 80%", but you can set it to "Do nothing". Unfortunately, this setting has absolutely no effect (unless you apply it after the call begins, which is rather useless) and this is a [known](https://answers.microsoft.com/en-us/windows/forum/all/selection-for-when-windows-detects-communications/721594ca-281e-4ccf-9e9f-cf71b8d6d426) [Windows bug](https://github.com/signalapp/Signal-Desktop/issues/5649) that Microsoft don't seem interested in fixing.

I think I read somewhere else that you said JAWS doesn't have this issue. That would raise the question of how they are working around this Windows bug. There must be some way to indicate to Windows that your app should never be ducked by communication apps, but I'm not sure how that's done.

**Comment by jcsteh** [comment]
Aha. It seems you can [use WASAPI APIs to disable the default communications ducking experience for your application](https://learn.microsoft.com/en-us/windows/win32/coreaudio/disabling-the-ducking-experience). My guess is that JAWS does this. NVDA definitely should.

**Comment by jcsteh** [comment]
Implementation note: This should be fairly straightforward. It should be done in wasapi.cpp, WasapiPlayer::open, probably near the bottom of the function.

**Comment by BlindMerican** [comment]
Reply to this being a known microsoft bug: microsoft says they do not consider this a microsoft bug as it not ducking in narrator and their valueless answer was to use narrator which we all know doesnt work.

**Comment by BlindMerican** [comment]
is this wasapi already a part of the windows operation system or part of the microsoft audio mapper? the microsoft audio mapper is part of the problem and forces ducking no matter what

**Comment by jcsteh** [comment]
> Reply to this being a known microsoft bug: microsoft says they do not consider this a microsoft bug as it not ducking in narrator

Sure, but this doesn't address the fact that the setting that is supposed to disable this ducking for the entire system doesn't work. That's much broader than screen readers. But anyway, that's academic because it seems we can opt out of the default (broken) ducking experience altogether.

WASAPI is an implementation detail you don't need to worry about unless you want to dig into the code. The short of it is that I've provided information regarding how this should be implemented and it should be relatively easy to fix this if things work as they should, but I can't make any guarantees as to when someone (whether me or someone else) will get to fixing it.

**Comment by XLTechie** [comment]
@BlindMerican Can you please answer this question that was asked earlier?:

> Just to clarify, are you saying that NVDA's own speech is ducked or that NVDA is ducking other apps? These are two very different things, so it's important we get that clarified.

**Comment by BlindMerican** [comment]
this is rediculous. there is no "wasapi" in my computer and to require  a new user who doesnt know how to code to be able to fix a problem that support should be helping with is ridiculous. this isnt even on my computer that i can find at all. somehow nvda is involved in this because i can constantly run com registry, restart nvda and it fixes it for a couple of hours then starts again, but doesnt in narrator or jaws. to require a random, newly blind user of nvda to go into the settings when nvda isnt even working properly  is a deriliction of duty of care to the users of nvda. if it's not present in the windows system or showing where to find it this is no solution. your steps arent clear. you have given steps as if i'm a programmer. this is unacceptable and NOT a solution

**Comment by BlindMerican** [comment]
blindmexican, it is showing you saying to answer a question from earlier, but i cant find one that i havent answered. is there a question I havent answered?

**Comment by seanbudd** [comment]
Hi @BlindMerican , The question in reference is as follows:

> Just to clarify, are you saying that NVDA's own speech is ducked or that NVDA is ducking other apps? These are two very different things, so it's important we get that clarified.

Thanks for being patient and responding to queries here. This is a developer forum, so we need to have some technical discussions with each other. Unless we have any specific questions from you, you don't need to worry about stuff like WASAPI. 
I'd please ask that you consider [our code of conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md) more broadly when responding in our GitHub. We as a community, made up of mostly volunteers, are here to try and support each other for a resolution together.

**Comment by Adriani90** [comment]
WASAPI is part of every Windows machine because is part of the audio engine. What are you actually talking about?I think your issue is solved now. Next time please take notice that people have lot of knowledge which is relevant for solving an issue. You misunderstood alot of things and no one asked you to install anything. So staying calm and being constructive in the communication definitely helps.  Von meinem iPhone gesendetAm 09.11.2024 um 02:14 schrieb BlindMerican ***@***.***>:﻿
this is rediculous. there is no "wasapi" in my computer and to require  a new user who doesnt know how to code to be able to fix a problem that support should be helping with is ridiculous. this isnt even on my computer that i can find at all. somehow nvda is involved in this because i can constantly run com registry, restart nvda and it fixes it for a couple of hours then starts again, but doesnt in narrator or jaws. to require a random, newly blind user of nvda to go into the settings when nvda isnt even working properly  is a deriliction of duty of care to the users of nvda. if it's not present in the windows system or showing where to find it this is no solution. your steps arent clear. you have given steps as if i'm a programmer. this is unacceptable and NOT a solution
