### ISSUE TITLE
Can't quit NVDA while modal dialog is open

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1740]
**Reported by briang1 on 2011-08-31 16:37**
To demonstrate.
 Run IE or Firefox
Open elements list
 use the  right alt/n shortcut to restart nvda. No falling tones will be heard but it will reboot. If one does this via a batch file, ie nvda.exe -q  and views the log, it can be seen that the  nvda session is not terminated.

**Comment by bhavyashah** [comment]
@jcsteh Since you seem to have replicated as well as investigated this ticket in the past (as indicated in https://github.com/nvaccess/nvda/issues/1740#issuecomment-155292151), could you please share updates about the current standing of the reported issue as well as methods of resolving it?

**Comment by jcsteh** [comment]
It still persists. No idea how to fix it besides never using modal dialogs, which isn't really feasible.

**Comment by bhavyashah** [comment]
In that case, should we close this as cantfix?

**Comment by jcsteh** [comment]
No; I'm hoping further investigation might reveal a solution eventually. P3 to investigate.

**Comment by Qchristensen** [comment]
Just noting this issue is still present.  I just had contact with a new user who was confused about not being able to quit NVDA - it turned out they had left the welcome dialog open.

**Comment by Qchristensen** [comment]
We pop up a warning when a user tries to open a dialog with one already open (eg trying to open settings twice) - could we pop up a similar message when trying to show the quit dialog with a dialog open?

My preference would be simply override any open dialogs and force close any dialogs if needed - if the user wants to quit, that's a fairly clear command - we should at least warn them if NVDA can't rather than no message and not doing what they asked.  Interestingly from a UX point of view - it does this on screens which won't lose data like the welcome screen, or request to collect information screen, but not on more critical screens such as the settings screen where a user might have changed something which may not be saved.

**Comment by seanbudd** [comment]
>My preference would be simply override any open dialogs and force close any dialogs if needed - if the user wants to quit, that's a fairly clear command

This behaviour has been implemented on #12183
