### ISSUE TITLE
Add a decider extension point to suppress key echo

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#17451]
### Is your feature request related to a problem? Please describe.
Some users may want to listen typed characters in protected fields, for example to be sure that they are typing passwords correctly.
Some add-ons were created for this, and they patch the `isTypingProtected` function.
### Describe the solution you'd like
Add a decider extension point replacing the current `isTypingProtected` function, available in the api module.
### Describe alternatives you've considered
An option to speak characters in protected fields can be included in Keyboard settings, in NVDA's core. This would replace the reportPassword add-on, available in the store.
### Additional context
This was discussed years ago in a spanish mailing list, and a teacher mentioned that this may be useful for students.

**Comment by Adriani90** [comment]
Imo this should definitely remain an addon due to potential security risks which might make NVDA a no go for corporate environments.  such a setting will never be accepted by sysadmins. Cc: @gerald-hartig

**Comment by CyrilleB79** [comment]
From what I understand, the feature would remain in an add-on. The scope of this request is that the add-on coud use a decider extension point instead of monkey patching a core function.

**Comment by nvdaes** [comment]
Hello. As Cyrille mentioned, my first purpose with this issue is to use a decider in the reportPassword add-on insteas of patching a function.
Anyway, this may be implemented in the core, for example in keyboard or advanced settings.
Sometimes to be informed about the typed password may be considered more secure than typing a wrong password, for example if the screen curtain is active and we use headphones.

**Comment by Adriani90** [comment]
Imo having this setting in core is a security vulnerability, especially for beginners who might enable it accidentally. For sysadmins this would be a no go, especially when they need to provide remote assistance and the user hears the password when the sysadmin enters it.I agree an extension point might be helpful, but me at least vote against having such a setting in core.Von meinem iPhone gesendetAm 29.11.2024 um 14:33 schrieb Noelia Ruiz Martínez ***@***.***>:﻿
Hello. As Cyrille mentioned, my first purpose with this issue is to use a decider in the reportPassword add-on insteas of patching a function.
Anyway, this may be implemented in the core, for example in keyboard or advanced settings.
Sometimes to be informed about the typed password may be considered more secure than typing a wrong password, for example if the screen curtain is active and we use headphones.

**Comment by seanbudd** [comment]
Our preference is incorporating the setting directly, and binding a key command to it, rather than the extension point. If this setting gets incorporate is there still a usecase for the extension point?

**Comment by nvdaes** [comment]
@seanbudd , I think that if we incorporate this in a setting, we don't need an extension point. I'll create a PR including this in keyboard settings and assigning it the NVDA+x command. X may mean something hiden, like in equations, and NVDA+p is used for punctuation.

**Comment by Adriani90** [comment]
@seanbudd please reconsider this, given my comment above. I think we need more community feedback on this, since e.g. Narator does not provide such a setting due to obvious reasons. System admins will definitely take this into account when deciding which software is allowed.

cc: @gerald-hartig, @jcsteh 

I will definitely send this issue to all community groups to start a discussion on regarding having such a setting in core.

**Comment by nvdaes** [comment]
@Adriani90 , smart phones have this option, accessible with screen readers. What I mean is that your proposal is valid, of course, but not obvious.

**Comment by CyrilleB79** [comment]
I am not against optionally echoing typing in protected fields.

Though, I vote against assigning a default gesture, especially an easy one. With a default gesture, there is too much risk that someone inadvertently enable the feature by mistake.

**Comment by nvdaes** [comment]
@CyrilleB79 , your explanation about a default gesture makes sense. I'll leave the command unassigned.

**Comment by davidacm** [comment]
I don't agree with implementing this feature in the core. It might be useful in certain scenarios, but I'm worried about what IT admins might think.
@Adriani90 explained it very well in his email, which is why I'm here.
For example, a support technician who must perform operations on my computer remotely, could be exposed if I have the possibility of listening to the access passwords.
It's the point that worries me the most, if there is any idea to solve it, then I might agree to integrate this feature.
@Adriani90  brought up other valid points, but in my opinion, NVDA in corporate environments is the most important point to address before implementing this feature.

How do other screen readers handle this?
I mean, Narrator, JAWS, Voice Over for Mac...

**Comment by nvdaes** [comment]
I don't see the difference, in terms of security, of having this setting in the core or in an add-on.
Anyway, for security, it would be better to add this to advanced settings, that aren't available when NVDA is run in secure mode.

**Comment by nvdaes** [comment]
Since this is being discussed on NVDA groups, this is a summary of my replies:

- After Cyrille's reasoning, my intention is to leave the command to change this setting unassigned, to prevent accidental changes if the keystroke is activated unintentionally.
- As mentioned in the issue, smartphones provide this feature with screen readers.
- I also mentioned that sometimes may not be secure to type wrong passwords.
- About remote control, if the add-on is active, this option can be activated too.
- When we grant access to a computer to be controlled, there is risk to run software and change settings, even someone may install the reportPasswords add-on.
- I'm happy maintaining this add-on if needed, but if this is included in NVDA's core, NV Access will have more control of this setting.
- If NVDA's debug or input/output log is active, and someone is controlling our computer, we have the risk of show our keystrokes if we type a password.
- In advanced settings, there is an option to speak passwords on Window consoles.
- - I'll add this to advanced settings, so that this won't be available from secure mode.

**Comment by CyrilleB79** [comment]
Adding the option in advanced settings is useless. Either we consider the option secure enough and we add it in widely accessible settings. Or we consider that the option is not secure enough in all cases and we keep it as an add-on.

This option, if made available, should not be available for advanced users only or upon request of a helper person. Thus it has not its place in advanced settings.

Also, regarding security, if the option is in advanced settings or not has no impact: any script or program having write access to `nvda.ini` can easily change the value of the option.

**Comment by zstanecic** [comment]
Hi, as i don't see the real benefit of this function, and see it as a fancy gadget, because even jaws is not implementing it, for the security reasons i am against it being in the NVDA core, because of the corporate environments. It admin can then be against NVDA in the corporate environment because of this.

**Comment by nvdaes** [comment]
@CyrilleB79 , I understand your point. In fact I created an add-on precisely for beginers.
@zstanecic , can you provide a reference from Freedom Scientific team arguing against this feature? The fact that this is not implemented doesn't demonstrate that they won't implement this in the future.
Beginers may need this feature to use passwords.

**Comment by zstanecic** [comment]
@nvdaes 
There is no reference from the freedom scientific team. I don't expect reference from them. I tried contacting them on another matter. 
I am sticking with jaws and NVDA myself to see the status of implementation of this feature. I see it not implemented even in Jaws 2025.
The only program which has implemented such feature is Zdsr the chinese Zhengdu screen reader.

**Comment by nvdaes** [comment]
@zstanecic wrote:

> The only program which has implemented such feature is Zdsr the chinese Zhengdu screen reader.

In smartphones, I have seen this for iPhone with VoiceOver, and on BlindShell.

**Comment by nvdaes** [comment]
@Adriani90 , in secure mode, settings aren't saved. They can be modified by the user if this feature is needed, but if NVDA is restarted, the default setting is applied.
My intention is to create a PR, and if needed, this can be disabled in secure mode like done in the add-on. Though, since settings aren't saved in this mode, may be enabled.

**Comment by zstanecic** [comment]
@nvdaes I understand your references, but in smartphones it is really needed, because the touchscreen key echo is not so consistent.
Talkback and Jieshuo screen reader provides these functionalities on android, but android needs it apparently. If we can provide valid arguments to system administrators why is it needed, i am happy for it.

**Comment by nvdaes** [comment]
@zstanecic , for some people typing with a keyboard may be difficult. Sys admins may disable this in secure mode by default.
If someone needs this, the person can enable the feature, but if NVDA is restarted the default option will be applied.
I think that, with this feedback, I should create the PR and reviews may be done in the code.

**Comment by britechguy** [comment]
I have always had very mixed feelings about the echoing of passwords, particularly on the PC or Mac platform, since it's generally very easy to copy and paste out of a password manager so that you do not literally type the password every time.  But, recently, I've noticed a trend where a number of logins will no longer allow paste in the password field.

Also it cannot be discounted that the password, as sole and primary key to entrance, is definitely on its way out.  MFA is truly taking over the world.

As to valid arguments to sysadmins, this is, in certain circumstances, a reasonable accommodation, pure and simple.  I have fought more battles that I care to count with IT that firmly believes they will have only "one size fits all" and they will determine what that "one size" is.  Well, at least in the USA (and I have to believe other elsewheres) the law dictates otherwise.

Most people I know of who use spoken password characters only do so via headsets (of some sort, earbuds, etc., count) or at exceedingly low volume.  With the former, unless someone's actively targeting that individual and their machine, the risk is essentially nil, and for the latter can be quite low.

Although I, personally, do not like having password characters echoed unless absolutely necessary, I have come to the position that for a certain subset of users, it is.  That, and that alone, makes the feature something worth supporting and also makes it fall into the category of "reasonable accommodation."

**Comment by nvdaes** [comment]
I've created a PR. Please feel free to review it.

**Comment by gerald-hartig** [comment]
This is a fairly controversial issue, and having surveyed the community and reviewed the discussions both here and off github, NV Access has decided that, on the balance, the potential adverse outcomes outweigh the benefits. Please feel free to revisit this if there is a reliable and robust way of addressing the security concerns around accidental password exposure.
