### ISSUE TITLE
Allow the focus to follow braille cursor.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1748]
**Reported by aleskis on 2011-09-05 10:55**
In order to avoid to be limited by a short focus during a braille reading only, add ability for the focus to follow braille cursor/review cursor. Currently, the problem during a long braille reading it the limit imposed by the shortness field imposed by the focus.

**Comment by dkager** [comment]
Good to close? Looks vague and possibly app-specific. We're already discussing this in other issues.

CC @leonardder

**Comment by jcsteh** [comment]
This issue seems to be about the caret not following braille in certain apps even when braille is tethered to focus. It's somewhat vague and is very old, so at the very least, the situation has probably changed. Therefore, I'm closing this. Please file issues for specific apps if this is still an issue.
