### ISSUE TITLE
Linebreaks Ignored during Say All by NVDA

### ISSUE THREAD

**Issue by Jykke67** [nvaccess/nvda#17508]
### Steps to reproduce:
1. Open a document, e-mail message or any text file containing several linebreaks (\n or \r).
2. Start reading the text from the beginning by Say All.
### Actual behavior:

The linebreaks (\n or \r) are ignored instead of causing pauses that would make the reading of text more convenient like in JAWS.
### Expected behavior:

The reading during Say All should be paused by linebreaks instead of constant reading.
### NVDA logs, crash dumps and other attachments:
Not available.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
NVDA 2024.4.1rc1.
#### Windows version:
Windows 11 Pro, 64-bit.
#### Name and version of other software in use when reproducing the issue:
Mozilla Thunderbird, Mozilla Firefox and any text editor.
#### Other information about your system:
Desktop with Windows 11 Pro that is updated from Windows 10 Pro.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, alpha versions with same behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by irrah68** [comment]
For example if you type:

one
two
three

And then type:

one two three

You'll not hear any difference when you read this by pressing Nvda+Down, but you should hear, because the first example is written to separate lines and the second one is in the same line.

Is it possible that NVDA doesn't send CR-LF line breaks to the speech synthesizer? I have made some tests but haven't been able to get any pauses between lines. I use Mikropuhe 5.4, a Finnish Sapi 5 speech synthesizer which has quite flexible interpretation system. So if a software sends line breaks to Mikropuhe, it is possible to configure a pause or other kinds of things.

**Comment by Jykke67** [comment]
Yes, this is exactly like @irrah68 has described, and it seems like linebreak characters are differently handled than others by NVDA. Thanks.

Pauses should be inserted during Say All whatever speech synthesizer is used.

The Finnish Mikropuhe synthesizer has more and even application spesific interpretation options than many other synthesizers, but this is not the point here. These things should be completely synthesizer independent. Then anybody could adjust the interpretations as much as he/she wants.

**Comment by Adriani90** [comment]
Closing in favor of #4944 which covers also this use case.
