### ISSUE TITLE
Reading month date format as a range of years in input

### ISSUE THREAD

**Issue by folt3k** [nvaccess/nvda#17544]
### Detailed description of the issue

I have a month date in input in the format **YYYY-MM**, e.g., 2020-12. The problem is that the screen reader is incorrectly reading this value as "from 2020 to 2012" as if it were a range of years.

### Expected outcome or behaviour (if applicable)

Screen reader should read it like a date or all digits separately.

**Comment by Adriani90** [comment]
This depends on the synthesizer you are using. eSpeak voices read things different to e.g. one core or SAPI5 voices.
Reading numbers with hyphens between them as dates is certainly misleading. An option to read single digits instead of numbers might be reasonable though. Note that you can increase the symbol level for the hyphen sign in the symbol pronounciation dialog in NVDA.
There is no concept of computing / processing dates separately in screen readers. This is something currently done on a synth level.
But yeah this is something which could be developed on a screen reader level. Given the customizable symbol levels, I am not sure the effort for developing a screen reader logic for processing dates separately is worth it. This can get very complex.

**Comment by SaschaCowley** [comment]
This is an issue with the TTS, not with NVDA.
