### ISSUE TITLE
cannot update to current alpha

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#17553]
### Steps to reproduce:
When trying to update I get following error:

IO - speech.speech.speak (09:14:10.280) - MainThread (10664):
Speaking ['Update now', 'button', 'ALT + ', CharacterModeCommand(True), 'u', CharacterModeCommand(False), CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (09:14:19.393) - winInputHook (13108):
Input: kb(laptop):space
IO - speech.speech.speak (09:14:19.420) - MainThread (10664):
Speaking ['väli', EndUtteranceCommand()]
IO - speech.speech.speak (09:14:19.420) - MainThread (10664):
Speaking ['pressed']
ERROR - core.triggerNVDAExit (09:14:19.510) - MainThread (10664):
NVDA cannot exit safely, ensure open dialogs are closed
ERROR - updateCheck._executeUpdate (09:14:19.530) - MainThread (10664):
NVDA already in process of exiting, this indicates a logic error.

This happens also after reboot.
#### NVDA installed/portable/running from source:
installed
#### Windows version:
w10 22h2
#### Does the issue still occur after restarting your computer?
yes

**Comment by CyrilleB79** [comment]
Cc @SaschaCowley

**Comment by SaschaCowley** [comment]
Notes:
This is because `updateCheck.UpdateDownloader._downloadSuccess` calls `UpdateAskInstallDialog` via `gui.runScriptModalDialog`. `runScriptModalDialog` has been updated to actually treat the dialogs it creates as dialogs (IE, to increment `gui.message._messageBoxCounter`), on the expectation that any side effects from dialogs it calls would either not be bothered by this behaviour, or would be executed in the callback function. However, `UpdateAskInstallDialog` calls the update directly on the press of its update button. Since the update process needs NVDA to exit safely, it fails because the dialog hasn't been hidden yet, so NVDA says it's not safe to exit, because the dialog is still open.
There are a couple of options here:
1. Restore the old behaviour of `runScriptModalDialog` whereby it doesn't actually perform the normal dialog actions.
2. Remove the callback functions from being directly in `UpdateAskInstallDialog`, but instead as a function passed to `runScriptModalDialog`.
3. Rewrite the update process to use the new message dialog API entirely.

**Comment by SaschaCowley** [comment]
@burmancomp we will be temporarily rolling back the work that introduced this bug until we can implement a fix in the new year. In the meantime, based on my testing, you can get around this by selecting to postpone the update, then checking for updates again and selecting to install the previously downloaded copy. You can also manually download the latest alpha from [our development snapshots page](https://www.nvaccess.org/files/nvda/snapshots/).
