### ISSUE TITLE
It seems that the registration tool is not working.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#17560]
### Steps to reproduce:
in the nvda tools menu press enter on the option:
Run Registry Fix Tool WITH...

### Actual behavior:
the menu is closed and not a single window is displayed, informing the success or failure of the operation, as well as not a warning about how the tool works.

### Expected behavior:
explanation window and requesting confirmation of the operation.
Window informing of the success or failure of the operation.
I haven't used this tool for a long time, I heard in the logs that in some version of nvda this window had been redesigned.
But I found it strange and suspect that it wasn't executed due to the total lack of warning after pressing the option in the tools menu.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-34867,e2eaab69

#### Windows version:
11 22631.4602
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

log
[com.txt](https://github.com/user-attachments/files/18202327/com.txt)

**Comment by CyrilleB79** [comment]
cc @SaschaCowley

**Comment by SaschaCowley** [comment]
Notes:
This is because `MessageDialog` erroneously no longer inherits from `ContextHelpMixin`. It looks like this was lost while [moving the new `MessageDialog` over to `gui.message`](https://github.com/nvaccess/nvda/commit/6bb8a4c69c65f4c774a6b997343e39cec2b24b7c). IIRC this is because there was a circular import issue with `ContextHelpMixin` in `gui.message`. I believe I fixed the circular import, but forgot to commit restoration of `ContextHelpMixin` to `MessageDialog`'s superclasses.
