### ISSUE TITLE
With no braille display connected, exception is thrown inside a MathCAT braille computation

### ISSUE THREAD

**Issue by NSoiffer** [nvaccess/nvda#17563]
This is a new bug that has shown up in NVDA 2025.1 alpha code. It is not part of 2024.4 or prior releases. Nothing changed in MathCAT.

If I turn on the braille viewer, there is no problem. This is possibly related to [this commit](https://github.com/nvaccess/nvda/commit/8d6a8607b3279cdc69cbbb6ebe0c45618487062c) which seems to try to address a similar "integer division or modulo by zero" error.

I can probably work around this bug by making a change in MathCAT to detect whether a braille display is connected or not. That's useful to do for  efficiency (why generate braille when it goes nowhere?), but I suspect that other addons might be affected also so this would be good to fix.

FYI: I traced the exception to the call to `self._calculateWindowRowBufferOffset` in `source/braille.py:BrailleBuffer::update()`. However, I can't see where there is division by 0 or modulo being called in that method.

### Steps to reproduce:
1. Install MathCAT addon
2. Turn off any braille displays
3. Unzip and open [test.html](https://github.com/user-attachments/files/18215407/test.zip) in a browser. (Due to a bug with chromium, you made need to open in Firefox for math to read).
4. Navigate to the math expression and hit "enter" to begin math navigation. You will hear an error message.

### Actual behavior:
The speech log is:
```
     t        raised to the fraction         b         plus  1         over 3         end fraction         power       
math
   in base         t      
Error in brailling math: see NVDA error log for details
```
and the log file contains the line:
```
ERROR - external:globalPlugins.MathCAT.MathCAT.MathCATInteraction.script_navigate (13:18:58.696) - MainThread (13688):
integer division or modulo by zero
```

### Expected behavior:
There should be no error.

#### NVDA installed/portable/running from source:
Running from source
#### NVDA version:
2025.1 current source
#### Windows version:
Windows 10
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All previous versions of NVDA have worked
#### If NVDA add-ons are disabled, is your problem still occurring?
NA
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
Cc: @Emil-18, @LeonarddeR

**Comment by NSoiffer** [comment]
Related to my plans to a work around: is there a public interface that says whether a braille display is connected? I thought `config.conf["braille"]["display"]` would tell me useful info, but it has the value `auto` even when there is no display.

**Comment by nvdaes** [comment]
@NSoiffer , here Noelia. I'm not sure if you receive my private emails or they are missing.
I've fixed this locally in MathCat add-on with this before `try` in the nav script:

if not braille.handler.enabled:
            return

I'm not sure if this requires some kind of fix in NVDA, or if this is some to be fixed in MathCat or other add-ons if they override NVDA's behavior to show text in braille.
Hope this helps.

**Comment by NSoiffer** [comment]
@nvdaes: thanks, that's the check I was looking for for the workaround.

That solves the problem for MathCAT, but addons may run into the same problem.

**Comment by LeonarddeR** [comment]
Hi @NSoiffer NSoiffer, thanks for reporting this.
I investigated your add-on. Here is wath I found.

1. You use `log.error(e)` when catching an exception. This will only log the message of the exception to the log and will discard the exception info itself. I would personally use log.exception() instead. That will automatically log the exception info of the most recent exception and will make it easier to debug.
2. You should indeed check `braille.handler.enabled` before doing anythin Braille related.

I'm closing this issue for now, since you have fixed your add-on and I currently see no reason why NVDA is in error here.

**Comment by NSoiffer** [comment]
@LeonarddeR: Thanks. I wasn't aware of `log.exception()`. That's much more useful. I'll switch all my calls.

FYI: here's the stack trace when I switch (and disable my check for `braille.handler.enabled`):
```
Traceback (most recent call last):
  File "userConfig\addons\MathCAT\globalPlugins\MathCAT\MathCAT.py", line 320, in script_navigate
    braille.handler.buffer.update()
  File "braille.py", line 2063, in update
    self._calculateWindowRowBufferOffsets(self.windowStartPos)
                                          ^^^^^^^^^^^^^^^^^^^
  File "braille.py", line 1890, in _get_windowStartPos
    return self.windowPosToBufferPos(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "braille.py", line 1880, in windowPosToBufferPos
    row, col = divmod(windowPos, self.handler.displayDimensions.numCols)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ZeroDivisionError: integer division or modulo by zero
```
