### ISSUE TITLE
excel 2010: copy from word, paste into cell, NVDA speaks cell coordinates, but not pasted content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1786]
**Reported by kevinchao89 on 2011-09-13 19:36**
NVDA Snapshot Main-4675 and Office 2010

Open Word 2010, type "test";
SHIFT+LEFTSHIFT+HOME to select to start of line, CTRL+C to copy;
Open Excel 2010, CTRL+V to paste into A1.

Expected: NVDA to speak pasted content and cell coordinates: "Test, A1"
Actual: NVDA speaks cell coordinate: "A1"

**Comment by bhavyashah** [comment]
@jcsteh @michaelDCurran It seems that a patch for this issue has already been provided. Therefore, could the NeedsCodeReview label please be added to this ticket and the attached patch be restored on Github as well?

**Comment by Adriani90** [comment]
This issue is not reproducible in Excel 2016. Copying from Word into Excel speaks content and coordinates which is very good. In most cases users copy small pieces of text or parts of a document in Excel. So, announcing the content is ok and helpful in my opinion.

This issue should be closed as worksforme.

**Comment by Adriani90** [comment]
I will test tomorrow if it works in MS Excel 2010 as well.

**Comment by Adriani90** [comment]
Tested in MS Office 2010, it works properly. I vote for closing this issue as per comments above.

**Comment by ehollig** [comment]
Closing per comments above.
