### ISSUE TITLE
With several Windows 8 Metro apps suspended, ALT+TAB to them and NVDA will make error sound/crash

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1807]
**Reported by kevinchao89 on 2011-09-18 06:23**
WIN+ENTER to run Narrator, Start Screen, ENTER on Gravity;
Turn off Narrator, run NVDA as admin;
ALT+TAB, focus will be on Gravity, and NVDA will make error sound/crash

**Comment by ehollig** [comment]
Can anyone confirm this still is the case with Windows 8.1, as I believe Windows 8 was succeeded by 8.1? CC @josephsl @bhavyashah

**Comment by bhavyashah** [comment]
I use a Windows 8.1 system running NVDA 2017.3 RC 1. However, I have no experience with the Windows 8 Metro apps and I am afraid I don't exactly follow the slightly unclear STR present in the ticket body. I suspect that this might have been resolved overtime since Kevin reported this issue with a developer preview of Windows 8, which is likely to have undergone drastic change before evolving into Windows 8.1. Also, this doesn't sound like too uncommon a scenario (although I still hardly understand precisely what it is), meaning that we should have had more reports of this bug, had it persisted with Windows 8 stable and Windows 8.1 too. Since we have no means of contacting the original author of this ticket, unless other Windows 8.1 users provide feedback confirming this error/crash, I suggest closing. @ehollig

**Comment by derekriemer** [comment]
@jcsteh confusingly said "It does now :-)" I'm not sure what he meant. I would suggest a close here, I sassume he meant "It works now :-)"

**Comment by ehollig** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [Aug 24, 2017, 11:32 AM MDT](https://github.com/nvaccess/nvda/issues/1807#issuecomment-324703622 "2017-08-24T17:32:13Z - Replied by Github Reply Comments"):
> @jcsteh confusingly said "It does now :-)" I'm not sure what he meant.
He meant that Windows 8 is now an option in the drop down on the issue tracker on the old Trac server,
It appears in the log provided in https://github.com/nvaccess/nvda/issues/1807#issuecomment-155293155 that an error was caused from Eloquence. The second log provided in https://github.com/nvaccess/nvda/issues/1807#issuecomment-155293156 does not appear to contain enough information to debug the issue. As we are unable to contact the original poster for more information about the issue, closing
