### ISSUE TITLE
Status Bar Not Detected

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1825]
**Reported by parham on 2011-10-05 07:24**
NVDA does not detect the status bar in Firefox when it is "waiting", "transfering", and etc. This used to be detected with a prior version, but in this revision (7d8b036011de10c71494039d98086b2d9db6b10c), it doesn't happen.
**Blocking #2277**

**Comment by leonardder** [comment]
@JCSTeh: What do you think about this now? I'm tempted towards a close.

**Comment by jcsteh** [comment]
From a purely user centric perspective, I think it'd be good to be able to access this. While it isn't a status bar as such, it has the same semantic value. Having said that, from a technical perspective, I don't know how we'd implement this. Setting to p4.

**Comment by lukaszgo1** [comment]
@jcsteh Would it be possible to improve it from the Firefox side instead of special casing this in NVDA? It is important for issues such as #141

**Comment by jcsteh** [comment]
This isn't needed for #141; see https://github.com/nvaccess/nvda/issues/141#issuecomment-552846042.

That said, as noted above, this isn't really a status bar any more, nor is it always visible. Even putting those two things aside, there's no efficient, unified, programmatic way to find a status bar; APIs don't have a direct way to expose this. That's why we have so much trouble with status bars across different apps. I guess we could expose a status bar relation via IA2, but that would be non-standard and would essentially only work in Firefox.

**Comment by Adriani90** [comment]
As per Jamie's comment above, I do not see any probability for this to be implemented. If someone comes up with other arguments, please comment on this issue and we can reopen it. I am closing it as can't fix for now.
