### ISSUE TITLE
extraneous verbosity in Word 2010

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1836]
**Reported by james gamage on 2011-10-14 19:37**
in word 2011 home and student edition, press alt shift control and S to open the styles dialogue, press the f6 function key to go into the styles dialogue, tab to "manage styles" and press enter,
tab on to the tab controls and choose "edit", tab to modify" and press enter,
tab through the controls, when you get to the font type NVDA says, "mso generic control container tool bar" this is repeated twice before the control is announced,
this behaviour is repeated on most of the controls in the modify procedure and is extraneous to requirements.
it should be noted that Jaws does not announce these controls at all, so NVDA does a better job in identifying the controls.

**Comment by bhavyashah** [comment]
@Qchristensen Could you please test this issue and report whether or not this bug still exists? If Quentin and others are unable to reproduce, I suggest closing as worksforme.

**Comment by Qchristensen** [comment]
I don't have 2010 but just tried in Word 2007 and Word 2016 and in both cases, NVDA reads:

"font combo box Calibri, changes the font of the selection."

(Actually in Word 2010 the font name is "Calibri (body)")

Either way #worksforme.  I'm fairly sure this is one of those things that has been cleaned up along the way (this issue was raised in 2011), but if someone with Word 2010 could double check to be sure, I think we can close this as fixed.

**Comment by bhavyashah** [comment]
I suppose the interface for this dialog differs between Word 2010 VS 2013/2016. I tested this using the slightly unclear STR provided in the ticket summary and was able to successfully reproduce it using NVDA version 2017.2 and Word 2010 on a Windows 8.1 64 bit system as follows:
* Open a new Word document.
* Press Ctrl+Shift+S to open the Apply Styles toolbar/dialog.
* Tab and press the Modify... button.
* Tab through the dialog and you shall be doubtlessly greeted by 'MSO Generic Control Container  tool bar  MSO Generic Control Container toolbar' before NVDA reads quite a few options.

**Comment by Adriani90** [comment]
As stated in #3041 and it is also valid for #3021, this is reproducible but in some dialogs however it cannot reproduced reliably. This issue however, occurs regularly in this specific Dialog. It seems that NVDA reports MSO generic control every time when changing to the toolbar of the Dialog. That means, in dialogs where you can select something from a list (like a style), then press shift+tab to go to the toolbar which provides Actions for that certain style. When changing the Focus from the list to the toolbar, NVDA reports MSO generic control.
By the way, the keystorke is ctrl+shift+s.

**Comment by Adriani90** [comment]
I think this cannot really be solved in NVDA. It seems this issue comes from accessibility API and Microsoft can improve this. But I don't think they will put efforts in solving it because in Office 2016 and newer this extra verbosity is not reproducible. Even in Office 2010 withNVDA 2019.1.1, the extra verbosity is not significant anymore.

I am closing this issue but feel free to comment on it if you think this can be solved in NVDA.
