### ISSUE TITLE
Odd behaviour when navigating web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1842]
**Reported by challsworth2 on 2011-10-15 19:55**
Please try to duplicate the following.
1. Open Firefox.
2. Browse to m.facebook.com.
3. Click on messages.
4. Click on a message.
5. Try replying to it.
6. Expected result: when moved to the edit multi line, stay there.
Actual result: moving to the edit field sometimes, but not always, results in odd, jumpy behaviour. I can get it to stay eventually, but it is jumpy. This of course makes navigation frustrating.
My Firefox is 3.6x if that helps.
Thanks in advance. It would be greatly appreciated.

**Comment by bhavyashah** [comment]
Since the original reporter of this issue cannot be contacted and he/she did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/1842#issuecomment-155293392, we remain the dark with regards to what exactly this ticket encompasses. In addition, I am a frequent user of m.facebook.com's messaging feature on Firefox and all seems well to me. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing. Worksforme.
This also could be a special case of #4522
