### ISSUE TITLE
Implement heuristics to find/move to sentences for controls which don't support this

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1873]
**Reported by Ted Reed on 2011-10-30 13:43**
To be able to have speech output to read by current, prior, or next sentence or paragraph - with appropriate keystroke commands for each.

**Comment by bhavyashah** [comment]
According to https://github.com/nvaccess/nvda/issues/1873#issuecomment-155293959, Word provides sentence navigation commands in the form of Ctrl+Shift+PgUp/PgDn to move to the previous/next sentence. Not only is this the first time I have learnt that something within Word exists for sentence navigation but also this does not seem to work anyways in Word 2010, or at least the system focus or caret doesn't follow Ctrl+Shift+PgUp/PgDn and thus NVDA stays silent.I suspect that this Word sentence navigation command is misinformation. CC @Qchristensen for confirmation
@jcsteh This cannot be marked as a duplicate of #3288 because that simply covered MS Word and its implementation was never generalized.
Since the Word sentence navigation is already in place, I reckon developers are aware of how NVDA identifies sentence boundaries. Still, https://en.wikipedia.org/wiki/Sentence_boundary_disambiguation may be a page worth looking at.
Do we all agree that NVDA, as a screen reader, should provide its own set of sentence navigation key commands (ideally Alt+up/down arrow for previous/next sentence)?

**Comment by jcsteh** [comment]
I agree this could be useful. However, it's far from simple to do this, and just because it's possible in one application doesn't mean it's possible in another.

There are two pieces to supporting sentence navigation:

1. The really hard part: A way to retrieve the start and end of a sentence.
    - Some applications have their own idea of sentences and we can ask these applications to tell us where a sentence starts and ends. Microsoft Word is a good example, and support for this was implemented in #3288. @bhavyashah, to be crystal clear here: Word itself tells us where a sentence starts and ends. Therefore, we cannot reuse this implementation anywhere else.
    - Some applications do not have such a concept, so we can't ask them. In this case, we need to use our own heuristics to figure this out, which means coming up with some way to detect sentences across multiple languages.
    - Using our own heuristics, unfortunately, even if we can find the start and end of a sentence, moving the cursor there might not be possible because a "character" is not necessarily one single character as we normally think of it; e.g. in a word processor, a date/time field might be considered one character.
2. The simple part: Once we have a way to retrieve the start/end of a sentence, we need commands to move there. #3288 implemented such commands for editable text. #5463 covers implementing them for browse mode.

So, this issue should address implementing our own heuristics for detecting (and moving to) the start/end of a sentence as described in point 1 above. Some notes:

1. We can possibly reuse (or at least derive from) the `re_last_pause` regular expression in `speech.py` to detect sentence endings.
2. This will probably require us to retrieve the line at the starting point, scan the text for sentence boundaries, and if we don't find one, retrieving previous and next lines until we do. We should limit the number of lines we walk, since too many would cause performance problems.
3. For OffsetsTextInfo, we can easily move the range to the right offset by just using the offset where the sentence boundary was found. For other TextInfos, this is not so easy. We could try moving by character, but as I noted above, a character might actually consume multiple physical characters. Honestly, I don't think we can solve that problem.

**Comment by Qchristensen** [comment]
Just to pick up the keystroke question - I'd never heard of control+shift+page up / page down to move by sentence, and it doesn't work in Word.  Page down moves the caret down by one screen full of information (more or less).  CONTROL+PAGE DOWN at first moves to the start of the next actual page.  Adding SHIFT to navigation commands generally moves the caret and selects the text along the way so theoretically control+shift+page down should select to the start of the next page in your Word document.  It doesn't, and the reason is (I assume) because control+page up and down actually move to the next or previous item searched for in the Go To dialog.  By default this is set to page, but if you change it to search for say, line, then suddenly, pressing control+page down moves down one line.  Note that all those commands are Word commands and work without NVDA or any other screen reader running.  Keystrokes like the navigation keys are commonly implemented in many applications, but they are not universal - control+right arrow moves to the next word in most text fields and editors I've come across for instance, but exactly what control+page up and down or control+shift+page up and down does can vary.

On the issue itself, I think it's fairly clear that the ability to move by sentence is useful.  Arguably it should be done by the applications, as Jamie pointed out, it's useful to any user, not just a screen reader user.  In the absence of the application providing such functionality, I'm not against NVDA doing it although the first priority would be to talk to the vendor (Microsoft in this case) and push for the functionality to be included by them.

**Comment by seanbudd** [comment]
Closing in favour of #8518  #15998
