### ISSUE TITLE
Usability: terminology dictionary needed?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#189]
**Reported by healeym on 2008-10-04 09:56**
In case anyone thinks the following is an attack on their 'baby', let me say in advance that I think NVDA is very good already, and its Help/Documentation is far superior to System Access's (for example)! I hope I'm not viewed as sniping from the sidelines,  but as passing on an authentic beginner's view which NVDA-experienced people would not usually have.

As the sighted husband of new user of NVDA I find that the documentation assumes my wife is already familiar with NVDA's terminology! Alternatively, it assumes that she's probably familar with another screen reader such as Jaws or Window-Eyes. These terms are probably so familiar to NVDA developers that they can't imagine any potential NVDA users not knowing them! The following terms are sometimes explained in passing, sometimes not. Definitions would be useful even where they might seem 'obvious' - people's ideas of what even a 'simple' term encompasses do vary a lot!
I'm not sure how the info should be presented - maybe via tooltips or links.  
Here are some of the terms that my wife was thrown by - and understandably so, in my opinion! Some are NVDA-specific, some not, but a beginning user isn't going to care about the difference. It's not a huge list, so perhaps the work involved in supplying useful definitions is not huge either. 

Here goes:

SAPI4
SAPI5
Virtual buffer
Old virtual buffer, new virtual buffer
Filtering
MSAA
Iaccessible2
Video intercept driver
Display hook
Jaws
Window-Eyes
extended Insert
Object presentation
Focus
Foreground window
Object
Navigator object
Edit cursor
Review cursor
System caret
Dynamic content
Field (is this the same as Object?)
Form field

**Comment by leonardder** [comment]
CC @josephsl @JCSTeh @bdorer

@QChristensen: Since you are now involved with the NVDA training materials, you might also want to share you ideas about this issue?

**Comment by chogenkamp** [comment]
I know this is an old issue, but I just wanted to say that I am in the middle of trying to prepare some training materials for my coworkers to train them in how to use NVDA and it would be absolutely helpful to have a glossary/primer of the very basic terms, like caret, focus, object, etc. These terms are indeed part of the documentation but as they are part of the actual sections, it's easy to miss the definition if you don't happen to read all of the section where it is contained, and the documentation itself is dense so sometimes I find myself skimming, trying to find a particular instruction or shortcut key.  I think a separate glossary would be a very helpful reference to have, especially for those that screen readers in general are a new thing (ie fully-sighted users who are learning it for a friend/loved one, or to use professionally to test websites, etc) and are not familiar with the elements involved. So that's my two cents, whatever they may be worth! Best of luck with NVDA development.

**Comment by Adriani90** [comment]
I am thinking how to implement this so it is most convenient for all people. What do you think if we create a table at the end of the userguide containing all relevant terminologies with their description? I could create one.
Or is it prefered to have a glossar as a Wiki here on github?

**Comment by chogenkamp** [comment]
Woo hoo a reply!

So right now there is this page: https://www.nvaccess.org/files/nvdaTracAttachments/189/nvda_glossary.html

It could be updated (and categories could be created to place the current terms on there, which are sort of randomly listed) and linked both from the GH page and also at the start of the documentation page.  Link it in as many places as you can, so people have more of a chance to find it no matter where on the NVDA site they are.

The glossary page could be organized similiarly to this page, re: numbering and categories: https://www.nvaccess.org/files/nvdaTracAttachments/455/keycommands%20with%20laptop%20keyboard%20layout.html

**Comment by Qchristensen** [comment]
Chiming in late here (not sure how I missed being tagged in this one back in 2017, but I'm here now :)

I'd mostly add that the User Guide is not specifically designed as a tool to teach new users to use NVDA, but moreso as a reference to confirm the keystroke for a function or where a setting is etc.  We now have the training material which is designed to teach a new user all the intricacies of NVDA, Windows and Office: https://www.nvaccess.org/shop/

All of which is not to take away from improving the other documentation or creating a comprehensive glossary of terms - simply to add that for the use case of the original poster, the training material would be better placed now to meet that specific need.

**Comment by bhavyashah** [comment]
I beg to differ with https://github.com/nvaccess/nvda/issues/189#issuecomment-511631899. I think the User Guide, even in its current state, does go above and beyond listing the names and locations of settings and keyboard shortcuts. Albeit briefly, it explains, among many other thins, what each NVDA setting does and how each NVDA feature works. But even if you dispute this characterization of the User Guide in its present form, a glossary of terms is just a list of definitions of key terms. This is direct, factual information as opposed to tutorial-styled instruction, and ought be given within the User Guide itself. Despite using NVDA for many, many years, I cannot claim to have a full understanding of terms like virtual buffer, system caret, review cursor, and navigator object. A glossary would be massively helpful for novice and intermediate users alike. On that point, I would vote to have it near the top rather than the bottom of the User Guide.

**Comment by Qchristensen** [comment]
Sorry, I wasn't trying to argue against including a glossary of terms - I do think it's a good idea!  One tricky part is working out where to include such a glossary, and when to link to it vs linking to a section of the user guide.  For instance, from the original issue, "IAccessible2" and "Extended insert" are both good candidates for a glossary definition.  Something like Object Presentation (Object presentation settings?) which is an NVDA feature or concept, I would like to that section of the user guide first.  (Actually reading the original issue again, a lot of the terms mentioned in it are not (no longer?) mentioned in the User Guide.  Whether that has been because the terminology has been cleaned up over the years, or just that it has evolved naturally I'm not sure.

In order to proceed with creating a glossary, the next step then, would probably be for someone to start working on a list of such terms to be included.

**Comment by Adriani90** [comment]
Actually after thinking more about this, I don' really know if it makes sense to include a glossary into NVDA. Because in the end we will end up with thousants of proposals for terms which should be included but are not really specific to NVDA. Most of the terms can be leasily found by searching on Google for them which is way more intuitive than looking into the user guide.
The user guide itself already explains the terms and you can jump to them directly from the content page. Adding a glossary would just add lot of duplicate or even redundant explanations.

@Qchristensen maybe it makes more sense to include such a glossary with general windows and NVDA specific terms into the basic training module which can be bought on NV Access website. What do you think?

Here is a list of terms which I think is important for novice users:
* Address bar
* Browse mode
* Carret
* Checkbox
* Child object
* Combo box (can be expanded with alto+down arrow and allows for selection of one item)
* Context menu (i.e. can be opened via the context menu key or with the right mouse click)
* Context menu key
* Dialog
* Dropdown (i.e. dropdown list or dropdown button, can be expanded with alt+down arrow and allows for selection of one item)
* Edit field (including read only edit field)
* Element
* Focus
* Focus mode
* Folder view (i.e. in Windows Explorer)
* Group (i.e. used to structure elements or objects in a window)
* Landmark
* Link (including link grafic, same page link, link image, link menu)
* List and list view (i.e. allows sometimes to select one or more items. Items have sometimes their own context menu)
* Menu (including button menu and coresponding menu items)
* Mouse cursor
* NVDA cursor
* Object (sometimes objects can have their own context menus, sometimes objects can be moved with the mouse or with the keybord to another place in the current window or to another window)
* Parent object
* Object navigation
* Radio button
* Region
* Review mode (i.e. screen review, object review, text review, document review)
* Ribbon (i.e. in MS Office)
* Separator
* Slider
* Spin button
* Status bar
* Sub menu (including i.e. button sub menu)
* System focus
* System carret
* Tab (i.e. an object in a window like search tab or like a browser tab. Sometimes a tab has its own context menu)
* Table (structuring items in rows and columns, sometimes allows selection of one or more items. The column headers sometimes allow to sort the items in a certain way. And in some cases an user can interact with items (i.e. download them or performing other actions)
* Tree view (including items being structured in a hierarchical form. Sometimes items can be selected via enter or space bar and sometimes tree view items have their own context menu)
* Virtual cursor (i.e. in browse mode)
* Window

**Comment by chogenkamp** [comment]
@Adriani90 All I can tell you is that from my experience, it wasn't as easy or straight forward to Google these terms as you may think.  Especially if you are an absolute accessibility novice who is using a screen reader for the first time. The issue with just leaving them within the section they belong to is that you'd have to know beforehand what section that term belongs to, and for an absolute beginner (or even beginner with a bit of experience) that is not as intuitive as you may think.  

The glossary will probably always be redundant, that's sort of the point of a glossary, to collect in one spot all the terms unique to the thing.  Including them in classes/teaching modules is a good idea, but it's also useful to have the glossary available at any time for those who need it at 2am and it can't wait until the next class, and even if the teaching module is available at any time, for the same reason I outlined above, the user would have to know what part of the module to look in for that term, which may not be self-evident.

**Comment by Qchristensen** [comment]
@chogenkamp The Basic Training for NVDA module Adriani referred to is available from NV Access shop: https://www.nvaccess.org/shop/ - it's a downloadable text or audio book (or hardcopy Braille). Once someone has purchased it and knows how to open it, I wouldn't expect they'd have much more trouble finding the glossary in the material than in the User Guide.  Certainly the terms Adriani has compiled are mostly Windows terms moreso than NVDA terms.  My view is that the User Guide should contain how to use NVDA and its features NOT how to use (or an explanation of) Windows features - yes you definitely need to know how to get around Windows (and other programs you will use, like your browser, or Microsoft Office, etc) in order to be most effective, but that is where other resources, such as the training material, or other material from Microsoft or 3rd parties comes in.

**Comment by Adriani90** [comment]
Given @Qchristensen's comment above, I'd say let's close this issue for now. I think this remains NV Access's decision to include such terms in the training modules, it would be helpful in my opinion at least.

**Comment by bhavyashah** [comment]
I don't think this issue should be closed just yet. In the list given in https://github.com/nvaccess/nvda/issues/189#issuecomment-671094882, there are terms like system focus, browse mode, child object, etc. which are critical to understanding how to use NVDA functionality like the review cursor, object navigation, and so on. However, there are not-so-relevant terms like context menu and address bar which are not uniquely relevant for screen reader users but are just generally helpful for any average computer user to know. I agree that more discussion is necessary to lay down clear criteria for the inclusion and exclusion of terms in this glossary, but discarding the idea altogether seems premature at this point. To be clear, even @Qchristensen agrees that a glossary would be useful to include in the NVDA User Guide as expressed in https://github.com/nvaccess/nvda/issues/189#issuecomment-657965612. Please reopen this ticket.
