### ISSUE TITLE
tooltips with say all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1914]
**Reported by dwillemv on 2011-11-16 10:08**
While reading with insert down arrow, tooltips are spoken as they appear. For thunderbird it even stops speech. This means that I can't leave open my email client when reading a book. Other times I might be informed about new updates in the middle of a sentence. I know I can turn reading of tooltips off (and here application speciffic settings may be a solution by not having them spoken in my text editor), but I would like the option to turn tooltips off for say all.

**Comment by bhavyashah** [comment]
@jcsteh Could you please clarify if a tooltip is queued as stated in https://github.com/nvaccess/nvda/issues/1914#issuecomment-155294232 or if it does interrupt say all as believed by the original author?

**Comment by jcsteh** [comment]
Tool tips are queued. Alerts might cancel speech, however. It's possible Thunderbird is using alerts for some things, and if so, this causes a problem here because some alerts are important and should interrupt speech. That should probably be dealt with in an app specific way.

Note that you can disable tool tips for say all now by using a say all triggered profile. I think that answers this request in general, so closing.
