### ISSUE TITLE
A hotkey to open NVDA's user guide directly.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1951]
**Reported by jpgreer on 2011-11-22 13:31**
Not sure how this feature would be accepted by developers and experienced NVDA users, but if there were a hotkey that new users could press to access the NVDA user guide instead of having to go through a series of menus to get to them, it may make it easier for those using NVDA for the first time. There could also be an announcement that NVDA could do when you start NVDA for the first time of the hotkey to press for the user guide.

**Comment by bhavyashah** [comment]
I think adding the Open User Guide button to the Welcome dialog is the best approach too. Users would definitely seek help material the moment they install NVDA, and if they don't, one extra button would be of no harm to them anyways. Do you still have any doubts/concerns in this matter? @jcsteh If not, please add the NeedsCodeReview label.

**Comment by ehollig** [comment]
The only problem is, the patch link provided in https://github.com/nvaccess/nvda/issues/1951#issuecomment-155294505 seems to no longer work.

**Comment by bhavyashah** [comment]
@feerrenrut Are we all in agreement that a relevant button to open the User Guide directly from the Welcome dialog is the correct way to approach this ticket?

**Comment by Adriani90** [comment]
Actually I don't see a need for this since we can open the user guide from the NVDA menu even during the welcome dialog is open or even during the indtallation process of NVDA.
I didn't see any software working in background which provides such a key stroke.
I am closing this issue. Please comment on it if you have other arguments and we might reopen this discussion.
