### ISSUE TITLE
Slight lag in Microsoft Speech Platform

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1961]
**Reported by KevanGC on 2011-11-25 09:29**
There seems to be a slight lag in the Microsoft speech platform with NVDA.

The voice is responsive, but commands take a short time to register, for example, when pressing control to stop speech, speech sometimes doesn't stop instentaniously like it does with other synthesizers. Also, moving around quickly can really bring out the lag at times. I'm assuming this is not an NVDA bug, but I thought I'd file it just in case.

**Comment by bhavyashah** [comment]
@jcsteh Since you asserted, and I guess I agree, that this is likely not an NVDA issue, could you please address https://github.com/nvaccess/nvda/issues/1961#issuecomment-155294566 and triage this ticket accordingly?

**Comment by jcsteh** [comment]
It's difficult to substantiate the claims that performance is better in these other apps. That said, the lag removal fix in #6166 will probably help this too.

**Comment by Adriani90** [comment]
Using Sapi5 voices, I do not experience a significant lag when pressing arrow keys or when pressing ctrl to interupt the speech. Ofcourse it is a bit slower than eSpeak or so but this is the case with almost every human like voice. Performance improved significantly in the last versions and specific performance issues (i.e. pause between reporting of a key and reporting of an object) is covered in other issues. I am closing this one because it is far to general and we don't have an update from the author since 8 years or so. Feel free to open new issues for specific synthesizers if you are still having this problem.
