### ISSUE TITLE
Review nextLine and previousLine commands does not work for large documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1970]
**Reported by surveyor on 2011-11-28 11:51**
I've tested with both main and winword branch. Ms_Word 2010. To reproduce:
Open a large document in word, mine is about 500 pages.
Try to read it line by line using reviewNextLine or ReviewPreviousLine commands, Numpad7 or 9 for desktop, NVDA+U or O for laptop.

Expected: NVDA should skip and read previous or next line in review.
Actual: NVDA waits a moment and says "unknown" after a while. I think the focus also changes, because arrowing to navigate in the document does nothing.

**Comment by bhavyashah** [comment]
@michaelDCurran Could you please clarify whether the behaviour described in https://github.com/nvaccess/nvda/issues/1970#issuecomment-155294643 falls under the scope of this ticket itself or a separate issue needs to be raised? Also, CC @Qchristensen and others for assistance in testing and troubleshooting. Personally speaking, I don't think I am able to reproduce the reported issue because object review is reviewing the contents of the document accurately, or wait, is this the case with flat review only?

**Comment by Adriani90** [comment]
I am not able to reproduce this. However, in a very big document NVDA is very sluggish. You must disable "page" in document formating settings to be able to read it smoothly. In some cases changing the view in MS Word from normal to web layout helps alot as well. This is covered in several comments in different issues. So I suggest closing this issue because it is possible to read line by line but it is quite slow.

**Comment by Adriani90** [comment]
The performance difference between Word using UIA and with UIA disabled is minimal now in NVDA 2019.1.1. In Word 2010 it works a bit slower. The lag is about 0.5 seconds which is reasonable. If you change the view to draft mode the lag is even much lower. Since performance in MS Word is covered in other several issues, I am closing this one for now.
