### ISSUE TITLE
Pitch change for capitals results in a perminent pitch change after reading a single capital letter

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2068]
**Reported by webboy42 on 2012-01-30 05:10**
The pitch change for capitals option results in a permanent pitch change when using the SAPI 4 speech driver.

Set speech driver to SAPI 4, then use review character on a capital letter. The result is the expected pitch change for a capital, but the pitch change remains in place until the pitch is reconfigured, even while reading lowercase letters, numbers, and symbols.

I am using TruVoice voices for SAPI 4.

**Comment by bhavyashah** [comment]
@brian1gaff and other SAPI 4 users: Could you please test if this still persists with any SAPI 4 synthesizers? Given that SAPI 4 is fading into obscurity, this issue is more than five years old, and we have no means to contact the original author of this ticket, unless we can get any feedback confirming the current standing of this issue, I suggest closing. @ehollig

**Comment by Mohamed00** [comment]
Using SAPI 4 and several engines, I can't seem to reproduce this, and the engine described doesn't seem to support capital pitch change adjustment. I'm leaning towards a worksforme for this unless someone else still reports this.

**Comment by ehollig** [comment]
I tried to reproduce this and was unable to. Closing as worksforme
