### ISSUE TITLE
Problems with List box and tree view

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2094]
**Reported by jfauchon on 2012-02-09 00:04**
Hi all,

str:
1. Open MicrosoftWord
2. Make CTRL+O to open a document
3. Choose a folder that contains no files
4. Make Entry
Expected: NVDA should say zero elements and the Braille display. Even one could repeat the information through NVDA NVDA+Tab.
Actual: NVDA any thing

Hoping that you can correct this problem.

Thank you

**Comment by bdorer** [comment]
> Comment 1 by jteh on 2012-02-09 00:15
> Is this the same issue as #2093?
no, it isn't. 
> What version of Windows?
reproducible on windows 10
> NVDA never says "0 items", nor do we have any plans to make it do so. However, it should at least say "list". I do notice empty file lists sometimes don't say "list" in Windows 7, but this shouldn't be the case in Vista and XP.
I think for beginners this would be very helpful. At least if sb presses up or downArrow. At the moment NVDA is silent

**Comment by ABuffEr** [comment]
> I think for beginners this would be very helpful. At least if sb presses up or downArrow. At the moment NVDA is silent

Hi Bernd,
I introduced this feature in dev version of [columnsReview](abuffer/columnsReview) some time ago, even if it's limited to some lists, due to a UIA bug in explorer lists of Windows 8 and 10, and this means that the user should know and install my add-on. Unfortunately I had no time yet to update compatibility flags, but I hope to do it soon.

**Comment by josephsl** [comment]
Hi,

Five years later...

I'm happy to announce that this bug is (finally) fixed in Windows 11 2024 Update - when I try the steps from the original comment and open an empty folder, NVDA says "No items match your search.. This was tested on Windows 11 24H2 preview build 26100.1150, and I don't think this wil be backported to earlier Windows 11 (or Windows 10) releases (for now).

Closing as resolved, thanks.
