### ISSUE TITLE
Braille verbosity levels

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#214]
**Reported by jkinnunen on 2008-10-27 16:35**
The amount of information that is shown in braille, such as the role labels, should be made configurable. Perhaps we need some kind of braille verbosity levels?

**Comment by leonardder** [comment]
In the last few months, I've heard several complaints about this from Dutch mailing list members and @BabbageCom customers. In #1885, I posted the following idea which might be a possibility for this issue as well:

> I propose changing some of the relevant check boxes in the document formatting dialog to a wx.Choice with the options off, speech only, braille only, and both speech and braille. The following items from object presentation seem to be relevant:

* Report object shortcut keys
* Report object position information
* Report object descriptions

Additional options which should be tog gable:

* Report role
* Report states
* Report focus ancestry

**Comment by jcsteh** [comment]
I think a tab control or radio button allowing you to select whether to
show options for speech or braille would be a nicer UX, particularly
because some of the options might already be choice controls. However,
that's a minor detail and can be sorted out later.

This issue is getting rather confused. It first talks about disabling
roles, but then others have commented about shortening the text for states
(which is something we've already done for some states and could easily do
for others if people have intuitive suggestions). Now you're discussing
separate configuration of formatting for speech and braille, which is
covered by #1885.

The bigger question for me here is use cases. If you disable role, states,
focus ancestry, etc., you're losing information which is essential to
understand the user interface. Is this primarily intended for users who use
both speech and braille and get the other information from speech? Or is it
intended for users who know the application they're using so well that they
don't need this information? Use cases are essential for us to justify
something being implemented.

**Comment by leonardder** [comment]
> This issue is getting rather confused. 

May be we should split it out to multiple ones? 

1. An issue for shortening states. I think @dkager would be interested in this in particular, and there are valid use cases for this IMO. 
2. An issue to allow disabling the reporting of roles 
3. An issue related to splitting speech and braille configuration for enabling/disabling reporting of formatting/object information/roles 

> The bigger question for me here is use cases. If you disable role, states, focus ancestry, etc., you're losing information which is essential to understand the user interface. Is this primarily intended for users who use both speech and braille and get the other information from speech? Or is it intended for users who know the application they're using so well that they don't need this information? 

You already have two valid use cases here. I think there are at least four types of screen reader users in terms of how they use speech and braille: 

1. Speech only users 
2. Users who primarily work with speech, but who would like to have the most fundamental information (such as object names) available in braille. I belief I'm one of those users. I, for example, am not interested in having focus ancestry on my braille display, since I get this information from speech and only want to use braille to have extra control over where I am and how things are written. 
3. Users who primarily work with braille, using speech for reading large amounts of text or for other supportive purposes. For those people, having formatting information available in braille is essential 
4. Braille only users: This is currently the group of people who get into problems with NVDA sooner or later.

**Comment by leonardder** [comment]
This issue is still a bit vague in scope. I suggest closing it in favour of newer issues that have a clearer scope and goal. @dkager, thoughts?

**Comment by dkager** [comment]
Sounds reasonable.
