### ISSUE TITLE
Support for BOINC Manager

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2141]
**Reported by krzyszp on 2012-03-02 21:46**
My Polish friend tried to use NVDA with BOINC Manager (http://boinc.berkeley.edu) but that application is not fully supported.
I have contacted Boinc dev mailing list and ask about that and they ask mi that Nvda use Microsoft Accessibility API?

Can you answer that question, please?

I would like to help make that application more friendly for Nvda users.

**Comment by bhavyashah** [comment]
Since this ticket was more of an enquiry than a request, the original author of this ticket can no longer be contacted, there was no follow-up response to https://github.com/nvaccess/nvda/issues/2141#issuecomment-155295972 and an application should improve its accessibility implementation itself instead of screen readers having to work around them, I suggest closing. @ehollig
