### ISSUE TITLE
Flat review seems to mix up different tabs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2158]
**Reported by kredh on 2012-03-09 15:00**
With an application divided in tabs, the flat review mode seems to mix up informations from different tabs.

This can be visible in Chatzilla (a IRC client) or MushCLIENT (a MUD client): when only one tab is open, it's fine.  When two are open, some lines of the first one are visible when browsing the second one.  That is still worse when you have a lot of open tabs.  I don't know if it occurs on a web browser which use one tab per page, because I can't use flat review on Firefox.  So I don't know where the problem comes from.

**Comment by bhavyashah** [comment]
NVDA has dropped the flat review concept in favour of the three review modes. Does that make this issue irrelevant?

**Comment by michaelDCurran** [comment]
@bhavyashah  Flat review is equivalent  to NVDA's screen review today. I would think it is still valid.

**Comment by bhavyashah** [comment]
@michaelDCurran Thanks for the clarification. On re-reading https://github.com/nvaccess/nvda/issues/2158#issuecomment-155296109, it now unclear to me what the bug being described actually is. Is NVDA reporting extraneous information of another tab which is not even open, or are two tabs actually open and are being simultaneously displayed and NVDA's screen review does not aid the user in distinguishing between the contents of the first and second tab, or something else? Since we may not be able to contact the original author of this ticket, I would like to invite comments from our sighted experts - @feerrenrut and @Qchristensen.

**Comment by Adriani90** [comment]
@kredh
cc: @michaelDCurran, @feerrenrut, your thoughts are very appreciated. I understand this issue as follows:
in screen review, when a single tab is open, everything is ok. When two or more tabs are open, NVDA reads the whole content in a row from left to right. This means it reads content of all opened tabs which is displayed in a row.

In my view this is not an issue in NVDA. NVDA reads out the content as it is visible on the screen line by line from left to right. This is the principle how it works in every application. In Jaws it works exactly similar to this when using jaws cursor.

**Comment by Adriani90** [comment]
I am closing this issue because we do not have any other reports on it.
