### ISSUE TITLE
focus 40 blue do'nt works with bluetooth

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2161]
**Reported by paul otter on 2012-03-13 17:01**
hello, we have a problem with a focus 40 braille display
the problem is this: when we connect the display with an usb cable all is working fine there is no problem and there is braille on the display.
but when we try to connect with bluetooth, nvda reports in the logfile that he can'nt find the display, while nvda is correct configured.
i've allready asked for a solution on the forum, but they tells me to create a ticket for this problem.
and when we close nvda, and starting jaws, the display will work good without any problem allso with bluetooth!
your help will great appreciated!

**Comment by bhavyashah** [comment]
@josephsl's https://github.com/nvaccess/nvda/issues/2161#issuecomment-155296125 seems to suggest that the reported issue may have been fixed in NVDA version 2013.3. Unfortunately however, the original author of this ticket did not respond to the cited comment by testing with said NVDA release and onwards, and we have no means of contacting Paul anymore. Unless we receive feedback from an NVDA user of the mentioned Braille display still confirming this ticket, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster for additional information.

**Comment by bdorer** [comment]
A friend told me, bluetooth support is working with the widcom bluetooth 
stack. May we should note with bluetooth stacks are supported.

Am 14.08.2017 um 22:00 schrieb Ethan Holliger:
