### ISSUE TITLE
Some buttons on websites state unavailable in IE8 when they are not

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2196]
**Reported by briang1 on 2012-03-23 20:29**

Some button types seem to be reported as unavailable in Internet Explorer, including some on the donation page, which might confuse a new user using IE.

IE8 says..
IO - inputCore.InputManager.executeGesture (20:09:19):
Input: kb(desktop):shift+tab
IO - speech.speak (20:09:20):
Speaking [('en_UK'), u'Single donation via PayPal', u'button  unavailable'](LangChangeCommand)
IO - speech.speak (20:09:20):
Speaking [('en_UK'), u'browse mode'](LangChangeCommand)

Firefox 3.6 etc says.

IO - inputCore.InputManager.executeGesture (20:17:38):
Input: kb(desktop):shift+tab
IO - speech.speak (20:17:38):
Speaking [('en_UK'), u'Single donation via PayPal', u'button'](LangChangeCommand)
IO - speech.speak (20:17:38):
Speaking [('en_UK'), u'browse mode'](LangChangeCommand)

In both cases these buttons do work, so I wondered what was triggering the unavailable  status on IE8.

This is not a new phenomenen, but could not find a ticket so...

**Comment by leonardder** [comment]
@brian1gaff: Could you confirm whether this is IE8 only? If so, i'll close this as won't fix, since IE8 specific fixes won't be done anymore.

**Comment by bhavyashah** [comment]
@brian1gaff Could you please respond to @leonardder's https://github.com/nvaccess/nvda/issues/2196#issuecomment-313713795 by confirming whether or not this is IE 8 specific?

**Comment by Brian1Gaff** [comment]
In a nutshell, yes.
I seldom use IE now 8 or anything else as Firefox seems to work far better 
for me.
 Occasionally you do get some odd controls on web sites but usually this is 
down to the strange web site not the browser.
 I think that iE8 is now almost unsusable  since its only been getting 
security fixes and no functional ones at all even in the extended support 
the NHS has had running till the end of last year.

So I'd close the ticket and if any similar issues come up it can be  asked 
that a new ticket is raised as its unlikely to be the same issue.
 Incidentally was this a n issue ported over from Trac. I never seem to get 
any alerts to any new content on an issue after the move so theere could be 
many like this for others as well.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
This is IE8 specific, as reported in https://github.com/nvaccess/nvda/issues/2196#issuecomment-322033013, closing
