### ISSUE TITLE
Firefox 11 - no more paragraph reading on mouse over

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2245]
**Reported by daTscharlie on 2012-04-15 14:34**
[mouse settings](NVDA) text unit resolution works only for characters, words and lines in Firefox 11 while Internet Explorer 9 works with all units and reads whole paragraphs too - doesn't depend on any special website, simply paragraphs doesn't work at all in FF11 - doc's, pdf's, txt's without problems...

**Comment by leonardder** [comment]
@QChristensen, could you try to reproduce this? Should we treat this as duplicate of one of the other mouse issues #3590 or #3591?

**Comment by Qchristensen** [comment]
I'd mark #3591 as a duplicate of this (this one is clearer - the issue is paragraph text unit resolution.  The other post noticed it in bullets, but it's wider than just bullets).

#3590 (wrapped hyperlinks) is likely partly related, and fixing the mouse tracking code might resolve both at once, but that one is not only about plain text, but how multiple elements in one paragraph are read (or not) so could be separate.

**Comment by jcsteh** [comment]
Closing as duplicate of #3591.
