### ISSUE TITLE
Option to disable the "out of element" messages in web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2250]
**Reported by clev on 2012-04-18 12:36**
When navigating a web page with quick keys or the arrows, it's anoying and very unproductive to hear "out of link", "out of frame", etc., before the actual information I want to know. AFAIC, the only way to disable it currently is to disable the reporting of each HTML element in the document formating dialog. NVDA should be able to tell when we get into an element, but not everytime we get out of it.

**Comment by bhavyashah** [comment]
Several other tickets on the tracker have complained in one way or the other about NVDA's excess verbosity on the web when it comes to the reporting of various elements multiple times, the 'out of' feedback, etc. Although the original author of this ticket is now out-of-reach and unfortunately failed to respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2250#issuecomment-155297114, I would like to take this ahead from a user/reporter's standpoint.
As a slightly more radical version of the request this ticket encompasses, I would like to propose we modify a significant number of document formatting settings (with the exceptions of course of options like page numbers, line numbers, and others which don't have a defined start and end) to essentially contain the following options in the form of a combo box instead of a check box:
* Headings combo box
* moving into a heading only
* moving out of a heading only
* both moving in and out of the heading
I understand that the above phrasing is not ideal, but I hope it conveys the functionality I am attempting to describe. Verbosity would then become much more flexible and customizable in the hands of intermediate to power users.

**Comment by ruifontes** [comment]
In my humble opinion, the problem is only when we navigate withquick keys.

Please, see the examples gave in #7137.

Rui Fontes

-----Mensagem Original----- 
De: bhavyashah
Data: 14 de agosto de 2017 05:24
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Option to disable the "out of element" messages 
in web pages (#2250)



Several other tickets on the tracker have complained in one way or the other 
about NVDA's excess verbosity on the web when it comes to the reporting of 
various elements multiple times, the 'out of' feedback, etc. Although the 
original author of this ticket is now out-of-reach and unfortunately failed 
to respond to @jcsteh's #2250 (comment), I would like to take this ahead 
from a user/reporter's standpoint.
As a slightly more radical version of the request this ticket encompasses, I 
would like to propose we modify a significant number of document formatting 
settings (with the exceptions of course of options like page numbers, line 
numbers, and others which don't have a defined start and end) to essentially 
contain the following options in the form of a combo box instead of a check 
box:

Headings combo box
moving into a heading only
moving out of a heading only
both moving in and out of the heading
I understand that the above phrasing is not ideal, but I hope it conveys the 
functionality I am attempting to describe. Verbosity would then become much 
more flexible and customizable in the hands of intermediate to power users.

**Comment by ruifontes** [comment]
I don't agree to much with your proposal, since when I am arrowing through 
the page, I think is important to know when I walk out of a element like a 
list or table.
But if I am navigating with quick keys, I think it is not necessary to tell 
the user that he is out of a bunch of elements...


And, if I understood your proposal, the behaviour will be equal for arrowing 
and navigating with quick keys...


Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 14 de agosto de 2017 05:24
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Option to disable the "out of element" messages 
in web pages (#2250)



Several other tickets on the tracker have complained in one way or the other 
about NVDA's excess verbosity on the web when it comes to the reporting of 
various elements multiple times, the 'out of' feedback, etc. Although the 
original author of this ticket is now out-of-reach and unfortunately failed 
to respond to @jcsteh's #2250 (comment), I would like to take this ahead 
from a user/reporter's standpoint.
As a slightly more radical version of the request this ticket encompasses, I 
would like to propose we modify a significant number of document formatting 
settings (with the exceptions of course of options like page numbers, line 
numbers, and others which don't have a defined start and end) to essentially 
contain the following options in the form of a combo box instead of a check 
box:

Headings combo box
moving into a heading only
moving out of a heading only
both moving in and out of the heading
I understand that the above phrasing is not ideal, but I hope it conveys the 
functionality I am attempting to describe. Verbosity would then become much 
more flexible and customizable in the hands of intermediate to power users.

**Comment by ehollig** [comment]
Should this issue be closed now that #7434 is merged?

**Comment by Adriani90** [comment]
yes, closing as fixed.
