### ISSUE TITLE
Add ability to read the current paragraph and the current, sentence

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2268]
**Reported by jfauchon on 2012-04-25 11:46**
Hi,

I suggest to add ability to NVDA to read the current paragraph and sentence and the previous and next sentence (for examples, for the curent paragraph with CTRL+Pavnum5, the current sentence with ALt+Numpad5, the next and previous sentence with ALT+Numpad2 and ALT+Numpad8). Now, nvda can read the current word and the current line.

Please can you add those functionalities.

Thank you for your work.

**Comment by bhavyashah** [comment]
Sentence navigation is already covered elsewhere and thus this ticket exclusively covers keystrokes to read the current sentence and paragraph. I am not too sure if this should be accepted because it may be difficult to come up with logical keystrokes for desktop and laptop layouts given our existing concern about common keyboard shortcuts running out. No usage case has been provided either and the original author of this ticket is now out-of-reach. Thus, I suggest closing. @ehollig

**Comment by jcsteh** [comment]
Closing as won't fix.
