### ISSUE TITLE
NVDA Sluggish In Microsoft Word when report pages is enabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2296]
**Reported by parham on 2012-05-03 15:44**
NVDA does not respond quickly to keypresses in Microsoft Word. This includes normal arrow key presses, table navigation commands, and so forth.

**Comment by ehollig** [comment]
I am not able to replicate this using the latest NVDA and Word 2016. Please correct me if I am wrong and this is still the case with Word 2007. CC @Brian1Gaff

**Comment by Adriani90** [comment]
I can reproduce this in documents with many tables or many text pages. However, NVDA is reacting much faster when changing the layout in MS Word to Weblayout.

**Comment by dineshkaushal** [comment]
I also faced the problem of NVDA responding very slowly for document with table of contents.

 

In fact within the table of contents it was taking 3 – 4 seconds to respond.

 

Word 2016, windows 10, NVDA 2017.3

**Comment by feerrenrut** [comment]
@dineshkaushal and @Adriani90 This might be caused by a particular option in document formatting. To narrow this down, or rule it out, could you please try unchecking options one by one in the `document formatting` settings dialog, please let me know which of these has the largest impact.

**Comment by Adriani90** [comment]
Hello,

the slugness is most noticeable when using browse mode in ms word or ms excel to navigate through the text or cells. Following settings are activated in document formating in my case:
1. Comments
2. Editor revisions
3. Pages
4. Row / Column headings
5. Cell coordinates
6. Headings
7. Links.

I have deactivated each of them and tried it again. Slugness in browse mode if I have 3 documents open is approximately 1,5 seconds. Deactivating the settings does not make any difference.
I'm using NVDA 2017.3 on a work station (7 core processor) on windows 8.1 and MS Office 2010. I have noticed this on my private laptop (4 core Kabylake, 16 gb Ram and 1 tb SSD) on Windows 10 and Office 2016 as well.

**Comment by Adriani90** [comment]
the documents are approximately 10 to 12 pages each and the text is structured in a table. There are some overlapping tables in the documents as well. Tables in document formating is deactivated.

**Comment by Adriani90** [comment]
In MS Excel it is most noticeable when there are formfields and macros integrated in the sheet.

**Comment by feerrenrut** [comment]
Thanks for the information @Adriani90. Seems like this will require a more in-depth investigation to work out the cause. Would you be able to attach an example document to this issue?

**Comment by Adriani90** [comment]
Hey,

 

this will be complicated due to data governance at work. I would have to create some Macros in Excel and to add some formfields as well to show you the effects. I would prefer to send you a word document rather than an excel sheet.

 

 

Best

Adriani

 

 

Von: Reef Turner [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. November 2017 23:32
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA Sluggish In Microsoft Word (#2296)

 

Thanks for the information @Adriani90 <https://github.com/adriani90> . Seems like this will require a more in-depth investigation to work out the cause. Would you be able to attach an example document to this issue?

**Comment by feerrenrut** [comment]
Yes a word document is ideal, really this issue is focused on Word.

**Comment by Adriani90** [comment]
@feerrenrut I attach a document which can be used for testing. i have reinstalled NVDA and the sluggness is a bit better but still significant. Try following:

1. Open the document let's say three times (so three versions of this document)
2. Navigate by up and down arrow through the document
3. Try it in browse mode
4. Start some processes (for example Abbyy finereader or some websites
5. Navigate again through the documents
6. Navigate through the tables on the first page by using up and down arrow and ctrl + alt + arrow keys
7. Go on second page and navigate from first ro to last row by holding down ctrl + alt + down arrow and back on first row by holding 
down ctrl + alt + up arrow (both in focus and browse mode)
8. Try the steps above when view in MS word is changed to web layout

Now imagine three 10 to 12 pages full of such tables where you have to see results in some rows and go back to other table regions.

I had a table with about 220 rows and held down the ctrl + alt + down arrow to navigate to row 70 because there was an important result. I waited about 25 seconds  for NVDA to land there.

This issue occurs even when you import much text in a document and try to navigate by down arrow to a certain part.

However, the issue does not occur when navigating by letters or by paragraphs or words holding down the ctrl key. Only navigation line by line through a text and row by row or column by column in a table causes the sluggness.
[Tables2.docx](https://github.com/nvaccess/nvda/files/1515697/Tables2.docx)

Best
Adriani

**Comment by derekriemer** [comment]
@Adriani90 out of curiosity, disable each of these individually and try it.
Pages, set to off.
Spell check set to off.
Editor revisions set to off.
Please tell me if any/all of these make it faster? Just trying to see if the options @leonardder reported a while ago hold or you as slowing it down.

**Comment by Adriani90** [comment]
@Derek thanks alot for your input. I found out what it causes. This is pages. If you set it to off, NVDA reacts really fast in tables and big documents.

Is it possible to improve performance for pages turned on? It is very important in big documents to know on which page I am.

**Comment by derekriemer** [comment]
Priority assessment please? Duplicate possibly? This is a quite severe bug for those needing the feature.

**Comment by ehollig** [comment]
The only possible duplicate or related issue that I found is #6903

**Comment by Neurrone** [comment]
Wow, turning off page numbers basically made word useable again with NVDA. I've been forced to switch to jaws to use word for a long time - can this be assigned the highest priority?

It doesn't seem to matter for me what the contents of the document are - even typing or arrowing in an empty document is excruciating.

Even with page numbers off, moving in tables is still noticeably slower than in ordinary text, but is much improved compared to page numbers being on.

**Comment by Neurrone** [comment]
The first post in #7008 has a good test document with many tables.

**Comment by Adriani90** [comment]
when web layout is enabled under the ribbon "view" in MS word and "pages" are disabled in document formating settings, NVDA reacts incredibly fast even in big tables and documents.

**Comment by derekriemer** [comment]
Yeah, this is probably the highest impact possible perf fix for word.

**Comment by Brian1Gaff** [comment]
Not sure which of the seemingly many changes to office issues this one 
relates, so I'll just mention it here.
 On machines using  Office 2003/2, there are errors when you reach a page 
break in focus mode, and you cannot get past the break point up or down 
without entering browse mode first.
 Also when invoking spell check in the same versions, as the word pops up 
you also hear pane and a collection of nvda error sounds. However it 
seemingly still does work.

I'll be off now!

Brian

**Comment by leonardder** [comment]
Other issues that might be related are #6423, #5851 and #5750.

**Comment by Adriani90** [comment]
and #7921

**Comment by Adriani90** [comment]
Maybe text columns should be seprarated from pages. I don't know what else is included in this reporting setting.

**Comment by Neurrone** [comment]
Any movement on this?

**Comment by Adriani90** [comment]
@Neurrone, @parham, @dineshkaushal, in NVDA 2019.1 MS Word reacts much faster even with pages enabled. But to assess this issue correctly we need more tests. Could you guys please test if there is still a significant performance issue when pages are enabled? For me at least it works quite fine now.

**Comment by LittleStar-VIP** [comment]
Hello,
I would like to share my recent findings.
After a word is growing in number of pages, and nvda is getting more slugish,
if I restart nvda, it seems that the slugish problem is lessen a bit

**Comment by Neurrone** [comment]
I noticed this too in #9465 but won't be able to provide good reports nowadays as I don't use Word on a regular basis.

**Comment by LittleStar-VIP** [comment]
I have observed that doing the following things would also lessen the slugishness:
1. disabling some of the addon, e.g. officedesk, wordnav, etc., nvda will become less slugish
2. If it is slugish in navigating a very long paragraph, putting a line break to break down the paragraph into shorter one will reduce slugish
3. if it is a long long table, more than 100 rows, instead of tab to the end of table to create a new row, selecting multiple rows and insert rows below will reduce slugishness

**Comment by Adriani90** [comment]
In NVDA 2024.2 or NVDA last alpha there is a significant improvement in performance noticeable, and there is no noticeable difference whether reporting of pages is on or off. I tested with this document, which previously was very very sluggish with NVDA.
[ONKYO.docx](https://github.com/user-attachments/files/16090822/ONKYO.docx)

I am closing this issue as works for me. If you still notice differences between reporting of pages off or on, please comment and we can reopen.
