### ISSUE TITLE
Windows displays error when inserting CD with portable copy of NVDA installed and configured to autostart

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2321]
**Reported by challsworth2 on 2012-05-10 20:24**
If you create a portable copy of NVDA, and you configured the portable copy to automatically start, and you burn both the portable copy and the autorun.inf file to CD, Windows displays the following error message as soon as the CD is inserted.

"Windows cannot access the specified device, path, or file.  You may not have the appropriate permissions to access the item."

There is just an ok button. Clicking on this returns you to whereever you were before the above error message was displayed.

**Comment by ehollig** [comment]
Possibly related: #2216

**Comment by jcsteh** [comment]
CDs/DVDs are a lot less common now; many systems don't have such a drive. It's possible to emulate one with a U3 drive, but U3 drives have been discontinued. Thus, I don't think putting resources into this makes sense. I think running the download package (rather than a portable copy) is acceptable where someone does still want to do this.
