### ISSUE TITLE
Updating the OCR add-on to use the contentRecog framework

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2331]
**Reported by Brendon22 on 2012-05-13 12:41**
Hi, When using The OCR Plugg-in and After doing an OCR of The Screen. And trying to read it NVDA will just admit The NVDA Errar Sound? Using NVDA Version 2012.2beta1.

**Comment by bhavyashah** [comment]
@jcsteh Does this still occur? I don't think I follow the issue correctly, because pressing NVDA+R and then arrowing around doesn't seem to generate errors at my end.

**Comment by jcsteh** [comment]
I think so. It will occur if you press NVDA+r while in an editable text field.

This can be fixed by updating the OCR add-on to use the new contentRecog framework.

**Comment by bhavyashah** [comment]
To summarize:
* While I am not too sure If I am exactly able to reproduce the reported errors myself using NVDA 2017.3 on Windows 8.1, this issue ('s title in particular) needs to be morphed to cover the errors generated by NVDA when a user attempts to review the OCR results using the system caret instead of the review cursor.
* The solution, as noted by @jcsteh in https://github.com/nvaccess/nvda/issues/2331#issuecomment-322094382, is to update the OCR add-on to use the new contentRecog framework.

**Comment by Adriani90** [comment]
Please open an issue against the ocr addon itself rather than NVDA. With OCR on Windows 10 this is not occuring.
The OCR addon on github is here:
https://github.com/nvaccess/nvda-ocr
I am closing this for now.
