### ISSUE TITLE
Allow the automatic check frequency of updates to be set

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2353]
**Reported by elliott94 on 2012-05-17 11:00**
From what I understand, if automatic updates are enabled, NVDA automatically checks for updated versions every 24 hours.

It would be a nice addition to allow this frequency to be editable by the user - for example, some people may want notifications of new updates, but might want them weekly as aposed to the current timeframe.

**Comment by bhavyashah** [comment]
At least with reference to stable versions of NVDA, it is a known fact that a new NVDA version can be expected quarterly. Since we do not push updates very regularly anyways, and three months is a reasonable time frame, I consider the proposed feature request to be an unneeded overkill. The story with development builds may be entirely different though, and due to my limited knowledge and experience in that regard, I shall leave that to be discussed by others. Thoughts?

**Comment by jcsteh** [comment]
This increases complexity and makes things difficult for our statistics. Closing as won't fix. Note that less intrusive notifications (#2257) and postponing of updates (#4263) will make daily update checks less annoying for users who don't want to install the update immediately.
