### ISSUE TITLE
Features in open office, or libre office

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2382]
**Reported by lallermacher on 2012-05-25 08:34**
I know, the two programms are the same, so I write it in to one.
I would like some features in soffice, so in open, or libre office, to presend from nvda:
1. Say site numbers. So, if you write an assey for the university, it is good to see them.
2. Use spell check.
3. Better using foot, endnotes.

**Comment by Qchristensen** [comment]
Reading issue #6760, I believe Spell Check works in LibreOffice, and at the time that issue was closed it was unlikely to be addressed by Open Office as per the comments in that issue.

Here is our open issue regarding Footnotes: #10060

There is not enough information to know what the numbers request was about (line numbers? Numbered lists? Footnote numbers?).  Closing as duplicate of other two issues.
