### ISSUE TITLE
allow user to add their own punctuation substitutions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2389]
**Reported by ashleycox on 2012-05-27 09:40**
Add a feature as part of the punctuation settings dialog that allows the user to add their own substitutions, much like the dictionary manager. This allows the user to add substitutions that are currently missing, such as the period in-word replacement.

**Comment by bhavyashah** [comment]
Since the original author of this ticket is probably now out-of-reach and she unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2389#issuecomment-155298203, we remain unclear about what essentially is being requested. It is also worth noting that speech dictionaries does support regular expressions and the Puncctuation/Symbol Pronunciation dialog does allow adding of new characters for which a custom symbol level and pronunciation can be set. Thus, I suggest closing this ticket. @ehollig

**Comment by ehollig** [comment]
Closing, as @jcsteh said we can not allow for regular expression matching with symbols.
