### ISSUE TITLE
wrong reading compound words and sites

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2432]
**Reported by Twinsen on 2012-06-11 15:24**
1)If NVDA find in text word like ‘приветguest’ this word will be read incorrectly.You will be hear some thing like this ‘letter four one ,letter four thre, letter four two ...
2)Severial web pages reading in mode’
‘letter four one ,letter four thre, letter four two ...’ non stop. For example ‘:http://www.skylight-hals.ru/about.htm?  
utm_source=yandex_cpc&utm_medium=yandex_cpc&utm_campaign=yandex_arenda&utm_term=arenda_ofisnogo_pomewenij_v_moskve.

**Comment by bhavyashah** [comment]
@michaelDCurran Since you have apparently been assigned this ticket (and all others under the same category by Trac, I know), mind making a quick check and sharing your findings? I am not too sure I follow the ticket well enough to test this myself.

**Comment by jcsteh** [comment]
From the character set and the example website URL, I'm guessing this is Russian text. While I don't understand Russian, switching eSpeak to Russian and reading text containing these characters does not report text like "letter four one", etc. as described. This was possibly due to having eSpeak set to the wrong language or broken eSpeak data at the time. Regardless, this appears to be fixed. Closing as works for me.
