### ISSUE TITLE
Option to just once report position information

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2433]
**Reported by ateu on 2012-06-11 15:56**
Hi

I think the checkbox Report Position Information should be replaced with a combo box with 3 options.
Always, once and never.
But if you think this is not a good idea, when this option is turned off, NVDA should speak just once this information, as for some users, is suficient.

**Comment by bhavyashah** [comment]
CC @josephsl to request further thoughts/inputs and assistance in triaging this ticket

**Comment by Adriani90** [comment]
@jcsteh, @derekriemer your thoughts are very appreciated. In my view at least, this would not really improve user experience. Because if we think of every setting in NVDA where you can either enable or disable it, we could add several varieties for those settings but then the user will ge overwelmed by too many variants for such simple settings.

**Comment by Adriani90** [comment]
I am closing this in favor of #8187 where the discussion goes in more detail. The results of the discussion in that issue might lead to a general conclusion upon which we can open a new issue or feature request if needed.
