### ISSUE TITLE
Support for entry of contracted braille via a braille keyboard

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2439]
**Reported by jteh on 2012-06-12 06:11**
(Spun off #808.)

Supporting input of contracted braille is much more complicated than computer braille, as we need to determine when to translate a chunk of input, the user experience before translation of a chunk occurs, etc.
**Blocked by #808**

**Comment by dkager** [comment]
If liblouis is to be used to do the backtranslation it may be a good idea to investigate how well it performs these days. I know the Dutch (nl-NL and nl-BE) tables aren't written for backtranslation and probably fail for the parts that use multi-pass rules. (Side question: why does NVDA disable the multi-pass facilities when forward translating?)
For UEB there is a lot of great work done by the APH that is pending review and possible inclusion in a future version of liblouis. This code too appears to deal only with forward translation. I don't know how much of the backtranslation functionality is covered by unit tests but this might be a good place to start.

**Comment by jcsteh** [comment]
> If liblouis is to be used to do the backtranslation it may be a good idea to investigate how well it performs these days.

liblouis is all we have. I take your point, though. I guess if it's really that bad, we'll have to push for improvements to the tables and/or liblouis before we can release this.

> (Side question: why does NVDA disable the multi-pass facilities when forward translating?)

Because multi-pass breaks the input/output position mapping. I have had grand ideas of completely rewriting that position mapping code for a while, but I've never gotten to it. [Arend Arends contributed](http://www.freelists.org/post/liblouis-liblouisxml/Update-output-positions-during-multi-pass-forward-translation-only) [a patch for this](https://github.com/liblouis/liblouis/pull/133), but it hasn't been integrated yet and I believe there are some outstanding concerns.

**Comment by dkager** [comment]
The next release of liblouis is planned for next Monday and should include the patches contributed by Arend, Bue, etc.

I’d be happy to look into backtranslation for the Dutch tables, though if it requires extensive code changes it’ll have to wait till the new year.

**Comment by derekriemer** [comment]
1. select UEB 
2. type dots a 3456-1 
3. type space. 
a is actually typed rather than 1

**Comment by derekriemer** [comment]
In UEB, type hello!
125-15-123-123-135-235 
Result: ff is typed rather than !

**Comment by derekriemer** [comment]
Type 542 
press space
delete until 2
type b 12
a 2 should appear, rather but appears.

**Comment by derekriemer** [comment]
As a user, I'd find it useful to force NVDA to translate with out forcing an enter or space.

**Comment by derekriemer** [comment]
Great work, that's all my observations as of now.

**Comment by jcsteh** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:23 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252984676 "2016-10-11T17:23:03Z - Replied by Github Reply Comments"):
> 1. select UEB 
> 2. type dots a 3456-1 
> 3. type space. 
> a is actually typed rather than 1

I can't reproduce this. I get "1" as expected.

[**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:27 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252985822 "2016-10-11T17:27:04Z - Replied by Github Reply Comments"):
> In UEB, type hello!
> 125-15-123-123-135-235 
> Result: ff is typed rather than !

I can't reproduce this either. I get "!", not "ff", once translation is complete. However, if you use speak typed characters, you will hear "ff" when you type the dot 2-3-5 because we can't actually be certain of what the character will be until translation is complete. Once you press space, the text actually entered will be "!", though.

[**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:28 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252986236 "2016-10-11T17:28:31Z - Replied by Github Reply Comments"):
> Type 542 
> press space
> delete until 2
> type b 12
> a 2 should appear, rather but appears.

Unfortunately, we can't fix this. Translation is based only on the word you're typing, not text at the cursor. Doing otherwise would require that the input and output tables always be the same, which is not always desirable. Also, later cells can change the text produced by earlier cells, so if that text has already been entered, that's problematic. Perhaps this needs to be documented more clearly, though.

[**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:31 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252987157 "2016-10-11T17:31:41Z - Replied by Github Reply Comments"):
> As a user, I'd find it useful to force NVDA to translate with out forcing an enter or space.

I didn't add this because I felt it might be confusing for users. You should be aware that if you pressed this, it would reset translation. For example, typing "b", then ending translation, then typing "b" again would result in "butbut", not "bb". Is that what you expect?

**Comment by derekriemer** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [Oct 11, 2016, 4:57 PM MDT](https://github.com/nvaccess/nvda/issues/2439#issuecomment-253071708 "2016-10-11T22:57:43Z - Replied by Github Reply Comments"):
> [**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:23 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252984676 "2016-10-11T17:23:03Z - Replied by Github Reply Comments"):
> 
> > 1.  select UEB
> > 2.  type dots a 3456-1
> > 3.  type space.
> > a is actually typed rather than 1
> 
> I can't reproduce this. I get "1" as expected.
> 
I can't any more. I think what I meant to say is things like that found in a password would do fill1 would go as fillable
This can be fixed by using the new press a key to force translation, which is actually nice for this case.
> [**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:27 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252985822 "2016-10-11T17:27:04Z - Replied by Github Reply Comments"):
> 
> > In UEB, type hello!  
> > 
> > 125-15-123-123-135-235   
> > 
> > Result: ff is typed rather than !
> 
> I can't reproduce this either. I get "!", not "ff", once translation is complete. However, if you use speak typed characters, you will hear "ff" when you type the dot 2-3-5 because we can't actually be certain of what the character will be until translation is complete. Once you press space, the text actually entered will be "!", though.

Not here. @josephsl can reproduce this as well. I also can type "hello!!!!!" and I get "hello! to to to to" in multiple braille tables.

> 
> [**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:28 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252986236 "2016-10-11T17:28:31Z - Replied by Github Reply Comments"):
> 
> > Type 542   
> > 
> > press space  
> > 
> > delete until 2  
> > 
> > type b 12  
> > 
> > a 2 should appear, rather but appears.
> 
> Unfortunately, we can't fix this. Translation is based only on the word you're typing, not text at the cursor. Doing otherwise would require that the input and output tables always be the same, which is not always desirable. Also, later cells can change the text produced by earlier cells, so if that text has already been entered, that's problematic. Perhaps this needs to be documented more clearly, though.

Could it be possible to make NVDA work in this case only if input == output?

> 
> [**@derekriemer**](https://github.com/derekriemer) commented on [12 Oct. 2016, 3:31 am AEST](https://github.com/nvaccess/nvda/issues/2439#issuecomment-252987157 "2016-10-11T17:31:41Z - Replied by Github Reply Comments"):
> 
> > As a user, I'd find it useful to force NVDA to translate with out forcing an enter or space.
> 
> I didn't add this because I felt it might be confusing for users. You should be aware that if you pressed this, it would reset translation. For example, typing "b", then ending translation, then typing "b" again would result in "butbut", not "bb". Is that what you expect?

The benefit of this is when entering something like brailleit4u or something with a number in a word.

**Comment by jcsteh** [comment]
> > > a is actually typed rather than 1

My sincere apologies. I can in fact reproduce this now that I'm running liblouis 3. Previously, I was running an outdated liblouis. I never considered the possibility that they might have regressed it in liblouis 3. :(

Both this and the "hello!" case are due to bugs in the liblouis 3 UEB tables. According to [this mailing list post, UEB backtranslation issues are being addressed at present](https://www.freelists.org/post/liblouis-liblouisxml/ueb-backtranslation-numbers,1). That post also requests people to report any backtranslation issues they encounter.

> > Unfortunately, we can't fix this. Translation is based only on the word you're typing, not text at the cursor. Doing otherwise would require that the input and output tables always be the same, which is not always desirable.
> Could it be possible to make NVDA work in this case only if input == output?

No. Later cells can still change the text of earlier cells. So, if the previous word was "tg" and you type "r", it has to try to erase the "g" and insert "ogether". Things get even more complicated if the user drops the cursor into the middle of a word. And those examples are without even trying to come up with obscure edge cases.

> > > As a user, I'd find it useful to force NVDA to translate with out forcing an enter or space.
> The benefit of this is when entering something like brailleit4u or something with a number in a word.

Well, you can do that without ending translation; UEB does support that (table bugs notwithstanding). Regardless, I've implemented this now.

**Comment by leonardder** [comment]
@jcsteh: Reported this earlier on IRC, but for refference.
When you select UEB1 as input table and enter dot 6, dot6 will stick on the braille display until you do another braille input gesture. This is expected of course, however it leads to slightly unexpected behaviour when you press dot 6 and than change your mind and start typing on the pc keyboard. Dot 6 will stay until the braille buffer until you switch windows or resume braille input.

**Comment by jcsteh** [comment]
Deferring to 2017.1 due to outstanding issues. See https://github.com/nvaccess/nvda/pull/6449#issuecomment-258073729 for details.

**Comment by feerrenrut** [comment]
Consider fixing "Make Unified English Braille the default Braille code" #6952 as part of this issue.

**Comment by josephsl** [comment]
Hi, I propose putting that all under Liblouis 3.1.0 PR (#6935). Thanks.

**Comment by Adriani90** [comment]
I see that the discussion here is very comprehensive. Is this issue now solved? Or could someone give a short update on this?
Thank you.

@josephsl sephsl, @jcsteh

**Comment by josephsl** [comment]
Hi,

Never mind about my last comment. Perhaps Adriani didn't see the issue was actually closed.

Thanks.
