### ISSUE TITLE
NVDA read the web pages to fast or to slow

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2441]
**Reported by Twinsen on 2012-06-12 13:44**
I use the Internet Explorer 9, Im from Russia. When i go to http://ru.wikipedia.org/ i type in search edit field -'Александр Македонский'after this i press (Enter). The nvda start reading Greek alphabet placed on web page after this NVDA talk to slow or to fast.

**Comment by rhdunn** [comment]
Using:

    src/espeak-ng -vru "Hello Александр Македонский, how are you?"

Both English parts are spoken normally, while the Russian appears sped up. As such, I think it is that the Russian phonemes have a shorter duration than the English ones, so appear faster at the same speech rate, although I have not confirmed this.

**Comment by Brian1Gaff** [comment]
I assume you are one of the developers of Espeak, since nobody has said, but I've often wondered how the samples are produced, as  we consistently hear that the us English is not very American sounding, and listening to it, it seems to be lacking the twang extension one hears in us voices based on eloquence etc. Not that I like that voice, nor am I an American :-)
 
The Quincy voice in nvda is one I fiddled with and made, and many seem to like it. 
 So how exactly are the samples made?
 As this is a ticket, you might wish to transfer this to a list instead.


bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----

**Comment by rhdunn** [comment]
Jonathan Duddington is the developer of espeak. I have been maintaining a POSIX/Linux build and the Android port for some time now. Recently, I have taken on the role of developing the espeak-ng fork.

Regarding how the samples are produced, the data is a mix of wave audio, spectral formant data and klatt formant data (for the klatt voices). These are selected and mixed according to phoneme rules. I don't currently fully understand how that code works, so I don't currently know how to modify a voice to produce the effect you describe.

**Comment by ehollig** [comment]
@rhdunn, since this sounds like an Espeak issue, can you file an issue on this topic on the [ESpeak Issues on Github](https://github.com/espeak-ng/espeak-ng/issues/new) and post a link to the issue here so that we can track it?

**Comment by ehollig** [comment]
Looks like this issue has been resolved in Espeak. Closing
