### ISSUE TITLE
Allow NVDA to speak the bullets and numbering, and list levels  in Microsoft Word lists

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2446]
**Reported by jhomme on 2012-06-13 11:00**
In Microsoft Word, NVDA knows that a paragraph has the list paragraph stile and other list styles. It would be very helpful to know which list item you are reading, and what level in the list you are working with if you are dealing with a multi-level list, such as an outline. The same goes with bullets of various kinds.

**Comment by michaelDCurran** [comment]
Review: 
The limitations of this implementation are that the level is announced for each new list item even if it has not changed, and the level is nnot announced when moving by character.  Both of these could be fixed by doing the following:
* In winword.cpp: rather than fetching the list level when getting the bullet, fetch it with the initial format fields (i.e. when we fetch line numbers and alignment). 
* in speech.py: handle list-level like we handle alignment etc... don't limit it to the existence of line-prefix.

**Comment by bhavyashah** [comment]
Since vrdhn  is the author of the code which @michaelDCurran reviewed in https://github.com/nvaccess/nvda/issues/2446#issuecomment-158818042 but his Github username is unknown to me, could someone please mention him (or perhaps another NVDA India member) for the suggestions put forth by Mick to be incorporated?

**Comment by bhavyashah** [comment]
Found out Vardhan's username - CC @vrdhn 
Could you please take a look at @michaelDCurran's review suggestions provided in https://github.com/nvaccess/nvda/issues/2446#issuecomment-158818042s and make the necessary changes?

**Comment by Adriani90** [comment]
@vrdhn, is your patch still needed? Could you please raise a pull request for NVDA and address the review comments above?
@dkager, any further comments on this issue?

**Comment by dkager** [comment]
All I can say is that reporting list levels would be a nice productivity addition.

**Comment by Adriani90** [comment]
I Close this one in favor of #6815 where list Levels are covered. Also in favor of #7742 and #7804 where bullet reporting is covered.
