### ISSUE TITLE
NVDA does not see document contents in Reader metro app

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2498]
**Reported by pitermach on 2012-06-27 20:27**
Just open any PDF file in the new reader app in Windows 8. NVDA will say the document has focus, but will not read anything. This does work fine with Narrator, which suggests an issue with NVDA.

**Comment by ehollig** [comment]
@josephsl, do you know if Metro apps have been officially superseded by UWD apps or whether they are still supported by Microsoft?

**Comment by Adriani90** [comment]
I am closing this issue as abandoned, probably metro apps have significantly changed since this issue has been reported, and we don't have any updates on the current situation since years. Microsoft officially announced that that technology is now integrated into the UWP app environment. Many old metro apps have been discontinued and replaced by UWP apps, see for example metrotweet. Please open a new updated issue if there is any issue with a specific app and we can start the discussion from there.
