### ISSUE TITLE
Issues reading in windows media center

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2500]
**Reported by ashleycox on 2012-07-01 13:08**
When navigating the menus in windows media center, nvda announces "pane" before every menu item. Also, if text appears on screen such as in a dialog box, nvda can't read the text.

**Comment by leonardder** [comment]
[WMC is discontinued](https://en.wikipedia.org/wiki/Windows_Media_Center). Also considering this ticket being abandoned, closing this as won't fix. However, since Media Center is still available in pre Windows 10, I think we could accept a third party fix for this if someone is ever willing to provide it, which I doubt.

**Comment by josephsl** [comment]
Hi, anyone using Windows 7 willing to provide a fix/PR please? Thanks.
