### ISSUE TITLE
when using the insert key to read lines overwrite mode becomes active

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2510]
**Reported by csm120 on 2012-07-07 03:30**
When using the insert key to read line etc overwrite mode becomes active. I have seen this happen in MsWord, wordpad, notepad, and even web forms. I would love to see a way to stop this from happening as it can be disconcerting to see that part of your document has been eaten. I realize that you can use the capslock key for the same things, but I like the flexibility of insert or capslock.

**Comment by bhavyashah** [comment]
@jcsteh The original author of this ticket is now out-of-reach and this ticket is over five years old, leading me to believe that it is very likely that this issue may have been resolved over the years, because such a bug would have been regularly reported were it non-exclusive to csm120. Thus, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as the ticket is over 5 years old and I do not recall this issue being reported before.
