### ISSUE TITLE
Option to suppress speaking of "blank" for blank lines

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2522]
**Reported by forcric on 2012-07-11 08:50**
Nvda implementing a way to suppress the showing of blank lines.    one can stop the blank line from being announced but you still have silence as you go over the line.  It wold help when reading line by line.

**Comment by bhavyashah** [comment]
@feerrenrut Do you consider this feature request accepted, or do we require further discussion on its UX, usage case, value, etc.?

**Comment by ehollig** [comment]
If this is specifically for browse mode, this is being addressed in #6704.

**Comment by feerrenrut** [comment]
It's a shame that there isn't a specific example of where the reporter expected this to apply. I would assume they were asking for this behaviour across the board.

**Comment by fernando-jose-silva** [comment]
For me I find a place where this would be very interesting.
Using outlook 2016 I get several emails that have a huge amount of empty lines, this I believe due to how the navigation mode of the nvda deals with these emails.
Being able to suppress empty lines in this case would speed up reading these emails much better.
These emails are very common coming from social networks like faceboo ,, linkdyn.

**Comment by bhavyashah** [comment]
@feerrenrut I suppose the original reporter was requesting this universally.
@fernando-jose-silva I believe there is some confusion with regards to what this ticket encompasses. NVDA says 'blank' for every blank line it encounters. The request being made here is to suppress the speaking of 'blank' so that NVDA would stay silent when one is arrowing down a chunk of empty lines. On the other hand, what you seem to be suggesting is for NVDA to suppress the blank lines themselves, such that NVDA would directly jump over a block of such blank lines and move ahead of the emptiness.

**Comment by fernando-jose-silva** [comment]
Yes you're correct, do you think it's worth me to request the request I made in another call?

Enviado do meu iPhone

**Comment by bhavyashah** [comment]
@fernando-jose-silva No, that feature request has already been made in #4904.

**Comment by fernando-jose-silva** [comment]
Perfect thank you.

 

De: bhavyashah [mailto:notifications@github.com] 
Enviada em: sábado, 19 de agosto de 2017 22:52
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Option to suppress speaking of "blank" for blank lines (#2522)

 

@fernando-jose-silva <https://github.com/fernando-jose-silva>  No, that feature request has already been made in #4904 <https://github.com/nvaccess/nvda/issues/4904> .

**Comment by ehollig** [comment]
I had a request from a user for this feature. It is most noticeable in some emails in Outlook. Is this still being considered as something to be added to NVDA?

**Comment by XLTechie** [comment]
I've observed surprisingly many requests for this feature over the years on 
mailing lists, and in direct support calls.
Apparently some people really hate hearing "blank".

**Comment by Qchristensen** [comment]
This seems to be the same request as #4904.  I'm going to close this issue as a duplicate, even though it is older, as #4904 links to many of the other duplicate issues where this one doesn't.  Also the original requested solution (a document settings option to skip blank lines) is clearer in #4904.
