### ISSUE TITLE
app module for Lambda math editor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2568]
**Reported by peter on 2012-07-30 08:38**
Hello,
Attached is the application module for Lambda math editor (http://www.veia.it). The module actually works only with portable nvda because of http://www.nvda-project.org/ticket/2483
**Blocked by #2483**

**Comment by albzan** [comment]
Hi,
I've developed an add-on for Lambda. You can find it at:
https://github.com/albzan/lambda-nvda/
The current version has braille table for the italian language only. Other tables can be added if anyone want to produce them.
Alberto

**Comment by ehollig** [comment]
This sounds like it is related to #1521. Has this been included into NVDA?

**Comment by josephsl** [comment]
CC @NVDAES

**Comment by Adriani90** [comment]
Unfortunately the Lambda project is discontinued and the website is offline. See
https://www.researchgate.net/publication/221010211_LAMBDA_A_European_System_to_Access_Mathematics_with_Braille_and_Audio_Synthesis

and
https://www.lambdaproject.org/

Also the links for Facebook, Instagramm or Twitter on this website do not work.
I hope this will not happen to Mathcat as well after some years. But I think as always it will be a question of how many users will demand this.

So in this case I will close this issue since Lambda math editor is not available anymore.

**Comment by albzan** [comment]
> So in this case I will close this issue since Lambda math editor is not available anymore.
There is a new scientific editor both for math and chemistry developed by ONCE (the spanish blind association). It is free and I developed the related nvda addon. It is called EDICO and it is available in English too.
More info at:
https://cti.once.es/noticias/disponible-el-editor-cientifico-once
download it from:
http://cidat.once.es/repos/edico/Edico.application
It requires a registration only to prevent abuses, since it is considered an educational aid for the blind.
Alberto
