### ISSUE TITLE
Drag and Drop Addons into the Addonsmanager to install them

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2579]
**Reported by Bernd on 2012-08-02 16:38**
Would it be possible to pick up Addons with mouse and drop the file in to the Addonsmanager?

**Comment by bhavyashah** [comment]
Dragging and dropping is not a typical method used by the average visually impaired computer user, but this addition might be nice to have for a sighted NVDA user. Thoughts? @feerrenrut @Qchristensen

**Comment by Qchristensen** [comment]
While I'm not against the idea, I wonder how many users would take advantage of it compared to the resources to implement it?

If I was redesigning the add-ons dialog, I'd probably look first at whether we could display the add-ons listed at https://addons.nvda-project.org/index.en.html directly in the window and enable them to be installed directly from there, rather than linking to the page where users have to download manually.

**Comment by Adriani90** [comment]
Pressing enter on an addon and installing it works also in a portable version, at least for me it works. I am not against this idea, I think there will be more discussions on this after carret and focus highlight is implemented by @leonardder. 
cc: @nishimotz

**Comment by seanbudd** [comment]
@Adriani90 - we do not display available and installed add-ons side-by-side. Also as a sighted user, I would find pressing the install button on an available add-on much more natural than dragging them between lists.

Drag/drop is much more typical for file upload - e.g. dragging from File Explorer to NVDA. 
With that scenario - you don't even need to drag - clicking an add-on file opens it in NVDA.

I am closing this as won't fix - a user can open an NVDA add-on file to install it in NVDA in any scenario where they could drag/drop instead.
