### ISSUE TITLE
Add ability to report exact slider value

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2617]
**Reported by pitermach on 2012-08-23 14:50**
This has been posted on the NVDA support list. A user is requesting the ability to report an actual slider value rather than its percentage, which is how window-eyes does it.

> I have few viry big sliders where i must have exactly talking >position. These are sliders about 10000 positions so percent >changes >every 100. I must know is this for example 20 or 80. Of >course i can >pressing down / up arrow to change percent, but this >is quite annoing. 

This could just be a toggle in object presentation, or an something that could be reported after pressing NVDA+Tab. Narrator on windows 8, if report additional information is turned on, and the narrator cursor is placed on a slider, after the percentage is announced it does say, for example, "current value 400, minimum value 0, maximum value 10000".

**Comment by leonardder** [comment]
@pitermach: Do you still belief this should be implemented?

**Comment by Adriani90** [comment]
@pitermach, are you still active on Github? @leonardder what do you think? At least in my view, I do not care much about reporting value or percent in sliders. At least for me it is more important the percentage because it give me a sense of orientation on how far the slider goes. The absolute value is very abstract and you have to know the maximal value which results in much more verbosity.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, and it seems there were no further strong arguments for implementing this so far. I am closing this as abandoned. If anyone has an use case for this and a strong argument for the need of such a feature, please comment and we can reopen.
