### ISSUE TITLE
request support urdu language again

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2774]
**Reported by princeMoinKhan on 2012-11-02 19:13**
hi,
i want to discus with you about urdu language support  in NVDA
 you have add previously urdu language in NVDA but now urdu language support no more in NVDA 
please add again urdu language support in NVDA because we want to improve it
i have 5 to 6 student for this work like improving urdu language,   translations, pronunciations and testing 
if  you have  any problem for adding again urdu language then please let me know 
thanks.

**Comment by ehollig** [comment]
Is the Urdu language now supported in Espeak NG? I do see it as an option voice settings dialog. CC @jcsteh @josephsl and whoever might know

**Comment by jcsteh** [comment]
I can't speak for its quality, but yes, it's listed.

Closing due to lack of feedback from reporter and availability of Urdu in eSpeak NG. For improvements in the eSpeak NG language, please follow this up in the [espeak NG project](https://github.com/espeak-ng/espeak-ng). There's also an Urdu translation of the NVDA interface, though it's several years out of date now. If you are a translator and want to update this, please see [the translation documentation on the wiki](https://github.com/nvaccess/nvda/wiki/Translating).
