### ISSUE TITLE
NVDA mixing letters in the Windows Store app comment.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2779]
**Reported by aleskis on 2012-11-03 16:52**
1. Install one app.
2. Go to comment it.
3. In the edit box to give your opinion, NVDA mixing letters when you're writting quickly.

**Comment by ehollig** [comment]
I am not sure what to think about this ticket. The original author does not state what version of NVDA they are using or the operating system version. Due to the age of this ticket, I assume it is referring to Windows 8, which has been superseded by Windows 8.1. Any thoughts @josephsl or @bhavyashah

**Comment by bhavyashah** [comment]
@ehollig I have no experience with using Windows Store even though I use Windows 8.1. @josephsl Do you have any thoughts or ideas about this bug report? If all of us fail to understand this ticket and are not able to reach the original author of this ticket, we might want to consider closing it.

**Comment by josephsl** [comment]
Hi,

If only if we can contact the original poster...

Since the ticket was created in 2013, a lot of changes were made to Windows Store (now Microsoft Store) since then, too many to list. Along with this, it might be possible that this issue is no longer relevant or a fix was provided by Microsoft. Also, given mixed to negative reception of Windows 8.x, coupled with Microsoft's campaign to encourage people to adopt Windows 10 means we won't find a way to resolve this.

Thus I'll close this. Please reopen if and only if:

* The original poster comes forward.
* There's a reliable way to reproduce this on Windows 8.x.
* The root cause should be identified no later than 2022 in order to prepare time to test a potential fix before Windows 8.x is declared EOL (end of life) in January 2023.

Thanks.
