### ISSUE TITLE
NVDA keyboard layout switch announcement is too verbose

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2809]
**Reported by aleksey_s on 2012-11-19 22:42**
This is discussed recently on Russian NVDA Community mailing list.
I am using windows seven with english interface, Russian NVDA interface. Reproducible also on windows with Ukrainian and Russian interfaces.

Pressing ctrl+shift to switch input languages makes NVDA speak "English (united states) - us", "Russian (Russia) - Russian", "Ukrainian (Ukraine) - Ukrainian", whereas before it used to say more briefly "Russian layout", "Ukrainian layout" etc.

Hearing "Russian" three times is imo too verbose.

**Comment by jcsteh** [comment]
While I understand the annoyance this causes, it's important to provide the language information, as the exact language isn't always clear from the layout. It'd be nice if we could compare the two to check for commonalities, but unfortunately, even this breaks for US (where the language includes United States but the layout is named US). If this is desperately needed, we could add an option to just speak the layout or speak the layout first. Closing for now due to inactivity, but please comment if there is a current need for a change here.
