### ISSUE TITLE
Focus and browse mode do not behave reliably.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2832]
**Reported by Harich on 2012-11-29 03:14**
In many instances, the focus and browse mode do not behave reliably. That is, where you expect them to turn on and off as intended, they do not do so. For instance, if I landed in a edit field, using arrow key and had my character focus turned on, it would not happened in some cases. The same is true for other focus mode setting. This is more so apparent in Windows Eight.

**Comment by ehollig** [comment]
Is this still the case @Brian1Gaff? The website that was provided does not exist anymore and I am unable to replicate the issue described here.

**Comment by Brian1Gaff** [comment]
It is far more reliable these days. This was quite a long time ago now and I 
think some other work has resulted in this working better.
 Of course if its a really s l o w machine it can be an issue, but if its 
that slow usually the page navigation is also slow due to overuse of 
scripts.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
Thanks for the update. Closing as worksforme
