### ISSUE TITLE
Improvements for Danish liblouis braille table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2835]
**Reported by MHameed on 2012-11-29 16:50**
Work with NSvendsen to identify mistakes.
- correct the Danish table
- correct/add to the test harness.

**Comment by dkager** [comment]
@BueVest Could you share the status of the Danish tables? Did you update existing tables, or should NVDA use different ones now? Is your work already complete?
Thanks!

**Comment by BueVest** [comment]
Apparently, this is from back in 2012, before I started working with the Danish tables in liblouis. In version 3.20, all the Danish tables should be  clearly marked both with metadata and description in clear text of function and intended use. Particularly, the da-dk-g08 table is the Danish 8 dots computer braille table for both input and output (there is no 6 dots Danish computer braille). Apart from the 8 dots computer braille table, there are tables for translation/back-translation in grade 1, 1.5 and 2, both 6 and 8 dots. There are also “literary” tables for 6 dots grade 1, 1.5 and 2 for output to paper Braille. These last tables are not suited for back-translation and are probably less relevant for NVDA.

 

If you have any questions, please don’t hesitate to ask me.

 

 

 

 

Fra: Davy Kager [mailto:notifications@github.com] 
Sendt: 15. juli 2017 20:24
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: BueVest <bue@vester-andersen.dk>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Improvements for Danish liblouis braille table (#2835)

 

@BueVest <https://github.com/buevest>  Could you share the status of the Danish tables? Did you update existing tables, or should NVDA use different ones now? Is your work already complete?
Thanks!

**Comment by dkager** [comment]
@BueVest Thanks for the thorough reply!
Do I understand correctly that the work on the Danish tables is finished, but that we may have to add some new tables to NVDA?

Which tables do you think are useful for screen reader users? NVDA currently includes:
- da-dk-g16.ctb
- da-dk-g18.ctb
- da-dk-g26.ctb
- da-dk-g28.ctb

Do you think we should add:
- Computer braille: da-dk-g08.ctb
- Grade 1.5: da-dk-g26l.ctb and da-dk-g28l.ctb

**Comment by BueVest** [comment]
I would say that da-dk-g08 is the most essential of them all. It should be used as the default table for input/back-translation in Danish. Also, the g1 and g2 tables for both 6 and 8 dots are obvious candidates.

 

If there are no restrictions on the number of tables, then the g1.5/g2l tables would be nice to have. Deaf-blind users would benefit from them, since most of them don’t use grade 2, but quite a few of them use grade 1.5 (limited contraction). Besides, NVDA would then be the only screen reader to offer this feature in Danish.

 

Please, remember that all Danish tables support both forward and back-translation, except for the tables that have “lit” in their name. These tables are only meant for literary Braille production and create a little more “relaxed” Danish Braille without indication of capital letters and a few other things that would make ambiguous back-translation. I don’t think they are very important in the context of NVDA, unless users start asking specifically for them for some reason.

 

 

 

 

Fra: Davy Kager [mailto:notifications@github.com] 
Sendt: 16. juli 2017 13:57
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: BueVest <bue@vester-andersen.dk>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Improvements for Danish liblouis braille table (#2835)

 

@BueVest <https://github.com/buevest>  Thanks for the thorough reply!
Do I understand correctly that the work on the Danish tables is finished, but that we may have to add some new tables to NVDA?

Which tables do you think are useful for screen reader users? NVDA currently includes:

*	da-dk-g16.ctb
*	da-dk-g18.ctb
*	da-dk-g26.ctb
*	da-dk-g28.ctb

Do you think we should add:

*	Computer braille: da-dk-g08.ctb
*	Grade 1.5: da-dk-g26l.ctb and da-dk-g28l.ctb

**Comment by BueVest** [comment]
BTW, I wouldn’t say that the Danish tables are finished. Making them is a bit of an on-going process, especially because of the way the Danish Braille Committee is apparently just making ad hoc solutions for whatever they think they want to address along the way instead of making a good set of rules that can last for some time to come.

 

However, the current tables should be working ok, if that is what you mean by “finished”. (smile)

 

Fra: Davy Kager [mailto:notifications@github.com] 
Sendt: 16. juli 2017 13:57
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: BueVest <bue@vester-andersen.dk>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Improvements for Danish liblouis braille table (#2835)

 

@BueVest <https://github.com/buevest>  Thanks for the thorough reply!
Do I understand correctly that the work on the Danish tables is finished, but that we may have to add some new tables to NVDA?

Which tables do you think are useful for screen reader users? NVDA currently includes:

*	da-dk-g16.ctb
*	da-dk-g18.ctb
*	da-dk-g26.ctb
*	da-dk-g28.ctb

Do you think we should add:

*	Computer braille: da-dk-g08.ctb
*	Grade 1.5: da-dk-g26l.ctb and da-dk-g28l.ctb

**Comment by dkager** [comment]
OK, I will bake a PR with these updates. Yes, by "finished" I meant "ready for inclusion". :)
Does one say grade 1.5 or grade 2l?

**Comment by BueVest** [comment]
Actually, in Danish we say something like small contraction, but there is no proper and agreed-upon English term, and the grade system never quite hit it in Denmark. I think grade 1.5 would be understandable in the English version, and then we will translate it to the proper Danish terms. I was thinking of renaming the tables to g1_5 instead of g2l, but that would have to be part of a larger renaming scheme, possibly including extensions whenever we get to decide which ones to use for what in the Liblouis community.

 

 

 

Fra: Davy Kager [mailto:notifications@github.com] 
Sendt: 16. juli 2017 15:31
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: BueVest <bue@vester-andersen.dk>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Improvements for Danish liblouis braille table (#2835)

 

OK, I will bake a PR with these updates. Yes, by "finished" I meant "ready for inclusion". :)
Does one say grade 1.5 or grade 2l?

**Comment by BueVest** [comment]
Did you also enable the remaining grade 1 and 2 tables for input?

 

 

Fra: Davy Kager [mailto:notifications@github.com] 
Sendt: 16. juli 2017 15:31
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: BueVest <bue@vester-andersen.dk>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Improvements for Danish liblouis braille table (#2835)

 

OK, I will bake a PR with these updates. Yes, by "finished" I meant "ready for inclusion". :)
Does one say grade 1.5 or grade 2l?

**Comment by dkager** [comment]
Danish 6-dot/8-dot grade 1 and 2 were already enabled for input. I didn't test them though.

**Comment by ehollig** [comment]
@dkager, should this be closed, as #7407 is closed?

**Comment by dkager** [comment]
Danish grade 1.5 is not yet in NVDA. However, there also has not been a user request that I know of, except for a hint by the table maintainer. Closing this until such a request is made. Then it would be trivial to add these last tables.
