### ISSUE TITLE
Using Festival Synth, NVDA not continuing reading when nvda+down is pressed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2839]
**Reported by aliminator on 2012-11-30 08:18**
This has been tested both in Notepad++ and Notepad.
When invoking the readAll command  NVDA does not continue to read if there more than nine blank lines and text follows.
Example 1: Paste it into Notepad.text d is not read:
this is a small text.
text a 
text b 
text c 

text d

Second example: Paste it into Notepad and read it again.Now it should work.
this is a small text.
text a 
text b 
text c 

text d

**Comment by bhavyashah** [comment]
According to https://en.wikipedia.org/wiki/Festival_Speech_Synthesis_System, the last stable release of the Festival speech synthesizer was in December 2014. Evidently, as previous comments seem to suggest, this issue is specific to Festival, whose development seems inactive. Unless we can get active Festival devs to cooperatively investigate the reported issue, I would like to kindly suggest closing this ticket. @ehollig

**Comment by ehollig** [comment]
this indeed sounds to be specific to Festival and needs an external fix.
