### ISSUE TITLE
NVDA loses focus and position in editable field and forms.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2841]
**Reported by Harich on 2012-11-30 22:46**
When filling out web forms or other similar editable field, e.g. entering user name and password, the NVDA loses its position from the focus of the selected field where it should not be doing so. For instance, I entered the user name and password in the logging page of my web mail site, but, when I tabbed to click on login/submit button, the NVDA cursor took me to the top of the page. I then literally had to navigate back to the location I was at before.

**Comment by ehollig** [comment]
I do not have an issue filling out the form provided in https://github.com/nvaccess/nvda/issues/2841#issuecomment-155302958. NVDA position does not get lost.

**Comment by ehollig** [comment]
Closing as worksforme, as reported in https://github.com/nvaccess/nvda/issues/2841#issuecomment-317594277. Also, the third combo box on the page reports as, "Select a Product combo box collapsed unavailable". This is because it depends on information to be selected in the previous combo boxes before it is active.
