### ISSUE TITLE
On certain web pages especially those with a test format NVDA runs very slow and uses a lot of CPU power

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2844]
**Reported by electronicman on 2012-12-03 02:25**
I am using a web site called www.universalclass.com provided by my local library.  I am taking classes online and the radio buttons and questions are extremely unresponsive.  It takes many seconds to possibly a minute to get the question read.

**Comment by ehollig** [comment]
It appears that there is not enough information provided in this ticket to replicate the issue and no way to contact the original poster. Can this issue be safely closed as invalid?

**Comment by bhavyashah** [comment]
Since the original author of this ticket is now out-of-reach, he/she unfortunately failed to respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2844#issuecomment-155302983, the test case requires login credentials to access the Q&A section (as it seems to me) which we lack, and I believe this is merely a specific instance of Java focusing errors and jumpiness which has certainly been covered in other tickets, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster for more information, and the test case provided requires a username and password combination.
