### ISSUE TITLE
Update related dialogs unexpectedly get focus

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2847]
**Reported by bramd on 2012-12-04 18:29**
Steps to reproduce:
1. Make sure there is an NVDA update available
2. Open a web page
3. Select the option to download the update
4. Use NVDA search (ins+ctrl+f) on the website

Expected result:
After searching the focus should return to the website.

Actual result:
The search result is being read, but the focus is moved to the "Downloading update" or "Update is ready to install" dialog.

**Comment by leonardder** [comment]
@BramD, can you still reproduce this? Might be related to #4228

**Comment by bramd** [comment]
@leonardder Wow, that's an old one. Just tried the exact steps I described. While the downloading dialog was displayed, nothing special happened. However, when the message that the download was succesfull and the update will be installed is displayed, the find dialog seems to react strangely. Tabbing no longer works properly and pressing enter doesn't activate the OK button anymore. I can't cancel out of it either.

**Comment by bramd** [comment]
@leonardder Wow, that's an old one. It seems I can't reproduce this right now with the "No updates available" dialog open on next. Will try it again if there are updates.

**Comment by bramd** [comment]
@leonardder Started an older build to trigger updates. When the dowloading dialog is visible, nothing strange happens. However, when the download is complete and the message box that the update will be installed appears, things get weird.

Opening a find dialog doesn't work as expected, tabbing around doesn't work and OK/cancel with enter/escape doesn't activate the buttons. I found an easier way to trigger this, just search for something that can't be found and open a second Find dialog. Now you should see the behavior I described.

**Comment by jcsteh** [comment]
If I'm reading this right, the originally reported behaviour (an update dialog gaining focus after dismissing the Find dialog) no longer occurs. The weird issue with the Find dialog not responding to key commands (tab, enter, escape, etc.) occurs because the update success dialog is a modal dialog, which seems to block messages from getting to modeless dialogs. #1451, #3361 and #5735 are other instances of the same behaviour (with the same cause). #1740 also has the same cause, though with different results.

By definition according to wx, a modal dialog blocks input to all other windows, so I guess this makes sense. However, it surprises me that there doesn't seem to be a way to prevent this from affecting other top level windows in the same app in wx. For example, if you have two documents open in Word or two browser windows open in Chrome, a modal dialog in one window doesn't affect the other window at all.

**Comment by Brian1Gaff** [comment]
There are indeed some strange things that happen sometimes like this when 
nvda is around. I put it all down to there only being one copy of nvda, so 
to speak. Its a similar issue when you cannot get the main nvda menu up on a 
running copy since its left some odd window open you cannot actually get at 
to close. this one goes all the way back to early versions of nvda and seems 
to occur when something in the machines boot up uses a lot of time and 
delays nvda from starting fast. The only option is to reboot nvda, though it 
still mostly works but no internal menus in nvda will work in this 
condition.
 I note you never hear nvda close when this condition is present as it has 
to force it to close rather non elegantly, and a look at the log just shows 
it stop recording at some point.


Not much one can do, thankfully its very rare, normally only if some 
software has done an update and decides to hog the system to configure 
itself during the next restart.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by bhavyashah** [comment]
According to @jcsteh's https://github.com/nvaccess/nvda/issues/2847#issuecomment-316539546, the original issue reported in this ticket no longer occurs, and the buggy behaviour described in @bramd's https://github.com/nvaccess/nvda/issues/2847#issuecomment-316494430 is unrelated to that and already covered by several other cited tickets. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing, as it sounds as if the original issue does not happen anymore.
