### ISSUE TITLE
suggestion for Speak command keys option

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2850]
**Reported by oaron on 2012-12-05 22:00**
When I check the Speak command keys checkbox in the keyboard settings, NVDA announces the arrow keys too. I think it disturbs the users. Is it possible to remove the arrow key announcing, or add a checkbox wherewith the users can be configure it?

**Comment by ehollig** [comment]
I think I tend to agree with @jcsteh in https://github.com/nvaccess/nvda/issues/2850#issuecomment-155303033. Arrow keys are still command keys and this should not be changed. Feel free to reopen if someone disagrees.

**Comment by ruifontes** [comment]
Hello!

Please, see #6553,

Most people, specially new screen readers and new NVDA users coming from 
Jaws, want to hear the command keys, but not arrows...

Rui Fontes

-----Mensagem Original----- 
De: Ethan Holliger
Data: 8 de agosto de 2017 16:20
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] suggestion for Speak command keys option 
(#2850)



I think I tend to agree with @jcsteh in #2850 (comment). Arrow keys are 
still command keys and this should not be changed. Feel free to reopen if 
someone disagrees.

**Comment by derekriemer** [comment]
I think we are ignoring a very significant number of users by ignoring this, and thus should rethink it.

**Comment by leonardder** [comment]
I also agree with @JCSTeh and @ehollig on this matter. Note that JAWS in general has a weird way of handling key echo (e.g. it ties command key echo to the speak characters/words options)

**Comment by ruifontes** [comment]
Hello!

I totally agree with @derekriemer. We need to rethink this one...
As I said in last comment, please see #6553.

1 - We must solve the problem of Enter and accents, since they are typed 
characters;
2 - Most newbies, specially those coming from Jaws, have great complains 
about do not hearing command keys, and it is totally improdutive hearing 
constantly "right arrow", "left arrow", "up arrow" and "down arrow".

Rui




-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 14 de agosto de 2017 15:12
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Don't speak arrow keys when Speak command keys 
option is enabled (#2850)



I also agree with @jcsteh and @ehollig on this matter. Note that JAWS in 
general has a weird way of handling key echo (e.g. it ties command key echo 
to the speak characters/words options)
