### ISSUE TITLE
NVDA recognizes the position bar only in the folders window.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2867]
**Reported by bramhini on 2012-12-12 10:32**
NVDA doesn't recognize the position bar in Adobe Reader or in any webpages.I feel this is important feature for vision impaired people.This feature could help them locating the position bar

**Comment by bhavyashah** [comment]
@jcsteh @feerrenrut Is the bug report/feature request sufficiently clear for you? If not, CC @brian1gaff in case Brian has any information.

**Comment by Brian1Gaff** [comment]
Although I can see I'm on this thread, I don't recall anything about it at 
all.
 I only see my name no actual data.
 However I'm unable to get at all my email due to a problem at Virgin this 
morning!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment]
No, I don't really understand what this is about. It would be fantastic if anyone who did know could update this with the steps to reproduce the problem, as well as the actual and expected output / behaviour from NVDA.

**Comment by Brian1Gaff** [comment]
Could position bar just mean where the screen has scrolled to, ie the old 
chestnut of the screen scrolling to reflect where say all or couursor down 
puts it and then its remembered when you come back again visually?


Since I cannot actually see the screen any more, its immitereal to me but if 
sighted help was needed I know this issue can be a problem as I get, I 
cannot see where you are reading from.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jcsteh** [comment]
This issue does not provide sufficient detail  and we don't have any way to contact the reporter. Closing.
