### ISSUE TITLE
NVDA stops working in windows store

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2881]
**Reported by gopalrohra on 2012-12-21 15:04**
NVDA stops working when in windows store, mail app, calendar app. It only speaks "Store invisible" or "Unknown invisible", similarly in mail app it speaks "Mail invisible" or "Unknown invisible". However it works fine in some other metro apps like youtube etc.

**Comment by ehollig** [comment]
As reported in https://github.com/nvaccess/nvda/issues/2881#issuecomment-155303330, this works as expected for other users. The original poster does not indicate which version of NVDA is being used, or the version of Windows. Due to the age of this ticket, I assume it is Windows 8. Any ideas @josephsl or @bhavyashah

**Comment by ehollig** [comment]
As we are unable to contact the original poster, as far as I am aware, and @jcsteh reports in https://github.com/nvaccess/nvda/issues/2881#issuecomment-155303330 that this works fine for him and other users, closing as worksforme
