### ISSUE TITLE
I am noticing when closing with Alt Plus f4 out of folders that a lot of times NVDA loses focus and sometimes does not continue reading the list box of folders.  This procedure seems to happen on a regular basis.  Here are the steps.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2893]
**Reported by electronicman on 2012-12-23 17:00**
Please refer to description above.  Steps follow:
1.  Open a fo,lder.  Doesn't matter what but be sure it has subfolders.
2.  Open up a sub folder.
3.  Do an Alt plus f4 on the subfolder.
4.  You will find that sometimes NVDA does read the list and sometimes it refuses to read the list view.
5.  I am using Windows 8 with a Toshibe laptop.

**Comment by ehollig** [comment]
Can anyone reproduce using Windows 8.1? CC @bhavyashah

**Comment by bhavyashah** [comment]
The STR provided by the original reporter is slightly unclear to me. Still, following the below steps worked as expected:
* Open a folder (which contains a subfolder) in Windows Explorer.
* Press the Applications key on any subfolder present in that folder and press 'e' to open it in a new window.
* Note: Although reporting the appearance of the folder in a new window does take NVDA several seconds, I suppose that is inevitable.
* Press Alt+F4 to close this window so as to revert back to the original parent folder in the previous window.
NVDA does accurately announce the window title followed by the subfolder name, as is desired.
In case we have different test results with my interpretation of the reporter's STR, or different interpretations of the original STR itself, or any means to contact electronicman himself, we should reconsider this ticket. If not, I would suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing for a couple reasons:

1. Ticket is 5 years old. A lot of NVDA updates have occurred since then.
2. the steps to reproduce is a little unclear. However, performing the steps in https://github.com/nvaccess/nvda/issues/2893#issuecomment-319868189, NVDA does accurately announce the window title followed by the subfolder name.

If this problem still exists, we can reopen this ticket or a new ticket can be created with clear steps to reproduce the issue.
