### ISSUE TITLE
Reconsider presentationType for IAccessible.ContentGenericClient

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2903]
**Reported by jteh on 2012-12-28 22:20**
In some applications (such as Sonar), there are a lot of !ContentGenericClient NVDAObjects. These are always forced to presType_content, which results in a lot of unknowns in simple review.
1. It shouldn't override presType_unavailable.
   - For performance reasons, we may want to check for invisible and unavailable directly, rather than calling super.
2. It might be worth considering making these layout if value is None, though I'm not sure about that.

Mick, thoughts?

**Comment by jcsteh** [comment]
We decided to expose ContentGenericClient as layout if there is no value and it isn't focused.

**Comment by Adriani90** [comment]
@jcsteh, @michaelDCurran could you please give a short update on this? Thank you.

**Comment by jcsteh** [comment]
The decision made concerning the implementation of this issue is explained in https://github.com/nvaccess/nvda/issues/2903#issuecomment-228216197. Having said that, I no longer personally care about this and I was the one driving it, so I'm going to close this. It can always be reopened should someone care in future.
