### ISSUE TITLE
text under the mouse is not being read by paragraph

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2940]
**Reported by surveyor on 2013-01-21 08:49**
Even if text resolution under mouse settings was set as paragraph, text under the mouse can only be read line by line..

**Comment by NavenduSanwal** [comment]
Facing the similar bug for anchor tags which have large text so that it breaks into separate lines. It only reads the first line on mouse hover and ignore the others.

Tested on stackoverflow.com/ for questions which wrap to second line.

Configuration:
- Win7
- Firefox 55.0.3
- NVDA 2017.1
- Mouse tracking enabled and text resolution set to "paragraph"

Are there any workaround?
Breaking links with `<br>` seems to have been working in some cases but can't be applied to dynamic links.

**Comment by feerrenrut** [comment]
Another similar example:
```
data:text/html,<span id="labeltext">some text in a span before an inline button</span><button aria-labelledby="labeltext">Quick brown fox<br>jumps over lazy dog</button>
```
Using Firefox (Version 60.0.2), when moving the mouse over the button, only "jumps over the lazy dog" is read.

**Comment by leonardder** [comment]
@feerrenrut: Note that NVDA reads on the object level. The button is a separate object, so IMO it is sort of expected that it does only read the contents of the button.

**Comment by jcsteh** [comment]
Firefox now supports the paragraph unit as of Firefox 82 (currently in beta): https://bugzilla.mozilla.org/show_bug.cgi?id=1520779

So, if text wraps across two lines, mouse tracking by paragraph (and braille read by paragraph) will now behave as expected. For example, this wraps across two or more lines and gets read as one paragraph:
`data:text/html,<button style="width: 50px; word-break: break-word;">foo bar</button>`

Note, however, that `<br>` is considered to begin a separate paragraph. This is consistent with Chrome, as well as with NVDA browse mode.

**Comment by feerrenrut** [comment]
I think this means we can close this issue. Please let me know if I missed something.
