### ISSUE TITLE
speech recognition input

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2976]
**Reported by zahari_bgr on 2013-02-09 22:02**
Creating of speech recognition input method.
Supporting of different engines, starting with Microsoft Speech Recognition engine, that is included in SAPI.
Introduction of Microsoft Speech Recognition in SAPI5.3 is available here: 
http://msdn.microsoft.com/en-us/magazine/cc163663.aspx

**Comment by dkager** [comment]
@jcsteh Thoughts? Thinking about wontfix because AFAIK speech recognition software can emulate keyboard shortcuts and hence interact with NVDA. But it could be a very nice feature.

**Comment by jcsteh** [comment]
Supporting voice commands is definitely in scope for NVDA. I'd say this is a valid (and potentially useful) feature. However, DictationBridge already supports this for Dragon and might some day support it for Windows Speech Recognition. While DictationBridge is a separate add-on, it's a much more compelling solution because it makes dictation more accessible as well, and duplicating effort here would be pretty wasteful. Closing.

**Comment by derekriemer** [comment]
covered by dictationbridge
