### ISSUE TITLE
Double announcing of desktop icons when alt+tab is pressed.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2988]
**Reported by ateu on 2013-02-12 22:28**
When pressing alt+tab or Windows+m to go to desktop, NVDA announces twice the desktop icons. After this, it speaks correctly.
My system is Windows 7 64 bit.
**Blocking #4275**

**Comment by ehollig** [comment]
This is not an issue on Windows 10. Could someone please test on Windows 7 to see if this is still an issue?

**Comment by Adriani90** [comment]
I cannot reproduce it on Windows 8.1 eather. @ateu can you still reproduce it on Windows 10?

**Comment by lukaszgo1** [comment]
I am not @ATeu but i can still reproduce in on Windows 7 by doing the following:
1. Press Windows to open menu start.
2. Start alt tabbing  to move to the desktop.
3. When desktop would be active window release both keys and observe, that the icon would be announced twice.

**Comment by Adriani90** [comment]
Which NVDA version are you using?

 

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 22:46
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Double announcing of desktop icons when alt+tab is pressed. (#2988)

 

I am not @ATeu <https://github.com/ATeu>  but i can still reproduce in on Windows 7 by doing the following:

1.	Press Windows to open menu start.
2.	Start alt tabbing to move to the desktop.
3.	When desktop would be active window release both keys and observe, that the icon would be announced twice.

**Comment by lukaszgo1** [comment]
NVDA 2018.4 beta 2

**Comment by Adriani90** [comment]
One last question from my side:

If you press alt tab quickly, actually it should report it only once. If you press alt tab but you release the tab key and hold the alt key pressed for short time longer, then NVDA reports it twice. Can you confirm this behavior?

 

If yes, this is actually correct behavior because NVDA reports once when you press alt+tab and hold the alt key pressed to report the current window in the buffer and then when you release the alt key finally NVDA reports the window to which the focus really changed.

 

 

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Mittwoch, 28. November 2018 00:16
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Double announcing of desktop icons when alt+tab is pressed. (#2988)

 

NVDA 2018.4 beta 2

**Comment by lukaszgo1** [comment]
This issue Isn't about reporting window twice, but about repeating a focused icon on the desktop twice after releasing alt+tab.

**Comment by Adriani90** [comment]
Oh sorry I should read more exactly title and description. Sorry, forget my comment above *g*

Von meinem iPhone gesendet

**Comment by lukaszgo1** [comment]
@Adriani90 No problem.
