### ISSUE TITLE
Nvda is muted in the edit field

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3015]
**Reported by Fabi_Omena on 2013-02-22 01:58**
On Field editing application &quot;Message&quot;, NVDA is silent and does not state when the user deletes a letter,Or tries to navigate through typed words or lines.

**Comment by ehollig** [comment]
Does this message app for Facebook still exist on Windows 8.1? CC @bhavyashah

**Comment by bhavyashah** [comment]
I have never been good with Windows 8 Metro/Modern apps and such, but still, searching for 'message' in the Start menu yielded no programs as search results, leading me to believe that this app might no longer exist. @ehollig

**Comment by ehollig** [comment]
According to [Facebook](https://www.facebook.com/help/852837148154446), it looks like the messenger app is only available for Windows 10. As this issue is over 4 years old and I have not heard other issues regarding this reported, we are unable to contact the original poster, and it is discussing Windows 8, closing.
