### ISSUE TITLE
Add JSon module to NVDA distribution

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3050]
**Reported by ragb on 2013-03-05 15:38**
It would be good to add the `json` module to NVDA's bundled python modules to avoid bundling it in every add-on that may need it. Further than communicating with web services, it can be used to store configuration and other data for add-ons (Pickle works too, but json is language-agnostic). From my testing it adds about 40kb to the distribution (probably less when compressed).

I believe it is just a matter of adding the `json` module to setup.py. If agreed I can make the change. If not, it is not a big deal, I can simply bundle the code when needed.

**Comment by leonardder** [comment]
CC @ragb

I'm afraid this change isn't this trivial, you will also have to deal with Py2exe stripping unneeded modules. So you will have to set an exception for this.

Having said that, I belief this would be helpful, since multiple add-ons are using JSON. Furthermore, now there is a recognition framework (#7361), it is easier to integrate web services into NVDA that might make use of JSon.

**Comment by jcsteh** [comment]
Actually, this is fixed by #7361, as UWP OCR depends on json and our builds thus now include it.

**Comment by leonardder** [comment]
Thanks for pointing out. I updated the description of pr #7361 accordingly to let the Github magic close this issue automatically.
