### ISSUE TITLE
Elements with tabindex higher than 0 are pushed to the end of the tab order

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3096]
**Reported by jmkenz on 2013-03-20 13:04**
When NVDA is turned on, elements with tabindex values of 1,2,3, etc. are pushed to the end of the tab order, rather than the beginning. The W3C specs for tabindex say they’ll be pushed to the beginning with those tabindex values, which is certainly what happens when NVDA is de-activated.  For some reason,  NVDA wants to push them to the end.

**Comment by bhavyashah** [comment]
Using Firefox 54 and NVDA 2017.2, I am getting completely different results than those provided in https://github.com/nvaccess/nvda/issues/3096#issuecomment-155305849 with http://webdesign.about.com/od/examples/l/bl_aa071105.htm. Going into focus mode on the first edit field of the page and then Tabbing lands me into advertisements, links, and what not - nothing close to what jmkenz  reported. This may be due to a change in the contents of the sample URL. Thus, unless @jcsteh, @feerrenrut and others suggest otherwise or can provide updated test cases, I suggest closing. @ehollig

**Comment by Adriani90** [comment]
@jmkenzm @jcstehI am not sure if I  can reproduce this issue. Actually when I tab away from search field NVDA says "search", then "computer science" and so on. Is this still the wrong tab order? If I am walking with down arrow in browse mode the order is the same like in focus mode which is actually the right behavior.

**Comment by ehollig** [comment]
CC @jmkenz
I am not able to reproduce this issue either, when performing the steps outlined in https://github.com/nvaccess/nvda/issues/3096#issuecomment-155305849
Closing, unless this is still an issue.
