### ISSUE TITLE
Reading in Word 2010 directly after opening a file

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3098]
**Reported by falinn.onda on 2013-03-21 11:01**
Each time i open a word file, the document is opened but NVDA only says the title and does not respond to navigation with arrows (nothing is read).
If i use NVDA+up it says "blank".
after i change the focus to a different window and then back to the document it starts reading correctly from that point on.

My configuration is win7 with office 2010 pro and NVDA 2012.3.1.

**Comment by bhavyashah** [comment]
@michaelDCurran In short, no, the reported issue is not specific to protected documents. Not only does the original author of this ticket indicate this in https://github.com/nvaccess/nvda/issues/3098#issuecomment-155305857, but I can also replicate this successfully from time to time. I may need to more consciously investigate this in order to be able to provide a consistent and reliable STR, but in the meantime, is there any other diagnostic information required from me and others to assess this ticket?

**Comment by Adriani90** [comment]
The focus tracking is not reliable in many cases. This is already covered in #8389. Closing this in favor of that issue because the discussion is more detailed in that issue.
