### ISSUE TITLE
inconsistent beeping on capitals when "speak cap for capitals" and "beep for capitals" both are turned on

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#310]
**Reported by aleksey_s on 2009-05-01 13:36**
## actual results

NVDA beeps on "cap" part of message, not on the letter itself.
## expected results

NVDA must beep when the actual letter is exactly speaking.
## Additional info

Split the message to "cap" and "actual character" isn't the solution, because it sounds bad for me. I assume this can be done only with custom indexing, which require redesign of nvda synth driver api. However, i am even not sure that it can be supported by all synthesizers, which nvda currently supports.
So perhaps this ticket is not for fixing, but for reporting inconvenience which can be noted in documentation.

**Comment by leonardder** [comment]
I assume this will be fixed in #4877

**Comment by fisher729** [comment]
Hi.

Should this issue still be open @Adriani90

**Comment by Adriani90** [comment]
This is still inconsistent in NVDA alpha 20045,a335297e. The speech refactoring might have made it possible to fix this, but there is no fix for this via speech refactoring yet.

**Comment by fisher729** [comment]
Hi.
Well, I'm using the latest stable, and I don't face this issue using
either eSpeak or OneCore voices

**Comment by CyrilleB79** [comment]
Hello

Since I have already worked recently on this part of the code (#11977), I may work on this ticket if it is really a need.
But is there anybody wanting to have this ticket resolved and how?

Now that #11977 has been merged, the "cap " message and the character are actually split one from another.

The original reporter (aleksey_s, probably Aleksey Sadovoy) indicates that:
> Split the message to "cap" and "actual character" isn't the solution, because it sounds bad for me.

If anyone understands this comment please give more explanations. Also if someone still has contact with Aleksey S, please Cc him; but it seems he is not active anymore in NVDA community.

If the solution is to add the beep just before the character and not just before the "cap ", I may implement it.
But again I do not know if someone really needs this.

If no one express a need for this, I rather vote to close this ticket.

**Comment by CyrilleB79** [comment]
Since my last comment did not cause any reaction after 3 yers, I am closing this issue.

@Adriani90, @fisher729, @LeonarddeR or others, if you wish this issue to be implemented, please provide the reason and we can reopen. Or better, open a brand new ticket.
