### ISSUE TITLE
NVDA won't work with my RefreshaBraille 18.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3109]
**Reported by santiagoblue7 on 2013-03-26 04:50**
Hello,
I recieved a RefreshaBraille 18 from APH today, and it seems to work fine with all of my devices, running different screen readers, like VoiceOver for OS X, VoiceOver on iOS, and System Access on Windows. When I tried to use it with NVDA, I recieved an error, even though I was choosing the right option, an APH display. Others have told me the display is not working with NVDA, however, I heard it did. Is this a new issue with a recent copy of NVDA, and, is a fix on the way? Thanks in advance,
Santiago

**Comment by bhavyashah** [comment]
Since the original author of this ticket is now out-of-reach and unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/3109#issuecomment-155305927 and the two subsequent comments, we remain with information insufficient for diagnosis. Unless we are in touch with a user of said Braille display who can confirm the reported issue, I suggest closing. @ehollig

**Comment by leonardder** [comment]
I agree. Closing as invalid.
