### ISSUE TITLE
Over time, NVDA lags with firefox open

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3138]
**Reported by tspivey on 2013-04-07 16:21**
If I leave firefox open for a long time (can be hours to days), NVDA starts to respond slowly. I notice while alt+tabbing and moving around lists in tween.
When I restart firefox, this stops for another few hours.

**Comment by jcsteh** [comment]
We can probably improve this significantly by cleaning up the isAlive property on the gecko_ia2 vbuf. Right now, it calls `NVDAObjects.IAccessible.getNVDAObjectFromEvent`, which is a complete waste. As a minimum, we could just check for the defunct state. Even calling `accChild` directly would be better than calling `NVDAObjectFromEvent`.

P2 because this can make NVDA sluggish for users with a lot of tabs.
