### ISSUE TITLE
When "Braille tethered to" option is set to review, it's not possible to move the caret when you press routing buttons on braille display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3166]
**Reported by sergioneves on 2013-04-17 15:15**
I'm using NVDA (last development version) and Focus 40 braille display.
Steps to reproduce:
1. Go to NVDA menu -> Preferences -> Braille settings.
2. Access the combo box labelled "Braille tethered to", change the selected option to "review" and press ok to save.
3. Open a text editor, like notepad.
4. Write some text and try to press the routing buttons on the braille display, in order to move the caret to the character you want.
Expected result: both the caret and the braille cursor move to the character you want.
Actual result: only the braille cursor moves to the character; the caret remains in the position it was before.

Note that when the option "Braille tethered to" is set to focus, the problem doesn't happen.
I think it's important to have the content of the braille display updated as you move the flat review cursor, without losing the possibility of using the routing buttons to change the caret position.

**Comment by heikofolkerts** [comment]
After reading all this comments and that of the referenced ticket I think the key points are in #6 and #7. Ofcourse we shouldn't risk blocking braille only users so using routing keys should be switchable from just moving the review cursor or moving it and performing a click on that position afterwards. I mean a click with the mouse since this way the routing keys can be used for moving just the review dursor as stated in #7, place the caret to edit text (which is the most used situation) and just click a button or whatever to activate controls etc. Even if this kind of click is hard in screen review mode it would be helpful in object navigation alone.

So what I request ist just
* create an option (with a hotkey if possible) to decide whether the routing key should trigger the mouse to be moved to the new position of the review cursor and perform a click or just behave as in the current version.
* enhance the responsible script that handles the movement of the review cursor to move and click the mouse.

I think this little confusion or specific behaviour makes it quite strange and hard for beginners and it is error prone to advanced ones because one forgets to switch cursors and realizes it when wrong edits are made.

**Comment by Adriani90** [comment]
@leonardder, @michaelDCurran unfortunately I do not have a braille display to test this but I guess this is still an issue even with automatic tetering. Right?

**Comment by Adriani90** [comment]
@jcsteh I guess the discussion was not been further expanded an NV Access. Right?
@sergioneves please test it if possible with automatic tetering and tell us if this issue still occurs.

**Comment by jcsteh** [comment]
I can't comment with certainty as to NV Access's plans or opinions concerning development, since I'm not a developer there any more. :) As far as I know, there hasn't been any further discussion on this.

**Comment by leonardder** [comment]
I'm also not able to speak on behalf of NV Access, but personally I believe that this is not a bug. @jcsteh has explained this in https://github.com/nvaccess/nvda/issues/3166#issuecomment-155306326 . I would say that especially now auto tethering is there, the only thing we can consider is changing the action of the routing buttons when tethering is set to auto, while it it is temporarily tethered to review (e.g. because of a review move). However, when braille is tethered to review explicitly, behaviour should stay as is.

**Comment by Adriani90** [comment]
@leonardder this sounds reasonable. I think if system carret follows review cursor in edit fields, then it should work properly. As of now, review cursor follows system carret but not vice versa. This could be an optional setting in braille settings because for speech this is not very important I guess.
