### ISSUE TITLE
NVDA is not passing the Escape key in ARIA menus

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3215]
**Reported by dfarough on 2013-05-10 15:32**
Can NVDA pass the handling of escape key presses to the widgit for ARIA menus?  See http://www.w3.org/TR/wai-aria-practices/#menu
for info

**Comment by jcsteh** [comment]
This is quite annoying when working with ARIA menus, autocompletes, etc.

[Test case (rename to .html)](https://github.com/nvaccess/nvda/files/1110668/fakeAutocomplete.html.txt)

STR:

1. Open the test case.
2. In browse mode, move the cursor to the edit field and press enter. Observe that NVDA switches to focus mode.
3. Press down arrow. Observe that NVDA reports "Some item".
4. Press escape.
    * Expected: NVDA should remain in focus mode and report the edit field, since it got focus.
    * Actual: NVDA switches to browse mode. The menu item remains focused.

P2 because this can be very confusing when trying to work with ARIA autocompletes and menus. Some users may not understand what's happening and thus not be able to figure out how to work around it.
