### ISSUE TITLE
Associating header and data cells in a complex table using headers-id attribute

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3244]
**Reported by spanchang02 on 2013-05-21 20:52**
Implementing support for headers-id method of associating header and data cells for complex tables is necessary to make them accessible with NVDA.
Example file at:
http://mars.dequecloud.com/demo/Census_2013.htm
Note:
The second table on this page is the same as the first marked up differently so that headers-id markup is not needed. 
It uses NVDA's feature of reading cells in multiple columns marked up as TH.  The h3 markup for group-row-headers also enhances table comprehension and navigation.

Yet, more complex tables rely on headers-id markup only.
Thanks,
Sailesh

**Comment by bhavyashah** [comment]
@jcsteh's https://github.com/nvaccess/nvda/issues/3244#issuecomment-155307302 states that the reported issue has been fixed for Firefox 24, and thus the remaining work needs to be done internally in NVDA for Internet Explorer only. Could someone please check if this still occurs in Internet Explorer 11 as well? This is because if not, we may safely close this ticket given that we are no longer addressing issues specific to older versions of IE.

**Comment by michaelDCurran** [comment]
We did not make any effort to address this in Internet Explorer 11. Again like with other Internet Explorer issues, we'll accept a PR, but we are not placing priority on these.

**Comment by Adriani90** [comment]
@jcsteh is this still an issue in Firefox?@leonardder I guess many organisations still use IE and I am thinking of SAP netviewer where you have very complex tables. Do you think there is any Chance that maybe you at Babbage look into this?

**Comment by Adriani90** [comment]
If this is not an issue in Firefox anymore, I suggest to close it because IE will probably not get and enhancements from NVDA's side sofar.
