### ISSUE TITLE
safe mode with nvda

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3271]
**Reported by Animesh.mr on 2013-06-08 12:54**
hi all accessing safe mode for blinds is an opstical for blind so hear is the solve by activating sound in safe mode wee can use n v d a 
attached file can make this work 
**Blocking #3855**

**Comment by ehollig** [comment]
@feerrenrut can you restore the attachment? this looks like an interesting hack, if someone may need to use safe mode on the computer for one reason or another. I agree this should not be included as apart of the main installation though, and should be available as a separate download if it indeed does work as advertised.

**Comment by feerrenrut** [comment]
Added attachment to https://github.com/nvaccess/nvda/issues/3271#issuecomment-155307544

**Comment by Adriani90** [comment]
NVDA works in safe mode in Windows 10 and 11 when you start safe mode with network enabled.
1. Press Windows+r
2. Type "msconfig" and press enter
3. Under the start tab, choose "start in safe mode"
4. Press tab and choose the radio button "network"
5. Press ok and reboot your pc.
6. After that you can start either NVDA or Narator in safe mode.

Since support for Windows 8.1 has ended in january 2023, I am not expecting any further accessibility updates to that Windows version.
So closing this issue as works for me.
