### ISSUE TITLE
Reporting deletes when done using CTRL+DELETE

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3298]
**Reported by falinn.onda on 2013-06-21 06:08**
Hi,
When editing text, i find it really useful to use CTRL+DELETE to delete the word at the cursor location.
This is more intuitive than CTRL+BACKSPACE since NVDA announces the word following the cursor (and not the word before), .

When using CTRL+BACKSPACE i get vocal feedback that the word was deleted but unfortunately this feedback is missing when using CTRL+DELETE.
If possible to add the same vocal notification for CTRL+DELETE it will be great...

**Comment by bhavyashah** [comment]
Confirmed. To summarize:
* Backspace erases the character at the left of the system caret and NVDA reports the erased character.
* Delete erases the character at the right of the system caret and NVDA reports the character to the immediate right of the deleted character.
* Ctrl+Backspace deletes the word at the left of the system caret and NVDA reports the erased word.
* However, the bug is that when Ctrl+Delete is pressed, and it erases the word to the right of the system caret, NVDA remains silent. A user would ideally expect to hear the word present at the immediate right of the deleted word when Ctrl+Delete is pressed for consistency as well as functionality.

**Comment by Adriani90** [comment]
this is duplicate of #11029. Closing in favor of that issue which ontains a bit more discussion and the template is filled accordingly.
