### ISSUE TITLE
Occasional character, word and line skips in Adobe Digital Editions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3299]
**Reported by erion on 2013-06-22 11:45**
When using the arrow keys in the book content buffer, NVDA sometimes skips characters, words or lines completely, repeating the previously read instance.
As a result, reading the word 'you' by character results in 'y, o, o'.
It does not happen all the time, but frequently enough to cause discomfort.
This issue is not OS specific.

**Comment by bhavyashah** [comment]
Since the original author of this ticket is now out-of-reach and unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/3299#issuecomment-155307774, coupled with the fact that Adobe Digital Editions isn't being worked on too actively by Adobe (is the impression I am under), I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as we are unable to easily contact the original poster and they did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/3299#issuecomment-155307774
