### ISSUE TITLE
SCR reads title on input field twice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3319]
**Reported by tutej on 2013-07-01 15:04**
Hello,
I'm developing my webpage and there was a problem with NVDA. I've added a title attrribute for input field, and if there is any data inside the input field, NVDA read title twice. How can i solve it?
I can not any label for it due to leyout(tried to use headers insted - didn't worked in I.E. 8.0 the have to be supported, in FF. 20 it worked propoerly)

P.s. sorry for my english

**Comment by bhavyashah** [comment]
If this bug turns out to be specific to Internet Explorer 8, then we can safely close this ticket since we are not addressing IE 8 issues anymore. Regardless, to ascertain that in the first place, @jcsteh, could you please take a look at the diagnostic information and test case provided in https://github.com/nvaccess/nvda/issues/3319#issuecomment-155307929 upon your request?

**Comment by Brian1Gaff** [comment]
In fact nvda has a history of saying things several times. It still does it 
on some programs and in some situations, but unless somebody has time to 
spare trying to zap them all might be a bit of a challenge.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@tutej is this still an issue for you?

**Comment by Adriani90** [comment]
I am closing this issue since I guess the request is outdated and IE8 is not really supported anymore.
