### ISSUE TITLE
IE 9: NVDA Stops On Something Other Than Form Fields When I Press F

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3352]
**Reported by jhomme on 2013-07-10 14:44**
Hi,
Use Internet Explorer 9 with Windows 7. 

The About box of my NVDA says 2013.1, although I updated it once since I got this version.

Go to http://en.wikipedia.org.

Go to the top of the page.

Start to press the letter f to jump to form fields.

NVDA stops on other items besides form fields on this page for some reason.

**Comment by bhavyashah** [comment]
Is this specific to version 9 of Internet Explorer or does this bug persist with more recent versions of IE as well? If it is specific to IE9, I would suggest closing this as WontFix, but if this issue is applicable to IE 11, I would suggest assigning this ticket a low priority. If the scope of this ticket includes other modern browsers however, we might want to give it more serious consideration.

**Comment by ehollig** [comment]
Just tested this by going to https://en.wikipedia.org/ in Firefox, Chrome, IE 11, and Edge. When I press F, NVDA appropriately moves to the form fields on the page. Closing as worksforme
