### ISSUE TITLE
IE script error on help balloons

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3362]
**Reported by mcronq on 2013-07-12 17:18**
Using IE 10.

Whenever a password field tries to present the help balloon "Caps Lock is on" an IE script error popup appears and is difficult to navigate past.

This problem can even be viewed by turning on NVDA and going to http://community.nvda-project.org/login turning on caps lock and tabbing into the password field and trying to enter a password.

**Comment by bhavyashah** [comment]
According to @michaelDCurran's https://github.com/nvaccess/nvda/issues/3362#issuecomment-155308284, this issue seems to have a very high implementation cost. If my inference is indeed correct, and since this seems to be IE specific, addressing this may not be worthwhile. Thus, I suggest closing. @ehollig

**Comment by ehollig** [comment]
As we no longer can contact the original author of this issue, and we have not had a reported issue like this in a very long time, I am going to close this issue.
