### ISSUE TITLE
nvda can not navigate by character in formfields when internet explorer is first loaded

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3384]
**Reported by mreiser on 2013-07-28 03:43**
For some reason, nvda isn't able to navigate in a form edit field when I first start the desktop version of Internet Explorer10.  To reproduce this, do the following.  
1.  Set your homepage to www.google.com
2.  Press E to go to the searchbox and press enter to go into focus mode.  
3.  Type something like test search and then try left arrowing over what you just typed.  

Expected: nvda should speak the characters typed.  

Actual: blank is spoken.  Also if I go to www.binsearch.info and try typing into the search box, the same thing happens.  However if I manually go to google.com, nvda behaves normally.  I switched back to 2013.1.1, and the same thing happened on google initially, but nvda behaved normally on all other sites.  I'm currently running the master branch.

**Comment by bhavyashah** [comment]
I cannot reproduce this with Internet Explorer 11 on Windows 8.1. My homepage on IE is MSN, and typing and editing in an edit field present on the website worked as expected. Since this issue is over four years old, it is possible that these issues were being caused by Google Instant, the original author of this ticket is now out-of-reach, and the demise of Internet Explorer, I suggest closing. @ehollig

**Comment by Brian1Gaff** [comment]
Unless I'm mistaken this was fixed at least two years ago by some extra 
coding as different forms of edit areas used on the web upset things.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
I can not reproduce using IE 11 either. Closing as worksforme
