### ISSUE TITLE
nvda update hangs if other apps are open

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3386]
**Reported by mreiser on 2013-07-30 16:44**
If you go to install an update with IE or any other app open, nvda will hang at the downloading update screen.  It will download the update and not install it.  Closing all apps and retrying doesn't fix the issue, only a reboot does.

**Comment by bhavyashah** [comment]
The original reporter is now out-of-reach, seems not to have experienced this issue again because no corresponding log has been attached as promised in https://github.com/nvaccess/nvda/issues/3386#issuecomment-155308457, and no one else seems to be able to replicate this. Thus, I suggest closing. @ehollig

**Comment by Brian1Gaff** [comment]
No not seen this at all. Sometimes an update to a portable version screen 
gets lost in the alt tab ring, but this in fact can happen to other software 
so suspect the problem is in Windows.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
Closing, as the reported issue does not occur anymore and no one, not even the original poster, can replicate it.
