### ISSUE TITLE
When focus and browse mode are in speak  rather than sound, you do not always hear the mode spoken on the change

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3447]
**Reported by briang1 on 2013-08-17 08:12**
When navigating any form which has edit areas, I often find nvda says blank and not focus mode when you are in the edit area. Its intermittent and couldbe due to different lags due to page complexity or whatever. Its been happening  for several versions of nvda, but seems more  likely  just recently, even happening on the search field of startpage.com at times.

I think it may not occur on faster machines as much though. It affects both ie8 and firefox in different ways. IE more complex pages affect firefox more, but IE is generally slower overall. Is there any way that buffering of the text could always ensure the mode change is not  removed before its spoken?

**Comment by bhavyashah** [comment]
@brian1gaff Does this still occur at your end?

**Comment by Brian1Gaff** [comment]
Yes sometimes it does. I think the spoken word focus  or whatever is cut by 
the following spoken string. Ie more and more we are finding edit areas on 
the web had text in them that explain what  they are after etc, so this is 
what does it. In this case its better to use the sound of course as this 
always works. It occurred to me the other day that the obvious way around 
this is to merely have a spoken word as the sound. Obviously you would then 
have synth  and language issues, but if the  new feature to alter the sounds 
is implemented, then people could do this themselves.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@Brendon22, @Brian1Gaff this might also be an issue related to soundcard which might go in standby after two seconds or so. Do you encounter this issue also with other words? let's say when navigating by headings in browse mode or so?

**Comment by Adriani90** [comment]
We do not hhave an update from the initial author since two years. @Brian1Gaff if you are still having this issue, please comment on it. Are you seeing this issue also with other words (i.e. quick navigation in browsers)?
For now I am closing this one as works for me because I cannot reproduce it and I didn't hear any other user reports about this specific issue. I guess it is related to the sound card which switches to standby every few seconds. This can be solved by installing the addon audio bluetooth. An issue related to the sound card behavior is already on Github.
