### ISSUE TITLE
Calling nvdacontrollerclient32.dll freezes NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3450]
**Reported by grego on 2013-08-19 04:55**
In my talking map application I'm extensively using nvdacontrollerclient32.dll to generate speaking messages for users. Nearly each user move is announced by speaking message so it can be thousands of calls per hour.
Everything works very well, but sometimes Nvda freezes, and no speech is generated since it happens until restarting NVDA.
I wrote a test program which generated 10 thousands of messages one by one, but it didn't crash the NVDA. Problem is hard to reproduce (there is no any known batch of things to do for generate this error), but it happens nearly always, after less than an hour... I tried to downgrade Nvda to last version 2012.3, but the problem existed there too.
Operating system is Win7 64 bit, and my application which uses NvdaControllerClient is 32-bit.

**Comment by bhavyashah** [comment]
CC @jcsteh

**Comment by Adriani90** [comment]
@grego is this still an issue for you?

**Comment by Adriani90** [comment]
We do not have an update from the initial author since more than 5 years. Unfortunately we are relying on tests from the initial author because this issue is very specific and cannot be reproduced reliably. I am closing this for now, but feel free to comment on it if you can reproduce it. We can reopen the discussion afterwards.
