### ISSUE TITLE
New braille table in gui (no-no-generic.cbt)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3470]
**Reported by stenevik on 2013-08-25 18:51**
I'm unable to select the table "no-no-generic.ctb" from the gui. Can you add it with the label "Norwegian unofficial computer braille table"?

**Comment by ehollig** [comment]
@jcsteh, is this already in NVDA? I see 5 types of Norwegian Braille available in the Braille settings.
Norwegian 8 dot computer braille
Norwegian grade 0
Norwegian grade 1
Norwegian grade 2
Norwegian grade 3

**Comment by leonardder** [comment]
If I may answer, the answer is no :)

**Comment by leonardder** [comment]
I'm afraid we can't contact the original author of this issue.

@DeamonDavid: Do you still think there is a desire for this table to be in NVDA?

**Comment by stenevik** [comment]
I am the original reproter of this issue. There is still a desire for this table in nvda.
This table is totally different from the official/modern table (no-no-comp8.tbl). The only thing they have in common is a-z, A-Z and a few special characters.
Numbers and characters like +, /, \, <>, [], {}, ;, !, ", %, and $ are completely different.
If no-no-generic.tbl is added with the correct description I don't think Norwegian users will pick the wrong tbale.

**Comment by zstanecic** [comment]
To the original reporter: is this table a separate norwegian standard?

can you tell mre?

**Comment by stenevik** [comment]
Before the official Norwegian 8 dot braille standard came in 2004 we got two alternatives:
The first one was the table which the standard is based on.
The second one was an enhancement of the German table. This tables was mostly used by owners of German braille displays.
Since the official standard was released most users changed to the official table, but some users are still using the "no-no-generic"-version.

An alternative solutin: Could you allow users to choose between all the available table-files from the gui by adding a "Show all braille tables"-option?

**Comment by Adriani90** [comment]
cc: @Andre9642

**Comment by Andre9642** [comment]
I notice that this table has no mapping for space. Is it really a table usable in standalone?

```
>>> louis.translate(["louis/tables/no-no-generic.ctb"], "a b")
("a'\\x0020'b", [0, 1, 1, 1, 1, 1, 1, 1, 1, 2], [0, 1, 9], 0)
```

However, in my opinion, we should encourage to use the official braille tables only.

**Comment by Adriani90** [comment]
I agree with @aaclause in this case. We should rather improve official braille tables if possible instead of adding alot of noise with unofficial tables. If you have problems with the official tables, please also raise issues with Liblouis.

I am closing this as won't fix. If you still have strong arguments in favor of the unofficial braille tables, please comment with some updates of the current situation and we can reopen this issue.
