### ISSUE TITLE
Links are no longer activable in E-Mails displayed using Outlook Express and other e-Mail clients

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3483]
**Reported by BachirBenanou on 2013-08-30 11:15**
Hello, Devs,
When a message is open in Outlook Express 6 for Xp, the links it may contain are no longer clickable using the space bar or the enter key.
Using insert+f7 to display the elements list does bring these up, but hitting the "Activate button" does not click the links as it as appropriate.
Other users also report this to happen using Windows Live Mail under Windows 7.
As this used to work before NVDA 2013.2, I think this tobe very important to fix. Thank you.

**Comment by leonardder** [comment]
It is very unlikely that this will ever be tracked down. Furthermore, Windows Live Mail and Outlook Express are both abandoned, closing as wontfix.

**Comment by Brian1Gaff** [comment]
I feel you are being draconian again.

Remember there are a lot of people still using these programs around the 
world. I've not seen this issue though unless its just new today.the issues 
may well be that many email software now has its own code for displaying and 
handling html. this is certainly how Outlook express new developments by 
third parties works. I'm using it now on windows 7 and could not do what I 
do without this software as no email client offers me the same group of 
features.
 So just because its not being actively developed by the original people, it 
does not mean its not still in use and should be supported.


Brian a great supporter of if it works then use it.
Brian

**Comment by dkager** [comment]
As several comments stated, this problem was hard to reproduce. It boiled down to an encoding issue, though the conversation comes to a halt after that observation.

While not being able to activate links is serious enough, I think @leonardder is saying that it will likely not be fixed for applications considered discontinued.
