### ISSUE TITLE
When using arrow keys to move through a spreadsheet in Libreoffice Calc, NVDA reads too much information.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3498]
**Reported by dgoldfield on 2013-09-04 15:12**
when navigating through a spreadsheet using arrow keys in Libreoffice Calc 4.1.1 with accessibility support enabled, NVDA 2013.2 reads much more than the cell data and coordinates, after data is entered in a cell.

steps to duplicate
1.  In document Settings dialog, enable the speaking of cell coordinates.
2.  Open Libreoffice calc.
3.  Use arrow keys to move through the blank spreadsheet.  So far, you will receive normal feedback as NVDA reads off cell coordinates, such as a1, b1, c1, etc.
4.  Next, enter data into a cell.
5.  After data is entered in a cell, use arrow keys to move through the cells.  Instead of hearing the cell coordinates and data which may be contained within the cell, you will hear NVDA read the title of the workbook, the phrase formula bar and reminding you that you can edit data in this cell.

This behavior does not occur with Openoffice or Excel.

**Comment by zahra21** [comment]
hello.
i had this problem since libreoffice 5.2
it seems that its resolved in 5.3.4, but i am not sure completely.
do you mean that the problem occures in all versions of libreoffice and the only solution is desabling formula?
now, i tested with version 5.3.4 and it worked for me without reading extra informations both with formula checked and unchecked.
i appreciate your help, for the solution that works for me,
God bless you all and his infinite mercy i pray for you.

**Comment by ehollig** [comment]
Closing as worksforme with the latest version of libreoffice 5.3.4 from https://github.com/nvaccess/nvda/issues/3498#issuecomment-343510486
