### ISSUE TITLE
Touch-based object navigation: next/previous object should move by controls, not by deepest object

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3514]
**Reported by nvdakor on 2013-09-10 16:56**
Hi,
Under current implementation, previous and next object touch gestures (left/right one finger flick under object mode) moves between objects of different hierarchy. Specifically, it moves to the deepest level of objects no matter what they are (for instance, if a checkbox is in focus, next and previous object gestures move from checkbox to the text of the control instead of moving to the next control). This is more noticeable in Windows Store apps such as news and weather (for instance, in weather app, instead of moving to next day forecast, current one finger flick gestures moves between weather information, the text of this information, to the next day forecast and so on).
Although this behavior is likely due to new review modes feature, in most cases a user would want to move to next or previous control rather than deepest object at hand. The current approach may be useful for documents or virtual cursor documents where one would need to review a text box such as page content. Thus I'd like to propose that the next/previous object gesture (one finger flicks) be modified to recognize when one should move by controls instead of moving by deepest object.
For reference:
To reproduce this:
1. Use a touchscreen device running Windows 8.0 or later with NvDA 2013.2 installed.
2. Open start screen.
3. Use one finger flick left and right to move among objects.
Expected: NvDA should move by tiles.
Actual: NVDA announces tile's name, tile text and any other information instead of moving to the next tile.
This can be reproduced in the following apps/situations:
- Windows 8.0/8.1 start screen (particularly with tiles view).
- Windows Store apps such as weather, mail, etc.
- PC Settings (Windows Store version of Control Panel; this one has another issue which will be filed as a separate ticket).
  Thanks.
  Also, when testing this, could we have access to try builds for this ticket and any other touchscreen-related tickets so others with touchscreens can give feedback? Thanks.

**Comment by bhavyashah** [comment]
Since I am not a Touch Screen user, I may have misinterpreted the requested behavioural change, but let me share my interpretation all the same to ensure that everyone is on the same page. Currently, the left and right flicks move the user between levels of the object hierarchy, whereas one would normally expect to move between the previous and next objects at the same level. This expectation can be derived from the way an object hierarchy can be visualized along with the manner in which object navigation keystrokes for the Desktop and laptop layout utilize the NumPad or arrow keys. If this understanding is not flawed, then this ticket is requesting a change rather than suggesting a feature or reporting a bug, and this ticket may thus need to be triaged accordingly. CC @josephsl (original author of ticket)

**Comment by josephsl** [comment]
Hi, one way to look at this is thinking about how Narrator’s next/previous item commands work. Currently Narrator doesn’t care the hierarchy of an object, but ideally, it should move by controls. Same thing applies in NVDA when moving via touch gestures. I think a much better way would be a toggle instead so people can experiment with this, as well as to account for the fact that it is desirable to use current behavior in certain apps. Thanks.

**Comment by josephsl** [comment]
Hi,

2024 update: in the end, I think the current behavior of moving through objects regardless of hierarchy might be better than usig role-based object navigation and detection (after all, the overall purpose of touch support is letting people review, navigate, and interact with elements on screen regardless of hierarchy since all elements on screen will be navigable in a flat way). One can achieve control-based object navigation by doing two-finger flick left and right in object mode.

Closing for now (as abandoned), thanks.
