### ISSUE TITLE
Column's Skip from table when there is no value

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3515]
**Reported by jagadeesh on 2013-09-11 05:38**
We have one bug that is affecting the PDFs while using NVDA. When the table contain multiple lines and some of the columns are blank, the columns “disappear” and the number of columns in that row are reduced. For example if we are having 5 columns in a table and if the 4th column value is empty then in NVDA it is reading column 5 as column 4 as there is no value in column 4.
  The number of columns should stay the same for all rows regardless of blank columns, so that the table navigation commands can be used.  Please

**Comment by ehollig** [comment]
When I open the [attached document](https://github.com/nvaccess/nvda/files/1236491/NVDA.column.issue.sample.form.pdf.zip), (remove the .zip extension), I am not able to locate an empty cell in columns 4 or 5. The only blank areas are between rows 2, 3, and 4 in column 4, 5, and 6.
As we are no longer able to contact the original poster for more clarification, I am closing this as worksforme

**Comment by feerrenrut** [comment]
The attachment has no values in the "Quantity", "unit price", or "extended price" columns (4, 5, 6) for rows 2, 3, and 4. When pressing `down arrow` in NVDA to move through the table, this blank area is skipped. When using `ctrl+alt+right arrow` to move through the row, from the "Service Description" column nvda reads "edge of table".

I think this is where the confusion comes from with the initial issue description. The table in this document is malformed.

The impact of this is mitigated (at least in recent releases of NVDA) since the row number is reported when it changes. I don't propose this issue is reopened, however I am happy to hear other's opinions.
