### ISSUE TITLE
NVDA throwing errors in Tortoise SVN

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3534]
**Reported by leonarddr on 2013-09-18 09:25**
When checking out an SVN-repo with Tortoise SVN, NVDA throws errors in the list view of the checkout dialog. I could also reproduce it in the update dialog list view. It only seems to occur in master and next, not in 2013.2.

> ERROR - eventHandler.executeEvent (11:23:21):
> 
> error executing event: gainFocus on <NVDAObjects.IAccessible.sysListView32.ListItem object at 0x04DBA1D0> with extra args of {}
> 
> Traceback (most recent call last):
> 
> File "eventHandler.pyc", line 136, in executeEvent
> File "eventHandler.pyc", line 84, in **init**
> File "eventHandler.pyc", line 91, in next
> File "NVDAObjects__init__.pyc", line 834, in event_gainFocus
> File "NVDAObjects\behaviors.pyc", line 458, in reportFocus
> File "NVDAObjects__init__.pyc", line 778, in reportFocus
> File "speech.pyc", line 317, in speakObject
> File "speech.pyc", line 235, in speakObjectProperties
> File "baseObject.pyc", line 34, in **get**
> File "baseObject.pyc", line 110, in _getPropertyViaCache
> File "NVDAObjects\IAccessible\sysListView32.pyc", line 368, in _get_name
> File "NVDAObjects\IAccessible\sysListView32.pyc", line 332, in _getColumnContent
> File "NVDAObjects\IAccessible\sysListView32.pyc", line 324, in _getColumnContentRaw
> File "winKernel.pyc", line 102, in readProcessMemory
> ArgumentError: argument 2: <type 'exceptions.OverflowError'>: long int too long to convert
> 
> IO - speech.speak (11:23:21):
> 
> Speaking [u'selected']

**Blocked by #3339**

**Comment by bhavyashah** [comment]
@leonardder Since @jcsteh's https://github.com/nvaccess/nvda/issues/3534#issuecomment-155309629 seems to suggest that the reported issue has more to do with NVDA's inability to process 64 bit memory rather than being specific to Tortoise SVN, do you think we should remove the app specific label and morph this ticket so as to broaden its scope and reflect the larger picture? Also, before all that, it might be useful to briefly update us about NVDA's current handling of 64 bit memory, test for the presence of the reported errors in Tortoise SVN, etc.

**Comment by leonardder** [comment]
I think it's ok to leave this app specific, since we have #3339 which actually seems to describe the cause of this problem. We can consider closing this ticket in favour of #3339 as well.

**Comment by bhavyashah** [comment]
Agreed. Since this ticket is a specific case of #3339, let us close this ticket in favour of #3339  so as to consolidate further discussion and development.
