### ISSUE TITLE
log viewer doesn't respect large fonts

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#356]
**Reported by timeless on 2009-07-03 09:24**
w7 rc; NVDA 0.6p3.2;
dpi set to "medium", 125% of normal (120dpi)

open NVDA's Log viewer
open notepad, compare the text size

expected results:
Log area should follow standard sizing

actual results:
titlebar+menubar respect settings, but text area does not.

**Comment by feerrenrut** [comment]
This issue was fixed in wxWidgets 2.9.
I tested this out, again it looks like it is fixed now.

- Using Windows 10
- with the "customise your display" and set "change the size of text, apps and other items" to 125%
- I compared the font in the log viewer to notepad.
 - It seems the default font is different.
 - By using NVDA+F in the log viewer I found that the font used there was Segoe UI (Regular), Size 9.
- When setting the same font in notepad, the sizes match.
