### ISSUE TITLE
Incorrect headers-id associations in tables

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3600]
**Reported by kennpetri on 2013-10-22 21:07**
NVDA incorrectly voices header-id associations in tables.

An example complex table is on this page: http://html.cita.illinois.edu/nav/dtable/dtable-example-complex.php

Throughout NVDA makes improper header to data cell associations. 

As an example, the last cell in the table has text of "9/7/2005." That data cell is associated through the headers attribute with "Approval" and "Date" header cells. NVDA reads the cell as "Approval 9/7/2005." It leaves out the Date header, though the headers for both Approval and Date are properly associated.

If I move back to the "Date" header cell, NVDA reads "Approval, Unit Cost, Items, Supplier Information, Requester Information, Date." The Date header cell has no headers attribute and other headers in the table are in no other way associated with the Date header cell. It appears that NVDA is reading all previous header cells that might align with the Date cell's column, moving up the table column from the Date header cell.

There are other similar issues experienced when navigating this table, either linearly or via the Ctrl + Alt table navigation keys. The table itself is correctly coded, however.

**Comment by bhavyashah** [comment]
As noted in the concluding remarks of https://github.com/nvaccess/nvda/issues/3600#issuecomment-155311106, we may want to morph this ticket to propose a new keyboard shortcut for 'inspecting cell attributes'. A few thoughts in that regard:
* NVDA+E sounds like a fitting keyboard shortcut for this purpose, though there could be several other varied suggestions for the keystroke such a feature should be designated. Regardless, I propose reporting cell attributes upon single press and reporting table attributes upon double press.
* Cell attributes may include the row and column count of the cell, the row and column headers of the same with respect to the cell, perhaps followed by more advanced cell information.
* Table attributes may include the number of rows and columns in the table, the table header (if I am not wrong in recalling that such a thing exists), perhaps followed by more advanced table information.
* The list of cell attributes and table attributes I have provided above is very limited since I have little knowledge about tables, let alone those that are complex, layout tables, etc. Thus, I would like to kindly request others to fill in those gaps so as to make this feature request well-defined.

**Comment by Adriani90** [comment]
This is still reproducible in Firefox 66.0.5 and other browsers. I am not sure if this is an NVDA bug though.
cc: @jcsteh as far as I understand, the last cell in the table should be reported together with "Aproval" and "date". But it is reported only with "aproval" as heading. "date" is being ignored.

**Comment by Adriani90** [comment]
The link does not work anymore.
@kennpetri could you please update with a minimal test case or a new working link?
@jcsteh maybe you can still reproduce this?
