### ISSUE TITLE
MS Word: blank line displayed previous line message

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3630]
**Reported by surfer0627 on 2013-11-08 01:29**
braille settings: Braille tethered to: review

The attachment shows the case.

The third line is blank, but braillle display shows previous line message: 
"erating system."

Please help to soulve the problem, thank you.

**Comment by Adriani90** [comment]
@surfer0627 I guess this is still an issue. Right?
@michaelDCurran #2874 was marked as nearterm milestone two times in the past or so. Is there any work related to this and that issue? I think they are indeed related to eachother.

**Comment by Adriani90** [comment]
@leonardder  Could this be related to #3497?

**Comment by Adriani90** [comment]
@hozosch, @ivnc, @ruifontes are you able to test this with a braille display? Is this reproducible in NVDA 2019.2?

**Comment by hozosch** [comment]
Sorry, but from that description, I don't quite get what to do.

Am 15.08.2019 um 23:53 schrieb Adriani90:

**Comment by Adriani90** [comment]
For example:
1. Open MS Word
2. Enable NVDA with a braille display connected
3. In MS Word, write "hello" on the first line
4. Press enter two times
5. Write "world" on the third line
6. Press left key on the braille display once to pan the braille display backwards

Expected: the braille display should not contain any text, since the focus  should land on the second line which is blank
Actual behavior according to this issue: "hello" appears on the braille display, which is the text of the first line, although the focus should be on the second blank line.

cc: @aaclause can you reproduce this issue?

**Comment by Adriani90** [comment]
Thanks for the update. I am closing this as works for me for now, but feel free to comment with updated steps to reproduce if you are still having this issue and we can reopen.
