### ISSUE TITLE
Lag when using Windows Explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3642]
**Reported by DCPendleton on 2013-11-12 14:49**
While navigating through the file list of Windows Explorer, NVDA takes a minimum of 0.2 seconds to announce the filename depending on the contents or structure of the folder and the number of items contained within it. Naturally the more items are in a folder the more it lags, which can become tedious and frustrating if you need to access files quickly when there are several. For example, it takes approximately 0.6 seconds to announce filenames in a folder of 50 audio files.
I have tried changing the Windows display theme several times but this has no effect as far as the screenreader is concerned. This happens when using the detail view layout in Explorer.

**Comment by bhavyashah** [comment]
@jcsteh Based on https://github.com/nvaccess/nvda/issues/3642#issuecomment-155312478, it does seem like the same issue is being discussed mutually. Thus, could you please respond to https://github.com/nvaccess/nvda/issues/3642#issuecomment-155312474 and update us about the current standing of Windows Explorer's performance on Windows 7 with NVDA?

**Comment by Brian1Gaff** [comment]
This seems to have been going on for some years now. I have to say that in 7 
with the processor idle rate speeded up there seems to be little lag unless 
the folder is very large, then you can hear the indexing happening via the 
beeping.

The main annoyance of all of this is that you can end up actioning a file 
you did not intend as the selected bar has not internally caught up with 
where you are from nvda's perspective.
 I don't think there is much one can do if its the program itself but one 
thing I do not get is why windows does not see its slowing down when nvda is 
in and shove up the processor speed as one supposes its supposed to do?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jcsteh** [comment]
I guess performance being better when starting windows in separate processes makes sense; that would essentially be the same as restarting Explorer for that instance. The bug that causes this behaviour only occurs after quite some amount of usage.

I haven't heard anything to suggest this issue has gone away in Windows 7. It's certainly gone in later versions of Windows. Unfortunately, this is a bug in Explorer, not NVDA, and Microsoft are very unlikely to even consider fixing it for Windows 7, since their focus is now very much on Windows 10. We don't have any way to work around this. Given this, I'm closing this as can't fix, frustrating as that is for users.
