### ISSUE TITLE
MS Excel: braille display shows hyperlink hint at the end of the cell message

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3659]
**Reported by surfer0627 on 2013-11-22 01:35**
In brose mode, a link will display like this:
lnk (the name of this link)

In Ms excel, it will display as below:
(the name of this link) lnk

Developers may have  other consideration for this arrangement. I just want to know the reason.

In addition, I could not active link in Excel. Should I create another ticket for this issue?

Thank you.

**Comment by ehollig** [comment]
CC @leonardder, could you address the first issue on placement of LNK?

**Comment by leonardder** [comment]
[**@ehollig**](https://github.com/ehollig) commented on [13 aug. 2017 05:03 CEST](https://github.com/nvaccess/nvda/issues/3659#issuecomment-322018754 "2017-08-13T03:03:22Z - Replied by Github Reply Comments"):
> CC @leonardder, could you address the first issue on placement of LNK?

This is probably best to answer by @dkager, since he fiddled with link presentation in browse mode recently.

**Comment by dkager** [comment]
> Developers may have other consideration for this arrangement. I just want to know the reason.

The reason is technical. Closing because I doubt the original author will read this.
