### ISSUE TITLE
Excel suggestion:  a way should be avialable to reach out to the objects on a sheet

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3679]
**Reported by sumandogra on 2013-12-02 12:55**
Excel 
It is not possible to reach out to the objects present on an Excel sheet.  Suggestion is to make available a  keystroke that should be able to collect all the objects present in a list then one can select one of the objects as per the requirement to reach out to that particular object.

Note:  This is basically for tracking a experimental feature.

**Comment by leonardder** [comment]
@QChristensen, what do you think about this?

**Comment by jcsteh** [comment]
I think we'd need to see solid real world use cases for this.

**Comment by Qchristensen** [comment]
Do we know what objects the original person had in mind?  The elements list can be used to jump to charts, which is probably the best real world case I can think of.  Objects such as shapes have accessibility issues anyway.  Theoretically, if and when we were able to get more information about shapes (not to mention insert them), having a category to reach them on the elements list could theoretically be useful.  Ditto pivot tables, and sparklines (though sparklines could possibly be put in the "charts" section, since logically, they are essentially simple, one cell charts, even if they behave differently).

**Comment by Adriani90** [comment]
There are no steps to reproduce so i suggest closing it. Button form fields set as macro are accessible in browse mode by pressing f. Charts are accessible with NVDA by pressing nvda+f7 and choosing a chart. I think the only usecase I am aware of is filter cells and macros which change the value for a certain cell (i.e. color etc) but which are not defined as a certain control.
Drop down menus are also accessible and you can press alt+down arrow to open the dropdown list.

**Comment by Qchristensen** [comment]
There are other objects such as pictures, shapes and slicers, but there are specific issues for shapes and slicers at least

Slicer: #6605
Shapes: #7969

So yes, I'll close this one and specific objects can be dealt with under individual issues.
