### ISSUE TITLE
NVDA isn't speaking bullets and nummerations in MS Word 2003

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3696]
**Reported by bdorer on 2013-12-08 12:24**
At the moment I can't test with Word 2010.

This is a regression of #208.

If it works on versions above 2003 may we should dropp support for this version.

**Comment by bhavyashah** [comment]
The original author's https://github.com/nvaccess/nvda/issues/3696#issuecomment-155313717 clearly indicates that this is not an issue, because numbering is reported when list reporting is enabled and bullets are spoken at the appropriate Symbol level. If @Qchristensen and other documentation specialists can identify any lacking in terms of documentation as noted by the original author of this ticket in the cited comment, please open a separate ticket for the same. For now, I suggest closing this ticket at least. @ehollig

**Comment by ehollig** [comment]
Closing, as this seems to be resolved from https://github.com/nvaccess/nvda/issues/3696#issuecomment-155313717. I still would be interested to hear from @Qchristensen and other documentation specialists on any lagging of documentation in this comment.

**Comment by Qchristensen** [comment]
This does come up from time to time.  I'm not sure there's a perfect fix for this, but perhaps in the User Guide under 9.1.3 Voice Settings (punctuation / Symbol level): https://www.nvaccess.org/files/nvda/documentation/userGuide.html?#VoiceSettings. Where this currently reads:

"Punctuation/Symbol Level

Key: NVDA+p

This allows you to choose the amount of punctuation and other symbols that should be spoken as words. For example, when set to all, all symbols will be spoken as words. This option applies to all synthesizers, not just the currently active synthesizer."

Perhaps the first sentence could be expanded to:

"This allows you to choose the amount of punctuation and other symbols (such as list bullets and currency symbols) that should be spoken as words"
