### ISSUE TITLE
Request to remove superseded addon.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3731]
**Reported by MHameed on 2013-12-22 23:45**
From time to time, there is a backwards incompatible change in an addon, and the new version should be able to request the removal of the old and incompatible version.
At the moment this is done in the installTasks.py:onInstall function.
This is duplicated (code and translatable messages) for each addon.
It would make more sence if the functionality lives in the addonHandler.py.

thanks

**Comment by bhavyashah** [comment]
I am in agreement with @jcsteh's following quote:
"While I'm sure this is nice, surely this is the user's responsibility. If they install an add-on from somewhere else and then download an add-on with a different name from the official site, we can expect them to remove the old one. This issue is not unique to NVDA add-ons."
I am not too sure of whether we should still pursue implementing this, but then again, I'll leave it at this - CC @josephsl, @nvdaes, @derekriemer and other add-on experts.

**Comment by nvdaes** [comment]
Hi, I reafirm my previous comments as norrumar (now I'm nvdaes). Cheers

2017-08-15 12:41 GMT+02:00, bhavyashah <notifications@github.com>:

**Comment by derekriemer** [comment]
I feel like this is the responsibility of the uninstalling addon.

**Comment by josephsl** [comment]
Hi,

Technical: an add-on can find out where an add-on lives and ask for add-on removal if told to do so.

I'd say it's something users should be told about and asked for confirmation before the newer add-on removes an incompatible add-on. As for what Zahari pointed out, this might bring up dependency problem where another add-on may depend on features provided by the deprecated add-on, and this is when communication between authors is the key. As for an add-on depending on features from a specific version of NVDA, there is a ticket out there that discusses this (if I'm correct).

For now, I'll close this, as this is more towards something that the add-ons community should discuss in detail. Thanks.

**Comment by nvdaes** [comment]
OK, the question is if NVDA's core could implement a function in
addonHandler to borrow translations, as pointed by Mesar.
Cheers

2017-08-15 17:53 GMT+02:00, Joseph Lee <notifications@github.com>:
