### ISSUE TITLE
The reaction arrow in a chemical reaction is not read as an arrow instead is read as left paren in a word document.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3751]
**Reported by sumandogra on 2014-01-07 12:09**
MSWord 2010
The reaction arrow in chemical equations is not read as arrow instead is read as left paren.

Steps to reproduce:
1.  Open a word document that has certain chemical reaction written in it.
2.  Please see the attachment for an example.
3.  Read the equation with usual reading commands, UP/DOWN ARROW, word reading command(CTRL+LEFT/RIGHT ARROW).
4.  Instead of reading it as an arrow NVDA reads it as left paren5.

**Comment by Adriani90** [comment]
Ok I have managed now to open the document. There are symbols reported as "bracket" (i.e. there is one in the last formula in the word document). But we would need some expertise from a sighted person if that bracket is indeed an arrow symbol or if it is just a normal bracket.
Maybe @Qchristensen or @feerrenrut can help with this.

**Comment by feerrenrut** [comment]
I can reproduce this in NVDA 2019.1.1 the arrow symbol is announced as "paren"

The symbol used in this document does not seem to be commonly used, or a well known symbol. The best I could find quickly was that this has unicode `U+F0E8`. In this case I recommend setting up a speech dictionary to pronounce that symbol correctly.

Because this is not a well known symbol, I don't think there is anything that we can reasonably do about it. Although, it would be better if we knew which ranges we did not support and were able to report "unknown symbol" or similar. I think that should be a separate issue, with some investigation as to how to identify symbols we do not support. For now I'm going to close this issue
