### ISSUE TITLE
support for applications using Siebel technology

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3767]
**Reported by mustafa on 2014-01-10 18:13**
applications using Siebel technology are widely used in call centers so, they will help blind a lot in their professional life. i don't have good knowledge of programming but what i have noticed is that these applications rely heavily on web dialogues and controls. For example you can find a tree view in the web page.

**Comment by ehollig** [comment]
Closing because of comments in https://github.com/nvaccess/nvda/issues/3767#issuecomment-155315467

1. The developer of Siebel should improve the accessibility of the framework so that it can be accessible with all assistive technology products.
2. We need specific details about the problems encountered when using such applications with NVDA to assist with making this application more accessible.

Please feel free to reopen if you feel I am to harsh.
