### ISSUE TITLE
pdf: Page Number and Heading Level Announcement

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3806]
**Reported by surfer0627 on 2014-01-23 07:14**
Hello developers,
  This is a trivial thing. Hoping that NVDA could report page number first while moving to the next page (control+page down). The attachment is a pdf document.

reproduce the case:
1.Open file and press (control+page down) move to the next page.

2.NVDA report: heading level1, page2

expected: page2, heading level1

Thank you.

**Comment by Qchristensen** [comment]
Just revisiting this one, since someone asked, whether page numbers are identified seems to be dependant on the format of the PDF file itself.  I just tried several, and some read the page number when navigating (eg when control+page down is pressed) and some don't.  Some announce it first when NVDA+tab is read and some PDFs announce it last or not at all.

In all cases, however, Adobe reader itself (I'm using Adobe Reader DC, 19.008.20081.46137) does know the page number, as it is displayed in the toolbar after the "Show previous page" and "Show next page" controls, and is written as "5 / 161" where (in this case) 161 is the total number of pages, and 5 is an edit box you can click in to type a new page to jump to.

Having a way to identify the page number, perhaps with NVDA+tab or NVDA+numpad delete, would definitely be useful.

**Comment by Adriani90** [comment]
ctrl+shift+n shows you the current page already.

**Comment by Qchristensen** [comment]
Thanks Adriani!  I couldn't find that in Adobe's documentation.  So, is this issue still an issue otherwise?

**Comment by Qchristensen** [comment]
I must admit, I looked at a couple of files I had before coming to this issue, so I didn't try the linked file until now.  Adriani, the document linked in the first comment downloads as a .pdf.zip - it is in fact a PDF file - rename it and drop the .zip off the end and it should open.  That file does present the reported issue.  NVDA reads  "Heading level 1 Page 2 Letter Two" - when "Letter two" is the text written in heading level 1, and "page 2" is simply reporting which page you are on.  So I agree with the original issue, although as the comments seem to have indicated, fixing it may not be as simple as it seems.

**Comment by Adriani90** [comment]
This seems fixed in Adobe reader 2022 and NVDA last alpha. In fact, NVDA now reports the page number 3 times. When pressing ctrl+page down, NVDA reports:"page 2", then the name of the document, then "page 2 heading level 1 page 2 letter two". Now it is too much repetition, but this is a different issue. I am closing this as works for me.
