### ISSUE TITLE
Keyboard help for  keypad plus does not  change if review mode has been changed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3808]
**Reported by briang1 on 2014-01-23 10:46**
Basically, if you change the review mode using the keypad  keys, and then try to use keypad plus to read text, it does not work as the keyboard help suggests. at least not in my opinion. The effect changes due to changes in the placememnt of the review cursor, but in effect those who have been used to using it as a say all but without moving the actual position, will find that does not happen. I'm not sure if the description in the keyboard help needs changing or a more prominent  warning added to the manual here.

**Comment by bhavyashah** [comment]
I think I agree with @jcsteh's https://github.com/nvaccess/nvda/issues/3808#issuecomment-155316426 because different Input Help messages for each review mode may make sense to a more advanced user, but it may create potential confusion for a novice user who will due to different Input Help messages being spoken for the same keystroke at different times. Unless @Qchristensen and other documentation specialists disagree, I suggest closing. @ehollig

**Comment by Adriani90** [comment]
@Qchristensen, @ehollig what do you think?

**Comment by ehollig** [comment]
I agree with @jcsteh in https://github.com/nvaccess/nvda/issues/3808#issuecomment-155316426. Unless @Qchristensen disagrees, I am going to close this issue
