### ISSUE TITLE
Add a command to read paragraph by paragraph.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3823]
**Reported by aleskis on 2014-01-27 18:38**
For a quick reading, moving paragraph by paragraph is very efficient. Nevertheless, not all application support this command. NVDA could allow this moving in native.

**Comment by ehollig** [comment]
This is discussed in #7052 which talks about moving by paragraph in notepad and #3970 talks about selecting text in notepad with CTRL+Shift+Up/Down if this is the application that was in mind.
It is already possible to move by paragraph in browse mode by pressing CtRL+Up/Down, but #4904 discusses skipping empty lines in browse mode.
CC @derekriemer and @jcsteh for any additional comments.

**Comment by bhavyashah** [comment]
Unfortunately, the original author of this ticket is now out-of-reach and he/she did not respond to @jcsteh's v about any specific application for which paragraph navigation was being requested so as to narrow the scope of this ticket. As @ehollig notes as well, implementing additional paragraph navigation for browse mode may be redundant since Ctrl+up/down arrows works perfectly well for that, doesn't it? Thus, I suggest closing this ticket with a request to open new tickets for paragraph navigation support on a case-by-case (application specific) basis. @ehollig

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster and the specific application requested was not mentioned. Any request for paragraph navigation support will be addressed on an application specific basis.

**Comment by derekriemer** [comment]
It also works in apps like word.
