### ISSUE TITLE
Is NVDA Compatible with Rational Quality Manager?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3824]
**Reported by waldorfpc on 2014-01-27 22:07**
Hello:

This is Reina again, and I am here to trouble you with a question and a problem. At my workplace, we are using Rational Quality Manager Version 4.2 to run test scripts. I am wondering if anyone has used this with NVDA. If so, what was your success. If not, is there a way that NVDA can be made compatible with Rational Quality Manager to help blind people in the IT field? If NVDA is not yet compatible with Rational quality Manager and the developers in the community wish to make it compatible, you can download a trial copy from the IBM website for testing purposes.

When I use Rational Quality Manager, I am using it in IE8. I can do everything accept access one of the drop down menus that contains the option to run a test case/script. I will be upgrading to IE9 to see if this makes a difference.

Pleaselet me know. Thanks so much and take care.

**Comment by ehollig** [comment]
Closing because the original poster did not answer @jcsteh's questions in https://github.com/nvaccess/nvda/issues/3824#issuecomment-155316661. Also, the original posted did not report back trying this in the latest Firefox. If there is still request for this, or parts do not function as expected, please list specific things that are not working in a new issue.
