### ISSUE TITLE
IE8: Web Page Freezed Case

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3883]
**Reported by surfer0627 on 2014-02-13 02:26**
  This is a web page freezed case. I'm not sure is this an NVDA issue or web design issue? So I just send the log file.

browser: IE8
test web page: (in Chinese)
http://www.uro.ntpc.gov.tw/web/Home

reproduce:
1. press ctrl+home to move to top of the page
2. press "m" twice to move to the second frame
3. press "k" to move (link by link)
  It needs few seconds to move from one link to another.
  MM/ SS
  (36:46, 37:03, 37:12, 37:24, 37:41, 38:08)

log file summary:

line: 577
IO - inputCore.InputManager.executeGesture (09:37:24):
Input: kb(desktop):k
DEBUGWARNING - watchdog._watcher (09:37:35):
Trying to recover from freeze, core stack:

line: 608
DEBUGWARNING - eventHandler.executeEvent (09:37:35):
error executing event: gainFocus on <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x03F54610> with extra args of {}
Traceback (most recent call last):

line: 257
DEBUG - treeInterceptorHandler.killTreeInterceptor (09:36:16):
Killed treeInterceptor: <virtualBuffers.MSHTML.MSHTML object at 0x040BE210>
DEBUG - treeInterceptorHandler.update (09:36:16):
Adding new treeInterceptor to runningTable: <virtualBuffers.MSHTML.MSHTML object at 0x0405AD50>

**Comment by bhavyashah** [comment]
@surfer0627 Does this still occur with recent versions of browsers such as Edge, Firefox and Chrome, or do you believe that this freeze was most prominent only on IE 8? If this proves to be an IE 8 specific issue, I suggest closing since IE 8 bugs are no longer worthwhile to address. @ehollig

**Comment by Brian1Gaff** [comment]
It actually does not happen much even in IE8 on the master branch. The main 
issue was I think due to other factors brought about by the  age of IE 8 and 
some web site behaviour. I've not used Edge, but iE 11 and Firefox  hardly 
ever freeze for nvda reasons, even on quite slow machines.
 Occasionally you find Firefox saying its not able to get a page but a retry 
usually fixes this. I see this a lot on nvda updates to portable versions.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
Closing this. If there are similar issues in other browsers or newer versions of IE8, please open a new issue.
