### ISSUE TITLE
Exception thrown when unlocking the computer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3885]
**Reported by aliminator on 2014-02-14 09:47**
A traceback is being produced when doing the  following:
1. Start IE or Firefox 2. Press windows+l to lock the computer and then unlock it.
This is the traceback:
ERROR - NVDAObjects.behaviors.Dynamic_IAccessibleWinConsoleWindowNVDAObject._monitor (10:42:34):
Error getting initial lines
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 247, in _monitor
  File "NVDAObjects\window\winConsole.pyc", line 48, in _getTextLines
  File "winConsoleHandler.pyc", line 121, in getConsoleVisibleLines
  File "wincon.pyc", line 70, in GetConsoleScreenBufferInfo
WindowsError: [6](Error) Handle invalid.

This does happen with the today's master version.

**Comment by bhavyashah** [comment]
@jcsteh's https://github.com/nvaccess/nvda/issues/3885#issuecomment-155317480 seems to suggest that this is an issue that happens with older versions of NVDA. Using a recent NVDA Master snapshot on Windows 8.1 (probably without any extra command console), I was unsuccessful in replicating the reported exception with the following STR:
* Focus on a Mozilla Firefox (version 54 stable here) window.
* Press Windows+L.
* Press any key (e.g. Tab) to get back out of the lock screen.
NVDA does not play the error sound during any of the above steps.
Since we cannot contact the original author of this ticket anymore, this ticket is more than three years old, the described exception is being thrown due to an external software (command console in this case), and Jamie considers this harmless. Time to close? @ehollig

**Comment by ehollig** [comment]
As this sounds to be a harmless error and it does not occur anymore, closing
