### ISSUE TITLE
Add "back to top" at the end of each chapter in the user documentation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3945]
**Reported by PZajda on 2014-03-03 10:00**
Hi,

In the user documentation, it may be useful to have a link "back to top" for example, which would allow to access the table of content, at the end of each chapter.

I know, the table of content is at the top of the document, more precisely at line two for the title. But this link may allow to focus directly the first link, or the level 2 header of the table of content.

**Comment by leonardder** [comment]
@PZajda: Thanks for your request. However, closing as won't fix due to two reasons:

1. As you mentioned, the table contents is at the top of the user guide. The top heading is Level 1, so you can also jump back to shift+1.
2. This would add a massive amount of back to top links, which would disrupt quick navigation by link. Furthermore, we would have a massive amount of extraneous links in the elements list.
