### ISSUE TITLE
A small regression with list views in Total Commander 8.50

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3952]
**Reported by k_kolev1985 on 2014-03-05 14:38**
After upgrading Total Commander to version 8.50, I've noticed a small regression in the way NVDA reads its list views with files and folders. Previously, when you are in a directory and press BACKSPACE to return to the upper directory, NVDA would speak the folder witch gets focused after pressing the BACKSPACE key (it is the directory, in witch you were before pressing BACKSPACE). Now with Total Commander 8.50, when you press BACKSPACE and the folder in the upper directory gets focused, NVDA speaks the first item in the upper directory, witch is the command to go up a level in the directory structure, and only then speaks the currently focused item in the list. But when you press NVDA+UpArrow to read the currently focused item in the list, NVDA correctly reports that the folder in witch you were previously has the focus. I'm not sure that it is a NVDA issue and not a Total Commander one, but with Narrator the issue does not occur.

Steps to reproduce it:
1. Open Total Commander.
2. Go in a directory witch has at least 1 parent directory.
3. Press BACKSPACE to return to the upper directory.

Expected results:
NVDA should read the list item witch gets focused after pressing BACKSPACE in step 3, witch is the name of the folder in witch you were in step 2.

Actual results:
NVDA reads the first item in that list, witch is the command to go to the upper directory and only then it reads the currently focused item.

NVDA version next-10408,f8c857a.
OS version: Windows 7 Ultimate, SP1, 32-bit.
Total Commander version: 8.50, in english.

**Comment by leonardder** [comment]
@k-kolev1985: Can you still reproduce this in Total Commander 9.0?

**Comment by k-kolev1985** [comment]
@leonardder Yes, I can still reproduce this with Total Commander 9.0.

**Comment by Adriani90** [comment]
cc: @novalis7747 do you have any idea if this could be a total commander bug or a NVDA bug?

**Comment by Novalis7747** [comment]
I see that as a combination of both, TC and NVDA. This behavior can also be seen in TC 9.12 and latest NVDA 2019.1 alpha, without any addon. Again it only occurs when going back with the backspace key or with alt-left arrow. As already stated, Narrator does it correctly, but Window-Eyes does it even worse, it always reads the first entry in the listview only.
To be honest, I didn't recognize this misbehavior before, but since at least one screen reader is reading the correct information as supposed I think this could  be fixed within NVDA, either in the part where it handles listviews or in the built-in TC appModule. On the other hand Total Commander did change its listview structure many times in the last 20 years and they are not common listview compliant.

**Comment by Adriani90** [comment]
@k-kolev1985 how is this now with NVDA 2023.3 and Total Commander 11.02?

**Comment by k-kolev1985** [comment]
@Adriani90 I don't know. I stopped using Total Commander many years ago.

**Comment by Adriani90** [comment]
I am closing this issue as abandoned due to missing updates since many years upon requests. If this is still an issue for users of Total Commander, please comment with updated test results and we can reopen.
