### ISSUE TITLE
Seika braille driver does not refresh properly in Thunderbird's message list

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3963]
**Reported by msuch on 2014-03-10 14:59**
When in the thunderbird message list and deleting a message using del key, the synthesizer announces the next message in the list but the Seika display displays a message with the word "unknown" until you press up or down arrow.

**Comment by leonardder** [comment]
This looks unrelated to the braille display of use.

**Comment by Adriani90** [comment]
I have heared about this issue also in other applications. Is it possible maybe to see some related information in a log file? @msuch could you please upload a log file? Preferably set logging in NVDA general settings to "debug". Then, open the python console and type:
```
import config; config.conf['debugLog']['hwIo']=True
```
Then try to reproduce the issue and upload the log file. Thanks

**Comment by Adriani90** [comment]
@JulienCochuyt is this somehow improved in the newer driver versions for Seika?

**Comment by JulienCochuyt** [comment]
> is this somehow improved in the newer driver versions for Seika?

I guess no.
There are two distinct drivers for the two kinds of Seika devices.
- One supports Seika braille displays and is included in NVDA since 2012.3beta1. I assume this is the one the present issue is about.
- The other one supports Seika notetakers (Mini16, Mini24, V6 and V7). We have recently repackaged it as an add-on for easier installation, based on the patch version 3.2 provided by the manufacturer. We are also working on helping this driver candidate for integration into NVDA.

I do not have any of those devices at hand right now, but I regularly do.
I might try to reproduce this issue in a near future.

> I have heared about this issue also in other applications

@Adriani90, would you remember which application / faulty scenario so that we have more means to try reproduce the issue?

**Comment by leonardder** [comment]
@JulienCochuyt wrote:
> We are also working on helping this driver candidate for integration into NVDA.

Out of curiosity, are you indenting to assist them in converting the driver to a native implementation using hwIo? This is mostly preferred.

**Comment by Adriani90** [comment]
@JulienCochuyt especially in E-Mail Clients but also in General in lists where items can be deleted. I am not sure if this is only related to Seika. It could also be due to the Review Cursor not properly jumping to the next item in the list after deleting an item. But for that we should test this with several Braille Displays and under different tetering Options.
@nvdaes, @dkager, @hozosch, could you please test this in different mail Clients or message lists in Chat Clients etc if this is also reproducible with other Braille Displays?

**Comment by hozosch** [comment]
With my braille display, the handy tech active star AS 4-16016, and thunderbird 60.6.1 it works correctly, although sometimes, it displays something else before the next message, but it changes so fast, there's no chance for me to make out what it is. It isn#t like described in the issue though, it does display the next message in the end.

**Comment by nvdaes** [comment]
I can't reproduce this with Ecobraille display on Windows 7 with NVDA 2019.1.1.

**Comment by Adriani90** [comment]
@zstanecic, @larry801 are you maybe available to test this with a Seika Braille display? I seems this issue is really specific to Seika but we don't know if it is still reproducible.

**Comment by seanbudd** [comment]
@cary-rowen is this still an issue?

**Comment by cary-rowen** [comment]
Hi @seanbudd 

I think you can close this Issue, I've been unable to reproduce this with the str provided.

- Thunderbird 91.9.0 (64 Bit)
- NVDA alpha-25456
- Seika Notetaker Mini24

Thanks

**Comment by seanbudd** [comment]
Thanks @cary-rowen
