### ISSUE TITLE
Add number of the kinds of controls in logical order.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3988]
**Reported by vgjh2005 on 2014-03-17 03:08**
There are lots of list/Button/Check etc have no name attribution. We have to browse it one by one and sure what it is everytime. I think, adding a number before them can easily distinguish them. We needn't review them each time, because we can remember the number for that. For example, 2checkbox.

**Comment by bhavyashah** [comment]
I am a little unsure of whether I follow this ticket or not. It seems to me that this ticket is requesting a feature by which NVDA would be able to report the number of the instance of any given element present on the page already.
E.g. A webpage contains three check boxes. If the proposed feature request is implemented, then NVDA would report these as check box 1, check box 2, and check box 3.
@vgjh2005  Could you please inform if my interpretation of this ticket is correct? Regardless, @jcsteh has noted in https://github.com/nvaccess/nvda/issues/3988#issuecomment-155318525 that this may be expensive to do from a performance standpoint. It would be interesting to determine whether the performance regressions such a feature may potentially cause outweighs its usefulness or vice versa.

**Comment by ruifontes** [comment]
The author, vgjh2005, seems wanting NVDA to numbering the different elements 
in a GUI.

I seems it is better to have a way  to allow NVDA to label controls not 
labelled by the developer.
See:
Graphics Labeler Functionality #2111
ability to label previously unlabelled buttons in applications and websites 
#4391
object customizer #6367
suggestion: providing a way to add custom labels on web pages on IE will be 
helpful #5874
Custom labels for MSHTML #6619
In custom labels mozilla #7194
A feature to lable links and graphics where NVDA cannot. #3333
NVDA Custom Label Feature for Web Pages, Word and PDF Documents #2531

and maybe some others...

It seems a rather requested feature by users.
Jaws have a similar feature since many years ago...

Rui Fontes



-----Mensagem Original----- 
De: bhavyashah
Data: 17 de agosto de 2017 12:54
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Add number of the kinds of controls in logical 
order. (#3988)



I am a little unsure of whether I follow this ticket or not. It seems to me 
that this ticket is requesting a feature by which NVDA would be able to 
report the number of the instance of any given element present on the page 
already.
E.g. A webpage contains three check boxes. If the proposed feature request 
is implemented, then NVDA would report these as check box 1, check box 2, 
and check box 3.
1 Could you please inform if my interpretation of this ticket is correct? 
Regardless, @jcsteh has noted in #3988 (comment) that this may be expensive 
to do from a performance standpoint. It would be interesting to determine 
whether the performance regressions such a feature may potentially cause 
outweighs its usefulness or vice versa.

**Comment by ehollig** [comment]
Closing as duplicate from the issues listed in https://github.com/nvaccess/nvda/issues/3988#issuecomment-323368650
Thank you @ruifontes for compiling this list.
