### ISSUE TITLE
Add support for the control rolling.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4019]
**Reported by vgjh2005 on 2014-03-24 07:47**
Hi:
Sometimes, I find some control, the keyboard cannot control the focus,  such as pressing the arrors key or PageUp etc.but the screen review mode can browse it. So, I only browse the current content in the screen. If can add the rool action for those controls? However, Emulating the mouse wheel function is a way to solve the problem. Thanks!

**Comment by leonardder** [comment]
@vgjh2005: Would you be able to reword your initial comment a bit? I'm afraid I don't completely understand what you were trying to say.

**Comment by vgjh2005** [comment]
Hi:
My meaning is that support mouse wheel controlling with keyboard. The second thing is  enable to set two point ( a start point and an end point) to drag down the mouse from those point with mouse clicking.

**Comment by leonardder** [comment]
Windows has a feature called [mouse keys](https://support.microsoft.com/en-us/help/14204/windows-7-use-mouse-keys-to-move-mouse-pointer) which allows you to control the mouse with the keyboard. Furthermore, you can route and click and hold the mouse with NVDA, which allows you to drag and drop with the mouse. I still don't see why supporting a scroll wheel would be helpful. Scroll wheels aren't available on laptops, for example.

cc @QChristensen, what do you think about this from a visual/low vision perspective?

**Comment by vgjh2005** [comment]
Hi:
Actually, there are more scenes that will use the mouse click. NVDA can't do anything for those software that no content can be found and browsed in. For example native kontakt.
Windows mouse keyboard isn't used for blind. Because they don't know which place should be clicked. Or mouse is unuseless for those clickable scene. The reason is that we can use navigator object to insted of it. However, we just used to those scenes that can't be controlled. But for the blind, they don't know which place should be clicked in those unsupported software. So:
1. We need a function to remember the clickable place to perform some specific action. However, we need help from other people to help us locate them.
2. There are more software that can't use keyboard to scroll in the control, but mouse wheel is OK. For example, add external controller control just like this in samplitude.

**Comment by derekriemer** [comment]
Does golden cursor help with this at all?

**Comment by Qchristensen** [comment]
Derek, no, golden cursor doesn't emulate or do anything with the mouse wheel.  I must admit I'm not exactly sure what use case the original poster has in mind either?

You could use Windows' mouse keys to select and drag an item.  The question then is, are there any situations where either the program in question or NVDA cannot provide a keyboard alternative, and if so, is it worth implementing our own version of it, over directing affected users to the Windows feature?

**Comment by vgjh2005** [comment]
Hi:
I have tried the add-on Golden cursor. Quesstion is that possition of it is based on the screen, if the window is moved, and the remembered possition is unuseful.
It need to remember the possition based on the window edge.
Second, I think windows mouse key is unuseful.
For regular UI, we can use navigator object to insted of it. For unregular ui(for example don't support MSAA/UIA/IA etc.), window mouse key can't do anything. Because we will not know which place should be placed. Thanks!

**Comment by josephsl** [comment]
Hi,

2024 update: would the recently implemented keyboard-based mouse scrolling offer at least a partial solution to this issue?

Thanks.

**Comment by Qchristensen** [comment]
I think the mouse scrolling commands in NVDA 2024.3 should fix this issue as much as is possible?  See: https://www.nvaccess.org/post/in-process-19th-august-2024/#mouse

I'm going to close the issue, but please open a new issue if there is still a need.
