### ISSUE TITLE
Merge the synthesizer settings into the Voice settings.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4040]
**Reported by vgjh2005 on 2014-03-29 07:35**
Hi:
I think the voice setting and synthesizer can merge to be one. The reason is below:
1.If the selected synthesizer interface contain a synthesizer that is the default one and NVDA cannot support it, it will not cause error. Because the synthesizer settings mustn't be refreshed.
2. It can be frugal of a hotkey.
3. It looks like more logicaler.
4. It can be frugle of user's time.
After merge them, add a checkbox to define if the voice should be refreshed realtime is more better.
Thanks.

**Comment by bhavyashah** [comment]
@jcsteh Could you please summarize your arguments against the proposed design change? While the proposal does make sense to me, I do understand how refreshing all voice parameters when the a different synthesizer is selected could cause performance problems.

**Comment by leonardder** [comment]
I think this request will be redundant as soon as #577 is done. Still, synthesizer and voice settings will be two separate categories in the new settings dialog, but it is much easier to go from panel to panel, i.e. it doesn't require closing and opening dialogs. Having said that, leaning towards a won't fix.

**Comment by Brian1Gaff** [comment]
I think this will be academic when the tab based property sheets are  put 
into the  snapshots as tabbing is quite easy, and even now the short cut 
keys are faster than the menu if you are a bit pushed for time.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jcsteh** [comment]
1. When you switch synthesizers, you have to load the new synthesizer. That can be relatively slow and can also fail if there is an error loading the new synthesizer.
2. Because of 1), we would definitely not want to do this every time the user changes the synthesizer in the list. Otherwise, moving up and down through the list would be very slow and could potentially throw up error dialogs. Think about those websites which load a new page every time you change the selection in a combo box.
3. I guess we could attempt to switch synthesizers only when the combo box loses focus. However, I'm not sure this is intuitive.
4. There is now also an output device setting in the Synthesizer section. This also requires a synthesizer reload and thus the same concerns (1 to 3) apply.

While #577 perhaps makes this less necessary, it's worth noting that switching categories probably doesn't apply settings (or does it?). If it doesn't, that will actually cause problems for voice settings if the synthesizer is changed.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [14 aug. 2017 08:49 CEST](https://github.com/nvaccess/nvda/issues/4040#issuecomment-322112376 "2017-08-14T06:49:13Z - Replied by Github Reply Comments"):
> While #577 perhaps makes this less necessary, it's worth noting that switching categories probably doesn't apply settings (or does it?). 

Nope, it doesn't, you will explicitly have to click apply.

> If it doesn't, that will actually cause problems for voice settings if the synthesizer is changed.

It wil indeed show the voices for the old synthesizer, unless you have explicitly clicked apply, what you probably want to do anyway if you'd like to test the new synthesizer. But still, that's something that needs to be documented for #577, or we should popup a question when one tries to leave the synthesizer dialog without having the new synth applied.

**Comment by bhavyashah** [comment]
I suppose I agree with the reasoning provided by @jcsteh in https://github.com/nvaccess/nvda/issues/4040#issuecomment-322112376. Also,In particular, #577  will also likely make this ticket less necessary. All in all, may we close this ticket as a wontfix? @ehollig

**Comment by ehollig** [comment]
Closing as wontfix because of reasoning expressed above. Also, #577 may, or may not make this issue less necessary.
