### ISSUE TITLE
Support HTML 5 outline algorithm

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4094]
**Reported by tyrylu on 2014-04-26 21:32**
According to this article: http://accessibleculture.org/articles/2011/10/jaws-ie-and-headings-in-html5/, the HTML 5 outline algorithm has been there for a while and at least JAWS supports it (to some extend).
It would be nice if NVDA had supported it too and if a specific level had been used, it would use that instead. I have no idea how complicated it would be to implement, i just wanted to point it out a little.

**Comment by jmuheim** [comment]
Is there any news on this issue? I'm working for an accessibility consultancy, and the question on whether to recommend HTML5 outlines or not is raised all the time. As an accessibility consultant, at the time being I have to say "no" to my clients, but as a web developer I can't really stand behind this recommendation.

**Comment by ehollig** [comment]
I do not believe I have heard of the HTML5 outline algorithm. I believe it is recommended for web developers and designers to use heading and regions to outline their pages. Thoughts? CC @leonardder @michaelDCurran

**Comment by jmuheim** [comment]
We have written a whole section about this topic in our accessibility developer guide.

> The idea behind HTML 5's heading algorithm is great: it allows to create valid and highly accessible heading outlines that can be much easier to implement than traditional ones. Sadly, it was never really picked up by any browser or screen reader, and the HTML 5.2 draft advises against using it any further.

Check it out: https://www.accessibility-developer-guide.com/examples/headings/html-5-outline/

**Comment by Adriani90** [comment]
cc: @jcsteh, @feerrenrut

**Comment by Adriani90** [comment]
There are already some tools out there that developers might use to structure their websites. See this one for example:
https://www.linkedin.com/advice/1/how-can-you-use-html5-outliner-tool-create-seo-friendly-urpkf?lang=en&originalSubdomain=com

So far NVDA supports the <article> tag, but not yet the <main>, <nav> and <aside> tags.

**Comment by ramoncorominas** [comment]
After many years with buggy/no browser support, the HTML5 outline algorythm was finally discarded about 2 years ago from the standard. You can read the full story here:

[There Is No Document Outline Algorithm — Adrian Roselli](https://adrianroselli.com/2016/08/there-is-no-document-outline-algorithm.html)

**Comment by Adriani90** [comment]
@ramoncorominas thank you for the very interesting lecture on this, it is indeed not easy to convince people to adopt new concepts, especially in developing areas. Some people are really stuck on old concepts and innovative processes are really not on an easy path to follow. I have to cope with this in many situations a lot as a blind person. When reading that stuff I really can understand but probably not imagine how frustrated people must have felt when actively trying to promote this for so many years.

However, if I am not totally wrong, I feel like having a structured outlining method / algorythm does not only help screen readers to better interpret the structure of a website. It might help also in many other use cases, for exacmple displaying websites in a better way on different screens (responsiveness might get better). Another use case might be that the reader mode in browsers can get better with the HTML5 outline algorythm because the <main> part could be technically depicted easier from <nav> or <aside> parts of a website.
So not only screen readers would benefit out of it, but also visual structures might get easier to understand. For example concept boards could implement filter buttons which would make possible to show or hide specific <section> outlines to improve visibility of a complex board.
So I think it might be worth gathering some practical use cases for such an outlining algorythm, and start some discussions again with browser vendors.

cc: @jcsteh and @aleventhal for Firefox and Chrome, maybe it is also interesting for you guys.
I don't know if @stevefaulkner or @scottaohara are in a position or willing to contribute to such a discussion again, but maybe we could get some insights from the different perspectives during a live discussion on Discord. If you guys wish, we could schedule a discussion on this on our NVDA discord server.

**Comment by jcsteh** [comment]
Personally, I'm not willing to put any time into this. That said, I'm closely watching (and contributing to) the current dicussion on headinglevelstart.

People are welcome to discuss this as they wish, but as for this issue, the outline algorithm does not exist, so it is a non-issue. Closing accordingly.
