### ISSUE TITLE
Focus to .NET controls overridden by NVDA in Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4132]
**Reported by jonesay2 on 2014-05-08 18:58**
When a user selects the Submit button, our .NET page validates the form, generates the error messages and displays them inside of a div. Once the page loads, we run a JavaScript function (using $(document).ready()) to set focus to the div. The error div has a tabindex of "-1" so it is focusable.

The keyboard focus is set correctly in Firefox without NVDA running. Once NVDA is turned on, the focus moves from the error div back to the submit button. It's almost like NVDA is overriding the focus that we are setting by setting focus to the last selected element (submit button).

This is a video of my screen to illustrate this: http://screencast-o-matic.com/watch/c2hjFmny48. I've attached a zip of the two aspx files.

**Comment by bhavyashah** [comment]
Unfortunately, the original author of this ticket did not respond to @michaelDCurran's https://github.com/nvaccess/nvda/issues/4132#issuecomment-155320368 and we have no means of contacting him/her at present. Since it seems that we have insufficient information to diagnose the reported issue, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, because of insufficient information to diagnose the issue and inability to contact the original poster.
