### ISSUE TITLE
Upgrade to BRLTTY 5.1/BRLAPI 0.6.2

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4147]
**Reported by nvdakor on 2014-05-19 10:47**
Hi,
Someone from the developer list asked about using BRLTTY/BRLAPI 5.1/0.6.2, which includes various updates and adds support for more displays. The full changelog can be found at:
http://mielke.cc/brltty/doc/ChangeLog.txt
Thanks.

**Comment by leonardder** [comment]
Now that BRLTTY can be used in Windows 10 Narrator, is there anything we should do with this issue?

CC @josephsl

**Comment by josephsl** [comment]
Hi, if Python 2 bindings still exist and provided that we deal with GPL 2 versus 3 licensing, then I think it’d be best to restart the research activity on this one. Thanks.

**Comment by leonardder** [comment]
The only thing I can mention is that I've never managed to get NVDA 
working with recent BRLTTY, mostly due to crashes as soon as I set 
BRLTTY as the braille display in NVDA.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [May 26, 2017, 5:14 AM GMT+10](https://github.com/nvaccess/nvda/issues/4147#issuecomment-304097982 "2017-05-25T19:14:23Z - Replied by Github Reply Comments"):
> Now that BRLTTY can be used in Windows 10 Narrator, is there anything we should do with this issue?

Our current BRLAPI bindings already work with the latest BRLTTy; confirmed by a user in https://github.com/nvaccess/nvda/issues/6764#issuecomment-292894454. Furthermore, there are now official Windows builds on the [BRLTTY download page](http://brltty.com/download.html). Therefore, I think this issue can be closed. Is there any way/reason you think Narrator's use of BRLTTY might affect us?

[**@josephsl**](https://github.com/josephsl) commented on [May 26, 2017, 5:15 AM GMT+10](https://github.com/nvaccess/nvda/issues/4147#issuecomment-304098272 "2017-05-25T19:15:35Z - Replied by Github Reply Comments"):
> Hi, if Python 2 bindings still exist

Pre-built Python 2 bindings aren't provided any more (only Python 3), but as I noted above, our current bindings still work.

> and provided that we deal with GPL 2 versus 3 licensing,

BRLAPI is licensed under LGPL 2.1 or later, so we're okay there.

[**@leonardder**](https://github.com/leonardder) commented on [May 26, 2017, 5:17 AM GMT+10](https://github.com/nvaccess/nvda/issues/4147#issuecomment-304098763 "2017-05-25T19:17:48Z - Replied by Github Reply Comments"):
> The only thing I can mention is that I've never managed to get NVDA 
> working with recent BRLTTY, mostly due to crashes as soon as I set 
> BRLTTY as the braille display in NVDA.

According to https://github.com/nvaccess/nvda/issues/6764#issuecomment-292894454, this is fixed with BRLTTY 5.5. Two users have confirmed this.
