### ISSUE TITLE
Forced restart NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4191]
**Reported by Diego on 2014-06-11 12:10**
Hi
Sometimes, when the shortcut of NVDA from the desktop is removed or are using portable copies and NVDA hangs, it's impossible to quit the program.
Other screen readers have a command that close  all processes automatically and restart the program.

**Comment by bhavyashah** [comment]
@jcsteh Your https://github.com/nvaccess/nvda/issues/4191#issuecomment-155321160 seems to suggest a cantfix to me. Thoughts?

**Comment by jcsteh** [comment]
I think this could be covered as part of #4467, either indirectly (because it restarts after a certain amount of time if a freeze is detected) or directly (via a key press which triggers something similar). Note that we don't know how #4467 would be implemented yet, but it has been triaged for investigation.
