### ISSUE TITLE
NVDA freezes on windows 8.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4200]
**Reported by mohammed on 2014-06-16 13:05**
I notice that on my Linovo computer, running Windows 8.1, Intel Core I7 CPU with 8 gb of ram, touch screen, that NVDA 2014.2 is not responsive with dialogue box. Steps to repro:
1. open note pad for example. 
2. press ctrl + o or ctrl + s.
3. visually the dialogue box instantly appears, however NVDA needs like 3 to 4 seconds to recognize and read it.

On my home assembled PC with the same spects but windows 7, NVDA is very responsive. in fact, NVDA is very responsive on every machine I have ever used it with. I am not sure weather it's Linovo bloatware which I uninstalled most of it, Touch support, or windows 8.1

is there a way to disable touch support from NVDA to troubleshoot this issue?

**Comment by ehollig** [comment]
As the original poster in https://github.com/nvaccess/nvda/issues/4200#issuecomment-155321244 said that the problem is now gone, and @jcsteh suspects that it was a piece of software (or less likely a driver) installed by the computer manufacturer that was causing the problem as stated in https://github.com/nvaccess/nvda/issues/4200#issuecomment-155321245, can this ticket be safely closed? The logs that have been provided do not provide any additional information that I can tell.
