### ISSUE TITLE
Alt must be pressed more than once for MS Office ribbons to gain focus with NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4207]
**Reported by mdcurran on 2014-06-19 01:02**
The UI Automation implementation for MS Office ribbons does not fire a focus event the first time the ribbon is activate after starting NVDA. Due to this, and some other small deficiencies with roles and naming in that implementation, it is probably best to disable UI Automation for the MS Office ribbons entirely. This will mean ignoring UIA for any NetUIHWND window that is a descendant of an MsoCommandBar window.
**Blocking #970**

**Comment by bhavyashah** [comment]
@michaelDCurran Do you have any updates to share with regards to implementation notes for this issue? In my brief (and probably perfunctory testing) with Word 2010, there were two issues I noticed with variable degrees of consistency:
* When I opened a new blank Word document, pressing Alt only took me to the System submenu. Alt+H to specifically go to the Home tab in the ribbon didn't work either. I Alt+Tabbed to another already open Word document and replicated this same behaviour there. Maximizing the window resolved these oddities.
* Next, I opened a new blank Word document to retest these oddities, and pressing Alt did nothing. As reported by Mick in this ticket, the second Alt press was needed for NVDA to go to the ribbon. However, I was able to reproduce this successfully only once.

**Comment by michaelDCurran** [comment]
I was under the assumption that the needing to press alt twice had been fixed along time ago. I can't reproduce it with Word 2016.  As for my comment about not using UIA, it is worth mentioning that going forward, NVDA will exclusively use UIA for MS Word. See #7409. But, this will only be for Office 365. Can this specific issue of having to press alt twice be reproduced in Word 2013 / Word 2010? Getting the System menu when pressing alt seems like an entirely different issue to me. If pressing alt twice issue can't be reproduced in Word 2013 / Word 2010 this issue can be closed.

**Comment by bhavyashah** [comment]
Yes, I am able to reproduce this issue in Word 2010 via the following STR:
* Open a new blank Word document.
* Press Alt.
Expected Result: NVDA should move to the Home tab on the ribbon.
Actual Result: NVDA stays quiet and nothing seems to happen.
* Press Alt again.
Expected Result: NVDA should move to the Home tab on the ribbon.
Actual Result: NVDA does move to the Home tab on the ribbon.
However, this behaviour can be experienced only once per Word document. Pressing Esc and Alt once for the same document as tested above will work as expected, but when a new blank Word document is opened, Alt needs to be pressed twice for accessing the ribbon for the first time. It may be worth noting that the Word window seemed maximized during my above tests.
Wait, upon retesting, the above STR wasn't exactly consistently reliable. I did manage to reproduce this two more times again, but it was hit and miss to some extent. What I noticed in the Log Viewer was that the Alt key press wasn't getting registered in the first place (as in the log showed inputs of Alt+Tab followed by NVDA+F1, although at one of these two times, I am sure Alt interrupted NVDA's speech for the window title. Regardless, it seems like Alt isn't getting sent to Word or the computer either due to a Word deficiency, or something wrong with my keyboard, or something of the sort. This is very trivial though, and I doubt it has got anything to do with NVDA anyways. I am happy for this to be closed because we can always reopen if someone can provide a more concrete method of replication.

**Comment by lukaszgo1** [comment]
I can definitely reproduce this with MS Excel 2010 on Windows 7 x64 100% of the time by simply launching Excel from the run box and pressing alt. When pressed for the first time nothing happens, the second press returns to the sheet and finally third press activates the ribbon. It is NVDA specific, because with the same STR when JAWS 2018 is running ribbon got reported with each alt press. Can this be reopened? It isn't life threatening, but very confusing, especially for new users.

**Comment by lukaszgo1** [comment]
cc @ehollig Could you reopen please?

**Comment by Adriani90** [comment]
I can reproduce this in MS Excel 2010 but only when pressing alt for the first time after opening the application. After pressing escape and then alt again, NVDA reports the ribbon accordingly

**Comment by Adriani90** [comment]
@lukaszgo1 thee were some changes for Excel 2007 in last alpha regarding formulas and regarding performance. Could you please test with last alpha if this is still an issue? I cannot reproduce it anymore in Office 2010 or higher. That PR might have had an effect on this.

**Comment by lukaszgo1** [comment]
Still reproducible. The PR mentioned by you had nothing to do with it.
