### ISSUE TITLE
A question about treating landmark in Nvda.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4236]
**Reported by khsruru on 2014-06-30 17:19**
Hello, I’m Hyongsop Kim in Korea.
In Internet Explorer or Firefox, Nvda doesn’t say where is the end of each landmark.
If there is a complementary landmark, Nvda says the start point of this landmark, but doesn’t say where is finished.
Of course if the other landmark is next to it, there is no problem.
But in many cases, there are many times that after finishing one landmark, the other landmark is apart. 
In this case, screen reader users may don’t know where is the end of this landmark.
Please check this issue.
Thank you.

**Comment by bhavyashah** [comment]
I would like to kindly request that this request be turned down. Many users have reported and many tickets have been filed due to the verbosity caused primarily by landmarks and nested lists, and reporting the end of landmarks could potentially increase these annoyances. I agree with @jcsteh and unless @leonardder and others can provide other cogent counter-arguments, I suggest closing. @ehollig

**Comment by Adriani90** [comment]
Lots of users in Jaws are turning off Landmark reporting completely even because it causes too much verbosity on many web pages. But is it possible to handle a Landmark as a Container and leave it with the key "dot or Koma"?

**Comment by josephsl** [comment]
Hi,

Landmarks are treated as containers, therefore what Adriani is suggesting has already been implemented.

I'll close this for now, and it should be reopened if and only if we get a very good justification as to why we should reconsider landmark verbosity as suggested by the original poster. Thanks.
