### ISSUE TITLE
Report formatting toggles (bold, italic, underline, etc.) in OpenOffice Writer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4248]
**Reported by gregjozk_ on 2014-07-03 15:29**
Some days ago next snapshot of NVDA got ability to report status of font and also has begun to report "bold on", when we pressed ctrl+b to bold some portion of text. is it possible that this functionality can be extended to other applications?

**Comment by Adriani90** [comment]
cc: @qchristensen, @michaelDCurran

**Comment by josephsl** [comment]
Also CC: @codeofdusk

**Comment by Adriani90** [comment]
@michaelweghorn is there any work on this in LO 24? Or should we open a new issue there?
See https://github.com/nvaccess/nvda/issues/4248#issuecomment-455091210 for clarification on how this issue is about, basically to report when formating is added or removed from text via shortcuts. Not sure if these properties are exposed in LO at all?

**Comment by michaelweghorn** [comment]
> @michaelweghorn is there any work on this in LO 24? Or should we open a new issue there? See [#4248 (comment)](https://github.com/nvaccess/nvda/issues/4248#issuecomment-455091210) for clarification on how this issue is about, basically to report when formating is added or removed from text via shortcuts. Not sure if these properties are exposed in LO at all?

@Adriani90 The formatting is reported via text attributes on the IAccessibleText/IAccessibleText2 interface, and since LibreOffice 24.2, the attributes are reported according to the IAccessible2 text attribute spec rather than via custom attribute names and values, see de4e8814f39ab6ae9fbc5330b007494ef6888cd3.

I tried implementing reporting of formatting toggles using that, but ran into the problem of not being able to reliably detect formatting when no text is selected (similar to the newly reported #16412 for MS Word).

A different approach that relies on the toolbar button state (change) works better, I've submitted a corresponding PR:
https://github.com/nvaccess/nvda/pull/16413

That however requires a LibreOffice change so that the state change is actually reported as it should, contained in LibreOffice >= 24.: https://git.libreoffice.org/core/commit/0425b6eb47830b1fe630dc0128d5049f4b3e5582

```
commit 0425b6eb47830b1fe630dc0128d5049f4b3e5582
Author: Michael Weghorn
Date:   Tue Apr 16 19:02:30 2024 +0200

    tdf#160695 wina11y: Send status change events for toolbar buttons
```

**Comment by michaelweghorn** [comment]
> > @michaelweghorn is there any work on this in LO 24? Or should we open a new issue there? See [#4248 (comment)]
> That however requires a LibreOffice change so that the state change is actually reported as it should, contained in LibreOffice >= 24.: https://git.libreoffice.org/core/commit/0425b6eb47830b1fe630dc0128d5049f4b3e5582

This actually requires LibreOffice >= **24.8**, i.e. the version that will be released in August.
