### ISSUE TITLE
CCleaner - unnecessary announcement when focus is moved to its Window

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4288]
**Reported by blindbhavya on 2014-07-13 13:48**
This is an issue I found in CCleaner (latest version) with NVDA.
Steps to reproduce
Open CCleaner and ensure that CCleaner is the only opened application.
Press Windows M to get your focus to the Desktop.
Press Alt Tab once and then release the two keys and wait for NVDA's announcement.
NVDA says :
piriform ccleaner dialog online help check for updates {lots of system information} button with focus.
Ideally, it should just say, Piriform ccleaner dialog button with focus.
If you do not have CCleaner installed on your system, download it from piriform.com, it is a freeware.

**Comment by ehollig** [comment]
@bhavyashah, are you still experiencing this? On Windows 10 with CCleaner  v5.32.6129 I am not able to replicate this with the results that you describe. CC @Brian1Gaff

**Comment by Brian1Gaff** [comment]
I think the design of Ccleaner has moved on since this time. It has had some 
gui alterations and although parts are better, it now seems to not always be 
given focus after some buttons neediing the old shift tab away and back 
method.
 This also happens on Windows 7. However I think the problem is Ccleaner not 
nvda.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by bhavyashah** [comment]
On my present Windows 8.1 and NVDA 2017.2 setup, I can reproduce the
afore described behaviour. However, I am using a slightly old version
of CCleaner - v 5.22.5724, whilst the latest stable release is v
5.32.6129. I would appreciate if maybe a couple developers could
investigate this briefly to verify whether this is an NVDA deficiency
or a CCleaner GUI issue (the latter seems more likely), so that we can
tackle this ticket further. Still, this bug, unless far wider in scope
and triggered by a fault of NVDA, is quite trivial.

On 7/26/17, Brian Gaff <notifications@github.com> wrote:
>
>
> I think the design of Ccleaner has moved on since this time. It has had some
>
> gui alterations and although parts are better, it now seems to not always be
>
> given focus after some buttons neediing the old shift tab away and back
> method.
>  This also happens on Windows 7. However I think the problem is Ccleaner not
>
> nvda.
>  Brian
>
> bglists@blueyonder.co.uk
> Sent via blueyonder.
> Please address personal email to:-
> briang1@blueyonder.co.uk, putting 'Brian Gaff'
> in the display name field.
>
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/4288#issuecomment-318110064


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by ehollig** [comment]
@bhavyashah, can you please update CCleaner to the latest version to see if the described behavior still occurs? If it does, could you please attach a log demonstrating the issue with logging level set to debug?

**Comment by Brian1Gaff** [comment]
This sort of thing is annoying certainly, but one can shut it up. Currently 
if you use the latest master snap and the latest ccleaner you get all the 
junk spokentwice in any case.,

as per..

snip
INFO - core.main (08:17:55.009):
NVDA version master-14289,6c85ce59
INFO - core.main (08:17:55.009):
Using Windows version 6.1.7601 service pack 1 workstation

snip

IO - speech.speak (08:30:01.188):
Speaking [LangChangeCommand ('en_GB'), u'CCleaner  8 of 59']
DEBUG - queueHandler.pumpAll (08:30:01.190):
generator 290 finished
IO - inputCore.InputManager.executeGesture (08:30:02.621):
Input: kb(desktop):enter
IO - speech.speak (08:30:02.859):
Speaking [LangChangeCommand ('en_GB'), u'Piriform CCleaner  dialog  Check 
for updates\nWindows 7 64-bit SP1Intel Core i5-4690S CPU @ 3.20GHz, 8.0GB 
RAM, Intel HD Graphics 4600v5.32.6129 (64-bit)']
IO - speech.speak (08:30:02.888):
Speaking [LangChangeCommand ('en_GB'), u'Cleaner  button  Alt+c']
IO - speech.speak (08:30:02.979):
Speaking [LangChangeCommand ('en_GB'), u'Windows 7 64-bit SP1Intel Core 
i5-4690S CPU @ 3.20GHz, 8.0GB RAM, Intel HD Graphics 4600v5.32.6129 
(64-bit)']

With no indication of any control at all if you let it run, but I know that 
if I then use tab I can get to all the buttons and controls. More annoying 
is the  loss of focus on returning from certain operations, but it has 
always been this way, so I suspect nobody is ever going to fix that one. A 
mouse user automatically refocuses the  control when they click the control, 
but the keyboard does not do this properly.

I think its a minor annoyance, but by no means unique with  this and other 
software.
 One also needs to note that there are a few other issues with Ccleaner.
1 if used in Windows 10 with a portable copy of nvda, it cannot have its 
scanning results and lists read reliably. You usually see these with 
shift/tab after the scan
 Secondly it crashes in its latest incarnation in some XP machines with amd 
processors. This latter behaviour has nothing to do with nvda, and 
everything to do with the lack of the sse2 instruction set in older AMDs.


Personally I don't feel this should be a top priority unless its an easy fix 
(the original complaint that is)
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by bhavyashah** [comment]
@ehollig I hope @Brian1Gaff's testing suffices. If not, let me know and I'd be happy to chime in.

**Comment by bhavyashah** [comment]
@feerrenrut Unless this issue manifests in other places as well or the true scope is wider than we think, I probably wouldn't mind a P3 or a P4 for this ticket.

**Comment by Adriani90** [comment]
@bhavyashah, @Brian1Gaff the design of the GUI changed also during 2018. Could you please test again with last CCleaner Version and Report if the issue still occurs? Thanks.

**Comment by Adriani90** [comment]
Ok I am testing with NVDA 2019.1.1 in CCleander 5.57, the issue is still reproducible. To be clear, when starting CCleaner or when changing to its window with alt+tab, NVDA reports the system information twice and does not report the current focused control. You must press tab or shift+tab to interupt the speech and to hear which control is focused.

**Comment by Adriani90** [comment]
This is solved in the last version of CCleaner. Closing as works for me.
