### ISSUE TITLE
Firefox does not gain focus when started from Windows 7 with latest snapshots

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4296]
**Reported by briang1 on 2014-07-15 21:51**
Firstly, I see another ticket with similar  problems, but to me at least this is different enough to need a new ticket.
 How to get the effect.
 Boot up xp and launch firefox 31 from the desktop shortcut.
 Most of the times  Firefox never puts in any apparence. However it is there, as can be found by just pressing alt, or space or  a cursor key. 
Nvda seems to think its still on the desktop. 
 I am going to attach a log I generated with comments earlier.
 Note that this effect is not in 2014.2, only in master and next snaps for some versions now. 
Sometimes it will work, but not all that often. There appears to be some kind of looping going on somewhere.

**Comment by jcsteh** [comment]
@Brian1Gaff, @MichelSuch, can you still reproduce this on non-XP systems?

**Comment by Brian1Gaff** [comment]
Yes intermittently I can. With auto  say all on, quite often the screen will 
not read on its own. One has to open a menu item then close it again and 
then do a say all. Even cursoring seems to be as if the page is empty.
 Windows 7 and a four core Intel and 8 gig of memory.
 It is more common on a first open of the browser and there is some core 
frozen in stack in the  log but whether this is a red herring I'm not so 
sore.
 Its been an issue for some years.

I think it could be Firefox, but how can one prove it.
 Any version from 48 to the 54 I am currently using seem to be the  same.
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment]
Not on xp demo.


I launched Firefox via the File Hippo  update checker applet. This displayed 
the page but the page was incomplete, ie the files needing to be updated 
were not displayed. I did an f5 to refresh the page. This happened.

IO - inputCore.InputManager.executeGesture (09:19:44.298):
Input: kb(desktop):f5
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes 
(09:19:45.154):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected 
to server', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (09:19:45.155):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 
0x05A4C970>
DEBUG - treeInterceptorHandler.update (09:19:45.164):
Adding new treeInterceptor to runningTable: 
<virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05B345D0>
DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.236):
Thread 4904, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::findNodeByAttributes, 897:
 offset 661 is past end of buffer, returning NULL

DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.237):
Thread 4904, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 788:
Offset 661 out of range. Returnning NULL

DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.239):
Thread 4904, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 808:
Could not locate node at offset, returning NULL

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (09:19:45.239):
oleacc.AccessibleObjectFromEvent with window 0, objectID -4 and childID 0: 
[Error -2147467259] Unspecified error
DEBUGWARNING - browseMode.BrowseModeDocumentTreeInterceptor._set_selection 
(09:19:45.239):
Invalid NVDAObjectAtStart
IO - speech.speak (09:19:45.239):
Speaking [LangChangeCommand ('en_GB'), u'FileHippo.com - Download Free 
Software  busy']
DEBUG - queueHandler.registerGeneratorObject (09:19:45.240):
Adding generator 4
IO - speech.speak (09:19:45.240):
Speaking [IndexCommand(1)]
DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.503):
Thread 4904, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 788:
Offset 661 out of range. Returnning NULL

DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.506):
Thread 4904, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 808:
Could not locate node at offset, returning NULL

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (09:19:45.506):
oleacc.AccessibleObjectFromEvent with window 0, objectID -4 and childID 0: 
[Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.539):
Thread 3776, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 788:
Offset 661 out of range. Returnning NULL

DEBUGWARNING - RPC process 2064 (firefox.exe) (09:19:45.540):
Thread 3776, build\x86\vbufBase\storage.cpp, 
VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 808:
Could not locate node at offset, returning NULL

DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (09:19:45.822):
IARole: span
DEBUG - queueHandler.pumpAll (09:19:47.842):
generator 4 finished
IO - inputCore.InputManager.executeGesture (09:20:20.441):
Input: kb(desktop):NVDA+control+f1
IO - speech.speak (09:20:20.450):
Speaking [LangChangeCommand ('en_GB'), u'Currently running application is 
firefox.exe and currently loaded module is firefox']
IO - inputCore.InputManager.executeGesture (09:20:30.273):
Input: kb(desktop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo 
(09:20:30.345):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states:
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x05A4C690>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 
'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, 
<type 'object'>)
description: None
location: None
value: None
appModule: <'firefox' (appName u'firefox', process ID 2064) at address 
5a36150>
appModule.productName: u'Firefox'
appModule.productVersion: u'55.0'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 328586
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 3776
windowText: u'FileHippo.com - Download Free Software - Mozilla Firefox'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0x83e33e0 at 5b39bc0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=328586, objectID=-4, childID=-318
IAccessible accName: exception: (-2147417842, 'The application called an 
interface that was marshalled for a different thread.', (None, None, None, 
0, None))
IAccessible accRole: exception: (-2147417842, 'The application called an 
interface that was marshalled for a different thread.', (None, None, None, 
0, None))
IAccessible accState: exception: (-2147417842, 'The application called an 
interface that was marshalled for a different thread.', (None, None, None, 
0, None))
IAccessible accDescription: exception: (-2147417842, 'The application called 
an interface that was marshalled for a different thread.', (None, None, 
None, 0, None))
IAccessible accValue: exception: (-2147417842, 'The application called an 
interface that was marshalled for a different thread.', (None, None, None, 
0, None))


When I woke it up by getting the above log and then went back. the page 
displayed OK but the actual focus had moved near to the bottom of the page. 
Bringing it to the top and using list I found the info displayed.
 This sort of part of a page missing is common in firefox intermittently. 
You either get the info missing altogether or a secction in the page saying 
server unreachable or unavailable. A refresh normally fixes it but often 
nvda needs to be sorted by either pulling down a menu or  switching between 
windows open to get it to read.
 Does this help?
 Windows 7 pro64
Any old recent Firefox version up to the latest of course I'm using a 32 bit 
version, by the way. Not tested before version 48 though.
Latest master snapshot.
Though this was launched via an application, I've seen it happen on links to 
other sites from a working system. I did wonder if it was the ad blocker, 
but turning it off seemed to make no real difference on the number of times 
this sort of thing occured.
 My feeling is that firefox is missing bits of a page and whether that is 
due to nvda delaying something or is just how firefox is, or even if its my 
internet connection, I have no way of knowing. However its far less likely 
to occur in IE.

I have had this  issue for a fair time now, and it is of course worse in XP 
presumably due to the slower processors in those machines.

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
@Brian1Gaff: How about the most recent next snapshots that include #7535?

**Comment by Adriani90** [comment]
I suggest closing this in favor of #8389 and referenced issues because they are reproducible on Windows 7 and higher.

**Comment by Adriani90** [comment]
@leonardder, @brian1gaff what do you think about my Suggestion above?

**Comment by Adriani90** [comment]
@leonardder, @brian1gaff what do you think about my Suggestion above?

**Comment by Adriani90** [comment]
I am closing this in favor of #8389 because this issue is very general and occurs in several situations regardless of the application. The discussion in that issue goes further and will continue there.
