### ISSUE TITLE
unstable audio volume

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4298]
**Reported by rwang on 2014-07-16 13:17**
Since the very begining I installed the NVDA, the speak volumes were always started from 0 for every sentence then graudally increased to the normal volume. Just like turn on the radio volume dial, from the very left side to teh rlight side. It makes the instruction difficult to catch since the begining were mostly inportant cues.

computer settings:
Asus S400C notebook
Windows 8
Office 2007
Realek audio

I am just a enduser who does not know much about computers. Asus can not give me an solution, and they claims it must teh thrid party's porblem. Can anyone help? Thanks

**Comment by ehollig** [comment]
As @Brian1Gaff said in https://github.com/nvaccess/nvda/issues/4298#issuecomment-155322226, it sounds like this is a hardware issue if the problem is occurring with other screen readers as well. Can this be closed?

**Comment by bhavyashah** [comment]
Yes, I suppose so. The fact that other audio also experiences this problem on the computer clearly implies that there is something wrong with the hardware as opposed to the software. Feel free to close as invalid. @ehollig

**Comment by Brian1Gaff** [comment]
I have seen this kind of thing with various sound cards. Often its driver 
related. Certainly in the case of a creative card a downdate to the older 
driver banished this apparent random volume setting at inopportune moments 
completely.
 This was in XP, but I'd imagine resetting hardware values is the issue, 
probably triggered by some control signal being misinterpreted.
 And yes it was all sound not just nvda and could happen even with nvda off.

Just my experience.
Might of course be different on this ticket since we do not have all the 
facts.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
Closing as invalid because of https://github.com/nvaccess/nvda/issues/4298#issuecomment-319237559
