### ISSUE TITLE
when speak typed words feature is on, pressing the spacebar sometimes wrongly announces words

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4308]
**Reported by blindbhavya on 2014-07-18 11:14**
Let me give you the example of a simple English word.
Note : This issue is inconsistent and may or may not work in all cases. However, the following steps to reproduce worked on two machines successfully (running Windows 7 Ultimate & Starter respectively).
Steps to reproduce
Press Windows + R to launch the Windows Run dialog box.
Ensure that the speak typed words feature is enabled (NVDA + 3).
Type the word 'incredulous' in the Run dialog box and press the Spacebar.
NVDA should say encredulous.
I repeat that this issue is not consistent and till now I have found that the word 'incredulous' is mispronounced in some cases.
**Blocking #4613**

**Comment by bhavyashah** [comment]
@jcsteh Just a friendly reminder to review this more than 2-year-old code submission.

**Comment by jcsteh** [comment]
Here's [the patch from Trac](https://github.com/nvaccess/nvda/files/1203624/0001-fixed-t4308-Nvda-no-longer-should-omit-the-first-cha.patch.txt).

@derekriemer, thanks for the patch. While this will indeed fix this particular case, the problem is that there are a lot of other cases it doesn't address; e.g. start typing a word, press NVDA+f12 to report the time, press space and you'll get no word. We really need to find a better place to clear curWordChars or, better still, get the word from the application.

Closing as a duplicate of #1259, which was missed when this was filed.
