### ISSUE TITLE
NVDA reports "Program Manager" when using read window title command (NVDA+T) on the Desktop

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4344]
**Reported by brandon15 on 2014-07-30 17:41**
When you go to the desktop and move around the icons, and you check the window title with NVDA+T, NVDA reports Program Manager.
Following are the steps to reproduce this problem:
1. Press Windows+M to go to the Desktop. NVDA should say "Desktop list."
2. Press NVDA+T to read the window title. NVDA will say "Program manager."
Instead, I think NVDA should say "Desktop" as this seems like a better name for this in my opinion.
This is not a huge problem, but I was just wondering if it could be corrected when you have time if you don't mind please.

**Comment by bhavyashah** [comment]
@jcsteh If NVDA is correctly reporting whatever Windows is exposing, I reckon it is okay to leave the current behaviour as it is, particularly because users are already familiar with this. Still, if you believe that this might be a quickfix/goodfornewdevs which may not confuse existing users, that would be equally fine by me. Feel free to triage accordingly.

**Comment by jcsteh** [comment]
Closing as duplicate of #4353, since that issue has more detail and the same fix should be applied to cover both cases.
