### ISSUE TITLE
Nvda quit by itself at sign in screen

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4395]
**Reported by christopherh40 on 2014-08-15 11:25**
Can any of you duplicate the following please.
1. Make sure Nvda is set to be used at the Windows logon and other secure screens. 
2. Shut down or restart your computer. If you're logged in automatically sign out by pressing Windows-x, u, i. 
3. Does Nvda quit on you seconds after it loads? Because it does at my end. See I have a PIN set on my account so I am asked for it at the sign in screen. But when I start typing it Nvda just quits working for me. I have to resort to Narrator to help me complete the process. Not a big deal but never had any trouble with Nvda on Windows 7. But the strange thing is Nvda is completely stable once I've signed in.

**Comment by bhavyashah** [comment]
I do not have a password to log in to my computer, but I have never heard reports of something fairly critical as this elsewhere. Since this ticket is more than 3 years old and we have no means of contacting the original author of this ticket for further diagnosis, unless we receive feedback confirming the reported issue, I suggest closing. @ehollig

**Comment by Brian1Gaff** [comment]
I have not seen anything like this for a long time.
 I do recall that some changes in 10 did stop nvda working on the screen for 
a while, but not crashed it.
 Brian

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster for more information or to clarify if this is still occurring for them. Also, @josephsl mentioned in https://github.com/nvaccess/nvda/issues/4395#issuecomment-155325881 that it worked for him. In order to determine what may be going on with this specific case, we would need a [crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) to see why NVDA crashes.
