### ISSUE TITLE
NVDA ignores aria-label on elements with role="math"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4422]
**Reported by jhung on 2014-08-26 16:44**
NVDA 2014.3rc1 is ignoring aria-label values if role="math" but should not.

In this example, aria-label helps provide semantics of math to ATs that would otherwise be lost to a non-sighted user.

```
<span role="math" aria-label="F subscript g equals m times g">
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
            <msub>
                <mi>F</mi>
                <mi>g</mi>
            </msub>
            <mo>=</mo>
            <mi>m</mi>
            <mi>g</mi>
        </mrow>
    </math>
</span>
```

**Comment by bhavyashah** [comment]
@jcsteh You seem to indicate in https://github.com/nvaccess/nvda/issues/4422#issuecomment-155326820 that this issue would be invalidated if Math Player support in NVDA becomes a reality, which it has, as of 2017. Time to close? @ehollig

**Comment by ehollig** [comment]
Actually, MathPlayer was implemented into NVDA in 2015.2 according to the What's New.
• Using MathPlayer 4 from Design Science, NVDA can now read and interactively navigate mathematical content in web browsers and in Microsoft Word and PowerPoint. See the "Reading Mathematical Content" section in the User Guide for details. (#4673)
Closing, but can be reopened in I misunderstand the issue.

**Comment by derekriemer** [comment]
No, aria-label with role of math labels something, but identifies the node as math.

**Comment by jcsteh** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [15 Aug 2017, 00:40 GMT+10](https://github.com/nvaccess/nvda/issues/4422#issuecomment-322208635 "2017-08-14T14:40:15Z - Replied by Github Reply Comments"):
> No, aria-label with role of math labels something, but identifies the node as math.

It would also override the real math content within. See the example provided in the [issue description](https://github.com/nvaccess/nvda/issues/4422#issue-116044308). The label is being used to provide a spoken representation of the math. We don't want to override usable math semantics with simple text.

Since MathPlayer did happen, this issue should indeed be closed.

**Comment by derekriemer** [comment]
What if it's <img role="math" aria-label="x+2" blah>

**Comment by derekriemer** [comment]
wo, um ... I don't know how my message came through like that. What I meant, and have no idea how it happened, is What if `<img role="math" aria-label="a subscript one plus a subscript 2 plus dot dot dot plus a subscript n" src="blah">`

**Comment by jcsteh** [comment]
role="math" is somewhat of a problem. The spec is pretty vague/unclear on
how it should be used/handled. Furthermore, it's difficult to differentiate
it from the <math> tag. I honestly don't think we can support this properly
until the spec gets clarified.
