### ISSUE TITLE
NVDA crashes testing to create a plugin with a wx menu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4424]
**Reported by norrumar on 2014-08-27 06:04**
While creating an unfinished add-on, in the test process, NVDA crashes, probably due to something done with wx menus.
If this plugin was continued, functions to up and down list items in a dialog should be reviewed, probably not disabling the buttons when the first of last element can't up and down throught the list items.

**Comment by bhavyashah** [comment]
@jcsteh indicates that the reported issue is almost certainly a WxPython bug in https://github.com/nvaccess/nvda/issues/4424#issuecomment-155326851, does our upgrade to a newer version of WxPython affect this ticket in any way? @josephsl

**Comment by Adriani90** [comment]
@josephsl, @jcsteh, @norrumar is this issue still valid given the new WX Python Version used in NVDA now?

**Comment by josephsl** [comment]
Hi,

Original poster: @NVDAEs, can we get an updated version of dictionary manager if you don't mind attaching it here or sending it to add-ons list? Thanks.

**Comment by nvdaes** [comment]
Hi, seems the attached pluggin is lost. Unfrtunately, I'm not good saving previous work locally, and frequently I loose previous works if I don't save it on a remote repo (sorry but order and planning or saving things to find them later is not one of my abilities. I have found a conversation on the old add-ons list where we commented with @Christianlm the possibility of creating a dictionary manager with a combo box to choose different dictionaries talking about Emoticons add-on. This is implemented in Emoticons but not with a combo box, but using different dictionaries for profiles.
So, I could work in a dictionary manager if neeced, but imo this issue could be closed since I don't have the original plugin.
Cheers.
