### ISSUE TITLE
MS Word2010: NVDA skips text in particular page

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4438]
**Reported by surfer0627 on 2014-09-04 03:22**
1. Open file "sample, NVDA skips text in particular page.rtf"
2. Press ctrl+page down twice, (turn to page 3)
3. Press down arrow
        NVDA report: page break
4. Press down arrow again
        NVDA report: page 4
5. Press up arrow
        NVDA report text in page 3

Sorry, the sample file is in Chinese.

**Comment by ehollig** [comment]
I am not able to replicate using the above steps using Word 2016. Can someone else confirm the same? As we are unable to contact the original poster, I will close, once I have confirmation from someone else that they are unable to replicate.

**Comment by bhavyashah** [comment]
Ctrl+PgUp and Ctrl+PgDn are the keystrokes to navigate between Find dialog search results. Regardless, arrowing between Page 3 and Page 4 contained no break as such. However, the document is indeed complex and NVDA reports 'new page' instead of the page number in some cases. Unless @surfer0627 requests otherwise, I believe this ticket can be closed as worksforme. @ehollig

**Comment by ehollig** [comment]
Thank you for testing @bhavyashah. Unless we can receive more information from the original poster, closing as worksforme
