### ISSUE TITLE
Formula and excell bug

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4440]
**Reported by chad.blanco on 2014-09-04 21:21**
NVDA will not read cell coordinates when entire column is selected and a formula is pasted.

**Comment by bhavyashah** [comment]
Can any more proficient Excel user understand what exact steps need to be taken in order to reproduce this issue? I don't think I follow, and we have no means to request a follow-up from the original author of this ticket either. Triaging thoughts? @ehollig

**Comment by ruifontes** [comment]
For me, can be closed.

How to try to reproduce:
1 - In A1 write a formula. Press Control Enter;
2 - Copy it to clipboard;
3 - Move to colun B;
3 - Press Control Space to select all the column;
4 - Press Control+V.

Expected and it happens.
NVDA announces the cell range and values of first and last cells.

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 09:47
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Formula and excell bug (#4440)



Can any more proficient Excel user understand what exact steps need to be 
taken in order to reproduce this issue? I don't think I follow, and we have 
no means to request a follow-up from the original author of this ticket 
either. Triaging thoughts? @ehollig

**Comment by ehollig** [comment]
This worksforme using Excel 2016 and performing the steps in https://github.com/nvaccess/nvda/issues/4440#issuecomment-323390341 which I believe to satisfy the requirements in the original post. NVDA does read the range of cells when CTRL+V is pressed. Closing
