### ISSUE TITLE
Issue with progress bar in firefox 3.5 html5 audio player

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#448]
**Reported by aleksey_s on 2009-11-01 07:53**
## steps to reproduce
- go to http://www.nvda-project.org/audio/nvda_demonstration_r380.ogg
- after the playback is started, navigate to the second progress bar which show the current position in the file
- move around it with horisontal arrows or numpad keys while the value changes
## current results

NVDA will each time read "out of progress bar in progress bar X" (where X is an actual character).
## expected results

NVDA must announce this information only when you actually leave that progress bar instead  while you are moving through it.

**Comment by derekriemer** [comment]
Hi: can't reproduce any more. Is this still true? if so, how to reproduce?

**Comment by feerrenrut** [comment]
# Chrome Version 55.0.2883.87 m
Press tab until "slider  editable  film time scrubber blank" is reported. Move the time scrubber (to alter the position withing the file).
No position information is reported.

Press tab twice more, "media control  0.75  media control" is reported. This controls the volume.
When left and right are pressed the normalised volume level is reported (E.G. 0.74 0.73 0.72)

# Firefox Version 50.0.2
Switch to focus mode (I could not find a way to control this in browse mode)
tab until "grouping" is reported
left and right alter the position within the audio file. With each key press the position is reported using the progress bar tones.
space plays and pauses the file, not reported by nvda
up and down alter the volume, not reported by nvda

In browse mode I was able to get nvda to read the position (in percent) of the progress bar. This seems to reproduce the issue:
Press tab until "nvda_demonstration_r380.ogg  document" is reported, then pressing `ctrl+right arrow` several times I get the following output:
> button
> Pause
> out of button
> progress bar
> 1.21533709392889%
> out of progress bar
> progress bar
> 4.56%
> out of progress bar
> slider
> 14
> out of slider
> button
> Mute
> out of button
> slider
> 100

I'm not sure what the first progress bar is (at 1.21533709392889%).
The progress bar 4.56% seems to be the position in the file.
I don't know what "slider 14" is
The control "slider 100" seems to be the volume control.

# Firefox Version 50.1.0
Similar behaviour to version 50.0.2

# Internet Explorer  Version: 11.576.14393.0
Update Versions: 11.0.38 (KB3203621)

Unable to play the file within the browser.

**Comment by feerrenrut** [comment]
It seems like the behaviour here could be improved. I'll set this to priority 3 for now.

**Comment by Adriani90** [comment]
This is not reproducible with NVDA 2017.3 and Firefox 60.0.2. When navigating with arrow keys, the Progress bar is only reported when entering or leaving it. When pressind ctrl + arrow keys NVDA treats the numbers as single word. That's why Progress bar and out of Progress bar is reported before and after the numbers. The numbers are in different Progress bars.

@feerrenrut I suggest closing it because the original issue reported is not reproducible when following the instructions in the issue.

**Comment by Brian1Gaff** [comment]
Is this the same issue where the bleeps come over while playing media?

I guess what this needs is some kind of situation specific turning off of 
the progress output.
 Brian

**Comment by feerrenrut** [comment]
When testing this again:

Chrome seems to be quite accessible

Firefox version 61.0.1:
Still seems to have similar issues. The positions of the progress bars are reported as percentages (with an excessive level of precision. Neither of the progress bars (position in file, volume) seem to be labelled.

**Comment by DrSooom** [comment]
### Actual behaviour in Firefox 65.0 with NVDA 2018.1:
+ Loading progress bar: 123.1234567890123%
+ Playing progress bar: 123.1234567890123%
+ Current position slider: 1234 (for 0:00:01.234, h:mm:ss.ms)
+ Volume slider: 100%
### Expected behaviour:
+ Loading progress bar: 123.12%
+ Playing progress bar: 123.12%
+ Current position slider: 00:01 / 59:59 (mm:ss; current / total)
0:00:01 should be shown only for media files which a longer than 1 hour.
+ Volume slider: 100%

I only reported the HTML audio tag. An additional look at the HTML video tag is required too.
CC: @MarcoZehe and @jcsteh: I guess this has to be changed on Mozilla's side, right?

**Comment by jcsteh** [comment]
Yes, this needs to be fixed in Firefox. We're tracking this in [Mozilla bug 1496851](https://bugzilla.mozilla.org/show_bug.cgi?id=1496851).

**Comment by fisher729** [comment]
Hi.

Therefore, can this be closed, as an external fix is needed. @jcsteh

**Comment by Adriani90** [comment]
I guess Jamie will close it as soon as the Firefox bug is being fixed. I propose to let this issue open since there might come other users accross this issue and they might report it to Mozilla or might comment on the bug which is referenced above.

**Comment by jcsteh** [comment]
bugzil.la/1496851 is fixed for Firefox 81, along with other bugs impacting screen reader usage of native video and audio controls: bugzil.la/1622995, bugzil.la/1659641. There will probably be further fixes coming, but I believe this covers the problems discussed here.
