### ISSUE TITLE
Braille doesn't follow on LibreOffice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4498]
**Reported by Texou on 2014-09-29 00:50**
Hi,

I try using Insert a formula in LibreOffice Writer. Formulas are so orderd per category, then I've the list. But while I access to the list with the arrow keys by speech synth, I have no access through my braille display. It is set to follow the focus, but stays blank.

Thanks for the fix and let me know if you need further info.

**Comment by Adriani90** [comment]
It seems we unfortunately do not have any response from the author since 5 years. I tend to close this issue. But before doing that, maybe someone with a braille display could test quickly.
cc: @Qchristensen, @novalis7747, @dkager, @bramd, @leonardder.

**Comment by Adriani90** [comment]
@david-acm, @zstanecic, @ruifontes, @nvdaes, @lukaszgo1 could someone please test if this is still an issue in Libre Office?

**Comment by bramd** [comment]
I can't reproduce this. However, after inserting a formula and going to the pane with functions with f6, this list of functions in a category is not readable. It is just reported as a "scroll pane". However, since the categories read corectly and the scroll pane is not accessible at all (either in speech or braille) this is clearly a separate issue.

**Comment by Adriani90** [comment]
Thanks for reporting back. I am closint this as works for me. Please comment on it if you still see this issue.
@bramd would you mind to open a new issue for that scroll pannel? Thanks.
