### ISSUE TITLE
Slow population and navigation of List in Windows Explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4530]
**Reported by kayatli on 2014-10-04 21:04**
When NVDA has been running for a period of time on any Windows OS, regardless of the computer being idol or not, navigating lists of folders and files in Windows Explorer becomes tedious due to a slow population of lists and a lag when pressing arrow keys to move up and down lists. When pressing the arrow keys, it takes a full second before the file or foulder is announced and when going to a directory, the progress bar tones can be heard. Restarting NVDA does not fix the issue. This issue occurs consistently when NVDA is running for a period of time(more than 4 hours).

**Comment by bhavyashah** [comment]
Windows XP specific issues are no longer addressed and Windows 8 has been superceded by Windows 8.1. Thus, we need only focus on Windows 7 and Windows 8.1 for the purpose of this ticket. As a long-time Windows 8.1 user, I can confirm that I have been having no such issue since months with Windows Explorer. @jcsteh has acknowledged the presence of such a bug on Windows 7, attributing it to a problem on Microsoft's part. Have Windows updates on Windows 7 resolved this by any chance or does this issue still persist? In case it is the latter, is there anything that can be done from our end to address this in any way?

**Comment by Brian1Gaff** [comment]
Was not this resolved by the Microsoft issue of throttling back the 
processor in advanced power settings not taking notice of the load of nvda?
 I have no issues in XP in current snaps I've tried, but 7 still is a little 
slow to catch up with the screen, Idea I can think I've highlighted a file 
to pay and a totally different one plays if I do not wait a second or so.

Its not serious though, and as I've for years used XP where the hardware of 
course was slower, one gets used to doing things this way.
 I used to find it in windows 10, but have no daily access to a machine at 
the moment but suspect upping the processor idle speed may well fix it.
 If this is not the case maybe somebody else has more details.
 There has been a few messages about this sort of issue in the main user 
list on and off.
 Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@kayatli are you still having this issue? @bhavyashah seems not able to reproduce it anymore. @Brian1Gaff Can you reproduce it still?

**Comment by Adriani90** [comment]
I have not seen this issue on Windows 8.1 and Windows 10 at all. And I am using the PC at work the whole day. I will close this issue since we have confirmations from Brian and @bhavyashah that the issue is not reproducible. If someone reports it, we can reopen it again.
