### ISSUE TITLE
Caret navigation problems when editing or browsing formulas in Excel

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4537]
**Reported by Palacee_hun on 2014-10-08 13:53**
It's not possible to give exact steps to reproduce, because this appears a bit randomly, but I can give a fair description.
When I arrow through a formula in order to edit it (after pressing F2), I experience that sometimes NVDA says "blank" or the character at the previous caret position instead of saying the correct character under the caret. This happens most often near parentheses in the formula. This makes formula editing quite unreliable and error-prone.
Symptoms make me think that the caret timeout is too small for formula editing in this edit box, because Excel does a lot of processing during editing formulas. I've never experienced this when doing simple data entry/editing.
This problem is reproducible with Jaws, although the symptoms are a bit different, but point to the same cause.
My machine is not particularly slow (1.8 Ghz, dual-core Intel CPU). I use Excel 2003, but this problem may well present itself with other versions.
Increasing the caret timeout for this edit box wouldn't do much harm, but it  would most probably eliminate this problem.

**Comment by bhavyashah** [comment]
This issue was definitely present very starkly till November last year, after which my usage of Excel became negligible. In my brief testing with NVDA 2017.3 RC 1 and Excel 2010 on Windows 8.1 just now, when I type "=sum(a2:a3)" in A1, pressing F2 on A1 to read the formula syntax itself, NVDA misses out on the last character of the formula, i.e. ")". This is consistently reproducible because the ')' just isn't existent to NVDA although I have ensured its presence. Thoughts? @michaelDCurran

**Comment by ruifontes** [comment]
After pressing F2, maximize the window.
That way, NVDA reports all characters...

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 16:59
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Caret navigation problems when editing or 
browsing formulas in Excel (#4537)



This issue was definitely present very starkly till November last year, 
after which my usage of Excel became negligible. In my brief testing with 
NVDA 2017.3 RC 1 and Excel 2010 on Windows 8.1 just now, when I type 
"=sum(a2:a3)" in A1, pressing F2 on A1 to read the formula syntax itself, 
NVDA misses out on the last character of the formula, i.e. ")". This is 
consistently reproducible because the ')' just isn't existent to NVDA 
although I have ensured its presence. Thoughts? @michaelDCurran

**Comment by bhavyashah** [comment]
The work-around mentioned by @ruifontes in https://github.com/nvaccess/nvda/issues/4537#issuecomment-323396416 does not make any change in the test I performed and described in https://github.com/nvaccess/nvda/issues/4537#issuecomment-323393059. The ")" remains invisible to NVDA even when Excel is maximized or object review is used to inspect the cell contents.

**Comment by Adriani90** [comment]
Duplicate of #4372. However I suggest cloind #4372 because the discussion here goes in more detail. cc: @leonardder, @Qchristensen your thoughts are very apreciated.
I can reproduce this issue only in long formulas. In short formulas it does not occur. It might be related to the visibility of the text in the cell itself. I think there was an option in Excel to disable something and to access the editing area when pressing f2 instead of the cell itself. @Qchristensen you had written about that in one of the in process articles.
In the edit area this issue does not occur.

**Comment by Adriani90** [comment]
I decided to close this in favor of #4372 because that issue is being referenced on newer issues as well.
