### ISSUE TITLE
symbol 0x3000 cannot be recurnized.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4543]
**Reported by vgjh2005 on 2014-10-11 12:31**
Hi:
I meet this symbol. I add it to the symbol to define its reading. But I cannot do that. If I put it into speech dictionary, and it is recurnized correctly. 
Thanks!

**Comment by ehollig** [comment]
@vgjh2005, is this still the case for you? If so, please upload the problematic file and indicated the line number of the new symbol as suggested in https://github.com/nvaccess/nvda/issues/4543#issuecomment-155329036.

**Comment by Adriani90** [comment]
@vgjh2005 are you still having this issue?

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
Ok the ideographic space 　 is widely used in east asian typographie to have a space exactly the same width as the characters around it. I can imagine that it makes sense to announce this character. I would implement this in the symbols.dic but I think it makes sense to have NVDA being able to report the unicode names of characters when pressing nvda+dot before doing this. Then we could let NVDA announce "space" for all space replacement characters when navigating around and the users can decide if they want to know the complete unicode name of the character spoken by pressing the command.
Alternatively there could also be a checkbox in the NVDA settings called "pronounce space characters as unicode names" which allows reporting them completely also when navigating. But I think it makes sense to have them spoken on demand rather than during navigation in the first run.

**Comment by CyrilleB79** [comment]
Testing on NVDA 2023.3:
The character "　" (ideographic space, code 0x3000) can be added in the symbol dialog.

I am closing this issue.

If you cannot add the symbol on your side or if the request is about adding this symbol in the factory symbol file of NVDA, please comment here and I will reopen.

**Comment by Adriani90** [comment]
@CyrilleB79 I think people using Asian languages would not want to include this symbol every time in the symbols dialog manually. I can include it in the symbols.dic as suggested above, but I would like to have the unicode names pronounced on demand first. Otherwise announcing "ideographic space" every time when NVDA lands on the character is too verbose.
I am reopening.

**Comment by CyrilleB79** [comment]
@Adriani90, my understanding is that the person who has opened this issue (@vgjh2005) could not add ideographic space in his personal symbol file, even trying with alternate methods (e.g. using character number instead of actual character).
I have done it successfully with NVDA 2023.3, thus I have closed this issue since it was the initial request.

You write:
> @CyrilleB79 I think people using Asian languages would not want to include this symbol every time in the symbols dialog manually. I can include it in the symbols.dic as suggested above, but I would like to have the unicode names pronounced on demand first. Otherwise announcing "ideographic space" every time when NVDA lands on the character is too verbose. 

@vgjh2005 has not answered although requested two times already. I think that we cannot activate this issue if we have no input from the original author; there's no need to imagine the need of Asian people without any feedback from them.

If there is a real need (@cary-rowen, @hwf1324?), I'd prefer that a brand new clear and activatable issue be opened.

**Comment by cary-rowen** [comment]
Hi,
@CyrilleB79 @Adriani90 
I believe this has been fixed, thanks for your attention.
