### ISSUE TITLE
Difficult to open attachments in Outlook.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4571]
**Reported by csm120 on 2014-10-23 12:47**
When I try and open attachments in outlook, I need to select it first using typical selection commands then move the mouse to the focus and do a left click. I would like to be able to arrow to the attachment and hit enter.

**Comment by ehollig** [comment]
@csm120, is this still the case? What version of Outlook is being used

**Comment by fernando-jose-silva** [comment]
I have a problem with outlook 2013 to open excel documents, right after putting the arrow on the file the nvda pronounces something like viewer's outlook and I can not open the file with enter.

**Comment by Adriani90** [comment]
This is because Outlook displays the live preview of the file. Please disable the coresponding option in Outlook itself, then you can use arrow keys to navigate through the attachments and you can use enter to open them.

**Comment by Adriani90** [comment]
I suggest to close this issue because it is actually not an issue. NVDA moves the focus on the live preview window but it does not read the content. For that there is another issue. If you have questions on how to disable the live preview in Outlook, please do not hesitate to ask for help on the users maillist on
https://nvda.groups.io/g/nvda

**Comment by Adriani90** [comment]
@ehollig what do you think?

**Comment by ehollig** [comment]
Closing as requested, and because we have not heard from the original author since the creation of this issue.
