### ISSUE TITLE
Report changes to screen orientation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4574]
**Reported by surfer0627 on 2014-10-25 17:22**
Hi,
  This is a trivial issue.
Take Internet Explorer for example.
Sometimes, I press ctrl+alt+arrow, which will rotate my screen. But, I could not reproduce it every time.

== Screen rotation commands:
Press one of the arrow keys while pressing ^ Ctrl+? Alt. The left arrow and right arrow keys will rotate the screen 90 degrees.
The down arrow key will flip the screen upside down.  
The up arrow key will return the screen to normal. 
# 

I don't know the screen orientation, so I use the following steps to check.
1. Open the Control Panel, choose Display.
2. Choose Change display settings.
3. Look for the Orientation drop down menu, and select the orientation mode I want.

Thanks.

**Comment by josephsl** [comment]
Hi,

Coming back to this issue...

Figured it out: you need to look for WM_DISPLAYCHANGE message. In order to determine if this is primary or secondary orientation, we need to use Windows API to retrieve relevant data structure.

Solution algorithm:

1. Use a custom window and define message processing routine.
2. Look for WM_DISPLAYCHANGE message.
3. If x is greater than y, we're in landscape, otherwise portrait.

Use cases:

1. Tablet orientation: some would use their tablets in portrait mode, and it would be handy to have this announced.
2. Display driver hotkey: Intel ones do have Control+Alt+arro keys defined to go set screen orientation (you can disable this).

Questions before committing:

1. Where: where should we define a custom window to handle this event? I was originally going to use touch tracker to look for display change message, but given that this will cover everyone, I thought about using another window or an existing message processing window.
2. Reporting primary or secondary mode: should we attempt at fetching the needed data structure in order to report primary and secondary modes? This would be most useful for slates (such as Surface Pro 4, Dell Venue 8 and similar devices).

I've assigned "good for new dev" as this is quite trivial to implement and would teach new developers how to process window messages and to think about general versus specialized solutions. Thanks.

**Comment by jcsteh** [comment]
We already have a message window which uses windowUtils.CustomWindow. We could just use that to listen for these messages. See core.py at around line 249. It doesn't currently have a windowProc method, but I'm happy for one to be added. This does look a bit odd because it's defined in the middle of core.main, but we only do this so we can import windowUtils late.

**Comment by surfer0627** [comment]
My friend told me a temporarily solution to prevent screen rotation.

'''disable the shortcut key'''
1. Press win+b to move to system tray.
2. Press down arrow to find your device. (E.G Intel(R) HD)
3. Press applications key to open menu.
4. Press down arrow to find "graphic options".
5. Press down arrow to find "shortcut key".
6. Choose "disable".

Notes: 
I'm not using English interface, maybe, the menu item expressions are incorrect.

**Comment by josephsl** [comment]
Hi,

For PR writers: Enhanced Touch Gestures add-on has a basic implementation for this feature. As noted in #4612, I recommend combining custom window issues into a PR package (preferably separate commits for each issue). Thanks.

**Comment by derekriemer** [comment]
@jcsteh, or someone with committer rights, can you make this b e blocked by #64612 and #6320
