### ISSUE TITLE
Add a run new version to the portable updater

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4595]
**Reported by briang1 on 2014-11-04 15:45**
When you are running a portable version, in which you have a customised espeak voice,  and it prompts you to update, the installer will default to running with the default voice of nvda. However, when you have done the update and it has copied its files to the location you browsed to, unless the machine has a shortcut already set up to that location, you are left with the default voice on the running copy.
 What would be nice would be an option to run the freshly updated portable copy.
 The updater knows where this is, as its just copied the files to it. It would save a lot of time if it could be configured to run the new version instead of the installer.

**Comment by leonardder** [comment]
This was implemented as part of #6329, probably missed this issue when filing the pr. Closing.

**Comment by Brian1Gaff** [comment]
Yes interestingly I never use it now due to its quirkyness, but as we know 
there is a ticket/issue for all two of us who have this problem, but it also 
affects installed copies now of course.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
