### ISSUE TITLE
Ability to optionally hear typed characters in a password protected feald

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4624]
**Reported by Agent Golder on 2014-11-14 13:05**
Would be usefull a setting to be implemented, like the Symbian screen readers have it already.
A check box in some NVDA's dialog for example.

**Comment by ehollig** [comment]
Marking this as feature.

**Comment by ruifontes** [comment]
For me, it is better as it is now, since exists an addon to do that...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 15 de agosto de 2017 02:04
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ability to optionally hear typed characters in 
a password protected feald (#4624)



Marking this as feature.

**Comment by ehollig** [comment]
For reference, here is the [Speak Passwords addon](https://addons.nvda-project.org/addons/speakPasswords.en.html)

**Comment by Adriani90** [comment]
I am closing this as won't fix. Sighted people are also not seeing the letters on the screen in proper password fields and in an corporate environment whis feature would raise serious security questions. There is an addon for who ever wants to have this feature though.
If you have other arguments, please comment on it and we could reopen the discussion if needed.
