### ISSUE TITLE
focus jumps to the NVDA window when an item is pressed in the Elements list dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4648]
**Reported by blindbhavya on 2014-11-29 09:03**
Hi,
This is a very strange issue.
What happens is that when any item is hit Enter on in the Elements dialog, instead of remaining in the same document from where the link/heading/item was obtained, the item does get activated, but focus jumps to the NVDA window.
ALso, why is there sometimes an NVDA window (a window is that what comes n the way while Alt Tabbing) and sometimes not?

**Comment by ehollig** [comment]
I have not seen this problem in a very long time using Windows 10 or 8.1. @bhavyashah, are you still experiencing this problem on occasion or does it still happen on Windows 7? CC @jcsteh for any technical input.

**Comment by bhavyashah** [comment]
I no longer use a Windows 7 system, since my primary machine runs
Windows 8.1 64 bit, on which, I do not believe I have experienced this
issue in the past several months, at the very least. Feel free to
close.

On 7/27/17, Ethan Holliger <notifications@github.com> wrote:
> I have not seen this problem in a very long time using Windows 10 or 8.1.
> @bhavyashah, are you still experiencing this problem on occasion or does it
> still happen on Windows 7? CC @jcsteh for any technical input.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/4648#issuecomment-318405016


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750
