### ISSUE TITLE
add an second (european name of the seika braille displays in the user guide)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4697]
**Reported by zstanecic on 2014-12-15 20:11**
There is an european term /name for the all seika braille display, can we separate these two names by a slash sign?
the second name is "Touchme".
This will help the european users that they are using the right display with NVDA.
This change is also good to be applied in the braille settings dialog, in the list of the braille displays.

**Comment by ehollig** [comment]
This sounds like a quickfix, is this still relevant to European users?

**Comment by ruifontes** [comment]
For Portugal don't make sense, since it is known only by Seika...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 19 de agosto de 2017 01:23
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] add an second (european name of the seika 
braille displays in the user guide) (#4697)



This sounds like a quickfix, is this still relevant to European users?

**Comment by zstanecic** [comment]
For croatia it has sense.
It’s sold as mini toucme braille

Od: ruifontes
Wysłano: sobota, 19 sierpnia 2017 02:33
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] add an second (european name of the seika brailledisplays in the user guide) (#4697)

For Portugal don't make sense, since it is known only by Seika...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 19 de agosto de 2017 01:23
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] add an second (european name of the seika 
braille displays in the user guide) (#4697)



This sounds like a quickfix, is this still relevant to European users?

**Comment by zstanecic** [comment]
Well, for croatian use
Rs it’s relevant because it’s tou
Chme or mini touchme
Because there is a notetaker like device from seika
I don’t know if it’s supported by
 NVDA


Od: Ethan Holliger
Wysłano: sobota, 19 sierpnia 2017 02:23
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] add an second (european name of the seika brailledisplays in the user guide) (#4697)

This sounds like a quickfix, is this still relevant to European users?

**Comment by bhavyashah** [comment]
CC one of our resident European users @Adriani90

**Comment by seanbudd** [comment]
I believe this needs to be fixed by translators. If a language / region has a different name for these devices, the translators should translate to that name in their copy of the User Guide. I would suggest emailing the relevant translators, or the translator mailing group with suggestions.
