### ISSUE TITLE
unnecessary announcement while pressing Shift Tab from the Find dialog box in Microsoft Word 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4704]
**Reported by bhavyashah on 2014-12-17 06:23**
Steps to reproduce
1.  Open Microsoft Office Word 2007.
2.  Launch the Find dialog box by pressing Ctrl + F.
3.  Press Shift Tab once and listen to what NVDA says.
Expected Result: NVDA would say ‘tab control find’or ‘tab control Find and Replace dialog’
Actual Result: NVDA says ‘tab control find find and replace dialog’
N the actual announcement, ‘find’ is said twice.
Additional Note: In the Replace dialog (Ctrl + H), something similar happens, NVDA announces ‘tab control replace find and replace dialog’
Hope I was clear enough.

**Comment by bhavyashah** [comment]
@michaelDCurran (Microsoft Office expert) Is the diagnostic information already provided sufficient for you to be able to do what you do? If not, I would like to sincerely request @Qchristensen to intervene by filling any blanks that I may have left, since I believe Quentin has a copy of Office 2007, while I only have Office 2010 on my system.

**Comment by Qchristensen** [comment]
Ok, I know what's happening here.  The confusion is that it probably shouldn't be announcing the dialog name when you press shift+tab.  Once you take that out (or ignore it), it's easier to interpret what is being reported.

The "Find and replace" dialog, has three "tabs", one for "find", one for "replace" and one for "go to".  Whichever one opens depends on which keystroke you used (control+f, control+h or control+g).  The focus starts in the edit box (either "find what" for find or replace" or "enter page number" for go to).

When you press shift+tab, it moves the focus to the tab control where you can arrow between "find", "replace" and "go to".  NVDA is simply announcing this:

"Tab control  Find" - telling you that the focus is on the tab control, and the selected item is "find" (as opposed to replace or go to).
"Find and replace dialog" - stating the name of the dialog.  Arguably this may be unnecessary at this point since the dialog hasn't changed.

Pressing NVDA+tab at this point reports "Find and replace dialog, focused", where it should report the tab control rather than the dialog.

The next step would be for someone to look at the code and work out why the dialog name is being announced at this point and whether it is easy to stop it from being announced.

For reference, I checked the dialog which appears when you insert (or customise) either a table of contents, index, table of figures or table of authorities.  Press alt+s, x to open the insert index dialog.  The focus in this case starts on the tab control, but if you press tab, then shift+tab back to the tab control, only the current tab is announced (not the dialog).  Pressing NVDA+tab at this point reads "tab control, index focused".

**Comment by derekriemer** [comment]
Okay, so focus is being placed on the dlg, not the tab control.

**Comment by josephsl** [comment]
Hi, at this point, I think it’d be best to mark Office 2007 issues as “wontfix” as support for it has ended unless there are folks still using it for critical tasks. Thanks.

**Comment by Qchristensen** [comment]
I can still replicate in Word 2007 still, but not Word 365.  Since it's most likely that it was Microsoft who fixed the dialog reporting at some point rather than anything we did, and they're not about to fix anything in Office 2007, the question becomes, is it worth us monitoring whether a user is in this dialog in Word 2007 and suppressing the dialog name from being reported when moving focus to the tab control.  My feeling is that the dialog itself still works fine, therefore, it's probably not worth the development time at this point.

If someone wants to tackle it and put in a pull request, feel free to reopen and submit.
