### ISSUE TITLE
Word forms with Legacy controls should speak forms label while tabbing through a form.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4709]
**Reported by csm120 on 2014-12-17 17:22**
The attached word doc doesn't speak properly with NVDA. This is because help text hasn't been provided. Is it possible for NVDA to get the form's label and speak that?

**Comment by bhavyashah** [comment]
From the last couple comments, I get the impression that the original author of this ticket, in @jcsteh's words himself, was "just hoping for some heuristic that can "guess" the label from the text". While this guesswork, as @jcsteh subsequently explained, could be potentially inaccurate in case of legacy Word controls as well as on the web, we should do either of the following to proceed with this ticket:
* Locate a duplicate ticket, if one exists, concerning control label guessing heuristics in particular
* If none exists, retitle/morph this ticket so as to relate only to heuristics for guessing control labels

**Comment by bhavyashah** [comment]
@Adriani90  I reviewed the thread and you are completely correct. My previous comment was wrong - please ignore it. For what it's worth, the provided test case's URL now takes you to a "This item might not exist or is no longer available - OneDrive" page. Also, I wonder if Word UIA changes things at all.

**Comment by Adriani90** [comment]
UIA makes it even worse to work with such legacy forms in MS Word. I think creating forms in Office 365 at least is better, so hope that those very old documents do not exist for a longe time from now. :-)

As for this issue, I am closing as abandoned, because the test case link provided by @csm120 doesn't work anymore, and we don't have a clear description with steps to reproduce.
If you are still having this issue, please open a new one and fill the coresponding template.
