### ISSUE TITLE
While running NVDA, Hindi Character "े" is not getting typed/sent to the windo

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4711]
**Reported by akash11501 on 2014-12-19 12:39**
Hello Mick and Jamie,
I'm developing an application, whose task is to do braille input in Hindi and english, as you've developed BrailleInput Addon.
but that will work with every screen reader/ without screen reader too.
I'm not taking any help of braille table or so on in my application, I'm following a different approach.
so, my problem goes like this, (This is problem is not with any other screen reader/without any screen reader, with all screen readers it's working fine, except NVDA)
so, every key combination is working fine, but Hindi "े" is not working. steps to reproduce:
Launched delight braillify with JAWS or any other screen reader, and tried pressing combination 1&5(Keys F and K)
this time, the character was Hindi "ए" and it typed fine, again pressed the same dots(1&5) this time, due to Hindi rules, this was another Hindi Character: hindi "े" and it also worked fine. now quitted jaws and started NVDA/Launched Braillify with NVDA.
No again pressed the combination (1&5) as first time and Hindi ठए" typed/sent to the window successfully.
now again pressed dots 1&5 and according to Hindi rules, now the Character should be sent "े", but no, it didn't sent anything, it spoke the character, but didn't sent to the window.
this problem is with only NVDA, please look at it, I'm attaching my Binaries and NVDA Log set to input/output with the ticket.

**Comment by bhavyashah** [comment]
Since we do not have any means to get in touch with the original reporter of the ticket (except his e-mail address, which I may can share upon request) and user 'dhankuta', who, I believe, was Him Prasad Gautam, is unfortunately no more, can we safely close this issue? For your information, the final product that Akash was developing is BrailleSpark (www.akashk.in) and and the reported bug has not been discussed anywhere with regards to the public release, leading me to believe that this problem may not even exist anymore. @michaelDCurran @feerrenrut

**Comment by leonardder** [comment]
@bhavyashah: I think especially your last point is a sufficient rationale for closing this. If this is still an issue, anyone who desires so can request a reopen.
