### ISSUE TITLE
add buttons in Type grouping option in Elements List for Skype

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4724]
**Reported by bhavyashah on 2014-12-20 14:10**
There are too many buttons in Skype, none of wich (or perhaps most of which) do not have a keyboard accelerator/shortcut key.
Therefore, I propose adding 'buttons' in the Type grouping option in Elements List dialog for Skype.
Buttons should only be included in the Elements List for Skype, including it in the Elements List universally is not needed, or at least that is not what I'm requesting.
Hope I was clear enough

**Comment by Adriani90** [comment]
@jcsteh in the new skype I think browse mode is not possible at all. Right?

**Comment by josephsl** [comment]
Hi, which Skype version – desktop or universal? We need to make that distinction clear at this point. Thanks.

**Comment by Adriani90** [comment]
@ruifontes could test with your kypes please? Unfortunately I am not so familiar with the new skypes. Thanks.

**Comment by k-kolev1985** [comment]
In Skype 8 for desktop, browse mode is possible. In Skype for Windows 10 from the Microsoft Store, browse mode is not possible (or at least cannot be activated with NVDA+Spacebar).

**Comment by jcsteh** [comment]
Buttons were added to the Elements List a while ago. You can already make use of this in Skype for Desktop, since browse mode is possible there.

Browse mode isn't possible in the Skype Windows Store app. However, I don't think that is a feature request specific to Skype; there are more general requests related to browse mode in things other than web frameworks. As such, I'm closing this.
