### ISSUE TITLE
When press arror keys in treeview, NVDA will announce the last selected item then the current item.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4747]
**Reported by vgjh2005 on 2014-12-24 02:47**
Hi:
This problem is the same in treeview at eclipse. I made test in flashxp. Thanks!

**Comment by leonardder** [comment]
@vgjh2005: Could you provide a status update for this issue?

**Comment by Adriani90** [comment]
@@vgjh2005 since this is a very specific issue, could you please test again and give us an update if the issue is still occuring? Thanks. I will let this issue open for some further weeks and will close it if the author is not responding. I didn't hear any related reports on this issue on user lists etc.

**Comment by Adriani90** [comment]
Closing due to missing updates.
