### ISSUE TITLE
Open file explorer from application window, press arrors key sometimes will not read the listview  on windows 7 64bit.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4870]
**Reported by vgjh2005 on 2015-02-01 19:23**
Hi:
Using internet download manager finished a file downloading, then press open its folder when downloading finishing dialog is apeared. Press arrors key to read the listview, nothing will be read. This bug is still existed for long time. Thanks!

**Comment by ehollig** [comment]
@vgjh2005, is this still the case for you? If so, could you provide more information as requested in https://github.com/nvaccess/nvda/issues/4870#issuecomment-155334157

**Comment by vgjh2005** [comment]
Hi:
I am using windows 10. It is still a case. Please running NVDA in high CPU usage environment. For example play a biggest game, running more application at the same time etc. Thanks!

**Comment by Brian1Gaff** [comment]
Is this just a slugging ie, slow down or an actual non working condition, as 
there seems to be a history of lag in this situation due to the  processor 
not speeding up when demand is obviously high, resulting in poor response 
times to cursors and other keys. I found it less annoying in list mode than 
in there views. The only true fix was to crank up the processor which I 
fully realise is not a good thing if its a laptop on battery.

I guess what I'm saying is that is this the well known issue or something 
else. I've tried running loads of stuff including registry compactors to 
increase processor use, but it only slows, never actually stops for me in7 
64.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@vgjh2005 I had a similar bug until Windows 10 1709 Update. after that in disapeared. Can you still reproduce it with Windows 10 1809 Update?

**Comment by vgjh2005** [comment]
Hi:
yes.

**Comment by Adriani90** [comment]
@vgjh2005 how is this now with NVDA last alpha version on Windows 10 22 H2 update?

You can download the last alpha version at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more than 3 years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
