### ISSUE TITLE
displaying font information in a virtual message will be helpful.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4908]
**Reported by sumandogra on 2015-02-12 07:16**
NVDA needs to have A virtual message window displaying all the font information.
 

With NVDA+F, NVDA gives information about font but there is no way one can read through the font information.  This information is helpful for those who have a lot of information related to font important for them during proofreading and formatting a document.
Suggestion:  this can be introduced in the form of a dialog that can be closed by just ESC.

**Comment by nvaccessAuto** [comment]
Incubated in cd5ba7031fe26f1e26d087e6202b9d7b6d9a5543.

**Comment by jcsteh** [comment]
Pull request: #5593.

**Comment by nvaccessAuto** [comment]
Incubated in 92a1bcdbe10028602d1eb59863f389c0ed50f54d.

**Comment by leonardder** [comment]
It slightly puzzles me why this functionality is implemented this way with a HTMl template. Honestly, I prefer an implementation as proposed by Joseph in comment 4

**Comment by leonardder** [comment]
Also found a little bug in here:

STR:
1. Press nvda+f twice to get the formatting info dialog
2. Press tab
3. Press alt twice to open and close the menu bar
Result: An error is generated
```ERROR - unhandled exception (21:15:44):
Traceback (most recent call last):
  File "wx\_misc.pyc", line 1367, in Notify
  File "wx\_core.pyc", line 16869, in Notify
  File "core.pyc", line 474, in _callLaterExec
  File "IAccessibleHandler.pyc", line 820, in _fakeFocus
  File "NVDAObjects\__init__.pyc", line 259, in objectWithFocus
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 188, in findBestAPIClass
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 444, in kwargsFromSuper
AttributeError: 'NoneType' object has no attribute 'nodeName'```

**Comment by jcsteh** [comment]
> It slightly puzzles me why this functionality is implemented this way with a HTMl template. Honestly, I prefer an implementation as proposed by Joseph in comment 4

Using HTML allows for content other than just text; e.g. links, headings, etc. I don't see a disadvantage with this approach using plain text; you can still just press escape to close it.

**Comment by dineshkaushal** [comment]
I found the cause of the problem. I had set tabindex=-1 for body in message.html, so the focus was not getting there. The fix is to set tabindex=0.

I tried to checkout branch t4908, but could not find it. Making changes in in_t4908 is difficult as you made some changes after taking code from there.

Please suggest what should be done?

**Comment by jcsteh** [comment]
The branch is called i4908 in the nvaccess/nvda repository. We use "i" 
for issue now instead of "t" for ticket.

**Comment by sumandogra** [comment]
I tested with the test build given with the fix. the issue is with tab and alt key is not present now and is fixed.

**Comment by nvaccessAuto** [comment]
Incubated in 0feb4fe5ec727bdf5b9d1fc4795eeb08348d323f.

**Comment by derekriemer** [comment]
Just a thought. Should we hash and store the hash of the message.html file in the python code? This way it is resistant to tampering. Otherwise, could it be somehow packaged somewhere where someone couldn't mess with the HTML document as easily? My concern (not that big of a deal really) is that someone could replace the message.html file on the fly in someones NVDA install, and then they could cause the message to present interesting things. For a proof of concept, go to NVDA's installation directory, (bad if it is on an external usb drive because this isn't admin privlages required), and add this code.
```javascript
<script> function windowOnLoad(e){document.body.innerHTML = "proof of concept self distructing evil file.";}
function escapeKeyPress(e){document.location = "http://nvaccess.org";}
</script>
```
It is not a huge vonerability though.

**Comment by jcsteh** [comment]
Someone could certainly do this, yes. However, they could also just replace a dll, executable or some other file. Unless I'm missing something, there's nothing particularly special about this file. If we're worrying about someone replacing this, one must equally worry about any file being replaced anywhere for any app.

**Comment by derekriemer** [comment]
Yeah. That's a good point.

**Comment by derekriemer** [comment]
Also, the virtual message only uses internet explorer when a link is pressed. Is this known behavior?

**Comment by leonardder** [comment]
Found another little bug. When rpessing nvda+f more than twice, multiple formatting windows are opened. Hold instert and press f four times, for example.

**Comment by derekriemer** [comment]
In that case, it turns out that NVDA is opening a font window to display 
font information (which just happens to be available) for the font 
information. This works out because this is a mshtml control (I believe) 
and NVDA supports retrieval of font information in those.

On 3/14/2016 9:30 AM, Leonard de Ruijter wrote:
>
> Found another little bug. When rpessing nvda+f more than twice, 
> multiple formatting windows are opened. Hold instert and press f four 
> times, for example.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/4908#issuecomment-196369022>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
> Also, the virtual message only uses internet explorer when a link is pressed. Is this known behavior?

Ug. That's kind of annoying. I suppose it makes sense; this function actually uses IE behind the scenes to render the HTML. The question is whether there's any way we can force it to use the shell to open external URLs. @Dineshkaushal, can you look into this?

> Found another little bug. When rpessing nvda+f more than twice, multiple formatting windows are opened. Hold instert and press f four times, for example.

The code displays the window if there was more than 1 press. We should instead explicitly make this 2 presses.

**Comment by derekriemer** [comment]
@jcsteh
I believe this also has to do with the fact that font info can appear 
for font-info window. To reproduce:

1. Press nvda+f twice somewhere.
2. In the window, press NVDA+f twice. It pops up font info for the 
font-info page.
3. Pressing NVDA+f twice again produces more font-info for the font-info 
window that displays font info for the window that you originally 
requested font-info for.
(that was a complex sentence, please excuse my non-brevity).

On 3/15/2016 5:00 PM, James Teh wrote:
>
>     Also, the virtual message only uses internet explorer when a link
>     is pressed. Is this known behavior?
>
> Ug. That's kind of annoying. I suppose it makes sense; this function 
> actually uses IE behind the scenes to render the HTML. The question is 
> whether there's any way we can force it to use the shell to open 
> external URLs. @Dineshkaushal <https://github.com/Dineshkaushal>, can 
> you look into this?
>
>     Found another little bug. When rpessing nvda+f more than twice,
>     multiple formatting windows are opened. Hold instert and press f
>     four times, for example.
>
> The code displays the window if there was more than 1 press. We should 
> instead explicitly make this 2 presses.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/4908#issuecomment-197060974>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Sure, but I don't consider this to be a bug. If you want formatting info 
for your formatting info, that's your business. It's a valid (if stupid) 
use case. Unless you can give me some reason it isn't valid...

On the other hand, opening another dialog when you press it three times 
is not valid, since it's only documented to do it when you press it 
twice. It's also more likely to be accidentally triggered due to a 
finger slip or the like.

**Comment by derekriemer** [comment]
I was just mentioning the fact that it exists because I'm pretty sure that's what you were referencing when you were quoting it. It had looked like you had misquoted it but maybe I misunderstood what you wrote. Sorry
I would also argue that it is not a book as well.

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by leonardder** [comment]
Shouldn't we actually just block people from opening multiple formatting 
information windows in a simlar way we do with configuration dialogs?

**Comment by jcsteh** [comment]
Well, stuff other than formatting dialogs could use browseable messages, 
so that question has to be broadened to any browseable message. 
Honestly, I don't know if there's scope for allowing multiple messages 
to be open at once. It doesn't seem like we should block it just for the 
sake of it.

Multiple settings dialogs are only prevented because settings can depend 
on each other. For example, if you open both Voice Settings and 
Synthesizer, change your synthesizer and then try to use the Voice 
Settings dialog, things will be broken because Voice Settings doesn't 
know about the synth change (#603).

**Comment by leonardder** [comment]
I see your point. However, multiple formatting windows create confusion 
about what window is for what formatting. Couldn't multiple formatting 
windows be disabled regardless of other browsable messages?

**Comment by jcsteh** [comment]
Because the formatting dialog is (and must be) modeless, it isn't 
trivial to prevent more than one dialog. In fact, I'm not even sure 
whether there's a way to get a callback from that dialog when it closes.

**Comment by tspivey** [comment]
Why does this say formatting 2 or 3 times?
```
IO - inputCore.InputManager.executeGesture (19:48:49):
Input: kb(laptop):NVDA+f
IO - speech.speak (19:48:49):
Speaking [u'Dark Gray on Black']
IO - inputCore.InputManager.executeGesture (19:48:49):
Input: kb(laptop):NVDA+f
IO - speech.speak (19:48:49):
Speaking [u'Formatting']
IO - speech.speak (19:48:50):
Speaking [u'Formatting']
IO - speech.speak (19:48:50):
Speaking [IndexCommand(1), u'Dark Gray on Black']
```

**Comment by nishimotz** [comment]
The 'center' option for HTML dialog is specified, however, the actual dialog position is not center on screen.
"center:desktop" seems work.

```
diff --git a/source/ui.py b/source/ui.py
index c91d0d0..862c782 100644
--- a/source/ui.py
+++ b/source/ui.py
@@ -23,7 +23,7 @@ import braille
 URL_MK_UNIFORM = 1

 # Dialog box properties
-DIALOG_OPTIONS = "dialogWidth:350px;dialogHeight:140px;resizable:yes;center:yes;help:no"
+DIALOG_OPTIONS = "dialogWidth:350px;dialogHeight:140px;resizable:yes;center:desktop;help:no"

 #dwDialogFlags for ShowHTMLDialogEx from mshtmhst.h
 HTMLDLG_NOUI = 0x0010
```
