### ISSUE TITLE
speak typed words in internet explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4958]
**Reported by JamaicanUser on 2015-03-02 15:47**
I don't know if this is a duplicate. 
For the longest while now, while using Internet Explorer (not Firefox), while using the browser with speak typed words enabled, there are very annoying problems:
If I make a mistake, and I correct it, then complete the word by pressing space or punctuation, I get speech that speaks as if I didn't press the backspace key.
Look at this example, using Windows 7 with IE 11 (although I have used Windows 8, 8.1 and XP and similar results occur)
1. In forms mode, type something like "frog" but don't press space.
2. Act like you made a mistake, clear the "-og" and replace with "-om"
Expected result after pressing space: from
Actual result: frogom

**Comment by jcsteh** [comment]
Another case of #2586/#3231. A similar fix can be used, but unfortunately, we have to do these case by case.

**Comment by Adriani90** [comment]
Support for Internet Explorer has completely ended in 2022, and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I am closing this as abandoned, since i don't expect any further accessibility updates to IE or to the Internet Explorer  mode in Edge.
As Jamie pointed above, this needs to be fixed case by case, so open new issues for other cases in case you encounter any.
