### ISSUE TITLE
Allow jumping past end of container elements in Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4962]
**Reported by Diego on 2015-03-07 18:02**
Hello developers!
In browse mode, you can jump tables, lists, frames using the comma key.
I would suggest that this can be implemented in the word.

**Comment by leonardder** [comment]
Lists are unsupported in Word quick navigation, but support for them might be added in #7409 for Word 2016. As for tables, it would help if jumping out of it would work, indeed. CC @MichaelDCurran

**Comment by bhavyashah** [comment]
@leonardder In https://github.com/nvaccess/nvda/issues/4962#issuecomment-315731419, you refer to lists and tables. Since the ticket body also explicitly mentioned frames as a container to the start or end of which the original author of this ticket would like to jump, do you have any inputs on NVDA and Word's support for frames, similar to your analysis of lists and tables?
Actually, wait. I am already able to move to the start and end of a table using , and Shift+, in Word browse mode for a simple 2x2 table in Word 2010 and NVDA 2017.3 on a Windows 8.1 system. Is this ticket exclusive to later versions of Word, or am I missing something else?

**Comment by derekriemer** [comment]
yeah, worksforme
Wait, are you sure jump to list doesn't work?

**Comment by bhavyashah** [comment]
Pressing "l" causes NVDA to say "not supported in this document" and
pressing "," when in a bulleted list causes NVDA to say "not in a
container".

On 10/13/17, Derek Riemer <notifications@github.com> wrote:
> yeah, worksforme
> Wait, are you sure jump to list doesn't work?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/4962#issuecomment-336411754


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by Adriani90** [comment]
navigation out of table works in MS Word just fine. It should also works for stuff like i.e. list of contents. But I think normally if you create a list by adding a bulet and pressing enter this is not a container list. You have to explicitely create a list of contents or something like that to have it as a container. Having aid that, this issue is a works for me. If you still have issues with this please comment on it and we can reopen it.
