### ISSUE TITLE
Cdex is not beeping in background or foreground  progress bars

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#500]
**Reported by scottbb on 2009-12-07 02:46**
When using Cdex there is no beeping for the background progress bar.

**Comment by leonardder** [comment]
@Brian1Gaff: Assuming you were briang1 in the past, could you give a status update on this?

**Comment by ehollig** [comment]
@Brian1Gaff, just a friendly reminder to respond to @leonardder in https://github.com/nvaccess/nvda/issues/500#issuecomment-307867494. If it is the case that there are no foreground progress bars, you may have to report this to the developers of Cdex

**Comment by Brian1Gaff** [comment]
I once again never saw this email alert that this old ticket had new 
comments, so apologies.
 Certainly I have found recent versions of Cdex are actually more awkward to 
use than the old one was, so I have gone back. The lack of bleeping can 
sometimes be slightly less annoying if you use object nav in certain cases.
 I have not attempted to try the very latest update of this software due to 
bad experiences with the first couple after development restarted.
 If nobody else is bothered, then close it and if need be we can create a 
new one later on.
 Everything else seems to work. Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
When I perform a search for Cdex, I am unable to find any issues aside from this one. If this is still an issue with the latest update of this software and it is an NVDA issue, please create a new issue. If the problem is not the fault of NVDA, please contact the developers of the software. Closing as requested
