### ISSUE TITLE
Problem with capital letter mark

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#505]
**Reported by werwoelfchen on 2009-12-09 10:06**
Since Snapshot R3422 the braille display doesn't show any longer the capital letter marks. It would be good if one could dis- or enable these marks by using the braille settings menu.

Text in German:
Betreff: Problem mit Großbuchstabenzeichen
Beschreibung:
Seit dem Snapshop R3422 zeigt die Braillezeile keine Großbuchstabenzeichen mehr an. Es wäre gut, wenn man dies ein- oder ausschalten könnte, indem man das Menü "Brailleeinstellungen" benutzt.

**Comment by dkager** [comment]
CC @egli
This seems to be done on purpose. Is this the preference of German readers?

Maybe NVDA could gain an option to suppress capitals. SuperNova has this too IIRC. The clean solution requires an option in liblouis. A hacky solution could be to transform all text to lowercase before translation. The problem is that German grade 0 does show a capital sign for two or more consecutive capitals. So clearly it's not so straight-forward.

**Comment by bdorer** [comment]
This feature is wanted from many German Braille Readers. Some of them 
are using Grade 2 to proove reading so if you'll find a solution it 
would be great.
Some persons created their own braille tables with capital letter mark 
enabled but they have to restore the table after nvda updates.


Am 08.06.2017 um 20:26 schrieb Davy Kager:

**Comment by dkager** [comment]
See https://github.com/liblouis/liblouis/issues/363.

**Comment by bdorer** [comment]
Separate Tables with and without caps letters will blow up braille 
tables list but if there isn't any better way we'll accept it.

Am 27.06.2017 um 20:07 schrieb Davy Kager:

**Comment by dkager** [comment]
Then again, German is the only table I've seen *without* capitals.

**Comment by egli** [comment]
I think our resident braille expert created the tables w/o caps letters because we produce most braille without. 
But what's the problem with just adding another table? In what way will it "_blow up the braille tables list_"?

**Comment by leonardder** [comment]
> I think our resident braille expert created the tables w/o caps letters because we produce most braille without. But what's the problem with just adding another table? In what way will it "blow up the braille tables list"?

Even if most braille is produced without capital signs, if a braille spec contains them, they should be included in the braille table by default. Probably better to discuss this in liblouis/liblouis#363.

**Comment by bhavyashah** [comment]
The impact of this issue is limited to the intersection of (a) Braille users, (b) German users. Doing some research on the German language, let me share some of what I found. Austria and Germany, both of which have German as their official language, cumulatively account for a third of German speakers worldwide. According to NVDA User Statistics, Germany and Austria together account for 1.3% of NVDA users. Thus, it can be extrapolated that roughly 3.9% of NVDA users are German speakers. According to WebAim Screen Reader Survey #8, 3.9% of respondents reported that they relied primarily on Braille output and they neglected to ask about using Braille in combination with visual or audio output. Even if we assume that 20% of screen reader users use Braille to some degree, we still have our German Braille users constituting well under 1% of the total user base. Therefore, given the small proportion of the impacted audience, this ticket should be assigned a low priority.
P.S. Some crude calculations in there, but I think the general picture is suggest is accurate. Not sure why I am cerebrating so much about impact calculation. 😂

**Comment by Adriani90** [comment]
@bhavyashah even though the statistics show this number, this was the current user respondents at that time. This changes over time and not to forget that most users using braille displays come from western countries such as germany, france and so on. Most braille contributions come from such countries. So this should not be neglected.
Moreover, by the way switzerland belongs also to german speaking community, as well as many other countries where people might have to learn german in the school. Not to forget imigrants who move to Germany or similar countries which is very comon in a globalized world. I know at least 10 blind people who came to Germany from abroad and try to learn german. For such people it is important to keep in mind the issues they are having.
Anyway, I think this issue needs to be fixed in Liblouis, I don't think NVDA can do anything about this. But we can track the progress here.

**Comment by Adriani90** [comment]
@BueVest now that the bidirectional talbes for german are integrated in NVDA, do you see this issue as solved?

**Comment by dave090679** [comment]
Hey all,

Since nvda has the "detailed braille translation tables" integrated, the capital letter marks are displayed correctly. ... BUT: In some Cases, NVDA crashes when the detailed braille translation table is used. 


Steps to reproduce:
1. open an empty Notepad.
2. in nvda braille settings, select any braille table marked as "detailed". (either "german basic braille (detailed)" or "german grade 1 (detailed)" or "german grade 2 (detailed)".
3. in the notepad, type an uppercase letter followed by a dot (.) and two lowercase letters. Just when you type the secons lowercase letter, nvda crashes. 

There are some exceptions from this "stranger thing":
"A.aa" works properly; "A.ab" also works, "A.ac" also works fine, ... bus "A.ad" brings nvda to crash.

in dayly use, this means that nearly all file names can bring nvda to crash when they are displayed in an explorer list.

**Comment by CyrilleB79** [comment]
@Adriani90 you have followed this issue. Do you think that it is fixed?

Also @BueVest and other users, can we consider this issue fixed?

@dave090679, the initial description of this issue is indicating that braille is not reported as expected by users. What you describe instead is a crash of NVDA. Please open a new issue for this with all related details so that it can be looked at specifically. Thanks.

**Comment by egli** [comment]
> In some Cases, NVDA crashes when the detailed braille translation table is used.

Hi @dave090679 can you reproduce this crash just using liblouis? And then file an issue at the [liblouis issue tracker](https://github.com/liblouis/liblouis/issues)? That would be appreciated.

**Comment by Adriani90** [comment]
The issue as it stands in the description seems fixed. Please open a new issue about the crash with Liblouis and if related, also with NVDA so we can track where it comes from.

I am closing this issue as works for me.
