### ISSUE TITLE
user guide" mention nvda specific activity

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5059]
**Reported by JamaicanUser on 2015-04-27 02:32**
Currently, in the user guide, there is a section that lists the keyboard commands provided by NVDA for specific applications. Why not extend this functionality to include the things that NVDA excels in as it relates to these applications? For example, for Skype for desktop, you can probably mention that NVDA announces typing notifications and other notifications presented to the user. For Word, mention the browse mode function (although it currently has 2 bugs which haven't been addressed yet), for Excel, mention, among other things, the fact that overlapping cells are announced, and that users may encounter problems if row/column headers are not announced. Just an idea, I know it's trivial.

**Comment by leonardder** [comment]
Any thoughts about this? I belief the user guide is ok as it is. I don't think that overlapped/cropped cells should be mentioned in the user guide explicitly. There is already a section about application specific features which covers major things.

**Comment by bhavyashah** [comment]
CC @jcsteh @Qchristensen

**Comment by Qchristensen** [comment]
For Word, Browse mode is documented in the User Guide now, if it wasn't when this issue was raised: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#toc49

The other comments about Skype and Excel raise an interesting point, they are NVDA specific reporting, which is useful for users to know, but unlike most things covered in the user guide, they don't need the user to press anything to use them.  It could be argued then that their explaination would be known to someone familiar with the software (Excel or Skype in this case).  The command to read comments is covered, for instance, asit is an NVDA command, but not that NVDA reports "has comment" when focus moves to a word (or cell) which has a comment.

**Comment by Adriani90** [comment]
@Qchristensen I think this kind of information is quide self explanatory. I mean then we could document also in MS Outlook the whole status informations we get from NVDA but I don't think that this makes sense. Actually the user must be given an approximate orientation on how to use the screen reader in a easy and understandable structure. In my opinion the userguide now is far too comprehensive. I don't think that we will be able to really document completely everything. But as long as the most important principles are covered and the user does not miss any function / feature / setting after reading the userguide, it is ok.
But this is only my opinion.

**Comment by Qchristensen** [comment]
I agree, the user guide is really good to help answer "I know NVDA can do XYZ, and I know how that function works, but I just can't remember the keystroke to press".  Mentioning things like NVDA reporting overflowing text in Excel is more about the feature of Excel itself than what NVDA can do.

We don't mention things like that you can navigate by word in most text fields with control+right arrow, because that isn't something specific to NVDA - it's something that probably a much larger proportion of screen reader users know than sighted users, but is something much more appropriate to mention in the training modules than NVDA user guide.

Browse mode in Word is the one part of the original issue definitely worth including in the User Guide, and that has been in there since before I last looked at this issue in 2017.  I'm going to close this issue, but definitely do please keep suggesting improvements to the User guide!
