### ISSUE TITLE
pauses during say all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5065]
**Reported by JamaicanUser on 2015-04-28 10:36**
Of recent, I have noticed this problem while using say all to read text.
STR
1. Open Notepad or any editable text editor really.
2. Type "Hello, Mr. Teh"
3. Read the current line.
4.  Use say all to read the text. Add another line with "This is Dr. McIntosh." or something just to confirm
5. Notice a difference? The Mr. sounds different in both cases. Why is this so? It happens with eSpeak and Nuance Vocalizer.

**Comment by bhavyashah** [comment]
@jamaicanuser Could you please update us as to whether or not this bug still stand?

**Comment by Adriani90** [comment]
I know that code factory vocalizer voices have issues with say all in NVDA. I suggest to report this to code factory. Vocalizer voices from tiflotechnia do not seem to have this issue.
Regarding eSpeak and the short delay after abbreviation, this is because NVDA interprets it like the end of a sentence. If you insert a new rule in the voice dictionary to force NVDA to read the whole word (i.e. etc. = et cetera), then eSpeak should not pause anymore. Note that if you set the new rule, you must include the dot in the rule. If you include ony etc then the dot will still be interpreted as fullstop.

I will close this issue as works for me regarding eSpeak and needs external fix for vocalizer voices.
