### ISSUE TITLE
Add a new option to define whether NVDA should save the change to the current profile.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5067]
**Reported by vgjh2005 on 2015-04-29 16:47**
Hi:
In my research, users like to create a new profile then make some change to be suitable for the profile's application. So that add this new option  will let the profile system become more complete. Thanks!

**Comment by Adriani90** [comment]
@vgjh2005 if I understand you correctly, you want a hotkey to switch between current profile and standard configuration? If you are using two sound cards and you have multiple profiles, you can also set a specific profile to be triggered manually instead of automatic. In that way you would always start with the standard configuration in your application and you can switch the profile manually.

Is my understanding correct?

**Comment by Adriani90** [comment]
We do not have updates on this issue since more than 4 years and actually in NVDA 2019.2 there is now the possibility to define a key stroke to change between configuration profiles. I am closing this as abandoned since we lost contact to the initial author.
