### ISSUE TITLE
A feature similar to web flexible of jaws

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5073]
**Reported by Diego on 2015-05-01 19:11**
Hello everybody!
I have a suggestion:
A similar use of flexible web of jaws

**Comment by leonardder** [comment]
@JCSTeh: I'm a convinced non-advocate of this functionality in the core of a screen reader, so I'm a bit biased for triage of this. May be you can share an "official" standpoint?

**Comment by Brian1Gaff** [comment]
OK for those of us not familiar with this Jaws feature, would somebody 
explain what it actually does and why?
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by fernando-jose-silva** [comment]
From what I know of the resource, it allows for example:
On a news page I set up jaws so that every time a news is read the focus will jump directly to the news text, so that I can start reading quickly.
On a page I already know very well, I can ask jaws to remove from my view all the links that I know I will not use.

**Comment by bhavyashah** [comment]
In case anyone would like to thoroughly understand what JAWS's flexible web functionality does and how it works from  a UX standpoint, please visit http://doccenter.freedomscientific.com/doccenter/doccenter/rs25c51746a0cc/2012-10-24_WhatIsNewJAWS14-L2/02_JAWS14-NewFeatures-L2.htm.

**Comment by Adriani90** [comment]
This feature is obsolete now that every browser including Firefox, Chrome, Edge, Brave and Opera provides a reader mode. This lets you make all the interactive elements such as links etc. disappear, so that only the readable content such as the main body with plain text, headings, grafics etc. remains on the screen. This is much more intuitive than the feature implemented by Jaws.

The other part of the request
"having a feature to define a position where NVDA starts the virtual document when opening a page"
is an overkill and not really user friendly. Website designs change dynamically nowadays, so defining a static position will be lost after a while and you will have to adjust it very often when visiting a website.
Also having such a feature will most probably introduce performance issues, for example when you define a certain position where the website would have to be scrolled down a lot after loading. NVDA would have to do this automatically on every page load.
I would recommend rather to use landmark navigation or navigation by region in browse mode, or any other quick navigation command, to find your way through the website. This makes it much easier to understand the structure of the website.

Having said that, I close this request as invalid. If the community insists on ahving such a feature, please comment with use cases and further arguments, then we can reopen.
