### ISSUE TITLE
There are four punctuation marks in Persian Language which are not spoken via NVDA with espeak SAPI5 This happens while navigating either character by character or typing. However, these are treated correctly while reading a sentence.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5092]
**Reported by shadyar on 2015-05-14 12:04**
Hello

There are four punctuation marks which are not spoken
via NVDA with espeak SAPI5 This happens while
navigating either character by character or typing. However, these are
treated correctly while reading a sentence.
In more tests, I noticed that only 
ـ 
is not spoken while using JAWS
with espeak SAPI-5. However, while using NVDA with espeak SAPI-5, all
four reported characters are not spoken.
The same problem exists in both Windows 7 and Windows 8.1
that is why I guess that part of the problem in
،
؛
؟
is related to NVDA, and while the problem in ـ 
ـ
is related to espeak itself.

the Explanation about mentioned characters:
، (equivalent to , in English)
؛ (equivalent to ; in English)
؟ (equivalent to ? in English)
ـ (this character is just used for illustration and to prettify the
text; it should be ignored in the Text to speech process).

Would you mind investigating this issue?

Best,

Shadyar Khodayari

**Comment by bhavyashah** [comment]
Are we in touch with any Persian user who would be able to verify whether this is still the case with ESpeak-NG? If not, I would recommend a close due to the following reasons:
* Any TTS deficiencies cannot be tackled by the screen reader.
* In case of ESpeak-NG at least, their Github project page located at https://github.com/espeak-ng/espeak-ng which has an issue tracker of its own.
* We have no means to contact shadyar and are unaware of whether or not ESpeak-NG is affected by this issue.
@ehollig

**Comment by ehollig** [comment]
CC @josephsl can the translator help in this situation to confirm if this is still the case?

**Comment by ehollig** [comment]
Closing, as I believe this issue has been fixed, testing with NVDA Version: master-14446,e8144a09 and ESpeak voice: Persian.
1. ـ is not spoken when navigating by word but is spoken when navigating by character, but as stated in the original post:
> ـ (this character is just used for illustration and to prettify the text; it should be ignored in the Text to speech process).
2. ،, ؛, and ؟ properly reads when navigating by line, word or character. If this is still an issue, we can reopen.
