### ISSUE TITLE
If reading a word and it contains only a symbol and white space, Read symbol irrespective of symbol level

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5133]
**Reported by sumandogra on 2015-06-02 09:09**
The punctuation marks such as comma are not read with word reading commands until and unless the punctuation marks is set to all in the voce dialog box.  It is suggested to make these punctuations marks read on using word reading and character reading command irrespective of the punctuation marks level, NVDA remains silent on reaching the punctuation   Marks such as comma with word reading command if the punctuation marks is not set to all.

Steps to reproduce:
1.  Open a word document that has many punctuation marks such as commas.
2.  Read the document with word reading command.
3.  On reaching comma, NVDA remains silent.

**Comment by jcsteh** [comment]
P3 because there's an easy workaround (change the symbol level temporarily or move by character if you hear silence when moving by word).

Implementation note: this shouldn't be too difficult. In speech.py, in speakTextInfo around line 853, we check `len(textWithFields[0])==1`. This needs to be changed so that we strip white space from `textWithFields[0]` before checking the length. Note that we shouldn't strip if the text contains only white space, since that would cause, for example, single tab characters to be silenced when moving by word.

**Comment by Adriani90** [comment]
I suggest to close this issue because the user can specify in the symbols dialog on which symbol level NVDA should report a certain symbol. So you can change the reporting behavior for Komma to be reported when you have symbols set to another setting than "all". Note that it works for example properly for dot, percent or dollar sign if you have punctuation to "some". For komma it can be adjusted accordingly.
cc: @jcsteh

**Comment by Qchristensen** [comment]
I'm not a fan of situations where you can move the focus and have NVDA report nothing, as is the case if you control+right arrow through a sentence with a comma (particularly in Word, for instance).  I agree with the proposal to have NVDA report the punctuation where it is the only text to be spoken, even if the punctuation level wouldn't have otherwise had that symbol spoken.
