### ISSUE TITLE
Differentiation between P and D using default NVDA setting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5153]
**Reported by bansalakashdeep6 on 2015-06-13 14:38**
Sir/Madam,

I am facing the problem is distinguishing the voice spoken by NVDA for letter P and D. Please check and try to resolve it as soon as possible.

**Comment by bhavyashah** [comment]
I believe this ticket should be closed due to the following reasons:
* NVDA has moved on from ESpeak to ESpeak-NG.
* Any pronunciation issue, particularly the one reported in this ticket, is not only subjective but also related to the synthesizer and not the screen reader.
* Although the problem does not require significant troubleshooting information, we still do not have any means of contacting bansalakashdeep6 given that the project has transitioned from Trac to Github.
If anyone remains to have concerns in this regard, please report this to the vendor of that particular TTS engine. The Github project page for ESpeak-NG, for instance, is located at https://github.com/espeak-ng/espeak-ng. @ehollig

**Comment by leonardder** [comment]
[**@bhavyashah**](https://github.com/bhavyashah) commented on [3 aug. 2017 09:28 CEST](https://github.com/nvaccess/nvda/issues/5153#issuecomment-319891077 "2017-08-03T07:28:14Z - Replied by Github Reply Comments"):
> * Although the problem does not require significant troubleshooting information, we still do not have any means of contacting bansalakashdeep6 given that the project has transitioned from Trac to Github.

There is one very important thing we do not know, what language did the author use?

If this still exists, it should be reported for Espeak-NG. Closing as invalid.
