### ISSUE TITLE
Problems with different types of ListView

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5163]
**Reported by Gregory on 2015-06-18 17:40**
Hi,
In some applications NVDA doesn't handle dialogs similar to ListView corectly. 
In Total Commander, for instance, when opening "Change Start Menu" and pressing Downarrow repeatedly NVDA just says "list item". 
The same occurs in "Change Directory Menu" under "Configure". 

A similar phenomenon shows up in MP3Gain. This program sets the volume of MP3 files to one level. After loading a directory NVDA says "unknown" instead of the chosen file name.

**Comment by ehollig** [comment]
Possible duplicate:
Total Commander: #1724, #3952. I wonder if #3791 could help with this?
MP3Gain: #4675

**Comment by leonardder** [comment]
This issue is too broad (e.g. it describes two different problems in two different programs), and there is no means to contact the original author. Closing as invalid, please create separate tickets describing your issues along with steps to reproduce if they are still reproducible. Also, there might be duplicates indeed, as @ehollig pointed out.
