### ISSUE TITLE
make the audio device still active for better response

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5172]
**Reported by ondrosik on 2015-06-20 21:39**
Some audio devices have power management system which disables the device when it doesn't play any audio. This makes NVDA less responsive. When you press a key and NVDA wants to say something, you need to wait few miliseconds because the device needs to initialize, and after that play the sound, in this case speech synthesys. This also applies when you for example spell the statusbar or titlebar - spaces between characters are longer. The solution is really simple, Play silence. to the device all the time or somehow make it still active. When you run audio player such as winamp, NVDA is really more responsive, also when you pause the player. I think that we should integrate to NVDA something which will make the soundcard active all the time when NVDA is running. In most situations user can not disable this power management. In older soundcards, there was a comfig file or specific driver related dialog where this was possible, but nowadays it seems that mostly user can't do nothing about it.

**Comment by bhavyashah** [comment]
@derekriemer I believe you were working on a Play Silence add-on at one point in time. Was that related to this ticket in any way?

**Comment by derekriemer** [comment]
It seems that this is becoming more and more common with modern dell sound cards, and the unspoken addon by @camlorn randomly fixes the problem, although I don't know what he does differently than NVDA to hold the sound card hostage. @feerrenrut Any idea on priority? This issue is very annoying for those who have it, making NVDA very very annoying to use and nearly useless on new dell sound cards.Instead of hearing hello, you'd hear ello, (To be clear, the first sylibal of every utterance is cut off after a pause of speech over half a second or so).

**Comment by feerrenrut** [comment]
Based on the impact (skipped sounds) of this, I would consider this is fairly important. The questions that come to mind are:
* How many users does this actually impact?
* Is a developer able to reproduce this problem?
* What are the concrete steps to reproduce the problem?

Without being able to reproduce this, it will be difficult to fix. Essentially requiring a process of sending builds to users who report the problem until we have the confidence that this does fix the problem without introducing any other issues.

**Comment by Brian1Gaff** [comment]
I had a dell laptop in here a couple of weeks ago, dual booting xp and 7. 
Neither would work through the internal card without cropping of the end of 
speech a lot. I ended up plugging in an el cheapo usb sound device through a 
couple of speakers. Liuckily the guy is sighted or it would have made him 
send it through the window.
 However its odd as i have a Dell of 2013 vintage with none of this issue at 
all.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by camlorn** [comment]
I have seen something like this in some form on almost every computer I have ever used any screen reader on for the last 8 or so years, fortunately (but not always) fixable by disabling enhancements in control panel.

Unspoken fixes it because Unspoken never closes the audio device and is always writing zeros.  The sound card can't distinguish between that and actual audio, and so holds onto all resources.  there's nothing else special in Libaudioverse that would change anything--it's just using NVWave in that add-on, not my (admittedly buggy) backends.

I'm not going to be fast to respond to e-mail for a while so if someone wants to ask specific questions it might be best to grab me via IRC or something.

**Comment by jcsteh** [comment]
I'm seeing this with Realtek High Definition Audio on a Lenovo P51, even with enhancements disabled. The first sound played after audio has been closed incurs about a half second of lag when a headset is connected (not USB). Curiously, the lag is less (though still not instant) when using the laptop's speakers. This happens even if I exit NVDA and cause a Windows sound to play; e.g. by pressing backspace on a button in the Run dialog. So, this is definitely something related to the audio hardware/driver. Note that updating drivers, etc. does not resolve the issue.

There are two options here:

1. Keep the device open forever. I don't know if we want to do this because it could have implications for power. Note that we already do this in some cases anyway due to tones audio, so I guess this wouldn't be a regression strictly speaking.
2. Close the device after a certain time of inactivity; e.g. 10 seconds. The downside to this is that when the user interacts again after this time lapses, they will incur the lag. That isn't so bad if the user is not likely to pause for that long during continual interaction.

There's also the question of whether we want to make this configurable and what the default should be. One concern is that an option like this isn't going to make sense to most users, so it should be considered an advanced setting. It's perhaps worth rolling this out as a hidden config option first so people can try it out.

**Comment by Brian1Gaff** [comment]
I don't understand what is going on here, as some cards chop at the end some 
at the start, yet they all seem not to do this on normal windows sounds.
 the thing I notice though is that most modern machines have some kind of 
semi intelligent system monitoring the sockets and identifying what is 
plugged in and also quite often if you monitor inputs on these machines the 
latency between the input and output of the monitor is far longer than is 
comfortable if monitoring a microphone, sounding very like it used to be on 
old three head tape decks. I was just wondering if these issues are 
connected in some odd way.
 Although how it manages to do system sounds without cropping eludes me This 
is one reason why I now use an external usb sound device over the built in 
one.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment]
@jcsteh, @feerrenrut, @michaelDCurran, I have found a very helpful vbs script which solves this problem, see the issue referenced by @leonardder above. Could something like that be implemented in NVDA at start?

**Comment by Adriani90** [comment]
cc: @mltony

**Comment by mltony** [comment]
My NVDA add-on BluetoothAudio fixes this issue by playing silence to prevent wireless headsets from entering standby mode. To optimize battery usage, it only plays silence for 1 minute (configurable parameter) after the last speech command. 
https://github.com/mltony/nvda-bluetooth-audio/
