### ISSUE TITLE
Pin Reader To One Application

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5175]
**Reported by RMP2iN58bRrATmLS on 2015-06-21 02:17**
The ability to lock or pin the reader to one application would help with multi-tasking; such as when reading an e-book while working on something else.

I realize this is probably outside the core functionality, so perhaps it would be more appropriate as a plug-in/add-on.

**Comment by bhavyashah** [comment]
I have never disabled mouse tracking for all usage purposes, and am therefore a little confused here. Shouldn't NVDA ignore any and all mouse movement when mouse tracking is off anyways? In theory, this is what disabling mouse tracking suggests to me, but NVDA's speech is interrupted when I move the mouse pointer even though mouse tracking is off. I do think that NVDA should external mouse-related stimuli when mouse tracking is disabled, and if that is not the present scenario, a third state to mouse tracking would be useful. Thoughts/clarifications appreciated. @jcsteh @feerrenrut @josephsl @Qchristensen @leonardder

**Comment by Qchristensen** [comment]
I think there's two issues here - What you've pointed out about mouse tracking @bhavyashah may be an issue, but let's stick to "the ability to have NVDA read something in the background" which I think is essentially the summary of this issue.

While the earlier comment that if you just want something to read out long text to you while you do something else, there are other packages than a screen reader may be true, there could be instances where such a facility could be useful to a screen reader user.  The example given of a sighted user could be reading a web page which takes up half the screen while taking notes in Word on the other half of the screen is an interesting one.  On the one hand, what would perhaps be easier for most users would be the current behaviour - read the web page, press alt+tab to Word, type a note, press alt+tab back to your browser window and keep reading - repeat as needed.  You could potentially have the ability to have a "background reading" command read the web page in the background, then alt+tab back to Word, and make notes while it's reading.  You would then have to deal with issue such as would you have the background reading pause while giving information such as what window you are alt+tabbing to.  You could have a background reading command that let the normal speech interrupt as needed, but then picked up where it left off after that - you would then potentially have to resolve issues such as what if I want to increase or decrease the speed of the background reading?  Would you then need a second command to stop (or pause?) the background reading or could you use the regular control or shift?

Either way, I think this is a more suitable project as an add-on rather than core.  I think the appeal would be limited, and primarily for power users, but having said that, those who use it would likely find it quite helpful.

**Comment by Qchristensen** [comment]
Not so much an update, but a potential alternative for someone wanting full documents read in the background, I found a freeware program called Balabolka.  The first time I ran it, none of the controls read, but the second time it read everything perfectly.  In any case, press control+o to open a file, then f5 to have it read in the background.  The trick is you can't use the same synth as NVDA is using.  Balabolka uses SAPI 5 by default.  As long as NVDA is using something else,k both can work at the same time: http://www.cross-plus-a.com/balabolka.htm

**Comment by ehollig** [comment]
I am going to close this issue as wantfix according to https://github.com/nvaccess/nvda/issues/5175#issuecomment-155340796. As stated in https://github.com/nvaccess/nvda/issues/5175#issuecomment-318998578, I think this is a more suitable project as an add-on rather than core.
