### ISSUE TITLE
Explorer: NVDA announces "Alt +" when gaining focus on a folder name with the "&" character

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5210]
**Reported by elliott94 on 2015-07-12 08:39**
STR (observed under Windows 7):
1. In Explorer, create a new folder in a location of your choice, using the name "First & Second"
2. Navigate inside the folder that was just created, and switch focus away from the Explorer window
3. When using Alt-Tab to switch windows, you will see the just-created folder in the list, with the "&" character as expected
4. Navigate back to the just-created folder in Explorer. You'll notice that in its description NVDA misses out the "&" character; it appears that Windows doesn't support these when displaying the name of any window that contains one of these. In this particular instance, it is evident when spelling the window title. However, immediately after navigating back to the window, NVDA gives the output of "First Second Alt +", rather than simply "First Second"

**Comment by ehollig** [comment]
@elliott94, is this still an issue? If it is, it sounds as if it is a bug with Windows, rather than a bug with NVDA.
Performed the following steps on Windows 10, although the original post is using Windows 7.

1. In Explorer, created a new folder using the name "First & Second"
2. Navigated inside the folder that was just created, and switched focus away from the Explorer window
3. Used alt+tab to see that the new folder had the & symbol.
4. Navigated back to the folder in Explorer and NVDA reports the "&" character

**Comment by elliott94** [comment]
Happy for this to be closed. Interestingly, when using Windows 10 the "&" character is missing when deleting the folder and Windows reports the name of the directory that is about to be deleted.

**Comment by ehollig** [comment]
Closing as worksforme, from testing performed in https://github.com/nvaccess/nvda/issues/5210#issuecomment-337621714
