### ISSUE TITLE
Hidden skip link is itself skipped when NVDA is running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5230]
**Reported by hhillen on 2015-07-17 09:04**
Scenario:

Using the following [test case](https://dl.dropboxusercontent.com/u/573324/testcases/bugreports/NVDA/hidden_skiplink.html) (also attached)

A skip link is the first tab stop on the page. It is hidden visually using Bootstrap's sr-only class (which uses clipping to hide the element), so the link is still perceivable by AT, focusable, and part of the tab order, A CSS :focus pseudo selector is used to make the link become visible when it receives focus, i.e. when a keyboard user tabs to it. 

Problem: 
In Firefox, When NVDA is running in browse mode, NVDA will skip over the link when tabbing through the page. NVDA does correctly focus the link when shift tabbing. The issue only occurs in with the Firefox/NVDA combination, and only in browse mode.

**Comment by hidanielle** [comment]
Is there any update on this? I'm currently experiencing this issue on my site.

**Comment by jcsteh** [comment]
On a newly loaded page, the browse mode cursor is placed at the top of the page. The link is at the top of the page. Thus, the browse mode cursor is right on the link. Tabbing therefore moves to the next link because the user is already on the first link. If we changed this, the user would never be able to move past a link the cursor is placed within.

**Comment by jcsteh** [comment]
Note that while it makes sense that tab doesn't focus the first link as explained above, the first link should get focus when browse mode is initialised because the cursor lands on the link. That's covered by #3575.
