### ISSUE TITLE
input type="file" is only read as "browse button" in firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5326]
**Reported by jmuheim on 2015-09-09 07:16**
File inputs are only read as "browse button" in firefox, regardless whether there is a label or any sort of aria-describedby (or similar) enhancement.

In IE and Chrome it works better.

Check out demo here:

http://codepen.io/jmuheim/full/JYdKRx

**Comment by leonardder** [comment]
@JCSTeh: Should someone file a bug against firefox for this?

**Comment by jcsteh** [comment]
Interestingly, in Chrome, the button does now get the author provided label instead of "Choose file".

For Firefox, I still think I'd prefer the file input (which currently gets a role of text frame) to get a role of grouping. It already gets the label. That way, this would be read as a labelled grouping with a Browse button when tabbing.

A bug has yet to be filed against Firefox.

**Comment by jcsteh** [comment]
Actually, there is a bug after all: [Mozilla bug 1316965](https://bugzilla.mozilla.org/show_bug.cgi?id=1316965)
