### ISSUE TITLE
When NVDA is set to read columns in Excel columns aren't read if there is separation between column headers and data.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5396]
**Reported by csm120 on 2015-10-01 23:32**
I've seen this behavior in Excel 2010, 2013, and 2016. 
Steps:
1. In Excel make 3 columns from a1 to c3.
2. Type data starting in a3.
3. Use NVDA+Shift+c on a1.
4. Reading of columns is spotty or not happening unless you delete the blank row at a2.
I have tried this with NVDA 2015.3, and with latest snaps.
I need the columns to be read even if there is separation between the column headers and the data. I'm attaching a file.

**Comment by jcsteh** [comment]
This was incubated months ago in b2831998, but the automated script didn't catch it for some reason.

There are a couple of additional things that are needed for this:

- [ ] If one defines two sets of headers, the first set will be read as the headers when moving over the second set of headers. For example, if a1 and c1 are set as column headers, a1 will be read as a header when moving from c2 to c1. We shouldn't search for a header in the same axis for a cell which is a header in that axis itself.
- [ ] #4409 fixed an issue which caused exceptions in a protected sheet if reporting of headers was enabled. I think (but am not sure) that this just disables headers, rather than just disabling region checks. That case needs to be checked.

**Comment by nvaccessAuto** [comment]
Incubated in c7ec64ce247125362a31e0bc44285e53a2a92236.

**Comment by nvaccessAuto** [comment]
Incubated in 6637f7f83bebe3141dc795b5c2718ee43a908f51.

**Comment by jcsteh** [comment]
Note: c14f16eb in next on 12 April reverted 35f0f0d7.
