### ISSUE TITLE
Braille doesn't scroll to same-line search result in Notepad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5410]
**Reported by dkager on 2015-10-11 20:03**
STR:
* Type a line with the same phrase in it multiple times, at the start of the line and later on with enough other text inbetween.
* Press Ctrl+F and search for the phrase.
* Press Escape. Braille shows the selected text, i.e. the search phrase.
* Press F3.
* Braille does not scroll to the newly selected text, i.e. the second occurrence of the search phrase.

**Comment by dkager** [comment]
Code is now [here](https://github.com/dkager/nvda/tree/t5410) on GitHub. I'll drop the BitBucket repo linked to in earlier comments.

**Comment by nvaccessAuto** [comment]
Incubated in f53054bed4976e0a8c6094e2ea7bc298edc09a3d.

**Comment by jcsteh** [comment]
Ug. I was reviewing #5198 and discovered that the selection indicator still shows when the cursor is disabled. I just realised that even with this fixed, the selection indicator doesn't appear/disappear when you toggle the option from a script, since the region isn't updated.

* I don't want to update all buffers every time we dismiss a message.
* I guess you could update the last region from within the show cursor script. That might result in an unnecessary update, but at least it's isolated.
* Alternatively, you could move selection drawing into BrailleHandler alongside cursor drawing. You'd still need to notify BrailleHandler, though, as there won't be a blink timer to do the work for you.

**Comment by dkager** [comment]
Very quick comment (more this afternoon when I have time to read the other comments in #5198): it wasn’t my intention to also disable the selection indicator when the cursor is toggled off. It is arguably not the same thing as a cursor indicator. Even without a blinking cursor I might still want to know what I selected in an edit control.

**Comment by jcsteh** [comment]
I'm confused. In #5198, I wrote:

> I think the command should toggle both the cursor and selection.

And you replied:

> I agree. ... SuperNova also uses one command to toggle both.

So, is this a re-think or am I missing something?

**Comment by dkager** [comment]
This is a re-think, I don’t want to fall into the trap of emulating an existing product. I’ll give it some serious thought and come up with a proper argument in #5198.
