### ISSUE TITLE
Update driver for Handytech braille displays

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5418]
**Reported by heikofolkerts on 2015-10-15 05:18**
The current stable version uses the Handytech Braille display driver HtBrailleDriverServer.dll in version 1.4.2.0. The current version is 1.5.0.0. The old driver in version 1.4.2.0 cannot correctly detect the change of a braille display e.g. when switching from a "modular evolution" to a "modular connect" braille display.

The current version of the driver is attached and was sent to me directly via handytech support.
It is enough to update the DLL - after doing so manually changing braille displays as described above is possible.

**Comment by ehollig** [comment]
@jcsteh is this still going to be implemented into NVDA, or should initiative be put toward #7458

**Comment by jcsteh** [comment]
Long-term, I think #7458 is the better approach. Near-term, I'm happy to update the dll in NVDA, but we still need to know whether we have permission from Handy Tech to do this and that it's not a private/test release; see https://github.com/nvaccess/nvda/issues/5418#issuecomment-155343973. CC @BramD for his thoughts, since he's working on #7458.

**Comment by bramd** [comment]
@jcsteh I hope to finish the work in #7458 soon. I'll post a status report in that issue.

Since there are lots of Handy Tech models, including very old ones, I'm unable to get them all tested without getting Handy Tech on board. Also, the keybindings are abstracted a bit by the COM server, so custom gestures might not work without providing some kind of migration code, or something that can still interpret the old gestures. Since this is a complete rewrite to replace the COM server, I think it's essential that we are at lease feature complete with the old COM server before shipping this. That being said, it's important that the new driver gets some real testing with the hardware that's out there. So, we might ship this as a preview with NVDA 2017.4 and iffer users of the old driver the option to test the new, native driver. If it doesn't work for them, they can still switch back to the old one. The best scenario would be that Handy Tech does code review and testing and that we can ship this knowing it will work with all hardware, but I'm not sure if that will happen.

So, it still makes sense to get the newer DLL in as soon as possible. I just checked and it still isn't offered at the downloads page at handytech.de.
