### ISSUE TITLE
Launcher: Remove Data from Temporary Directory on Exit

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5419]
**Reported by elliott94 on 2015-10-15 08:05**
Upon running the Launcher, it appears that data is copied to the Temporary directory of the logged-in user; further files get added to this depending on how NVDA is used. For example, if the user opens the What's New file, the resulting HTML file gets copied to the running directory and opened in the default web browser. However, on exiting NVDA it appears that this directory is kept behind and not removed; this doesn't appear to occur if an update operation is performed from an already installed copy.

**Comment by bhavyashah** [comment]
Although @jcsteh reopened this ticket in https://github.com/nvaccess/nvda/issues/5419#issuecomment-155343985, the cited comment still seemed indicative of a cantfix. Thoughts? @feerrenrut @leonardder and others

**Comment by jcsteh** [comment]
We can't fix dlls being left behind. In theory, we should be able to fix nvda_logo.wav being left behind by using a player which closes the file properly once it finishes playing. We might be able to use the Windows PlaySound function; I'm not honestly sure why we don't use that already. Not high priority, though, since these are temporary files and are thus candidates for cleanup by Windows.

**Comment by Brian1Gaff** [comment]
I'm not worried by this at all. As you say not only does windows clean out 
this, but ccleaner will as well. Other programs are far worse than nvda in 
this respect. Not to name names of course, but it begins with an A.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [25 aug. 2017 13:20 CEST](https://github.com/nvaccess/nvda/issues/5419#issuecomment-324891409 "2017-08-25T11:20:30Z - Replied by Github Reply Comments"):
> We can't fix dlls being left behind. In theory, we should be able to fix nvda_logo.wav being left behind by using a player which closes the file properly once it finishes playing. We might be able to use the Windows PlaySound function; I'm not honestly sure why we don't use that already. Not high priority, though, since these are temporary files and are thus candidates for cleanup by Windows.

I belief we are already using this since #6557.

```
System::Call 'winmm::PlaySound(t r9, i 0, i r0) b'
```

@Elliott94: Could you investigate the current state of this issue?

**Comment by elliott94** [comment]
Happy for this to be closed; the file now automatically gets deleted; and the folder that gets placed into the Temp directory is removed upon a reboot. :)
