### ISSUE TITLE
Put EditableTextWithAutoSelectDetection for IA2 after other IAccessible overlay classes instead of before

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5433]
**Reported by jteh on 2015-10-21 07:36**
NVDAObjects.IAccessible.findOverlayClasses appends EditableTextWithAutoSelectDetection for IA2 text. However, it does this _before_ other overlay classes. Ideally, it should be _after_ so other (more specific) overlay classes can override it. This is causing problems for selection in Mozilla rich text editors. I am hacking around this in Mozilla specific code for now, as I think this code is too risky for 2015.4 at this stage, but we should try to fix it properly for 2016.1.

**Comment by jcsteh** [comment]
Actually, we didn't need this at all for Mozilla rich text editing. We should still possibly consider this, but it's not at all important now.

**Comment by leonardder** [comment]
@JCSTeh: Could you give a specific use case where this would be an useful change?

**Comment by jcsteh** [comment]
I don't know of any specific use cases. The way things are now does seem odd - overlay classes you might expect to override the editable text stuff can't override it because editable text ends up getting placed before them. However, as I noted previously, we didn't end up needing this for the original use case at all, and my recollection of this is vague at best. I'm Closing as won't fix for now; we can always reopen if there's a valid use case in future.
