### ISSUE TITLE
Word 2013 raises ExpatError on Reviewing Pane

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5451]
**Reported by nishimotz on 2015-11-01 13:36**
Setup:

* Windows 8.1 32bit (Primary language: English)
* Microsoft Word 2013 32bit (Japanese version + English language pack)
* NVDA master-11513,7190109 portable

Procedures:

* Open Word 2013
* Ctrl+N (open new Document1)
* Alt+R G G (Review - Track Changes) make sure checked
* Alt+R T P V (Reviewing Pane Vertical)
* focus on Document1
* press Enter (make new revisions)
* press F6 to go to Revisions pane
* press down arrow
* NVDA says "blank" and error occurs as follows:

```
ERROR - XMLFormatting.XMLTextParser.parse (22:32:45):
XML: <control wdStoryType="0"><text _startOffset="26" _endOffset="27" page-number="1" line-prefix="<#>" wdRevisionType="1" wdLanguageId="1033" >
</text></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 60, in parse
ExpatError: not well-formed (invalid token): line 1, column 94
```

Same error is observed on Windows 7 with Word 2010 as well.

**Comment by jcsteh** [comment]
Perhaps it's just me, but I think there is a lot of other brokenness in that Reviewing Pane. Lines don't seem to read properly; I just get single letters. In addition, once it's focused, I can't seem to f6 back to the document; every time the document gets focus, focus seems to bounce back to the Reviewing Pane. This focus bouncing doesn't seem to happen if I exit NVDA.

Due to all of this weirdness, I haven't noted this fix in the What's New, since users can't really use this pane anyway. However, we should investigate/fix this stuff separately at some point.
