### ISSUE TITLE
provide a description of the NVDA logo

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5456]
**Reported by bhavyashah on 2015-11-03 13:17**
On the NVDA COmmunity portal, there is a graphic containing the NVDA logo.
Tis logo graphic should be described, by alternative text or by a long description.
Furthermore, I am slightly confused as to why this logo of NVDA is only placed on the NVDA COmmunity portal, and not on NV Access's website.
On NV Access's website, pressing 'g' yields no results.

**Comment by derekriemer** [comment]
Hi, I too think describing this logo, and the NVDA desktop icon, would be useful.

**Comment by ehollig** [comment]
@Qchristensen was this done at one point? I seem to recall an update that you sent out had the NVDA Logo described. Is the logo discussed here the same or something similar?

**Comment by Qchristensen** [comment]
I do include a description as part of the larger description of the Certified Expert certificate.  I think I did include it in In-Process once, but I think it's a great idea to have it as an extended description of the logo on the site.

The NV Access logo is a hollow purple sun shape with 16 points.  8 points are sharp and triangular, coloured in purple.  The purple points alternate between either orange or turquoise rounded points.  The orange points are at the top, bottom left and right.  Inside the circle of the sun is a purple diamond outline, and in the centre is a hollow turquoise ring.

To the right of the logo are the words "NV Access" above the tag-line "Empowering lives through non-visual access to technology".  The text "NV" is in orange and the rest of the text is in purple.  There is a purple horizontal line in the centre, between the company name and tag-line.

The sun logo itself is about a third of the total width, with "NV Access" in large text and the tag-line smaller.

**Comment by Qchristensen** [comment]
Just to separate it to its own comment, here is a description of the NVDA logo I included in In-Process at one point:

"For those wondering, the NVDA logo is a stylised blend of the letters NVDA in white on a square purple background. There is a vertical line on the left with a rounded hook to the right at the bottom as if starting to form the bottom corner of a "D". Then from the top, a straight diagonal line comes down to the right. Next, a line curves in a semi-circle out to the right then back up to the top.  The line finishes in a downward hook with a curved end. The vertical and diagonal lines make the first part of the letter N and also the letter A (without the crossbar). The diagonal and curved lines form a V, and the curve is the right part of the D."

**Comment by ehollig** [comment]
@Qchristensen thank you for the reply. Is this something that could be considered as a long description for an image on the site? I do think that text that you provided above may be too long for alt text for an image, but considering other ways to express this information would be u8seful so everyone is able to enjoy the NVDA Logo.

**Comment by Adriani90** [comment]
@Qchristensen is the logo actually visible on the website at all?

**Comment by bdorer** [comment]
The NVAccess logo is vissible on nvaccess.org and described. I couldn't 
find any logo on githubs community page.

Am 02.02.2019 um 15:05 schrieb Adriani90:

**Comment by Adriani90** [comment]
@bdorer     where did you find the logo? I cannot find it on nvaccess.org.

**Comment by Adriani90** [comment]
@Qchristensen I guess this is fixed. Right? If yes, then I vote for closing this one.

**Comment by Adriani90** [comment]
@Qchristensen I think this is meant in this issue:
https://www.nvaccess.org/nvda_200x200_op/

It can be found imediately in google when searching for NVDA logo.

**Comment by Qchristensen** [comment]
Adriani, that link you found is to the original NVDA logo.  It was updated in 2017, and introduced in Alpha builds prior to 2017.3 and in this In-Process post: https://www.nvaccess.org/post/in-process-2nd-august-2017/

I have updated the About NV Access page with a description of the NV Access logo, as well as the sunburst design which is used as decoration in a few places here and there (on the website and on the NVDA certified expert certificate to name two places): https://www.nvaccess.org/about-nv-access/#NVAccessLogo

I have also added a description of the NVDA logo to the About NVDA page: https://www.nvaccess.org/about-nvda/#NVDALogo

The original commented noted the logo on the community portal.  We don't use the old nvda-community domain anymore; the content from there has pretty much all been migrated to GitHub or elsewhere.  To answer the other question from that original post though, the reason some graphics don't get listed with G is that they are marked as presentation only (ie: decorative).  If that is something we want to address, I'd suggest a new issue for it (there might be one, I haven't looked).

As the essence of this issue was about providing a description of the NVDA logo which could more easily be found, I believe that has now been resolved, so I am going to close this issue now.
