### ISSUE TITLE
Firefox: "Blank" announced in edit boxes whilst navigating by character using Object Navigation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5475]
STR (can also be performed in Search Bar):

1. Navigate to a form, and enter some sample text

2. When finished typing, navigate to the next character using object navigation; you should hear "blank"

3. Use the left cursor to navigate to the previous character, and unlike the previous attempt when now moving to the next character with Object Navigation NVDA will now count the last character as its boundry

Expected: NVDA never to announce "blank" and to treat the last character as its boundry without first having to cursor left

**Comment by jcsteh** [comment]
When you navigate to the next character in step 2, you're actually not navigating to the next character, since your cursor is already at the end of the text; NVDA says "right" because you can't go any further. There is always a "blank" spot at the end of the text (where your cursor is positioned) because otherwise, you wouldn't be able to type text at the end. For example, if you press the end key, you must land on this "blank" spot. If we always snapped the review cursor to the last real character, pressing report current character would say the last character instead of "blank", which would be incorrect.

I understand the concern about asymmetry here because you can't get back to that blank character; it's not a real character in Firefox. However, it needs to be there for the reasons given above.
