### ISSUE TITLE
feature request for command keys in NVDA

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#5484]
there is no control for users to tell NVDA what to speak and what's not while having enabled the speaking of command keys. for example, some user only want to speak "tab" "enter" "escape" keys feedback. but when speak command keys is enabled, NVDA start speaking left/right/up/down aerrow, every keystroke like NVDA+T before saying title of the windows, and so on. this is too much irritating. so please add control for the same.

**Comment by jcsteh** [comment]
The problem with this is that every user will have different desires. The choice of just tab, enter and escape is fairly arbitrary. Solving this would require us to have checkboxes for every single key on the system, which would be difficult to configure and maintain.

**Comment by abdullah5490** [comment]
ok, then don't add check boxes for each key, simply remove the aerrow and multi keys strokes such NVDA+T from speaking of command keys. just keep included the speaking of tabs, enter, function keys, and others. because i think, no one wants to know, that he/she has press the right, left, up or down aerrow, or NVDA+B keystroke. the action will be made on the pressed keystroke, that is enough. because in absence of speach for command keys, NVDA felt too slow as compared to other screen readers.

**Comment by jcsteh** [comment]
Your choice of "command keys" is still arbitrary and certainly doesn't fit the description of the option. If a user enables this, maybe they *do* need to know about the arrow keys because they're still learning the keyboard, for example. In some cases, the arrow keys will say nothing at all; e.g. an empty list. Also, if you know the keyboard well enough to say you never need to hear about the arrow keys, then why do you need to hear about tab and enter? Those keys are fairly major.

**Comment by abdullah5490** [comment]
speaking of these important keys can enhance the performance of NVDA and make it more comfort to use. because in absence of keys announcement, NVDA's response felt slow as compare to when its present.  for those who are learning the keyboard, there is keyboard help mode available. so no need to add it to speak command keys. NVDA always speaks every key in keyboard help mode. and secondly, creating checkboxes or comboboxes are not very impossible task. every new feature/option in a software is presented through checkbox or a new combo box, then why shouldn't in this case? you can catagorize the keys in to 3 types (for example). none: where no key will be spoken. some: where important function keys such as tab, enter, f1 through f12, can be spoken. and all: in which every key, and keystrokes will be spoken back to user. if you add something to NVDA, you are required to create a new option in form of check box, a combo box, or a new menu itum. then why are you refusing to do the same on this little feature request? i want this ticket to be opened and be considered for the development. i'am not agreed with this way in which this ticket is closed without any strong logic or reason.

**Comment by josephsl** [comment]
Hi,

 

Hmmm, you raise good points. May I address this question and hopefully elaborate why Jamie has closed this ticket:

 

In regards to correlation between command announcement and performance: I see no correlation. Possible reasons why people might perceive command announcement as a performance boost include speech response and an illusion that more speech may mean increased performance. In some cases (such as when reviewing a long document or examining text carefully such as formatting), more speech may mean decreased productivity. Also, the question of performance boost is a subjective question that can never be resolved through features like this. Also, there are other things that affect NVDA’s performance and productivity such as add-ons, responsiveness of an application one is dealing with and so on.

 

In regards to every feature needing a configuration user interface: there is a good counterexample that is now included in 2015.4. In older versions of NVDA, when selecting text, NVDA announced “selected (text)”. Now in 2015.4, NVDA says, “(text) selected”, which improves productivity in some situations, and this didn’t require a checkbox or a combo box to configure this.

 

In regards to level of announcement: The question of what is considered important keys is a subjective one. Some may include media keys in “some”, while others would like to exclude certain function keys from being announced. Also, we cannot ignore international audience, and this raises three issues that this ticket may have not addressed:

 

1.       Some people use software that allows them to use specific combination of keys to enter text (Vietnamese, for example). Ideally, NVDA Core should handle this, but if this ticket is adopted, it’ll mean hunting for these apps and creating special cases (or app modules) to handle them such as determining at which level these keys should be announced.

2.       Different countries use different keyboard layouts, and labels of some keys might not be standardized. Although it is possible to look at technical information behind key presses, users in some countires may not want some keys from being announced (such as dead keys).

3.       Certain keyboards include nonstandard function keys and send different key codes and other information to operating systems. Some may wish these nonstandard keys to be announced in a certain level, and we cannot handle all possible special keys, key codes and so on.

 

Thus I’m in agreement with Jamie that the most optimal solution that can satisfy many would be on or off (keep this feature as is).

 

One final note and advice (mostly for members of the public): On the surface, NVDA is like any other screen reader. But deep down, it is a complex, modular and a group of interconnected components that work together to perform its duties. These interconnected modules are not only used by power users, but also used by beginners, professionals and alike. Also, English isn’t the only language NVDA speaks – it has been translated into almost 50 languages. Thus when thinking about a feature, please keep these points in mind – a simple feature request could mean deep changes (such as what this ticket is actually asking), and a suggestion may not come to life because it is beyond NV access’ control (a good example being NVDA for mobile phones, which may never materialize).

 

Hope this helps.
