### ISSUE TITLE
build nvda on appveyor

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#5499]
hello devs.

did you think about hosting build environment on appveyor?

**Comment by jcsteh** [comment]
I looked into it a bit a while ago. There's quite a lot of work involved 
in porting our current system. There are also some issues which are 
going to be tricky such as secure stuff like our Authenticode 
certificate and uploading to our server. I know you can encrypt 
environment variables, but we probably can't store the entire 
certificate in an environment variable. Also, having it encrypted 
doesn't stop someone from modifying the config and making it do stuff it 
shouldn't do on our server instead of just uploading, so these builds 
would absolutely need to be restricted to core committers.

We may well switch to Appveyor eventually, but the only real advantage 
it offers us is that we don't have to pay for a Windows VPS (which is 
not overly expensive), so it's not high priority right now.

**Comment by dusek** [comment]
Another advantage of appveyor is that it can be run on each Pull Request and the result of the build (successful / not successful) can then be seen directly in the PR. So you at least know that the PR does not break the build. When NVDA will have tests, it will add yet another level of control and the CI status on the PR will reflect those too.

I want to give it a try (to be precise, I have it basically working here, just want to polish it) and submit it as a PR in a few days. I simply do not use any certificate (without it NVDA and installer build fine, it's just not signed), and register the installer as an Appveyor build artifact, so that for each AppVeyor build (new commits in branch, or new PR), it is possible to download the resulting NVDA installer, install it, and check things manually.

**Comment by jcsteh** [comment]
Thanks for your interest.

Where do those artefacts actually get placed? I haven't been able to 
work that out yet from reading the documentation.

I'm against running builds for pull requests. I realise they don't have 
access to secure data, but I'm still concerned about the fact that 
anyone can change the build scripts how ever they like and a build will 
get made. Of course, without the certificate, there's nothing stating 
they're authentic NV Access builds, but they still appear under the NVDA 
project, so people can easily be misled. Also, these builds would be 
running under our Appveyor account, which means that if there are too 
many of them, we end up contending with the public for our official builds.

There's quite a bit of extra code involved in getting snapshot builds 
published, including debug symbols, index generation, auto updates, etc. 
We'd need to refactor all of this to work in an Appveyor world, 
including associated security concerns.

**Comment by nvaccessAuto** [comment]
Incubated in 83f8f990141abcae549c60ab38541226a4495213.

**Comment by nvaccessAuto** [comment]
Incubated in e9ab8ee5c9e0e3c3ab6cd3eda53ba5a501210a32.
