### ISSUE TITLE
Windows 8.1, IE 11, ARIA live region; updates not voiced

### ISSUE THREAD

**Issue by pkra** [nvaccess/nvda#5501]
We're having trouble getting NVDA to pick up ARIA live regions on IE11. Below is a link to a simple demo that works in IE9 and IE10 but not IE11 (or MS Edge). 

http://s.codepen.io/pkra/debug/BoVBpX

**Comment by michaelDCurran** [comment]
For me, running the testcase on IE 11, NVDA announced "Hello updated" and "Hello insert" due to the live region updates, just as it also did in Firefox. I ran the test on Windows 10 though... perhaps this issue is specific to Windows 8 though I would highly doubt it.
What version of NVDA were you testing with?
Note that we have no live region support for Microsoft Edge at this point in time.

**Comment by pkra** [comment]
Thanks for looking into it, @michaelDCurran! I have to apologize for creating noise. I had not realized that I had a more systemic problem -- NVDA was not working properly in browsers anymore (though oddly enough it did pick up on a live region in Chrome and Firefox). I'm not sure how I corrupted my test VM this way but when I tried a fresh VM the problem does not occur anymore -- yay!. 

For the record, I was using the modern.ie VM for IE 11 on Windows 8.1 and NVDA 2015.3. Again, sorry for the noise.

**Comment by hrvojegolcic** [comment]
Hi there,

the provided example works fine for me too but only when used `setTimeout(injectAlert, 10000)` to inject alert messages with such delay. But it doesn't work if executed **on page load** (instead of button click) and **if the delay time is too small**, e.g. `setTimeout(injectAlert, 0)`.

**How much time does it need in order to register an update and why?**

```html
<div id="my-live-region1" role="alert" aria-live="assertive"></div>
<div id="my-live-region2" role="alert" aria-live="assertive"></div>
```

```javascript
// ON PAGE LOAD
document.addEventListener("DOMContentLoaded", function() {
    let alertCont1 = document.getElementById("my-live-region1");
    let alertCont2 = document.getElementById("my-live-region2");

    // WITH SMALL DELAY... DOES NOT WORK
    setTimeout(function(){
        alertCont1.innerHTML = "TEST ALERT 1 - THIS DOESN'T WORK";
    }, 50);

    // WITH LONGER DELAY... WORKS
    setTimeout(function(){
        alertCont2.innerHTML = "TEST ALERT 2 - THIS WORKS";
    }, 2500);
})
```

Environment:
* NVDA 2020.1
* Windows 8.1
* IE 11.778.18362.0 (version update 11.0.185)
