### ISSUE TITLE
Norwegian language problem on NVDA

### ISSUE THREAD

**Issue by Giovani93** [nvaccess/nvda#5502]
Hello!
I am not native norwegian speaker, but I notice a problem. It says english punctuation and letters in Norwegian (across the Espeak), when I switch the language. Ofcourse, when I switch Spanish, It says a Spanish interpunctuation also. If Swedish, it says Swedish too. But, when I switch Espeak to Norwegian, It says only English interpunction. But, It works good, when Norwegian is set to Sapi5 Espeak, not on NVDA espeak.
One example: It says dot in Norwegian, when I press dot and not punktum, like in Norwegian. Please, could You fix this problem?
Thank You!

**Comment by jcsteh** [comment]
The problem is that there are two forms of Norwegian (and NVDA has translations for both): Norwegian Bokmål (nb_NO) and Norwegian Nynorsk (nn_NO). eSpeak just uses the code no, though it also reports nb as a secondary code, which suggests it's closer to Norwegian Bokmål. Obviously, "no" doesn't match either of these codes, and even if we somehow made it fall back to "nb", the NVDA translation is more specific than this (nb_NO), so it would never match.

I think we're going to need some feedback from the Norwegian translators on this.

**Comment by bhavyashah** [comment]
Just wondering, is this still the case with ESpeak-NG? If so, do we have the Github usernames of members of the Norwegian localization team, if they have Github accounts in the first place, that is? As noted in https://github.com/nvaccess/nvda/issues/5502#issuecomment-157202292, their inputs would be valuable.

**Comment by Adriani90** [comment]
@Giovani93 is this still an issue for you?

**Comment by Adriani90** [comment]
We didn't get an update from the initial author and I didn't hear of this problem in the translations list where also novergian translators are active.
Thus, I am closing this as abandoned.
