### ISSUE TITLE
Copying text with review cursor copies an extra character to the right of the selection

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5507]
Press NVDA+f9 to start marking with the review cursor. Select text to be copied (eg num pad 6 to select the rest of the word or next word, then press NVDA+f10 and an extra character is copied to the right of the selection.  EG if I did that at the start of my comment here, instead of copying "Press ", it would copy "Press N".  If I had the review cursor at the start of my comment and pressed NVDA+f9, then immediately NVDA+f10, it would copy the "P".  This is different to the regular text selection / copying behaviour.  It works the same regardless of which characters I select with (eg selecting by line / word / character, and also in both desktop and laptop mode.  It also behaves the same in both Internet Explorer, notepad and wordpad, and in both 2015.3 and 2015.4rc1

**Comment by josephsl** [comment]
Hi Quentin,

 

Does this happen with all review cursor movement keys or with words and lines? I cannot reproduce this if I move the review cursor by character.

 

Thanks.

**Comment by Qchristensen** [comment]
Yes it happens with characters too.  So if I move with the review cursor to the start of this comment, it will announce "Y" (or the word / line depending on how I move to get there), if I then start marking with NVDA+f9 it reads "Start marked", if I then press num pad 3, it reads "e", as it would if the caret was there and I pressed right arrow (If I selected with standard keys it would read "Y selected" at this point - I've only moved right one character since starting selecting), If I then press NVDA+f10, it copies "Ye" where it should only copy "Y" - similarly if I move the review cursor to the start of my comment, start copying and press num pad 6 (select word) and then num pad 3 (select character) it actually selects "Yes it".

**Comment by jcsteh** [comment]
This is intentional behaviour.

It's certainly true that the end being inclusive (not exclusive) is different to normal selection. Normal selection is a bit different because you add to it, rather than marking the start and end. However, the real reason we do this is because there sometimes isn't a blank character at the end of text, particularly when dealing with controls which *aren't* editable such as buttons, list items, etc. (which is where this is most useful). So, for example, try this:

1. Open the Run dialog.
2. Tab to the Cancel button.
3. Now, try to copy "Cancel" with the review cursor.

You'll notice that when you hit the "l", you can't move any further right. If we made the selection end exclusive, you would only be able to copy "Cance".
