### ISSUE TITLE
Windows 10, NVDA closing when leaving the command prompt by pressing alt+f4

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5509]
Under Windows 10, you can close a command prompt by pressing alt+f4 like any other windows.
Unfortunately, this also closes NVDA.

**Comment by leonardder** [comment]
I can confirm this issue. Some additional observations

* NVDA doesn't shut down when closing cmd with exit
* Problem occurs with CMD both with and without administrative privileges

**Comment by dkager** [comment]
This has been brought up a few times before, initially in #1682.

**Comment by jcsteh** [comment]
#5343 also brought this up and I closed it as a duplicate. However, while we probably can't fix all cases of #1682 (e.g. clicking the close button), it's more likely that someone might press alt+f4 and we can at least intercept that key.

One thing to investigate is whether we can hook the function Windows calls to force our process to exit. If we can do that, we can fix #1682 completely. Otherwise, we'll just intercept alt+f4 for Windows 10 as noted above.

**Comment by jcsteh** [comment]
@michaelDCurran did this work in #5343, so I'll reopen that and close this as a duplicate.

**Comment by MichelSuch** [comment]
Hi,


Yes, it works fine for me.

                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel
