### ISSUE TITLE
Cortana's greetings not being read by NVDA

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#5510]
So I have noticed for a long time that Cortana will randomly steal NVDA's focus, and I recently found out why. Sometimes Cortana pops up with a greeting from time to time, and whenever that happens, focus is suddenly set to the Cortana window. So, I'm wondering if it would be possible to implement a way to have Cortana's greetings be read automatically by NVDA? Thanks.

**Comment by josephsl** [comment]
Hi,

 

I was told that users of other screen readers are having this issue.

 

For whoever would like to work on this, I recommend trying the following:

 

1.       Use Windows 10 SDK’s accevent.exe to watch events.

2.       Once the focus moves away due to Cortana greeting you, note a few objects:

 

*         The focused object.

*         The object which displays the greeting text.

 

The one we’re interested in the most is the second one, and if Accevent detects a UIA event coming from this window (you need to find out the event name, class name, UIA element from cache and so on), then extend source/NvDAObjects/UIA/UIA.py to handle this case (similar to toast notifications).

 

Good luck.

**Comment by Mohamed00** [comment]
This issue stopped occurring in Windows 10 version 1511, and as of 1703, still isn't occurring. Should this be closed?

**Comment by josephsl** [comment]
Closing due to updated report. Please reopen if this happens ever again. Thanks.
