### ISSUE TITLE
Elements list filter when changing element type

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5511]
After bringing up the elements list (NVDA+f7) and entering text in the filter box, if you then change type (eg between links, headings and landmarks), the list of elements resets to show an unfiltered list of the new element type, however the original filter text is still left in the filter edit box.

**Comment by jcsteh** [comment]
Implementation note: The filter field should simply be cleared when we switch to (initialise) a different element type.

**Comment by derekriemer** [comment]
This behavior could be useful if someone realized they were looking for 
a heading titled fish tacos rather than a link titled fish tacos. Just 
thought I would note.

On 11/18/2015 6:14 PM, James Teh wrote:
>
> Implementation note: The filter field should simply be cleared when we 
> switch to (initialise) a different element type.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5511#issuecomment-157915157>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Even if we assume this is intuitive, it doesn't work; the filter isn't 
applied once the type is changed even though the filter field isn't cleared.

Aside from that, I think users will potentially be confused if they 
switch types and end up with a filtered view. My feeling is that the 
number of cases where this will confuse people outweighs the number of 
cases where it'll be useful.

**Comment by nvaccessAuto** [comment]
Incubated in b8ac268d261a5067eaefeb5c890a122710aa0c3b.

**Comment by nvaccessAuto** [comment]
Incubated in f392e5a851bd5875dab78cf35edbfc04c907b506.
