### ISSUE TITLE
Ease of Access Center opened upon launch of NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5519]
I've never seen anything like this before, so wanted to open this issue in the hope of possibly being able to gain some more insight as to how this could have actually happened.

Upon a fresh boot of Windows, I noticed that after NVDA had successfully started it's dialog was still present on the screen; this usually indicates that the process took longer than usual, and the dialog hadn't had time to be killed. After looking around the other open windows, I noticed that the Ease of Access Center was open.

I realise that NVDA is now included in the list of available options within EoA from Windows 10 and later, but could this possibly have an effect on Windows 7-based installations also? Somewhat annoyingly, I haven't been able to reproduce the same since - my guess is that it was down to the delay in starting.

**Comment by jcsteh** [comment]
EoA is now used behind the scenes in both Vista and Windows 7, as it's 
somewhat less error-prone than our service and is the way Microsoft 
recommend you do things. However, we aren't listed there due to 
deficiencies in EoA in Windows Vista/7 that make it impossible for us to 
use it completely.

The question is why the EoA Center appeared. We do have to launch it 
behind the scenes (in accordance with Microsoft documentation), but it's 
not supposed to actually appear. There is obviously some weird timing 
issue here, but precisely because it's a timing issue, it's going to be 
very difficult to catch.

**Comment by elliott94** [comment]
This is interesting; I've noticed that since this change was made, my machine takes several more seconds to login. I had originally assumed that this was due to something unrelated, but since EoA is now used in the background upon an initial login do you think this could be the reason? I assume that the background process would still need to be carried out for Vista/7 also?

**Comment by josephsl** [comment]
Hi,

 

If you haven’t already, you need to go to General Settings and tell NVDA not to start after you log in and click OK. Do this again, this time checking the box, then click OK a second time.

**Comment by elliott94** [comment]
Hi, thank you for the suggestion.

In theory, what would this achieve? Surely just unchecking/checking the box would carry out the same steps as are currently being performed, i.e. NVDA starting at boot time?

Thanks.

**Comment by jcsteh** [comment]
Checking/unchecking the box is only necessary on Windows 8 and above, since we want to start with EoA after logon, which means we can start a lot sooner.

In Windows Vista and 7, EoA starts the copy on the logon screen, but not the normal copy. We do have a process which watches the normal copy, but that process doesn't *start* NVDA. On the flip side, we no longer have the service running all the time, so the net impact should be more or less equivalent.

**Comment by ehollig** [comment]
@elliott94, have you had this issue where the Ease of Access Center opens upon launch of NVDA happen again, or was that a one time thing?

**Comment by elliott94** [comment]
No; I haven't seen this since. Happy for it to be closed.
