### ISSUE TITLE
Problem with new Audio Ducking mode

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5536]
The problem is with option "Duck when outputing speech and sounds", which seems to be the default.
When playing music for example, the sound is correctly ducked when NVDA speaks, but forgets to get back to its original level when NVDA stops, wich probably is the purpose of this option.

**Comment by jcsteh** [comment]
What synthesiser are you using? If this works for you with eSpeak, this 
is due to your other synthesiser driver using NVDA's audio output API 
incorrectly.

**Comment by MichelSuch** [comment]
Well, in fact, this option does not work at all when using sapi5. I run Windows 10 64 bits and french Microsoft voice Hortense.
It works fine with Espeak.

**Comment by MichelSuch** [comment]
Hi,

I tried to answer on GitHub but it did not seem to work, need to get 
more clever with it.
In fact, this option does not work at all with a sapi5 synthesizer, I 
use Microsoft Hortense french voice.
It works fine with eSpeak, works partially with another unsupported 
synth I can't name here.
I run Windows 10 1511 64 bits.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by jcsteh** [comment]
Your first reply did work; both did.

This can't be supported with SAPI 5 for now; see [this comment for more details](https://github.com/nvaccess/nvda/issues/3830#issuecomment-159559090).

If it only partially works (e.g. ducks but doesn't unduck) for a particular driver that we don't control, this is due to a problem with the driver and we can't do anything about that.

Note that this is now disabled by default.
