### ISSUE TITLE
Use ui.message more instead of speech.speakMessage and fix capitalization while at it

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#5547]
There are a few cases where messages are spoken but not brailled. Some really are specific to or only desirable for speech, but the majority are useful in braille too. For example, the "no next" message in object navigation.

**Comment by dkager** [comment]
The topic branch shows what I had in mind. The capitalization changes aren't necessary but they make everything look a bit more consistent in braille. This can be taken a little further, but right now I'm most interested in feedback on using `ui.message` more.

P.S. It's amazing how many little things you discover when you start using a product more frequently! :)

**Comment by jcsteh** [comment]
Pull request please... unless there's some reason you're not using one? Actually, this is one of those situations where I'd accept a pr without an issue first, since there's probably nothing to discuss really apart from accepting or rejecting various cases.

**Comment by dkager** [comment]
Sure. Just trying not to be too presumptuous. PR will follow early tomorrow.

**Comment by derekriemer** [comment]
Here is a table with the files in which things NVDA speaks can be safely changed.
The fourth column has important notes for each of these.  Legend for fourth column below.

## Legend:
<dl>
<dt>Yes </dt><dd> I am pretty confident changing this won't break anything.</dd>
<dt>Probably </dt>
<dd>Consult with Other devs because this could break something. It probably can be changed though.</dd>
<dt>Maybe</dt>
<dd>Not sure if this does what I think it does, but I think there is value to adding braille to this. </dd>
<dt>Probably not </dt>
<dd>With reasonable certainty, this should not be changed, however I am not confident. </dd>
<dt> custom braille </dt><dd> This may not be fit to braille directly, we should probably braille a custom message for this. </dd></dl>

## Table.

If you want this in a CSV file I have one.
Sorry some quotes aren't the way they should be, my python script I used to walk NVDA's source looking for speech.speakMessage accidentally removed some quotes while putting it into csv format, because I forgot to escape quotes. I should have just used the csv module.

| File Name | Python code of the line | Line Number | Comments |
| -------- | -------- | -------- | -------- |
| ./source\core.py | speech.speakMessage(_(Loading NVDA. Please wait...)) | 205 | Maybe. Note. Braille display support may very well not exist yet at this point in nvda's loading process. |
| .\source\cursorManager.py | speech.speakMessage(_(no selection)) | 307 | yes |
| .\source\cursorManager.py | speech.speakMessage(_(copied to clipboard)) | 311 | probably |
| .\source\globalCommands.py | speech.speakMessage(_(no selection)) | 203 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(selected %s)%info.text) | 205 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no navigator object)) | 727 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(%s copied to clipboard)%text) | 754 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(move to focus)) | 783 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no focus)) | 795 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no navigator object)) | 818 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(No containing object)) | 827 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no navigator object)) | 835 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(No next)) | 844 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no navigator object)) | 852 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(No previous)) | 861 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no navigator object)) | 869 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(No objects inside)) | 878 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(top)) | 921 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(top)) | 933 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(bottom)) | 961 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(bottom)) | 975 | cYes |
| .\source\globalCommands.py | speech.speakMessage(_(top)) | 988 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(bottom)) | 1015 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(left)) | 1030 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(left)) | 1044 | Yes |
| .\source\globalCommands.py | speech.speakMessage(%d, % c) | 1067 | Yes. Note: dose not use[)}.format style but uses %s style. |
| .\source\globalCommands.py | speech.speakMessage(_(right)) | 1083 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(right)) | 1102 | Yes |
| .\source\globalCommands.py | speech.speakMessage(_(no focus)) | 1258 | Probably. Note: This has no translator's comment  |
| .\source\globalCommands.py | speech.speakMessage(text) | 1337 | Probably (NOTE, I think this may be for testing by devs only though). |
| .\source\mouseHandler.py | speech.speakMessage(_(%s cursor)%curMouseShape) | 139 | Probably |
| .\source\appModules\firefox.py | speech.speakMessage(controlTypes.stateLabels[controlTypes.STATE_BUSY]) | 21 | Maybe |
| .\source\appModules\firefox.py | speech.speakMessage(statusText) | 22 | Maybe |
| .\source\appModules\outlook.py | speech.speakMessage(_(Appointment {subject}, {time}).format(subject=p.subject,time=t)) | 348 |  |
| .\source\appModules\outlook.py | speech.speakMessage(timeSlotText) | 366 | Yes |
| .\source\appModules\thunderbird.py | speech.speakMessage(controlTypes.stateLabels[controlTypes.STATE_BUSY]) | 25 | Maybe |
| .\source\appModules\thunderbird.py | speech.speakMessage(statusText) | 26 | Probably |
| .\source\appModules\totalcmd.py | speech.speakMessage(_(left)) | 35 | Yes |
| .\source\appModules\totalcmd.py | speech.speakMessage(_(right)) | 37 | Yes |
| .\source\appModules\totalcmd.py | speech.speakMessage( .join(speakList)) | 46 | custom braille |
| .\source\appModules\winamp.py | speech.speakMessage(onOff) | 83 | Yes |
| .\source\appModules\winamp.py | speech.speakMessage(onOff) | 95 | Yes |
| .\source\brailleDisplayDrivers\handyTech.py | speech.speakMessage(text) | 30 | Probably not |
| .\source\gui\__init__.py | speech.speakMessage(_(Please wait)) | 808 | Probably |
| .\source\NVDAObjects\IAccessible\sysTreeView32.py | speech.speakMessage(_(%s items)%self.childCount) | 202 | Maybe |
| .\source\virtualBuffers\__init__.py | speech.speakMessage(_(Refreshed)) | 388 | Yes |
| .\source\virtualBuffers\__init__.py | speech.speakMessage(_(use screen layout on)) | 464 | Yes |
| .\source\virtualBuffers\__init__.py | speech.speakMessage(_(use screen layout off)) | 467 | Yes |

**Comment by derekriemer** [comment]
[possibilities.csv.txt](https://github.com/nvaccess/nvda/files/46503/possibilities.csv.txt)

**Comment by dkager** [comment]
Thanks, this helps. I think you missed a few (that incidentally also should probably not be changed). There will be a PR after I capitalized some more things and looked at the app modules. We can then discuss the cases that aren’t a clear ‘Yes’.

**Comment by jcsteh** [comment]
Going to close this and use the PR instead because there isn't really much to discuss apart from accepting/rejecting specific cases.
