### ISSUE TITLE
bug: NVDA says "unknown" randomly when firefox is in focus

### ISSUE THREAD

**Issue by marrie** [nvaccess/nvda#5550]
Summary: firefox sometimes will say unknown when using nvda and you focus firefox. I'm using the latest of windows 7, firefox and nvda snap
1. Launch windows.
2. Launch nvda
3. Launch firefox and use it.

Notice that the work around when unknown happens is to alt tab away from and back to  firefox. I have not seen this in any other browser but this is a high importance bug in my opinion that should be looked in to. It has been reported before but since it's hard to reproduce I can't really include any logs as of now.

**Comment by ehollig** [comment]
I am not able to replicate this. NVDA does say unknown when Firefox is launched, but does not say unknown when Firefox is in focus.

**Comment by Brian1Gaff** [comment]
Several things here. it can say unknown on very slow pages or on very slow 
machines occasionally, but its better it does this than sits there saying 
nothing at all.
 Often as has been observed, Firefox can fail to get a page and goes into a 
kind of sulk, but bringing up a menu, cancelling it and doing a page refresh 
can sort it. Since this seems to be firefoxs fault not nvda, then unknown is 
probably right!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@marrie can you still reproduce this issue? If yes, could you please run the com registration fixing tool in NVDA menu / tools? Does that solve it?

**Comment by Adriani90** [comment]
We do not have any update on this since more than two years and I am prety sure that com registration fixing tool solves this issue. I cannot reproduce in in NVDA 2019.3 Beta 1 and Firefox 72.0.1. Closing as works for me and abandoned.
