### ISSUE TITLE
Review cursor jumps to last line in dynamic command line windows

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#5560]
Lately, I've using wget to download some files, and I found out that when the download is progress and hence the last line is dynamic, NVDA's screen review doesn't let me review the entire screen. This, interestingly, is solved by using the Virtual Revision addon, which appears to take a snapshot of the window.

**Comment by jcsteh** [comment]
While I understand why this isn't desirable here, it is expected behaviour and we can't compensate for it without breaking caret tracking. Whenever that progress updates, it moves the caret, so NVDA moves the review cursor to the caret because you have the review cursor set to follow the system caret. If you don't want this, disable follow system caret. You can do this quickly by pressing NVDA+6 (that's NVDA plus the number 6 on the main number row).
