### ISSUE TITLE
Copy Current Configuration to Secure Screens: Add Remove button to General Settings Dialog

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5585]
Currently, NVDA allows a user to copy their settings to the systemConfig directory of NVDA's install location; this process can easily be achieved by simply activating the relevant button from within the General Settings dialog.

Whilst this function works as expected, unless the user is somewhat advanced an option does not currently exist that easily allows the removal of these settings. I can think of two possible ways of easily implementing this (starting with the preferred):

1. Keep a single button in the General Settings dialog, and change it's title to "Add/remove currently saved settings on the logon and other secure screens (requires administrator privileges)". When activated, NVDA would search for the existence of the systemConfig directory, and depending on the result either copy the user's current settings as is currently done, or prompt the user as to whether they are sure that they wish for the directory to be removed.

2. When the user first chooses to copy their current settings, a value could be inserted within NVDA's configuration file; upon launching, NVDA would search for the existence of this value, and depending on the result carry out a different action when the button is pressed from within General Settings. The downside of this method is that in theory, a user could manually remove the systemConfig directory themselves, and as a result the value within nvda.ini has the potential to be out-of-date and not reflect the current state of the directory.

**Comment by jcsteh** [comment]
What's the use case for this? Presumably, most users might want the system config to reflect their current config, but i can't see a good reason for them to want to revert it to the default configuration. One reason would be if their configuration was broken, but in that case, their user configuration would also be broken, in which case they would fix their own config and then copy it again.

IMO, "Add currently saved settings on the logon and other secure screens" doesn't make a huge amount of sense. Remove is even worse because they're not technically removing *current* settings; they're removing what was there, which might be very different settings.

**Comment by elliott94** [comment]
My initial idea was that the addition of this functionality would mainly be useful for new users; somebody may, for example, install NVDA and make some customisations, at which point copy their current config using the button found in General Settings. As a new user to NVDA (and perhaps Windows for that matter), they may not know where the settings are placed, or even that pressing the button again would allow them to overwrite the current configuration that had initially been placed. Furthermore, what if the user simply decided that they wanted to have the default configuration whenever a Secure Screen was encountered? I realise that this last scenario may be unlikely; that said, I don't think it's currently made that clear as to how settings can be removed.

**Comment by jcsteh** [comment]
> As a new user to NVDA (and perhaps Windows for that matter), they may not know where the settings are placed,

I'd argue this isn't necessary. Why should a new user care? They only need to care that these settings will now be used on secure screens, just as the button suggests.

> or even that pressing the button again would allow them to overwrite the current configuration that had initially been placed.

I don't follow. The button says "Use currently saved settings on the logon and other secure screens". So, a user should read from this that their current settings will be used on secure screens; what was used previously is irrelevant. Can you explain how a user might misinterpret the label of this button? We certainly want to tweak the label if it could be misinterpreted.

> I don't think it's currently made that clear as to how settings can be removed.

Sure; it isn't specified at all. My point is that I'm not convinced it's necessary.

**Comment by elliott94** [comment]
You're right that a new user may (or shouldn't) need to care where the settings are placed; the reason I mentioned this was due to my initial thought process behind this issue. If a new user later decides that they don't want an alternative configuration set activated whenever a Secure Screen is encountered, apart from manually reverting NVDA's configuration back to default and explicitly re-saving the configuration using the button in the General Settings dialog, how should they achieve this?

In terms of the label, on second thoughts the point I was trying to get across is that a user may not know how settings can be removed, which in my opinion is the somewhat bigger issue here. Taking the above into account, how would you suggest a relatively new user should go about removing their settings?

Finally, this discussion has ultimately lead me onto a related idea. Would it not just make more sense to use a consistent configuration across the entirety of NVDA, rather than having two potentially different states? I realise that this would make my last couple of comments somewhat irrelevant and that there may be other issues related to permissions that would prevent this, but would it not make more sense overall to use this approach rather than the current implimentation? This would also allow separate users on the same machine to use their own settings whenever a Secure Screen is activated, which if I understand the current implimentation is not possible due to the fact that only a single set of data can be present in the systemConfig directory.

**Comment by jcsteh** [comment]
> If a new user later decides that they don't want an alternative configuration set activated whenever a Secure Screen is encountered

My point is: is there actually a real world use case for this? Would a user ever want to do this? Have you ever needed to do this? It makes sense that a user might want to update the config, but I don't see removing it being common. Obviously, it's not impossible that someone might want to do this and flexibility is nice to have, but nice to have isn't enough to justify a confusing user experience. I believe adding yet another button or making the existing button do two different things is confusing.

> Would it not just make more sense to use a consistent configuration across the entirety of NVDA, rather than having two potentially different states?

It doesn't make sense when you take multiple users into account.

* On the logon screen, no user is logged in yet, so which config do you use? The answer can't just be default here because some people won't like this.
* While other secure screens are partially associated with a user, they aren't entirely from a practical standpoint. For example, imagine you have a multi user machine. Alice logs in, does some stuff, then locks the system. Bob comes along and wants to use the system. Bob can switch users, but Bob can't understand Alice's speech configuration, so there's no chance of doing that. The point is that the configuration on secure screens needs to be something that all users will be happy with, regardless of who is logged in.
* From a security standpoint, NVDA on secure screens runs as the system user, so it's not safe to run an arbitrary user configuration (not approved by an admin) with add-ons, etc.

**Comment by elliott94** [comment]
I've only personally wanted to change certain aspects of the configuration after initially copying it to the systemConfig directory, which has always involved manually editing the contents of files within the directory itself. I realise that this may be a separate issue altogether, but to answer your question directly - no, I've never wanted to remove custom configuration.

Thank you for the insight into the second issue - I knew that you'd probably be able to point out why this wouldn't in theory be a good idea. I'm glad I asked! :)

**Comment by jcsteh** [comment]
While I understand that it's not impossible that someone might want to do this, I'm going to wontfix this given that we don't have a strong real world use case, the potentially ugly user experience this might create and the implementation effort. Regardless, thanks for taking the time to make the suggestion.

**Comment by elliott94** [comment]
No problem at all. Thank you for your feedback - I always find it interesting to get the viewpoint from a developer, and as with this example you provided insights that I hadn't considered.
