### ISSUE TITLE
Focus not given to link in browse mode by line

### ISSUE THREAD

**Issue by Chido42** [nvaccess/nvda#5594]
Hello,

In the following example:
https://jsfiddle.net/ohoegdhy/7/
Using Firefox 42.0 and NVDA 2015.3. When reading by line with down and up arrow the focus is not given to the link. You have to specifically go the link using ctrl+right arrow to be able to focus it.

In some cases it seems the focus is given to the link but I am not sure why some links are focused and some others not. Is it when the link is at the start of the virtual cursor ?
For example on the [NVDA wikipedia page](https://en.wikipedia.org/wiki/NonVisual_Desktop_Access) 

In the presentation text:
NonVisual Desktop Access (NVDA) is a free, open source, portable screen reader for Microsoft Windows. The project was started by Michael Curran in 2006.
NVDA is programmed in Python. It currently works exclusively with accessibility APIs such as Microsoft Active Accessibility, IAccessible2 and the Java Access Bridge, rather than using specialized video drivers to "intercept" and interpret visual information. It is licensed under the GNU General Public License.

If you read using down arrow the presentation only the links  Microsoft Active Accessibility and GNU General Public License will get focus. Other links are not focused.

I am not sure if this is a bug or if it is working as expected.

Thanks and regards,

**Comment by jcsteh** [comment]
This is expected behaviour. NVDA focuses the element under the browse mode cursr. When you move by line, the cursor moves to the start of the line. With NVDA's default of screen layout enabled, inline elements are rendered on the same line, so a link in the middle of a line won't be under the cursor when you move by line and dthus won't be focused. In contrast, a link at the start of a line will be under the cursor when you reach that line, so it will be focused.

Note that if you disable screen layout, links will always be rendered at the start of their own line.
