### ISSUE TITLE
Test comparison in 2015.3 versus 2015.4 in Mozilla Thunderbird

### ISSUE THREAD

**Issue by rbmendoza** [nvaccess/nvda#5616]
I made some comparison test to my two machine with different version
of nvda. Both are running into Windows 10 platforms. The mentioned
test scenario was from 2015.3 versus to 2015.4.  This is simply a
simple test that I've render this afternoon, while trying to creating
and opening of an email message in Mozilla Thunderbird. Note that the
setup was into a default mode, and nothing has been change from the
configuration settings of nvda. The mentioned two version is installed
as fresh copy.

Here are the details:in 2015.4 it send back or echoed entirely the
whole screen, but in 2015.3, the reading was fine and the focus was
directly into the edit field for the TO entry where you add the email
address. And, lastly when you hit or open email message in 2015.4 is
repeatedly spoken the subject line, but to the 2015.3, the reading of
the message was directly to the content of the email message, which is
the proper and effective way to reads by nvda. Not so sure if there is
an open ticket or has been raised to fix this , in order to correct it
in the next release. Thanks.

**Comment by leonardder** [comment]
@rbmendoza: I'm not sure if I understand your issue correctly. Anyhow, do you still think there has been a regression somewhere?

**Comment by ehollig** [comment]
@rbmendoza could you respond to @leonardder's question in https://github.com/nvaccess/nvda/issues/5616#issuecomment-315822020

**Comment by Adriani90** [comment]
So the issue here is:
1. NVDA reads the whole Screen when creating a new message in Thunderbird and does not move the Focus directly in the to: address field and
2. NVDA repeats the subject line of the message when opening it.
Expected behavior:
1. NVDA should move the Focus directly in the to: address field when creating a new message and
2. NVDA should start reading the message Body directly after pressing enter on a message and should not repeat the subject line.

@bdorer, @novalis7747 could you please test if These issues are still occuring in NVDA 2018.4.1?
Thanks.

**Comment by Novalis7747** [comment]
clean NVDA 2018.4.1, TB 60.5:
1) creating a new message with control-n reads the subject and then the focus is in the TO field - normal behavior
2) when reading new messages NVDA repeats the subject of the message (window title) 3 times, the first 2 times are spoken in a row, then you hear "busy, loading" and then the third time. After that the focus is in the message body.  beside of the first 2 times title speaking in a row a normal behavior.

**Comment by Adriani90** [comment]
I will close this in favor of new created issue #9247. @Novalis7747 feel free to comment on that issue in case I forgot something. Thanks.
