### ISSUE TITLE
NVDA always starting on taskbar

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5632]
Hi,

Some users complain that NVDA always start on taskbar instead of immediately getting focused on the active window.
The only case where it does not happen is when updating NVDA, when it restarts after update.

**Comment by Brian1Gaff** [comment]
This seems pretty random to me. I have no idea what its using but I'd suspect that it depends what the last thing focussed it sees is where it goes. Its a bit like when Windows7 starts and you find the  focus nowhere at all sometimes, and you have to  use the keyboard shortcut for the desktop, but at other times it might be the start button, or desktop.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: MichelSuch 
  To: nvaccess/nvda 
  Sent: Wednesday, December 23, 2015 8:35 AM
  Subject: [nvda] NVDA always starting on taskbar (#5632)


  Hi,

  Some users complain that NVDA always start on taskbar instead of immediately getting focused on the active window
  The only case where it does not happen is when updating NVDA, when it restarts after update

**Comment by jcsteh** [comment]
When NVDA starts, the foreground window goes back to whatever it was just before it started. Unfortunately, when you use Explorer shortcut keys in Windows 7 and later, it throws you onto the Taskbar. You'll notice that if you restart it from the Run dialog, you land on the Desktop. So in short, this is what Windows is choosing to do.
