### ISSUE TITLE
Excel: Possible Missed data due to Merged Cells

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5637]
I realise that this isn't a problem with NVDA exclusively, but I wanted to open this to get other people's thoughts.

When navigating within an Excel worksheet that contains merged cells, the cursor automatically jumps past these when navigated to; for example, if cells A2-A5 were merged, a down press of the cursor on A1 would jump the user to A6. This is all good; however, if there is data in adjacent cells (B2-B5), there is a large possibility that this would be missed. Many users would never have to deal with the concept of merged cells, and whilst cursor behaviour is the same whether or not any screen reader is being used sighted users would physically be able to see that data existed in those cells that a screen reader user may miss; this has happened to me many times, and since I prefer not to have cell references enabled the probability of this occurring increases.

Does anybody have any thoughts on how this potential issue could be approached? My initial thought was to simply treat any merged cells that are focused in Browse Mode as regular cells; however, I realise that in reality better solutions most likely exist that I'm just not thinking of right now.

**Comment by Laughingthunder** [comment]
My understanding, is that all data in cells, except for the top left cell, will be deleted when the cells are merged. So cited users would miss the data as well.

**Comment by elliott94** [comment]
This is correct; however, I was referring more to cells in columns next to the merged cells that could be missed if a merged cell is navigated to by a user.

**Comment by jcsteh** [comment]
If you have cell coordinates enabled, you won't miss the fact that 
you're dealing with emerged cells and would thus be aware that you 
needed to check adjacent cells. I really don't see a better way we can 
do this. The only alternative would be to show every cell in browse 
mode, but that's flawed because you would either get a lot of repetition 
or see a lot of blank cells which didn't exist (depending on how it was 
done). If we showed them as blank cells, this would cause problems when 
returning to a merged cell from an adjacent cell in the middle of the merge.

**Comment by elliott94** [comment]
This is true, and maybe just something that by design should stay as is. Shall I close this?

**Comment by jcsteh** [comment]
I understand the request and it'd certainly be nice to have a quicker way to deal with this. However, I can't think of anything that doesn't cause other equally annoying problems. If someone can come up with a user experience that doesn't suffer from this, we can consider reopening this.
