### ISSUE TITLE
Suggested enable performing OCR PDF documents

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5679]
Good afternoon dear.
 One suggestion I would make is the possibility to perform OCR on a PDF document.
 This is a demand that arose in my work, reading PDF documents without accessibility, where the only way to read is doing using an OCR.
 Using an evaluation copy of the jaws could read the document, but with NVDA got unsuccessful.
 Tried using the OCR add-on available in page downloads of NVDA supplements.
 Thank you, and sorry for any errors or lack of clarify for me.

**Comment by jcsteh** [comment]
Bundling an OCR engine with NVDA is not feasible. A commercial engine can't be bundled because these are paid products and NVDA is a free product. Aside from that, bundling a free engine isn't feasible because of file size, which is why the OCR add-on is a separate add-on.

There are other standalone OCR products which are probably better suited to this task at this stage.

**Comment by fernando-jose-silva** [comment]
thank you so much.

 

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: segunda-feira, 18 de janeiro de 2016 01:00
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>
Assunto: Re: [nvda] Suggested enable performing OCR PDF documents (#5679)

 

Bundling an OCR engine with NVDA is not feasible. A commercial engine can't be bundled because these are paid products and NVDA is a free product. Aside from that, bundling a free engine isn't feasible because of file size, which is why the OCR add-on is a separate add-on.

There are other standalone OCR products which are probably better suited to this task at this stage.
