### ISSUE TITLE
NVDA does not count accessible rows and columns correctly when using role=presentation

### ISSUE THREAD

**Issue by mpreyskurantov** [nvaccess/nvda#5717]
Use the following HTML Table markup to reproduce the issue:

```
<table>
    <thead>
        <tr>
            <th><a href="#">First header</a></th>
            <th>Second header</th>
        </tr>
    </thead>
    <tbody>
        <tr role="presentation" style="height: 0; font-size: 0; border-width: 0;">
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>First cell</td>
            <td>Second cell</td>
        </tr>
    </tbody>
</table>
```

NVDA reads this markup in the following manner:

_table with 3 rows and 2 columns
row 1 column 1
First header
link_

The first data row has the role="presentation" attribute and should not be counted (i.e., should not be treated as a data row).
Another possible way to avoid counting such a row as a data row is to use the illustrated style.

The expected pronounced state is the following:

_table with 2 rows and 2 columns
row 1 column 1
First header
link_

**Comment by jcsteh** [comment]
Aside from IE, this is something that would need to be addressed in browsers, since NVDA gets table info from the browser.

That said, I'd argue having a row with role="presentation" is quite broken and shouldn't be permitted anyway. role="presentation" doesn't "hide" the content within; it only marks the element itself as presentational. So, you'd end up with content in the table between rows which isn't a cell. That leaves you with a broken table which you can't navigate properly. A table can't contain arbitrary content like that; it has to be within a caption or a cell. This is probably why browsers currently ignore role="presentation" in this case.

It might help if you can provide a use case.

**Comment by leonardder** [comment]
@mpreyskurantov: Note that NVDA works according to your expectations when using IE. Firefox and Edge report 3 rows, while Chrome even ignores the fact that this is a table. I think that this supports @jcsteh's comment in https://github.com/nvaccess/nvda/issues/5717#issuecomment-176480245, saying that this should be treated as unpermitted code. Therefore, I"m inclined to close this, but will leave it open for another week to allow some discussion to take place first.

**Comment by Adriani90** [comment]
This might be related to #7852, where @feerrenrut provides a valuable reason for the different treatment of tables in different browsers. Note also comments in #7913.

**Comment by leonardder** [comment]
I'm closing this as per above comments.
