### ISSUE TITLE
Getting "scons: *** [dist] Error 1 scons: building terminated because of errors." while doing "scons source". PLEASE HELP

### ISSUE THREAD

**Issue by akp1985** [nvaccess/nvda#5753]
Install file: "build\x86\liblouis\liblouis.dll" as "source\liblouis.dll"
Install file: "build\x86\liblouis\liblouis.dll.pdb" as "source\liblouis.dll.pdb"
Install file: "build\x86\liblouis\liblouis.exp" as "source\liblouis.exp"
Install file: "build\x86\liblouis\liblouis.lib" as "source\liblouis.lib"
espeak_compileDict_action(["source\synthDrivers\espeak-data\mt_dict"], ["include\espeak\dictsource\mt_rules", "include\espeak\dictsource\mt_list"])
espeak_compileDict_action: failed to switch to language mt, skipping compilation
espeak_compileDict_action(["source\synthDrivers\espeak-data\tn_dict"], ["include\espeak\dictsource\tn_rules", "include\espeak\dictsource\tn_list"])
espeak_compileDict_action: failed to switch to language tn, skipping compilation
espeak_compileDict_action(["source\synthDrivers\espeak-data\tt_dict"], ["include\espeak\dictsource\tt_rules", "include\espeak\dictsource\tt_list"])
espeak_compileDict_action: failed to switch to language tt, skipping compilation
<lambda>(["dist"], ["source", "user_docs"])
cd source && C:\Python27\pythonw.exe setup.py build --build-base C:\Users\pathaa5\Desktop\nvda\build py2exe --dist-dir C:\Users\pathaa5\Desktop\nvda\dist
scons: *** [dist] Error 1
scons: building terminated because of errors.

**Comment by jcsteh** [comment]
For some reason, you seem to be using pythonw.exe instead of python.exe. Perhaps you associated .py files with something other than python.exe (which is the default)? If you did that for a reason, try starting a command prompt, changing to the NVDA repository directory and running:
`c:\python27\python.exe scons.py source`

Btw, for future reference, since this is a request for help and not a bug or feature request, it would be better posted on the [nvda-devel email list](https://lists.sourceforge.net/lists/listinfo/nvda-devel). Thanks.
