### ISSUE TITLE
When using Firefox, pressing the tab or K key to move forward to the next control causes NVDA to sometimes read more than one link if the links contain drop-down menus

### ISSUE THREAD

**Issue by dgoldfield** [nvaccess/nvda#5756]
This bug occurs with the latest RC for 2016.1 with the latest version of Firefox.
When on the page
https://www.mozilla.org/en-US/thunderbird/
there are links with drop-down menus, such as "releases, submenu."
When pressing the tab key or the letter K on this page, NVDA consistently reads all of these submenus all at once, rather than reading one at a time. I do not believe this behavior occurred with 2015.1.

**Comment by jcsteh** [comment]
I just tested and this definitely occurs with NVDA 2015.1. I'd say this is actually due to a change in Firefox, which now correctly supports something that it didn't previously (the aria-owns attribute). The mozilla.org site you mention uses this attribute, but doesn't account for the fact that doing so will cause this rather annoying label. This is not a bug in Firefox or NVDA, but rather, it is a problem with mozilla.org.
