### ISSUE TITLE
jQuery UI Datepicker: NVDA preceeds speech with "blank" while announcing highlighted date

### ISSUE THREAD

**Issue by noobards** [nvaccess/nvda#5765]
When the datepicker is initiated and the user moves between dates (Using ctrl + left/ctrl+right/ctrl+up/ctrl+down combo), NVDA first says "blank" and then announces the date. Upon using the combo, I populate a div with the current selection using the keyup event on the input field.

I assume NVDA says "blank" because the focus is set to the input field and not the datepicker DOM, but is there a way to avoid announcing "blank"?

I'm attaching the demo with this message. Please advise.
[datepicker.zip](https://github.com/nvaccess/nvda/files/139577/datepicker.zip)

**Comment by jcsteh** [comment]
You're correct; NVDA says blank because the focus is on a text input and caret commands should read the appropriate text in text inputs. There is no way to disable this if focus remains on the text input; NVDA has no way of knowing that you've overridden these commands to do something other than their standard function.

If you type into the field and position your cursor over one of the characters, you'll actually get the word at the cursor instead of "blank".

While implementation is of course entirely up to you, I'd suggest there are more appropriate ways to implement this. Aside from the issue you've reported, it won't work well for braille users. I'd suggest you do something similar to the ARIA pattern for combo boxes; i.e. use aria-activedescendant to focus the selected item or similar.

**Comment by noobards** [comment]
Hi,
I tried following your suggestion (using arai-activedescendant) but unfortunately, the output is the same. The word "blank" gets read before the date. 

So I was hoping if there are any other suggestions you might have that I could try out in order to solve this?

**Comment by jcsteh** [comment]
That suggests the descendant isn't getting focus for some reason. If it 
isn't a DOM child of the input (which, come to think of it, it won't 
be), you may need to use aria-owns as well.

**Comment by noobards** [comment]
Thanks for the lightning fast reply :)

I will definitely try that out at my end. Meanwhile, if it's not asking for too much, can you perhaps lend me your expertise? I have the files attached in my opening post. I would really appreciate it if you can push me in the right direction. ARIA is a new topic for me and hence I'm not sure if I'm doing it the correct way.

**Comment by noobards** [comment]
Ok. I did make some progress. I put the "aria-owns" on the input box and "aria-activedescendant" on the datepicker popup container (table tag). Doing this solves the problem in Firefox but doesn't in Chrome and IE. Is there a special attribute that I need to put in in order to make them work in Chrome and IE? If you want, I can put up a fiddle for reference.

**Comment by manilak07** [comment]
Did you find for chrome?
