### ISSUE TITLE
NVDA reads footer links when use tab mode from the top of the page

### ISSUE THREAD

**Issue by ikuznalex** [nvaccess/nvda#5801]
Steps to reproduce:
1. Go to any accessible website. For example, http://webaim.org/
2. Move focus using 'tabbing' to the footer of the page. 'Tab' multiple times more to move focus to the top of the page. (Focus will be moved from footer to the browser controls and to the page itself again).  
NVDA reads page's title and then links from the footer. Next 'tab' will move focus to the first element of the page.

Expected result: NVDA reads only document title but not footer links.
Browser where detected the issue: Mozilla Firefox 44.0.2.

**Comment by jcsteh** [comment]
When the document gets focus, we read the line on which the cursor is located, just as we do in a word processor or text editor which is thus what users expect in browse mode. When you tab back to the document, the line on which the cursor is located is the bottom line, since that's where you last were. To understand this another way, try alt+tabbing out and back in again after tabbing to the footer links. You'll see exactly the same result because focus returned to the document. This is intended behaviour.
