### ISSUE TITLE
When does NVDA announce an element as clickable?

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#5830]
I found out that NVDA sometimes announces an element as clickable, and sometimes it doesn't.

I have written a comprehensive thread about this on StackOverflow, it would be great to hear the opinion of you NVDA guys, too!

http://stackoverflow.com/questions/36151647/are-there-ways-to-react-upon-a-click-without-adding-an-event

**Comment by jcsteh** [comment]
1. NVDA will consider reporting clickable if the node has click, mouseDown or mouseUp event handlers.
2. However, if the element is inherently clickable or it just isn't useful to report clickable for that element, it won't be reported. Currently, this means that it isn't reported for the following control types: ROLE_LINK, ROLE_BUTTON, ROLE_CHECKBOX, ROLE_RADIOBUTTON, ROLE_TOGGLEBUTTON, ROLE_MENUITEM, ROLE_TAB, ROLE_SLIDER, ROLE_DOCUMENT, ROLE_CHECKMENUITEM, ROLE_RADIOMENUITEM

For future reference, please note that this is not the correct place for a question like this. At this stage, the issue tracker is only for reporting bugs or feature requests, rather than asking questions. Technical questions like this belong on the [nvda-devel email list](https://lists.sourceforge.net/lists/listinfo/nvda-devel). Thanks.

**Comment by hulmerous** [comment]
What does "clickable" exactly mean. "Clicking" won't lead them anywhere. Is it referring to the fact that you can select and copy/paste the text? 

Why does it repeat 'clickable' 8 times in some situations?

**Comment by Brian1Gaff** [comment]
Most repeat clickables I've looked at suggest that there are actually 
multiple elements there all unlabelled and all that is revealed about them 
is that they can have some active action performed on them, its much like 
when buttons are not labelled and you hear button repeatedly. In these cases 
its normally the site authoring which is not very good for access.
 I find often that if clickable seems to do nothing this is because although 
something changes somewhere its not flagged as a change. Often  going around 
the page I do find some changes, and sometimes I need to refresh the page to 
find it, once again, a site authored for the sighted I suspect. More and 
more things like hovering a mouse pointer over some odd element is supposed 
to bring up extra info, much like onGithub contributors names etc, according 
to a sighted friend but we have no idea what the function actually is, so 
clickable is what you get.

I'm sure others who know why this is seemingly an increasing issue might 
want to chip in here.
 Whether anything can be done about it from the screenreader point of view 
is debatable.
 Brian

**Comment by bradjcoughlin** [comment]
@Brian1Gaff I realize this is an old thread, but I've found that sometimes excess 'clickable' announcements are caused by event listeners that are targeting too many elements on the page. For example, jQuery makes it easy to target all elements using the star selector `$('*')` and `.on('click', function( // do something or nothing ));` which indicates to NVDA it is clickable, even if nothing happens or if the targeted element is "filtered out" by logic in the listener function.
