### ISSUE TITLE
can't handle enter with NVDA

### ISSUE THREAD

**Issue by afiorenza** [nvaccess/nvda#5840]
Hi, In windows and firefox NVDA is handling enter and intro in a different way. I have some logic if enter is pressed and nothing happend, but if i press intro it handle okey.

This bug doesn't happens on firefox in ubuntu.

Thougts?

**Comment by jcsteh** [comment]
What do you mean by "intro"? Is this perhaps a translation error?

**Comment by afiorenza** [comment]
I meant that if i press intro key from the numeric keyboard it's works, but if i press enter from the common keyboard NVDA was handling it as a click and it works wrong.

**Comment by jcsteh** [comment]
When in browse mode, NVDA uses the enter key to activate the item under the cursor. In most cases, this means a click. This is done in order to support controls which do not have keyboard support (of which there are many).

If you explicitly want to pass the enter key through, you can switch to focus mode with NVDA+space or pass the key through with NVDA+f2.
