### ISSUE TITLE
dark screen

### ISSUE THREAD

**Issue by hatserdevlats** [nvaccess/nvda#5856]
Is it possible to add a dark screen function to NVDA?

**Comment by josephsl** [comment]
Hi, dark screen as in screen curtain?

**Comment by hatserdevlats** [comment]
Yes

**Comment by josephsl** [comment]
Hi, What are some use cases for this? Do you see drawbacks to this issue? The reason I ask is that we wish to gather insights before investigating this. Thanks.

**Comment by fernando-jose-silva** [comment]
Good afternoon, I liked the idea.
For me one of the great utilities would be when for example the use of a bank site, reading the stratum of the bank account, we never know for sure who is behind us watching the computer screen.
Another example would be to read a pay stub (proof of receipt of wages of a company), to read bills like telephone or light (energy), among others.
We often use the computer in a place with many people and in companies, libraries, restaurants, and the people around are not reliable.
This would be an innovative and usefulfunctionality to the windows, which is present in some other systems such as the ios with voice over.

**Comment by hatserdevlats** [comment]
I totally agree with Fernando. This feature is available on iOS and 
Android, so why not on Windows.

**Comment by josephsl** [comment]
Hi, I feel uneasy (at least for me). There are privacy screens that can be placed over monitors, and you can lower the brightness settings on some systems. Privacy guarantee should not be the reason for implementing this. On the other hand, using it to let developers experience how an app would “look like” if a screen reader user is interacting with it is a good reason for implementing it. If there is no justifiable reason, then I think we should move on (and no, I’m not angry; I’m doing this in order to let you think and make reasonable decisions, as NVDA is a quite a sophisticated software package). Also, please do not assume that NVDA is Windows – it is not, and it’s not a toy project (it requires dedication from tens of hundreds of contributors). Thanks.

**Comment by jcsteh** [comment]
I think privacy is a fair enough argument for a screen reader because a blind user may not be aware of who might be looking at their screen, whereas a sighted user usually would be. That said, I looked into this a while ago and I don't think there is a way for us to do this in Windows.

The workaround is to press Windows+p and switch to "second screen only", but that has some annoying side effects and obviously isn't what you want if you do actually have a second screen connected.

Closing because I don't think this can be done, but if anyone has any technical thoughts on how it could be done, we'd love to hear them.
