### ISSUE TITLE
"Grouping Required" is spoken when tabbing into fieldset containing radio buttons

### ISSUE THREAD

**Issue by ianmclean2011** [nvaccess/nvda#5884]
Just curious about what this means, and why NVDA is saying it? Any clear reasons why?

**Comment by jcsteh** [comment]
We can't provide any info without more thorough details. A test case would be best.

**Comment by ianmclean2011** [comment]
Sorry, I think I understand what is going on now. I added an aria-required attribute, which was set to true. After it read the legend, I think it was saying "grouping" to let the user know that it was a grouping of something, and then immediately saying "required" because required was set to true. I didn't realize that it would say "grouping". Sorry to raise this as an issue ... I'm still very new at using NVDA, and I couldn't find anything online that explained this.

**Comment by jcsteh** [comment]
No problem. For future reference, please only use GitHub issues to report bugs, feature requests, etc. For technical questions that aren't bugs or feature requests, please use the [nvda-devel email list](https://lists.sourceforge.net/lists/listinfo/nvda-devel). Thanks.

**Comment by Brian1Gaff** [comment]
At a rough guess if these are online radio buttons or checkboxes as one 
might find in some kind of online form. The creator of said form may well 
make the system speak required as an indication that you have to select one 
of the options to actually move on.
 I've seen this a lot recently on questionnaires. It used to be that they 
said  * indicates a required field, but often the star was not spoken due to 
the punctuation level in use, and the required tag is actually a much better 
way. Unfortunately if you have never come across it before it can be a bit 
odd
 Of course if this  dialogue is not an online form and is part of a program, 
the setting may well still be mandatory, but normally a sensible default is 
already set.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
