### ISSUE TITLE
NVDA announces "Document" in Internet Explorer if Automatic Say All on page load is unchecked in Preferences\Browse mode

### ISSUE THREAD

**Issue by JamesMozer** [nvaccess/nvda#5920]
Hello,
If I uncheck Automatic Say All on page load in Preferences\Browse mode, NVDA announces "Document" in Internet Explorer after loading any webpage.
For example, when opening nvaccess.org, NVDA says "NVAccess Document". or when opening google.com, NVDA says "google document".
Note that I am having his issue only in Internet Explorer 11 and not in other browsers like Firefox.
Thanks.

**Comment by jcsteh** [comment]
I get "(title) document" in Firefox as well. This is in fact intentional. With auto say all enabled, it's very obvious that you've landed in a document because the entire content reads. With auto say all disabled, this isn't necessarily obvious, so we report document to make it extra clear.

**Comment by JamesMozer** [comment]
OK, But I think there should be an option for it. What if a user do not like to here "document" anyway? So I am forced to keep Automatic Say All on page load on?
Not a great idea...

**Comment by jcsteh** [comment]
Hearing "document" is much shorter than hearing the entire document. 
Furthermore, you could just as well argue you don't want to hear 
"dialog" or any other control type. Having configuration options for 
every one of these cases would make for extremely complicated configuration.

**Comment by JamesMozer** [comment]
So there's no way for getting rid of it? Sure, I can stop using NVDA at anytime, so do not recommend that option.

**Comment by jcsteh** [comment]
No. Sorry.

**Comment by josephsl** [comment]
Hi all,

In order to reduce possible misunderstandings, I think we need to look at this from multiple angles, chiefly technical and user experience perspectives:

* User side: as far as users would "see" it, webpages are documents. Although we now have web apps, standards and so on, the original principle behind web browsing remains the same: a two-dimensional document (we might see three-dimensional websites). Also, we need to keep in mind that different web browsers work differently and have varying levels of accessibility  and standards conformance, thus I think developers felt it best to label webpages as documents. As for inconsistencies: I think it is best to test it with multiple versions of the same browser (Firefox stable versus ESR, for instance). I can quickly confirm that the behavior you're describing also happens in MS Edge.
* Technical: We're working with different rendering engines, and different browsers use different ways of communicating with NVDA (and other screen readers) in order to give meaningful information. For this reason, NVDA source code has different base classes suitable for different rendering engines (MSHTML for IE, Gecko for Mozilla apps, Edge for Edge and friends, Chromium for Chrome, Web Kit for iTunes browse mode and so on). Due to sheer number of different web rendering and conformance implementations, it isn't feasible to turn off "document" mode for specific browsers, which would look bad when looking at this from user experience perspective (see above).

Personally, I concur with @jcsteh: when we look at user experience perspective, it would be best to leave it as is. Note that NVDA isn't just composed of Python files: we have another dimension to consider, and that is user experience.

To our friend: Note that I'm not being harsh to you. I was thinking that we should sit down and think about this issue from multiple perspectives in hopes of reaching something concrete. If we misunderstood your last message (to some, it may have sounded a bit odd), we sincerely apologize.

Hope this helps. Thanks.

**Comment by JamesMozer** [comment]
Hello,
I sincerely thanks for this information. I found it very favorable from the above "dictating" reply.
I agree, but I am still hoping to be able to correctly turn off that "document" announcement. Maybe just by editing some NVDA's files? I am not finding it useful or informational.
Thanks.

**Comment by jcsteh** [comment]
> I found it very favorable from the above "dictating" reply.

FWIW, I wasn't trying to be harsh or unsympathetic. I attempted to clearly explain the reasons for this decision above. I understand that everyone has their preferences for verbosity and we try to cater for these when we can, but there are also limits to the number of possibilities we can cater for before things get overly complex.
