### ISSUE TITLE
ARIA tabs list not usable

### ISSUE THREAD

**Issue by alastc** [nvaccess/nvda#5950]
Hi,

Sorry, not the best bug title, but it's hard to describe.

When using an ARIA tabs widget, such as:
http://a11yideas.com/testcode/tabs/tabs_with_ARIA.html

When arrowing through the tabs they are announced, but all read out in one go, you can’t move between them. The tab panel is not announced, and there is no way of selecting a tab without manually going into forms mode.

Tabbing through, selecting a tab with the arrow keys does work, but then you have to manually exit forms mode.

Apparently if you uncheck "use screen layout (when supported)" then it works fine, but I don't think that should be needed. Some discussion on that here: http://webaim.org/discussion/mail_thread?thread=7459

**Comment by jcsteh** [comment]
When screen layout is enabled (default), items that visually appear on one line are rendered on one line in browse mode. Thus, to activate other items on the same line, you have to move the cursor to those items using, for example, right arrow or control+right arrow to move by character or word. If you don't like this and you want every item to be rendered on a separate line, turn off screen layout as you suggest. Note that this is intended behaviour and is in fact expected by NVDA users who desire screen layout.

**Comment by alastc** [comment]
Would it be possible for pressing enter to activate forms mode in that scenario? Or some other means of activating the tabs. 

At the moment it seems kinda broken. Whilst I fall into the category of sporadic tester who's experience doesn't matter, it will probably seem broken to real users on the more novice end of the scale. I've seen issues like that in usability testing with real users.

**Comment by jcsteh** [comment]
If I move the cursor to a tab with control+rightArrow and press enter, 
it activates the tab, so it's already possible to activate them.

**Comment by alastc** [comment]
Ah, I'm in VMware on OSX so cntl-right moves to a different desktop.

If you think regular users know that short cut, I'll let it drop.

**Comment by jcsteh** [comment]
It's the standard command to move the cursor to the next word.

The thing I'm not quite following here (and I'm not at all trying to be 
antagonistic) is why this seems so confusing to you. The idea of browse 
mode is that you move around very much like you would in, say, a word 
processor. You move by line using the up and down arrow keys. You move 
by character using the left and right arrow keys. You move by word using 
control+left arrow and control+right arrow. So, why does it seem 
intuitive to you that up and down arrows move to the tabs with JAWS (or 
with screen layout disabled in NVDA), but it doesn't seem logical that 
you can move *across* the line with right arrow/control+right arrow if 
there are multiple things on the line? That suggests that moving by line 
is somehow "special" for you; i.e. you don't see it like a cursor in a 
word processor, which can move in both dimensions.

**Comment by alastc** [comment]
It isn't the movement so much, as how you activate / choose the tabs.

I expected that having browsed to the tabs, pressing enter would activate them or drop into forms mode, perhaps with the currently selected one in focus. Bryan thinks that is important for other reasons as well (see the webaim post).

I was somewhat confused by the one-line approach for a couple of reasons, both of which you can ignore for regular NVDA users:
1. I tend to use VoiceOver more in testing, and for trying ARIA tabs I had used Jaws first as well, both of which go item by item through the tabs.
2. I knew about up/down for lines and left/right for words, but I didn't know about cntl-left/right and it doesn't work in my setup (VMware on OSX).

Also, probably from front-end development experience, I don't think in lines but in elements. A paragraph is an element so I get confused when a screenreader goes line by line and stops mid-sentence, and a list-item is an element, so seems like a suitable unit for reading.

So you can ignore the movement aspect, but not being able to press enter with the tabs in focus seems to be an issue.

**Comment by jcsteh** [comment]
But pressing enter on a tab under the browse mode cursor *does* activate 
it, at least for me. Can you please confirm what browser you're testing 
with? The only difference with screen layout enabled is that you have t 
use right arrow to move by character or control+right arrow to move by 
word to get to subsequent tabs. At that point, you press enter like you 
would with JAWS.

**Comment by alastc** [comment]
The setup was Windows 10, NVDA latest, firefox latest and same results in IE11.

I'll have to check when I'm back home this evening. From memory, if you arrow down to the tabs and press enter, nothing happens. 

My expectation was that pressing enter would drop into forms mode and select either the first item, or the currently selected item.

Perhaps you assumed people would move by word first? And I assumed you wouldn't have to.

**Comment by frastlin** [comment]
I think there are a couple higher-level issues that are being hinted at here:
1. It is confusing that NVDA is installed with show screen layout on. I know Jaws does not and I'm not sure about VO. For novice screen reader users, having all the tabs on one line is really unclear and confusing.
2. When one presses enter on an aria element in VO or Jaws, they get placed in edit mode where they can then move through the elements. I personally like what NVDA does and just selects the element without changing what one is selected, but it is not expected behavior.
Thanks,

**Comment by accdc** [comment]
Hi, I think the confusion with the screen layout mode muddied the waters for this bug.

The issue is with the following:
http://www.nvaccess.org/files/nvda/documentation/userGuide.html#toc40

Where it states:
"When in Browse mode, by default, NVDA will automatically switch to focus mode if you tab to or click on a particular control that requires it. Conversely, tabbing to or clicking on a control that does not require focus mode will switch back to browse mode. You can also press enter or space to switch to focus mode on controls that require it. Pressing escape will switch back to browse mode."

In testing this functionality at
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Menus/Variation%20ARIA%20Tabs%20With%20Right%20Click/demo.htm

It is not possible to arrow to a tab in Browse Mode then press Enter or Space as instructed in the NVDA documentation to activate Focus Mode as expected, making it impossible to then use the Applications or Shift+F10 key to open the attached menu on the focused tab.

**Comment by jcsteh** [comment]
> My expectation was that pressing enter would drop into forms mode and select either the first item, or the currently selected item.

If there's a tab at the cursor, pressing enter activates it without switching to focus mode. More on that later.

> Perhaps you assumed people would move by word first? And I assumed you wouldn't have to.

In this example, if you move by line, pressing enter will activate the first tab on the line because the cursor is at the start of the line. If you want to access the second and subsequent tabs, you need to move by character or word.

> 1. It is confusing that NVDA is installed with show screen layout on. I know Jaws does not and I'm not sure about VO. For novice screen reader users, having all the tabs on one line is really unclear and confusing.

There's certainly some validity to this argument, but there's also a counter-argument. It was highlighted quite well by this comment above:

> Also, probably from front-end development experience, I don't think in lines but in elements. A paragraph is an element so I get confused when a screenreader goes line by line and stops mid-sentence,

That's precisely the reason screen layout is ideal. Stopping mid-sentence when moving by line because of an interspersed doesn't make a huge amount of sense when thinking in "lines", which is what up and down arrow normally do when moving a "cursor". Rendering every element on its own line is also extremely inefficient when dealing with content with lots of inline elements. Take a look at a Wikipedia article with screen layout off; the experience is pretty painful.

> "You can also press enter or space to switch to focus mode on controls that require it."
> ...
> It is not possible to arrow to a tab in Browse Mode then press Enter or Space as instructed in the NVDA documentation to activate Focus Mode as expected,

The key phrase is "controls that require it". Tabs do not require focus mode. You can activate them just fine without focus mode, just as you can links, check boxes or radio buttons.

> making it impossible to then use the Applications or Shift+F10 key to open the attached menu on the focused tab.

This is incorrect. You can press the applications key or shift+f10 even in browse mode if a tab is focused and it will do whatever it is supposed to do. In this sense, tabs are n different to links or radio buttons, though they're probably more similar to the latter. Users would get pretty annoyed if we switched to focus mode every time they pressed enter to activate a radio button. I don't see tabs as being any different.

**Comment by alastc** [comment]
> In this example, if you move by line, pressing enter will activate the first tab on the line because the cursor is at the start of the line.

If that's true, you can't tell that is what's happening, there is no feedback.

When I arrowed down to the tabs, it read them all out, I press enter, no feedback. 

Could it say "Tabname tab selected" or something? 

Or is it that you have to move by character/word first? I have trouble with that, but I also haven't seen regular users do that when browsing.

**Comment by accdc** [comment]
"This is incorrect. You can press the applications key or shift+f10 even in browse mode if a tab is focused and it will do whatever it is supposed to do."

That's interesting, I see what you mean. The act of moving the reading cursor over the tab text activates the onFocus handler which does work when Shift+F10 is pressed. Then when Escape is pressed from the menu focus is set back to that tab.

**Comment by jcsteh** [comment]
> If that's true, you can't tell that is what's happening, there is no feedback.
> When I arrowed down to the tabs, it read them all out, I press enter, no feedback.

Okay. This is what happens for me. Steps to reproduce:

1. Open this URL in Firefox: http://a11yideas.com/testcode/tabs/tabs_with_ARIA.html
2. Arrow down to the line with the tabs.
3. NVDA reports "tab selected, Home" before the other tabs, indicating that the first tab "Home" is selected.
4. Pressing enter here will do nothing (it's already selected), so press control+rightArrow (or repeatedly rightArrow) to move to the "Work" tab.
5. Press enter to activate it.
 * Result: NVDA says "selected", indicating that the tab under the cursor is now selected.
6. Now press upArrow to move to the start of the previous line.
7. Press downArrow to move back to the start of the line containing the tabs. NVDA reports "tab, Home, tab selected Work ...", indicating that the Work tab is now selected.
8. The cursor is at the start of the line, so it'so the "Home" tab is at the cursor. Press enter to activate it.
 * Result: NVDA says "selected", indicating that the tab under the cursor is now selected. Notice that you didn't have to hit control+rightArrow or rightArrow because the tab is at the tart of the line and thus already under the cursor.

**Comment by alastc** [comment]
Ok, now that I've re-mapped the keys in the VM I get the same results.

Overall I would drop this as a bug, but are you open to possible improvements?

We aren't the only people that have seen regular users (including NVDA users) struggle with ARIA tabs. A lot of it stems from lack of familiarity with the term, which isn't something you can fix, but there are some things that could help from the UA point of view.

There is still discussion about what form that help would take, but for example
- Providing some in-context hint about what tabs are (a front-end version is the second example here: http://bit.ly/ariatabs but it might be better as a UA hint, it could be more specific.)
- Providing a keyboard short-cut to go from the tab to the controlled content (unless that's what Shift-F10 does? On my Mac keyboard with VM that brings up the firefox context menu.)

And I think it would help to provide some feedback if you land on the tabs and press enter, even if it just repeats "tab selected, Home".

Thanks for taking the time to investigate though, ARIA-tabs seem to be a particularly confusing area for many, not just the end users! (Or me)

**Comment by jcsteh** [comment]
NVDA doesn't currently do tutor messages at all... for anything. Thus 
far, our preference has been to address this in training, but there's 
discussion about introducing some sort of context sensitive help in 
future. It's worth noting that this is difficult with screen layout 
enabled because the last thing the user hears isn't necessarily where 
the cursor is sitting (which is also true in any word processor). That's 
something you can only really address in training material; the user has 
to understand the concept of the cursor and how a screen reader "reads" it.

It's worth remembering that tabs aren't unique to the web. Users will 
also encounter these in desktop applications and the concepts are more 
or less the same. If they struggle with them on the web, they're going 
to struggle with them elsewhere too. In this sense, the web isn't 
"special". A lot of this is actually due to poor training: the idea that 
you can navigate the web entirely by using the tab key or the links list 
equivalent is utterly ridiculous, yet this is is often how users are 
trained.

**Comment by frastlin** [comment]
The comment above about being a front-end developer means that in order to think in elements, one has to already understand the computer. They need to have programmed in HTML or have some deep knowledge of how the web works. In order to know how the web works, one needs to have used a computer, either on a phone or a computer (probably a computer).
It is the rare novice user who has an understanding of html elements before learning how to use the computer. They would be a person who lost their sight later in life who did programming before they went blind. I think the number of Jaws users, beginning computer users and people who have never had screen layout on far outnumber those rare people who would benefit from screen layout on as default. For someone who understands what is going on, they know it is screen layout and they know what to look for in the user guide. It is a matter of one checkbox and that more advanced user has never to worry about it again. But for a new person testing out NVDA, the screen layout being on could be a huge deterrent and source of frustration for a novice user.
I have always used screen readers with the screen layout off and find Wikipedia articles just fine to read... (there is a reason read all was invented :D)

I think the issue is NVDA is not really built for novice users.

**Comment by jcsteh** [comment]
The flaw in this argument is that screen layout on is actually what 
users experience when they use any other editor, word processor, 
whatever. Having screen layout off actually is closer to "thinking in 
elements" than having it on because with it off, moving by line actually 
becomes moving by element. You're assuming that moving by line is 
somehow more intuitive than moving by word. Why? It's just moving 
through text at the end of the day... unless you've been taught that up 
and down arrows move through elements, which is incorrect anyway.

**Comment by frastlin** [comment]
Links and clickable elements. The way links are viewed on a webpage are the only reason. It is unclear (As we saw above) that one should arrow (not to mention a little difficult if the text of the link is long) through a line to click on a link.
If links were on their own line in screen layout, it would solve this problem. It is just these clickable elements being in the middle or at the end of a line in screen layout that make it so confusing for novice users. They have a hard enough time hearing and filtering all the elements as it is on a webpage, when links are in a row, it becomes overload.

**Comment by jcsteh** [comment]
If links appeared on their own line, it wouldn't be screen layout, since 
they don't appear on their own line on the screen.

My point is that it shouldn't be unclear to anyone who is familiar with 
using a word processor or text editor, since in a word processor, you 
have to move by word or character to do anything with a word that isn't 
at the start of a line. Of course, if a user only ever uses the web and 
never uses a word processor, that isn't the case.

In any case, this is getting out of scope. There's some ongoing 
discussion about having a different set of settings for "new users", but 
that's certainly not a short-term thing.

**Comment by dfarough** [comment]
The problem here as  I see it is that NVDA does not support  ARIA tabs.  Why is it not possible to put NVDA into focus mode by pressing enter on the tab at the cursor whether it is selected or not?  If this were possible, then switching tabs could be achieved by using the proscribed keyboard interactions called for in the ARIA practices guide.  It should not be necessary to use control+ right arrow  to move to the next tab.

**Comment by alastc** [comment]
> It is unclear (As we saw above) that one should arrow ... through a line to click on a link.

Tabs aren't links, but that seems to be a very common (mis)understanding.

**Comment by dfarough** [comment]
I think that providing some tutor messaging capability within NVDA is a good idea and should be pursued.  It has been  stated earlier that NVDA is difficult to master for a new user.  All screen readers are complicated and cannot be mastered without a significant amount of training or practice.  Providing this functionality would make learning the program easier for new users.  In JAWS and Voiceover these hints can be turned off when desired.  this would make learning new or confusing elements easier for new users if hints were available when a menu or tab or other new widget gained focus.

**Comment by alastc** [comment]
We are getting off topic, is there a better place to discuss wider improvements?

FWIW, I think the VoiceOver method of providing an interactive tutorial when you first open works very well. Probably harder for NVDA to do that system-wide, but one for web use would be really good.

**Comment by jcsteh** [comment]
NVDA certainly does support ARIA tabs. However, switching to focus mode 
just to activate a tab (especially when the cursor is already on it) is 
an extra step that in many cases isn't necessary and makes for an 
inefficient user experience. If you really want to use tabs in focus 
mode, either move to the tab control with the tab key (which will 
automatically switch to focus mode) or press NVDA+space to force a 
switch to focus mode (which is a documented command).

This issue is now heading way off topic and/or is reiterating points 
that have already been made. Unless you have something new to add, 
please avoid further comments. Thanks.
