### ISSUE TITLE
The ctrl+backspace and backspace keys aren't assignable with NVDA in braille

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5959]
It should be possible to reassign, or assign keys to the ctrl+backspace, or backspace keys. For example, on my focus 40, I would like to be able to press bkspace+space to remove a whole word, and bkspace to remove a char. This is currently not configurable and so I have to reach to the keyboard to remove a word.

**Comment by jcsteh** [comment]
You can already do what you're asking in gestures.ini.

Coming up with a UI for it is somewhat more complicated because that 
requires some way for the user to bind gestures to emulate arbitrary 
keys, which doesn't fit into the current Gestures dialog. Right now, you 
move through the list until you find a command you want to bind to, but 
there are a huge number of possible arbitrary keys, so we can't include 
them in the commands list.

**Comment by derekriemer** [comment]
Good point. Is it in scope to assign this at the braille display level? 
I remember using a refreshabraille 18 and I couldn't use dot 7 as a 
delete key.


On 5/17/2016 10:05 PM, James Teh wrote:
> You can already do what you're asking in gestures.ini.
>
> Coming up with a UI for it is somewhat more complicated because that
> requires some way for the user to bind gestures to emulate arbitrary
> keys, which doesn't fit into the current Gestures dialog. Right now, you
> move through the list until you find a command you want to bind to, but
> there are a huge number of possible arbitrary keys, so we can't include
> them in the commands list.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5959#issuecomment-219919995>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
It could be assigned in individual drivers, though it probably makes sense to have a set of common commands where possible, especially for braille dots. Note that #2439 currently maps dot 7 to backspace (indirectly).

Addressing something I said earlier:

> Coming up with a UI for it is somewhat more complicated because that 
> requires some way for the user to bind gestures to emulate arbitrary 
> keys, which doesn't fit into the current Gestures dialog.

It just occurred to me that we could have a button active only while in the "Emulated system keyboard keys" category which allows the user to add an emulated key to that category. The user could then assign a gesture to it. The only issue is that I'd rather not have a special button which is inactive except when in that category. We could abuse the Add button so that it does this while focused on (but not inside) that category, since the Add button is normally inactive when focused on a category. I'm not sure if that will be intuitive, though.

**Comment by jcsteh** [comment]
Closing in favour of #6060, which was filed later but is somewhat more general and a bit clearer.
