### ISSUE TITLE
Tinymce, Ckeditor And Other Ritch Wysiwyg Text Editor Support

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5967]
Currently NVDA can only read the list of buttons in such applications, however there isn't a separate interface for writing, paragraph support style and the buttons. In places where dialogues appear, especially in tinymce, they are not inline making switching between documents and fixing formatting changes very difficult.

**Comment by jcsteh** [comment]
I don't really understand the issue here. Please give an example 
scenario. Note that these editors generally provide controls near the 
document area, so you should be able to tab or shift+tab to them. Also, 
the editor may provide its own keyboard shortcuts to make this faster.

**Comment by Elshara** [comment]
The issue is not with accessing the buttons, they are usually the most
accessible thing about them. The issue is, despite shift tab and tab
not working, the left and right arrows usually work if the buttons are
displayed from within the application style. If not, then they are
displayed within the document as a regular web page button you can
click on. The issue is, dialogue controls for such buttons appear at
the very bottom of the screen, instead of inline where the button or
editor is. For sighted users, it appears as an in window browser pop
up, not an overlay window. Also, navigating between the list of
buttons and using them is almost impossible when trying to see where
the changes made through the buttons take effect. Sometimes in
paragraph view, the cursor hangs and you have to reload the page to
retype what cannot be read. It is very crude, very inaccessible in
paragraph view and the only way around it is to navigate to the edit
source code or edit html button to solve it. Sometimes that doesn't
even work because if the html is malformed or there are spelling
errors, the source code editor won't pick that up. There is also no
autosave feature within html view, so you're taking a chance of
editing code like you would in note pad should the feature break
suddenly which happens rather a lot on websites due to scripts timing
out. Ever since the wysiwyg editor was introduced to websites, it has
been a head ache for screen readers to grasp the concept of the
interface not as far as the buttons are usually concerned, but how
accessible the framework is in paragraph view for what changes are
applied where. Take a forum software like IPBoard, you can't even edit
anything in wyciwyg. Same goes for word press.

**Comment by jcsteh** [comment]
What do you mean by "paragraph view"? Do you mean browse mode? And what do you mean by the cursor "hanging"?

If the buttons appear a long way from the editor, that is because the author of the editor has placed the content at that point in the document's logical structure. As explained elsewhere, trying to second guess this kind of behaviour is extremely problematic.

It's worth noting that these editors often provide keyboard commands which make working with them much more efficient. For example, see [this post by Marco Zehe about TinyMCE accessibility](https://www.marcozehe.de/2014/02/26/wai-aria-showcase-tinymce-4-17/).

Closing because based on your description, there's nothing NVDA can do here.

**Comment by Elshara** [comment]
I understand. I do think that further development of the editor would
prove most useful in this regard.
