### ISSUE TITLE
Espeak Language Burmese

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5969]
This language is very malformed.

**Comment by Christianlm** [comment]
All issues for eSpeak-ng's languages are wellcome on:

https://github.com/espeak-ng/espeak-ng/issues

Thanks.

Chris.

Elshara

**Comment by Elshara** [comment]
https://github.com/espeak-ng/espeak-ng/issues/117
I just posted it there. Thanks for the reference. I love git hub. I'm
glad to see you are using it!

**Comment by jcsteh** [comment]
As noted above, this should be addressed in the eSpeak NG project.

**Comment by Elshara** [comment]
I just thought you could hold off on delivering Espeak functionality
if the language is so badly formed it breaks on trying to spell
individual letters in English, or seems as if it will. And no number
support. Honestly espeak is more buggy than sappy 5 at times.

**Comment by bhavyashah** [comment]
Hi Elshara,
From a rational point of view, it would be impossible for two
Australians to verify how sufficiently well ESpeak reads a language,
i.e. Burmese. Moreover, the ESpeak project marks those languages which
it considers have primitive reading support as test, such as Bengali
and Gujarati, two Indian languages.
I would second the response that this issue is in the scope of the
ESpeak NG project, and not NVDA.
Thanks.

On 5/21/16, Elshara Silverheart <notifications@github.com> wrote:
> I just thought you could hold off on delivering Espeak functionality
> if the language is so badly formed it breaks on trying to spell
> individual letters in English, or seems as if it will. And no number
> support. Honestly espeak is more buggy than sappy 5 at times.
>
> On 20/05/2016, James Teh <notifications@github.com> wrote:
>> As noted above, this should be addressed in the eSpeak NG project.
>>
>> ---
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/5969#issuecomment-220573363
>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5969#issuecomment-220764882


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by Elshara** [comment]
Just go to voice settings and select burmese as the voice language.
Then try tabbing around the voice dialogue. See if you come up with
the same conclusion I have. The only other language which acts this
way is ancient greek. Quite frankly I don't know why it exists.
