### ISSUE TITLE
PDF Documents In Firefox Refuse To Respond To Any NVDA Command

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5972]
Windows 10 has its own pdf reader which does the same thing. When opening a document, there is nothing to view or interact with. It seems firefox acts like it is freezing the window when a pdf document appears, even though the window isn't actually frozen. This is how NVDA interprets such data in similar windows.

**Comment by jcsteh** [comment]
If you're talking about the PDF reader built into Firefox itself, this definitely shows some controls here, though whether the PDF is accessible depends on the PDF. It's also possible it's just opening the Windows PDF reader. In either case, these issues are either due to inaccessible PDF documents and/or problems with other PDF readers. Please use Adobe Reader to read PDF files.

**Comment by Elshara** [comment]
I've used the pdf extension as the nvda add on for this purpose and it
worked in fire fox without any problems. Without it, nothing loads.

**Comment by jcsteh** [comment]
What PDF extension? What NVDA add-on? Please provide thorough details, 
information about your PDF software/configuration and steps to reproduce 
the problem.

**Comment by Elshara** [comment]
I found the add on listed here.
http://jeff.tdrealms.com/NVDA.htm
It's a pdf to text add on. Just installed it and I can read any
document independently in any pdf reader. I use firefox with it. It's
awesome. There's a bunch of add ons there.
