### ISSUE TITLE
In wordPad Move to previous/next Word gesture issue

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#5983]
STR:

1. Run wordpad
2. Press sample text: 'NVDAis free openSource screen reader.
3. Press Move to next word(Control right) read sample text

Expected Results:
- NVDA speak text: NVDAis free openSource screen reader .

Actual Results:
- NVDA Speak text: NVDAis free openSource screen reader.

I think that NVDA is recognized by the dot words.

Test env:
- OS/Windows7 64Bit(Korean), NVDA next-13323

The issue is the same in programs such as Notepad++, AkelPad. Thanks.

**Comment by jcsteh** [comment]
In Wordpad, NVDA treats the full stop (.) as a word because that is how Wordpad treats it. You can see this if you use control+rightArrow (which is provided by Wordpad, not NVDA) to move word by word. NVDA aims to conform with the application's idea of words, lines, etc. so as to ensure maximum consistency and compatibility.
