### ISSUE TITLE
[Feature]: announce the action performed when the print screen button is pressed.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6011]
1. Press Print screen.
2. Notice how there is no indication that the  current window was copied.

**Comment by jcsteh** [comment]
Do sighted users get any such indication?

**Comment by k-kolev1985** [comment]
Just for when pressing the Print Screen key - I think not. At least I don't see any indication on the screen that I've pressed it. But on Windows 8 and newer, when pressing Windows+Print Screen (to make a screenshot of the whole screen and save it as a file in the "Screenshots" folder in the "Pictures" folder"), the screen flashes. Actually, maybe due to my high-contrast setting, or it is so in all cases, the screen darkens for a moment when the key combination is pressed, instead of flashing white.
