### ISSUE TITLE
The speaking of the typed characters does not work in Universal apps in the latest build of the Windows Insider Preview

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#6017]
I've noticed that, with the latest build of the Windows Insider preview, NVDA does not speak the typed characters in the so called universal apps. That includes the search field in the Start menu. If I use the arrow keys to review the typed characters - it works as expected. If I use the DELETE or BACKSPACE keys to delete characters, it also works as expected. The only issue is with the characters not being spoken when entering them from the keyboard (keyboard echo). Both Windows and NVDA are the latest test builds.

Steps to reproduce it:
1. Update the Windows Insider Preview to its latest build via Windows Update.
2. Update the installed copy of NVDA to its latest "next" snapshot.
3. Open one of the so called "universal" apps. The Microsoft Edge browser will do it.
4. Make sure that the option "Speak typed characters" of NVDA is turned on.
5. Find an edit field in that app and start typing text in it.

Expected results:
NVDA should speak the typed characters.

Actual results:
NVDA stays silent.

Test environment:
- Operating system: Windows 10 Pro Insider Preview (build 14352.1002)), 32-bit, in English with all locale settings set to "Bulgarian", in a virtual machine in VMWare Player.
- Input languages: "Bulgarian" and "English US".
- VMware® Workstation 12 Player version: 12.1.1 build-3770994.
- NVDA version: next-13343,73ee6b2a.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 3.00GB.

**Comment by k-kolev1985** [comment]
Am I the only one that can reproduce this? Does it work OK on your machines?

**Comment by jcsteh** [comment]
No; I confirmed this, but neglected to comment here. The issue is that 
Microsoft have completely blocked NVDA (and all other assistive 
technology software) from injecting into UWP apps. Previously, only 
installed software with uiAccess privileges (including NVDA) could 
inject, but now, even this has been blocked. This has been done in the 
name of security, but the problem is that Microsoft have not provided a 
suitable alternative which enables AT to access typed characters in a 
way which works properly for all languages. We've raised this with 
Microsoft, but they've yet to provide a useful solution or response.
