### ISSUE TITLE
Random changes in index on Windows 10 taskbar items 

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6042]
The attached log demonstrates behavior. here's some context.

I currently have five items pinned to my task bar. Once I open items, the index (item X of Y) changes. Rather than reporting 1 of 5 or 1 of six, NVDA
reports larger numbers. The example log shows that 13 total items are on the taskbar; but only 7 items are there. This changes based on the number of items that are open and which application on the taskbar is opened. Sometimes the index skips two items, sometimes three; and other times four. I have not been able to determine a pattern. I won't speculate as to the cause. I'll report this to Microsoft as well. 
The expected behavior should be item 1 of 7, 2, of 7, 3 of 7, 4 of 7, 5 of 7, six of 7. Actual behavior is 1 of 13, 2 of 13, 4 of 13, 6 of 13, etc.
 [NVDA2.txt.txt](https://github.com/nvaccess/nvda/files/301176/NVDA2.txt.txt)

**Comment by jcsteh** [comment]
These positions aren't reported at all unless you have "Guess object position information when unavailable" enabled (disabled by default). This is precisely because the way we get item positions for controls like this can be highly inaccurate. (Technically, it's just the accessible child id and child count.) Unfortunately, there's no efficient, accurate way for us to get item positions here. Note that Narrator doesn't report an item position here either. Any fix here would need to come from Microsoft.

**Comment by PratikP1** [comment]
Yes. I tested that. Right now, it’s showing me index numbers when “guess object position” is unchecked. I’ve restarted NVDA several times. I will test it again after restarting Windows.

**Comment by jcsteh** [comment]
Is it possible you have a triggered profile with this enabled?

**Comment by PratikP1** [comment]
No. I disabled all profiles.
