### ISSUE TITLE
Custom emulated system keyboard keys

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6060]
Several braille display drivers add emulated system keyboard keys to NVDA, such as escape or alt. It might be an interesting feature if one could add other keys for emulation, for example when one wants to add an emulated system keyboard key to a braille function key which they can't choose by default.
I'd suggest adding a separate button to the imput gestures dialog "Add emulated system keyboard key", which allows you to press a random key on the keyboard which is than added to the emulated system keyboard keys category in the dialog. After that, one should be able to add a gesture to it.

**Comment by jcsteh** [comment]
I'm bothered by having a special button to add emulated keys which is always present. It just doesn't really "fit" and is only relevant to one category. I suggested in https://github.com/nvaccess/nvda/issues/5959#issuecomment-224762276 that we could abuse the Add button to do this only while focused in the emulated keys category. From a technical standpoint, this seems a bit strange, but I think it makes sense from a UX perspective.

**Comment by leonardder** [comment]
I agree there, provided that the emulated system keyboard keys is always 
present in the input gestures tree.

**Comment by leonardder** [comment]
I will take this as soon as I have the time for it, but it will probably be a private project, so not on behalf of @babbagecom. I consider it a relevant issue though, not only specifically for braille.

I will do a self-assignment, but if anyone wants to take this before I start working on it, feel free to poke me.

**Comment by dkager** [comment]
I think we should also evaluate the list that is already there. For example:
- Alt is represented, but not Control.
- Windows+D is represented, but not the equally useful Windows+B (and others).
- The super handy applications key or Shift+F10 is missing.
- Is there a need to translate between the key and its function? I.e. instead of Windows+D, the entry would read "Go to desktop".

**Comment by jcsteh** [comment]
[**@dkager**](https://github.com/dkager) commented on [Dec 3, 2017, 9:08 PM GMT+10](https://github.com/nvaccess/nvda/issues/6060#issuecomment-348756489 "2017-12-03T11:08:04Z - Replied by Github Reply Comments"):
> I think we should also evaluate the list that is already there.

The "list that is already there" is purely based on what braille display driver you have loaded. There is no default list otherwise.

> - Alt is represented, but not Control.

> - Is there a need to translate between the key and its function? I.e. instead of Windows+D, the entry would read "Go to desktop".

I think this is more trouble than its worth. That would require special casing and hard-coding these names.

**Comment by dkager** [comment]
> The "list that is already there" is purely based on what braille display driver you have loaded. There is no default list otherwise.

Interesting. I would expect there to be a default set, since you might want to assign a specific key to a touch or keyboard gesture.

**Comment by leonardder** [comment]
@dkager, there will be a default list of toggle scripts as part of #7843.

**Comment by leonardder** [comment]
I currently have neither time nor interest to work on #7784 any time soon.
