### ISSUE TITLE
On reading with word by word, word just before a punctuation mark such as period, comma, question mark etc is repeated twice in gmail message edit field in basic view in internet explorer.

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#6077]
Steps to reproduce:
1.  Login to a gmail account in internet.
2.  Go to compose link.
3.  Tab to message edit field and put on the forms mode if not already switched on
4.  Type a sentence with punctuation mark.
5.  Read by word reading command, CTRL+LEFT ARROW.
6.  The word just before a punctuation mark is read twice.

**Comment by Adriani90** [comment]
@sumandogra are you still able to reproduce this issue with NVDA 2018.4.1?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, and support for Internet explorer has ended completely in 2022. The browser is automatically removed from machines that still have it after an Edge update in February 2023. I  don't expect any accessibility updates to internet Explorer or to the IE mode in microsoft Edge. Closing as abandoned.
