### ISSUE TITLE
GUI: Use wx.ListBox when displaying list of synthesizers, braille displays and others

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6100]
Hi,

Continuing from #6099:

For the most part, wx.Choice is adequate when displaying lists such as synthesizers. However, when viewed from visual perspective, it means only one selection is visible. For users using object navigation (especially for touch users), it means having to tap expand button, navigate through items, select and see the combo box collapse.

On the other hand, wx.ListBox allows the toolkit to show a true list of items where one can see more than one entry. This is useful for some (especially sighted trainers) where they'd like to get a glimpse of available options without having to drill through combo box items. This is also advantageous for people using object navigation and touch flicks, in that all they need to do now is just move through entries and activate (select) the desired item. Although this means users would not know the hotkey at first, this is a minor thing that can be fixed through accessibility API handlers.

I'd like to propose changing the following combo boxes to list boxes:

* Synthesizer dialog: list of synthesizers
* Braille settings: list of braille displays
* Voice: voice list (not variant yet)
* Others as needed.

Thanks.

**Comment by josephsl** [comment]
Hi,

The reason for saying not all items should be converted to wx.ListBox: screen real estate (because a list box displays all items, it'll mean slightly larger dialogs). Thanks.

**Comment by jcsteh** [comment]
I think we should get some sighted opinion on this. I think the voice 
list in particular is possibly too big to be displayed as a list rather 
than a drop-down, although the same could be true for the braille 
display list. As I understand it, expanded lists only really work when 
there are only a few other controls in the dialog or all other controls 
are across the screen from the list (not above/below it). Neither is 
true for these dialogs.

@QChristensen, thoughts, please?

**Comment by Qchristensen** [comment]
The voice list, variant, Braille tables etc are all larger than will fit on 3 - 4 screens high for me (24", 1920x1080 at 175% size - all using regular settings options).  A list would definitely still need to be scrolled for these and others (eg language).  It would introduce another control type to the NVDA interface - which isn't necessarily a reason in itself not to do it.  If you tab around and down arrow or use the alt+letter to get to a control and down arrow then it should work pretty much the same.  For someone who uses alt+down arrow to open drop down lists, they would need to listen out for which is a drop down list and which isn't if they also used escape to close as it.  It would save a little navigation here and there, particular for sighted users, although I wonder whether the trade off in terms of more complex dialogs is worth it?

As Jamie says, it would need a redesign of the dialogs to allow these lists to beside other controls rather than above / below them.  I think that in itself makes it harder to navigate, particularly when looking visually at the screen - at least with everything in one column, I know to go from one item to the one below it, and the one below that etc.

Ideally I would like to have a relatively consistent logic between controls.  In the voice settings dialog for instance, we could arguably fit the punctuation options (none, some, most, all) in a list, but in the punctuation / symbol pronunciation dialog, we'd be starting to run out of room if we had that, because we'd also need to have the send actual symbol to synthesizer as a list since that's even fewer options.  As it is in that dialog, the symbols list that already exists isn't large enough, even for the space it's in (I might file a separate issue about that - there's a bit of blank space around it while it needs to be scrolled still).

My personal inclination is to leave it as it is, although at the same time I'm not passionately against redesigning any of the controls either.

**Comment by derekriemer** [comment]
Nope.

Should have been @jcsteh


On 6/21/2016 7:01 PM, Quentin Christensen wrote:
> The voice list, variant, Braille tables etc are all larger than will fit on 3 - 4 screens high for me (24", 1920x1080 at 175% size - all using regular settings options).  A list would definitely still need to be scrolled for these and others (eg language).  It would introduce another control type to the NVDA interface - which isn't necessarily a reason in itself not to do it.  If you tab around and down arrow or use the alt+letter to get to a control and down arrow then it should work pretty much the same.  For someone who uses alt+down arrow to open drop down lists, they would need to listen out for which is a drop down list and which isn't if they also used escape to close as it.  It would save a little navigation here and there, particular for sighted users, although I wonder whether the trade off in terms of more complex dialogs is worth it?
>
> As Jamie says, it would need a redesign of the dialogs to allow these lists to beside other controls rather than above / below them.  I think that in itself makes it harder to navigate, particularly when looking visually at the screen - at least with everything in one column, I know to go from one item to the one below it, and the one below that etc.
>
> Ideally I would like to have a relatively consistent logic between controls.  In the voice settings dialog for instance, we could arguably fit the punctuation options (none, some, most, all) in a list, but in the punctuation / symbol pronunciation dialog, we'd be starting to run out of room if we had that, because we'd also need to have the send actual symbol to synthesizer as a list since that's even fewer options.  As it is in that dialog, the symbols list that already exists isn't large enough, even for the space it's in (I might file a separate issue about that - there's a bit of blank space around it while it needs to be scrolled still).
>
> My personal inclination is to leave it as it is, although at the same time I'm not passionately against redesigning any of the controls either.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6100#issuecomment-227615775

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Not going to fix this as per last few comments.
