### ISSUE TITLE
Website: No/Bad HTTPS support

### ISSUE THREAD

**Issue by rugk** [nvaccess/nvda#6105]
Sad to see your website does not use HTTPS.

See this blog post for reasons why you should always use HTTPS: https://scotthelme.co.uk/still-think-you-dont-need-https/

In your case with HTTPS also the downloads would be protected. Without such a protection layer they could easily be modified.
If you don't want to offer the download files over HTTPS as least show the file hashes on the download site, which is delivered via HTTPS.

I also see you already have a certificate as you redirect HTTPS to HTTP. Only your shop does not redirect to HTTPS, but this makes [SSL stripping](https://moxie.org/software/sslstrip/) easy, which could result in users visiting your shop in HTTP.

----

Furthermore have a look at [these test results](https://www.ssllabs.com/ssltest/analyze.html?d=www.nvaccess.org) of your HTTPS config. It is vulnerable tom several attacks (!), so please improve your configuration.
See https://mozilla.github.io/server-side-tls/ssl-config-generator/ for a config generator.

**Comment by jcsteh** [comment]
Thanks for reporting these issues. I'm closing this, as this isn't the right place for us to deal with this, but we'll look into this as we are able.

Note that NVDA downloads are digitally signed by NV Access (and Windows will warn about running unsigned applications). Also, automatic updates provide a hash to prevent MITM attacks.

**Comment by leonardder** [comment]
I've had very good experiences with [Lets
    Encrypt](https://letsencrypt.org/). There's currently no package for
    Ubuntu Trusty though, but there might be several reasons to upgrade
    to Ubuntu 16.06 Xenial as that allows switching to a more recent
    version of NGinX. See https://certbot.eff.org/#ubuntuxenial-nginx
    
    > I'm closing this, as this isn't the right place for us to deal
    with this
    
    What would be the right place to discuss these things?

**Comment by jcsteh** [comment]
* www.nvaccess.org now uses https only; all http traffic is redirected to https. It also supports HTTP 2.
* Likewise for addons.nvda-project.org.
* The SSL configuration now has an A rating on SSL Server Test.
* files.nvaccess.org (which hosts the podcast and some add-ons) is still http only. However, we plan to migrate all of that content to our main server, at which point we can use https for that too.
* www.nvda-project.org still supports plain http because there are very old builds of NVDA which are still pinging the old update check URL which was plain http. We probably don't care, though, so I'll probably eventually switch that as well. However, we don't officially direct anyone to that site now anyway; it's all redirects for transitional purposes.
