### ISSUE TITLE
Security Concerns About Speech Viewer

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#6115]
I work for Pearson Assessment in the U.S., and we are concerned that the Speech Viewer tool for NVDA developers opens up a potentially serious security risk in the area of high stakes assessment.  Because Speech Viewer captures everything NVDA is reading, and the dialog stays open after the application being accessed is shut down, a user could capture the content of a secure test, and allow someone else to view that content.  Is there any way of disabling the use of Speech Viewer during high stakes assessment?

**Comment by RD-Brown** [comment]
Can someone from NV Access please comment?

Dan

**Comment by derekriemer** [comment]
@MichaelDCurran


On 7/7/2016 8:04 AM, RD-Brown wrote:
>
> Can someone from NV Access please comment?
>
> Dan
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6115#issuecomment-231087283>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivWIml1IT0LHE6VY9mXBvfsYrCL5Mks5qTQd3gaJpZM4I_k-Y>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by bramd** [comment]
@RD-Brown If you have such concerns, you should also check the logging system. On debug level it might log speech an/or brailel output. If you control the environment where these tests are taken, you could create a custom build with these features disabled?

**Comment by leonardder** [comment]
The log viewer is disabled when NVDA is running in secure mode WITH THE -S FLAG. I can see reasons to disable the speech viewer in that mode as well.
However, in that case, people would still be able to restart NVDA themselves without the command line switch. So, I'm afraid a custom build is the only thing you can do.

**Comment by leonardder** [comment]
@jcsteh: What do you think about disabling the use of speech viewer in secure mode?

**Comment by ehollig** [comment]
CC @jcsteh to get your opinions on the question by @leonardder in https://github.com/nvaccess/nvda/issues/6115#issuecomment-242017119

**Comment by michaelDCurran** [comment]
I would support disabling speech viewer in secure mode if this is a 
suitable solution for the reporter.

**Comment by ehollig** [comment]
Although @leonardder brings up a great solution in https://github.com/nvaccess/nvda/issues/6115#issuecomment-242017119 and @michaelDCurran is in favor of the idea, are there any users, that we are aware of, that rely on the speech viewer on secure screens such as UAC or the login screen?

**Comment by derekriemer** [comment]
I'd prefer a CLI option to disable only speech viewer, and log and ... so a student doing tests in a field like biology could have a speech dict with the appropriate pronunciations of various biology words, like Lophotrochozoa, which need to be pronounced correctly on a test. Security mode is a bit too course grained now, because different people have different requirements.

**Comment by feerrenrut** [comment]
@RD-Brown To ensure that we understand the use case, can you confirm which (if any) of the following correctly describe what you are concerned about:

- After an NVDA user has completed a secure test, we want to be able to limit the ability of the next computer user from viewing the answers. 
- When a user of NVDA is completing a secure test we want to be able to limit their ability to copy the contents (EG questions / answers) of this test and sharing it with others.

**Comment by RD-Brown** [comment]
- When a user of NVDA is completing a secure test we want to be able to
   limit their ability to copy the contents (EG questions / answers) of this
   test and sharing it with others.

**Comment by feerrenrut** [comment]
@RD-Brown are you suggesting that the other use-case is not relevant for this issue?

**Comment by RD-Brown** [comment]
Both use cases are valid.  The case I listed was our primary concern when
we initially filed this bug.

**Comment by feerrenrut** [comment]
Understood, the other case can be mitigated by restarting NVDA. Handy to know that this about security of the content, rather than security of the user.

To stop a user from copying content using NVDA would require more than just disabling the speech viewer. There are other methods for selecting and copying text to the clipboard. Although, using the speech viewer might be the most convenient way to copy a lot of text from different elements.

So, disabling the speech viewer on secure screens is probably the best first step. This has the benefit of also addressing the concern for the security of a user on a secure screen:

`As a user who has speechviewer enabled generally, and copies settings to be used on secure screens, speech viewer is still not displayed when on secure screens. This helps to keep my login and other secure information safe from those viewing my screen.`

This would not be a big task, and will achieve several outcomes. Setting as a priority 2.

**Comment by Adriani90** [comment]
is disabling speech viewer on secure screens still being an option which has to be explored? cc: @leonardder

**Comment by leonardder** [comment]
I think we could accept a pr in which the speech viewer is disabled in secure mode. I think it is hardly used on secure screens, so it won't hurt anyone while having the benefit of giving the user the ability to forcefully disable it.

**Comment by Qchristensen** [comment]
As the only options currently available from the tools menu in secure mode are "Speech viewer", "Braille viewer" and "reload plugins" - would it be easier to simply disable the tools menu entirely?

Note for anyone implementing this (whether disabling speech viewer or the whole tools menu) - it is possible to setup an input gesture to toggle the speech viewer so starting the viewer that way would need to be disabled.

**Comment by Adriani90** [comment]
This is fixed now in the last Alpha of NVDA in #15680.
