### ISSUE TITLE
Why Are Email Addresses Required To Download NVDA?

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#6153]
And why has no announcement been made about this rather recent change? It seems downloading next builds are impossible.

**Comment by michaelDCurran** [comment]
We are aware that update check in NVDA Next is broken and are looking 
into the issue.


Thanks

Mick




On 7/07/2016 10:27 PM, Elshara Silverheart wrote:
>
> And why has no announcement been made about this rather recent change? 
> It seems downloading next builds are impossible.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6153>, or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5nZFv63f4_4fP3P0izdrmTRWiTMBIks5qTPDEgaJpZM4JHBvQ>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by leonardder** [comment]
This is not the right way to discuss this. Furthermore, downloading snapshots works fine for me.

**Comment by Elshara** [comment]
So much for being curious.

**Comment by ehollig** [comment]
Is update check now working as expected? I assume so, otherwise this would get more attention. Can this be closed?

**Comment by jcsteh** [comment]
Yes, update checking is working now; this was broken by 621e5393 and fixed by ac6b5228. As to why email addresses are required for downloads, this helps us to get a more accurate count of unique users. We plan to provide a statement clarifying the reasons for this on our new website, though there is no ETA on the launch for that yet.

**Comment by derekriemer** [comment]
I'm not sure you should trust this, because I know people (Myself included) who put xxx@xxx.yzz or something in to get past it if I want to download it in a hurry for doing server admin for someone. That's not a unique download.

**Comment by Brian1Gaff** [comment]
Because if nvaccess can point to a certain number of unique users, they have 
more clout with the makers of inaccessible software and also may get more 
grants.
Everything is based on metrics these days of course!
 I have no issue with that. If you don't want to do this use snapshots.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
