### ISSUE TITLE
Always read a page from the beginning (even on a re-visit)

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#6208]
NVDA sometimes seems to remember the position until where I have read a page. When I re-visit that same page, the cursor is placed at this position.

While this may seem handy sometimes, it can lead to unpredictable behaviour e.g. when in a shopping cart and removing the last item. When the page is reloaded, the focus is stuck somewhere in the footer, because the last item isn't there anymore.

I want to disable this, e.g. I always want to have the cursor placed to the beginning of the page (except when the focus is explicitly placed using JavaScript). But I don't find the option for it.

In JAWS, there's a similar option, but I don't remember how it was called (something like "Skip navigation" maybe?)

**Comment by jmuheim** [comment]
Oh I'm sorry, should I better place this on StackOverflow? Because it's rather a general question, not a bug report.

**Comment by jmuheim** [comment]
I have created a working demo of the problem here:

http://developer-guide.access4all.ch/en/examples/remember_position_when_revisiting_page_example

**Comment by jmuheim** [comment]
I think this is related: https://github.com/nvaccess/nvda/issues/4998

**Comment by ehollig** [comment]
CC @michaelDCurran @jcsteh, this sounds like a general question

**Comment by bhavyashah** [comment]
@jmuheim #4998 has been closed as worksforme. Do you believe we could close this ticket as a duplicate of that one, or as a worksforme in itself? Regardless, the Github issue tracker isn't really meant for questions. Please post those on the NVDA_Devel list or forums of the like.

**Comment by Adriani90** [comment]
@jmuheim is this still an issue for you?

**Comment by ehollig** [comment]
@michaelDCurran @feerrenrut @leonardder is there any interest in creating a feature request like this? I am leaning toward closing

**Comment by Adriani90** [comment]
Is automatic say all on page load in NVDA setting / browse mode not working for this purpose?

**Comment by Adriani90** [comment]
We didn't get further updates from the initial author since many years and it seems it was also not meant to be a bug report. If this request is still valid, please comment and we can reopen. Or fill a new request with the new feature request template.

**Comment by XLTechie** [comment]
I think the original feature request was well enough stated, and the problem it 
represents still exists today.
I think at the time, GitHub wasn't really used for feature requests?
Never the less, even more than when this issue was generated, simply determining 
that a webpage hasn't changed by comping the URL, is not a satisfactory 
methodology.

Regardless the comments of this issue seem to have gotten diverted in comparing 
another issue that was invalid, and I agree that this should be re-created 
cleanly with the modern feature request template.

It's certainly still a valid request though.
