### ISSUE TITLE
Say All with Review: Change Input Help Description

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6211]
Currently, the following description is given from within Input Help:

Reads from the review cursor up to end of current text...

This should instead be:

Reads from the review cursor up to the end of the current text...

**Comment by ehollig** [comment]
Opinions from others? It appears the request is to add an additional word, "the" to the input help. Would this assist the translators in translating this string or provide more clarity to this sentence? CC @josephsl

**Comment by Adriani90** [comment]
in my opinion this is software language, we also usually say up to end of line or up to end of page. So I would suggest to close this because is a really small detail and it does not bring really any improvements. It causes work for developers / translators or who ever would raise a pull request for this. I would say let's put more energy in more important problems rather than concentrating on such small wording issue. @elliott94 what do you think?

**Comment by elliott94** [comment]
In my opinion this is incorrect and is aimed at users rather than developers - however, I do also agree that it's just a case of changing a really small detail so am open to thoughts from other users on this.

**Comment by Adriani90** [comment]
fixed in #10130. Closing.
