### ISSUE TITLE
[Firefox] Editable readed when input has aria-readonly

### ISSUE THREAD

**Issue by troianoandres** [nvaccess/nvda#6234]
Hello,I've founded an issue related to the following case. 

I have an `<input>` field with `aria-readonly='true'` and NVDA is reading `editable` into Firefox browser.

After some research I founded that this could be unsupported by NVDA into Firefox but supported into Chrome, is this right?

Thanks!

**Comment by leonardder** [comment]
In what version of NVDA did you test this?

**Comment by pratham2003** [comment]
I'm facing the same issue. Chrome reads it as 'editable' .. Doesn't say that it's read-only.
Chrome Version 62.0.3202.75 (Official Build) (64-bit)
NVDA Version 2017.3

On latest firefox version 56.0 (32-bit) the input[type="number"][readonly][aria-readonly="true"] box reads '.... Edit Read-only...'

This looks more like a chrome issue

**Comment by feerrenrut** [comment]
@pratham2003 this issue relates to "editable" announced when using firefox. Rather than "readonly" not announced when using chrome. Could you please raise a new issue for the problem you describe. I believe the following example illustrates the problem:

`data:text/html,<label for="numoforanges">Number of oranges</label><input type='number' readonly aria-readonly='true' id="numoforanges" value=5></input>`
