### ISSUE TITLE
Broken Google Chrome support from NVDA

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#6249]
Google Chrome is quite unusable now with NVDA.
I'm using version 52, with NVDA snapshot next-13418,a6c0724c.
When you press h for moving between headings, or press downarrow key, in many website NVDA make the error tone and don't read text, links, etc.
an example?
www.yahoo.it

I attach the log, anyway the error regards bad mxl formatting.
Can you fix please?

[chrome.txt](https://github.com/nvaccess/nvda/files/406313/chrome.txt)

**Comment by jcsteh** [comment]
This works when Chrome is set to use English, but breaks for Italian and possibly other languages. This needs to be fixed in Chrome, so I've filed [Chromium issue 640043](https://bugs.chromium.org/p/chromium/issues/detail?id=640043). I'm going to see if I can at least partially work around this in NVDA.

**Comment by jcsteh** [comment]
I've worked around this as far as we can in NVDA. You won't get told about clickable content--that needs to be fixed in Chrome--but NVDA no longer chokes completely. I've pushed this as a very late fix into 2016.3 because it's pretty nasty.

**Comment by dreinn** [comment]
Thank you very much Jamie, in fact I have this problem on 3 different pc 
and I was quite surprise that nobody on NVDA mailing list report this.
Really thank you.

Il 23/08/2016 06:39, James Teh ha scritto:
