### ISSUE TITLE
Allowing automatic updates of portable copies

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6281]
IN the current situation, when you check for an update in a portable copy and decide to download it, de installer will be opened into the default browser. I'd like to propose the possibility to also update portable copies automatically. This would involve adding an extra possible argument to the NVDA executable which creates/updates a portable copy in the dir the initial portable copy started from.

**Comment by Brian1Gaff** [comment]
I'd like to see this myself, but I thought there were security implications 
to doing this on a portable copy.
 The thing is though that any portable copy can be made into an installed 
one so maybe this is academic in any case especially in later versions of 
Windows.
I've had no end of trouble on certain machines where Firefox is the default 
browser and its opened with a blank page and no start or even 
acknowledgement of a download being requested.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
I assume the security implications are not very different to the case where one downloads the installer manually and than creates a portable copy from the launcher in the same directory as the initial copy.

Alternatives could be:

* Download the update automatically and than start the launcher. One will have to choose for install or create a portable copy manually
* Download the update mautomatically and open the create portable copy window with the directory of the initial portable copy inserted into the field. This will make it required for a user to always confirm the portable copy creation.

**Comment by zahyur** [comment]
I don't think there are security implications with the portable copy, specifically. As far as I can remember, I implemented this as part of #4263
The original reason behind opening the default browser, instead of downloading the update directly, as far as I can remember, was the possible issue of write access (mick and Jamie could tell if I'm wrong). Or may be it was so NVDA won't leave trace to the hard drive, in case it's run from an external media. Or may be both - it was something about the location, where the file will be written.

**Comment by jcsteh** [comment]
The problem here is that apps sometimes refuse to release our injected dlls, which means they can't be removed until the app exits. With installed copies, we can rename the file and then instruct Windows to remove it on the next reboot. However, this can't work for portable copies because the the path might not even exist on the next reboot.

**Comment by leonardder** [comment]
@jcsteh: I see your point here, and I guess that is a show stopper for the automatic updates part. However, I still think that one could have benefits from having a command line option for creating portable copies, similar to installing.

**Comment by Brian1Gaff** [comment]
Maybe the way to go is as \Ive seen on other portable apps, where somehow it 
detects that the new copy cannot run unless you exit x or y program first 
but as you say, it might well be that detectiing every use of a dll or 
whatever while in a portable app is not going to be possible due to 
permission issues in this context at least.
 I have noticed that portable updates, particularly when Firefox is the 
default browser can end up with firefox launched but no sign of the download 
dialogues at all.
 I've seen this issue with firefox on other programs which auto launch a 
browser as well, so I think its a Firefox issue that the address gets lost 
durring the first boot of Firefox in a session.
 In that case maybe we could make it browser selectable in some way as IE 
tends to work better in this respect.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
Command line parameters for portable copies are now incubating.

[**@jcsteh**](https://github.com/jcsteh) commented on [20 aug. 2016 00:46 CEST](https://github.com/nvaccess/nvda/issues/6281#issuecomment-241153791 "2016-08-19T22:46:34Z - Replied by Github Reply Comments"):
> The problem here is that apps sometimes refuse to release our injected dlls, which means they can't be removed until the app exits. With installed copies, we can rename the file and then instruct Windows to remove it on the next reboot. However, this can't work for portable copies because the the path might not even exist on the next reboot.

I think this is no longer a show stopper as soon as the fix for #7563 is merged, which places all NVDA dlls in a version specific folder. The worst that can happen is that old dlls remain in the portable copy folder structure, but according to the code implemented for old file clean up, the dlls for not more than one older version might remain in the respective folders.

**Comment by leonardder** [comment]
This code is now in next, many thanks to @zahyur. As mentioned in #6355, this part of the code might require some extensive testing before this code can proceed to master.
