### ISSUE TITLE
UIA: Handle combo boxes with value pattern

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6337]
Hi,

May apply to Windows 8 and later: there are combo boxes that does expose value pattern (for example, Settings/Devices/Auto play). As of now, NVDA handles ones without value pattern, but it might be helpful to work with ones that does expose this pattern.

Thanks.

**Comment by jcsteh** [comment]
We already use the value pattern where it's available. In fact, that's 
the way we already get the value from this particular combo box.

We don't report changes here because even though it supports the value 
pattern, it does not fire value property change events. Narrator gets 
around this by reporting the selection change event on child items. We 
can probably do the same in this specific case.

**Comment by josephsl** [comment]
Hi, In that case, it might be best to follow conventions unless MS does something interesting in Redstone 2. Thanks for letting us know about this.

**Comment by josephsl** [comment]
Hi,
Returning to this issue...

Redstone 2 did not change this, so I guess a PR might be in order. Thanks.

**Comment by michaelDCurran** [comment]
Fixed by pr #7132
