### ISSUE TITLE
The order of options in some dialogs

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6346]
Feedback on GUI, received via email.

With respect to the General settings dialog:

> The order of options currently shows many checkboxes separated by buttons or combos.  This makes the dialog look a bit messy. The dialog would look less messy if things were organised in the following order (note my suggested wording applies here ).  This ordering puts all the checkboxes together one above the other.
> 
> Language:  combo box  User default  collapsed 
> Logging level:  combo box  info  collapsed 
> Save configuration on exiting NVDA  check box  checked 
> Confirm before exiting NVDA  check box  not checked 
> Play sounds when starting or exiting NVDA  check box  not checked 
> Automatically check for updates to NVDA  check box  checked 
> Automatically start NVDA after logging on to Windows  check box  not checked 
> Use NVDA on the Windows logon screen  check box  not checked 
> Use saved settings on the logon and secure screens  button 
> OK  button 
> Cancel  button

![general settings](https://cloud.githubusercontent.com/assets/3491346/18268945/9e6524dc-7458-11e6-8adf-f6820ca1311f.PNG)

**Comment by feerrenrut** [comment]
Putting similar controls next to each other makes sense from a visual point of view, as long as they are not separating similar options. There is probably an argument to putting the most frequently accessed options first too.

**Comment by Adriani90** [comment]
I am not sure putting effort in achieving this is worth it. For example combo boxes might display new controls based on the value that is chosen (e.g. unicode normalization in the voice settings.

cc: @seanbudd, @SaschaCowley what is the position of NV Access on this?

**Comment by seanbudd** [comment]
@Qchristensen - any thoughts on this?

**Comment by CyrilleB79** [comment]
My opinion is that trying to group related options next to another is much more important than grouping similar controls.

Also, I am probably not the best person to give such advice, but my impression, with my remaining low vision, is that grouping similar controls does not bring a much better visual experience in the GUI. Is such grouping by control type a common experience in other applications or in Windows dialogs? I don't think so, but have not checked.

**Comment by Qchristensen** [comment]
I agree with grouping related options and ordering based on frequency of use.  For instance we have language at the top - many people might want to change that ONCE, sure - but having done that, do many people need to change language again vs for instance, changing log level when troubleshooting a problem?

Having the language first means you don't need to search for it if you have inadvertently changed language and need to fix the setting.... but actually I wonder if having the option first makes it MORE likely someone will inadvertently change the setting in the first place? This is particularly for language, but also for any drop down - eg if you open the dialog and try to down arrow, it will change the options in that drop-down rather than move between options (as some users may expect).

Aside from logging level (which still has the same drop-down first problem I just speculated) - I'm not sure any of these options are used more often than any others?

**Comment by seanbudd** [comment]
Closing as won't fix - arguments for this don't seem to be clear
