### ISSUE TITLE
browse mode: interact with object, NVDA indicate ROLE_UNKNOWN

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#6364]
setup:
Firefox 47.0.1

STR:
1. Open link
https://contact.line.me/en/
2. Press NVDA+ctrl+f to search string "Your device"
3. Press rightArrow 
  braille: clk (abbreviation before the content)
  speech: 
  This case could be a problem especially when user do not have braille display or ignore the message.
4. Press enter to expand a list with 10 items.
Notes:
In Chrome52.0 and Internet Explorer11.0, speech and braille do not provide feedback for the object.

**Comment by surfer0627** [comment]
Screen reader VoiceOver define this object as pup-up button.

**Comment by Adriani90** [comment]
I am not sure if this is bad implementation from the web developer though. Actually in every browser the control type is not anounced. NVDA only reports "your device".

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
Note that for example in focus mode you even don't get the label reported by NVDA.

**Comment by Adriani90** [comment]
The website is not working anymore, it requests login. @surfer0627 could you please post another example?

**Comment by surfer0627** [comment]
Hi,
Please try this link: (continue_without_login)
https://contact-cc.line.me/en/?continue_without_login=true

(Here the case is that user perhaps do not know the text "Your device" can be activated.)

Thanks.

**Comment by Adriani90** [comment]
This occurs in Firefox, Chrome and other browsers. I still think we are dealing here with bad web authoring but I am not sure.
cc: @JulienCochuyt do you have any suggestions?

**Comment by JulienCochuyt** [comment]
@Adriani90 wrote:
> I still think we are dealing here with bad web authoring but I am not sure.

I agree.
By inspecting the page, you'll see that the "Your device" control is indeed implemented twice.
First, there is a drop-down list made of HTML elements select and option, nothing to complain about.
But then, the DOM contains within nested div elements a second occurrence of the same content, in which the options' values are provided as links within an unordered list.
Those links are getting the focus rather than the drop-down.
I guess they are displayed above it and the whole thing is synced using js.
