### ISSUE TITLE
object customizer

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#6367]
Could NVDA developers please create an object customizer dialog or addon? this would do the following. 1. when on any object whether in simple review mode or not you could press NVDA control shift r. a dialog opens showing all object attributes. so say you are in an unknown app and you see a graphic you want to label. you can simply change its name. don't know what the graphic is? you can hit the label using tooltip and NVDA will route the mouse to the object no matter what that object is if mouse can't be routed it would say so. anyway then it would grab the tooltip info and put it in the edit box and you could label the object using the tooltip. still not enough? use the label with OCR button if OCR addon is installed it OCR's the current object focused with object nav and puts the result in the edit box for yu to let the label  alone or modify. object not behaving as you want? maybe you know that unknown object is a list box or an edit box or has text. with the object customizer just tell NVDA what the object is even label it if you wish. object customizer also will monitor objects for changes and in the dialog you can tell NVDA to monitor specific object and speak changes or not. This will let us without programming knowledge to customise NVDA a whole lot more. then share those customizations with others if you wish. also another feature I would like to see is object quickNav mode. It would be a toggle. when you turn it on rather than using the special object navigator commands you could hit left and right arrows or tab and shift tab to go through all objects on the screen. want to filter objects? page up and page down would let you switch object type such as button graphic edit box list box combo box and so on to quickly only jump between those object types. hitting enter would perform the default action or in object quick nav dialog let you make enter do mouse click on the object either left or right click and so on. once you hit enter you object nav would be turned off but only if you hit the turn object quicknav checkbox stay in quicknav box in the quicknav dialog. also object customizer labels and attributes would also apply in object quicknav.

**Comment by jcsteh** [comment]
This issue is quite broad:

1. Labelling is covered by #2111. The difficulty in implementing this is that there's no efficient, reliable way to identify a given object that works across applications.
2. Changing the type of an object that identifies as unknown is in most cases not possible. In order to treat something as an edit box, a check box, a list box, etc., NVDA has to know how to get the required information from the control. If it gets identified as unknown, chances are that standard techniques for accessing information from that control won't work. (If they were going to work, the control shouldn't have been identified as unknown in the first place.) There are some exceptions to this where the control does support a standard but didn't identify correctly, but they're the exception rather than the rule.

Thanks.
