### ISSUE TITLE
When using rtl languages, the text in the interface should be right justified.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#638]
**Reported by MHameed on 2010-05-02 09:18**
When using English interface, text using the UI is left justified (menues, dialogues etc).

When we switch to Arabic, the interface shows the correct text, but it still has a left justification. It should be to the right.

Thanks

**Comment by leonardder** [comment]
cc @feerrenrut

**Comment by feerrenrut** [comment]
@leonardder thanks for bringing this up. My previous experience with swapping between LTR and RTL languages makes me cautious to recommend a low cost of implementation for this one. It will at the very least require that all dialogs in the GUI are checked, I expect we will run into some edge cases. We will also need to consider how this can be made generic and fit into the the GuiHelper.

Before I assign priority to this, it would be handy if we could hear what the impact is to someone expecting right to left layout. Does left to right layout particularly impact the usability of NVDA?

**Comment by mohdshara** [comment]
as a blind user this has no influence on how I use NVDA, however, this may be very important for a sighted teacher, for example. I will have to specifically approach those and see what they think.

**Comment by bhavyashah** [comment]
@mohdshara  stated in https://github.com/nvaccess/nvda/issues/638#issuecomment-310996442 that you might consult sighted individuals about the significance of the issue of NVDA GUI displaying your text left to right instead of the ideal right to left. Could you please update us with regards to the response of the sighted individual you consulted? In case you haven't done so already, please consider kindly aiding us in evaluating the impact of this ticket by doing the same now.

**Comment by mohdshara** [comment]
hi. @bhavyashah just to acknowledge seeing your prompt. I can not get sighted help this week. But will do as soon as I can and report back. Somebody else from our Arabic speaking followers may do so if possible.

**Comment by bhavyashah** [comment]
With reference to https://github.com/nvaccess/nvda/issues/638#issuecomment-326422858, this is a friendly reminder for @mohdshara to kindly attempt to consult a sighted individual to let us know what the impact of the issue in the current interface in displaying RTL languages is.

**Comment by smtsh** [comment]
I am a sighted user of Persian (one Right-To-Left or RTL language), also I have some familiarity with Arabic, and I recently checked the user interface of NVDA in the Hebrew language. 
It seems that the current version of NVDA supports RTL view in all dialog boxes correctly (except for the NVDA menu that does not support RTL yet, and the important issue that revealed in the bug number of #8859). 
Notes: The RTL view is not just about the justification of text to the right corner (instead of left), it effects on more important aspects such as:
1. The visual sequence of words in translation into RTL languages that depend on the support of RTL view when the sentence contains some untranslated words. For example, when the expression of "NVDA website" in the NVDA help menu translate into an RTL language and the word of NVDA remain untranslated (as it is usual), it is visually seen as "website NVDA" (suppose the website word replaced with its translation) so the sequence of words change if RTL view be not supported (except when all words in a sentence be LTR or all of them be RTL). 
2. If the NVDA menu also fully supports RTL, the submenu will be located in the left side of the menu (because at that case the first means right corner and after that submenu will locate in the left of menu), so to access submenu users must use the left key instead of the right key. This will be more natural for RTL users that use also translated user interface of windows, where for example they also use the left key to go inside of the tree views in the windows explorer. 
3. If you need I am ready to help at least by checking the bug fixed versions of NVDA for RTL issue. 
@feerrenrut
@bhavyashah

**Comment by smtsh** [comment]
More explanation about the previous comment with a picture of Arabic windows:
https://docs.microsoft.com/en-us/globalization/localizability/mirroring-awareness

**Comment by mohdshara** [comment]
thanks @smtsh for summarizing the impact. Maybe related to this is your ticket #8865 
@feerrenrut is this enough for you to give this a priority?
