### ISSUE TITLE
review.handleCaretMove and braille.handler.handleCaretMove executed twice for caret moved in editable text situations

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6395]
In my research regarding #6383, I noticed that review.handleCaretMove() is executed twice for cursor movement. Once in editableText.EditableText._caretScriptPostMovedHelper (line 86), and once in NVDAObjects.NVDAObject (line 925). This is blocking a possible implementation of #6383. 

Reproduce: add a tones.beep call to review.handleCaretMove(). When following caret is enabled, you will notice that the beep is playing twice for every movement of the caret in applications such as notepad.

Should we do something about this? I assume that executing a function twice if once is enough just is not a good idea. Why is it executed in editableText.EditableText._caretScriptPostMovedHelper anyway?

**Comment by leonardder** [comment]
Updated the initial report with more details

**Comment by leonardder** [comment]
I think that removing lines 86 and 90 from editableText.py would be sufficient to fix this, due to two reasons:

1. In contrast to the event_caret implementation in NVDAObjects.NVDAObject, editableText.EditableText._caretScriptPostMovedHelper is not triggered on text input.
2. As far as I know, the only situation where _caretScriptPostMovedHelper is triggered when event_caret isn't, is when you are pressing end on the end of a line, down arrow at the end of a file, etc. Since this is no caret move, I don't think it is really necessary to update review information in these situations.

**Comment by jcsteh** [comment]
Unfortunately, this duplication is necessary because one or the other of these might not get called:

1. Some objects don't fire any kind of caret event that we can map to event_caret. The handleCaretMove in editableText at least allows cursor keys to update us accordingly.
2. Cursor keys are not the only thing that can move the caret. For example, someone might click the mouse. For objects which do fire event_caret, we want to be updated for these cases.
3. There's no way to know for certain whether an object does or doesn't fire event_caret, so we can't avoid one or the other of these in specific cases.
