### ISSUE TITLE
The images will be ignored when there aren't Alt attribute.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#6443]
Hi:
I find a tables that includes cover image. But the image can't be regornise as an image. However the reason is that the images haven't alt attributes. Below is the page:
https://wav.hnair.com/HUPortal/dyn/portal/DisplayPage?COUNTRY_SITE=US&SITE=CBHZCBHZ&LANGUAGE=US&PAGE=CBAG

**Comment by jcsteh** [comment]
Can you explain why it would be useful for this image to be reported? We can't report any useful information for an image that doesn't have an alt attribute. We do try to report something for unlabelled images in links or clickables, but only because you might need to interact with these. In contrast, an unlabelled, non-interactive image generally doesn't serve any useful purpose. Note that if we did report these, it would cause a lot of unwanted verbosity on a lot of websites.

**Comment by vgjh2005** [comment]
Hi:
I agree that these images don't waste our more time. But now we don't know there are there. So I feel that streamlining them is better way. For example,add a number for them.
Thanks!

**Comment by Adriani90** [comment]
@vgjh2005 you can actually see that there is an image with the object navigation.
1. Press t to go to the table
2. Press nvda+shift+left arrow with laptop keyboard layout

NVDA will report "grafic". In my view this is an information we really do not need because the grafic does not contain any relevant information for the purpose of the website. For people who want to explore it anyway, they can use object navigation. In my view we should not overload the browse mode navigation with information we don't really need.
So if you don't mind I will close this one because the implementation of this would weaken user experience rather than improving it. But I would like to know what other users tink before closing it.
cc: @ehollig, @mltony, @k-kolev1985, @novalis7747

**Comment by Novalis7747** [comment]
from my point of view I don't see any advantage of getting images without an alt tag announced. As stated before, we're getting notified if any action is combined with the image, and that's enough information, at least for me. Even if I would be notified about such images, what should I do with that kind of an image?
Maybe we can think about an additional checkbox in the document settings, like "announce neutral graphics without an alt tag". checking this option would speak "graphic only"

**Comment by Adriani90** [comment]
Cc: @leonardder

Von meinem iPhone gesendet

**Comment by fernando-jose-silva** [comment]
In the list of nvda addons there is an advertised addon called Auto alt text-
If nvda identified the graphics without description and then we could make use of the addon to describe it if desired would be very good.
I am in favor of this option being turned on or off.

**Comment by Adriani90** [comment]
@fernando-jose-silva how would an user describe the image if he or she cannot see it? You can interact with it in object navigation, routing the mouse to it and pressing right click. Then you can apply the description in some browsers. However, I think sighted people can properly interact with it, but most blind people would not need this.
I am closing this issue as per comments above, the consensus seems to be that this information is not really needed in browse mode and we have a workaround for this.
