### ISSUE TITLE
Tables ignore the numbers in word

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6446]
In this preview table, alt+ctrl+down in col 1 doesn't read the numbers.
[Match the mountain range with the continent.docx](https://github.com/nvaccess/nvda/files/520648/Match.the.mountain.range.with.the.continent.docx)
[Match the mountain range with the continent.docx](https://github.com/nvaccess/nvda/files/520650/Match.the.mountain.range.with.the.continent.docx)
change txt to docx

**Comment by derekriemer** [comment]
This is a fake test question which resembles the bug presented by a real test question in a bio psych class, of which I can't publish because I don't have the test it was part of any more, and it's against the professors policy for me to do so.

**Comment by feerrenrut** [comment]
There is a work around, by using the read current line command while in each cell. This will successfully read the whole cell but not the whole row.

**Comment by jcsteh** [comment]
Technical: This occurs because list numbering uses the line-prefix attribute, but this is only read for UNIT_LINE and UNIT_PARAGRAPH. Word table movement doesn't currently pass a unit. I think we can pass UNIT_PARAGRAPH. Passing UNIT_PARAGRAPH to speakTextInfo in `NVDAObjects.window.winword._moveInTable` does seem to fix this, but we need to check that there aren't negative implications.

**Comment by jcsteh** [comment]
P2 because this causes users to miss information and the fix should be fairly trivial.

**Comment by derekriemer** [comment]
Correct, however while arrowing   through a document they work perfectly fine.

Sent from a mobile device.
Please disregard errors as this is a smaller device.
