### ISSUE TITLE
Incorrect offset points generated in tree interceptor text info

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6460]
Steps to reproduce:
1. GO to nvaccess.org
2. Scroll to the text below the "What is NVDA" heading
3. Select the line below the heading
4. Start a python console
5. Do the following:
    >>> ti=nav.treeInterceptor.makeTextInfo("selection")
    >>> ti._startOffset
    323
    >>> ti._endOffset
    421
    >>> ti._getPointFromOffset(323).x
    401
    >>> ti._getPointFromOffset(323).y
    673
    >>> ti._getPointFromOffset(421).x
    401
    >>> ti._getPointFromOffset(421).y
    673

As you will notice, the x and y for both offsets are the same, which shouldn't be the case.

**Comment by jcsteh** [comment]
Currently, virtual buffers can only reliably map to the deepest object; i.e. they can't map to positions within the text. Doing otherwise is complicated because of the way embedded objects are exposed, things such as aria-label (which aren't really text as far as the underlying document is concerned), etc. Doing this efficiently would require some significant enhancements to the virtual buffer framework.

We're looking at moving away from virtual buffers in the future anyway (at least for some things), at which point this issue will no longer exist. However, that is probably quite some way off.

P4 because this would definitely be nice to have, but it doesn't affect most use cases currently.
