### ISSUE TITLE
NVDA prevents the "Space" key pressing in the element with the "checkbox" role assigned  

### ISSUE THREAD

**Issue by CodeKarno** [nvaccess/nvda#6466]
The following HTML markup can be used to reproduce the issue:  
```
<!DOCTYPE html> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head runat="server"> 
    <title></title> 
    <script> 
        ToogleState = function(evt) { 
            if(evt.keyCode !== 32) //Space 
                return; 
            var checkBox = evt.srcElement; 
            var value = checkBox.getAttribute("aria-checked"); 
            checkBox.setAttribute("aria-checked", value === "true" ? "false" : "true"); 
        } 
    </script> 
</head> 
<body> 
    <form id="form1" runat="server"> 
        <input type="button" /> 
        <div tabindex="0" role="checkbox" aria-checked="false" 
         onkeydown="ToogleState(event)">Select all</div> 
    </form> 
</body> 
</html> 
```
According to the [WAI - ARIA - Checkbox guidance](https://www.w3.org/TR/wai-aria-practices/#checkbox), pressing the Space key should change the state of the checkbox. However, NVDA does not pronounce that the checkbox state is changed in this case. The issue can be reproduced in NVDA v2016.3, but does not occur in previous versions.

**Comment by jcsteh** [comment]
When you're in browse mode, pressing space or enter clicks the element under the browse mode cursor. This is the only reliable way to provide access to all elements, since many don't implement keyboard handling. If you want to pass keystrokes directly to a control, you either need to switch to focus mode or use the pass key through command. Presumably, a check box would support mouse clicks as well as keyboard events, so this normally isn't necessary.
