### ISSUE TITLE
In some dialogs of NVDA there is no visual separator between the "Close"/"OK"/"Cancel" buttons and the controls above them, as it is in other dialogs of NVDA

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#6468]
With the changes in the latest "next" snapshots of NVDA, I see some very good improvements in terms of the visual aspect of the dialogs and windows of NVDA.

I was checking some of them and I've came across the one for managing the add-ons. I approve of the "Close" button to be right-aligned (as are the similar buttons in most of the other dialogs and windows of NVDA), but currently in the "Add-ons Manager" dialog, there is no separator between the "Close" button and the row of buttons above it. That makes it visually to appear as if the "Close" button is of the same group as the other buttons on the row above, witch is not true. If possible, there should be a visual separator between the "Close" button and the row of buttons above it.

Now that I've checked some other dialogs, the same is true for the "Configuration Profiles", the "Exit from NVDA" and the "About NVDA" dialogs.

P.S.: The dialogs of the "NVDA Remote" add-on are not affected by the improvements mentioned in the first paragraph, but I guess that is for another ticket (?).

**Update: (via https://github.com/nvaccess/nvda/issues/6468#issuecomment-520366991)**
- The visual separator has been added to the Add-on Manager dialog
- @DataTriny created #10076 to improve the appearance of the Exit dialog

**Remaining:**  The Configuration Profiles dialog.

**Comment by josephsl** [comment]
CC @feerrenrut; I personally agree with this for consistency reasons (and Reef’s work is something some add-ons should adopt, particularly those that have config dialogs or ask for file paths). Thanks.

**Comment by jcsteh** [comment]
Note that add-ons are responsible for their own GUIs, so you should file any issues regarding add-ons in the appropriate place for that add-on. That said, with these changes, we've introduced a framework which should make it a little easier to produce dialogs that are more visually appealing/consistent and add-ons can use this too.

**Comment by feerrenrut** [comment]
I tend to agree with this, specifically the add-ons dialog. We planned on addressing a few layout issues on this dialog at some later point however adding the separator is a quick fix that would make this dialog more readable.

The separator was introduced in the settings dialogs to help to visually separate the controls for the settings, from the controls for the dialog. The 'about' and 'exit' dialogs I feel are different and dont fit this pattern, the buttons on these controls relates to the controls. 

In terms of priority, since its easy to implement and we are fairly sure its a good idea for the add-ons dialog, this portion of the work should be p2.

The rest of the work (configuration profiles, etc) should be considered p3 since we are not so sure about how that will look. Its easy to try, but if it doesn't look right, then the implementation time could go up significantly to re-organise the dialog to make it consistent.

**Comment by Adriani90** [comment]
@feerrenrut I am not sure, Bu I saw recently a discussion on this topic on Github. Is there a PR related to this already?

**Comment by Adriani90** [comment]
@feerrenrut this issue seems to have p2 and p3 label assigned. Which one should be kept?

**Comment by DataTriny** [comment]
Hello there,
Given that a visual separator have been added to the Add-on Manager dialog, and that I just filled #10076 to improve the appearance of the Exit dialog,the only issue remaining relates to the Configuration Profiles dialog. I would then mark this issue as p3.

**Comment by feerrenrut** [comment]
Generally I think this is a fairly quick thing for a developer with vision, given that, I would prefer to make it P2 and get the issue closed. 

I have updated the description, to note the work done.

**Comment by lukaszgo1** [comment]
What about About dialog? It was also mentioned in the original report.

**Comment by DataTriny** [comment]
@lukaszgo1 About dialog is technically a message box and thus the layouting is dictated by Windows. So I guess that we can't do anything here unless we create a custom dialog (which in my opinion would be a waste of time given that visually impaired users should already be familiar with message box design).
@Adriani90: since I guess you are maintaining a table of NVDA developers to dispatch the work, could you add me as "visually impaired"? Just in case there is a need for graphical thing somewhere and I miss the call. Thanks!

**Comment by k-kolev1985** [comment]
Actually, now the "About" dialog is fixed - there is a visual separator below the text and above the "OK" button.

Yes, this visual design probably is determined by Windows itself, but I think it is not the only factor. I think WX also has a saying in how such dialogs look, but I might be wrong about the last one.

**Comment by Adriani90** [comment]
@DataTriny thanks very much for the Detail, I will certainly consider this wehn ccing in certain issues etc.
