### ISSUE TITLE
Limit cursor blink rate

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6470]
Warning: the following STR may harm your display, don't try it with anything under 30 ms or so.
1. braille settings.
2. set cursor blink rate to 1 millisecond.
3. press okay.
Your display's cursor will go nuts. Can this be limited to something like 150 ms to prevent damage to the pins being forced up and down so rapidly? I haven't seen damage ever, but accidentally did this, and it didn't sound good for the display.

**Comment by feerrenrut** [comment]
This is an easy fix, and it seems unlikely anyone would want to set their cursor blink rate below say 200 ms (5 times a second), therefore P2.

When implementing
* take into account the introduction of spin controls for this setting: see #6417
* test the behaviour of NVDA when a previously set "too low" value is present. It's ok for this to round it up to the new minimum.

**Comment by derekriemer** [comment]
@feerrenrut note that 0 is used for don't blink the cursor

**Comment by feerrenrut** [comment]
@derekriemer Thanks for pointing that out. Looking at the code, there does not seem to be any explicit decision for this behaviour, I think it more likely that this is a "happy accident" and probably a quirk of calling `wx.PyTimer.Start()` with a zero value.

When the value is set to zero, I assume the cursor is present (but not blinking)? As opposed to being disabled which could be achieved with the `show cursor` option.
In order to implement this, I think we would need to add another checkbox.

Is this a valuable feature? Considering this is undocumented behaviour, are people currently disabling the blink for the cursor by setting it to zero?

**Comment by jcsteh** [comment]
> @derekriemer Thanks for pointing that out. Looking at the code, there does not seem to be any explicit decision for this behaviour, I think it more likely that this is a "happy accident" and probably a quirk of calling `wx.PyTimer.Start()` with a zero value.

I probably should have thought of this. :) Actually, it's not an accident. See around line 1517 of braille.py:

```
		blinkRate = config.conf["braille"]["cursorBlinkRate"]
		if blinkRate:
			self._cursorBlinkTimer = wx.PyTimer(self._blink)
```

Note the `if blinkRate`. That evaluates to False if blinkRate is 0, which means the timer won't get set.

> When the value is set to zero, I assume the cursor is present (but not blinking)?

Correct.

> Is this a valuable feature?

I think some users will want it, but maybe @dkager could shed more light?

**Comment by feerrenrut** [comment]
It wouldn't be hard to add an explicit option for this, however given its undocumented we should consider whether we should do this.

**Comment by jcsteh** [comment]
It's certainly true that it's not documented, but I definitely knew about
this (my negligence in not flagging it during review notwithstanding). So,
I'm pretty sure it was intentional and it was just never documented
properly.

I'd be interested to know what UI other screen reader use for this setting.

**Comment by feerrenrut** [comment]
Ok i'll extend my PR to cover this.

**Comment by dkager** [comment]
Off the top of my head, SuperNova has different cursor shapes and has a blinking and a non-blinking  version of each. That seems to be a bit muddy, the shape and the blinking are two separate things. The "0 to disable" semantics make more sense. I agree 200 ms is a sane minimum.

Would rate limiting braille in general make be useful? E.g. when rapidly scrolling through a menu the display goes nuts too.

**Comment by feerrenrut** [comment]
Rate limiting the output of braille generally might make sense, but I think that should be handled as a different issue. While it could potentially share / change the implementation of this issue, it raises other questions and there are more things to consider than with limiting the cursor blink rate. 

If you would prefer not to have a new check box as an explicit way to disable cursor blinking please comment on the pull request #6558. Or if you would like to try out this implementation to see if it works for you take a look at branch `i6470-LimitCursorBlinkRate`

**Comment by dkager** [comment]
Yes, rate limiting in general is a separate issue. It was just a side thought here.
I usually have the cursor disabled altogether, but will try the branch you mentioned. Thanks!
