### ISSUE TITLE
NVDA speaks long passages of text in 100 character chunks

### ISSUE THREAD

**Issue by augustocallejas** [nvaccess/nvda#6481]
When navigating (using only the arrow/directional keys) to elements with long pieces of text (> 100 characters), NVDA speaks only 100 characters at a time. Using the sample HTML file below, if one starts navigating from the first checkbox (using the down arrow), when the 2nd label is reached with the "lorem ipsum" text, NVDA only speaks up to "labore". Pressing the down arrow again speaks the remainder of the text, starting at "et dolore":

1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
2. et dolore magna aliqua

Pressing the down arrow one more time, the checkbox is spoken. NVDA appears to split up the text into 100 character chunks, and speaks each chunk after pressing the down arrow. Note that the issue isn't an audio issue - this was confirmed by enabling the NVDA Speech Viewer and noticing that the the entire text wasn't being spoken, but only the 100 character chunks.

Windows 10.0 (Build 10240) (Running in VirtualBox 5.1.6 on Mac OS X 10.11.6
Firefox 49.0.1
NVDA 2016.3

`<html>
<body>
<label for="username1">Click me</label><br/>
<input type="text" id="username1"/><br/>
<label for="username2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</label><br/>
<input type="text" id="username2"/><br/>
</body>
</html>`

**Comment by derekriemer** [comment]
Hi: 
This is expected behavior. See this section of the users guide.
9.1.1: 

##### Maximum Number of Characters on One Line
This field sets the maximum length of a line in browse mode (in characters). 



This defaults to 100 characters and can be set to the users liking.
http://www.nvaccess.org/files/nvda/documentation/userGuide.html#toc74



Please reopen this ticket if I have mistaken what you meant.
Thanks.

**Comment by augustocallejas** [comment]
Thanks, confirmed that this was the issue.
