### ISSUE TITLE
Mouse tracking issues on second monitor

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6598]
When a second monitor is connected (with the desktop extended to it) and mouse tracking is enabled in NVDA, mouse tracking reports as if the mouse was moving up and down the edge of the first monitor - as if it was on the very far left, right, top or bottom, depending on the location of the second monitor.  Playing audio coordinates seems to confirm this.

Preferred behaviour: Correctly track mouse location on multiple monitors, just as it is tracked on the first monitor.

**Comment by feerrenrut** [comment]
Yes, I can reproduce this with `NVDA version next-13701,967f1697`.

Technical:
A related bit of code would be the positioning of the Speechviewer which needs to check if the layout of the monitors is different from when the speechviewer window was saved.

Setting priority 2, this could be quite a confusing bug and should be quick to fix.

**Comment by jcsteh** [comment]
I do wonder how common multi monitor setups would be among screen reader
users. I would have thought not so likely. I'm also not convinced this will
be easy to fix, as it depends what coordinates get returned from a11y
implementations, how hit testing behaves, etc. Still, happy for this to be
p2 for now; we can consider dropping the priority later if the
implementation cost turns out to be prohibitive.
