### ISSUE TITLE
Screen reader reads twice when entering input in a form with aria-live="assertive" on Chrome

### ISSUE THREAD

**Issue by classicmike** [nvaccess/nvda#6608]
Hi,

I've been asked to resolve an issue where I need the screen reader to read out some text after it has been inserted dynamically into the DOM from Ajax. I know that in order to do this we need to use aria-live. I have inserted 'aria-live="assertive"' in the parent <form> tag.

The insertion works, with the exception that whenever I focus on an input and enter some text, each character I enter gets repeated twice. Example would be I focus on an input, I type in the letter 'a', the screenreader would read 'a' twice.

I have created a codepen and have been able to replicate this under Google Chrome. http://codepen.io/mikethefrontenddeveloper/pen/Ypxdby.

I get the feeling NVDA reads it twice, because it would read the change i.e. text input then it would read it again to confirm the input to change in terms of the HTML document. I am also experiencing the repetition when text gets dynamically injected into the DOM as well. You can see that in the codepen as well.

I am not an expert in accessibility, but if some clarity can be provided on how NVDA reads the aria-live regions, that would be great. Thanks.

**Comment by jcsteh** [comment]
I think there are two issues here:

1. aria-live should not be set (or inherited) on any element which accepts input. Otherwise, user input gets included as part of the live region and is thus reported. This is in addition to speaking of typed characters if the user has that enabled. If you must set aria-live on an ancestor of the input, set aria-live="off" on the input itself to override the live region for the input.
2. You noted that "I am also experiencing the repetition when text gets dynamically injected into the DOM". That seems to be a Chrome issue that we haven't pinned down yet; see #5919. It'd be great if you could confirm whether this happens in Firefox for DOM injection (not typing).

**Comment by jcsteh** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [1 Dec 2016, 08:31 GMT+10](https://github.com/nvaccess/nvda/issues/6608#issuecomment-264017696 "2016-11-30T22:31:50Z - Replied by Github Reply Comments"):
> 2. You noted that "I am also experiencing the repetition when text gets dynamically injected into the DOM". That seems to be a Chrome issue that we haven't pinned down yet; see #5919.

I just tested and this appears to be fixed in Chrome Version 60.0.3112.113 (Official Build) (64-bit).

As for the issue with typing being echoed, see https://github.com/nvaccess/nvda/issues/6608#issuecomment-264017696 regarding not having aria-live on inputs.

Closing.
