### ISSUE TITLE
API docs: detailed docstrings for various classes

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6654]
Hi,

Briefly mentioned in #6589:

At the moment some important classes does not have associated API docs. This include some controls in Outlook app module, IAccessible objects and others. Thus I propose adding at least a one-liner description for these classes (the more detailed, the better) so we can let new developers have an easier time understanding how these controls work and rationale for including them in NVDA Core.

Thanks.

**Comment by jcsteh** [comment]
I don't think we need to track these things as big "projects". If you identify something that needs a docstring and you want to write it, we'd be grateful for a pull request. If you are trying to reuse or work on something and you don't understand how something works due to poor documentation, please do file an issue so someone who knows the code can fix it. If you're working on some area of code and you see a missing docstring in the area, please feel free to fix it as part of your work. Major code "audits" just aren't an effective use of time and resources at this point, especially relative to other priorities.

Thanks!
