### ISSUE TITLE
Announcement of supports autocomplete state

### ISSUE THREAD

**Issue by LJWatson** [nvaccess/nvda#6663]
When NVDA encounters a standard input with type="text", it announces "has autocomplete".

```
<div class="form-group">
<label class="form-label" for="full-name-f2">Full name</label>
<input class="form-control" id="full-name-f2" type="text">
</div>
```

 This seems to be driven by IA2 exposing standard text inputs as having the state "supports autocomplete", but announcing "has autocomplete" when no such functionality exists seems confusing for users.

**Comment by jcsteh** [comment]
The functionality does exist, though. It's just native functionality provided by the browser, rather than by the site itself. If you use the same input several times in Firefox, pressing down arrow (or typing some text and then pressing down arrow) will present autocomplete suggestions based on previous entries in that field.

Hope this helps explain this.
