### ISSUE TITLE
Option to Present messages received by NVDA Controller in braille

### ISSUE THREAD

**Issue by Piciok** [nvaccess/nvda#6670]
It would be useful to have an option which, once enabled, would display messages received by the NVDA Controller Client directly in braille, just like it currently works with system notifications.
This would be useful while playing Audio Games or using software that generates such messages with braille output alone.

Haven't found this one being discussed yet. I hope it's not a duplicate.

**Comment by derekriemer** [comment]
Do you mean
/* [comm_status][fault_status] */ error_status_t __stdcall nvdaController_brailleMessage( 
    /* [string][in] */ const wchar_t *message);

**Comment by derekriemer** [comment]
@jcsteh the .h files generated have strange comments at the beginning of lines. Is this known?

**Comment by jcsteh** [comment]
@Piciok: nvdaController has speakText and brailleMessage functions. There is no general message function. We figured this would give the client the maximum degree of control, especially since self-voicing is inherently specialised. Also, it's not always appropriate to braille all spoken messages. It's thus up to the client to use these appropriately.

**Comment by jcsteh** [comment]
@derekriemer: What do you mean by "strange comments"? Do you mean the com_status, etc. stuff? That is just telling the caller about the flags from the IDL, which indicate the kinds of status codes the caller might receive, etc. This is standard for IDL stuff. I'm not sure we could disable it even if we wanted to.

**Comment by OzancanKaratas** [comment]
@jcsteh Hi,
 
How to compile NVDAControllerClient for other programs? I want to compile it myself. Which files must be used?
