### ISSUE TITLE
Moving about in long PDFs in adobe reader switches pages unexpectedly

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6673]
When using NVDA with the latest version of adobe reader in long documents, pressing the arrow keys to move about makes you switch pages unexpectedly (especially when you're at the top or bottom of the page), making reading a frustrating experience. I don't remember having this problem with jaws. Has anyone else observed this?

**Comment by jcsteh** [comment]
Can you please try the following:

1. Open Adobe Reader.
2. Open Preferences by pressing control+k.
3. In the Categories tree view, select Accessibility.
4. Tab to the "Always use Page Layout Style" check box and ensure it's checked.
5. Tab again to the combo box for this option and select "Single Page".
6. Press OK, restart Adobe Reader and try reading again.

This happens because NVDA scrolls the document as you move the browse mode cursor so that sighted users have some idea of where you are. Unfortunately, in certain page layout styles, Adobe Reader then scrolls to a new page, which requires us to reload browse mode.

I guess we'll need to figure out some logic to avoid scrolling when this might occur, but I'm not sure how we'd do this.

P2 to investigate this and at the very least document the single page option.

**Comment by bhavyashah** [comment]
@jcsteh From https://github.com/nvaccess/nvda/issues/6673#issuecomment-270037047, do you mean that further testing on the part of @Neurrone is required, or that you have successfully reproduced this issue and a technical investigation needs to be made by Adobe and NV Access themselves?

**Comment by jcsteh** [comment]
I was asking @Neurrone to test using the steps I provided and report back. If that doesn't fix the issue, my diagnosis is incorrect.

**Comment by Adriani90** [comment]
@jcsteh your suggestion above works great. I think @mltony came up with a solution for this with the fast browse mode feature.

**Comment by mltony** [comment]
@Adriani90, fast browse mode still calls .scrollIntoView(), so it wouldn't fix this problem. However, it would make sense to provide a new option to prevent calling .scrollIntoView() in Acrobat Reader. The reason why we scroll to current elemnt in web browsers was that there are some pages, such as Amazon, that rely on that for infinite scrolling feature. But for blind people I don't think there'd be any regression in Actobat Reader if we don't scroll.

**Comment by Neurrone** [comment]
Sorry for not doing this sooner.

Doing this still doesn't fully solve the problem for me, especially if I don't pause between moving to the next page, and pressing down arrow. If not enough time has elapsed, pressing down arrow repeatedly says unknown, with each press of the down arrow scrolling to the next page of the PDF.

**Comment by Adriani90** [comment]
@Neurrone, @mltony If I am not wrong the current implementation of  fast browse mode calls .scrollintoView only when switching to focus mode mannually or automatically.
@Neurrone could you please give an update how NVDA 2023.1 works now in Adobe acrobat last version when automatic focus focusable elements is turned off with nvda+8 or in browse mode settings?

**Comment by Adriani90** [comment]
oh I might be wrong with the .scrollintoView, My assumption was that moving system focus calls .scrollintoView but this might also occur without forcing the system focus to move.

**Comment by Neurrone** [comment]
I've not seen this problem for some time now.
