### ISSUE TITLE
nvda jumps to beginning of document unexpectedly when using adobe reader.

### ISSUE THREAD

**Issue by devil418** [nvaccess/nvda#6678]
When using adobe acrobat reader and switching between multiple programs (i.e. reader and text editor), nvda sometimes jumps to the beginning of the document. It happens when I switch back to adobe reader.

**Comment by josephsl** [comment]
Hi, which version is this – 11, DC? Thanks.

**Comment by Brian1Gaff** [comment]
Yes and sometimes Firefox's position changes as well. I actually thought it 
might have been responding to one of the keys when I switched active 
programs around, but  maybe it is something else.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by bhavyashah** [comment]
@miki123211  Could you please respond to @josephsl's https://github.com/nvaccess/nvda/issues/6678#issuecomment-269130885 by providing system information, particularly the version of Adobe Acrobat Reader in use?

**Comment by Brian1Gaff** [comment]
I'm not sure if any of these adobe reader threads mention it, but one of the 
main issues about strange goings on is because of no or poor tagging of 
reading order in the file to start with. Not much a screenreader can do 
about this. Adobe should force  creators to tag their files correctly in my 
view.
You can often see the mess if you extract the text from a pdf, either in 
reader itself or using the text reader from webbie.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
This occurs only when reading entire document and not page by page. Another case where it could happen is when you switch to Adobe Acrobat window and press arrow keys before NVDA gets the focus on the text. That means NVDA reports the window but passes through the arrow keys directly to the Adobe Acrobat and the pages change instead of line by line navigation. After one or two seconds NVDA finally gets the focus on the text and then using arrow keys is not being passed through anymore.

cc: @derekriemer, @leonardder

**Comment by Adriani90** [comment]
This works just nice in the last Adobe reader version with the default behavior from #11190.
Closing as works for me.
