### ISSUE TITLE
Difference between report current line and review current line with automatic language switching checked

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#6726]
STR:
1. Open test.html in Firefox.
2. Switch to English eSpeak, with Automatic language switching checked.
3. Press report current line twice. I hear letters spoken in English.
4. Press review current line twice. I hear letters spoken in Esperanto.

Expected:
Both of these should speak Esperanto letters, since I'm reading the same text.
[test.txt](https://github.com/nvaccess/nvda/files/703441/test.txt)

**Comment by jcsteh** [comment]
Confirmed. Occurs because script_reportCurrentLine calls speakSpelling with info.text instead of spellTextInfo. (The review script does call spellTextInfo.) I'm guessing this was just an oversight in 55b779e8. @MichaelDCurran, can you think of any reason we wouldn't have changed reportCurrentLine other than oversight?

P2 because while it's probably not a common use case and there's a simple workaround, it should be trivial to fix. Reassess priority if fix turns out not to be trivial.

**Comment by michaelDCurran** [comment]
@jcsteh no reason that I can think of.
