### ISSUE TITLE
Problems with command consoles and object navigation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#673]
**Reported by jteh on 2010-05-26 22:41**
When you move to a command console with object navigation, NVDA connects to this console, which allows this console to be reviewed. While this is useful, it presents three problems:
1. When you move to the console using object navigation, the console is connected, but it isn't disconnected when you move away.
   - This is because there is a becomeNavigatorObject event, but no event for the reverse.
2. When object navigation causes NVDA to connect to a console, new text is reported for that console. New text should only be reported for focused consoles.
3. Because only one console can be connected at a time, if a console is focused and the user moves to another console with object navigation, the user can no longer access the focused console. That is, new text is not read nor is caret navigation, backspace, etc.

While issues 1 and 2 can be fixed, it is probably not possible to solve issue 3, as this is due to a limitation of the implementation in Windows. Therefore, the only option may be to not connect to consoles for review.

Work around: To restore functionality to a focused console, move the navigator object back to the focused console.

This functionality was introduced in 4808ab654c473343bac0a49b185128d8e31ce116.

**Comment by leonardder** [comment]
@JCSTeh: Can't we tie console connect/disconnect to event_gainFocus/leaveFocus?

**Comment by jcsteh** [comment]
Sure we can. However, that will make it impossible to review non-focused consoles. Still, that's probably the best we can hope for at this stage, so that's probably the solution we should go with.

**Comment by Adriani90** [comment]
Any update on this?

**Comment by Adriani90** [comment]
cc: @derekriemer

**Comment by codeofdusk** [comment]
Once #9771 is merged, this issue will be resolved on Windows 10 version 1803 and later; UIA has no notion of "connecting" to consoles like the legacy support did. However, it is still not fixed on Windows Server and LTSC 2016 (Windows 10 1607), which will still be supported for many years to come. Unfortunately though, since the legacy console support requires that we connect to consoles in this way, we cannot fix the bug on this older release. Since the issue has either been resolved or resolution is impossible, I vote to close it. You are, of course, welcome to investigate further for legacy consoles and propose a solution if one exists!
