### ISSUE TITLE
in Notepad++, the key mapper is inaccessible with simple object navigation.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6730]
1. In notepad++, open the key mapper from the settings menu.
2. Use object navigation to find the pane.
3. if simple object nav is enabled, note that you cannot drill down into the list which is a child of the pane.
4. Disable simple object navigation.
6. now, drill down into the pane. You'll find a window, and then a list with the keys in it.

**Comment by jcsteh** [comment]
That's because that list is invisible (check with report current navigator
object or dev info). Invisible objects get filtered out in simple review
for obvious reasons.

The content that is displayed on screen there is actually quite different
to what's in that list; have a play in screen review or OCR. For example,
on screen, we see two columns:

Name Shortcut
1New Ctrl+N
...

In the list, we get four separate items for this:

00000-001|UA|Name
00000-002|UA|Shortcut
00001-001|UA|New
00001-002|UA|Ctrl+N

My guess is that they're using the list internally to manage content, but
they're drawing their own view of the content and hiding the list. No idea
why.

**Comment by jcsteh** [comment]
So, not being able to see this list as it is now is by design; it's invisible. Happy for you to morph this issue to cover the inaccessibility of that control... but the only way you can probably access that is via screen review unless the owner drawn view actually aligns with the coordinates of the invisible list (which I'm not sure about). Hacking around that would be a p4.

**Comment by derekriemer** [comment]
This is covered in the Notepad++ addon, although IMO I hate my design for it. I've tried three times and they break it on every update. I'm tempted to say I'm gonna rip it out of the app module since I'm planning to some day merge that into core.

**Comment by derekriemer** [comment]
Closed as there's probably not much needing fixed here that my addon doesn't already try to address.
