### ISSUE TITLE
Fix alignment and spacing of the nvda find dialog

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6768]
The NVDA find dialog has a few alignment and spacing issues. It could probably be updated to use the `GuiHelper`.

**Comment by Adriani90** [comment]
cc: @marlon-sousa

**Comment by marlon-sousa** [comment]
Hello, perhaps using the find dialog component from wx widgets can fix that. T!is is in ny to do list and I didn.t do it before because I hopped that my changes would be integrated into 2019.1 but cinse it wasn.t then I think I can integrate this now. The only thing I would like to be sure is that the feature will be integrated in 2019 2 regardless of this fix.

**Comment by Adriani90** [comment]
@marlon-sousa your change regarding search history is now part of Alpha, so it will be 100% be part of 2019.2 if no further bugs are identified by users. As of now we do not have any negative reports about that. And as far as I can see, everything works well in Alpha so there is no reason not to include it in 2019.2.

**Comment by CyrilleB79** [comment]
It seems that this issue was fixed in #10354.
Unless I have missed something, it can be closed.

**Comment by feerrenrut** [comment]
Yes, thanks @CyrilleB79 closing.
