### ISSUE TITLE
Can't read status bar in File Explorer (Windows 10)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6769]
In File Explorer (WINDOWS+E), pressing NVDA+end (laptop: NVDA+shift+end) reads "No status line found", even if the status line is enabled (it's possible to disable it in the folder options.

Expected behaviour, read the status bar, for instance, "30 items, 1 selected, details view button, large icons view button".

**Comment by josephsl** [comment]
Hi, there is an issue that’s on file that deals with this problem. Note that this isn’t specific to Windows 10, as this exists in other versions as well. Thanks.

**Comment by Qchristensen** [comment]
I was sure this had come up before but I couldn't find an issue when I created this one.  I wasn't sure whether it was Windows 10 specific or not.

**Comment by josephsl** [comment]
CC @MichaelDCurran, @JCsTeh, I forgot which issue number was where we talked about tweaking api.getStatusBar(). Thanks.

**Comment by feerrenrut** [comment]
Perhaps relevant:
* Unable to find status bar in Visual Studio Ref bug #5618
* Unable to find status bar in Office aplications #649
* appModules should have a way to override the logic to retrieve status bar text in api.getStatusBar #2125
* Status bar handling does not work with Java Access Bridge applications #5674

**Comment by feerrenrut** [comment]
In https://github.com/nvaccess/nvda/issues/6842#issuecomment-410670910 @ruifontes proposed the following appmodule as a fix. This can probably be adapted into a pull request to fix this issue.
[explorer.py.txt](https://github.com/nvaccess/nvda/files/2268565/explorer.py.txt)

**Comment by Adriani90** [comment]
@ruifontes are you planing to raise a pull request with the las version of the NVDA Addon?

**Comment by ruifontes** [comment]
No, I am yet gaving my first steps in GitHub...
If you, or someone else, can do it, better!

**Comment by lukaszgo1** [comment]
In my view we  cannot proceed with this until #4640 is implemented. The problem with the current approach is the fact that the entire script for reading status bar is duplicated, therefore any updates to it needs to be performed in the Explorer appmodule in addition to the globalCommands.py

**Comment by josephsl** [comment]
Hi,

Now that #4640 is a reality, let's proceed with solution design. The solution is actually simpler than what Rui proposed earlier. There are two possible solutions:

1. Screen coordinates: if it is determined that File Explorer status bar text is located 3 percent to the right of the bottom-left corner (absolutely 3 percent to the right regardless of screen orientation, resolution, and DPI), then Rui's solution should work. I doubt that's the case, as things can change depending on the three factors noted above. This solution has a flaw: what if wrong item gets announced, such as when all windows are minimized?
2. UIA and overlay class: define an overlay class for status bar that handles status bar text correctly (overriding get_name), then locate this status bar via UIA tree traversal (IUIAutomation::CreatePropertyCondition/ElementFromHandle). For reference, UIA automation ID for the status bar object is "StatusBarModuleInner". This option raises concerns about performance and responsiveness.

I advise exploring both options and choosing the one that works across all of the following scenarios:

* Windows versions
* Screen resolution and orientation
* High DPI
* Window is maximized and restored
* Regardless of whether an item is selected or not
* Opening hidden operating system folders

I'm personally in favor of option 2 because it can work better across screen resolutions, orientation, and DPI setting.

Thanks.

**Comment by JulienCochuyt** [comment]
Thanks to @josephsl hints, I could prototype option 2 with what seems at first glance running with decent performance.
However, complying with the current `api.getStatusBarText` implementation requires overlaying the status bar children, which in turns requires to look up the object parent in `chooseNVDAObjectOverlayClasses`.
The prototype works fine, but I've already encountered in other situations corner-cases where this parent lookup might be risky (freezing NVDA in some circumstances I could not well determine).
@josephsl, can you strongly confirm looking up the parent object role in this very context is 100% sure during `chooseNVDAObjectOverlayClasses`?

Furthermore, the status bar itself and two of its potentially three children in latest Windows 10 have names that are simply reformulations of their role's label. This info is of no use, but other/future implementation may differ. Thus I'm a bit concerned by dropping the names altogether in the overlays.

The safest solution IMHO would be to allow the app module to also provide a `getStatusBarText` implementation.
This way, `chooseNVDAObjectOverlayClasses` would not be penalized by extraneous tests, the `report_statusBar` global command would still move the navigator object to the status bar for eventual interaction, and the announced text would be much more informative, eg. stating "No elements selected" when the selected element counter is missing.
This approach would also ease customizing the announce depending on the Windows version if need be.

**Comment by JulienCochuyt** [comment]
By the way, wouldn't the UIAWalker method be a suitable solution for cases where the standard `api.getStatusBar` mechanism could not locate one? Or is this too performance-risky? (I'm not experienced in UIA at all.)
