### ISSUE TITLE
Links in Word aren't displayed with the lnk indicator in braille

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#6780]
STR:
1. Open Word, tested with Word 2016.
2. Type "This is something to click on."
3. Select the word "click", right-click on it, choose Hyperlink... and make it a link.

Speech reads:
This is something to link click out of link on.
Braille shows:
This is something to click on.
Expected:
Braille somehow shows the link, e.g. with the "lnk" indicator.

**Comment by dkager** [comment]
Could be added to braille.getFormatFieldBraille(). But isAtStart is False if a link appears in the middle of some text.

We should probably also work something out for comments/revisions.

**Comment by jcsteh** [comment]
P2 because this is important info that isn't available to braille only users.

[**@dkager**](https://github.com/dkager) commented on [23 Jan. 2017, 5:19 am AEST](https://github.com/nvaccess/nvda/issues/6780#issuecomment-274352242 "2017-01-22T19:19:27Z - Replied by Github Reply Comments"):
> Could be added to braille.getFormatFieldBraille(). But isAtStart is False if a link appears in the middle of some text.

isAtStart isn't useful here, since that's to ensure we don't present info in the middle of the line that should only be presented at the start. However, we're probably going to need a cache of attributes we presented in the last chunk of the line so we don't present them again.

> We should probably also work something out for comments/revisions.

Indeed, though I don't consider that quite as high priority (though still important) and we should address it separately.

**Comment by dkager** [comment]
> However, we're probably going to need a cache of attributes we presented in the last chunk of the line so we don't present them again.

It looks like this only applies if you have some text selected. Then you have three chunks: text before and after selection, and the selection itself. But that implies there can be multiple "link start" commands for the same text. Is that true?

**Comment by jcsteh** [comment]
FormatFields contain all of the formatting relevant to the text they
immediately precede. So, if you have a link consisting of two characters
and you getTextWithFields just for the second character, the field will
contain link: True. That's why I say you'll need a cache.

**Comment by dkager** [comment]
I'm going with a full cache like is used for speech, because that looks the most extensible.
