### ISSUE TITLE
Kindle: Get page number for location text

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6794]
1. Search for "a" in a book.
2. Select an instance.
3. press nvda+delete.

Expeted: there should be a way to get the page number for later reference, or to tell a sighted friend.
Adcual: Just a numbered location is available.

**Comment by jcsteh** [comment]
Print page numbers are only available on certain books (out of our control). Where they are supported, this command already reports them. Note, however, that the location number is consistent across restarts, platforms and accounts, so that number can be used for later reference or shared between friends also reading that Kindle book. (Sighted users can also see and use this number.)
