### ISSUE TITLE
Freeze and quite often crash with e10s enabled on nightly.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6805]
I have seen several crashes with NVDA and e10s enabled nightly.
All of the freezes exhibit this when I switch tabs.
Speaking [u'#nvda - Instantbird  row 1  column 3']
IO - inputCore.InputManager.executeGesture (10:51:17):
Input: kb(laptop):alt+tab
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:51:17):
IAccessibleObject.attributes COMError (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
IO - speech.speak (10:51:17):
Speaking [u'Are we e10s yet? - Nightly  row 1  column 4']

I saw a very strange crash after a 2 minute freeze. like this.
https://crash-stats.mozilla.com/report/index/669ee559-5397-4fd6-8a39-f32742170125
The top of the stack is really really really really weird on this one, and seems to come from NVDA.
Also, the huge massive freeze can be produced reliably with https://arewee10syet.com/
It's a huge site, and even froze chrome a little, but that's where the crash occurred on. I've seen it with gmail as well.

**Comment by derekriemer** [comment]
After about 5 minutes of waiting, that page loaded on firefox

**Comment by bhavyashah** [comment]
@derekriemer Do the reported freezes and crashes still occur with recent stable/nightly versions of Firefox? Visiting https://arewee10syet.com/ did not cause any freeze as such from a usage standpoint, but certainly quite a lot of interesting log content. The odd thing is that NVDA does not freeze as such at all, so a user might not even observe the effects you describe and those that the log contents may imply normally.

**Comment by derekriemer** [comment]
@bhavyashah this was with e10s on, which you probably don't have enabled. This has been fixed a lot by mozilla, this was primarily a holding ground for tickets which had parets of the stack in NVDA's address space, so I'm closing it.

**Comment by zahra21** [comment]
hello.
thanks so much for your great job.
derekriemer could you please tell is it related to
https://www.github.com/nvaccess/nvda/issues/6885 or not?
if i use previous versions of nvda which recieved messages execInWindow instead of execInThread?
if i use previous versions of nvda and e10s becomes enabled for me in firefox, do i recieve quite crash and freeze most of times or not?
whats the different beteween recieving messages from window or Thread?
the fixes for e10s crashes related to recieving messages from window and became solved by new change in nvda 2017.2 which recieves messages from Thread?
or its related to mozilla and no matter which version of nvda that we use, we can use multiprocess without consideration and worried from where, nvda recieves messages, window or Thread?
i appreciate you if you explane me about it and clarify for me about it.
God bless you, and his infinite mercy i pray for you.

**Comment by derekriemer** [comment]
using the latest version will work. We don't recommend using previous versions of NVDA, and both sides made fixes.

**Comment by zahra21** [comment]
hi.
thanks so much for your reply.
could you please test for me with previous versions?
because for some reasons, i cant update my nvda anymore.
i cant explane my reasons here, but realy wish that know specially about nvda 2017.1 and 2017.2
i forgot to ask, with which version of nvda did you test?
i appreciate your help, please test for me with previous versions.
God bless you and i wish his infinite mercy and prosperity for you.
