### ISSUE TITLE
allow unlabeled buttons to be labeled

### ISSUE THREAD

**Issue by Dennisl123** [nvaccess/nvda#6808]
Hi, Please allow unlabeled buttons on websites and flash players to be labeled.  Thank you.

**Comment by leonardder** [comment]
Closing as duplicate of #5874, which has associated pull requests.

**Comment by Dennisl123** [comment]
Why was this ticket closed?

**Comment by ehollig** [comment]
@Dennisl123, this issue was marked as a duplicate, as #5874, already has code contributed to this issue.

**Comment by Dennisl123** [comment]
Will this be in a release soon?

**Comment by ruifontes** [comment]
Hello!

For me, it seems abandoned code... last comment about code is one year 
old...

And the broad of this ticket is only for HTML objects, and not GUI 
objects...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 20 de agosto de 2017 17:14
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] allow unlabeled buttons to be labeled (#6808)



@Dennisl123, this issue was marked as a duplicate, as #5874, already has 
code contributed to this issue.
