### ISSUE TITLE
Move system configuration to %programdata%

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6824]
Although I understand that changing the directory for the system configuration wouldn't get a high priority and will probably be rejected, I still would like to propose moving the system configuration folder to the program data directory (all users under XP). See [this](https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/) blog post from Microsoft about this subject. I think it is also a matter of style and good habits to not save system wide configuration to the program files directory.

See also #6822...

**Comment by jcsteh** [comment]
ProgramData is intended for configuration used by all users. The system config is actually a special case that most applications don't have: it is used when NVDA is run as the system user (secure desktops). That is different to all users:

1. User configurations should not "merge" with the system configuration, even if they use the system configuration as initial defaults. That is, changes to the system configuration should not affect existing user configurations. An all users config implies that it is actually used in some way for all users.
2. There are good reasons to separate the system config and the all users config. For example, there may be add-ons installed in the all users config that should not run on secure desktops for security reasons.

**Comment by Brian1Gaff** [comment]
In XP though any admin can see anything in any case, so in that particular 
case its a bit academic is it not?
 Also where do you draw the line here. Remember you then have to work out 
what happens when you  use the create a portable version, as wherever you 
had the config, it will then end up in the self contained folder or drive 
spcified if you make what is basically a clone of your current installed 
version.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
