### ISSUE TITLE
NVDA not presenting aria-labelledby target in IE unless in forms mode

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#6831]
In Chrome NVDA presents the target of aria-labelledby when arrowing, tabbing or pressing x.  In Firefox it does so when tabbing or pressing x.  In IE it only does so in forms mode.  The attached file has an aria-labelledby example and a comparison table for four screen readers (rename from .txt to .htm to view).  While I am yet to find a good example of appropriate use of aria-labelledby (including the attached example), consistent presentation is merritted.

Andrew

[aria-labelledby-issue.txt](https://github.com/nvaccess/nvda/files/746372/aria-labelledby-issue.txt)

**Comment by Adriani90** [comment]
Confirming I can reproduce this issue in NVDA 2019.1 and IE11.
Additionally,
In Firefox, when using tab in browse mode, the arialabeledby is also not reported.
In Chrome, when pressing x, the arialabeledby is reported twice.

**Comment by Adriani90** [comment]
IE support has completely ended in 2022 and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I am closing this as abandoned, since I don't expect further accessibility updates to IE or to IE mode in Edge. In Edge, Chrome and Firefox 111 everything seems to work just fine, only when navigating with arrow keys in browse mode NVDA does not speak the aria-labelledby on the checkbox, instead it speaks a heading above the checkbox with the aria-labelledby text.
If you are still having this issue in other browsers, please open a new issue with updated steps to reproduce.
