### ISSUE TITLE
Include link to Codefactory vocalizer voices in user's guide

### ISSUE THREAD

**Issue by ondrosik** [nvaccess/nvda#6873]
In the user's guide, we are now offering vocalizer for nvda from Tyflotecnia. Now, users can also buy it from Codefactory. Codefactory declares that it also supports NVDA from every sale.

**Comment by jcsteh** [comment]
We originally included the Tiflotecnia product in the User Guide because it
was the first NVDA specific commercial synthesiser. However, there are now
several such products. We feel listing them all in the User Guide is
excessive. Instead, we will remove the Vocalizer section, thus driving
users to the Extra Voices page (which is also linked from our Download
page).

**Comment by bhavyashah** [comment]
Since this sounds fairly trivial to tackle, could we come back to this for a bit? @jcsteh @josephsl 
By the way, instead of removing the section of Nuance Vocalizer altogether, I believe we would be able to do more justice to all TTS engines by simply mentioning all in one list. Details regarding each can be obtained from the Get Extra Voices page to which we have already linked, but a comprehensive list of all available synthesizers might make more sense than (categorically?) specifying some and detailing them in dedicated sections and completely nonrecognizing the rest. Just a thought. :)
Also, a tiny little catch in the NVDA User Guide:
"For an even more extensive list of free and commercial synthesizers that you can purchase and download for use with NVDA, please see the page at http://www.nvda-project.org/wiki/ExtraVoices. "
This URL took me to a page with https and not http. Rather than changing http to https in the text, we could simply rephrase from 'please see the page at ...' to 'please see this page' with 'this page' linking to this URL.

**Comment by leonardder** [comment]
Tiflotecnia Vocalizer has been removed from the user guide. I'm closing this as won't fix.
