### ISSUE TITLE
Focus lost after leaving menus in Windows live mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#688]
**Reported by Agent Golder on 2010-06-02 09:23**
You only have to open a menu, and click an item like Request reading resceept..
Result: Focous doesn't return to where it was priviously and have to alt+tab twice to continue working.

**Comment by leonardder** [comment]
Windows Live mail is obsolete now. A won't fix?

**Comment by ruifontes** [comment]
A won't fix because it is not a problem now...

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 22 de junho de 2017 18:34
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Focus lost after leaving menus in Windows live 
mail (#688)



Windows Live mail is obsolete now. A won't fix?
