### ISSUE TITLE
Upgrade to Liblouis 3.2.0

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6935]
Hi,

Liblouis 3.1.0 has been released. This release includes tons of changes to back-translation submitted by @JCSTeh (a great help for #2439), braille table improvements, and couple new tables such as Chinese (simplified) table and enhanced Greek and Turkish tables.

Thanks.

**Comment by josephsl** [comment]
CC @DKager, @LeonardDer

**Comment by jcsteh** [comment]
I started an i6935Liblouis3.1 branch which updates the build system with a change necessary to build liblouis 3.1.0. However, liblouis 3.1.0 fails to build as-is with NVDA. I've submitted liblouis/liblouis#300 to fix this. liblouis 3.1.0 is also missing liblouis/liblouis#211 which we need for contracted braille input.

So, I think we're going to need to ship a slightly modified liblouis until these things get incorporated into a liblouis release. Because some of this depends on contracted braille input, I'll probably just handle that in #6449 (unless we really need liblouis 3.1.0 before that ships).

**Comment by dkager** [comment]
Could you ship a slightly modified liblouis 3.1.0? For the time being I'd like to make an add-on that includes the `en-us-comp8-ext` table. That would be easier and less hacky if the file is available in louis\tables, which it is as per liblouis 3.1.0.

**Comment by jcsteh** [comment]
The problem is that this causes some pretty serious conflicts with #6449, which is currently on next. Thus, it's going to be very hard to ensure this gets tested properly. I'm going to try to move #6449 further along so we can hopefully ship it sooner rather than later. If my efforts fail, I'll look at how to solve this in the interim. Thanks for your patience.

**Comment by dkager** [comment]
@josephsl Would you mind updating the title to liblouis 3.2.0, which will be [released soon](https://github.com/liblouis/liblouis/wiki/Release-schedule)?

In this next release I made a few improvements to the Windows build system with NMake. @jcsteh I hope it plays nicely with NVDA's build magic now.
