### ISSUE TITLE
In Internet explorer pressing enter on an aria list Box does not cause NVDA to turn on focus Mode.

### ISSUE THREAD

**Issue by rnickelson** [nvaccess/nvda#6936]
In internet explorer navigate to 
https://labs.ssbbartgroup.com/index.php/ARIA_Listbox
Navigate to the Platform list Box using the ARROW keys
Press ENTER
Notice that Focus mode is not activated.

**Comment by bhavyashah** [comment]
@rnickelson The provided test case (rnickelson ) seems to no longer exist. Could you please create or share an alternate test case demonstrating the reported issue?

**Comment by rnickelson** [comment]
It is fixed now. The site was down.

**Comment by Adriani90** [comment]
Related to #6965. Actually I think that solving the related issue will solve this one as well.

**Comment by Adriani90** [comment]
IE support has ended completely in 2022 and the browser is being removed automatically from machines that still have it after an Edge update in February 2023. I am closing this issue as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. If you are having this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
