### ISSUE TITLE
Link with role=button inside table has aria-label read twice

### ISSUE THREAD

**Issue by sesopenko** [nvaccess/nvda#6940]
If an HTML link has role="button" and an aria-label and the link is inside a table then the label is read twice.  Example HTML found in this jsfiddle: https://jsfiddle.net/67pwmbds/

Steps to reproduce:
Tab to button

Expected Result:
Hear "This is a button, button"

Actual Result:
Hear "This is a button, button, This is a button"

Windows 10, IE11, NVDA 2016.4

**Comment by derekriemer** [comment]
Hi:
Firstly, was this example the intended example?

> If an HTML link has role="button" and an aria-label and the link is inside a table then the label 

I do not see a table in this HTML.

Also, this code doesn't specify the tabindex property. This is required to make it tabbable. Currently, this link that quacks like a button can't gain focus.

The fact that IE reads this twice when I press tab (When I tabindex 0 it) seems buggy. This doesn't happen on firefox.

**Comment by Adriani90** [comment]
Testing with NVDA 2019.1 as follows:
1. Coppied the code from jsfiddle to a blank html file because tabbing does not work under the provided link above
2. Opened it in IE
Result: the link is reported only once which is the desired behavior.

@sesopenko can you still reproduce this issue? if so, could you please rebuild the example on a different platform? It seems tabbing does not work on the example site.

**Comment by Adriani90** [comment]
No update from the initial autor since years and I cannot reproduce. i am closing as works for me and abandoned. Please comment on this if you have other updates on it and we can reopen. Thanks.
