### ISSUE TITLE
Stop automatic reading,  how to read just when I want.

### ISSUE THREAD

**Issue by dextherry** [nvaccess/nvda#6947]
Hi friends, I want to use this software, but I dont like that when I open it it read everithing without control where the mouse passes over ,I know that the key ctrl is to stop a reading, but  I would like this software to read just when I want, for example, a key could work as "play" so it wil read just when I want, there is a way or settings for that?
Thanks

**Comment by jcsteh** [comment]
Thanks for your interest. NVDA's primary function right now is to read the screen for those who are blind/vision impaired and are thus unable to read the screen. As such, it reads in response to most user actions, since a user would otherwise have no idea when there was something they wanted to read. This is configurable to some extent; e.g. you can disable tracking of the mouse or you can turn off speech temporarily by pressing NVDA+s. However, entirely on-demand reading is not currently something we are considering for NVDA. This might change in the future, but not in the short-term.

**Comment by gungfujoe** [comment]
I know this decision not to offer this functionality was made a long time ago, but I want to note that many vision-impaired users **are not blind**. I'm trying to help someone with vestibular migraines who can see, but for whom watching videos and reading text causes significant and long-lasting pain. She can see the screen, and she can read short lengths of static text, but she needs a screen reader for long messages, documents, etc. She is absolutely vision-impaired, but the constant barrage of audio every time she moves her mouse or touches her keyboard is _completely overwhelming_, so she finds NVDA unusable. Unfortunately other options (Windows Narrator, the "read aloud" function in various programs, browser plugins) all have significant limitations (or outright deficiencies) that prevent her from being able to read certain kinds of documents.

I appreciate the benefits NVDA offers to the blind community, and I recognize how vitally important they are. At the same time, I respectfully request that you give thought to whether you'd also be willing to support other vision-impaired people who need screen readers, but who are not blind, by adding some simple read-on-demand functions.

**Comment by josephsl** [comment]
Hi,

If this user is using NVDA 2024.1 and later, she can switch to speak on demand mode (one of the speech modes available when pressing NVDA+S to cycle through these).

Thanks.

**Comment by gungfujoe** [comment]
Thanks, that's a tremendous help! I'll keep digging through the help files to try to learn more about how to help her use NVDA most effectively
