### ISSUE TITLE
Windows 10 settings: NVDA does not provide easy access to the back button

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6950]
In the Windows 10 settings app, win+i, The back button appears adjacent to the system menu and to the minimize, maximize, and close buttons. But, navigation to this button via the NVDA object navigation leads to a lot of confusion. there are multiple "Settings window" objects that appear in the object navigation. For example, two "Settings Window; settings" objects appear adjacent to each other and more. This behavior does not occur in Narrator. I've asked Microsoft to assign a keyboard command to Back and Home buttons. But, ideally, both home and back buttons should appear in the tab order. Let me know if you want a log.
STR:
1. Open the Settings app (windows+i).
2. Go to one of the settings such as "updates and security."
3. Use object nav to move up the hierarchy to the "settings window" level and move to the next and previous objects.

Test environment: Windows 10 Pro build 15048 
NVDA version next-13899,af44c1d4

**Comment by jcsteh** [comment]
I can confirm this. Narrator navigation is difficult to compare with NVDA
object navigation because Narrator's navigation is completely flat, which
is not always a good thing; e.g. where there are multiple large containers.
Regardless, these window objects don't really serve any useful purpose and
just confuse the user. The question is how to filter them out without
breaking cases where these might be useful.

@MichaelDCurran, aside from top level windows, do you think having windows
in simple review (even if they are labelled) is actually useful? I guess we
chose to do this for a reason, but I can't really remember why. It's also
worth noting that these windows are not considered to be "content elements"
by UIA (though they are unfortunately considered "control elements").
Should we be using the UIA content element check for presentationType? I'm
concerned this might filter out more than we want, but in the modern world,
it seems like less objects is a lesser evil than more.

**Comment by jcsteh** [comment]
Btw, you can go back with the keyboard quickly by pressing backspace.

**Comment by PratikP1** [comment]
Ah. I hadn’t realized the backspace command was working there. I should have tried and known. Thank you.

**Comment by JulienCochuyt** [comment]
> Ah. I hadn’t realized the backspace command was working there. I should have tried and known. Thank you.

As there is a Windows keyboard shortcut for this functionality, maybe could we close this issue?
cc @feerrenrut
