### ISSUE TITLE
Bad reading number with digit using ReactJS, NVDA and FireFox

### ISSUE THREAD

**Issue by dszymczuk** [nvaccess/nvda#6963]
I write application with accessibility using ReactJS.
I have a problem with NVDA and FireFox - NVDA can't read number correctly.
I've found solution (use setTimeout with 0 delay), but I think, that can do it better.

I've created proof of concept to show the problem:
https://jsfiddle.net/IceManSpy/1bxu6aau/

To reproduce - sad path:
Run jsfiddle on FireFox
Run NVDA (you can open speech viewer)
Click sometimes on Random me! in Not works example
Check results - first value will be ok, but next not.
Sometimes will be (fe. 345.67):
345
67
but sometimes (it missing first digit):
45
67

To reproduce - happy path:
Run jsfiddle on FireFox
Run NVDA (you can open speech viewer)
Click sometimes on Random me! in Works example
Check results - every value will be ok.

How can I resolve this problem without setTimeout ?

**Comment by dszymczuk** [comment]
Also please checkout this link:
https://github.com/facebook/react/issues/9149

It is not ReactJS issue only.

**Comment by dszymczuk** [comment]
It is

**Comment by grzegorzjudas** [comment]
Can confirm it is indeed a problem, and lowers the quality of experience for users using NVDA.

**Comment by jcsteh** [comment]
The reason this occurs is that the entire text isn't removed and then deleted, but rather, it is changed. Thus, if you have the number "1.2" and replace it with "1.3", you'll only hear "3" because that's the only text that's new. Similarly, if you have the number "1.2" and replace it with "3.4", you'll get "3" and then "4" because that is the new text; the "." didn't change. Note that Firefox is calculating changed text, not NVDA; we handle the events Firefox sends us.

This behaviour is not incorrect: we shouldn't be reading content that hasn't changed (and Firefox shouldn't be sending us events covering content which hasn't changed). The controversial issue here is whether Firefox should treat changing nodeValue of a text node as an update or a remove/insert of the entire text. The latter is perhaps the "intuitive" behaviour in this case, but it may not be in all cases. Furthermore, I can see why that wouldn't be so easy internally; text nodes would need to be special cased.

Chrome "misbehaves" here as well, but differently: it causes the information to be spoken multiple times and it seems to strip common characters only at the start of the text. However, the fact that both browsers have issues here should serve to illustrate that this is not a trivial case to get right. Actually, Chrome misbehaves when setting textContent in some cases too.

A solution here is to set aria-atomic="true" to indicate that the entire node should be reported whenever it changes. Unfortunately, this will result in double speaking right now because multiple events are still fired.

P3 because while this could cause users to miss information, there is a solution (aria-atomic). However, the fixes will probably need to be in browsers.

Distilled test cases:

* textContent (working as expected in Firefox): `data:text/html,<div id="live" aria-live="polite">1</div><button onClick="document.getElementById('live').firstChild.nodeValue = '12';">Go</button>`
* nodeValue (not working as expected in Firefox): `data:text/html,<div id="live" aria-live="polite">1</div><button onClick="document.getElementById('live').textContent = '12';">Go</button>`
* nodeValue with aria-atomic (solves the problem, but currently results in double speaking): `data:text/html,<div id="live" aria-live="polite" aria-atomic="true">1</div><button onClick="document.getElementById('live').firstChild.nodeValue = '12';">Go</button>`

**Comment by Adriani90** [comment]
@dszymczuk, @dszymczuk is this still an issue in NVDA 2019.1 and Firefox 66.0.2? I cannot reproduce it anymore.

**Comment by Adriani90** [comment]
This works as expected in Firefox and NVDA as commented above. I am closing as works for me.
