### ISSUE TITLE
NVDA does not associate labels with select dropdowns appropriately.

### ISSUE THREAD

**Issue by claydiffrient** [nvaccess/nvda#6997]
I've created an example reproduction here: http://jsbin.com/bubupuk/1/edit?html,output

I tested this using:
Firefox 52.0.1
Windows 10 (10.0.14393)
NVDA 2017.1

The problem is that by navigating using the up/down arrows the label is never associated with the select dropdown.

Workaround: Using TAB to move between elements triggers NVDA to read the label in addition to the form control.

**Comment by feerrenrut** [comment]
I seem to be able to reproduce this issue with Firefox. In Chrome the label is reported and NVDA switches to focus mode automatically. For anyone reading this issue looking for further information on adding labels to form fields, a quick tutorial is available here: https://www.w3.org/WAI/tutorials/forms/labels/ which specifies that it is valid to use labels in this way for dropdown elements.

In terms of expected behaviour, when in browse mode and the down arrow is pressed the following output is expected:
```
Focus mode
Role  menu button  collapsed  subMenu
list
Student
```
Where `Role` is the label, `Student` is the currently selected value.

**Comment by jcsteh** [comment]
In browse mode, the label appears directly above the combo box (on the previous line), which is perfectly normal (and expected) if the label is a block element. If the control already has focus and NVDA is in focus mode, up/down arrows will only report the items, since you're already interacting with the control.

Switching to focus mode automatically when moving with the cursor keys in browse mode is definitely not the expected behaviour and is due to a Chrome bug which I'm discussing with Google at present.
