### ISSUE TITLE
NVDA PDF Actual Text bug

### ISSUE THREAD

**Issue by Wildted** [nvaccess/nvda#7034]
There is currently a serious bug in NVDA as follows. If you add some Actual Text to a PDF tag and then delete the actual text again, an empty Actual Text attribute will be created in the PDF. This will cause NVDA to stop working completely (remain completely silent) on a Windows 7 machine. On a Windows 8 or Windows 10 machine, Acrobat or Adobe Reader will crash 100% of the time if you try to open such a file with NVDA running. This bug dos not affect JAWS, ZoomText, SuperNova, MAGic, Read&Write Gold or Claro Read.

The attached file that includes the word "Edit" is so affected (will crash). I also attach a version ("Original") which works fine.

For info I have experienced this bug in perhaps 50 different PDFs before I worked out what was going on (not just the attached files).  

Thanks 

[Coram Life Education Bro 2015 - Edit.pdf](https://github.com/nvaccess/nvda/files/883748/Coram.Life.Education.Bro.2015.-.Edit.pdf)
[Coram Life Education Bro 2015 - Original.pdf](https://github.com/nvaccess/nvda/files/883749/Coram.Life.Education.Bro.2015.-.Original.pdf)

**Comment by jcsteh** [comment]
The crash is the same as the first crash in #7021.

Technical: Getting the IPDDomNode for one of the nodes in this document
fails with E_FAIL for some reason and returns null. The crash is
because NVDA doesn't check for this and tries to dereference it. It
probably shouldn't be failing anyway, but that doesn't excuse the lack of a
check.

In this case, adding that check does fix the crash.
