### ISSUE TITLE
Problem using NVDA read Kindle book by braille

### ISSUE THREAD

**Issue by tck618** [nvaccess/nvda#7064]
I have updated the Kindle for PC 1.20 and using NVDA 2017.a. I read the Kindle menu clearly and use text-to-speech listen the books. How can I do? is my NVDA or kindle app settings problem?

**Comment by feerrenrut** [comment]
@tck618 I'm sorry, but I do not understand the problem. Could you please list the steps that you take, and an example of the output and how it is different from what is expected. Thanks.

**Comment by nvdaes** [comment]
Replying to @tck618
> I have updated the Kindle for PC 1.20 and using NVDA 2017.a. I read the Kindle menu clearly and use text-to-speech listen the books. How can I do? is my NVDA or kindle app settings problem?

I think you're discussing the same question posted by me on the development mailing list. I provided info requested by @jcsteh.
You can see if it's the same question at
http://nabble.nvda-project.org/Kindle-Supposed-supported-books-don-t-work-with-NVDA-td41814.html

Thanks.

**Comment by tck618** [comment]
When I use Kindle for PC, I can see the menu and choose my books. but I open the book, 
cannot read the book by braille. 

I can press ctr+r to listen the book. But I want to read the book by braille.I cannot use arrow key to browse the book content.
Thanks for your help. 

    Reef Turner <notifications@github.com> 於 2017年04月11日 (週二) 1:57 PM 寫道﹕
 

 @tck618 I'm sorry, but I do not understand the problem. Could you please list the steps that you take, and an example of the output and how it is different from what is expected. Thanks.—

**Comment by jcsteh** [comment]
What language are you using with Kindle?
Are the books you're trying to read designated with "Screen Reader:
Supported"?
Can you please provide the addresses to the pages on the Amazon website for
each book you're having trouble with?
Thanks.

**Comment by nvdaes** [comment]
Hi, just to say that I've tried with an English book designated with 
"Screen Reader: Supported", but browse mode doesn't work using NVDA 
2017.1 and Kindle 1.20.1 (47037), with Kindle and Windows interface set 
to English and Spanish.
In case this issue is valid, here's further info:

Book: [Lying about Hitler](https://www.amazon.es/dp/B06XCG65HY/ref=sr_1_1)

Developer info for navigator object:
name: u'Book page view'
role: ROLE_DOCUMENT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <appModules.kindle.PageTurnFocusIgnorer object at 0x04F79BF0>
Python class mro: (<class 'appModules.kindle.PageTurnFocusIgnorer'>, 
<class 'NVDAObjects.IAccessible.IAccessible'>, <class 
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 
'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, 
<type 'object'>)
description: None
location: (56, 102, 1318, 654)
value: None
appModule: <'kindle' (appName u'kindle', process ID 2660) at address 
4f79590>
appModule.productName: u'Kindle'
appModule.productVersion: u'1.20.1.47037'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 460840L
windowClassName: u'Qt5QWindowIcon'
windowControlID: 0
windowStyle: -1764818944
windowThreadID: 8332
windowText: u'El 2\xc2\xba Kindle para PC de Noelia - Lying About Hitler'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x6f16e74 at 511aad0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=460840, objectID=-4, 
childID=-2147483334
IAccessible accName: u'Book page view'
IAccessible accRole: ROLE_SYSTEM_DOCUMENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, 
STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None
IAccessible2 windowHandle: 460840
IAccessible2 uniqueID: -2147483334
IAccessible2 role: ROLE_SYSTEM_DOCUMENT
IAccessible2 states:  (0)
IAccessible2 attributes: None

**Comment by jcsteh** [comment]
@tck618 didn't provide answers to https://github.com/nvaccess/nvda/issues/7064#issuecomment-294057228, so I'm not certain whether the books tried are designated as Screen Reader: Supported. Assuming they are, this is probably the same issue @nvdaes is encountering.

I worked with Amazon to track this down. Apparently, there is an issue which causes books based on the new Kindle format to be displayed incorrectly with display adapters based on the Intel Express chipset. As a result, the new Kindle book format (which is needed for accessibility) has been disabled for users with this display adapter.

While this causes incorrect visual display, it does not affect accessibility. So, if sighted users don't need to access Kindle on your computer, you can downgrade to an earlier version of Kindle to temporarily work around this issue until it is properly resolved in a future version of Kindle.

To do this, please do the following:

1. Open Kindle.
2. In the Tools menu, choose Options.
3. On the General page, uncheck "Automatically install updates when they are available without asking me", then press OK. This is to prevent Kindle from upgrading again after you downgrade.
4. Close Kindle.
5. Download Kindle 1.19.1 from this link: https://s3.amazonaws.com/kindleforpc/46084/KindleForPC-installer-1.19.46084.exe
6. Install the application you just downloaded.
7. Open the Kindle app.
8. You will now need to remove affected books from Kindle for PC and download them again in order to receive the correct versions for accessibility.

I'm closing this, since there's nothing further we can do on our end. Amazon are aware of the issue and are working to resolve it for a future release. The above workaround will allow affected users to access Kindle books in the meantime.
