### ISSUE TITLE
protected pdf documents

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7094]
when openning a pdf document which is protected, NVDA is not able to read the text. JAWS screen reader can read it properly. How to solve this problem in NVDA?

Best regards
Adriani

**Comment by jcsteh** [comment]
In order to access protected PDF documents, Adobe requires screen readers to use a special key. Because NVDA is open source software, including such a key is problematic. Even if we only included it in special builds, add-ons would be able to use protected PDF content in whatever way and thus violate the conditions of the agreement. I guess the only way we could achieve this would be to somehow restrict usage of this key such that it only works when no add-ons are installed, but this is problematic because many users depend on add-ons for daily functionality.

This is obviously functionality we'd like to have, but at present, there doesn't appear to be a way to do this without introducing security issues. I'm closing this as can't fix for now, but we're very happy to discuss potential technical solutions if they arise in future.
