### ISSUE TITLE
Unexpected behavior with browse mode and line breaks

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7162]
It seems that, in contrast to normal text editors, pressing end in browse mode places the cursor on the last character of the line, rather than after the particular character. I see a reason why this is the case in virtual buffers. However, this behaviour also applies to Microsoft Word.

Str:

1. Create a single line word document with "hello" on one line
2. Enable browse mode
3. Press end

Expected result: NVDA says line feed
Actual result: NVDA says O

**Comment by PratikP1** [comment]
I’m unable to verify this in Word 2016 16.0.7726.1030 and NVDA version next-14037,0e4a5ba6. NVDA lands on linefeed when pressing the end key. Similarly, NVDA behaves the same in editors such as Notepad, Outlook, and Wordpad.

**Comment by leonardder** [comment]
@PratikP1: Are you sure you had browse mode enabled while testing this? In Notepad and Wordpad, there is no browse mode.

**Comment by jcsteh** [comment]
Confirmed. It seems that the Word object model does not treat this line ending character as part of the line (unless you are actually positioned on it).

Can you provide a use case for why this is important to you? Obviously, it's inconsistent with Word itself, but browse mode in general is somewhat inconsistent with Word; e.g. moving by line behaves differently and this is very much intentional.

**Comment by dkager** [comment]
One case is doing End then Shift+Home, which omits the last character. But that's common to all browse mode scenarios.

**Comment by leonardder** [comment]
I reported this because of the inconsistency, but I do not have a problem with it now that selecting to end of lines has been fixed. So, I think this can be closed as a won't fix if you agree.
