### ISSUE TITLE
serious problem in latest espeak

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#7167]
hello.

georgian language support is broken in latest espeak update.
leters arespelled there.

**Comment by k-kolev1985** [comment]
Not only georgian. It affects at least a few other languages like bulgarian, russian and greek. In those cases/languages, text written in the native alphabet (e.g. cyrillic) is read fine, but text in latin is not - each word is spelled and in some cases - even repeated.

Test environment:
- Operating system: Windows 10 Pro (build 15063.296), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-14041,c3bd5fa7, in bulgarian.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 8.00GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 3071MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.

**Comment by feerrenrut** [comment]
Thanks for reporting this.

The latest espeak master was incubated yesterday (and included in next-14041). 
For the change that incubated this, please see PR: #7115
A bug has been raised with espeak: espeak-ng/espeak-ng#262

For anyone who is having major problems please revert to the latest master or release 2017.1
If espeak-ng/espeak-ng#262 is not fixed within the week, we will revert the change we made in #7115

**Comment by dingpengyu** [comment]
Recently espeak speech synthesizer also appeared in the Chinese under the bug: the main problem is that when I install a program, switch uac espeak garrison.

**Comment by beqabeqa473** [comment]
ok, please reference latest commit after submitting my issue to espeak-ng which should fix the issue.

**Comment by beqabeqa473** [comment]
hi.

please update espeak to the latest commit which should fix spelling issue.

**Comment by feerrenrut** [comment]
The latest espeak commit has now been merged into next. Please advise if this resolves the issue for you. Thanks.

**Comment by k-kolev1985** [comment]
Yes, with the latest "next" snapshot of NVDA, the problem seams to be resolved. Thanks much!

**Comment by feerrenrut** [comment]
Great! I'll close this issue then. Please comment or re-open if necessary.

**Comment by Mary5958** [comment]
Now going through all languages I see there are still a few issues:

1. Still some of the more recent ones tend to spell the Latin letters:
bpy (Bishnupriya Manipuri)
JP (Japanese)
kok (Konkani)
ky (Kyrgyz)
my (Burmese)

2. In Norwegian that renamed from no Norwegian to nb Norwegian Bokmål since ESpeak-ng's recent updates the letter å in Bokmål isn't recognized so well by NVDA which produces this error when starting in this language:

WARNING - synthDriverHandler.SynthDriver.loadSettings (16:03:42.151):
Invalid voice: nb
ERROR - synthDriverHandler.setSynth (16:03:42.158):
setSynth
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 88, in setSynth
  File "synthDriverHandler.pyc", line 497, in loadSettings
  File "synthDriverHandler.pyc", line 35, in changeVoice
  File "speechDictHandler.pyc", line 141, in loadVoiceDict
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

Also independently on that in Norwegian numbers with more digits are spoken by digits rather than full numbers even if NVDA is set to speak full numbers.
I realised it only now but both issues in the Norwegian language seems to be happening since next-14020,2969bc5d

**Comment by jcsteh** [comment]
Regarding the UnicodeDecodeError, it seems eSpeak voice names can now be UTF-8, not just ASCII. Fixing this should just be a matter of decoding from UTF-8 for the `name` of voices in `_getAvailableVoices` at around line 198 of `source/synthDrivers/espeak.py`:

```
name=v.name.decode("UTF-8")
voices[identifier]=VoiceInfo(identifier,name,l)
```

@Mary5958, would you mind [filing an issue against espeak-ng](https://github.com/espeak-ng/espeak-ng/issues/new) regarding the letter and digit spelling issues you identified? Those need to be fixed in espeak-ng.

**Comment by jcsteh** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [May 18, 2017, 12:43 PM GMT+10](https://github.com/nvaccess/nvda/issues/7167#issuecomment-302285222 "2017-05-18T02:43:45Z - Replied by Github Reply Comments"):
> Regarding the UnicodeDecodeError, it seems eSpeak voice names can now be UTF-8, not just ASCII.

@feerrenrut, this will need to be done as part of #7115.

**Comment by feerrenrut** [comment]
Thanks for your testing @Mary5958. I have fixed the issue causing an error with Norwegian Bokmål (For any Norwegians reading this: Vær så god) 

I have also updated to the latest espeak-ng commit. If anyone is willing to test this again that would be excellent.

**Comment by vgjh2005** [comment]
Hi:
Simplified Chinese is also the same. Thanks!

**Comment by feerrenrut** [comment]
Hi @vgjh2005 could you please let us know what version of nvda you are using? Since espeak was just updated, it would be good to know which version you have.

**Comment by vgjh2005** [comment]
Hi:
My NVDA version is next-14059,39bd650d. Random number will be added between all Chinese characters. Thanks!

**Comment by feerrenrut** [comment]
Numbers spoken between Chinese characters issue: https://github.com/espeak-ng/espeak-ng/issues/257

**Comment by feerrenrut** [comment]
espeak has been rolled back to the latest release see pull request #7280.

Once we are happy with this version of espeak, the intention is to regularly update nvda-next to the latest from espeak. This will mean that espeak on NVDA-next will be a little unstable. The goal of doing this is to be able to test espeak and report issues on the espeak repository earlier. Hopefully this results in a more stable espeak in the release of NVDA.

Closing this issue since it's no longer relevant. Please open a new issue if you find problems in the incubated version of espeak (in nvda-next). At the moment this is likely the version of espeak we will use in NVDA 2017.3
