### ISSUE TITLE
[request] Some fix about Korean braille table regarding first consonant characters

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#7193]
Hello, I'm Hyongsop Kim in Korea and NVDA user with braille erminal function.
Because Korean braille table translation is very good, I use it very well.
By the way, there is one problem.
To explain about it, I should give you a English braille example.
In English braille, if I just type b, b is translated as dot 56 and 12, not 12.
If it is translated as just dot 12, it is very confusing, because braille users don't know whether this is b or but.
like this example, in case of Korean braille, if I type just one first consonant, it is translated with dot 123456 followed by the character, this is a Korean braille rule.
But in NVDA, this dot 123456 is not included.
So braille readers are confusing, whether this is just one consonant or braille abbreviation.
So please add dot 123456 if just one consonant or vowel is typed.

Thank you.

**Comment by josephsl** [comment]
Hi,

In order to do this, we need unicode codepoints for these.

Technical: when someone types Korean, the first conscenant should have its own character codepoint. For example:

1. Switch to Korean input/native input.
2. Type the letter "r" (without quotes and with Korea native input active). One should get the conscenant character.

Solution: after we obtain those unicode codepoints, it is a matter of adding them and dot representations in Liblouis braille table set (if the solution is simple as letting NVDA display these dot combos). I've been meaning to work on the new Korean braille table set (based on the latest standard published in 2017), and it won't be ready until this fall at the earliest (if I work on these tables in summer).

Thanks.

**Comment by jcsteh** [comment]
This should be filed as a liblouis issue, as that's where the change needs to be made. Once the change lands in a liblouis release, it can then be integrated into NVDA.

@josephsl, I don't know much about Korean, but I'm slightly confused here. @khsbory noted that a single consonant does get displayed, but without the dot 123456 indicator. If that's the case, doesn't that suggest that the consonant typed already got mapped correctly from its codepoint and the table is just missing indicator rules?

**Comment by josephsl** [comment]
Hi,

@JCSTeh: I need to double-check the table set in Liblouis. If all that's needed is indicator dot combination, then yes, this is quite a trivial fix that should be discussed on Liblouis side of GitHub.

Thanks.

**Comment by josephsl** [comment]
Hi,

Update: trivial to fix, should be a matter of a pull request and several test cases. Thanks.

**Comment by jcsteh** [comment]
Okay. I'm going to close this, since it'll be dealt with in liblouis and I see no need to track it here, but please do provide any relevant liblouis issue/PR numbers here for reference. Thanks.
