### ISSUE TITLE
Unknown with SR but a couple of times only

### ISSUE THREAD

**Issue by 3spectro** [nvaccess/nvda#7199]
I have a similar problem, but the difference is only reads unknow one or twi times, out of that, the sr reads right!

i.e:

SHIPS
collapsed  link  Ships
Cruises | Carnival Cruise Deals: Caribbean, The Bahamas, Alaska, and Mexico - Mozilla Firefox
unknown
Cruises | Carnival Cruise Deals: Caribbean, The Bahamas, Alaska, and Mexico - Mozilla Firefox
list
button
Cruises | Carnival Cruise Deals: Caribbean, The Bahamas, Alaska, and Mexico - Mozilla Firefox
unknown
Cruises | Carnival Cruise Deals: Caribbean, The Bahamas, Alaska, and Mexico - Mozilla Firefox
Cruises | Carnival Cruise Deals: Caribbean, The Bahamas, Alaska, and Mexico  document
clickable
collapsed  link

**Comment by ehollig** [comment]
Could you provide more information? 
Please provide exact steps to reproduce, including the program you used, version of NVDA, what you experienced, and the expected behavior.

**Comment by ehollig** [comment]
Closing as invalid, as we do not enough information to replicate the issue.
@3spectro, if you could please provide exact steps to reproduce, including the program you used, version of NVDA, what you experienced, and the expected behavior, this would assist people like me to replicate the issue you are experiencing.
