### ISSUE TITLE
If there are two consecutive spans next to eachother, NVDA doesn't place a space between the elements in browse mode.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7229]
This example was taken from gmail, where this occurs in chrome on emails headings. I simplified it a bit however.

### Steps to reproduce:
1. paste this into ff or chrome's address bar.
    `data:text/html,<h3><span>Michael Curran</span><span>notifications@github.com</span>`
2. Notice how it writes 
    ```
    heading  level 3
    Michael Currannotifications@github.com
    ```
    to the buffer (That is what speaks).

### Expected behavior:

```
heading  level 3
Michael Curran notifications@github.com
```
(Place a space between the items).

### Actual behavior:
```
heading  level 3
Michael Currannotifications@github.com
```

**Comment by derekriemer** [comment]
This might be why we sometimes see weird hidden text get thrown together into one mashup

**Comment by jcsteh** [comment]
It's inappropriate to place a space between the spans in this example because there is no space visually. In fact, doing this would break real world use cases; e.g. underlining the first letter of a word for menus, etc. NVDA inserts a space if the browser reports one in the accessibility API, so it's up to the browser to work out whether it's appropriate or not based on whether there was a space in the DOM, styling, etc.

**Comment by leonardder** [comment]
This is related to #6529. It is true that Chrome sometimes has it 
horribly wrong.
