### ISSUE TITLE
Braille cursor routing doesn't work in terminals

### ISSUE THREAD

**Issue by ajirving** [nvaccess/nvda#7252]
### Steps to reproduce:

1. Open the windows command prompt by going to run and entering cmd
2.  Type a command 
3. Press a cursor routing key on one of the characters of the command you've input 

Cursor routing also doesn't work when using other terminal applications, for example PuTTY.  That's when I would find it most useful, for example when editing files on a remote Linux system.

Looking at the code it appears that the textInfo objects used for terminals don't have any functionality for moving the caret.  Would it be possible to add this?

### Expected behavior:
 
Assuming the character is within the editable part of the input command the cursor should be moved to it.

### Actual behavior:

No cursor movement.

### System configuration:

Only tested on Windows 8

**Comment by leonardder** [comment]
cc @dkager

**Comment by PratikP1** [comment]
I wonder if review should be used to track in terminal apps as opposed to tracking objects—i.e., review synchronized to system. This will be quite useful in Linux Subsystem for Windows.

**Comment by jcsteh** [comment]
As far as I know, there's no programmatic way to move the caret in
terminals. The only thing we could do is try to guess what arrow keys we'd
have to send to get to the requested position. However, this would have
very strange results in many cases. For example, if you tried this in a
shell, you'd end up walking back through your history. If you tried this in
an editor where there was line wrapping or characters which consumed
multiple positions (e.g. tab characters), you'd end up in the wrong place.
If it's likely to cause very unexpected results, it's not a good thing to
implement due to user confusion.

@leonnarder, @dkager, thoughts? At this stage, I'm inclined to "won't fix"
this.

**Comment by dkager** [comment]
One thing that would be very useful is if you could perform mouse clicks at specific characters in a terminal window through cursor routing keys. This would make working with terminal-based GUIs in a program like PuTTY a lot easier. But that's a different use case and a different issue.
The question here is about routing the cursor. I'm not even sure if clicking with the mouse will move the cursor in the average terminal, so I would go along with won't fix.

**Comment by leonardder** [comment]
> One thing that would be very useful is if you could perform mouse clicks at specific characters in a terminal window through cursor routing keys. This would make working with terminal-based GUIs in a program like PuTTY a lot easier. But that's a different use case and a different issue.

I don't think that's a different issue, since I assume that if one would click on a character in a Terminal, at least on the input line, one would assume that clicking moves the cursor.

The question here is about routing the cursor. I'm not even sure if clicking with the mouse will move the cursor in the average terminal, so I would go along with won't fix.

> I tried routing and clicking the mouse with screen review in PuTTY, but it didn't have any effect. I agree about the won't fix

**Comment by ajirving** [comment]
I hadn't realized it was generally so difficult to move the cursor in terminals, I assumed that the mouse would do it but testing suggests it doesn't.  In that case I agree this ticket should probably be closed.

In certain instances mouse clicks work in PuTTY, for example emacs with xterm-mouse-mode enabled.  In such situations it would be useful to have a single script to move the mouse to the review cursor and then left click.  Presumably that would be very easy to add either directly or via a plugin.

**Comment by jcsteh** [comment]
Closing as won't fix due to the inability to reliably move the cursor programmatically in terminals.
