### ISSUE TITLE
Browse mode in Mozilla Gecko products no longer can be used after restarting NVDA due to IAccessible2 interface registration issues

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#7269]
### Steps to reproduce:
This can only be reproduced on a small amount of machines running Windows 10 Creaters Update.
While NVDA is running:
* Start Firefox and navigate a page with NVDA browse mode
* Restart NVDA
* Move back to Firefox and try and navigate the page.

Browse mode  will not be available due to NVDA not being able to queryService to IAccessibleApplication to fetch the Gecko version.

**Comment by jcsteh** [comment]
CC @@DerekRiemer, @JosephSL, who I believe are experiencing this.

**Comment by beqabeqa473** [comment]
also have the same problem.

**Comment by jcsteh** [comment]
#7207 is possibly related, though we don't have enough technical info there to be sure.

**Comment by jcsteh** [comment]
Note that #5758 has similar symptoms, but is very different technically and can be worked around. It'd be good if those of you who believe you are experiencing this can do the following:

1. Switch to another application that isn't a Mozilla application. You may need to start another application if you don't have another open.
2. Restart NVDA.
3. Now switch back to the Mozilla application.

If you're experiencing #5758, everything will work as expected. If you're experiencing this new issue (#7269), nothing will fix things except restarting the Mozilla app.

**Comment by jcsteh** [comment]
@MichaelDCurran, as discussed, we should log CoRegisterPSClsid failures as errors to help diagnose issues like this.

**Comment by gregjozk** [comment]
Hi,

confirmed on windows 10 (64-bit) build 15063.413 last firefox (54.0.1 - 32-bit) and NVDA (last next snapshot).

This problem has been detected for a while.

**Comment by mohdshara** [comment]
confirmed with NVDA 2017.3 and firefox 55..0.3. I have been experiencing this for a while, and our Arabic speaking users confirm this as well.

**Comment by zahra21** [comment]
@michaelDCurran,
you mentioned that:
"This can only be reproduced on a small amount of machines running Windows 10 Creaters Update."
i tested with nvda 2017.2 and 2017.3 and wished to share the result with you!
unfortunately its not a problem for small amount of systems.
i did not have this issue with any version of nvdausing firefox single process mode.
i even wanted to use multiprocess in firefox versions before version 57, but multiprocess did not work for me before firefox quantum.
even when activating
browser.tabs.remote.autostart
in firefox about:config,
firefox worked for me in single process mode.
so, i cant say exactly its the problem in nvda 2017.3 and previous versions with firefox quantum,
or with these versions of nvda when multiprocess is activated.
my test result with firefox 81 and 82 and nvda 2017.2 and 2017.3
after five minutes or ten minutes or a little more,
brows mode stop working for me.
all arrow keys and navigation quick keys and using SayAll, all dont work anymore even in gmail or other simple web pages.
only tab works in this condition.
when i press nvda+plus q and restart nvda,
or, i use nvda control n to run nvda again,
even tab stop working!
and i only hear unknown unknown unknown.
it does not matter whether firefox is in focus for me or another application like notepad or even desktop is in focus.
so, my issue is 7269 and ias i mentioned in the first sentences of my comment, its not specific for windows ten creator update.
it should be related to multiprocess feature, because i dont have this problem in firefox 52 and 52esr and previous versions of firefox or firefox 53 until 56 which are not firefox quantum.

**Comment by jcsteh** [comment]
@zahra21, the issue you're reporting here sounds more like #7778. Where this issue here only occurred after restarting NVDA (and is now fixed), your explanation notes that you see this issue even without a restart.

**Comment by jcsteh** [comment]
@@zahra21, I just realised you said you're testing with NVDA 2017.2 and 2017.3. Those versions are no longer supported and the issue you're experiencing may well be resolved, especially since #11494 was fixed in NVDA 2020.3.

**Comment by zahra21** [comment]
i did not test issue 5758 with newer versions of nvda.
but, 7269 is not reproduceable for me in nvda 2017.4 when i tested.
but, unfortunately, for some reasons, i really cant use beyond 2017.3 and since nvda is opensource program, i believe that backporting such essential fixes to 2017.3 is possible and just needs a few minutes!
yes, nvda 2017.2 and 2017.3 unfortunately dont work with firefox quantum (81 and 82 i tested)
and i tested these nvda versions with firefox 61.0.1 two years ago.
and i experienced crashing firefox after for example 30 minutes using simple web pages like gmail in basic html view
and, reading nvda documentations.

**Comment by zahra21** [comment]
michaelDCurran,
you mentioned that:
"This can only be reproduced on a small amount of machines running Windows 10 Creaters Update."
i tested and my result is very different for this bug!

**Comment by zahra21** [comment]
i tested some versions of firefox on windows seven for example: firefox 52 until 56 and also 67 which is the last version that multiprocess can be enabled or disabled easily on that version.
                    first, its not specific for windows ten only, as i said, i reproduced it on windows seven.
                    second, it does not affect firefox multiprocess disabled.
                    if you wish to test, for example: you can disable multiprocess in firefox 67 and previous versions by modifying one item in about:config
                    in the address bar, type about:config and press enter.
                    accept the risk.
                    in the search bar of about:config type autostart
                    the last item is browser.tabs.remote.autostart
                    press enter on it to make it false if its true by user or by default.
                    if its false, thats great, because nvda 2017.3 and previous versions work again after restarting it while using firefox!
                    in nvda 2017.4 and later, your solution worked and restarting nvda does not cause nvda says unknown and stops working in firefox at all!
                    in firefox 68 and later, disabling multiprocess still is possible, but it has risk and i think that developers can do it, because its technical and i did not understand exactly how can i disable this terrible feature that makes my system completely unusable with 2017.3 if i dont some task to reduce problems!
                    here you are the link for instruction to disable multiprocess in firefox 68 and later.
                    https://techdows.com/2019/08/multi-process-e10s-can-still-be-disabled-in-firefox-68-or-later-versions-here-is-how.html
