### ISSUE TITLE
Create a new NVDADialog class

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7283]
In the current situation, NVDA's several dialogs either subclass gui.settingsDialogs.SettingsDialog or wx.Dialog directly. SettingsDialog has a nice multi instance check in it, which blocks a user from opening multiple settings dialogs at once. However, the wx.dialog based dialogs don't benefit from this. This causes several things we probably do not want to happen, such as:

* Multiple open browse mode find dialogs
* People having multiple update downloaders running:
	+ When I'm downloading an NVDA update, I can rerun the check for updates option and it will allow me to have multiple NVDA downloaders open

We can solve this by adding a multi instance check to every wx.Dialog based dialog (e.g. as in the configuration profiles dialog. However, it might be a much cleaner approach to move the multi instance code from SettingsDialog to a new NVDADialog class and base every wx.Dialog based dialog on it. This new NVDADialog class can also have other types of functionality which is now copied several times, such as a main sizer which is also positioned properly on screen. I think such a new NVDADialog class can also be helpful for add-on writers.

Thoughts appreciated

cc @josephsl, @jcsteh, @derekriemer, @feerrenrut

**Comment by feerrenrut** [comment]
I think this is essentially a duplicate of #4620 (GUI: A base dialog for general-purpose dialogs with multiple settings)
This is also related to
* Focus existing NVDA Settings dialog if the same dialog is attempted to be opened again instead of presenting Error dialog. #5383
* Check for updates: an instance of this dialog is shown each time a user selects Check for Updates from NVDA help menu #4579
* Disallow multiple find dialogs at once #4228
* NVDA allows to open its dialogs when an wx file or dir dialog is opened #3361

I imagine all these issues could be resolved together with the right implementation. Personally I would steer clear of using inheritance as a method of sharing an implementation, and prefer a modifier method, a class, or some other form of composition. As @jcsteh points out in #4620 not all dialogs are created and opened in the same way, which is just one way that problems could arise when using a base class approach to share this implementation.

I think the first step is to abstract some logic for preventing multiple instances, I would look to see how this could be coupled with a call back to ask a dialog to regain focus (to solve some of the other related issues).

**Comment by leonardder** [comment]
I think @feerrenrut is right here, so closing this as a duplicate of #4620.
