### ISSUE TITLE
"No" is announced as "Number" in a dropdown using English(US) SAPI5 voices

### ISSUE THREAD

**Issue by poorgeek** [nvaccess/nvda#7291]
### Steps to reproduce:

1. Switch to using one of the English U.S. voices SAPI5 voices; either David or Zira
2. Create a simple `select` dropdown with _Yes_ and _No_ options ([example Codepen](https://codepen.io/poorgeek/full/VWKxeZ/))
3. Navigate to the dropdown and 

### Expected behavior:

The "No" option is announced as "No 2 of 2"

### Actual behavior:

The "No" option is announced as "Number 2 of 2"

### System configuration:

* Windows 10 Version 1607 Build 14393.1358
* Firefox 54.0
* NVDA version: 2017.2 (Installed)

Other information:

Running in a Windows 10 VM via VMWare Fusion.

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No, but I did try the same thing in NVDA with eSpeak and English U.K., both of which perform the expected behavior.

**Comment by jcsteh** [comment]
Unfortunately, there's nothing we can do about this. The synthesiser is choosing to expand this as an abbreviation and we have no control over this. We even separate meta information from content using a double space instead of a single space (e.g. "no  1 of 2" to make it clear that this is separate, but the synthesiser is choosing to expand the abbreviation anyway.

**Comment by Brian1Gaff** [comment]
Unfortunately these abbreviations idiosyncrasies occur in lots of places 
even on UK English machines with sapi 5. NY is new york and lots of others 
as well.
 I'm surprised Microsoft do not simply put in a toggle for expanding 
abbreviations or not.
 Brian
