### ISSUE TITLE
Improvements for the braille tethering  setting

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7315]
Apologies for dropping the issue template. This is intended as a discussion place, in particular for @leonardder, @bramd and @jcsteh.
Very brief summary of the issue: the braille tethering feature isn't always practical to use. There are many ideas to improve it, but they all have pros, cons, and interdependencies with other features.

Here are my thoughts. They are grouped by feature and in a rough order from most promising to least promising in my opinion. If agreement is reached on any of the features discussed in this issue we should open a separate issue for that. But for now I thought it would be a good idea to have a central place to talk. Hopefully this isn't too much of a duplicate.

#### Smarter Tethering

After discussing with @leonardder we came up with the following behavior for the tethering setting:

1. Automatically tether to review if a review command is executed, such as object navigation. Obviously this should not display a quick message.
2. If braille was previously tethered to focus, restore that setting when the focus changes.

This allows for using object navigation without manually changing the tethering setting.

#### Cursor Routing Options

I think it makes sense for the default cursor routing action when tethered to review to be a mouse click/default action on the object under the braille cell.

I also suggest comands to:

1. Move the review cursor to the location under the braille cell (current behavior).
2. Mark the start position of the selection with the review cursor. This could automatically happen when (1) is executed.
3. Select up to the position under the braille cell.
4. Report formatting information, see #7106.

So if b1, b2 and b3 were braille display keys, we could have:

1. Mouse click: routing
2. Move review cursor: b1+routing
3. Set selection end: b2+routing
4. Report formatting: b3+routing

Because not all braille displays allow to combine keys with routing it may be handy to have a few special combinations with the NVDA key plus Control and/or Shift. For example, NVDA+ctrl+routing to report formatting.

#### Panning

Another potential improvement. When going a line up/down with the review cursor, try to preserve panning.

STR:

1. Open a command prompt
2. Tether braille to review
3. Type `ping google.com`
4. Go up by line until you reach "Reply from ..."

On a 40-cell display, seeing the response time requires you to pan right once. Then when you go up another line you land on another reply and have to pan right again. If panning was preserved you would save some time, especially if you have a lot of console output. I think blank lines should reset panning.

Note that in general, moving up/down by line also repositions the review cursor at the start of the line.

#### More Options Specific to Tethering

Based on feedback from @derekriemer we already discussed different cursor shapes for focus and review, see #7122. It could be useful to have a few more:

1. Show cursor on/off
2. Blink cursor on/off

The big problem is that this bloats the braille settings dialog even more. I was thinking about a config profile specifically for "tethered to review", but the problem is that only three settings can be configured here.

#### Better Spatial Display

An often mentioned issue is that braille could do better with spatial representation. Examples include tables in Excel and Word, the Windows Explorer details view and menubars. While improvements could definitely be made in this area, I don't think it is part of the tethering discussion.

#### Separate Braille Cursor

It has been suggested to add a third cursor to NVDA, which would be a dedicated braille cursor. My understanding is that this would remove the tethering mode or at least make it optional. I don't really like this idea because I don't see what it adds compared to making the tethering setting more intelligent. It also complicates NVDA for users with speech and braille enabled because the review cursor and braille cursor don't necessarily have to be synchronized.

**Comment by PratikP1** [comment]
@dkager wrote:
> It has been suggested to add a third cursor to NVDA, which would be a dedicated braille cursor. My understanding is that this would remove the tethering mode or at least make it optional. I don't really like this idea because I don't see what it adds compared to making the tethering setting more intelligent. It also complicates NVDA for users with speech and braille enabled because the review cursor and braille cursor don't necessarily have to be synchronized.

I very much like the intelligent way that this proposal would address braille review. I'd prefer not to have to deal with a braille cursor though. It would add additional complications to navigation. The way automatic switching is proposed, I see no additional reason for having such a cursor.

**Comment by ruifontes** [comment]
Hello!

The advantage of a Braille cursor is the possibility of exploring the screen 
without mouving any of the, lets call this way, voice cursors, but it will 
be necessary to implement commands, on the Braille display, to allow the 
mouvement of the cursor by line, word, character and so on...

But, in NVDA, for me, it makes more sense to have Braille following, 
intellegimently,  the active cursor, being either PC or review cursor.

By the way, when Braille is tethered to review cursor, performing, in the 
Braille display, a mouvement command it will be send to the review cursor?

Regards,

Rui



-----Mensagem Original----- 
De: PratikP1
Data: 22 de junho de 2017 21:41
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Improvements for the braille tethering setting 
(#7315)



@dkager wrote:



It has been suggested to add a third cursor to NVDA, which would be a 
dedicated braille cursor. My understanding is that this would remove the 
tethering mode or at least make it optional. I don't really like this idea 
because I don't see what it adds compared to making the tethering setting 
more intelligent. It also complicates NVDA for users with speech and braille 
enabled because the review cursor and braille cursor don't necessarily have 
to be synchronized.



I very much like the intelligent way that this proposal would address 
braille review. I'd prefer not to have to deal with a braille cursor though. 
It would add additional complications to navigation. The way automatic 
switching is proposed, I see no additional reason for having such a cursor.

**Comment by jcsteh** [comment]
Most of this is already covered by other issues. Also, I think this is far too broad even just as a discussion place; it's far too difficult to keep track of decisions. I'd suggest we take the discussion of respective issues into separate issues.

> 1. Automatically tether to review if a review command is executed, such as object navigation. Obviously this should not display a quick message.
> 2. If braille was previously tethered to focus, restore that setting when the focus changes.

Mostly makes sense. However, there are open questions, like whether we should auto tether to focus if the user moves the caret, how to handle situations where a braille action actually caused a focus/caret movement, etc. Also, I was originally concerned a user might not realise they had auto switched modes, but having different cursor shapes will fix that. These questions should be answered in #2385.

> I think it makes sense for the default cursor routing action when tethered to review to be a mouse click/default action on the object under the braille cell.

Technically, I think this should be move caret/do action/activate text range, rather than specifically mouse click, but I understand what you're suggesting. I guess that could also be covered by #2385.

Open question: if tethered to review and the review cursor isn't following the caret, routing will not actually move the cursor, since the review cursor will stay where it was. Is that confusing? If so, how do we mitigate it?

Your additional commands make sense. I'd suggest filing issues for them, referencing #2385.

> Another potential improvement. When going a line up/down with the review cursor, try to preserve panning.

Please file a new issue for this. I don't think it's related to tethering, though I understand the desire for it. That said, I don't know how feasible implementing this will be, since most text APIs (and thus TextInfo implementations) don't provide a way to go the next/previous line while maintaining the horizontal position.

> Based on feedback from @derekriemer we already discussed different cursor shapes for focus and review, see #7122. It could be useful to have a few more:

I think this might be easier to discuss once we have the new tethering behaviour, since we will have answered some other questions by then and users will get a feel for it in practice.

> An often mentioned issue is that braille could do better with spatial representation. Examples include tables in Excel and Word, the Windows Explorer details view and menubars. While improvements could definitely be made in this area, I don't think it is part of the tethering discussion.

Agreed. See #5559 and #6587.

> It has been suggested to add a third cursor to NVDA, which would be a dedicated braille cursor. My understanding is that this would remove the tethering mode or at least make it optional.

It seems multiple people (including you and me) don't like this idea. If it's going ot be debated nevertheless, I'd suggest #2385.
