### ISSUE TITLE
A summary of page elements could be announced when a page has finished loading

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#737]
**Reported by elliott94 on 2010-06-30 17:14**
When a web page has finished loading, an optional setting could allow NVDA to tell the user how many web elements (links, headings, etc) are on that particular page.
**Blocking #3221**

**Comment by jcsteh** [comment]
CC @leonardder, @ruifontes.

I realise other screen readers have this functionality, but I'd argue we shouldn't implement this as requested for several reasons:

1. Performance: This could be quite slow.
    - For virtual buffers, we still need to walk the entire virtual buffer tree to get this information. Alternatively, we could maintain counts for element types of interest as we build and update the buffer, but that introduces a fair bit of complexity.
    - We're moving away from virtual buffers. We don't use them for neither Edge nor Kindle and it's probable we will move away from them for Firefox and Chrome as well at some point. Once that happens, this will be even slower.
2. Usefulness: Why is it useful to know the exact number of links, headings, etc.? I can understand someone wanting to know that certain types of things are present, but why the number of them? If it's about knowing what types of things are present, why not just "Document has headings, links and landmarks"?
3. Accuracy: The idea of when a page finishes "loading" is becoming less and less relevant. We start reading the document when there's something useful to read. We haven't waited for the DOM "load" event for many years now because on the modern web, this might take a very long time to arrive (or may never arrive at all). Also, some pages load content dynamically. If we're giving the user exact counts, the user may trust those counts to be accurate. And if they can't, why are we counting at all? See point 2.
4. Equivalent experience: There is no equivalent experience for a sighted user. Sure, if there's something a sighted user can do and making that accessible just doesn't "fit" for a screen reader user, we might implement an alternative method to achieve it; e.g. quick navigation is an alternative to a sighted person "skimming" the page with their eyes. However, counting links, headings, etc. is just not something anyone would waste their time doing. Sure, they might identify the kinds of things on a page, but that has nothing to do with counting.
5. Verbosity: This increases the amount of stuff a user has to wait through before they can get on with reading the page. I guess making this optional mitigates this, but I'd want it disabled by default in that case, which raises the question of whether anyone would actually enable it.

As always, please provide real world use cases to justify the need for this. From there, we can figure out the best user experience.

**Comment by leonardder** [comment]
1 and 3 are interesting points i do agree with. As for point 2, I can 
see why you would prefer leaving out the exact number of elements. As 
for 4, I belief that sighted users have a somewhat equivalent experience 
if they quickly scan and scroll the screen, searching for headings, but 
I an not an expert in how a sighted user experiences web pages and which 
elements are important in particular for them. Regarding Verbosity, I 
actually consider the default of say all on page load much more verbose 
than a short summary about the elements on a page.

**Comment by jcsteh** [comment]
Sure, a sighted user can skim, which is the same reason we have quick
navigation. However, would anyone ever actually sit there and count the
number of headings, links, etc.? Why would the average user care that there
are exactly 1546 links on the page?

And use cases? How/why is this actually useful in achieving some real world
task?

**Comment by leonardder** [comment]
I can see use cases for having the number of actual headings or 
landmarks on the page. For example, if a page has over 50 headings and 
like 3 landmarks, using the d key is probably the quickest way to reach 
the main content, whereas if a page has like 15 landmarks and only 5 
headings, it tells the user that moving by heading is the way to go to 
find relevant content.

**Comment by fernando-jose-silva** [comment]
Generally I use stammetric counting of objects to quickly know if the page I just opened is very extense, and it will take me a long time to get to know the content of the page.

**Comment by bhavyashah** [comment]
@elliott94 @jcsteh raises some fair points and makes some powerful arguments against this functionality. As the original author of this ticket, do you have any remarks or responses?

**Comment by elliott94** [comment]
This was initially logged at a time when I'd just switched from JAWS to NVDA. I'm happy for this to be closed if that's the general opinion.

**Comment by fernando-jose-silva** [comment]
I still really like this feature, and if nvda informs you how many lines or words in navigation mode when loading a page.

Enviado do meu iPhone

Em 19 de ago de 2018, à(s) 07:38, elliott94 <notifications@github.com> escreveu:

**Comment by ruifontes** [comment]
Hello!

For me, it is a good feature, but should be possible of configuration...
At least, be possible to turn on or off.
Preferably, allow to turn on or off each type of information...

That way, will be possible to heard only the controls desired, by 
instance, only hearing:
Page with x links and y headings.

Rui


Às 11:38 de 19/08/2018, elliott94 escreveu:

**Comment by Qchristensen** [comment]
Has anyone looked at this issue lately?  I had a request from a user for it today.

**Comment by Brian1Gaff** [comment]
Yes Jaws has an option like this. It can be very handy when you go to sites 
you have never visited before. Controlling verbosity  is a very personal 
thing though, and soon ends up with so many options that one can miss the 
onne you want.
 Like many things though, I do like that feature of Jaws, but only when 
using sites that have been redesigned or are new to me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by feerrenrut** [comment]
To me it looks like the feature as described will not be implemented, reasons for this are well explained in previous comments. There is potentially a remaining use case for providing some kind of skimmed overview of a page. Though the specific goals have not been well defined. This issue currently reads like an implementation in search of justification. I'd prefer to close this issue.

**Comment by Adriani90** [comment]
One suggestion from my side at least, could this not be acomplished in the elements list? At least for the elements that can be chosen there? The radio buttons could contain also the number of the elements (i.e. link 320 radio button, headings, 20 radio button etc.). However, I think even this would have a big impact on performance. I wonder how Jaws does this?
