### ISSUE TITLE
nvda announces keyboard and input language in weird places

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7383]
Very hard to reproduce, and not expected unless I press Alt and shift.
It happens many times when I sign in. It announces my language and my keyboard input method in unexpected places.
It sometimes happens when I start some programs and the response takes a while.

**Comment by mohdshara** [comment]
For what it's worth, I do confirm this issue.

**Comment by jcsteh** [comment]
See also #1676, #2627, #5545.

If you're hearing the language get reported, that means NVDA was notified that it changed at some point, even if that change wasn't obvious to the user.

@MichaelDCurran, since problems like this keep showing up from time to time, do you think it might be worth putting some debug logging at the top of the input lang change thingy? That way, we can poke through a log to see what notifications we're actually getting without having to second guess our caching.

**Comment by jcsteh** [comment]
P3 because it's annoying, but doesn't really affect functionality.

**Comment by PratikP1** [comment]
In Windows 10, left alt+shift are assigned to switch languages along with windows+space. As far as I can tell, both commands do identical things. I'll file a request with Microsoft to remove the left alt+shift combination as this is the one that cause the most problems. It's used far more frequently in forming keyboard commands.
