### ISSUE TITLE
Excel 2010: Browse Mode Notification sounded when Navigating away from a Workbook into Firefox

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7392]
STR:

1. Ensuring that no web browser windows are open, launch Excel and open a new workbook

2. Leaving Excel open, open a new Firefox session

Actual: The notification for Browse Mode is sounded

Expected: Nothing should happen when the page is loaded

**Comment by leonardder** [comment]
Why do you think this is expected behaviour? I'd expect that if I am in Excel, even when I am in Excel browse mode, that Firefox will also trigger the browse mode sound since I've been moving into another app which triggered focus mode.

**Comment by ruifontes** [comment]
Leonard, in that case, we should have the sound of browse mode deactivated 
when exiting Excel and the sound of entering browse mode when landing in 
Firefox...
For me, only make sense if happens like I said... Browse mode deactivation 
when exiting the app in browse mode and entering again in browse mode when 
landing in the new app...

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 13 de julho de 2017 19:41
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Excel 2010: Browse Mode Notification sounded 
when Navigating away from a Workbook into Firefox (#7392)



Why do you think this is expected behaviour? I'd expect that if I am in 
Excel, even when I am in Excel browse mode, that Firefox will also trigger 
the browse mode sound since I've been moving into another app which 
triggered focus mode.

**Comment by elliott94** [comment]
It was simply that the sound shouldn't play; it doesn't have any advantage to the user, and if anything has the potential to cause some confusion as to why a notification sound is output.

**Comment by jcsteh** [comment]
We keep track of the last browse mode state; i.e. browse mode or focus mode. We play the sound whenever that state changes. In Excel, you start in focus mode, so when you switch to a browser, the sound gets played because that document is in browse mode and you were previously in focus mode (in Excel). Remember, Excel has browse mode now, so the focus mode and browse mode concepts do apply.

**Comment by bhavyashah** [comment]
@jcsteh By https://github.com/nvaccess/nvda/issues/7392#issuecomment-315223560, are you trying to imply that the described behaviour is expected and desirable for consistency, or are you open to making exceptions and allow for a change of behaviour as requested originally by this ticket?

**Comment by jcsteh** [comment]
I'd argue it's consistent and that we don't need an exception for Excel. Any change in behaviour related to these sounds should be consistent across all applications.
