### ISSUE TITLE
In internet explorer, area elements alt attribute text will be ignored.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7398]
### Steps to reproduce:
> 1. Open page: http://www.szmb.gov.cn/site/szmb/chengshitianqichaxun/index.html?city=深圳#cityreport
2. Press tab key to navigate to those area elements in the page
### Expected behavior:
> All text included in the area elements  alt attribute will be read.

### Actual behavior:
> Nothing was happened.

### System configuration:
NVDA version:2017.2

NVDA Installed or portable:install

Other information:
> Example: Running in a VM

Windows version:windows 7 above

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
> yes
Have you tried any other versions of NVDA?
> yes

**Comment by Adriani90** [comment]
@vgjh2005 could you please post a link with a new example for this issue? The link in the description is not working. Thanks!

**Comment by Adriani90** [comment]
IE support has ended completely in 2022 and the browser is being removed automatically from machines that still have it after an Edge update in February 2023. I am closing this issue as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. If you are having this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
