### ISSUE TITLE
split word boundaries for JAB applications as so not to break unicode chars

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7404]
### Steps to reproduce:
https://github.com/nvaccess/nvda/issues/1570

Do this with any java application which has a multiline edit field (Eclipse?).

**Comment by jcsteh** [comment]
Please provide specific STR in future rather than referring to another issue.

1. Eclipse doesn't use JAB.
2. NVDA now uses Windows Uniscribe for its own word splitting algorithm, which should handle Unicode correctly.
3. I tried pasting ആപ്പിള് into an edit field in Java Control Panel and moving by word reported the entire word.
