### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by danwainwright01** [nvaccess/nvda#7420]
Hi, I have a suggestion, as a person who downloads a lot, and is into software development, I spend a lot of time waiting for things to load, I am suggesting that as well as the progress beeps which I admit are very good and helpful, can we please please have the chance to change to percentage updates as seen on JAWS. I just think it would be a good idea. Sorry for mistakes, this is typed in a hurry at work. Another place where we deal with software a lot and use github. This is also typed with NVDA.

Thank you.

**Comment by ehollig** [comment]
Possibly related: #4388, #5031

**Comment by leonardder** [comment]
Honestly, I'm reading this as @danwainwright01 is suggesting to have NVDA speak for progress bars, and that is already possible. See nvda mmenu > options > object presentation.

**Comment by dan1982code** [comment]
The OP appears to be asking for a way to change the interval at which percentage notifications are spoken; e.g. every 5%, every 10%, etc.

**Comment by jcsteh** [comment]
As noted earlier, you can already switch to speaking of percentages. Closing.

[**@dan1982code**](https://github.com/dan1982code) commented on [20 Jul 2017, 08:54 GMT+12](https://github.com/nvaccess/nvda/issues/7420#issuecomment-316514267 "2017-07-19T20:54:47Z - Replied by Github Reply Comments"):
> The OP appears to be asking for a way to change the interval at which percentage notifications are spoken

The request was "the chance to change to percentage updates". The "to" suggests switching, rather than adjusting. However, please reopen if you believe this was misunderstood.
