### ISSUE TITLE
Possibility to add a keystroke to switch between input and output braille tables

### ISSUE THREAD

**Issue by mohammadrezarashad** [nvaccess/nvda#7515]
Is it possible to create a quicker way to switch between specified input or output braille table?
This could benefit Bylingual blind users to switch between their chosen braille tables for reading and typing in braille using their braille displays.
For example I, as a Persian user who also wants sometimes to read just English text, would be able to switch between Persian grade 1 and American English grade 2 by a keystroke on my braille display or my computer's keyboard.
and also When writing by braille keys, I would be able to switch between my prefered input tables quickly.

**Comment by ehollig** [comment]
This is requested in #3718, but that primarily requests for switching of input tables. If a feature like this were to be implemented, I agree that it should allow for switching of input and output tables. CC @leonardder and other Braille experts

**Comment by nvdaes** [comment]
Hi, imo this will be better fixed with an add-on, since it requires to configure a subset of input or output braille tables, and keystrokes to switch between options, for instance synthesizers or log levels, could be requested and make less simple the NVDA's gui.
Anyway, if this was implemented in the NVDA's core, a possibility will be to add:
- A checkbox after each combo box (for output and input braille tables, in the Braille settings dialog), to choose if the selected table would be added to the subset of tables accessible from a gesture. This checkbox should be checked for the currently selected table, and unchecked when the element of the checkbox is changed, so that the current table is included in the subset (list) by default.
- In the brailleTables.py file, a quickAccessInput and quickAccessOutput elements for the BrailleTable namedtuple, and the corresponding modification in the addTable function.
- In configSpec.py>braille section, two keys quickOutputTables and quickInputTables assigned to empty lists as default values.
- In globalCommands.py, two scripts without assigned gestures, under the SCRCAT_CONFIG category, to toggle the input and output tables through the corresponding lists.
Cheers

**Comment by Andre9642** [comment]
Hi,
In the meantime, I propose you my BrailleExtender add-on. I recently added the possibility to switch between several input braille tables https://andreabc.net/projects/NVDA_addons/BrailleExtender/

**Comment by mohammadrezarashad** [comment]
Thanks dear André for your great add-on. I'm now using BrailleExtender
17.8.27.3. I have currently no braille display. Using
PCKeyboardBrailleInput add-on, I could test braille input table switch
and it works. I'll test braille output switch this weekend. and will
report.

-- 
     Best wishes,
     Mohammadreza Rashad

**Comment by leonardder** [comment]
@dkager, thoughts? I'd say UX would be a problem here. E.g. if we change the combo boxes into check list boxes, it would have a major impact on how the ui is displayed visually.

**Comment by dkager** [comment]
Is there a use case for this that is not covered by setting the braille table in a config profile, then switching between config profiles with a hotkey?

**Comment by leonardder** [comment]
[**@dkager**](https://github.com/dkager) commented on [28 aug. 2017 17:40 CEST](https://github.com/nvaccess/nvda/issues/7515#issuecomment-325390169 "2017-08-28T15:40:25Z - Replied by Github Reply Comments"):
> Is there a use case for this that is not covered by setting the braille table in a config profile, then switching between config profiles with a hotkey?

I think I agree here.

**Comment by mohammadrezarashad** [comment]
Hi and thanks for comments,
Currently I'm testing BrailleExtender add-on with a Seika Mini Notetaker braille display. It's great! It quickly switches between output braille tables too!
Thanks dear Andre. I think I can close this issue now.

**Comment by ehollig** [comment]
Would it be possible to get this addon in the list of official NVDA addons?

**Comment by zstanecic** [comment]
no, because the author’s page, as i know is in french,

it’s only for baumm displays,

not for the other.


W dniu 05.09.2017 o 18:06, Ethan Holliger pisze:

**Comment by Andre9642** [comment]
> Thanks dear Andre. I think I can close this issue now.

Thanks you for your feedback! :)

> Would it be possible to get this addon in the list of official NVDA addons?

The add-on is not yet completed. There are many additions and corrections to be made.

> it’s only for baumm displays, not for the other.

That is no longer the case. Focus and Brailliant displays are also supported now. In addition, some features can be used with Any braille displays.
