### ISSUE TITLE
NVDA skips pronunciation of outer 'div' when moving baсkward (using `Shit+Tab`)

### ISSUE THREAD

**Issue by DzmitryAlifer** [nvaccess/nvda#7522]
Here is my [code snippet at jsfiddle](https://jsfiddle.net/y8tLme06/21/) and its duplication below:

Here is the actual behavior (what you do / focused element id / what NVDA reads):

### When moving forward (using `Tab`):
> 1. Navigate to Header / header / Header
> 2. `Tab` / slats-component / Total [2], Slat 1, Slat 2
> 3. `Tab` / slat1 / Slat 1
> 4. `Tab` / slat2 / Slat 2

### When moving backward (using `Shift + Tab`):
> 1. Navigate to Slat 2 / slat2 / Slat 2
> 2. `Shift + Tab` / slat1 / Slat 1
> 3. `Shift + Tab` / slats-component / [nothing]
> 4. `Shift + Tab` / header / Header

### Actual behavior:
while moving backward on step #3 NVDA reads nothing

### Expected behavior:
on the same step NVDA reads: Total [2], Slat 1, Slat 2

### System configuration:
NVDA version: 2017.3 (installed)
Example: Windows 8

**Comment by Adriani90** [comment]
I am not sure if this implementation is actually correct because the behavior is inconsistent between browsers. You will see the differences when you enable focus mode with NVDA+spacebar and navigate with tab and shift+tab over the slat1, slat2 etc.

My testing results with NVDA 2019.1.1 and firefox 66.0.3 as well as Chrome 74 are as follows:
* Browse mode:
1. Open the link in the description
2. Press ctrl+nvda+f and search for "slat"
3. Press enter to jump to the first string
4. Press h to jump to the heading after the code
5. Press shift+tab multiple times until you hear "header
6. Press tab twice
7. Press shift+tab once
Actual: NVDA is silent in both browsers
Expected. NVDA should report "Total [2], Slat 1, Slat 2"

* Focus mode:
1. Repeat steps 1 through 4 above
2. Press nvda+space bar to enable focus mode
3. Press shift+tab and tab multiple times
Actual: In Chrome everything works as expected. Even the issue in browse mode is not occuring anymore. In firefox however, the elements are not reported at all as if they were not focusable.
Expected: In firefox the elements should also be treated as focusable objects if the implementation is correct. NVDA should report "Slat 1, Slat 2" etc. also when using focus mode.

cc: @jcsteh your thoughts are also very appreciated. thanks.

**Comment by Adriani90** [comment]
might be related to #6627 and #6606.

**Comment by Adriani90** [comment]
Not sure why this works in Chrome, but actually here is bad authoring. Tabindex is used on non interactive divs, which are not displayed in the accessibility tree. Firefox handles this properly.
More details:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex?retiredLocale=de
So this is not an NVDA issue, closing as invalid.
