### ISSUE TITLE
Make HumanWare BrailleNote driver thread safe

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7574]
The current HumanWare BrailleNote driver, although native, does not yet utilize the hwIo module. This driver should be updated to support braille display auto detection, since we agreed in #1271 that this will be a prerequisite.

@ragb: Would you be able to do this?

**Comment by josephsl** [comment]
Hi, a few months ago I and @JCSTeh discussed this briefly when I worked on BrailleNote QT support, and we both agreed that moving to HwIO would provide significant benefits. Jamie knows more about thread safety of this driver, and I do have a BrailleNote I can use for testing purposes, so I’d say let’s try it.

**Comment by leonardder** [comment]
I do not have such a device myself, and from what i've learnt from driver development, it is really hard when you do not have a device. I'd be happy to review code alongside others though.

**Comment by jcsteh** [comment]
Any driver that users hwIo should be thread safe. Porting this driver should be fairly simple. The bits that need the most attention relate to the way packets are read. As I understand it, each packet is 2 bytes (except the describe response, which is 3 bytes). Because this is serial, I'd recommend you stick to the default of receiving 1 byte in the callback, then reading 1 further byte for the argument (or 2 if handling the describe response). This is because with serial, you can't trust that the first byte you ever read will be the first byte of a packet; it could be the second byte of a previous packet.

**Comment by josephsl** [comment]
Hi,

BrailleNote driver says: ord function was expecting a character but got an empty (zero-length) string instead when querying various status info. Thanks.

**Comment by ragb** [comment]
Hi all,

Unfortunately I'm not able to help that much since my very old BrailleNote stoped working a year ago or something... If someone needs help with the driver code I can try to recall what I did there though :).

**Comment by jcsteh** [comment]
@josephsl, full traceback please?

**Comment by jcsteh** [comment]
Just pushed a change to the i7574ThreadSafeBrailleNote branch which might fix things.

**Comment by josephsl** [comment]
Hi,

Yes, works beautifully now - no issues at this point. Thanks.
