### ISSUE TITLE
Klicktel phone book CD

### ISSUE THREAD

**Issue by jammerhexe** [nvaccess/nvda#7575]
There is the very common phone book CD in Germany entitled "Klicktel". It runs without installing direct from the drive. Unfortunately when I scroll with arrow down through the list of towns, names etc. NVDA didn't read this entries. I suppose it only is a minor problem. However, I would be happy if you could fix it.
I uploaded an 800 MB ISO imae of an older Klicktel CD to my NAS at:
https://menschomat.goip.de/nas/filelink.lua?id=154cd01141600847
Hope you can download it from there. Thanks in advance for have a look to this problem.
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by Adriani90** [comment]
Closing as duplicate and in favor of #6135.

**Comment by jammerhexe** [comment]
Hi,

please tell me what this mean? Is the problem solved? Did you get my last mail with Steffen König’s description how Baum fixed the problem?
Will NVDA be able to handle the Klicktel in ist next release?
Or do you no longer try to solve the problem?

Thanks in advance for any reply.

Yours sincerely

Arno

Von: Adriani90
Gesendet: Montag, 22. April 2024 21:24
An: nvaccess/nvda
Cc: jammerhexe; Author
Betreff: Re: [nvaccess/nvda] Klicktel phone book CD (#7575)

Closed #7575 as completed.

**Comment by Adriani90** [comment]
Hey Arno,

 

the old issue is still open, this one was just a double issue so that’s why I closed it. I cannot tell anything about a solution for now, this will depend on community engagement and NV Access if they have capacity to contact Steffen for more details.

 

 

Von: jammerhexe ***@***.***> 
Gesendet: Dienstag, 23. April 2024 22:54
An: nvaccess/nvda ***@***.***>
Cc: Adriani90 ***@***.***>; State change ***@***.***>
Betreff: Re: [nvaccess/nvda] Klicktel phone book CD (#7575)

 


Hi, 

please tell me what this mean? Is the problem solved? Did you get my last mail with Steffen König’s description how Baum fixed the problem? 
Will NVDA be able to handle the Klicktel in ist next release? 
Or do you no longer try to solve the problem? 

Thanks in advance for any reply. 

Yours sincerely 

Arno 

Von: Adriani90 
Gesendet: Montag, 22. April 2024 21:24 
An: nvaccess/nvda 
Cc: jammerhexe; Author 
Betreff: Re: [nvaccess/nvda] Klicktel phone book CD (#7575) 

Closed #7575 as completed.
