### ISSUE TITLE
Some of lapTop layout keys don't work with the french keyboard

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#7668]
Some of lapTop layout keys don't work with the french keyboard, among them:

* `NVDA+ù` (left mouse button);
* `NVDA+SHIFT+ù` (Left mouse button lock);
* `NVDA+*` (Right mouse click);
* `NVDA+SHIFT+*` (Right mouse button lock);
* `NVDA+;` (Report current character in review);
* `NVDA+CTRL+;` (Report current word in review);
* `NVDA+SHIFT+;` (Report current line in review).

**Comment by ehollig** [comment]
@Andre9642, could you please try this with all NVDA addons disabled? It is possible that one of them has modified your input gestures.

**Comment by Andre9642** [comment]
@ehollig I already tested... Same issue with portable and installed version. Tested on Windows 10 only, on several computers. At least 2017.3 and next recent versions concerned.

**Comment by Andre9642** [comment]
Another precision: if I copy the `gestures.ini` file located at "%programfiles(x86)%\nvda\locale/fr" in "%appdata%\nvda", it works perfectly. If a `gestures.ini` file doesn't present or another `gestures.ini` file (without these gestures) is present in "%appdata%\nvda" these gestures don't work.

**Comment by feerrenrut** [comment]
@Andre9642 What language do you have NVDA set to (in General settings dialog)? Could you please remove the `gestures.ini` file from `%appdata%\nvda` (in order to reproduce the problem), then restart NVDA with debug level logging, and attach the NVDA log to this issue? This will hopefully allow us to investigate further.

Technical:
The code that loads the locale specific gestures file is in `def loadLocaleGestureMap` in the `source/inputCore.py` file. This could be improved to add debug level logging to show which files are loaded.

**Comment by Andre9642** [comment]
I just found the problem, and it's my fault. By mistake, in one of my addons, I called `inputCore.manager.localeGestureMap.clear()`.
I don't understand because it seems to me have already tested with all addons disabled...
I'm terribly sorry for all of the noise.
