### ISSUE TITLE
Windows 10: NVDA Silent on Cortana Search Screen when Laptop Lid Closed

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7746]
When typing anything into the Cortana search screen, NVDA is silent when my laptop lid is closed and I'm typing on an external keyboard. Search suggestions are automatically output as expected when the lid is opened; currently, I'm manually able to cursor around and focus on these after typing what I'm searching for. I can get developer info if that would help diagnose this.

**Comment by Brian1Gaff** [comment]
What make and model of laptop is it? Might be just a quirk of the bespoke 
software in your laptop that deals with what happens when the lid is closed. 
some go into a semi sleep mode others hibernate and others do nothing at all 
or maybe switch the screen off.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ehollig** [comment]
@elliott94, what do you have set in your power options under additional power settings. There should be an option, "Choose what closing the lid does". When I close my lid, I have it do nothing when plugged in and do not experience the issue you are having. So as @Brian1Gaff says in https://github.com/nvaccess/nvda/issues/7746#issuecomment-343728545, it could be something specific with your computer, or a setting is not set correctly in the power options.

**Comment by feerrenrut** [comment]
I think the suggestion by @elliott94 is worth pursuing first. One question, can any sound be heard from the laptop? Perhaps the audio device is disabled when the lid is closed?

**Comment by elliott94** [comment]
The setting in Power Options is set to "do nothing"; I often use my laptop in this way if I have an external keyboard connected and do not need to keep the screen up. In addition to this, NVDA does not output the default sound that a search suggestion has popped up.

**Comment by feerrenrut** [comment]
@elliott94 can you trigger a sound from some other application or windows when the lid is closed and report if that sound can be heard? I want to establish that some sound outside of NVDA can be heard, this will help us to understand if this is caused by NVDA or some Windows / driver setting. For instance try plugging and unplugging a USB device, this normally causes windows to make a sound. Also please try playing some music and closing the lid.

**Comment by elliott94** [comment]
Everything works without issue when the lid is closed; sound is output as usual. NVDA behaves as expected apart from when on this screen.

**Comment by feerrenrut** [comment]
Ok, thanks for the clarification. I now understand the issue is specific to the Cortana search screen, otherwise NVDA works as expected while the lid is closed. Could you attach a debug level log file to this issue after reproducing this problem please?

**Comment by josephsl** [comment]
Hi, and preferably with the WinTenApps add-on enabled and NVDA restarted in debug logging mode so I and Reef can take a look at what’s up? I mention the add-on and the debug logging mode because the add-on will include information about events and objects as they come in. Thanks.

**Comment by Adriani90** [comment]
@elliott94 Is this issue still reproducible?

**Comment by Adriani90** [comment]
Could you please enable the Win10 apps add-on from Joseph and send us a log file? Please set NVDA on debug Level in General Settings. Ideally you start NVDA, Close the lid and when the objects are comming and if NVDA is silent, after that open it again and save the log file.. Thanks.

**Comment by josephsl** [comment]
Hi, in order to do so, you need to enable my add-on, restart with debug logging enabled (because normal debug log procedure won’t work), then attach the log. Thanks.

**Comment by josephsl** [comment]
Hi,

Any updates in August 2021? Note that since Windows 10 Version 2004, Cortana was separated from Windows Search experience.

Thanks.

**Comment by elliott94** [comment]
Unfortunately I no longer have access to the machine where I was able to reproduce this - will close for now and re-open if I can reproduce at a later date.
