### ISSUE TITLE
NVDA does not behave consistently when navigating with tab in certain dialogs in ms office 2016

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7758]
Steps to reproduce:
1. Type something in a cell in ms excel 2016
2. Press the context menu key and go to formating cells
3. Press tab and shift tab. 

Expected behavior:
NVDA should read the font type and so on when navigating by pressing tab and passing the combo boxes. Ideally first the entry which is selected and after that if it is a combo box or what so ever.

Actual behavior:
In several dialogs in ms office 2016 NVDA shows an inconsistent behavior when navigating by pressing tab. Entries in some combo boxes are not being red, selected tabs are not being reported. In my example, when I reach the position where NVDA should say which tab is selected, there is no report at all. I have to press the right arrow key to here the next tab and than the left one to hear the tab where I was originally.

System configuration:
NVDA version:
2017.3

NVDA Installed or portable:
both

Other information:

Windows version:
Windows 10 last update.

Name and version of other software in use when reproducing the issue:
MS Office 2016

Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
not yet

**Comment by feerrenrut** [comment]
Can you give specific information about a control that you can not access?

I tried the following with Excel 2013:
1. type into a cell ( dont press enter or otherwise leave the cell)
1. open the context menu and select formatting
1. press tab and hear "Font:blank"
1. press the up and down arrows to select different fonts.

Actual:
NVDA announces "blank"

Expected:
The names of the fonts should be announced as I select them

**Comment by Adriani90** [comment]
Yes but when I type something it has a certain type selected already. But NVDA apparently does not recognize the entry in the Combo box. When I choose for example times new Rroman with the arrow keys and press ok and go back to check if it's selected, NVDA says "blank" again.

As far as other elements are concerned, the issue seems to be more bovious in MS Office 2016.

**Comment by Adriani90** [comment]
This issue might not be important if it would occur only in this Dialog. But there are lots of dialogs where the same issue appears.

Imagine you have a Dialog with many Settings and lots of them are structured in Combo boxes. You would have to press down arrow and then up arrow on every combo box to find out which Setting was actually selected.
In my opinion there is a General issue in Combo boxes, rather than only in Office 2016. This is just an example.

**Comment by PratikP1** [comment]
I believe the title of this bug report should be changed to reflect the issue outlined—namely, “NVDA does not read all controls in Excel 2016’s formatting dialog.”

**Comment by PratikP1** [comment]
@Adriani90 commented 
< This issue might not be important if it would occur only in this Dialog. But there are lots of dialogs where the same issue appears. Imagine you have a Dialog with many Settings and lots of them are structured in Combo boxes. You would have to press down arrow and then up arrow on every combo box to find out which Setting was actually selected. In my opinion there is a General issue in Combo boxes, rather than only in Office 2016. This is just an example.

The behavior of combo boxes and other dialog controls is often dependent on how these controls are programmed. In some cases, NVDA can use accessibility APIs or other techniques to read information and allow navigation. However, without looking at each case or type of cases, NVDA can't resolve issues if developers do not provide proper information. The blanket issues you have defined above cannot be solved with a blanket solution; thus, my recommendation above to change the focus of this bug report to refer to the specific issue in Excel.

**Comment by Brian1Gaff** [comment]
Yes I just ran a very old version of word 2003, and noted this on fonts 
which I was trying to change on a block of selected text, so its as if its 
kind of once removed from the actual item its trying to  read.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment]
No it is in several dialogs. This is just an example to reproduce it.



Von meinem iPhone gesendet

**Comment by feerrenrut** [comment]
@Adriani90, first it's important to ensure we are observing the same behaviour in one specific case. Then we can list a few other cases where a similar problem seems to exist. Can you confirm for me that you get the behaviour described in:  https://github.com/nvaccess/nvda/issues/7758#issuecomment-344539297

@PratikP1 You may be right that there is little we can do to fix this case in a general way, however I believe it's useful to know and acknowledge that the problem exists in a general way. It may be, that we have to fix each of these problems individually. Having a single issue that highlights and explains a single case well and then references other locations where a similar category of problem exists will make fixing this easier.

**Comment by Adriani90** [comment]
So with NVDA 2017.2 on Windows 8.1 and MS Office 2010 works everything properly. NVDA 2017.3 on Windows 8.1 and Office 2010 as well. Not so 2017.3 on Windows 10 and Office 2016.

**Comment by Adriani90** [comment]
Could it be an issue related to Windows 10?

**Comment by Adriani90** [comment]
@ Brian did you encounter that issue in Office 2003 on Windows 10?

**Comment by feerrenrut** [comment]
This seems annoying, however since this is a workaround to get the information I'll give this issue a priority 3.

**Comment by Qchristensen** [comment]
There might be several issues here.  One is that in dialog boxes in Excel, NVDA cannot seem to find text which is selected.  This is why when you tab to the font name, it reads none because what happens is that the focus moves to that edit box and the contents are selected.  If you press left arrow at that point, it will unselect the text, move to the start of the edit and read the first character.  If you now read the current line, it will read the current font name.

#6891 is the same issue.
#5076 is possibly the same issue as well.

The other issue in the original comment was that the tab name not being read.

For the sake of clarity, since most of the conversation in this issue is on the reading edit boxes problem, I've created a new issue #7808 specifically on the tab name not being read.

**Comment by feerrenrut** [comment]
@Qchristensen thanks, I will remove the references to the tab name from the description of this issue in an attempt to reduce confusion.

**Comment by Adriani90** [comment]
this is still reproducible with NVDA 2018.2.1 and MS Excel 2016.

**Comment by Adriani90** [comment]
It might be related to #8328

**Comment by Adriani90** [comment]
I cannot reproduce this issue in NVDA 2018.4.1 and Excel 2016 and 365. I am closing this one as works for me. We can reopen it if someone reports it again. thanks.
