### ISSUE TITLE
adjust voice language automatically to application language for object type and state

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7764]
Steps to reproduce:
1. Open a Programm where Status of objects is being reported by NVDA (i.e. Excel sheet with locked and unlocked cells, MS Outlook with e-mails containing attachments, a Website in a browser). Navigate through the elements
2. Be sure that the application language is similar to NVDA language (i.e. english)
3. In the application you have text in a different language (i.e. german)
4. Voice language is switched to german to read the text.

Expected behavior:
The pronounciation of object state and type should still be pronounced by a voice which matches to the application language (i.e. english voice). For this, the synthesizer should automatically change the voice when reporting status and type of objects to application language. Status could be for example edit only, unlocked, unchecked, unavailable etc.

Actual behavior:
NVDA reads the text in the language which is selected from the settings ring (german). State and type of objects are pronounced by german voice and not by english voice.

System configuration:
NVDA version:
all

NVDA Installed or portable:
both

Other information:

Windows version:
All

Name and version of other software in use when reproducing the issue:
All

Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
yes, all

**Comment by leonardder** [comment]
I'm afraid this must be implemented on a per language basis. For espeak, this should be not that difficult actually, as NVDA already sets espeak to the NVDA language on first launch.

**Comment by feerrenrut** [comment]
@Adriani90 could you update this with examples of the speech, it really helps to clarify the request.
Let me provide an example of what I assume was intended:
* Opening a Norwegian document / website / form (_please excuse any bad Norwegian language_)
* NVDA language is set to English (General settings dialog)

Actual: `Ha en fin dag button`
Expected: `Ha en fin dag knapp`

If you are not a Norwegian speaker, you have no context at all for what it is you are interacting with. The semantics of this object is lost.

**Comment by Adriani90** [comment]
If you turn the synthesizer to norvegian, object types are being pronounced strange anyway. But I aggree with you. I think this could confuse the user. My problem is rather in outlook or excel, where NVDA does not automatically change the language for example if an e-mail with norvegian subject has an attachment. The status „has attachment“ is being pronounced in the nvda-language but with norvegian accent. Assume nvda language is inglish but synthesizer language is norvegian.


Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
I have updated the issue accordingly. I did a mistake in thinking when I have created this. Thank you for the remark.

**Comment by feerrenrut** [comment]
Please add expected and actual speech for each of the examples in the description.

**Comment by Adriani90** [comment]
I have edited the description accordingly. If it is still difficult to understand it, then I think I have to record an audio to show the problem.

**Comment by feerrenrut** [comment]
Sorry, I think my last comment was intended for a different issue. 

To make sure I understand the issue, can you confirm that this issue is to request that the accent / voice of the synthesizer automatically match the language currently being spoken by NVDA

@Adriani90 just generally, since you are creating many issues at the moment, and seem to be representing a group of users which really is appreciated. To make the process a little bit easier, please could you:
* List the exact steps someone needs to take to experience the behaviour for themself. This helps to resolve the ambiguities that are likely to be present in the discussion of the issue. It may seem tedious to have steps such as "open excel", "type blah". But it gets everyone discussing the issue onto the same page. This is extremely important when there is a language barrier. 
* Try to stick with one clear example of how to reproduce the behaviour when discussing the issue. Once one example is clearly understood, it is likely enough to say something like: "This also affects outlook, word, excel"
* The examples given on this issue are more like "use cases", giving a justification of **why** certain behaviour should be supported. These are useful too, but not really a substitute for detailed "steps to reproduce"
* When using multiple examples, keep the steps to reproduce, actual output, and expected output for each example together. You can follow this with general discussion if you wish. For example:
Example 1
Steps to reproduce: "type blah"
Actual output "hear hello"
Expected output "hear blah"
Example 2
Steps to reproduce: "type hello"
Actual output "hear world"
Expected output "hear hello"

Again, thank you for your contributions to NVDA, I hope that you find this advice / criticism constructive. I should add NV Access is a small team, reading and understanding these issues takes a lot of our time. The easier you can make this process for us, the faster we can get to actually making changes. This goes for new feature ideas as well, currently there is no shortage of good ideas or bugs to fix. Given our current size, many ideas proposed will be unlikely to get implemented by NV Access. However, many of the ideas do get implemented by other contributors, for this to happen the issue needs to be well understood by NV Access and the contributor.

**Comment by Adriani90** [comment]
@feerrenrut yes this is correct.

Thank you very much for your important aspects. I will try to edit the issues as soon as possible to make it easier to understand. I must admit that some of them are very comprehensive. But I think some are also very interesting from a development point of view.


Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
Edited

**Comment by Adriani90** [comment]
I think now is quite clear where the issue is.

**Comment by Adriani90** [comment]
@leonardder, @feerrenrut I have edited the issue again. i hope it is more understandable now.

**Comment by Adriani90** [comment]
After testing this feature with Voiceover on mobile devices, I think it should be an optional feature which can be activated in synth settings.

**Comment by Adriani90** [comment]
Ok i will close this issue because it gets more and more confusing. I will open a new one with a more reproducible character. Apart from that, this works for me actually. Only if the voice language is a language which does not match with application language, text language and NVDA language, the issue occurs.
