### ISSUE TITLE
in chrome the labels of text boxes are not reported in the browser

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7840]
When you open the page
https://cabify.com/signup

When walking with the arrows below
there are a number of text boxes that must be filled.

### Expected behavior:
When navigating with the arrows and passing over the text fields, nvda should announce the label of the boxes that are:
name
last name
email
password
cellphone number

### Actual behavior:
When navigating with the arrows and going through the text boxes, nvda announces only editing.

### System configuration:
NVDA version:
> Example: next-14699

NVDA Installed or portable:
instaled

Other information:
this works correctly in firefox 57

Windows version:
> Example: Windows 10 Version 1709 Build 16299.64 and windows 7

Name and version of other software in use when reproducing the issue:
google chrome 62.
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

no

**Comment by Adriani90** [comment]
Actually the fields seem to have alt tags. If you press e to navigate from edit field to edit field, NVDA will read the labels. Also when you go to focus mode by pressing NVDA + space and navigate by pressing tab, the labels are being reported. I think this issue is not very significant.

**Comment by Adriani90** [comment]
or do you really need to use the arrow keys to navigate from edit field to edit field?

**Comment by fernando-jose-silva** [comment]
Respectfully disagree, this call to me is very important, EU mainly use to certain to navigate the Internet pages

Enviado do meu iPhone

Em 8 de dez de 2017, à(s) 11:09, Adriani90 <notifications@github.com> escreveu:

**Comment by ehollig** [comment]
It appears that the placeholder is not being reported in Chrome in browse mode.

**Comment by feerrenrut** [comment]
I can reproduce the issue, with Google Chrome canary `65.0.3299.0` and Chrome `63.0.3239.84`. NVDA does output the expected values when using Firefox, which I believe uses the same code path as Chrome, so I suspect this is a Chrome bug.

The markup on Cabify uses the "placeholder" attribute rather than `aria-placeholder`.
Looking at the attributes passed into `Gecko_ia2_TextInfo._normalizeControlField` I found out:
*  There is no placeholder attribute passed in, which is the case for both FF and Chrome.
* I presume that NVDA is speaking the `name` attribute when using Firefox, however this attribute is present in Chrome as well.

A quick smoke test of the `aria-placeholder` support (using the test document from https://github.com/nvaccess/nvda/pull/7055#issuecomment-303925221) indicates that `aria-placeholder` seems to be reported as expected in browse mode for chrome.

Either way, more investigation needs to be done.

**Comment by michaelDCurran** [comment]
This requires both changes in NVDA and in Chrome.
NVDA changes are in branch i7840 in this repository, though no pr has been made yet due to the change not yet in Chrome stable.
The change is already in Chrome Canary, but we should wait until it gets to stable as the change in NVDA is backwards incompatible. 
See Chrome issue 757707

**Comment by michaelDCurran** [comment]
Technical:
Chrome stable does not yet implement IAccessible2_2::relationTargetsOfType for 'labelledBy'.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [12 Feb 2018, 08:22 CET](https://github.com/nvaccess/nvda/issues/7840#issuecomment-364844894 "2018-02-12T07:22:23Z - Replied by Github Reply Comments"):
> The change is already in Chrome Canary, but we should wait until it gets to stable as the change in NVDA is backwards incompatible. 

What does this mean in practice? Does this change make older versions of chrome unusable?Note that in corporate environments, people might be forced to stick to an older version of Chrome.

**Comment by fernando-jose-silva** [comment]
Thank you very much for the attention you are giving to the question.
A small opinion about the result, I prefer that the labels be reported twice, than not to be reported.

**Comment by ehollig** [comment]
Unfortunately, it does not appear that the original URL is valid anymore. @michaelDCurran can this issue now be addresse4d now that [Issue 757707](https://bugs.chromium.org/p/chromium/issues/detail?id=757707) is now in Chrome stable?

**Comment by Adriani90** [comment]
Testing with NVDA 2018.4.1 and Chrome 71, the issue is not reproducible anymore.
@fernando-jose-silva can you confirm?

**Comment by fernando-jose-silva** [comment]
yes, it's working properly now, thank you very much.
