### ISSUE TITLE
IE11 & Chrome: table navigation commands do not work in this page

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7852]
### Steps to reproduce:
1. Open [this page](http://lib.blindness.org.tw/user_recommend_display.php).
2. Press NVDA+control+f to find text "序號".
3. Press control+alt+rightArrow to move to next column.
### Expected behavior:
NVDA Reads column2 "書名".

### Actual behavior:
NVDA reads "not in a table cell.".

### System configuration:
NVDA version: 2017.3 and later
NVDA Installed or portable: installed
Name and version of other software in use when reproducing the issue: Internet Explorer11

### Other questions:
Have you tried any other versions of NVDA?
This case does not occur in 2017.2 and previous version.

**Comment by Adriani90** [comment]
I can reproduce this with NVDA 2017.3 in IE11

**Comment by Adriani90** [comment]
I can reproduce it in Firefox 57 too.

**Comment by feerrenrut** [comment]
The table in the given example does not seem to have table headers, which seems to be why table navigation is not working. A couple of simpler examples (paste into chrome or firefox address bar)

**With table headers:**
`data:text/html,<table style="width:100%"><tr><th>Firstname</th><th>Lastname</th><th>Age</th></tr><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

**Without table headers:**
`data:text/html,<table style="width:100%"><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

I actually don't know if this is intentional or not. Further investigation is required.

**Comment by Adriani90** [comment]
It is somehow strange that Jaws does not have this issue at all.

**Comment by feerrenrut** [comment]
After talking to michaelDCurran about this, he has made me aware that this is intentional. There are several heuristics used to differentiate between data tables and layout tables, one of which is the presence of column headers. Layout tables are used to set the structure of a web page rather than to provide tabular data. Other attributes that identify a HTML table as a data table are borders, having more than one row, or more than one column.

This behaviour can be disabled by checking the "Include layout tables" option in browse mode settings.

**Comment by Adriani90** [comment]
The difference is that when layout tables is enabled, table navigation works properly in IE. But it does not work in chrome. So I think we should reopen that issue related to chrome.


Von meinem iPhone gesendet

**Comment by feerrenrut** [comment]
I already mentioned this on #7913, but to make sure this issue is clear also:
We rely on Chrome to expose these tables. 

**Example 1. with table headers:**
`data:text/html,<table style="width:100%"><tr><th>First name</th><th>Last name</th><th>Age</th></tr><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

**Example 2. without table headers:**
`data:text/html,<table style="width:100%"><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

Example 1. works as expected.
I see that in Chrome that Example 2 is not recognised as a table, regardless of whether the "Include layout tables" option is checked or not. Exploring this with Object navigation, and "Simple review mode" off, shows that each cell of the table is reported as a "Section". This means that Chrome is not exposing this as a table to NVDA, we do not have any control over this.

The question becomes, why is it expected that this should be interpreted as tabular data rather than structural? The web author has not provided column or row headers, or made it look like tabular data.

If it really is important to that this header information is not visible the following approach could be used:
`data:text/html,<head><style>.screen-reader-text { clip: rect(1px, 1px, 1px, 1px); height: 1px; width: 1px; overflow: hidden; position: absolute !important; }</style></head><body><table><thead class='screen-reader-text'><tr><td>first name</td><td>last name</td><td>age</td></tr><tbody><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></tbody></table></body>`
