### ISSUE TITLE
Regions with assertive or polite aria-live attributes are not voiced when created

### ISSUE THREAD

**Issue by sclower** [nvaccess/nvda#7906]
### Steps to reproduce:
1.  In Chrome or Firefox, visit the following JSBin: http://jsbin.com/bomexuxopu/edit?html,css,js,output
2.  Click the "Run JS" button.

### Expected behavior:
NVDA speaks "this text should be automatically read by a screen reader."

### Actual behavior:
It does not. Note: JAWS 17+ and VoiceOver on macOS 10.10+ do speak this text.

### System configuration:
NVDA version: 2017.4
NVDA Installed or portable: installed

Other information:

Windows version:
Windows 10 version 1703, OS build 15063.726

Name and version of other software in use when reproducing the issue:
Firefox ESR 52.5.2 (64-bit)
Chrome 63.0.3239.132 (Official Build) (64-bit)

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Yes, occurs at least as far back as 2017.1

**Comment by Otobelikethee** [comment]
@jcsteh Hi James, is this a bug? I have met the same problem.

**Comment by Otobelikethee** [comment]
@josephsl Hi Joseph, could you please confirm this issue?  thx.

**Comment by josephsl** [comment]
Hi,
Sorry, I'm not really an expert on this one.

**Comment by Adriani90** [comment]
cc: @jcsteh Your thoughts regarding firefox are very appreciated here. Thanks.

**Comment by Sebi2020** [comment]
The same issue exists with Chrome (latest version @ 29.10.19). 

With aria-live="assertive" NVDA does not advertise changes if the user does some input. But if you follow the specs, unlike "polite", "assertive" should trigger an announcment in any circumstances if something changes.

**Comment by carolmariaabb** [comment]
Hi, Is there any update regarding this issue? Thanks!

**Comment by sclower** [comment]
No. Behavior in NVDA 2020.3 is unchanged.

**Comment by mezzab** [comment]
Hi,  I have met the same problem.

Is there any plan to change this behavior? 

cc @michaelDCurran @feerrenrut

**Comment by feerrenrut** [comment]
I believe this is an authoring error. The [spec for `aria-live`](https://www.w3.org/TR/wai-aria-1.1/#aria-live) describes this in terms of updates, rather than initial content:
> Indicates that an element will be updated, and describes the types of updates the user agents, assistive technologies, and user can expect from the live region.

NVDA does not announce the initial content until the user intentionally tries to read it. Content that is added "on load" is also considered "initial content". Updates to live regions are reported.

It has been discussed previously: https://github.com/nvaccess/nvda/issues/11410#issuecomment-663285942

The work around of course is to add the aria live element to the initial page, then subsequently add content when you wish it to be announced. All of the initial content of the page is new to the user, why not let them explore / read that content in their own time. 

I'm going to close this issue as invalid.

**Comment by Sebi2020** [comment]
This does not only happen to initial content. But okay.

**Comment by sclower** [comment]
I disagree. If the element is created dynamically, for example a status indicator in response to a user action, the initial text is not read aloud. If JAWS and VoiceOver read the initial text when the element is added to the DOM and NVDA does not, then I believe NVDA’s implementation is in error.

Note: we intentionally avoid use of role=“alert” because of the “alert” message that is prepended to each spoken update

Regardless, thank you for eventually responding to this issue.

**Comment by mezzab** [comment]
Yep, same situation in our team, we avoid the use of role = "alert" because of the spoken "alert" preceding the update. I agree with @sclower .

Also, this behavior is different with other screens readers, like Voice Over or Orca. 

Regardless, thanks for the answer.

**Comment by feerrenrut** [comment]
@mezzab and @sclower Please open a new issue and provide a minimal test case. You need to fill in the details of the template so that there is no (or less) ambiguity about what you are describing. I have responded to the initial test case provided. We view this test case as web author error, since in this test case the aria-live element was created with content via the "on page load" event. Subsequent "updates" to the content of this aria-live element are announced as per the W3C spec.

**Comment by sclower** [comment]
This is still broken in NVDA 2023.1. I am not opening a new ticket as the above is accurate and steps are still reproduceable despite NV Access's opinion.

**Comment by dleetr** [comment]
The misalignment of various assistive tools is a great detriment to many teams and users utilizing them. Users do not care if you adhere to specs - they care that the software presented to them provides a desired effect. If the spec matters so much, then work to change it to align with the current majority ecosystem of assistive tools, so that the expectations on software are aligned with user and developer expectations of consistency.

Please prioritize the experience of users and adopt the behavior as described of other assistive devices as noted their functionality is working from the initial post: `Note: JAWS 17+ and VoiceOver on macOS 10.10+ do speak this text.`. The initially provided steps demonstrate the issue, there is not an error in the way the content has been created.

+1 to reopen this issue and improve the experience of our collective userbases and not have to do workarounds.

**Comment by Sebi2020** [comment]
> The misalignment of various assistive tools is a great detriment to many teams and users utilizing them. Users do not care if you adhere to specs - they care that the software presented to them provides a desired effect. If the spec matters so much, then work to change it to align with the current majority ecosystem of assistive tools, so that the expectations on software are aligned with user and developer expectations.
> 
> Please prioritize the experience of users and adopt the behavior as described of other assistive devices as noted their functionality is working from the initial post: `Note: JAWS 17+ and VoiceOver on macOS 10.10+ do speak this text.`. The initially provided steps demonstrate the issue, there is not an error in the way the content has been created.
> 
> +1 to reopen this issue and improve the experience of our collective userbases and not have to do workarounds.

Sorry, but it should be the other way around. The spec should be changed if a different behavior is appreciated. Specs are there to have a common sense on how things should work. It's the fault of Apple and Freedom Scientific if they don't follow the spec regarding the aria role, not the one of the nvda authors.

**Comment by mdlawler** [comment]
I totally agree with dleetr and disagree with Sebi2020 on this.  If all screen readers are reading this accept for NVDA then guess what users won't care about opinions about the spec, but they will care that the content is not being read.  Developers will test with other screen readers and say that it is working and since NVDA is the only screen reader not reading it that it is the fault of NVDA and again not care about the spec.  I'm not an expert on this spec, but it seems somewhat vague to me anyway.  What we are really deciding here is the goal to be a spec perfect product whatever that means or to give the user the best experience and guess what the latter will win every time!  I believe this should be reopened.

**Comment by Adriani90** [comment]
Just to add a note, in Jaws the virtual cursor of its browse mode is moved to the new content added to the DOM, however I have no idea how Jaws scans the DOM for the new content and moves the virtual cursor there.
The drawback is that the user is loosing the previous position when the virtual cursor is automatically redirected, and this is not desirable actually. Jaws does not provide a key stroke to move virtual cursor back to its initial position. Especially when the newly added content is placed very far away from the initial position of the virtual cursor, the user gets lost.

I think NVDA could provide a feature like a key stroke to move back to the initial virtual cursor position after it has been redirected to the newly added content, but then it needs a storage method for the initial virtual cursor position which is applied whenever the virtual cursor is redirected automatically.
See #14591 for more details. If that one will get reopened, then we can consider reopening this one as well.

**Comment by ramoncorominas** [comment]
> The misalignment of various assistive tools is a great detriment to many teams and users utilizing them. Users do not care if you adhere to specs - they care that the software presented to them provides a desired effect.

That's true, it's sad to see so many AT that fail to meet the spec and provoke discussions on how the AT that do meet the spec should behave without considering the real side effects of such a decission. Live regions are not read on creation for a good reason, because doing so will cause that the screen reader could start to read a lot of unintended content on many situations:

* On page load, any content in live regions will go to the speech queue, altering the expected behavior (read them on update, when the live region content changes in real time).
* In SPAs, whenever a component with a live region is re-inserted in the DOM, all of its content would be read, even if that content is outdated or already read.
* In certain cases of form validation, the content of the corresponding live regions would be read before the user has even interacted with the form itself.

For example, imagine a SPA that has several tabs, one of them including a chat box. Whenever the user switches between tabs, the tabpanel loads the corresponding component, so the chat box with its live region is reinserted in the DOM with all of its existing messages, so they would be read again, instead of only new messages, which is the expected behavior.

> If the spec matters so much, then work to change it to align with the current majority ecosystem of assistive tools, so that the expectations on software are aligned with user and developer expectations.

You can fill a bug to change the spec if you think that the reasons above are not valid. It is not the responsibility of the screen reader to fix bad practices or wrong implementations of live regions. If developers want their live regions to read immediately after creation they can very easily create the live region and update it just after its insertion to force its reading according to the spec.

**Comment by sclower** [comment]
While the rationale for the specification’s behavior is technically sound, it’s important to recognize that end users are not concerned with academic or theoretical correctness—they simply expect their software to work. If all other modern assistive technologies behave in a consistent way and NVDA does not, the perception—fair or not—is that NVDA is at fault, even if it is the only product adhering strictly to the spec. This suggests that the specification, however well-intentioned, may be out of alignment with practical user needs and should be reconsidered.
Unfortunately, changes to specifications are often slow, involving lengthy proposal, review, and adoption cycles—not to mention the additional delays introduced by browser implementation timelines. In the meantime, users are left with a subpar experience, which could potentially be addressed with a relatively small update to NVDA itself to align its behavior with that of other screen readers.
Having worked in this field for over 25 years, I’ve seen firsthand how dismissing user feedback and insisting on technical purity over usability can harm both users and reputations. It’s disappointing that we’re still having this debate after so many years. I hope NV Access will prioritize the real-world impact on users going forward.

**Comment by mdlawler** [comment]
ramoncorominas you are absolutely right, but you are absolutely wrong also.  The perfect cannot be the enemy of the good.  Currently NVDA users just miss out on this information and devs probably are not going to change what they are doing anytime soon.  If this were implemented it could even be done with an option to disable the feature which would allow the documentation to explain it.  Users would be able to then silence the unwanted cases where things that shouldn't be read are now being read which is better than not having notification of the new information in cases where it is now not being read.  Steve and I aren't just advocating for this from some hypothetical place we discussed and considered these type of issues at GW Micro all of the time while working on Window-Eyes.

**Comment by ramoncorominas** [comment]
> While the rationale for the specification’s behavior is technically sound, it’s important to recognize that end users are not concerned with academic or theoretical correctness—they simply expect their software to work.

Your proposal is to go against the spec so end users will have a degraded experience when developers follow the spec, thus penalizing those developers that follow the spec.

As I've already explained, the current specification has strong reasons to ignore live regions when they are just inserted and not updated. I think screen readers, and AT in general, should not promote bad practices, I don't mind if other screen readers are doing it, I think NVDA should not try to "fix" bad code just because others do that, I don't want to create a bad experience when the developers do the right thing.

> If all other modern assistive technologies behave in a consistent way and NVDA does not, the perception—fair or not—is that NVDA is at fault, even if it is the only product adhering strictly to the spec. This suggests that the specification, however well-intentioned, may be out of alignment with practical user needs and should be reconsidered.

What you call "practical user needs" is that NVDA tries to fix bad implementations, at the risk of breaking good implementations. Is this valid for any other accessibility issues? Should NVDA create descriptions for images without an alt? Should NVDA try to determine the label for a form control if there is no  accessible name in the accessibility API? What other bad practices should NVDA promote?

> Unfortunately, changes to specifications are often slow, involving lengthy proposal, review, and adoption cycles—not to mention the additional delays introduced by browser implementation timelines. In the meantime, users are left with a subpar experience, which could potentially be addressed with a relatively small update to NVDA itself to align its behavior with that of other screen readers.

This issue has more than 7 years, just after the publication of ARIA 1.1; version 1.2 was published 2 years ago, if the change is so important and obvious I think it could have been already done. Maybe the problem is that there are strong reasons to not change it.

> Having worked in this field for over 25 years, I’ve seen firsthand how dismissing user feedback and insisting on technical purity over usability can harm both users and reputations. It’s disappointing that we’re still having this debate after so many years. I hope NV Access will prioritize the real-world impact on users going forward.

Having worked in this field for over 20 years, I’ve seen firsthand how dismissing best practices and promoting bad code, because browsers or AT are more or less capable of dealing with it, can harm both users and reputations. It’s disappointing that we’re still having this debate after so many years. I hope NV Access will prioritize the real-world impact on users going forward.

**Comment by mdlawler** [comment]
ramoncorominas it is obvious that we aren't going to agree on this.  You are approaching it from an academic standards based approach and Steve and I are approaching it from real world experience.  You might not know this, but over 30 years ago screen readers did have to guess field names because there were no standards to define them.  Even now Nvaccess is considering AI to perform OCR on unlabeled images.  Would you want to just say that there is no alt attribute so just give up.  It might surprise you that Microsoft currently "guesses" field names for many Win32 applications to provide them with MSAA and UIA.  When a dev creates a resource for the UI in a Win32 app generally they define a static label and then a control, then another static label and another control, and so forth.  Many Win32 apps were written before Microsoft decided to use this method of determining field names so if an app just put controls and statics in random orders in the resource file because it didn't impact how things were visually displayed Microsoft's "guess" would fail.  Clearly Google and Apple doing this in their screen readers for the last 7 years hasn't caused enough problems to have them stop doing it.  Standards aren't perfect and they are never perfectly followed and I'm not just talking about accessibility standards I'm talking about all standards.  Sometimes this happens because they are too vague.  Sometimes it happens because enough users of the standards do it incorrectly that it causes everyone to follow their lead.  We are proposing implementing this and as I said in an earlier comment even add an option for it which would give users what they want and allow Nvaccess to bring attention to this for developers in NVDA documentation and you are proposing to do nothing because it satisfies your pedantic need for standards perfection.  The real world requires flexibility not rigidity and giving the user an option to get or not get this data is a great solution.  As I said if you don't get the data which is currently the case with NVDA you don't even know it is there, but if you do get the data you can easily silence it with a key press if you don't want it because it is wrong or redundant.

**Comment by ramoncorominas** [comment]
@mdlawler @mdlawler  > You are approaching it from an academic standards based approach and Steve and I are approaching it from real world experience.

I am approaching it from my perspective as a web developer for more than 30 years, as an accessibility consultant for more than 20 and as a blind NVDA user for more than 10. I'm tired of dealing with bad code that simply exists because some browsers or tools more or less patch it, so developers have no real incentives to learn. I'm tired of seeing good code that is not properly read or interpreted because the browser or the tools don't adhere to the standard, which in turn promotes a myriad of ugly hacks and strange fixes that perpetuate bad practices and accessibility barriers. I remember the browser wars and the infinite series of hacks that we had to use just because IE or Netscape didn't follow the standards, and I don't want to go back in time to repeat those wars now in the assistive technologies that I use everyday.

Anyway, there are also more technical reasons to avoid it, as you can read for example in [this comment](https://github.com/nvaccess/nvda/issues/14591#issuecomment-1784236314) and in other issues linked from that comment.

> We are proposing implementing this and as I said in an earlier comment even add an option for it which would give users what they want and allow Nvaccess to bring attention to this for developers in NVDA documentation and you are proposing to do nothing because it satisfies your pedantic need for standards perfection.

I am proposing to avoid changing a behavior that is according to the spec, because I assume that good developers will read the spec and develop their content according to that spec. Changing this behavior would penalise well implemented code and might also perpetuate bad practices.

This issue, as it is described for now, is about changing the current behavior, not about adding a new setting to allow users to be notified in those pages that are not properly coded. If that is your proposal then I think you should create a new issue explaining how that setting should work, pros and cons, its default value, possible side effects, how to document it, etc.

I am not absolutely opposed to such an option if it is disabled by default and well documented, including a warning when users enable it, since it can cause a degraded experience in well coded pages.

**Comment by mdlawler** [comment]
Now we are getting to the heart of the issue.  I actually completely understand and agree with what you are saying in an ideal world it would be nice to do what you describe, but we don't operate in an ideal world.  I can't tell you how many times I felt like we couldn't add new features or improve existing ones on Window-Eyes because a new version of the OS or some important program came out with new UI that was exposed in a different way and we had to take time to keep it working rather than being able to move on to new/improved features.  Unfortunately at the end of the day a screen reader's primary job is to present and expose information to the users.  If there is a preponderance of web sites, programs, etc presenting that information in an improper manner then the screen reader has to find a way to deal with that even with the drawbacks you mention above.  The screen reader can explain in its documentation issues like this, but it can't just ignore them because they are wrong.  A screen reader conveys information not just standards compliant information.  We had to actually make these choices all of the time.  For you in your professional life you get to do the right thing and encourage others to do it as well, but in my professional life I had to deal with what was out there and find a way to get that information to the Window-Eyes users even if I wasn't happy about it.  I hope you can see/understand this side of the coin thus my suggestion for an option.  I think this issue has a lot of good content so rather than create another one Steve could modify the description and add a comment to bring the issue into compliance with the current discussion.
