### ISSUE TITLE
NVDA announces the last number of the typed pin on Windows 10 Lockscreen window

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#7908]
If one selects to sign into Windows 10 by typing a pin (instead of typing a password or using a fingerprint), NVDA announces the last number of the pin instead of replacing it with an asterisk (star). This happens regardless of whether or not the typed pin is correct.
This is with Windows 10 Pro 64-Bit, all recent Win 10 releases, and NVDA 2017.4, 2017.3, and 2017.2.
Quite interestingly, this doesn't affect the "Password" option.

**Comment by josephsl** [comment]
CC @MichaelDCurran, requesting slightly above priority consideration as it concerns possible security issue. And yes, I can confirm it myself.

**Comment by josephsl** [comment]
Hi,

Technical: this is because there is no "submit" button when entering a pin, whereas password field does. This means the last character will be spoken, as winlogon will immediately validate the pin as soon as last pin character is entered. This is an unintended side effect from #6017.

To confirm that this is indeed the side effect from keyboard handler changes made recently, can you try with NVDA 2016.4 and 2017.1 and see if NVDA even announces pin entries or asterisks?

Thanks.

**Comment by amirsol81** [comment]
Hi,

Unfortunately testing this with those older NVDA releases will take a
couple of days as modifying my work machine which depends on NVDA is
rather challenging. However, I just tested it with the demo copy of
the latest JAWS 2018 release, and it doesn't exhibit this behavior --
the last number of the pin is properly announced as asterisk.

Cheers.
