### ISSUE TITLE
UIA errors when switching applications in fall creator's update

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#7934]
### Steps to reproduce:

Happens intermittently when switching applications using alt+tab in Win10 fall creator's update.

```sh
ERROR - eventHandler.executeEvent (14:02:00.203):
error executing event: gainFocus on <NVDAObjects.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x07229970> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 147, in executeEvent
  File "eventHandler.pyc", line 162, in doPreGainFocus
  File "NVDAObjects\__init__.pyc", line 290, in objectInForeground
  File "NVDAObjects\__init__.pyc", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 201, in findBestAPIClass
  File "NVDAObjects\UIA\__init__.pyc", line 824, in kwargsFromSuper
COMError: (-2146233083, None, (None, None, None, 0, None))
```

### System configuration:
NVDA version: master-14798,e6292ba9
NVDA Installed or portable: installed
Windows version: windows 10 1709 10.0.16299.192

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
Related to #7982.
Please note the comments provided by @dineshkaushal.

**Comment by Adriani90** [comment]
@Neurrone Does this still happen in Spring creators Update?

**Comment by Qchristensen** [comment]
I've had a report of this from a user running the April update, 17134, where, in certain cases, particularly when the PC is performing an operation, such as copying a folder, pressing ALT+TAB, particularly to another Explorer window results in:

"Input: kb(laptop):alt+tab
DEBUGWARNING - eventHandler.executeEvent (12:40:24.710):
error executing event: gainFocus on <baseObject.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x04E71F90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "appModules\explorer.pyc", line 301, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 961, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 849, in reportFocus
  File "speech.pyc", line 383, in speakObject
  File "speech.pyc", line 275, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1235, in _get_columnNumber
  File "NVDAObjects\UIA\__init__.pyc", line 713, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))"

And the information about the new window is not read.

**Comment by josephsl** [comment]
Hi, which version of NVDA is this – perhaps beta? The reason I ask is because line numbers are different between beta and current alpha builds. For alpha build users, the lines to look at would be from 1244 for NVDAObjects.UIA._get_columnNumber. Thanks.

**Comment by josephsl** [comment]
Hi,

For reference, the log from an alpha build is as follows:

error executing event: gainFocus on <baseObject.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x05546510> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\User\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 231, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\User\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "appModules\explorer.pyc", line 301, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 961, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 849, in reportFocus
  File "speech.pyc", line 383, in speakObject
  File "speech.pyc", line 275, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1245, in _get_columnNumber
  File "NVDAObjects\UIA\__init__.pyc", line 716, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

My guess is that this occurs because the UIA object dies prior to or during the pump cycle. The code in question does the following:

1. The function will first fetch cached element for the current pump cycle.
2. If cached, the cached property is returned.
3. Otherwise, current value is retrieved, and this is where the problem happens.

This code fragment is executed when trying to locate column number for an item in Explorer (it is really a grid), or any time NVDA or add-ons need to query cachable UIA property and somehow it fails - perhaps the element dies (removed from UIA tree), NVDA or something else holds onto a resource that becomes invalid somehow and so on. Fixing this issue requires careful design, as it may lead to regressions if not done carefully, as this function is used in many places.

Thanks.

**Comment by josephsl** [comment]
Hi,

For folks experiencing this problem: can you try this [try build](https://ci.appveyor.com/api/buildjobs/m8ekf13u9oofry6t/artifacts/output%2Fnvda_snapshot_try-uiaCacheableValueCOMErrorHandler-15790%2C0446a430.exe) and see if this helps? If so, then this validates a theory that we're not taking care of COM errors in column/row number/span/count code in NVDAObjects.UIA.UIA object, which may give us one possible route for getting to the heart of the matter.

Thanks.

**Comment by Neurrone** [comment]
@josephsl the try build doesn't help at all to properly read explorer folder list items, nor context switching tab names when under load - the same thing still happens.

**Comment by josephsl** [comment]
Hi, so try/except avenue is out. Thanks for this feedback.

**Comment by feerrenrut** [comment]
> doesn't help at all to properly read explorer folder list items, nor context switching tab names when under load

Hi @Neurrone would you mind testing the [try build](https://ci.appveyor.com/api/buildjobs/m8ekf13u9oofry6t/artifacts/output%2Fnvda_snapshot_try-uiaCacheableValueCOMErrorHandler-15790%2C0446a430.exe) provided by @josephsl again, specifically focusing on the alt+tab behaviour?

If you are still getting errors with that try build, could you paste them into a comment on this issue?

**Comment by Neurrone** [comment]
@feerrenrut ah sorry that my comment yesterday wasn't clearer - the behaviour is identical to a normal build, specifically alt-tabbing it doesn't read properly as well.

**Comment by Neurrone** [comment]
@feerrenrut The errors no longer appear in the log, which I've appended below. Not sure if that means the try build properly catches the error or whether it just means the error didn't happen this time. This debug log corresponds to pressing alt+tab twice, alt+shift+tab then alt+tab again to switch to an open folder in explorer called downloads. There were multiple items in the tab order.

Notice that in the second press to alt+tab, it registers it but just doesn't say anything, and there are no debug warnings/errors. In the next alt+tab, it appears to speak a keyboard layout change (though I am not sure what could have triggered it or whether this could be related somehow).

```
IO - inputCore.InputManager.executeGesture (23:11:29.736):
Input: kb(laptop):alt+tab
IO - speech.speak (23:11:29.848):
Speaking [LangChangeCommand ('en'), u'Downloads  row 1  column 2']
IO - inputCore.InputManager.executeGesture (23:11:30.292):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (23:11:32.845):
Input: kb(laptop):alt+shift+tab
IO - speech.speak (23:11:32.921):
Speaking [LangChangeCommand ('en'), u'English (United States) - US']
IO - speech.speak (23:11:34.075):
Speaking [LangChangeCommand ('en'), u'Downloads  window']
IO - speech.speak (23:11:34.088):
Speaking [LangChangeCommand ('en'), u'Items View  list']
```

**Comment by Neurrone** [comment]
@josephsl hmm, sorry I don't get what you're asking. All my comments are based on running the try build, and the scenario that reliably reproduces these errors for me is starting a large copy operation, then alt tabbing about while its in progress.

**Comment by josephsl** [comment]
Hi, I see. I may have been under the impression that try builds produced mixed results, and the previous report that the bug isn’t fixed may have been due to my assumption that try build wasn’t used. Thanks.

**Comment by Neurrone** [comment]
@josephsl sorry if my feedback was unclear; was really tired when I tested.

So we're all on the same page, I am pretty sure that the try build stops the switching errors from occuring, but it does not solve the UIA related performance problems.

**Comment by josephsl** [comment]
Hi, Got it. Thanks.

**Comment by Adriani90** [comment]
@Neurrone are you still having those errors in NVDA 2019.1.1 under Windows 10 1809 Update?
Regarding UIA performance and other issues, please create individual issues because this makes discussions easier to follow. Thanks!
I am prety sure this errors are not occuring, I am on alpha-17134,363af94b and tried with several synthesizers. If you have these errors though, may I ask which Synthesizer are you using?

**Comment by Neurrone** [comment]
Yup, errors are no longer happening for me. Closing.
