### ISSUE TITLE
IE11: NVDA reads element "edit" when moving by line

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7936]
### Steps to reproduce:
1. Go to [this page](https://www.npr.org/sections/thetwo-way/2018/01/22/579640565/amazons-cashier-less-seattle-grocery-opens-to-the-public).
2. Press 1 to move to next level1 heading.
speech: (main content edit) Amazon's Cashier-Less Seattle Grocery Opens To The Public
3. Press downArrow to move to next line.

### Actual behavior:
speech: (edit) January 22, 2018

### Expected behavior:
speech: January 22, 2018

### System configuration:
NVDA version: 2017.4
NVDA Installed or portable: installed
Name and version of other software in use when reproducing the issue: Internet Explorer11

### Other questions:
Have you tried any other versions of NVDA?
No.

**Comment by feerrenrut** [comment]
By finding the first element on the page that reports as `edit`, then using object navigation to go "up" to the highest level that still reports as "edit" I get the following Devinfo:
```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:02:49.125):
Developer info for navigator object:
name: u'NPR header'
role: ROLE_EDITABLETEXT
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x06F3FA10>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (163, 157, 1352, 68)
value: ''
appModule: <'appModuleHandler' (appName u'iexplore', process ID 11032) at address 6cf5e70>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.16299.15'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 264090
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 6384
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x9e58f04 at 6f29df0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=264090, objectID=None, childID=0
IAccessible accName: u'NPR header'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState:  (0)
IAccessible accDescription: None
IAccessible accValue: None
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'HEADER'
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (13:02:49.157):
oleacc.AccessibleObjectFromEvent with window 198872, objectID 824 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (13:02:49.157):
oleacc.AccessibleObjectFromEvent with window 198872, objectID 825 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (13:02:49.157):
oleacc.AccessibleObjectFromEvent with window 198872, objectID 826 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (13:02:49.165):
oleacc.AccessibleObjectFromEvent with window 198872, objectID 829 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (13:02:49.165):
oleacc.AccessibleObjectFromEvent with window 198872, objectID 830 and childID 0: [Error -2147467259] Unspecified error
```

Looking at the source for this, the element is a `<header>` element. Our guess at what is happening here, is that this element does not have a correct IAccessible implementation in Internet Explorer, and is marking this element (and all child elements) as editable. I think the same is happening in the `<main>` 

The virtual buffer code will need to be updated to mark these elements as not editable. Since this may be likely to continue to happen with other newer HTML elements, we may need to patch all elements except those known to be editable. See `nvdaHelper/vbufBackend/mshtml/mshtml.cpp`

Because of the age of internet explorer and the dwindling support, we recommend that Firefox of Chrome are used instead.

**Comment by Adriani90** [comment]
This works as expected with NVDA 2019.3 Beta 1 and IE11. Closing as works for me.
