### ISSUE TITLE
Outlook prompts that body of message has been changed if NVDA encounters a graphic or embedded Image

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#8038]
Using Outlook 2016, NVDA 2018.1 RC1 will cause Outlook to prompt a user to save changes to a message due to changes  being made to the body of the message. This only occurs when NVDA is running, and only if an embedded image or graphic (for example, as used in a signature, or a separator from an original message) has been reached with the caret.

**Comment by josephsl** [comment]
Hi, confirmed. I’ve been wondering why I’ve been getting that prompt for a while. How about with 2017.3 or 2017.4, and is this specific to Outlook 2016 and can this be observed in 2010 or 2013? Thanks.

**Comment by Brian1Gaff** [comment]
Does Outlook 2016 use Word for its editor still?

I've noticed that word of various vintages does exactly the same even after 
a save, but not always which is irritating.
 Brian

**Comment by leonardder** [comment]
@bramd: Could this somehow be caused by the fix for #6827?

**Comment by dkager** [comment]
@leonardder We also wondered if support for charts in Word and PowerPoint might be the cause.

**Comment by dineshkaushal** [comment]
On my laptop with windows 10 and office 2016, outlook prompts for many messages including github messages and I could not find any embedded object in those messages.

 

This has started only since 2018.1 and I am observing this issue since January build nvda_snapshot_master-14785,1ce1c3e1.

**Comment by michaelDCurran** [comment]
Testing shows it is the call to shape.hasChart in winword.cpp.

As hasChart is only called here in order to then go on and fetch the 
title, I highly suggest we remove this block of code to stop the 
regression. This will mean that NVDA will no longer announce the title 
of a chart when cursoring onto it in Microsoft word, but it will still 
announce as "chart". Switching to browse mode and pressing enter on the 
chart will still activate it and provide full access to the chart, but 
doing this will of course cause the document to look like it has been 
altered. But at least this will not be the case for *all* inline shapes now.

**Comment by dkager** [comment]
Sounds very reasonable, assuming charts can actually be sent to/from Outlook (I expect they can).
