### ISSUE TITLE
Loading NVDA with specific languages shows "Locale not supported by OS" warning message box

### ISSUE THREAD

**Issue by florianionascu7** [nvaccess/nvda#8064]
Hello folks! When changing the language to Kirgyz, NVDA works Properly till the restart. After that, the following error message occurs:

---------------------------
Nvda Warning
---------------------------
Locale 'Kirghiz' not supported by OS.
---------------------------
OK   
---------------------------
Steps to reproduce:
1. Open the NVDA menu.
2. Go to Preferences, General Settings.
3. Choose and select Kirgyz language from the languages list. After the restart, the error I'm talking about occurs.

NVDA version: 2018.1
Operating system: Windows 10 Fall Creators Update 64-bit.
Hope this helps.

**Comment by leonardder** [comment]
cc @josephsl 

This also applies to Mongolian at least.

**Comment by ivnc** [comment]
Also for Galician.
Looks like that's something related with dependencies, as TWBlue shows the same message with Galician.

**Comment by florianionascu7** [comment]
Now I'm confirming what Iván said. Unfortunately, it seems that this is a regression bug.

**Comment by leonardder** [comment]
[**@ivnc**](https://github.com/ivnc) commented on [13 Mar 2018, 21:33 CET](https://github.com/nvaccess/nvda/issues/8064#issuecomment-372808704 "2018-03-13T20:33:27Z - Replied by Github Reply Comments"):
> This issue was pressent in many versions, it didn't appeared with 2018.1.

Are you saying that this problem also occurred in 2017.4 and even earlier?

**Comment by ivnc** [comment]
Yes, you’re right, at least in case of Galician.
As I said, this also happens with all TwBlue versions I've tried.

Regards

**Comment by angaragmn** [comment]
Yes, when using Mongolian local test, it gives exactly that error. I'm wondering when  it is going to be fixed. Still 18.1.1 didn't fix  it yet. :)

**Comment by Qchristensen** [comment]
As noted in linked issue #8080, Macedonian also encounters this error.

I noticed when looking at: https://github.com/nvaccess/nvda/wiki/Translating

That a number of the languages affected (Mongolian, Kyrgyz, Macedonian at least), aren't listed on that page, could that be related, or is it just that the translation list on that page is out of date?

Has anyone found a workaround?

**Comment by michaelDCurran** [comment]
If I understand correctly from quick testing, a part from that warning, NvDA continues to function normally?
I'm guessing that the error is because wx does not have a translation database (wxstd.mo) for these languages.
This means that some standard UI elements won't have translations. E.g. Ok and cancel buttons etc.
Question is though whether we can/should suppress that warning.

**Comment by ivnc** [comment]
I think it isn't related, because as I've said happens also with other Python applications. For example Galician, one of the affected languages, is listed in that page and is a NVDA translation since several years ago (cc @quetzatl).
It could be more related with the size of the language's community. For instance, Galician isn't present in most of big/proprietary-code applications (p.e. JAWS, without going any further). If the app in question is opensource the  probability of being translated into less diffused languages normally increments, but there still are few translated open-source apps compared to other languages. What I want to say is that probably there is one NVDA dependency that supports less languages than NVDA itself. I suppose that something similar may happen, more or less, with the other languages affected by this.

I say this from my elemental NVDA internals knowledge, but this is the option I've in mind that makes more sense for me.

BTW, could the reason why these languages don't appear in the wiki be that it was updated with 2017.3 release? Mongolian was added in 2018.2, Kyrgyz in 2018.1 and Macedonian in 2017.4, according with the changelog.

Regards.

**Comment by josephsl** [comment]
Hi,

This is a wxPython error. When wx.Locale().Init is called and when the locale isn't present, the dialog noted will be shown.

Thanks.

**Comment by michaelDCurran** [comment]
I have a branch with a fix: i8064.

I will submit the pr a little later.

In short though, we can call wx.Locale().IsAvailable, passing 
wxLang.Language to check if wx actually supports this language or not.

**Comment by angaragmn** [comment]
Guys, in 2018.3 rc1,  the famed warning message is still there, showing its ugly head upon us. lol all joking aside, has anyone tested it with the 2018.3 rc1? I have checked all 3 languages that were effected by this, and all 3 are giving same warning messages. "NVDA warning, locale x is not supported by OS." I thought we have fixed this issue. So is it only me? or you guys are getting same errors as well. The 3 languages are, Mongolian, Kirgiz and Galician.

**Comment by ivnc** [comment]
I think the fix corresponds to 2018.4. I tested the pilot build and it is fixed there.

Regards

**Comment by zstanecic** [comment]
Hi,

fixed in the latest alpha snap.

Thanks,

Zvonimir

**Comment by angaragmn** [comment]
Oo I just saw that Michael had added it to the milestone 2018.4 my bad. Thanks guys, Yeah just tested the Alpha snap and it works fine. Once again, thank you guys for responding quickly. :)b

**Comment by florianionascu7** [comment]
I really enjoy that this bug has been fixed.

La 12.09.2018 16:50, angaragmn a scris:

Oo I just saw that Michael had added it to the milestone 2018.4 my bad. Thanks guys, Yeah just tested the Alpha snap and it works fine. Once again, thank you guys for responding quickly. :)b
