### ISSUE TITLE
A complete Paragraph is read in 3 instances by NVDA instead in a single go.

### ISSUE THREAD

**Issue by Raju1saha** [nvaccess/nvda#8067]
### Steps to reproduce:
1.Open Mozilla.
2. hit the below URL
https://sit57.online.citi.com/US/ag/ordercheck/address-review
3. try to read the line using NVDA starting with "Please Note"

### Expected behavior:
> The entire line should be read in one single go as it is under the same paragraph tag

### Actual behavior:
> It is reading in 3 instances on using the Arro key

### System configuration:
NVDA version:
2017.3

NVDA Installed or portable: installed

Windows version:
> Example: Windows 7

**Comment by ehollig** [comment]
I am not able to reproduce this with the latest Master of NVDA and Firefox 58. @Raju1saha, does this still occur with the latest stable release of NVDA 2018.1?

**Comment by Raju1saha** [comment]
Hello Ethan,

Let me give you a background..

Its a paragraph of 3 lines... under <p> <|p>tag.. When i only used down
arrow the entire paragraph got highlighted.. But it reads the line in 3
different instances.. 1/3 every time i hit the down arrow.

Later i used Contrl+ Downarrow and the whole paragraph was highlighted and
read at one go.

Just curious to know what is the reason of the behavior in the first
scenario?
Is that NVDA has some limitations of word or alphabets while reading a big
paragraph or is there any other limitations.

Regards
Raju saha

**Comment by Adriani90** [comment]
@Raju1saha could you please upload another example? The website does not work for me.
In general, if a text paragraph is set under the same paragraph tag, NVDA should be able to read the whole paragraph at once when pressing ctrl+down or up arrow. This is the command for reading paragraphs. When using arrow keys, NVDA tries to interpret how long is a visible line on the screen and reads that line at once. In NVDA settings / browse mode settings you can even adjust the line length by entering a lower or a higher number of characters per line.
At least this is my understanding.
cc: @leonardder, @feerrenrut for a more qualified statement on this.

But from my conclusion, this is not an issue in NVDA, it is actually expected behavior.

**Comment by feerrenrut** [comment]
I think this is expected behaviour. Just using down arrow will essentially read by line, as mentioned the maximum number of characters to read can be configured. `NVDA+down arrow` will say all.  This is described [in the user guide at section 5.3. Navigating with the System Caret](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#SystemCaret)

I don't think there is any default navigation binding for control+down arrow.

**Comment by Adriani90** [comment]
The ctrl+arrow keys I think is not a Default binding in NVDA, however it moves paragraph by paragraph regardless if you run NVDA or not. It seems to be a Standard behavior in Windows.

**Comment by Adriani90** [comment]
I mean ctrl+up and ctrl+down arrow
