### ISSUE TITLE
The latest snapshot for NVDA!

### ISSUE THREAD

**Issue by BEdenhofer** [nvaccess/nvda#8068]
I've recently downloaded the latest snapshot of NVDA, and it launched, and a message comes up saying error registering remote hook, and there's a button that says okay, so I space on it, and everything is fine after that I can reproduce this problem, everytime I reload NVDA!

**Comment by josephsl** [comment]
Hi, isn’t this yet another duplicate of an issue not long ago? Thanks.

**Comment by Brian1Gaff** [comment]
Was not this cured by changing the file bundled with nvda?
 Brian

bglists

**Comment by dkager** [comment]
@BEdenhofer I updated your report to remove the issue template you hadn't used. Please take note of it next time. :)

**Comment by BEdenhofer** [comment]
Okay.

**Comment by tapper82** [comment]
If this is fixed I rec emend this be closed. I cant reproduce  this bug on windows 7 or windows 10.

**Comment by dkager** [comment]
Closing because of a lack of information. If the problem still occurs, please open a new issue and follow the issue template so that we have more information to go by. Also provide a clear issue title that describes the problem. Finally, check to make sure there is not already an open issue that deals with the problem.
