### ISSUE TITLE
Can not change the value of a combo box

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8171]
### Steps to reproduce:
open the donation page to nvacces:
press enter on the button
DONATE NOW
now walk with the arrows down until the combined box to choose the country.
If you press alt + down arrow on chrome the combo box is opened however nvda does not read the values in case the fields to seless.
If you press enter the box opens, however when you press down arrow the country changes, a new page opens and you can not continue to change the countries.
### Expected behavior:
we should be able to select a country in this combo box.

### Actual behavior:
it is not possible to choose the country by pressing enter in the combo box, and also it is not possible to choose the country by pressing alt + arrow below.

### System configuration:
NVDA version:
next 15007
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 10 1803 build 17133.73
Name and version of other software in use when reproducing the issue:
chrome 65 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by ehollig** [comment]
@fernando-jose-silva, where is this combo box? On the [NVAccess Donation page](https://www.nvaccess.org/donate/) I do not see a combo box. I am not able to access the currency converter, but that is probably another issue.

**Comment by fernando-jose-silva** [comment]
You need after the button
SHOW CURRENCY CONVERTER
continue navigating to the next button:
DONATE NOW
open the button:
DONATE NOW
on the new page open navigate to the line:


Donate with a credit or debit card
now navigating with arrow below the next object found is the combo box spoken by me:

**Comment by feerrenrut** [comment]
Thanks, it seems like the currency conversion widget is broken. We'll look into this.

**Comment by Adriani90** [comment]
@feerrenrut this issue is still reproducible as follows in Cghrome 74 and Firefox 66.0.3 with NVDA 2019.1.1:
1. Open the browser
2. Go to NV Access website and open the link "donate"
3. Choose an amount
4. Choose "donate with a card"
5. Press c to go to the country combo box
6. Press enter
7. Press down arrow one or two times without expanding the combo box

Actual: the item is directly fired and the new page loads. NVDA changes to browse mode and you have to go back to access the country combo box again.

Expected: When pressing arrow key in the combo box without expanding it, NVDA should read the items but the focused item should not be activated. Pressing enter should select the item but should not bring you to the next page.

**Comment by feerrenrut** [comment]
The currency conversion tool has been removed, there are plenty of other currency conversion tools online. 

> Pressing enter should select the item but should not bring you to the next page. 

When you change the item in the country combo box, the page is reloaded in the language of that newly selected country. This seems flawed to me, but this page is provided by paypal. The best way to get this fixed would be to notify their support.

I think the current situation is workable, please let me know if I am wrong. I'll close this issue for now.
