### ISSUE TITLE
"Apply" button and accelerator keys in new combined settings dialog.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8249]
In the new combined settings dialog, most options have accelerator keys.  For instance, when the focus is in the Speech category, press `alt+b` for "Beep for capitals" or `alt+p` for "Pitch".  This moves to that setting, and toggles it's value (for checkboxes).

Some of the categories have an option which uses `alt+a`.  "Variant" in the Speech category, or "Automatically start NVDA after I log on to Windows" in General, for instance.  When `alt+a` is pressed in these categories the focus first moves to those settings, but does NOT change them.  This is because the Apply button also uses the accelerator of `alt+a`.  When `alt+a` is pressed a second time (or once on categories without a setting which uses `alt+a`), the focus moves to the Apply button, the button is then activated so any changed settings are saved, and the focus jumps to the Category list (which is intentional behaviour).

This behaviour is not consistent with how other accelerator keys work, and also no feedback is given that the apply button has been activated other than the shift to the category list.

I propose:
1. Provide feedback when the apply button is pressed, which would be useful even when the user presses TAB to move to the button and ENTER to activate it.
1. Changing the accelerator keys for settings which currently use alt+a, to leave this functionality exclusive to the Apply button on this screen.  Most users are more likely to learn this behaviour, than to learn most of the accelerator keys so it would have a greater benefit.

The settings that would need to have their accelerator keys changed are:
* "Automatically start NVDA when I logon to Windows" in General (perhaps use T)
* "Variant" in speech (possibly N)
* "Handle keys from other applications" in Keyboard (Use H)
* "Play a sound when auto-suggestions appear" in Object presentation (Possibly S)
* "Include Layout Tables" in Browse mode (Use L)
* "Alignment" in Document formatting (Perhaps G, since L is already used by several settings here)

**Comment by leonardder** [comment]
[**@Qchristensen**](https://github.com/Qchristensen) commented on [8 mei 2018 08:21 CEST](https://github.com/nvaccess/nvda/issues/8249#issue-321056556 "2018-05-08T06:21:36Z - Replied by Github Reply Comments"):
> 2. Changing the accelerator keys for settings which currently use alt+a, to leave this functionality exclusive to the Apply button on this screen.  Most users are more likely to learn this behaviour, than to learn most of the accelerator keys so it would have a greater benefit.

Hmm, this is problematic due to two reasons. 

1. It relies on the assumption that alt+a is the accelerator for Apply, but this is not the case for every language. In Dutch, Apply is translated to Toepassen, for which the accelerator is alt+t
2. Similarly, if we want consistent behavior, it would be necessary for every locale to:

    + Find the accelerator for Apply
    + Walk through every settings panel with that particular language, changing all accelerators that conflict with the apply accelerator.

I'd rather come up with a documented accelerator that works consistently across languages. Control+s pops into mind.

**Comment by michaelDCurran** [comment]
I'm not sure if we can set an accelerator with control rather than alt.

At least, we can do it manually, but I don't think we can have it show 
up as the keyboard shortcut on the button.

Perhaps for 2018.2 the best thing is to remove the accelerator for Apply 
all together?

We need to decide this one quickly as the translation freeze is rather 
overdue.

**Comment by leonardder** [comment]
Fixed in #8252.b
