### ISSUE TITLE
NVDA portable version will not update

### ISSUE THREAD

**Issue by jcoffin1** [nvaccess/nvda#8265]
NVDA will not update using portible version. Using NVDA Next snapshot.

**Comment by Brian1Gaff** [comment]
Hi I've just updated next snap about 10 seconds ago with no issues. To 
troubleshoot such a problem in some cases and not others, I think it might 
be useful if you tell us what version of windows you are running, what the 
last next snap was which you were running and  exactly what you got step by 
step. IE did it flag up a new version
Did that version download after answering the prompts
Did it run and try to update

Did it then reboot after the update or leave the machine apparently locked 
up?
 This last issue I have seen several times and is due to an error from 
windows blocking the restart due to files on the disc being locked. If you 
wait some seconds before doing ok it then will work, or if stuck in that 
mode, escape then restart the copy from the shortcut.
 If its a very old copy of next you are attempting to update. this could be 
due to the old version of the updater and the changes in the way things are 
done now. I remember reading a post on this some months ago.
 Brian

**Comment by Adriani90** [comment]
@jcoffin1 are you still having this issue in last NVDA versions? I was not able to reproduce it with Beta, Alpha or ful releases in the last time.

**Comment by Adriani90** [comment]
No update since almost 2 years, I am closing this as abandoned and works for me. Please comment on it if you are still having this issue and we can reopen. Thanks.
