### ISSUE TITLE
sysListView32.ListItem._getColumnLocationRaw can return malformed rectangles (i.e. with a left coordinate that is greather than the right coordinate)

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8268]
### Steps to reproduce:
1. Install NVDA Version: next-15126,d5e58ddf
2. Launch Becky! Internet Mail and focus a list of messages.
3. Try to navigate with arrow keys.
### Expected behavior:
NVDA should read list columns such as subject send date and from

### Actual behavior:
An error sound is played. I am attaching a  fragment of the log with specific error.

### System configuration:
NVDA version:
next-15126,d5e58ddf

NVDA Installed or portable:
Installed
Other information:
It is probably caused by #8190. The problematic column seems to be the first column, which contain graphical presentation of the message state read, unread etc. I am also attaching developer info for this column.

Windows version:
Windows 8 x64

Name and version of other software in use when reproducing the issue:
Becky! Internet Mail version 2.74 [en] 
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
Yes next 15121,7fcd6fe7 and it was possible to read this list.
[Issue.zip](https://github.com/nvaccess/nvda/files/2005295/Issue.zip)

**Comment by leonardder** [comment]
This is caused by #7537, which introduces the new locationHelper module. It looks like sysListView32.ListItem._getColumnLocationRaw can return malformed rectangles (i.e. with a left coordinate that is greather than the right coordinate). This really should not be the case for these rectangles. In any case, this code is slightly complex and fixing that as part of #7537 might be quite error prone, so I reverted _getColumnLocationRaw to the stage before locationHelper for now. I think we should leave it as is for now, but we should keep this issue open in order to investigate why _getColumnLocationRaw returns a rectangle that we do not expect.

**Comment by leonardder** [comment]
@lukaszgo1: Could you please try this again with the latest version of next?

**Comment by lukaszgo1** [comment]
@leonardder Latest next fixes it. Thanks.

**Comment by derekriemer** [comment]
should this be closed now?

**Comment by derekriemer** [comment]
never mind, I think not.

**Comment by leonardder** [comment]
Hmm, I was able to reproduce this with Becky. When I use UIA for syslistview32,, the location for the particular column turns out to be different and according to the guidelines.
