### ISSUE TITLE
NVDA does not speak typed characters immediately after starting

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#8460]
The problem is observed in NVDA version 2018.2.1 and earlier. Windows 7 32bit.
Steps to reproduce:
1. Start NVDA, but do not move the system focus.
2. Try typing characters from the keyboard (speak characters should be enable).
3. Expected behavior: NVDA must speak the input characters. Actual behavior: NVDA does not say anything.
4. After moving the system focus (for example, using the tab key), speaking the input characters start to work correctly.

This is particularly annoying in UAC dialogs, when the focus is immediately set in the password entry field.

**Comment by Brian1Gaff** [comment]
Could this be because of something else still loading in the background?
 I have seen this sort of effect caused by this in the past. Indeed even now 
on a system with no password, when windows starts you get unknown spoken, 
then if you wait a few seconds it speaks something sensible and can  then 
work normally. I put this down to dropbox or  the anti virus loaders. Can 
you demonstrate that an earlier nvda does not do this?
 Brian

**Comment by kvark128** [comment]
I have tested and found that the problem appeared in NVDA 2015.4. In NVDA 2015.3 and earlier, speaking the input characters immediately after starting works correctly.

**Comment by Adriani90** [comment]
cc: @leonardder, @michaelDCurran, @jcsteh maybe it is a regression?

**Comment by lukaszgo1** [comment]
Yes, it is. It regressed when 75d5ddffb5b455f7efc58170de1464e2b37f8821 was merged.

**Comment by Adriani90** [comment]
@kvark128 Does this also impact Windows 8.1 or Windows 10 / 11?

**Comment by Adriani90** [comment]
Support for Windows 7 has ended and we didn't hear any updates from the initial author since many years. i am closing as abandoned. If you are still having this issue, please comment and we can reopen.
