### ISSUE TITLE
EditPlus efitor under 2018.2.1 no longer working with NVDA

### ISSUE THREAD

**Issue by DarrylSherwood** [nvaccess/nvda#8461]
Editplus is a great editor that I use quite a lot and this was working just fine with NVDA until the last upgrade. Now speech and reading of characters words lines etc is highly problematic. I will need to downgrade to older version of NVDA until fixed.The version of editplus being used is 3.1 and I think is based on an old VC++ dll. I am happy to provide further details if needed.

**Comment by leonardder** [comment]
This looks like a regression caused by the fix for #8102. I will investigate this further.

**Comment by leonardder** [comment]
Comfirmed that #8102 is the cause. I will therefore mark this as a regression. Note that the edit control implementation for EditPlus might be broken, there is only partial support for it.

Iw as only able to download version 5.0. Is the bahviour with 5.0 identical to the 3.1 behavior?

**Comment by leonardder** [comment]
Could you please try [this](https://ci.appveyor.com/api/buildjobs/5exmsx04uae8xy6u/artifacts/output%2Fnvda_snapshot_try-unidentifiedEditFix-15447%2C5985f417.exe) try build of NVDA and test if the problem persists?

**Comment by DarrylSherwood** [comment]
Hi Leonard,

It is a partial fix. I have upgraded to version 5 of editplus and
downgraded to nvda 2017 and all works fine. With the test binary lines
are now being read correctly and all seems fine moving by word and
character but a problem still persists when set up in word wrap mode.
This works fine under nvda 2017 but not in the test binary.

Cheers
Darryl

**Comment by leonardder** [comment]
[**@DarrylSherwood**](https://github.com/DarrylSherwood) commented on [4 jul. 2018 06:44 CEST](https://github.com/nvaccess/nvda/issues/8461#issuecomment-402361514 "2018-07-04T04:44:14Z - Replied by Github Reply Comments"):
> a problem still persists when set up in word wrap mode.
> This works fine under nvda 2017 but not in the test binary.

Could you please elaborate on what's the culprit here? Is NVDA ignoring word wrap (i.e. does it read the line without taking word wrap into account?)

Note that with NVDA 2018.1 and below, NVDA is using the display model to get the text from the editor's window, it is basically scraping the text from the screen. This works ok in some situations, but goes often wrong when selection gets into scope. EditPlus has a partial implementation for edit controls, that's why NVDA 2018.2 works differently.

**Comment by DarrylSherwood** [comment]
When word wrap mode is on and you move to the second line or further
lines you receive tts from the start of line 1. Moving by word and the
like is fine just line movement being the issue.

**Comment by Adriani90** [comment]
@DarrylSherwood could you please try last NVDA alpha? Is this issue still occuring with that version? You can download the alpha here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
@DarrylSherwood are you still available to test if this issue is still occuring?

**Comment by Adriani90** [comment]
We didn't get any further updates from the initial author. I am closing as abandoned. Please comment if you are still having this issue and we can reopen.
