### ISSUE TITLE
Does not read out div inside iframe when focused on.

### ISSUE THREAD

**Issue by julzelements** [nvaccess/nvda#8507]
### Steps to reproduce:

1. Open IE11 on windows 10
2. Browse to https://nested-iframe-nvda-bug.herokuapp.com/index.html
3. Tab into the page a few times.

### Actual behavior:
When the focus is on myapp-iframe-wrap, NVDA says: "Frame, readme please, button".
When the focus is on 'main-ctn', nothing is spoken.

### Expected behavior:
When the focus is on myapp-iframe-wrap, nothing is spoken.
When the focus is on 'main-ctn' NVDA says: "readme please, button". Or a similar description.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.1.1

#### Windows version:
10.0.16299 Build 16299

#### Name and version of other software in use when reproducing the issue:
Internet Explorer, version: 11.547.16299.0

#### Other information about your system:
It occurs on a native installation and on a VM.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
This works as expected now with NVDA 2020.2 RC1 and IE Version: 11.329.19041.0.
I don't see major differences between browsers. Readme please is read properly when navigating with tab or shift+tab in every browser within the myapp frame.
You defined the focus to be called on myapp frame, and the div ID is Myapp. So NVDA gathers this information and announces the frame label in the div. This is expected behavior.
Why do you expect the readme please button to be announced in the main-ctn? Is this button visually not in the myapp frame?
