### ISSUE TITLE
Change table navigation from ctrl+alt+arrow keys to windows+ctrl+arrow keys

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8542]
### Steps to reproduce:
1. Open NVDA
2. Open MS Excel 2010 or 2013
3. Alternatively, open a pdf document with Images

### Actual behavior:
NVDA does not invoke table Navigation functionality.

### Expected behavior:
This is also expected for any other aplications which use ctrl+alt+arrow keys to turn Screen orientation. This keystroke is a Windows keystroke. As stated by @leonardder and other in #8541, System keystrokes have priority over NVDA keystrokes.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [23 jul. 2018 11:59 CEST](https://github.com/nvaccess/nvda/issues/8542#issue-343566331 "2018-07-23T09:59:22Z - Replied by Github Reply Comments"):
> This keystroke is a Windows keystroke. 

Strictly spoken, this is a key stroke of the Intel Graphics manager.

Control+alt+arrows have been the table navigation key strokes for years and years in both NVDA and JAWS. I don't think that there's a reason to change this, other than solving a conflict with the Intel orientation key strokes. In my opinion, there is a difference between windows key strokes like alt+arrows, control+arrows, etc. and these intel key strokes in this specific situation.

Other thoughts are welcome of course. cc @josephsl, @michaeldcurran

**Comment by k-kolev1985** [comment]
Actually, there is a program built into Windows that also uses Control+Alt+Arrow Keys. And that is the Windows Magnifier. So, the proposition seams valid to me. I often use the Windows Magnifier and this conflict causes me inconveniences.

Using Control+Windows+Arrow Keys however may also lead to conflicts. I don't know if Control+Windows+Arrow Keys is used by Windows at the moment, but it may at some point. Wouldn't it be more safe to use NVDA+Alt+Arrow Keys? Or is this used in some cases by NVDA itself?

**Comment by Andre9642** [comment]
Control+alt+arrows can be done with one hand. in my opinion it's a big advantage...

**Comment by Adriani90** [comment]
@Andre9642, I agree. But then we talk about System keystrokes or keystroke assigned for other parties functions which are overwritten by NVDA. As far as I understand, NVDA should not apply its own custom functions to system assigned keystrokes. But it is actually inevitable for the future because NVDA will Need more keystrokes, especially if magnification Features will be implemented. So, in my opinion the question is rather how likely is that users will Need the System keystroke. If the keystroke is not used at all, I don't see any reason for not assigning NVDA functions to it.
An alternative is to provide king of double NVDA key but this could overwelm new users.

**Comment by Adriani90** [comment]
My Suggestion in a different issue was to integrate text Navigation in the Settings ring and the user can choose between line, paragraph, sentence or table Navigation.

**Comment by josephsl** [comment]
Hi,

Control+Alt+arrows, if not used by NVDA, is used by Intel video card drivers for changing screen orientation (does not work because I have an AMD GPU). Also, ontrol+Windows+left/right arrows are used to switch between virtual desktops in Windows 10.

Thus, I'm closing this for now unless there are really good justificaitons to reopen this. Thanks.

**Comment by DrSooom** [comment]
I just want to note down that it is possible to disable ALT+CTRL+ArrowKeys in the Intel HD Graphics Control Panel. Maybe you need sighted assistance doing for this. But after disabling this, ALT+CTRL+ArrowLeft/ArrowRight will also work as expected in the VLC media player (jump 5 minutes backward/forward).

Closing this issue is correct at this point. But it might be helpful to implement this existing conflict with the Intel Graphics driver in the NVDA's User Guide.

PS: I'm asking me how many user know that this Intel Graphics driver is using ALT+CTRL+ArrowKeys to rotate the display.
