### ISSUE TITLE
Handle selectable checkboxes as list items when speaking selected state

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8554]
cc @dkager

### Steps to reproduce:
1. Open windows disk cleanup by typing cleanmgr in the run window.
2. Select a drive if applicable
3. Use arrow keys and object navigation in the resulting list.

### Actual behavior:
For a focused (selected) item, NVDA says: Downloaded Program Files  check box  selected checked  0 bytes  1 of 10
For an unselected item, NVDA says: Downloaded Program Files  check box  checked  0 bytes  1 of 10

### Expected behavior:
For a focused (selected) item, NVDA says: Downloaded Program Files  check box  checked  0 bytes  1 of 10
For an unselected item, NVDA says: Downloaded Program Files  check box  not selected checked  0 bytes  1 of 10

**Comment by DrSooom** [comment]
There are four possible states for checkboxes in a list:
1. selected and checked
2. unselected and checked
3. selected and unchecked
4. unselected and unchecked
Don't forget that you can move the (focus) cursor in a list (e.g. Windows Explorer, Details View) via the CTRL key as well.

Furthermore please add additional information about NVDA Version and OS because the cleanmgr could be different between Win7 and Win10-1803. Thanks.

**Comment by dkager** [comment]
I would argue that (not) selected applies to the list item as a whole while (un)checked applies to the checkbox.
Trying to generalize this a bit. What this issue seems to say is that "selected" should be the implicit state. That is, NVDA should not announce "selected" but should announce "not selected".

@leonardder two questions:
1. Is this correct?
2. If so, will it work? Or if not, then what did you mean?

**Comment by leonardder** [comment]
[**@dkager**](https://github.com/dkager) commented on [25 jul. 2018 12:44 CEST](https://github.com/nvaccess/nvda/issues/8554#issuecomment-407713042 "2018-07-25T10:44:25Z - Replied by Github Reply Comments"):
> I would argue that (not) selected applies to the list item as a whole while (un)checked applies to the checkbox.

I agree. However, a checkable list item can have only one role, and this happens to be checkbox for disk clean up.

> Trying to generalize this a bit. What this issue seems to say is that "selected" should be the implicit state. That is, NVDA should not announce "selected" but should announce "not selected".

> 
> @leonardder two questions:
> 1. Is this correct?

Yes.

> 2. If so, will it work? Or if not, then what did you mean?

I'd say that it might work, however I'm unsure of whether non list item check boxes could have the selectable state.
