### ISSUE TITLE
On Chrome, NVDA Does Not Handle a Toolbar Inside of a Tab

### ISSUE THREAD

**Issue by MRayermannMSFT** [nvaccess/nvda#8560]
### Steps to reproduce:
1. Open tabs-with-buttons.html (inside attached .zip) in Chrome and Firefox. The file contains 3 tabs, which use the aria roles for tabs. Additionally, inside the elements that have `role="tab"`, there is an `<ul>` that has `role="toolbar"`, with each `<li>` of the unordered list containing an `<img`> that has `<role="button">` and `tabindex=0`. There is only 1 item in each list though, that item being a close button.
2. Use tab to the navigate to the close button on one of the tabs (they occur after the tab control itself is focused)
### Actual behavior:
Firefox, NVDA says:
```
tool bar
Close Button button
```
Chrome, NVDA says nothing.
### Expected behavior:
Chrome says the same thing as Firefox.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.2.1
#### Windows version:
Windows 10, up to date
#### Name and version of other software in use when reproducing the issue:
Chrome, 68.0.3440.75 
Firefox, 61.0.1
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, 2018.1.1

[tabs-with-buttons.zip](https://github.com/nvaccess/nvda/files/2233106/tabs-with-buttons.zip)

PS: I followed this guide to make accessible tabs: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

**Comment by michaelDCurran** [comment]
It looks like Chrome's accessibility implementation is choosing to ignore any children of tabs.
In other words, as far as NVDA can see, the tabs have no toolbars inside them.
In firefox, the toolbars are children of the tabs.

Having said this though, I'm not sure that placing children in tabs is right. At very least, if this is a new kind of UI pattern, then ARIA should be updated to clearly define the behavior.

If you truly believe that this is the right way to do things, I'd suggest you file a bug with Chrome so that they do not drop children of tabs from the accessibility tree.

**Comment by MRayermannMSFT** [comment]
Ok, thanks for the solid analysis @michaelDCurran ! I appreciate the time/effort. 😄 I'll make sure that there's nothing in ARIA that says "don't do this", then I will pursue further action with Chromium.

**Comment by MRayermannMSFT** [comment]
For any future people interested, I didn't find anything in the ARAI spec about this. So here's the bug I opened against chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=868589&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
