### ISSUE TITLE
Positions of items in HTML dropdowns are not read

### ISSUE THREAD

**Issue by MRayermannMSFT** [nvaccess/nvda#8573]
### Steps to reproduce:
1. Create a dropdown in HTML by using `<select>`, example:
```
<body>
  <select role="combobox">
      <option value="Option 1">Option 1</option>
      <option value="Option 2">Option 2</option>
      <option value="Option 3">Option 3</option>
    </select>
</body>
```
2. Focus the dropdown and move through the items, either with our without expanding the dropdown
### Actual behavior:
NVDA simply reads the text of each item.
### Expected behavior:
NVDA not only reads the text of each item, but it should also say what index each item is. So for my example, it might say "Option 2, 2 of 3"
### System configuration:
Windows 10
Chrome
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.2.1
#### Windows version:
10.0.17134 Build 17134
#### Name and version of other software in use when reproducing the issue:
Chrome, 68.0.3440.75
#### Other information about your system:
N/A
### Other questions:
N/A
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No, but I recall this working back in 2017, so if someone has a link to a 2017 version of NVDA I'd like to try it out. 😄

**Comment by michaelDCurran** [comment]
I agree it probably should speak item position when expanded, but not 
when collapsed.

Though I am making an assumption here. Can a sighted person please 
confirm to me that when a select is collapsed, it is impossible to tell 
how many items / what position the current value is at?

**Comment by MRayermannMSFT** [comment]
As a sighed person, unless I am super familiar with a list, I am unable to know the number of items/what position the current value is at. So if y'all want to go with only speaking item position when expanded, I can understand that logic. 👍

**Comment by MRayermannMSFT** [comment]
Hey @michaelDCurran , any thoughts on what version of NVDA this might make it in?

**Comment by Adriani90** [comment]
I think a fix for this issue had to be reverted due to a bug in Chrome itself. However, this verbosity is somehow controverse and it is discussed among several users and developers because actually this information is not really needed for every item. There are many alternatives (i.e. providing a key stroke which reports item position and number of items on demand. See the discussion in #8187.

**Comment by Adriani90** [comment]
In Firefox this works as expected in this issue.

**Comment by Adriani90** [comment]
cc: @SaschaCowley this seems to fail in Chromium, NVDA doesn't even announce the option values at all when arrowing through the combo box in focus mode. In Firefox this works as expected.

cc: @dsexton

**Comment by SaschaCowley** [comment]
This problem is due to the eroneous inclusion of `role="combobox"`. When this is removed, I get the following output in Chrome:

```
document
combo box  Option 1  collapsed
down arrow
Option 2
f4
expanded
list
Option 2  2 of 3
down arrow
Option 3  3 of 3
enter
combo box  Option 3  collapsed
```

With this snippet:

```
data:text/html,<select><option value="Option 1">Option 1</option><option value="Option 2">Option 2</option><option value="Option 3">Option 3</option></select>
```

We could probably work around the behaviour when role is set to combobox, but I'm not sure if it's worthwhile. We can't work around every authoring error. @michaelDCurran, @gerald-hartig, what do you think?

**Comment by MRayermannMSFT** [comment]
@SaschaCowley MDN describes that role as:

> The combobox role identifies an element as an input that controls another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of that input.

I can imagine how a `select` element could be used to control another element. Are we sure using that role on a `select` is eroneous? I will conceed that the example HTML I provided should probably also have a `aria-controls` on the `select`, but I'm not sure if that would make a difference.

**Comment by seanbudd** [comment]
@SaschaCowley - we generally close issues with invalid web authoring. If you're confident it's invalid feel free to close

**Comment by SaschaCowley** [comment]
@MRayermannMSFT the [same MDN article](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role#description) states that:

> A combobox is a composite widget that combines a named input field with a popup providing possible values for that input field. [...]
> The combobox input field can either be a single-line text field that supports editing and typing, similar to a HTML `<input>` with a `<datalist>`, or an element that only displays the current value of the combobox.

I don't see how a `<select>` fits those criteria. In a sense I guess it does, since it is essentially a combobox with "an element that only displays the current value of the combobox", but if that's the case, the ARIA is redundant, and therefore it's best practice not to include it.

Happy to keep this open if there is an actual use case, but I don't see it, to be honest.

**Comment by Adriani90** [comment]
The question is why does it work in Firefox but not in Chromium? I expect bad authoring to fail in both scenarios at least. Maybe @jcsteh has some insights here as well.

**Comment by jcsteh** [comment]
Looks like a Chromium bug to me. [Per the HTML AAM spec](https://w3c.github.io/html-aam/#el-select-combobox), `<select size="1">` (the default size is 1) maps to role combobox. So, while the author should not use redundant ARIA as a general rule, there is no reason for this to fail like this per the spec.

**Comment by SaschaCowley** [comment]
This needs to be filed against Blink then

**Comment by jcsteh** [comment]
@Adriani90, for future reference, if you are tracking a bug in an external project, please be sure to set the correct labels: blocked/needs-external-fix, plus the label associated with the app (app/chrome is the closest match in this case). This just makes it clear that there is no action (beyond tracking) for the NVDA project. Gerald and I have done that in this case. Thanks.

**Comment by Adriani90** [comment]
This is fixed in Chrome 132, closing as works for me.
