### ISSUE TITLE
"Categories" not reported for messages in Outlook

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8603]
Outlook has a "Categories" feature which can be used to mark messages into well, categories.  By default, the category names are colours - red, green. blue etc, but the first time you assign one, you are invited to rename it if you want.  

To mark a message, select it then press the applications key to open the context menu, choose "Categorize" (T), then pick one from the list.

When you navigate through the Inbox, categorized messages have a coloured square as an indicator, however, NVDA does not report anything to indicate that a message has a category.

If you open a message, you can press SHIFT+TAB to move back to the header information and the category is reported there ("Red category", "In-Progress", whatever other names you've given categories, etc).

Expected behaviour would be that NVDA reports any categories (a message can have multiple categories) along with other information when navigating through it in a mail folder.

Using the current version of Outlook 2016 / 365: 1807 build 10325.20082 Click to run, on the latest Windows fast insider 1803, build 17730.1000 and NVDA Version: alpha-15781,d58e1cd4

The behaviour is the same when using NVDA 2018.2.1.

NVDA DOES report "Red flag" when messages are flagged for follow up (that is a different feature of Outlook).

Narrator DOES report categories when navigating.

**Comment by michaelDCurran** [comment]
@qchristensen: please test this try build from pr #8608:
https://ci.appveyor.com/api/buildjobs/q742rlcx323xoo8v/artifacts/output%2Fnvda_snapshot_try-i8603-15806%2C24fe2f47.exe

**Comment by Qchristensen** [comment]
That works, although a couple of things I noticed:

Firstly, when there is a flagged status, it gets read twice:

"Red flag From Quentin, Subject Testing, Received Mon 18/06/2018 10:34 AM, Size 13 KB, Categories Green Category, Flag Status Red Flag,  row 19  column 1  through 12  18 of 18  level 1"

And secondly, when there is no category, and / or flag, it gets reported:
"From Quentin, Subject Re: test, Received Mon 18/06/2018 10:35 AM, Size 13 KB, Categories No Categories, Flag Status Unflagged,  row 18  column 1  through 12  17 of 18  level 1"

My initial assumption would have been that similar to attachments, if there isn't one, it doesn't need to be mentioned at all?

**Comment by michaelDCurran** [comment]
I'm assuming that the announcement of "no categories" or "unflagged" 
also happens with Narrator?

Annoyingly, Microsoft exposes these labels. It would be very hard if not 
impossible to filter out as there is no way to tell the value of "no 
categories" verses a valid category name. That is if we are to support 
all languages.

In regards to the duplication for flagged. That is annoying.

What happens when you rather than setting a red flag, set the completed 
flag (context menu -> follow up -> mark complete). is this duplicated? I 
have a feeling it isn't.

In that case though, that means that we are fetching flagged from the 
object model, but the object model only tells us about some of the 
flags. I'll have to look into this further.

There is a big push for us to move away from the object model all 
together, but this does mean Microsoft fixing up its UI Automation 
support a great deal more.

**Comment by Qchristensen** [comment]
Narrator reads "unflagged" for messages which don't have a flag, but nothing about categories unless a category has been set for a message.

You are right the completed flag isn't duplicated.
