### ISSUE TITLE
Allow disabling easeOfAccess integration with a command line parameter

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#8636]
### Background
Some organisations (particular governmental) have forcefully disabled access to the ease of access center (or utilman.exe) for security reasons. A simple google search on utilman.exe reveals that utilman.exe is quite often abused to circumvent security restrictions.

### Steps to reproduce:
Start or close NVDA with a `--no-ease-of-access` parameter or similar.

### Actual behavior:
Ease of Access center is notified that NVDA is running or not running any more. From [Microsoft's page about EOA registration](https://docs.microsoft.com/en-us/windows/desktop/winauto/ease-of-access---assistive-technology-registration):

> An application notifies the Ease of Access Center by setting a temporary registry key and then injecting the Windows Logo key + U key combination into the input stream.

windows+u triggers utilman.exe, resulting into an error about access rights for utilman.exe

### Expected behavior:
NVDA should not notify the ease of access center. When --no-ease-of-access is provided together with --install or --install-silent, ease of access registration should be avoided.

### Known issues caused by this approach
NVDA will not talk on secure screens if EOA registration doesn't take place.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1

#### Windows version:
Windows Server 2012 R2 in a corporate environment. This environment uses Res One Workspace Manager to lock access to certain parts of the operating system, including utilman.exe

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Brian1Gaff** [comment]
OK one question, does this mean that a copy installed on win 10 with this 
disabled will effectively work like a portable version? If so that on 
windows 10 is quite a problem.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
No, it means that NVDA does not talk at the control+alt+del and other secure screens. But this command line parameter will only be used by system administrators if strictly necessary.

**Comment by leonardder** [comment]
It turns out that restoring the NVDA Service might be desirable for complex work places where utilman.exe has been forcefully disabled. Testing reveals that the service still works great, even under Windows 10. EOA should always be preferred wherever possible, but in practice, using EOA seems to be impossible or is not allowed due to organisation wide security policies. Don't ask me why, but it happens that EOA is just not allowed, whereas running an NVDA specific service on a dedicated server is allowed.

In that case, I propose a "--secure-screens-support" command line parameter that alters the behavior during installation. It should have three possible values:

- eoa (for ease of access)
- svc (for service)
- off (when secure screens support should be left out

Alternatively, we could use the keywords easeOfAccess or service.

@josephsl: Your thoughts are welcome, since you were the one who initiated the removal of the service. Given my thoughts above, I think that the statement that the service is Windows XP specific should be reconsidered.

**Comment by josephsl** [comment]
Hi, reintroducing the NVDA service may also fix a problem where NVDA’s startup registry key is accidentally deleted during update installations. If restoring the service is the way to go, then I recommend modifying the service module so it’ll run happily on Windows 7 SP1 and above. Thanks.

**Comment by leonardder** [comment]
In what way, do you think, should the service module be updated? Note that it already functions quite well as far as I can see.

**Comment by DrSooom** [comment]
@leonardder: [This German article from c't 26/2013](https://heise.de/-2057434) descripte how to replace "utilman.exe" with "cmd.exe" and how to use "cmd.exe" to change the password of an user account on Windows 7 and 8.1.

**Comment by leonardder** [comment]
Now we officially decided to drop our pywin32 dependency, restoring the service is no longer an option really.

**Comment by Adriani90** [comment]
I think though this is still relevant for system admins, and the control pannel is still alive and will continue to be for an unspecified time.
I am reopning.
cc: @seanbudd, @gerald-hartig for triaging.

**Comment by gerald-hartig** [comment]
As of 2024, it appears this issue of utilman.exe abuse is still a problem, although it looks like Microsoft has made steps to address this vulnerability in Win 10/11, eg requiring additional authentication when accessing the Ease of Access features during recovery.

This does not look like an easy fix in NVDA, so to prioritise it correctly we would need to know if a large number of users are confirmed to be affected by this. It's also not great UX if we lose NVDA functionality in secure screens. Has anyone investigated if there are other potential impacts to NVDA if ease of access registration is disabled, for example on UAC prompts?

Apart from blocking utilman.exe, sysadmins have other approaches they can use to secure their machines, including disabling booting from external media in BIOS/UEFI, full disk encryption and ensuring that physical access to the machines is blocked or monitored.
