### ISSUE TITLE
Stop using deprecated wx.yield

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8679]
cc @Josephsl

### Steps to reproduce:
Run NVDA or explicitly call wx.Yield from the python console.

### Actual behavior:
The following is printed in the log:

```
DEBUGWARNING - Python warning (10:03:30.427):
C:\Program Files (x86)\NVDA\library.zip\api.py:274: DeprecationWarning: Yield() is deprecated
```

### Expected behavior:
No deprecation warnings should be raised

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.3 Beta

#### Windows version:
N/a

#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes. This does not happen in 2018.2.1

**Comment by ehollig** [comment]
Possibly related: #8592

**Comment by leonardder** [comment]
@josephsl Is this required for us moving forward to WXPython 4.10?

**Comment by josephsl** [comment]
Hi,

It’s ideal, but I haven’t seen issues with wx.Yield in 4.1.0 snapshots I have (also partly because there is a wx.Locale issue that’s blocking us from moving to 4.1.0). Thanks.

**Comment by josephsl** [comment]
Hi,

Note that wx.YieldIfNeeded may or may not help - changing wx.Yield to wx.YieldIfNeeded in api.py doesn't improve #6800 
Thanks.

**Comment by josephsl** [comment]
Hi,

Looks like wxPython 4.1.0 restores wx.Yield - doesn't record deprecation warning, at least in 4.1.1 alpha (and in 4.1.0 when I tested with Python 3.7.8). I first installed wxPython 4.0.3, then ran Python 3.7.8 with the following switches:

py -3.7 -Werror -Wall

Then:
import wx
app = wx.App()
app.MainLoop()
wx.Yield()
wx.YieldIfNeeded()
Press Control+Z

Repeated the above procedure with wxPython 4.1.0.

Results:

* Deprecation warning printed when calling wx.Yield under wxPython 4.0.3.
* No warning whatsoever when calling wx.Yield in wxPython 4.1.0.

If it turns out wxWidgets people are planning to not deprecate wxYield (C++ counterpart) function, then I suggest closing this issue as wx.Yield will not block migration to 4.1.0. However, there are more serious issues that will block 4.1.0 upgrade, namely locale and slow responsiveness when wx.MessageBox is called.

Thanks.

**Comment by feerrenrut** [comment]
@josephsl Could you see if you can get some confirmation of that? It would be nice to know for sure if it will be deprecated. On the other hand, if there is an easy way to get rid of wx.Yield used in NVDA then that would be a good thing in itself.

**Comment by josephsl** [comment]
Hi,

It was documented as deprecated in 3.0.5 but it is actually not (wxWidgets commit 7851535d023fc45b08030157ce13866eb0b9d6cf, later tagged as part of v3.1.0 removed deprecation flag). This means wx.Yield will not block us from moving to wxPython 4.1.0, although it would be nice to find a more updated alternative.

Closing.

Thanks.
