### ISSUE TITLE
Settings: Move Audio Preferences into their own Category

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#8711]
During use, NVDA plays several sounds that are useful to users - however, these are currently spread across several sections of the Settings dialog. To make things easier for users, could we possibly consider moving these into one central location? If we did this, the following would need to be moved - this also includes volume settings:

Play sounds when starting or exiting NVDA

Output Device

Audio Ducking Mode

Volume

Beep for capitals

Beep if typing lowercase letters when caps lock is on

Play sound for spelling errors while typing

Play audio coordinates when mouse moves

Brightness controls audio coordinates volume (I was thinking that this could be left in the Mouse section because this would make more sense to leave it under this category)

Play a sound when auto-suggestions appear

Audio indication of focus and browse modes

**Comment by bhavyashah** [comment]
I quite like this suggestion. I can certainly imagine a new user arduously combing through all the NVDA settings categories in search of that one option to toggle a certain sound on or off. A few thoughts below:
* I propose calling this category "Sound" as opposed to "Audio." This is because the latter, at least to me, seems to cover speech synthesis too, whereas this settings category is specifically devoted to sound effects and audio cues. While speech synthesis is technically an instance of sound, the term 'sound' gives me more of an impression of sound effects, i.e. beeps and music, rather than synthetic speech.
* I don't think the Volume slider should be moved from Voice Settings to Sound Settings. This is because this option only affects the volume of the speech synthesizer , and is even part of the Synth Settings Ring along with other options in Voice Settins, so is better placed as is.
* Apart from the comprehensive list of options given in the ticket, I would mention the Progress bar output combo box from the Object Presentation Settings as well. Similar to the Audio indication of focus and browse modes check box, this option allows for toggling the reporting of progress bar updates between beeps, speech, both, or none.

**Comment by dawidpieper** [comment]
Considering #11006 , does it make sense to create such a PR, or would it be closed?

**Comment by feerrenrut** [comment]
@dawidpieper For now please refrain from working on stuff like this. Instead, please take a look at any of the stale PR's and see if you can help to progress them. Once we have them out of the way will accept new PR's

**Comment by CyrilleB79** [comment]
With #15472, Output device and Audio Ducking mode have been moved to a new audio settings panel.

Regarding all the remaining mentioned items, I am reluctant to move them. They are all tied to an event and the sound is the way this event is reported. I feel more intuitive to configure what should be done when the event occurs in the setting panel dedicated to this event rather than moving the parameter in the audio settings panel just because a sound may be the answer to this event.

For example:
* There are three options controlling how capitals are read char by char. "Beep for capitals" would land in "Audio" but the two other options (raise pitch and say cap) would remain in voice settings. I prefer to be able to configure how capitals are read at the same place.
* Same for progress bars: if we split the option "Report progress bars with beeps" in "Audio settings" and "Report progress bars with speech" in Obj presentation settings (or in Speech settings?), I feel it's more confusing. It's clearer to configure in Obj presentation settings how progress bar are reported, no matter the way they are reported.
* Same for indent reporting in Doc formatting settings; this option has not even been mentioned in this issue.
* What is reported when mouse move should remain in the mouse panel, no matter if it's reported through speech or other audio sounds.

At last, if an option to report objects roles and/or states through sounds (earcons) instead of speech is implemented in the future, I would expect that enabling or disabling this feature be configured in object presentation panel.

So I vote to close this issue.

@seanbudd, @michaelDCurran, given the recent creation of the audio settings panel, could you share NV Access opinion on this issue?

**Comment by seanbudd** [comment]
Agreed.

We don't intend to move the other options for those reasons

Closed by #15472
