### ISSUE TITLE
synthesizer settings are no longer available

### ISSUE THREAD

**Issue by vortex7463** [nvaccess/nvda#8721]
1. I have followed  the instructions in this new article . in order to add another voice to window 10 , (asaf/hebrew), that will work with NVDA . in my own language.

THE ARTICLE :
    https://support.office.com/en-us/article/download-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130

2.  then I have changed the settings to "Windows OneCore voices" see screen shot
http://prntscr.com/kqz3rp .
 
3. it  didn't work at all , the hebrew voice didn't work , so I have tried to reverse the settings back to this: 
http://prntscr.com/kqz67p (Nuance Vocalizer) , but the second I pressed O.K , NVDA shuts-down and restart , with the settings as before , it doesn't allow me to reverse settings any more,

what can I do?
thank you:)

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by feerrenrut** [comment]
This issue is quite old. @vortex7463 Sorry that you didn't get any assistance here and if you are still experiencing the issue please leave a comment. A log file from NVDA would help a lot to determine what is going wrong. Since so much time has passed without a comment we can only assume the issue no longer occurs, I'll close this for now and re-open if we get more information.
