### ISSUE TITLE
NVDA reads extra information after selecting any list item from Combo box.

### ISSUE THREAD

**Issue by mvaibhav96** [nvaccess/nvda#8764]
### System configuration: Windows 10 64bit, 
[1220152_External sample.zip](https://github.com/nvaccess/nvda/files/2396075/1220152_External.sample.zip)
12GB ram

**Comment by Adriani90** [comment]
This is also reproducible in Firefox 71 with NVDA 2019.3 Beta 1.
At every down arrow press in the combo box, when the combo box updates, the page title is reported everytime by NVDA.
cc: @jcsteh any idea why this happens in Firefox?

**Comment by jcsteh** [comment]
When an option is selected, the combo box is hidden as per the Javascript code in this test case, so it loses focus. Something always has to be focused, so focus goes to the document. Since the document gets focus, the name of the document (its title) is read. This is behaving exactly as expected. The problem is due to authoring error. If you don't want the title of the document to be read, you need to avoid messing with focus.
