### ISSUE TITLE
Emojis Do Not Speak when Arrowing by Character

### ISSUE THREAD

**Issue by jage9** [nvaccess/nvda#8782]
### Steps to reproduce:
Note: These steps apply when running NVDA Master 16003 with pull request #8758 included, which reads unicode emoji characters.

1. Open Notepad
2. Insert an Emoji such as 🌮 which is the taco symbol.
3. Arrow over the emoji by character.
You can also arrow over the taco emoji above to observe the same results. Using the up and down arrow keys reads it correctly.
I'm not sure if some emojis are represented by two characters, especially in browse mode.
### Actual behavior:
NVDA does not speak anything when landing on an emoji character, which is the same behavior as before Master 16003.

### Expected behavior:
The emoji character should be spoken.

#### NVDA Installed/portable/running from source:
installed

#### NVDA version:
NVDA Master 16003, 

#### Windows version:
1803

#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
Eloquence speech.

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
n/a, based off recent PR

**Comment by leonardder** [comment]
@jcsteh: I recall you said something about Python 3 making it easier to fix this, but I'm not yet sure why or how.
Interestingly, moving by word in notepad reads the emojis just fine.

**Comment by jcsteh** [comment]
My comment regarding Python 3 was related to handling of repeated emoji; i.e. 🌮🌮🌮🌮 being reported as 4 taco. That is a valid issue, but separate from this one.

As for the issue at hand, it's complicated. :) These Emoji are 32 bit Unicode characters,  so they consume two UTF-16 code units. How this gets handled depends on the underlying text implementation. For example, if you try this in Wordpad, it does work because we ask ITextDocument for its idea of a character and it does account for UTF-16 encoding. It doesn't work in Notepad because Notepad is a standard Edit control and we use our OffsetsTextInfo implementation for that.

I wrote a fix for this in OffsetsTextInfo 2 years ago. It's in the offsetsUnicodeBeyond16 branch in my fork. I didn't ship it because I have concerns it might affect performance (since it has to fetch text when calculating characters) and I never found the time to test it extensively. In practical terms, it should be fine - it's only fetching one character and that should be fairly fast - but it should be tested with various controls to be sure. This should fix Edit controls like Notepad, as well as NVDA virtual buffers.

Note that there is a further complication, which is that some Emoji are actually multiple Unicode code points; e.g. 🤦‍♂️ consists of the characters person facepalming, zero width joiner, male sign, Variation Selector-16. Even Wordpad doesn't seem to get this right. Right arrow skips over the whole combined character, but ITextDocument only returns the first character (🤦).

My branch does not fix this second issue for OffsetsTextInfo. This could be fixed for OffsetsTextInfo by retrieving several characters before and after (ideally in one call) and then looking for zero width joiner and Variation Selector-16 code points to determine the boundaries. Alternatively (and perhaps better), we should be able to use Uniscribe for this, just as we do for word offsets. It looks like the [SCRIPT_LOGATTR](https://docs.microsoft.com/en-us/windows/desktop/api/usp10/ns-usp10-tag_script_logattr) data returned by [ScriptBreak](https://docs.microsoft.com/en-us/windows/desktop/api/usp10/nf-usp10-scriptbreak) has an fCharStop attribute as well as the fWordStop attribute we already use for words. See `_getWordOffsets` in source/textInfos/offsets.py and `calculateWordOffsets` in nvdaHelper/local/textUtils.cpp. Note that the word calculation code takes a whole line of text. I'm hoping we don't have to use a whole line for characters (maybe just, say, 6 chars before and 6 after?), as calculating a line might be expensive in some implementations and moving by character needs to be really snappy.

I don't think we can fix this for ITextDocument or any other non-offset implementation.

**Comment by jage9** [comment]
Thanks for the fix. When arrowing in FF, the first character reads the emoji while the second reads right paren. I assume this is expected behavior based on the comments in the PR?
