### ISSUE TITLE
Nvda stops reading the items inside folders.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8825]
### Steps to reproduce:
my machine is configured as follows:
The file explorer is configured to open in the My Computer item.
The items inside the file explorer are organized in grid form, where I get to the items also navigating with right and left arrows.
To reproduce the error I make:
I open the file explorer, and then immediately press the right arrows, barely wait for the nvda to announce that the file explorer item is open already press the right arrows.
### Actual behavior:
nvda no longer read an item inside the file explorer, it reads again if I take focus from the file explorer window and put it back.
### Expected behavior:
nvda should not stop reading the items inside the file explorer.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
16149
#### Windows version:
10 17763.1
#### Other information about your system:
If I wait a few seconds after opening the file explorer, everything works fine.
The point is that I must be doing something wrong by not waiting for the file explorer or nvda to be ready to read the window.
However I believe that nvda should recover from user anxiety and should read the items normally from the file explorer when everything is available.
In this case the speed of the machine is very relevant, so I'll put my pc configuration:
notebook
Processor:
Intel (R) Core (TM) i3-6100U CPU @ 2.30GHz 2.30 GHz
Installed memory (RAM):
4.00 GB (usable: 3.89 GB)

I do not have dedicated video card.
I have a ssd of 128gb, and a memory card fixed on the computer almost all the time.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes
log:
[file.txt](https://github.com/nvaccess/nvda/files/2453583/file.txt)

**Comment by Brian1Gaff** [comment]
This is very similar to an effect I see with web browsers. If I try to do 
anything too fast, only opening a menu, or switching away and back brings 
back content.
 My take on this is that nvda is missing some info it needs due to delay or 
user action.
 Its nothing that new, and can happen randomly.

I, like you feel its a bottleneck in hardware, as I also find, for example, 
that when updating nvda, and it does a restart, it can fail with an error 
unable to access log file. which of course you cannot tell is there as nvda 
is not running.
 It seems windows take a lot of time closing the file and releasing the name 
and renaming the file to old.

I too have an SSD, and I've not seem as much of these issues on old 
fashioned  drive machines.
 Counter intuitive, but nonetheless it happens.
 Be interesting to look at an nvda debug  log around the time of your 
problem. Its hard on my windows 7 machine as of course Firefox or whatever 
seems to max out the core nvda is running in, and the other error is when 
nvda is trying to start. In your case it might be easier to see what is 
going on.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-

**Comment by Adriani90** [comment]
@fernando-jose-silva do you still have this issue in NVDA 2020.1 with addons disabled?

**Comment by fernando-jose-silva** [comment]
I don't have this problem anymore, thanks.

**Comment by Adriani90** [comment]
Thanks for reporting, closing as works for me.
