### ISSUE TITLE
After dialog has been closed and focus has been returned, NVDA announcing text before focused element.

### ISSUE THREAD

**Issue by ogregames** [nvaccess/nvda#8828]
After dialog has been closed and focus has been returned NVDA announcing some text before focused element and only after this announced text for element that receive a focus.

### Steps to reproduce:
1) Go to: www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html
2) Open inspect elements
3) Dublicate node "Add Delivery Address" several times
4) Open dialog by click "Add Delivery Address" button
5) Close dialog by "Cancel" button
### Actual behavior:
After close dialog focus will be return to button "Add Delivery Address". (Same to the button that open dialog). But NVDA will announced Add Delivery Address button several times. 
Same behavior will be if before button we placed some text - after focus returned this text will be read before button.
### Expected behavior:
NVDA must announced only element that had been received focus.
### System configuration:
Window 10
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.2.1
#### Windows version:
Window 10
#### Name and version of other software in use when reproducing the issue:
Firefox ESR
#### Does the issue still occur after restarting your PC?
yes, and at other computer too
#### Have you tried any other versions of NVDA?
2018.3.1

<a href="https://ibb.co/cfMUpU"><img src="https://preview.ibb.co/fdqdip/git.png" alt="git" border="0"></a>
<a href="https://ibb.co/np9FUU"><img src="https://preview.ibb.co/cv17b9/git2.png" alt="git2" border="0"></a>

**Comment by ehollig** [comment]
This is because you have you have screen layout turned on. When exiting the modal, it is announcing the buttons "Add Delivery Address" as they are on the same line. Try turning screen layout off by pressing NVDA+V.
When I go to the above address and perform the steps suggested above with screen layout off, everything works as expected. When I escape from the modal using escape, it reads the trigger that opened it.
Closing this issue.
