### ISSUE TITLE
Letters shown as numbers on screen when using braille display Orbit Reader 20 in Portuguese Grade 1

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#8862]
### Steps to reproduce:
1. Connect braille display Orbit Reader 20 to computer using a USB cable.
2. Configure NVDA to recognize the braille display (Preferences > Settings > Braille).
3. Configure NVDA for input and output braille tables in Portuguese, Grade 1.
4. Open Notepad and type a b c d e f g h i j using the braille display.

### Actual behavior:
The letters output correctly on the braille display, but on screen, the letters are output as numbers (ex: 1 2 3 4 5 6 7 8 9 0).

### Expected behavior:
The letters should output as letters on both the braille display and on screen in Notepad.

### System configuration:
Windows 10

#### NVDA Installed/portable/running from source:
NVDA Installed

#### NVDA version:
NVDA 2018.3.2

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Notepad (latest version with Windows 10)

#### Other information about your system:
-  NVDA is being used in Brazilian Portuguese.
- This does **not** happen in Portuguese Grade 2 nor Portuguese 8-dot computer braille, so I think it's a specific problem with the Portuguese Grade 1 input table.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, it was also a problem in NVDA version 2018.2.

**Comment by Brian1Gaff** [comment]
That would mean the display driver software is not converting things correctly going back to the computer, surely?
Brian



bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- Original Message ----- 
  From: Cristina Stoll 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Sunday, October 21, 2018 2:11 PM
  Subject: [nvaccess/nvda] Letters shown as numbers in when using braille display Orbit Reader 20 in Portuguese Grade 1 (#8862)


  Steps to reproduce:
    1.. Connect braille display Orbit Reader 20 to computer using a USB cable. 
    2.. Configure NVDA to recognize the braille display (Preferences > Settings > Braille). 
    3.. Configure NVDA for input and output braille tables in Portuguese, Grade 1. 
    4.. Open Notepad and type a b c d e f g h i j using the braille display. 
  Actual behavior:
  The letters output correctly on the braille display, but on screen, the letters are output as numbers (ex: 1 2 3 4 5 6 7 8 9 0).

  Expected behavior:
  The letters should output as letters on both the braille display and on screen in Notepad.

  System configuration:
  Windows 10

  NVDA Installed/portable/running from source:
  NVDA Installed

  NVDA version:
  NVDA 2018.3.2

  Windows version:
  Windows 10

  Name and version of other software in use when reproducing the issue:
  Notepad (latest version with Windows 10)

  Other information about your system:
    a.. NVDA is being used in Brazilian Portuguese. 
    b.. This does not happen in Portuguese Grade 2, so I think it's a specific problem with the Portuguese Grade 1 input table. 
  Does the issue still occur after restarting your PC?
  Yes

  Have you tried any other versions of NVDA?
  Yes, it was also a problem in NVDA version 2018.2.

**Comment by dkager** [comment]
My first guess was a problem in the Portuguese Grade 1 braille table from liblouis, but the table looks fine to me.
Could you post a comment where you describe which dots you type on the braille display, what comes out on the display and what you see on screen (and what your speech synthesizer announces)?

**Comment by xtstoll** [comment]
@dkager - For example...

Braille display = dot 1 (which is a)
Screen = 1
Audio = 1

Braille display = dots 1 and 2 (which is b)
Screen = 2
Audio = 2

Braille display = dots 1 and 4 (which is c)
Screen = 3
Audio = 3

etc. etc. etc.

**Comment by xtstoll** [comment]
@dkager I just looked at the [latinLetterDef6Dots.uti table](https://github.com/liblouis/liblouis/blob/master/tables/latinLetterDef6Dots.uti) which is the reference for these letters, and I don't see any problem. The weird thing is this does not happen with TalkBack or VoiceOver, but it does with NVDA. 

I'm going to reach out to another blind person here in Brazil that has an Orbit Reader 20 to see if this is happening with her as well.

**Comment by ruifontes** [comment]
Hello!

The Braille portuguese authority is working, near LibLouis, to correct 
that and other problems...

Best regards,

Rui Fontes
NVDA portuguese team


Às 02:46 de 25/10/2018, Cristina Stoll escreveu:

**Comment by dkager** [comment]
Thanks for your feedback. What happens when you write 1 2 3 using the keyboard on your PC? I tried this with the Portugese Grade 1 table and the numbers got a number sign in front of them, so they don't look like letters. This makes me think that if you enter numbers they will not come out as regular letters or vice versa, even if you enter them through a braille display. I bet I'm missing something super obvious here. :)

**Comment by xtstoll** [comment]
@marlon-sousa Hey, Marlon! Here's a friendly reminder to help out with this Portuguese / NVDA / Orbit 20 issue. Thanks! <3

**Comment by Adriani90** [comment]
@ruifontes any updates on this? Have the input translation problems hbeen fixed meanwhile?
@xtstoll can you still reproduce the issue in NVDA 2023.1?

**Comment by ruifontes** [comment]
I can't confirm with Orbit, but with my HT Braille Basic Plus it works as expected...

**Comment by xtstoll** [comment]
Sorry, I do not have access to an Orbit 20 anymore to test.

**Comment by Adriani90** [comment]
Given we don't have a way to test this, I am closing as abandoned. if someone has this issue and can provide test results, please comment and we can reopen.
