### ISSUE TITLE
NVDA virtual buffer doesn't fuly load text files in Google Chrome

### ISSUE THREAD

**Issue by michal-dziwisz** [nvaccess/nvda#8863]
### Steps to reproduce:
In Google Chrome press CTRL+o and open text file, may be the attached one.
### Actual behavior:
Nvda loads only portion of file, in atached example 9503 from 11398 characters
### Expected behavior:
Nvda loads all file content to the buffer
#### NVDA Installed/portable/running from source:
Instaled
#### NVDA version:
NVDA 2018.3.2
#### Windows version:
Windows 7 Pro X64
#### Name and version of other software in use when reproducing the issue:
Google Chrome 70.0.3538.67 oficial version ) X64
#### Other information about your system:
I tested the problem on other brovser named Basilisk, and on that browser problem doesn't appear.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
no
[rtv39.txt](https://github.com/nvaccess/nvda/files/2499321/rtv39.txt)

**Comment by Adriani90** [comment]
Is this an NVDA issue? Actually it look liek rather a chrome issue.
cc: @leonardder

**Comment by Adriani90** [comment]
It is working as expected in NVDA 2020.1 and Chrome 81. Chrome loads 11334 characters, the same like in Firefox, Edge Chromium or Internet explorer. In MS Word 11399 characters are loaded, in Wordpad there are 11335 characters loaded, in Notepad and Notepad++ 11398. So it is very likely due to some ISO characters not being recognized by browsers and thus they are not rendered at all. This should be reported to browser developers, if this is important for an user.
Closing as invalid.
