### ISSUE TITLE
Firefox Web Console does not read Javascript Objects in Quantum

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#8876]
### Steps to reproduce:

[Here is a video of me demonstrating this issue](https://youtu.be/2_YUL2WHFuE)

1. Open a page on Firefox Quantum
2. press F12 to open the web console (If web console is not announced, press escape until it is announced)
3. In the edit box type:

    obj = {a: 1, b: 2}

Then hit enter. You will hear the object announced with all its properties.
4. Type obj and hit enter. You will hear the properties read out again.
5. Get out of input mode and arrow up to the console output. The last section of that output says:

    obj
    log
    tree view clickable

### Actual behavior:

The console says:

    obj
    log
    tree view clickable

### Expected behavior:

I need the console to tell me all the attributes of the object. It should say:

    obj
    log
    {a: 1, b: 2}

This is the behavior in the old version of firefox.

#### NVDA Installed/portable/running from source:

NVDA is installed

#### NVDA version:

NVDA 2018.3.2

#### Windows version:

Windows 10 64 Bit.

#### Name and version of other software in use when reproducing the issue:

Firefox 60.2.2esr (32-bit)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

No

**Comment by DrSooom** [comment]
CC: @michaelDCurran, @MarcoZehe and @jcsteh

**Comment by PratikP1** [comment]
In the latest nightly of FF 65, I get the following output
> snippets.js:320:8
> Log
> obj = {a: 1, b: 2, c: 3}
> Log
>  
> Log
> obj
> Log

**Comment by frastlin** [comment]
was that first log from you pressing enter from obj? or from you defining obj?
I wish there was an easy way to test Firefox Nightly while still keeping my stable version.

**Comment by PratikP1** [comment]
Testing it again, you’re right. The first log is from defining the object. I’m wondering, however, whether the same information is supplied to all. In other words, is this a NVDA issue or a Firefox issue? I have nightly and the regular release of Firefox installed on this machine. I’m  running both of them without a problem.

**Comment by jcsteh** [comment]
It's (at least partially) a Firefox issue. Objects are displayed in a tree view for easier inspection. This is a very small object, but an object could easily be hundreds of lines long. However, that tree view is not currently keyboard navigable. That's covered by [Mozilla bug 1424159](https://bugzilla.mozilla.org/show_bug.cgi?id=1424159).

Even once that's fixed, there's an open question as to what should show up in browse mode. Generally, tree views don't show anything in browse mode; you have to interact with them to get anything. This is because they are complex controls; there's no clear answer as to what item in the tree should be read in browse mode. That is a change that will need to be made in NVDA.

**Comment by Neurrone** [comment]
I like the idea of just the existence of the tree view being reported in browse mode, and don't mind having to interact with it to see its contents. Some objects could be really large, and clutter the browse mode display otherwise.

**Comment by PratikP1** [comment]
I agree with @Neurrone in that having the ability to interact with the tree view from the browse mode is perfectly fine. I want to see how NVDA behaves once we're actually able to navigate the tree view. Currently, the tree view is reported. But due to the bug that @jcsteh pointed out above, no interaction is possible.

**Comment by Adriani90** [comment]
This is solved since Firefox 67. I also agree that interacting with tree views first in order to hear the elements in it is fine. Note that you could also have hierarchies displayed as part of a tree view and it is not possible to give all that information on one key press in a virtual buffer. This is the same like a dialog element. NVDA reports "dialog" and if you interact with it you get the dialog title and all the other stuff in it. If we force the virtual buffer to bundle all the information in such a tree view or a dialog on one key press, we would run into significant performance issues.

I close this issue as works for me. Please comment on it if you have other arguments and we can reopen it.

**Comment by frastlin** [comment]
There is currently no way that I am aware of to copy the object, or hear how the property is spelled. I need to have access to the spelling of the property names. So despite this fix, I'm still selecting all and copying and pasting the console to a text file.

**Comment by jcsteh** [comment]
If you press report current navigator object twice (desktop: NVDA+numpad5, laptop: NVDA+shift+o), it will spell the current tree item. If you press it thrice, it will copy to clipboard. You can also copy the entire message to the clipboard using the context menu.
