### ISSUE TITLE
Impossible to find download link for NVDA 2017.3 on nvAcces website.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8884]
### Steps to reproduce:
1. open nvaccess.org
2. Click on download.
3. Try to find download link for 2017.3 to be able to use NVDA on Windows XP, Vista or 7 without SP1.
### Actual behavior:
No link for version 2017.3
### Expected behavior:
the file should be available for download like it used to.
#### NVDA Installed/portable/running from source:
N/A
#### NVDA version:
N/A
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
nvAccess website
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
N/A

**Comment by DrSooom** [comment]
Download-Link to NVDA 2017.3: https://www.nvaccess.org/download/?nvdaVersion=2017.3

Sadly https://www.nvaccess.org/files/nvda/releases/ is forbidden (error 403).

**Comment by lukaszgo1** [comment]
@DrSooom thanks, I am not saying, that i am unable to find it. I am just pointing out, that the link should be available on the website.

**Comment by DrSooom** [comment]
Yep, that would be very nice. A list of all releases and a direct link to NVDA 2017.3 for XP/Vista users.

@michaelDCurran: Could you please add a .htaccess file with the following content into the folder I mentioned above and link to this folder on the download page?
> Options +Indexes

**Comment by Brian1Gaff** [comment]
Yes I suggested this should be there some months ago, and also suggested 
that any  add ons that work on it should also be made available in a frozen 
archive as well. The same issue is already coming up due to wx4, and soon no 
doubt python 3 as well. Somebody needs to look at an old versions section to 
the web site, as it will fulfil a need and as it will be static, then it 
should not be a drain on resources, it only needs to be done the once.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by DrSooom** [comment]
The list of all released NVDA Beta, RC and Stable versions from 0.5 (2008-03-26) to 2014.4 (2014-11-27) is available [here at SourceForge.net](https://sourceforge.net/projects/nvda/files/releases/). Sadly it seems that there is no such an easy to access list of all releases since the beginning of 2015.

Adding the minimum OS version and the release date nearby the version on the [download site](https://www.nvaccess.org/download/ – as well as a link to NVDA 2017.3 for XP users – would be nice too – as partly mentioned before.

Well, and the latest Alpha, Beta and RC builds of NVDA (without the Stable ones) can be find [here](https://www.nvaccess.org/files/nvda/snapshots/).

**Comment by Qchristensen** [comment]
As you know, when 2017.4 came out, we had a link to 2017.3 on the download page for XP users.  When we updated the site, it was a simple oversight - I think actually that even though the new site didn't go live until later, that page might have been written before we dropped XP support.  We've only had a few requests for an XP compatible version, and I wonder how many "new" users still use XP?  I know we have some dedicated XP years who have been with us for awhile, but most people in that situation already have the program...

**Comment by lukaszgo1** [comment]
It isn't only about XP users. It is also about, still used in some institutions, Vista, and W7 without  SP1. The last scenario is pretty common someone install W7 from the dvd that he/she bought when Win 7 came out and until someone sighted install SP1 for him he has no access to the computer at all.

**Comment by DrSooom** [comment]
@Qchristensen: This isn't really the point in my opinion. As NVDA is open source, all released versions of it (RCs and Stables) should be easy to access through the download page. Furthermore those files are still on the webserver like [NVDA 2015.1](https://www.nvaccess.org/files/nvda/releases/2015.1/nvda_2015.1.exe). But you have to know the correct link to it, otherwise you aren't able to find the desired installer at the moment.

**Comment by Adriani90** [comment]
@lukaszgo1, @DrSooom, there is the website filehorse where all NVDA versions back until NVDA 2009.1 can be downloaded:
https://www.filehorse.com/download-nvda/old-versions/

But yes, comon practice for open source projects is also that all stable version are available on their websites. See i.e. VLC player.

**Comment by feerrenrut** [comment]
I believe it is quite purposeful that we do not list old versions of NVDA. We (currently) don't do long service releases, and would prefer everyone to be using the latest version.

**Comment by lukaszgo1** [comment]
In general I agree. 2017.3 is however a special case, as it is the last version to support older versions of Windows.

**Comment by feerrenrut** [comment]
Yes, I should have been explicit about that. There will probably be a point in the future where we remove this link however.

**Comment by lukaszgo1** [comment]
> 
> 
> Yes, I should have been explicit about that. There will probably be a point in the future where we remove this link however.


I am afraid I do not understand. This issue was created exactly because the link isn't there, and now you are talking about removing it in the future.

**Comment by feerrenrut** [comment]
As @Qchristensen mentioned, the link was was unintentionally removed and we will replace it. However, at this stage that build is already 2 years old. At some point we will have to consider whether it is sensible to continue to recommend people use it. We will probably keep the (soon to be replaced) link on our website until a serious issue makes that build unattractive to recommend to XP users.

**Comment by lukaszgo1** [comment]
Thanks, having  the link fixed would be nice indeed. As I said above XP users aren't only for whom having it would be beneficial. I've created this issue after discussion with blind friend of mine who reinstalled Windows 7 on her relative computer only to find out that the image which she used had no SP1 and therefore needing and failing to find last compatible with it version of NVDA on the website.

**Comment by DrSooom** [comment]
@feerrenrut: Recommendation isn't the point here, as NVDA is open-source. I totally agree that the normal users should also use the latest stable version of NVDA, but there are other reasons, why an older stable version is temporarily needed, e.g. investigating bugs, updating Windows or just running older Windows versions in a VM for historical reasons or just for fun.

Therefore in my opinion Issue #10023 is required – of course not as recommendation. Well, I guess I will have to set up a "mirror server" to do this instead of you – later this year –, sadly. 😞

**Comment by XLTechie** [comment]
@feerrenrut Is that position really consistent with the position of not wanting 
to publish a list of when NVDA will not support certain OSes, because we can't 
control how long people will be required to use them? On the one hand we're 
saying that we won't say how long we'll support an OS, but on the other hand 
we're saying that unless you are on a recent build of Windows 10, we won't 
support you, and so we want to make it difficult for you, by design, to find the 
version of NVDA you need, in order to "encourage" you to upgrade your OS.

By not providing links to download past versions, unlike most open source 
projects which do, and adding in your comments above, you are effectively saying 
that you don't want to support people who have to use old versions because that 
is what Windows they have. For example, in this case, Vista. Or XP.

Now, of course as a rule, who would want anyone to use such old software (soon 
to include Windows 7), but some people don't have a choice.

My understanding is that there are still corporate networks, especially in the 
UK such as the NHS, that are using XP in some places.
If those users want to use NVDA, shouldn't we make it easy for them? Heck, if I 
want to use NVDA on my old Vista machine that I must maintain because of drivers 
for some external hardware I must use, why should NV Access make that hard for 
me by burying their older releases?

And shouldn't we make it easy for people writing add-ons, to be able to find and 
install those older versions to test against?

Recently a contributor here asked me to test something against 2018.4. It took 
me more than a half an hour to dig that out of google, and when I did, I had to 
settle for 2018.4RC1, rather than waste more time with it.

I question the reasonableness of this policy. It seems like protectionism. Why 
do you think we can still download much older versions of Python, and just about 
every other tool or resource NVDA relies upon, from the original manufacturer's 
site, and easily? Because it's open source. We aren't here to "stop" users from 
doing stupid things. We provide the recommended version, but providing older 
unsupported versions, with a proper disclaimer like everyone else does, is not 
saying by any means that we want people to use them. It's only saying that we 
are open to everyone possible using our software, and being able to get it 
without difficulty.

**Comment by DrSooom** [comment]
I posted this comment in issue #8884 as well as in issue #10023, in the hope that it helps somebody finding certain Stable, RC and Beta versions of NVDA. You only have to change the NVDA version once or twice in the following URLs.
+ Download page with parameter:
  + 2017.3 Stable: https://www.nvaccess.org/download/?nvdaVersion=2017.3
  + 2019.1 Stable: https://www.nvaccess.org/download/?nvdaVersion=2019.1
  + 2019.1.1 Stable: https://www.nvaccess.org/download/?nvdaVersion=2019.1.1
  + 2019.1 RC1: https://www.nvaccess.org/download/?nvdaVersion=2019.1rc1
  + 2019.1 Beta 1: https://www.nvaccess.org/download/?nvdaVersion=2019.1beta1
+ Direct links to the exe files:
  + 2017.3 Stable: https://www.nvaccess.org/files/nvda/releases/2017.3/nvda_2017.3.exe
  + 2019.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1/nvda_2019.1.exe
  + 2019.1.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1.1/nvda_2019.1.1.exe
  + 2019.1 RC1: https://www.nvaccess.org/files/nvda/releases/2019.1rc1/nvda_2019.1rc1.exe
  + 2019.1 Beta 1: https://www.nvaccess.org/files/nvda/releases/2019.1beta1/nvda_2019.1beta1.exe
+ Direct links to the html changelog files:
  + 2017.3 Stable: https://www.nvaccess.org/files/nvda/releases/2017.3/nvda_2017.3_changes.html
  + 2019.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1/nvda_2019.1_changes.html
  + 2019.1.1 Stable: https://www.nvaccess.org/files/nvda/releases/2019.1.1/nvda_2019.1.1_changes.html
  + 2019.1 RC1: https://www.nvaccess.org/files/nvda/releases/2019.1rc1/nvda_2019.1rc1_changes.html
  + 2019.1 Beta 1: https://www.nvaccess.org/files/nvda/releases/2019.1beta1/nvda_2019.1beta1_changes.html
+ Directories:
  + Stable/RC/Beta: https://www.nvaccess.org/files/nvda/releases/
    Note: This public directory is currently forbidden (error 403). You can download files, which are stored in this directory, but you must know their complete path. Therefore a list of all Stable, RC and Beta versions including their release dates and file sizes isn't accessible yet. This can be easily fixed by adding a .htaccess file with the content "Options +Indexes" in that directory on the NV Access web server.
  + Stable/RC/Beta until 2014.4: https://sourceforge.net/projects/nvda/files/releases/
    Note: This page lists all Stable, RC and Beta versions from 0.5 (2008-03-26) to 2014.4 (2014-11-27) including their release dates and html changelog files.
  + Latest Alpha/Beta/RC snapshots: https://www.nvaccess.org/files/nvda/snapshots/
    Note: This page lists plenty of the latest Alpha, Beta and RC snapshots including their release dates and provides direct download links. Previous versions are removed from this page from time to time.

**Comment by Adriani90** [comment]
I am closing this one in favor of #10023.

**Comment by lukaszgo1** [comment]
It isn't a duplicate of #10023 because it talks about a specific version for which link should be present separately from older builds. It should be reopened.

**Comment by Adriani90** [comment]
But if an alternative website will be implemented anytime in the future as proposed in #10023, then the 2017.3 version wil be present there. Is there any strong argument for having this on NV Access website although that version is not supported by NV Access anymore? My understanding of dropping support is that the entity which drops support does also not officially offer that version on their website. This is valid for any software. Staff which is not supported is migrated to an alternative website unless you still intend to promote it.

**Comment by Adriani90** [comment]
by the way, I didn't close this as duplicate but in favor of the referenced issue above.

**Comment by DrSooom** [comment]
> My understanding of dropping support is that the entity which drops support does also not officially offer that version on their website. This is valid for any software. Staff which is not supported is migrated to an alternative website unless you still intend to promote it.

I totally disagree with this regarding open-source software. Please give us some examples.

You are so focusing on support and support and support that you're unable to see the negative aspects of maintaining two totally different websites. And as I wrote multiple times – which you ignored all the time – previous versions of NVDA are stored on the NV Access's web server right NOW! A new website as well as a domain, which costs additional money, isn't necessary and useful at all. Most of the required files are already there – on NV Access' web server.

**Comment by lukaszgo1** [comment]
If the newest version of my software doesn't support particular operating system, and if I care about my users still using it in the other words if I don't want them to hunt for the old version on the internet just because I can I should make it as easy as possible to find it. In the case of a screen reader it is even more important. We as a blind people should be as independent as we can, so the situation in which I for instance want to install Windows 7, and then install SP1 but I cannon because I haven't archived needed version of NVDA installer is simply not acceptable. While I believe that #10023 is badly needed, I am realistic and know that it woulld take some time to implement. To solve this issue it would be sufficient to add on the download web page something  like:
> If you need to use NVDA on Windows XP, Vista, or Windows 7 without SP1 click here.

Regarding dropping support and availability of older version in case of incompatibility with older OS's an example of developer that done this right might be AutoIt https://www.autoitscript.com/site/autoit/downloads/ On this page you can download older builds for Windows version older thhan 2000, which is simply great.

**Comment by Adriani90** [comment]
Ok I see your point. I am reopening this discussion and will let the decision for this issue as well as for #10023 up to @feerrenrut, @Qchristensen and @michaelDCurran.

**Comment by lukaszgo1** [comment]
The link is present now. Thanks to whoever did this. Closing.

**Comment by DrSooom** [comment]
Quote from the [download page](https://www.nvaccess.org/download/): (The link "NVDA 2017.3 for Windows XP" refers directly to https://www.nvaccess.org/download/nvda/releases/2017.3/nvda_2017.3.exe.)
> Please note: NVDA is only available for PCs running Microsoft Windows 7 SP1 and later. If you require a version of NVDA that can still run on Windows XP or Vista, please download the much older NVDA 2017.3 for Windows XP instead. NV Access does not however recommend or support running this older version on newer Operating systems.

PS: I only wrote this post here to complete this topic. And I also saved the current download page via the Wayback Machine [here](https://web.archive.org/web/20190905224738/https://www.nvaccess.org/download/).

**Comment by feerrenrut** [comment]
Links to all (well, at least 2012.2) releases can be found via the [release posts on the NV Access website](https://www.nvaccess.org/category/news/releases/). There is also now a "Releases" link to these posts in the footer of the NV Access website under "Useful links"

**Comment by DrSooom** [comment]
@feerrenrut: Thanks a lot for adding and providing this page. Sadly it doesn't contain all stable releases back to 2012.2 and also no beta and RC versions. It would be grateful if you could take a look at all posts and check their categories. Thanks.

**Comment by michaelDCurran** [comment]
In some cases, a release post has been changed to be the post for its 
latest point release. For example 2018.3 was renamed to 2018.3.1 and 
then 2018.3.2. However, From what I can tell, every major release is 
represented on that page, even if it is by its latest point release.

In the cases where a release was replaced by a point release, it was due 
to  severe crashes or freezes. There is really no need to list a release 
that was quickly replaced by a stability fix.

As for betas and rcs: I could move these into the releases category as 
well I guess...

But let's point out here that it is very easy for someone to quickly 
work out the url scheme to get any release, even if it is not listed on 
that page.

It is always of the form: 
https://www.nvaccess.org/download?nvdaVersion=<version>


Fiddling with this release archive is in deed taking up a bit of my time 
and I think it is not of the highest priority, especially due to the 
fact people can get the releases if they know the url scheme.

**Comment by XLTechie** [comment]
Michael Curran wrote:

> As for betas and rcs: I could move these into the releases category as
> well I guess...

As someone who ardently supported making all released copies available directly 
through an NV Access controlled website, I have to say that personally I'm not 
really sure why betas and RCs, especially betas, need to be available in this 
way at all. What is the use case for doing something with a beta after its 
release is distributed? Aren't betas intended to be temporary by their nature?

  > But let's point out here that it is very easy for someone to quickly
> work out the url scheme to get any release, even if it is not listed on
> that page.

Is that so for betas? I.E. can someone actually be able to anticipate a beta's 
filename without much research?
For that matter, isn't it somewhat difficult to even know that there was a 
particular beta or RC, once some time has past?

Just asking out of curiosity, as I still don't see the point in betas or 
RCs being available, though I could easily be missing something.

**Comment by feerrenrut** [comment]
More information about beta's and RC releases (which are closely aligned with developer interests) is available through the [github releases page for NVDA](https://github.com/nvaccess/nvda/releases).

But there are very few use cases I can imagine where it would be required to download these at some distant point in the future rather than the subsequent (and often almost entirely equal) full release.

**Comment by DrSooom** [comment]
> In some cases, a release post has been changed to be the post for its latest point release.

I didn't recognize this, but you're right. I checked that out with the stored RSS feed entries in Mozilla Thunderbird for a few posts right now. This condition only applies to [2018.2/2018.2.1](https://www.nvaccess.org/post/nvda-2018-2-available-for-download/), [2018.3/2018.3.1/2018.3.2](https://www.nvaccess.org/post/announcing-the-release-of-nvda-2018-3/) and [2018.4/2018.4.1](https://www.nvaccess.org/post/nvda-2018-4-now-available/).

> However, From what I can tell, every major release is represented on that page, even if it is by its latest point release.

Challenge accepted. 2012.2.1, 2012.3.1 and 2013.1.1 are missing. Here are the links to the announcements of [2012.2](https://www.nvaccess.org/post/nvda2012-2released/), [2012.3](https://www.nvaccess.org/post/nvda-2012-3released/) and [2013.1](https://www.nvaccess.org/post/announcing-the-release-of-nvda-2013-1/). I of course checked out the how [news category](https://www.nvaccess.org/category/news/). Therefore I'm not able to claim that there aren't also posts for these three point releases, as the article links in the very old RSS feed entries no longer work – in the meantime they are now redirecting to the NVDA GitHub site.

> As for betas and rcs: I could move these into the releases category as well I guess...

Okay, including them into the "releases" category could lead into some misunderstandings. Perhaps a new category called "testing releases" or so in the near future could help here. I wouldn't call it "beta" because this category also includes Release Candidates, which aren't Betas.

> Is that so for betas? I.E. can someone actually be able to anticipate a beta's filename without much research?

Yep, just add "beta1" or "rc1" directly after the version, e.g. [2019.2.1beta1](https://www.nvaccess.org/download/?nvdaVersion=2019.2.1beta1) instead of [2019.2.1](https://www.nvaccess.org/download/?nvdaVersion=2019.2.1). And if you try to download [2019.2.1beta2](https://www.nvaccess.org/download/?nvdaVersion=2019.2.1beta2), which doesn't exist, a 404 error will appear after pressing the "DOWNLOAD" button.

**Comment by feerrenrut** [comment]
> 2012.2.1, 2012.3.1 and 2013.1.1 are missing.

Known issue. There is almost certainly no need for someone to use these very old releases, we now have a system that will work going forward, and coverage backwards for 6-7 years worth of development. This is already covers most needs, and not worth spending more time on.

> As for betas and rcs: I could move these into the releases category as well I guess...

I don't think we should do this. The only useful time for the betas and RC's is during the lead up to a release. - They are typically not useful when trying to isolate when an issue was introduced, since there is often very few changes made during this process. Releases for low granularity and source copies for high granularity are much more appropriate.
- They would never be the most recent version to support X. We purposefully drop support early in a release cycle so that there is time to deal with subsequent consequences. 

Again, we have a solution going forward, and the main use cases are covered. Our time could be used to impact many more people if spent in other ways.
