### ISSUE TITLE
can not open a button that contains submenu in chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8890]
### Steps to reproduce:

using chrome open this page:
https://downloads.quickbooks.com/app/qbdt/products
Now locate the button with submenu
Select Country
Press enter in an attempt to open the submenu.
Press alt + down arrow also to try to open the submenu.

### Actual behavior:
The nvda is with the auto brouse mode disabled.
Nothing happens.
### Expected behavior:
The submenu should open by pressing enter or alt down arrow.
This works in firefox.
If I put the nvda in focus mode you can press enter and change the options.

#### NVDA Installed/portable/running from source:
install
#### NVDA version:
alfa 16188
#### Windows version:
10 17763.55
#### Name and version of other software in use when reproducing the issue:
chrome 70
### Other questions:
The problem is that the nvda in this control is not activating focus mode by pressing enter or alt + down 
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by ehollig** [comment]
I was able to expand this option by pressing alt+down arrow twice in Chrome. It does not respond to enter or space. Below is the code reference for the button in question.
```<button type="button" class="action-button no-connector ha-input" id="ha-select-target-4" aria-expanded="false" aria-haspopup="true" aria-label="QuickBooks Desktop">
<span class="label">QuickBooks Desktop</span>
</button>
```

**Comment by Adriani90** [comment]
cc: @derekriemer

**Comment by ObjectInSpace** [comment]
The code sample for this didn't work in Chrome or Firefox. When I wend to the website provided, NVDA announced "expanded" when I pressed enter and space, however focus mode was not activated. Thus pressing down arrow closes the popup menu as focus moves away from it. This behavior is the same in Chrome and Firefox.

IMO the best solution here is for NVDA to activate focus mode when the menu is expanded, so arrow keys change the selection of the menu. Alternatively, focus could remain in the popup for the purposes of reviewing options before making a selection. In that case, the menu should be kept open during browse mode.

**Comment by Adriani90** [comment]
This issue occurs only in browse mode. This works as expected if the option "automatically set focus to focusable elements" is turned off via nvda+8.
Other wise the list will colapse due to focus being moved from the list.
What happens here is following:
* When pressing enter on the button submenu, a list appears at the bottom of the page. Probably the focusevent on the button is fired after the list has been opened, so the focus remains on the button. This might be a web autoring issue. More exactly, the virtual cursor in the virtual buffer is not redirected to the list. So the system focus is not moved either since it follows the virtual cursor. Because the system focus stays at the position of the virtual cursor, NVDA does not switch to focus mode automatically and the list is colapsed when pressing down arrow in browse mode.
@ObjectInSpace I think this issue could be solved from Chrome side by defining where the virtual cursor in the virtual buffer should be redirected via IAccessible2. But I don't know if this is really possible in a consistent way. I guess this needs to be solved by the autor of the website case by case.
Ideally in this case, the virtual cursor should be redirected to the bottom of the page where the list is, so that NVDA can switch to focus mode.
Note that this also occurs in Firefox, the virtual cursor is not redirected to the list at the bottom of the page when expanding the button.
I think this is somehow also related to #11133 which does not redirect the focus to menu item when expanding the submenu in browse mode in Google drive. Please see #11133 for a more technical explanation on the underlying issue. I am closing this in favor of that issue.
