### ISSUE TITLE
MS Teams: NVDA focus does not go on "Call" button in browse mode

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#8952]
### Steps to reproduce:
1. Open NVDA and launch MS Teams app.
2. Navigate to the "Chat" Appbar element and press Enter to activate it.
3. Navigate to Call button in browse mode.
4. Verify the issue.

### Actual behavior:
NVDA focus does not go on "Call" button in browse mode.

### Expected behavior:
NVDA Focus should go on "Call" button in browse mode.

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
2018.2.1

#### Windows version:
Win10 1809

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment]
@HarishTerala I am not sure if I can replicate the issue you are having. When I open MS Teams and activate a chat conversation, I am able to tab, or shift tab to the video call button and the audio call button. Many updates to the MS Teams desktop app has been made since this issue was created, is this still an issue?

**Comment by HarishTerala** [comment]
@ehollig - Issues still repro's. 

We can reach Video and Audio call buttons using Tab key. But when browse mode is enabled and upon pressing down arrow key on 'Video call" button focus does not moves to "Audio call" button, here NVDA skips these controls and moves to "Conversation" tab. Also using up arrow key NVDA skips "Audio call" button and focus moves to "Video call" button.

**Test environment:**
Platform: Win32
Application: MS Teams
NVDA version: 2019.1

**Comment by Adriani90** [comment]
Thank you for reporting back @HarishTerala.

**Comment by ehollig** [comment]
Hello HarishTerala. This could be because you have screen layout turned on. This setting is turned on by default, and reads items if they appear visually on the same line.
In MS Teams, Video call, Audio call, Start sharing your screen, Add people are all read out at once.
Try turning off screen layout by pressing NVDA+V when in browse mode, or unchecking the box for Use Screen Layout in the browse mode settings to see if this resolves your issue.

**Comment by Adriani90** [comment]
@HarishTerala see the comment above by @ehollig
