### ISSUE TITLE
Somali is not recognized on Windows 7 in NVDA language list.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8984]
### Steps to reproduce:
1. Start NVDA on Windows 7.
2. Open general settings with NVDA_CTRL+G.
3. Look for Somali on the list of languages.
### Actual behavior:
There is entry named so, but not somali.
### Expected behavior:
The entry for Somali should be present.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.4 beta 2

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
N/A
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?

No

**Comment by josephsl** [comment]
Hi, and we need to do something about the Somali nvda.po, as the one we had was a result of multiple copies squeezed into one file. I’ll correct these two issues via a pull request on master branch unless people need this fix very urgently (and no, Somali won’t be listed in what’s new section because it does not meet 70 percent translation threshold to trigger Subversion to Git transfer via CommitBot).
