### ISSUE TITLE
NVDA not reading in IE 11

### ISSUE THREAD

**Issue by samsaida** [nvaccess/nvda#9010]
### Steps to reproduce:
NVDA not reading following in IE11.

`<div tabindex="-1" id="abc"><span title="abc efg">efg</span></div>`

### Actual behavior:
In other browsers such as Firefox and Chrome, NVDA reads "abc efg" (span title) on focusing the div. But in IE, NVDA says 'grouping' while moving the focus from one div to another.

### Expected behavior:
In IE, NVDA should read "abc efg" once while focusing the div.
#### NVDA version:
2018.3.2

#### Windows version:
Windows 10 Version 1709

#### Does the issue still occur after restarting your PC?
Yes

**Comment by Adriani90** [comment]
This is broken in Firefox and Google Chrome as well now. In IE it seems all divs are reported togehter (EFG).

**Comment by Adriani90** [comment]
In edge Chromium is broken as well.

**Comment by Adriani90** [comment]
CC: @jcsteh at least for Firefox

**Comment by jcsteh** [comment]
This usage is incorrect authoring. The accessible name (which is how the title attribute is exposed in this case) is intentionally not rendered in browse mode for spans which have content, since this would cause the content of spans to be overridden in a lot of cases where it shouldn't. See [my blog post](https://www.jantrid.net/2015/12/woe-aria-surprisingly-but-ridiculously.html) for an in-depth discussion of this.
