### ISSUE TITLE
NVDA does not pick up the long desc in Google Chrome

### ISSUE THREAD

**Issue by TanjaKleut** [nvaccess/nvda#9049]
Hello,

the long desc is not retrieved by NVDA in Google Chrome.
NVDA Version: 2018.4rc1
Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)
See the example https://www.w3resource.com/html/attributes/example-longdesc-img.html
The graphic has "w3resource logo" as alternative text and "This is a demo of longdesc" as long desc attribute
In Chrome NVDA does not pick up the long description and if I press ins+d it says "no long description".
The workaround to read the long description on Chrome is to install the extention for long descriptions https://chrome.google.com/webstore/detail/long-descriptions-in-cont/ohbmencljkleiedahijfkagnmmhbilgp but then it is not retrieved by NVDA, but by the browser.
I can get the long desc in Firefox 64.0.

**Comment by Adriani90** [comment]
This is a browser issue. Longdesc atribute is not supported in Chrome natively, see this source:
https://www.w3.org/WAI/tutorials/images/complex/#a-text-link-to-the-long-description-adjacent-to-the-image

A workaround is to use the link to the long description in a ```<br>``` snippet or better in a ```<figure role=group>``` with a ```<figcaption>```. See approach 1 under this link. The workaround with role=group would be also compatible in older browser versions and in nearly every browser out there.
I am closing this issue since it is not related to NVDA.

**Comment by Adriani90** [comment]
cc: @aleventhal just for your reference, supporting longdesc natively in Chrome would be a great feature, especially for people who are using complex websites with many diagrams and data charts with NVDA or any other screen reader.
