### ISSUE TITLE
Firefox crashes in Google Groups message area

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9072]
### Steps to reproduce:
1. Go to a google group
2. Compose a new message
3. After entering something into the subject field, start typing/arrowing in the message field.

### Actual behavior:
Firefox crashes. [Here](https://crash-stats.mozilla.com/report/index/bp-935e66c8-f95b-484a-a21e-1b42b0181214) is a crash report.

### Expected behavior:
Firefox does not crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4RC2

#### Windows version:
Windows 10 1809 (OS Build 18298.1000), insider preview

#### Name and version of other software in use when reproducing the issue:
Firefox 64 x64

#### Does the issue still occur after restarting your PC?
Not yet tested

#### Have you tried any other versions of NVDA?
Yes, latest Alpha and 2018.3.2 also suffer from this. With 2016.4 as portable copy which I had floating around somewhere, the issue did not occur.

cc @jcsteh @MarcoZehe: a quick look at the crash reports indicates that this is NVDA related.

**Comment by leonardder** [comment]
@amirsol81: as you reported #8442, have you also suffered from this lately?

cc @derekriemer

**Comment by MarcoZehe** [comment]
I've seen these crashes, too, in build 18290, not yet in 18298. This seems to be something in the UIAutomation code that gets injected into Firefox by Microsoft. Since they also go in-process, if they crash, Firefox crashes. NVDA doesn't use UIA for Firefox AFAIK, but something causes Microsoft to want to deal with Firefox on the UIA level, too. Firefox does, however, not support UIA.

**Comment by amirsol81** [comment]
Yes. In fact, I just checked again and the issue persists. It can be 
reliably duplicated.

This is with Chrome 71.0.3578.98 (Official Build) (64-bit) and NVDA 
2018.4 RC2.

**Comment by jcsteh** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1511649 which @MarcoZehe filed. The crash stacks look quite different, but the fact that these crashes only occur in Insider builds seems unlikely to be a coincidence.

@leonardder: May I have your permission to privately forward your Firefox crash dump to Microsoft? (I can retrieve the crash dump from Mozilla, so you don't need to do anything, but I need your permission before sending it anywhere else.)

**Comment by leonardder** [comment]
> @leonardder: May I have your permission to privately forward your Firefox crash dump to Microsoft? (I can retrieve the crash dump from Mozilla, so you don't need to do anything, but I need your permission before sending it anywhere else.)

Sure, go ahead!

**Comment by zahra21** [comment]
hello. i believe that firefox quantum versions are very instable and buggy.
because i dont have such problem with firefox esr 52!
firefox 61 i tested sometimes and i faced crashes even when reading web pages.
but i dont have such problem with firefox 52.9 and nvda 2017.2 which i use and 2017/1 which i tested google groups with it.

**Comment by jcsteh** [comment]
We believe this has been fixed by Microsoft. @leonardder, I'm closing this as fixed, but please reopen if the problem persists.
