### ISSUE TITLE
Allow live regions to be disabled.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#9077]
I am proposing allowing live regions to be disabled. I'm planning to control this with the report dynamic content changes setting, which could be set in profiles as well. Ideally, you'd be able to control on a per site | per region basis, but that isn't easy for us to do yet.
The idea would be to speak live regions when this setting is on, and nvda+5 will be finally able to stop monster pages (pages that read live regions incessantly). PR coming to plum live regions from IA2 through to a callback first, please comment on this proposal.

**Comment by bramd** [comment]
Sounds like a great idea and the behavior I expected in the first place. It would also be nice to provide callbacks on the Python level when a live region fires, so that appmodules or addons can decide if they should be spoken or not. A good case is the Windows 10 updates window in Settings. It floods NVDA with live region updates to indicate the status of every update multiple times, making it hard to see what is going on. With some more smart filtering, these message might be useful, but the logic would be very specific to this case.

**Comment by jscholes** [comment]
Any update on this?  I came here to report this specifically.  Live regions represent the very definition of dynamic content changes, but yet NVDA+5 has no impact on them at all.

**Comment by lukaszgo1** [comment]
I've recently tried to send some accessibility feedback to Google using the following form
https://support.google.com/accessibility/contact/feedback
Unfortunately with each typed letter and each arrow movement in the edit field current amount of characters and amount of characters allowed were repeated. It looks like this info was placed in a live region below the field. The fact that companies as big as Google are not using Live regions correctly shows how badly needed is the feature proposed here.
