### ISSUE TITLE
Add support for Propeller IDE

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9080]
### Is your feature request related to a problem? Please describe.

I had a request from a user to support the Propeller IDE by Parallax: https://developer.parallax.com/propelleride/

I downloaded the program and found that while I can type in the IDE, text is not read when navigating.  Reading the current line results in NVDA reading the first line, regardless of where focus actually is.  Reporting the object with focus reads the entire IDE text.

### Describe the solution you'd like

Support reading text in this IDE.

### Describe alternatives you've considered

Created an issue on the Propeller IDE project GitHub: https://github.com/parallaxinc/PropellerIDE/issues/56

**Comment by Adriani90** [comment]
Propeller IDE and Simple IDE are not active since more than 6 years now, but there is another IDE called spin tools, which works well for Propeller 1 and 2. nvDA works quite well with it, the user needs the Java Runtime JRE 17 for this to work.
https://github.com/maccasoft/spin-tools

Given the two projects Propeller IDE and simple IDE are not active anymore and there is an alternative, I am closing this issue as abandoned.
