### ISSUE TITLE
Firefox 64.0 (X64): Lag when entering Downloads Window from within Private Browsing

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9085]
STR:

1. Launch a copy of NVDA (2018.4 in this case), and a copy of Firefox 64

2. Enter a new Private Browsing window, and start a download

You will notice that when the prompt is displayed which asks what to do with the file, tabbing around the window is much slower than it was with Firefox 63, additionally, accepting the download and then opening the Downloads window shows the same behaviour

OS: Win 7 X64

**Comment by elliott94** [comment]
After more experimenting, it appears that this lag only happens initially if the download presents multiple options (as an example, a ZIP archive where the user can either choose to open or save the file). In the case of an executable (which only offers the option of saving the file), the initial lag cannot be observed but is still present when opening the actual Downloads window after the download has begun.

**Comment by elliott94** [comment]
One last update - interestingly, this also impacts certain sections of the Preferences dialog (the actual "Downloads" section within the dialog being a good example of this).

**Comment by lukaszgo1** [comment]
@elliott94 I was experiencing something similar in the past, but after updating to Nightly 66 this problem is solved for me. Are you able to check with the recent Nightly version?

**Comment by Adriani90** [comment]
@elliott94 are you still having this issue in Firefox 72 and NVDA 2019.3 Beta 1?

**Comment by Brian1Gaff** [comment]
Actually I moved back to Waterfox classic recently though I do have firefox. 
My main problem seems to be that Firefox now just vanishes for no apparent 
reason.

It can also lock the up but only if nvda is loaded. I will update it and see 
if we get the same thing as it is snappier than Waterfox and does not suffer 
from not opening the tab in the foreground syndrome Waterfax can have under 
some circumstances. On both browsers I als notice that some urls either say 
page not found until you do a refresh or parts of the page, say media 
players or advertising content do not appear or say server not found.
I suspect this though, could be down to my isp latency issue, which they say 
does not exist, but since I also get drop outs on alexa and the app store on 
I[phone, say it does.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by elliott94** [comment]
All resolved. Thank you. :)
