### ISSUE TITLE
Increased number of crashes in NVDARemoteHelper and Firefox

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9133]
I am seeing an increased number of crashes in Firefox and NVDA's RemoteHelper DLL today. The crashes occur while performing ordinary tasks such as opening a conversation in Gmail, or loading a Gmail tab alltogether, etc.

Three of the most recent crash reports I got, with varying signatures, but all related to NVDARemoteHelper.dll, are:

* https://crash-stats.mozilla.org/report/index/304a1d52-fbaf-46ca-b7ac-449e00190107
* https://crash-stats.mozilla.org/report/index/bfcc61e9-fc85-477e-be34-6c85d0190107
* https://crash-stats.mozilla.org/report/index/39516d12-2e98-4620-8d3f-dccde0190107

The last one has the NVDAHelperRemote near the top, not _at_ the top.

* NVDA alpha-16477,f6cd02d2
* Firefox Nightly 66.0a1 (2019-01-06)
* Windows 10 Version 1809 (Build 18309.1000)

@jcsteh, you have my permission to provide the mini dumps to @michaelDCurran for analysis.

**Comment by jcsteh** [comment]
These crash stacks all seem to be quite different. The fact that you're seeing them all around the same time might suggest correlation... or it might not. I'm particularly suspicious of the fact that UIAutomationCore shows up between Firefox and nvdaHelperRemote in two of the stacks, especially given the other UIAutomationCore crashes you've been seeing on Windows Insider builds. The other stack is a stack overflow and seems to be missing a whole bunch of intervening frames, but it's entirely possible UIAutomationCore is in there somewhere.

That said, the [@ kernelbase.dll | ntdll.dll | CxxThrowException] crash is I think due to a QueryInterface from IA2 to IAHyperlink failing. I'm not sure why it failed, but I didn't realise `_com_ptr_t` could throw exceptions. A failure could certainly happen here (e.g. if the object died while we were rendering), so we need to deal with this. As discussed in [this thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1f51e953-822f-4144-9415-cb2540a900d1/ccomptr-vs-comptrt?forum=vcgeneral), `_com_ptr` can throw exceptions, but `CComPtr` cannot. Since we're already using `CComPtr` elsewhere, we should probably just switch `HyperlinkGetter` to `CComPtr`.

**Comment by jcsteh** [comment]
From conversations with @MarcoZehe, I believe this has been resolved after fixes in both Windows and NVDA. Marco, please reopen if you think I've closed this prematurely.
