### ISSUE TITLE
When performing say all in the log viewer cared isn't following spoken text.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9179]
### Steps to reproduce:
1. open log viewer.
2. perform say all.
3. stop say all after some lines, and check caret location with NVDA+up arrow.
### Actual behavior:
Caret is in the place from which you've started reading.
### Expected behavior:
Caret should follow like in the notepad or MS Word.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2018.4.1 tested also with recent Alpha.
#### Windows version:
Windows 7
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Back to 2017.1 the issue was present in every version

**Comment by zahra21** [comment]
hello.
i tested with nvda 2017.3 on windows xp two times and i could not reproduce the issue.

**Comment by feerrenrut** [comment]
Rather than fix this log viewer issue, my preference would be to replace the log viewer with the following:
- A read only text box for 'devInfo'
- A button to open the log file in a default text editor.
  - Text editors such as Notepad++ have auto/manual refresh functionality, and the ability to save a copy of the file.
- A command to open the log in default editor directly so users can override the `NVDA+F1` shortcut if they wish.

@michaelDCurran @jcsteh @leonardder any opinion on this?

**Comment by lukaszgo1** [comment]
@feerrenrut I've used log viewer just as a convenient example. This problem occurs with most wx.TextCtrl's which I've seen in the wild - it is particularly problematic in apps used for reading longer texts such as QRead.

**Comment by feerrenrut** [comment]
Ah, thanks for pointing that out @lukaszgo1
