### ISSUE TITLE
NVDA announces a button with role="switch" and aria-checked="true" as "pressed checked"

### ISSUE THREAD

**Issue by iamrafan** [nvaccess/nvda#9187]
### Steps to reproduce:
1. Turn on NVDA and navigate to the button in the page(https://codepen.io/iamrafan/pen/NoPrBP?editors=1000) using NVDA
2. Observe how the toggle button is announced

### Actual behavior:
NVDA announces the toggle as "Improved dialog toggle button pressed  checked"

### Expected behavior:
The toggle is expected  to be announced as "Improved dialog toggle button checked" or " Improved dialog toggle button pressed"

**Comment by DrSooom** [comment]
@iamrafan: Please list all browsers (including version) where this issue occurs. Thanks.

**Comment by leonardder** [comment]
Comfirmed with Firefox 64.0.2 and Chrome. Firefox just ignores the aria-checked attribute with regard to the pressed state, Chrome seems to add both the checked and pressed states when aria-checked is true.

@jcsteh and  @MarcoZehe: could one of you spread some light on this?

It looks like there are two ways to implement toggle buttons, both which are considered valid implementation strategies according to the Mozilla Developer Network.

* role="switch", the pressed/unpressed state is covered with aria-checked
* role="button", the pressed/unpressed state is covered with aria-pressed

**Comment by iamrafan** [comment]
@DrSooom This specific issue occurs in both Chrome and Firefox

  | AT/Browser | Announced as
-- | -- | --
1 | Edge/NVDA | toggle button   pressed
2 | Chrome/NVDA | toggle button   pressed checked
3 | IE/NVDA | button
4 | Firefox/NVDA | toggle button  not pressed checked

Do you want me to file separate issue for:
1) NVDA not announcing the state in IE when aria-checked="true" ?
2) NVDA announcing aria-checked="true" as not pressed in Firefox ?

**Comment by jcsteh** [comment]
I honestly think trying to get the spec changed isn't worth the effort at this point. The simplest solution for now is to implement an overlay in NVDAObjects.IAccessible.ia2Web for xml-roles:switch, expose ROLE_CHECKBOX and remove STATE_PRESSED if present.

**Comment by leonardder** [comment]
@jcsteh wrote:
> The simplest solution for now is to implement an overlay in NVDAObjects.IAccessible.ia2Web for xml-roles:switch, expose ROLE_CHECKBOX and remove STATE_PRESSED if present.

What do you think about the alternative: Replace STATE_CHECKED with STATE_PRESSED? I think I prefer this approach:

1. It respects the aria role. A switch behaves like a checkbox, but it is supposed to be a toggle button
2. It will/can be consistent across browsers. It seems that Edge maps aria-checked to pressed in the case of switch, see https://github.com/nvaccess/nvda/issues/9187#issuecomment-458672152
3. While it does not respect the ARIA spec, changing the role to CHECKBOX wouldn't follow the spec either. The only way to follow the spec would be speaking the negative CHECKED state if appropriate, but that would be really hacky and is definitely not the way I'd go. Using STATE_PRESSED consistently actually implements the spec as we would have intended it to be (i.e. having aria-pressed for switch instead of aria-checked).

**Comment by jcsteh** [comment]
Your arguments are based on the premise that a switch is "supposed" to be a toggle button according to the spec. However, that is debatable. The spec says that a switch is "a type of checkbox". It doesn't say "a type of button". If you map it to checkbox, then speaking the negative checked state will "just happen" and is not hacky at all.

The fact that Edge treats it as a toggle button might be a convincing argument except that Edge will no longer be a real concern for much longer. :(

I don't really have a strong opinion on whether it should be a toggle button or a checkbox. My point is that I don't think you can convincingly use the spec to argue either way.

**Comment by leonardder** [comment]
> The spec says that a switch is "a type of checkbox". It doesn't say "a type of button". If you map it to checkbox, then speaking the negative checked state will "just happen" and is not hacky at all. 

You're correct.

> The fact that Edge treats it as a toggle button might be a convincing argument except that Edge will no longer be a real concern for much longer. :(

True. However, there is the UIA proxy for IA2, which I think will use the pressed state as expose by Chrome. I have to check that, though

Re #9219: the switches in Skype 8 really look like toggle buttons visually.

@michaelDCurran, may be you can cut the knot for us?

**Comment by leonardder** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [31 Jan 2019, 14:33 CET](https://github.com/nvaccess/nvda/issues/9187#issuecomment-459345187 "2019-01-31T13:33:27Z - Replied by Github Reply Comments"):
> There is the UIA proxy for IA2, which I think will use the pressed state as exposed by Chrome.

Nope, it looks like this is not yet complete. Both switches and buttons are treated as buttons, however there is currently no implementation for the relevant states. Tested with Windows build 18323

**Comment by MarcoZehe** [comment]
I just ran into this again with Riot. They're using the switch role and aria-checked, which in Firefox (and Chrome) sounds really messy. I am trying to change it to aria-pressed instead, but was pointed to various conflicting views on this, including this issue. Because the AAM says to map this to a toggle button, I am inclined to argue for aria-pressed, and maybe file spec bugs just for posterity. That, for Riot, is at least a fix that works and stops NVDA from saying stupid things like "not pressed checked".
