### ISSUE TITLE
could firefox page loading and download beep progress bars  be audable again?

### ISSUE THREAD

**Issue by mhussaincov** [nvaccess/nvda#9261]
### Steps to reproduce:
1.
load firefox,
2
go to www.google.com
3
download a file from any website

### Actual behavior:
progress bar beeps are not reported when firefox's page is loading,
or when a file is downloading when firefox's download window is being desplayed.

### Expected behavior:
like in the older versions of firefox, v3.x series nvda should indicate page loading via the beeping progress bars
and when a download is in progress to indicate how much the download has completed so far.
note:
in google chrome download progress can be herd in there download manager.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
snapshot alpha-16743
#### Windows version:
windows 10 v1809
#### Name and version of other software in use when reproducing the issue:
firefox 65.0

#### Does the issue still occur after restarting your PC?
YES
#### Have you tried any other versions of NVDA?
NO

**Comment by DrSooom** [comment]
@mhussaincov: Please add the NVDA version.
CC: @MarcoZehe and @jcsteh: I guess this is also something which has to be fixed in Firefox itself. … And in Thunderbird too.

**Comment by jcsteh** [comment]
There is no longer measurable indication of progress when a page is loading, even for sighted users. The reality is that trying to measure progress on the modern web is unreliable/inaccurate due to the various types of content, various ways pages load new content, etc. So, this is not something that can be restored.

As for progress during a download, I still get progress beeps in the Downloads window opened with control+j. Could you please re-test this part?

**Comment by DrSooom** [comment]
@jcsteh: In Firefox 56.0.2 and 65.0 there is a sound/beep feedback based on the download progress bar after the download window has opened with CTRL+J. (It doesn't appear in Thunderbird 52.9.1. Confusion on my side, sorry.)

But there is no build-in sound feedback on loading a page, when a page finished loading and when a single or all downloads are finished. Until Firefox 56.0.2 the add-on "Navigational Sounds" was a nice one to get this sound feedback. The add-on [Noise](https://addons.mozilla.org/en-US/firefox/addon/noise/) is working similar for Firefox 57.0+, but it's a little bit stupid to configure it. @MarcoZehe already told me that Mozilla isn't going to add such a sound feedback features directly in Firefox – even if it was planned for Edge. (I don't know the current status here.)

**Comment by MarcoZehe** [comment]
We once had this for iOS, and immediately got push back from it because this caused some problems in hearing aids used with an iPhone, among others pain in the person's ears. And as @jcsteh points out above, loading progress is very inaccurate nowadays anyway. I know that Safari on iOS has these progress clicks, but I've found more than one occasion where these even fell short because of some progresive web app, e. g. continuing to click when everything was already there.

**Comment by DrSooom** [comment]
@MarcoZehe: There only should be the ability to enable the sound feedback and set his own wave files for each event. Of course I'm not talking about to enable it automatically on default if Firefox's accessibility flag was enabled by a screenreader on startup. The user must enable it first. Well, but the add-on Noise should handle this – even Navigational Sounds was much better.

See also: Issue #9272

**Comment by Adriani90** [comment]
I also hear the progress tones when downloading and the download list is displayed. As for the second request of progress beeps for page download, I agree with the coments from Jamie and Marco.
Thus, I am closing this issue for now.
