### ISSUE TITLE
MS Outlook: NVDA does not report anything when switching between messages by ctrl+"." or ctrl+","

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9264]
### Steps to reproduce:
1. Open NVDA
2. Open a received message in Outlook
3. Press ctrl+fullstop or ctrl+komma to switch between messages without leaving the message window.

### Actual behavior:
NVDA does not report the sender and the subject line of the new message

### Expected behavior:
NVDA should report the sender and the subject line of the message I have switched to.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha 16743,9509C256

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Outlook 365

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

**Comment by Qchristensen** [comment]
Just confirming that I can replicate this on the same setup with NVDA 2018.4.1

**Comment by Adriani90** [comment]
cc: @CyrilleB79

**Comment by CyrilleB79** [comment]
With Outlook 2016, I do not have anything spoken when I press these shortcuts. It is a problem because the message has changed and this should be announced.

There is probably nothing announced because the foreground window of the message does not change; only its content is updated.

@Adriani90, why would you expect to have Sender and Subject announced? Is it because this is the information you are interested in? Or is it to be in accordance with another use case where this 2 pieces of information are announced? Note that when you open a message by pressing Enter in the message list, you can hear the foreground window title, that contains the object, as well as the line where the caret is located. But you cannot hear the Sender.

**Comment by Adriani90** [comment]
Well the first expectation is to hear the author and the subject as it is when you navigate in the message list with arrow keys. For keeping consistency I would say it makes sense to hear the same things when switching between messages with the commands in the issue title.
Anyway, it seems issue #10734 contains more information on this issue. I am closing this one as duplicate in favor of that one.
