### ISSUE TITLE
Allocate a hotkey to save a copy of the current logfile on the Windows Desktop

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9281]
In addition to issue #9280.
#### Procedure No. 1:
1. Open the Log Viewer via the NVDA menu.
2. Press CTRL+S to save a copy of it wherever you want.
#### Procedure No. 2:
1. Open the Windows Explorer and move to "%temp%".
2. Find "nvda.log" and copy it.
### Expected behaviour:
After the new allocated hotkey NVDA+CTRL+Shift+F2 was pressed, a copy of the current logfile is saved automatically on the Windows Desktop. The filename for this new logfile is based on the current timestamp, e.g. "NVDA_2019-02-15-012345.log".
#### NVDA installed/portable:
Both
#### NVDA version:
2018.4.1
#### Windows version:
Win7 to Win10-1903

**Comment by leonardder** [comment]
As pointed out in #9280, saving a log file on the desktop might result into a chaos on the desktop, which I'd avoid. Alternatively, having (parts of) the log copied to the clipboard could be useful.

**Comment by DrSooom** [comment]
We could also give the user the opportunity to choose the folder in which the copied logfile should automatically be saved by pressing this hotkey. The destination folder would be configurable via the General or via the Advanced NVDA Settings.

**Comment by DrSooom** [comment]
We could also give the user the opportunity to choose the folder in which the copied logfile should automatically be saved by pressing this hotkey. The destination folder would be configurable via the General or via the Advanced NVDA Settings.

**Comment by Adriani90** [comment]
This might result in forgetting what the default folder was especially when you didn't need the log file feature for a long time. Given the already confortable way to open the log, save it with ctrl+s, copying content from the log without opening it and having already the temp folder which already contains the log file, I think it is not desirable to add an additional feature to move the log file to another folder. This would be too much work for very less impact and would probably cause other downsides in the user experience.
Maybe this is a feature which can be handled by an addon rather than the core of NVDA.

I am closing this as wont fix.
