### ISSUE TITLE
The entrys of listboxes are not read

### ISSUE THREAD

**Issue by sonor3000** [nvaccess/nvda#9391]
### Steps to reproduce:

1. Open the following URL:

https://www.audio-markt.de/_markt/

2. Navigate to the first and second listbox (Produktgruppe, Hersteller)and try to read the entrys..., its not possible.

### Actual behavior:

the entrys of the listboxes are not read.

### Expected behavior:

The entrys should be read. This was possible before, at least with NVDA 2018.x.

#### NVDA installed/portable/running from source:

NVDA 2019 rc1 installed.

#### NVDA version:

2019 rc1

#### Windows version:

Windows 10, 64 Bit.

#### Name and version of other software in use when reproducing the issue:

Firefox 60.6.0 ESR, 64 bit.

#### Other information about your system:

With Google Crome 73.0 the listboxes are working....

#### Have you tried any other versions of NVDA?

Yes. With earlier versions, the newest 2018.x version, the litboxes are working.

**Comment by Adriani90** [comment]
Cc: @jcsteh

**Comment by jcsteh** [comment]
Thanks for reporting. Just to clarify, I assume you mean combo boxes, not list boxes?

This is a bug in Firefox that I'm working on fixing: https://bugzilla.mozilla.org/show_bug.cgi?id=1473234
This has been broken since Firefox 57. It is irrespective of NVDA version. It only happens with certain combo boxes (specifically, those within frames or shadow DOM).

We're already tracking this in #7819, so I'm closing this as a duplicate.
