### ISSUE TITLE
Upgrade to comtypes 1.1.7

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#9440]
### Is your feature request related to a problem? Please describe.

I saw that UIA is a bit slow than other screen readers (in stable releases), but after some testing I saw a better performance with this version of comtypes, not so much, but it is notable.

### Describe the solution you'd like

I don't know what should be the correct solution, because a comment from @leonardder on #8522. I was searching for the particular bug and I didn't found anything.

### Describe alternatives you've considered

I whas thinking about NVDA object caching, primarily for UIAHandler because it has a bad performance, same to JABHandler. I'm planning to do some testing today.

### Additional context

I saw in UIAHandler that every time that an event ocurs a new object is created. I suppose that it takes some time to instantiate it, and it impacts to NVDA's performance in heavy UIAutomation applications, such Visual Studio.

**Comment by leonardder** [comment]
There were some issues with comtypes 1.1.3, most notably causing the Handy Tech classic braille driver to stop functioning. See #7831. This was fixed in #8213, but than we had to switch back to https://github.com/enthought/comtypes/commit/edbaf3bfb7b0c68daa6ee8eac4a770dc66e296ec because https://github.com/enthought/comtypes/commit/98f6a42e8b452c67a65848d1c4476fb37df2aa6a introduced another bug. See also https://github.com/nvaccess/nvda/pull/8213#issuecomment-385655312.

Having said that, I think switching to the newest comtypes should be most prefered given your findings.
