### ISSUE TITLE
Skim reading

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#945]
**Reported by etman98 on 2010-09-26 11:50**
Skim reading allows you to read a file or webpage by a screen reader speaking certain important lines that the user specifies.  You can have it read text that is just one font color (such as red).  Could NVDA get something like that?

**Comment by leonardder** [comment]
Seems like a valid request, but the ticket is quite abandoned. If noone else shows interest in this before end of next week, I will close.

**Comment by ruifontes** [comment]
Skin reading is very interessant to read/consult big documents...
You can define a word or conjunt of words, and ask NVDA to read only sentences with those words, or, by instance, ask NVDA to read the 3 first lines of each paragraph...

We talked some days ago in addons list ina feature related...

Hi Derek!

1 - Check if I did not repeat lots of times, unnecessarily, the same word...

2 - If with the same features of Jaws, create resumes where a specific word 
appears, and that way check only the meanfull parts of a big document.

Rui

-----Mensagem Original----- 
De: derek riemer
Data: 17 de julho de 2017 17:34
Para: nvda-addons@nvda-addons.groups.io
Assunto: Re: [nvda-addons] Suggestion for a new add-on


Besides being curious about how many words are in a document, what use will 
this have to make it worth my time to write?


On Sun, Jul 16, 2017 at 10:49 AM, Mohammadreza Rashad 
<mohammadreza5712@gmail.com> wrote:
Hi dear Derek,
As I'm not so good in English writing, I will try to illustrate what I
mean by giving a practical example:
1. I run JAWS.
2. I open NVDA User Guide.
3. Now, I press the Insert+Ctrl+W key combination to run the "Word
list" command.
   By the way, I ran this in a text document and it listed the words
of that txt file in Notepad.
4. It lists the wirds in order of their occurances in the document:
   NVDA (561)
   key (241)
   dot (212)
   will (201)
   braille (180)
   display (126)
   object (117)
   when (113)
   text (106)
   review (105)
   option (101)
   Move (99), etc...
5. In list above, "NVDA (561)" means: the word "NVDA" repeated 561
times in the document; "key (241)": the word "key" repeated 241 times;
and so on.
The word list is part of a dialog box which also has "OK", "Cancel",
and "summary" buttons. When I select a wird from the list and press
OK, The cursor lands on the first occurance of that word. Then when I
press "W", it moves on the second occurance; and so on.
When I press "Summary" button on selected word, It will list the
sentences that have my selected word.
That's it. Excuse me because of my lenghy explanation.
     Best wishes,
     Mohammadreza

--
     Best wishes,
     Mohammadreza Rashad

**Comment by leonardder** [comment]
cc @DerekRiemer

**Comment by Adriani90** [comment]
I think the suggestion from @ruifontes is more suitable in an addon rather than in the NVDA core. 
But note, you can already navigate parapgraph by paragraph with ctrl+down or up arrow key and listen only to the first sentences. So actually not really a need for an addon for this.
* You can also search for a word with NVDA+ctrl+f and then jump with nvda+f3 or shift+nvda+f3 from result to result.
* We also have sentence by sentence navigation, at least in word. For sentence navigation in other programs, a different issue is already in place.
* We have already the setting "Allow skim reading during say all" which acomplighes this. Paired with quick navigation key for headings, lists etc in most documents in browsers and MS Word or Adobe Reader, a good user experience is already in place.

Regarding navigation by colors, this is covered in two other issues already.

Given theese features, I am closing this issue in favor of other issues addressing the few remaining points on this matter.

**Comment by peterpacult** [comment]
Dear NVDA team, like the previous speakers, I would be very happy if such a function could be implemented in NVDA.

**Comment by CyrilleB79** [comment]
Here are some refs of the already opeend issues mentionned by @Adriani90:

> * We also have sentence by sentence navigation, at least in word. For sentence navigation in other programs, a different issue is already in place.

Reference: #8518.

> Regarding navigation by colors, this is covered in two other issues already.

References: #9527, #7744

@peterpacult if these opened issues match your need, please comment there.
Else, please open a new issue since the original reporter of this issue probably cannot be contacted anymore and thus will not reopen the current issue.
