### ISSUE TITLE
Expanding and collapsing disclosures in the Firefox console in browse mode unexpectedly redirects focus to text input

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#9490]
Cc: @MarcoZehe and @jcsteh

### Steps to reproduce:

1. Paste the following code into the console.

```
console.groupCollapsed("test");
console.log("some content");
console.groupEnd();
```

2. Press space on the collapsed button to expand its contents, while still in browse mode.

### Actual behavior:

Focus is always forcefully moved to the text input. The disclosure does expand.

### Expected behavior:

The disclosure is expanded, and focus does not move unexpectedly.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17077,7f274eca

#### Windows version:
Windows 10 1809

#### Name and version of other software in use when reproducing the issue:
Firefox 67.0 b10

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by jcsteh** [comment]
This isn't NVDA specific. It looks like clicking the button throws focus to the console input. My guess is that they're doing this so the button doesn't get focus when it is clicked with the mouse, since that's the default behaviour and is probably pretty annoying for mouse users in this case (they want the input to keep keyboard focus). It'd be great if you could file a Mozilla bug and CC me (or provide the bug number here if you can't do that).

Note that if you activate it by pressing enter (which would require passing the key through or switching to focus mode), this doesn't happen. 

I'm closing this, since I don't see a need for the NVDA project to track this itself.

**Comment by Neurrone** [comment]
Thanks for investigating.

I've [filed this bug on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1544773). Tried to CC you like I would on GitHub, not sure if it worked or not.

**Comment by jcsteh** [comment]
Thanks! No, you can't CC like that; there's a separate CC field where you
can type :jamie (or my Mozilla email address) to CC me. That said, I'm not
sure if you can access that field or not. Regardless, I followed the issue
myself.

**Comment by Neurrone** [comment]
I see a combo box called "Need more information from", is this the one you're referring to?

**Comment by jcsteh** [comment]
No; that's for an explicit request for further information from that user.
There should be a "cc list" section near the top of the bug. That said,
it's possible you don't have access to that; I'm not sure. In any case,
once I have bug numbers, it's all good.

**Comment by Neurrone** [comment]
Thanks, I found it by expanding the people section disclosure.
