### ISSUE TITLE
Input Gestures Dialog: Add Missing Gestures for Document Formatting

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9507]
When taking a look at the gestures listed for Document Formatting from within the Input Gestures dialog, I've noticed that both "Cell Borders" and "Font Name" are missing. Would it be possible to add these so that all gestures are present?

**Comment by DrSooom** [comment]
In NVDA 2018.1 "Cell Borders" is missing, but there is an entry for the font name. It's called "Toggle reporting font name changes on or off" or so. (I'm using the German GUI.)

And for the next time, please completely fill out the bug report draft for such kind of issues. Thanks in advance.

**Comment by fisher729** [comment]
@DrSooom , please remember that following the template is not a requirement, but rather suggested by NV Access to properly diagnose an issue. In this case, the issue can clearly be pointed out, as the author of the ticket included steps to reach his/her conclusion. Furthermore, once no version of NVDA is stated, it is my opinion that persons try to recreate the issue with the latest NVDA version first, before asking for a version number. The Windows version would not affect an issue like this.

**Comment by DrSooom** [comment]
@fisher729: It isn't clear if the latest stable or alpha build is used. Furthermore you have to think about the exact version first, if you read such issues without the NVDA version a few years later, to figure out if this issue could still exist. And the [snapshot list](https://www.nvaccess.org/files/nvda/snapshots/) also only contains just a few alpha, beta and RC versions of NVDA. So this site also doesn't help you here either.

And of course, sometimes it isn't necessary to completely fill out the draft. I only add a comment, if I think that significant additional information for reproducing the issue is required. And I'm also thinking a few years into the future. New developers might not know all NVDA releases. Therefore it's always better to mention it directly in the issue description. Finally this will save much time for the developers in the future.

**Comment by fisher729** [comment]
The point is that, in the current stable release of NVDA, and in the latest snapshots, an entry for the reporting of cell boarders is not present. This is after my own tests. Reporting of font names is present, but represented as font changes. I propose this be changed.

In the future, I believe as persons who want to see the quick resolution of bugs and issues, that initiative should be taken to test obvious things from our end, before seeking to ask these questions ourselves, thereby dragging them out.

**Comment by leonardder** [comment]
[**@fisher729**](https://github.com/fisher729) commented on [23 Apr 2019, 02:44 CEST](https://github.com/nvaccess/nvda/issues/9507#issuecomment-485600764 "2019-04-23T00:44:52Z - Replied by Github Reply Comments"):
> @DrSooom , please remember that following the template is not a requirement, but rather suggested by NV Access to properly diagnose an issue.

Slightly offtopic, but I just wanted to quickly reply on this. While filling in the issue template is not required, it is strongly encouraged and appreciated to do so. I wouldn't call it just a suggestion.

Having said that, this looks like an oversight in #6895. I guess it is pretty easy to add such a script. Labeling this as "good for new dev".
