### ISSUE TITLE
Error message on addon installation

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#9514]
### Steps to reproduce:
On a fresh new portable NVDA
- Install an addon by executing it file in Windows explorer (e.g. Easy Table Navigator)
- Click 2 times "Yes" to install the addon

### Actual behavior:
A message is shown telling that the addon installation failed. However, the addon seems to be installed correctly anyway.
Log attached.

### Expected behavior:
Addon should install without error message.

#### NVDA installed/portable/running from source:
Portable ; same issue with NVDA installed as well (but many addons already installed)

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 1709

#### Name and version of other software in use when reproducing the issue:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
[NVDALog.txt](https://github.com/nvaccess/nvda/files/3107459/NVDALog.txt)

**Comment by DrSooom** [comment]
If you only use NVDA Portable, opening an .nvda-addon file via the Windows Explorer shouldn't work. I guess the .nvda-addon file is still allocated to the installed NVDA version.

Maybe it's better to block the add-on installation process via the Windows Explorer if NVDA is running in portable mode.

**Comment by DataTriny** [comment]
Hello, for those who are interested, error log starts at line 270.
@DrSooom Opening an NVDA addon in the Windows Explorer installs it as expected without any issue.
However, I can't reproduce the issue by installing EasyTableNavigator on a portable copy of NVDA 2019.1.1, running on Windows 10 version 1809 (got the same behavior with an installed copy).

**Comment by fisher729** [comment]
Yes, @DrSooom, it should be able to be installed without any issues, if NVDA is running, despite running a portable copy. This is unless NVDA is not installed on that system. Any further ideas

**Comment by leonardder** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [23 Apr 2019, 18:04 CEST](https://github.com/nvaccess/nvda/issues/9514#issuecomment-485868550 "2019-04-23T16:04:28Z - Replied by Github Reply Comments"):
> I guess the .nvda-addon file is still allocated to the installed NVDA version.

This is incorrect. Whenever the NVDA installation process starts after opening a nvda-addon file, it will be installed in the running version.

@CyrilleB79: Which add-on are you using that causes this issue?

**Comment by DrSooom** [comment]
@leonardder: Thanks for the correction. I haven't tested that specific situation.

**Comment by CyrilleB79** [comment]
Hello

By testing the new DebugHelper addon from @XLTechie V1.0, I get the same error on NVDA 2019.2 installed version, wether the other add-ons are de-ativated or not. The issue occurs only when I install from explorer, not from Add-ons window.
However, with V1.0.01-dev, the issue has disapeared. 

@XLTechie, what are the modifications between these 2 versions? Thanks.

Please find attached the [Install_DebugHelper_NoExt_nvda.log](https://github.com/nvaccess/nvda/files/3541628/Install_DebugHelper_NoExt_nvda.log) file, when I install V1.0 without extensions activated

**Comment by XLTechie** [comment]
There were two, only one of which seems likely as the source of this:

First, I did not have either the .gitattributes or style.css files installed 
from the add-on template when I made this add-on. The .gitattributes file, in 
particular, implements an option which converts from DOS to Unix style newlines 
before git push.
The Python file for the add-on had been using cr/lf, because I had been editing 
it under Windows and thought it safer to use Windows-style line endings.
So what I did there, was to convert it to unix style, and push.

The second thing, was to read the file into Notepad++, and re-encode it as UTF8. 
However I think this did nothing, as the file still reports as ASCII, and 
contains no characters beyond the normal 128. It contains the magic which tells 
Python2 that it is UTF8, and Python3 assumes it is anyway, so I don't believe 
this was the cause.

I can not directly test whether either of these was at issue, because I have no 
systems that ever showed this problem.

Lastly, though I don't think this is it: version 1.0 was packaged using a local 
installation of scons on Win 10 1903 64bit, Python 3.7. Version 1.0.01-dev was 
packaged using Appveyor, Python 3.7, and possibly a very slightly different 
version of the Gnutext executables. That said, there are no translations here.
I can get exact versions of everything if someone thinks this is relevant, 
though I do not.

Links:
debugHelper v1.0: 
https://github.com/XLTechie/debugHelper/releases/download/1.0/debugHelper-1.0.nvda-addon
debugHelper v1.0.01-dev: 
https://github.com/XLTechie/debugHelper/releases/download/1.0.01-dev/debugHelper-1.0.01-dev.nvda-addon

**Comment by DrSooom** [comment]
@XLTechie: Notepad++ supports the LF line ending format as well as CRLF and CR.

**Comment by XLTechie** [comment]
Thank you, I know. However when I started writing this add-on, I wasn't using 
Notepad++ for the purpose. It was originally done on Linux, and every once in a 
while I would pull it into notepad in scratchpad to make some change or other, 
and Notepad is not well known for its handling of Unix line endings.

This was originally just a tool for me, so it didn't matter at the time. Then 
later, when I expanded it into a real add-on, the old newline format persisted.

All that said though, mine is not the only add-on with this rare issue, and it 
is a bit strange that the install code can get so hung up on this on some 
systems, but not on most.

**Comment by leonardder** [comment]
I wonder whether Alpha versions of Python 3 handle this differently, in which case we might be able to safely close this issue.

**Comment by CyrilleB79** [comment]
On NVDA add-on mailing list and via private e-mail, @XLTechie suggested that running COM Registration Fixing tool may change something to this issue, according to what he has seen in my log.

I have run the fixing tool, but this has no effect on the error, which is always the same.

Note that I did not find any information in the user guide or elsewhere regarding this tool. Where can anybody know when it is required to launch it and what type of issue it may fix ? On the contrary, the features of the "Advanced" setting panel are documented, even if they are only for advanced users.

At least,In the past however, I have installed the same version of Outlook Extended without any problem. I have updated some add-ons. The issue does not occur anymore with the DebugHelper 1.0 add-on (as it did before), but occurs with OutlookExtended 1.3. This let me think that the add-on's content (end of line or other) is not responsible to cause this issue.
I am not be able to investigate further.

**Comment by XLTechie** [comment]
On Tue, 27 Aug 2019, CyrilleB79 wrote:

> On NVDA add-on mailing list and via private e-mail, @XLTechie suggested that running COM Registration Fixing tool may change something to this issue,
> according to what he has seen in my log.

Mainly because what was in your log was the same error series as the one or two 
others who had the original problem saw in their logs, and running it for them 
at least seemed to fix the problem.

> I have run the fixing tool, but this has no effect on the error, which is always the same.

Unfortunate.

> Note that I did not find any information in the user guide or elsewhere regarding this tool. Where can anybody know when it is required to launch it and
> what type of issue it may fix ?

The basic answer seems to be: if things are acting strange, run it. I have some 
idea of what it does, but am not the best person to answer this question.

**Comment by Adriani90** [comment]
@CyrilleB79 do you still see this issue in NVDA 2019.3 Beta 2?

**Comment by CyrilleB79** [comment]
I do not remember having seen this issue on NVDA2019.3beta1 or beta2, nor recently on an alpha. However the issue was only appearing sporadically. Thus I cannot guarantee that the issue has disappeared on NVDA 2019.3beta2.

@Adriani90 is there something specific that let you think that this issue could go away with NVDA 2019.3? Or is it just because you are trying to clean old issues with Python 3 transition? Just curiosity...

In any case, you can close this issue. If I ever get the problem again, I will re-open it.

**Comment by Adriani90** [comment]
@CyrilleB79 actually I found this issue by chance while looking for something else. I thought it might be solved while migrated to Python 3.
However, looking at your log file, it seems this file comes after you restarted NVDA with addons disabled. Right?
If you choose this option in the exit dialog, I guess NVDA disables all addons, including addons which you install in that session. I am not an expert, but as far as I know the addons are enabled by default when installing them. This issue might have been caused by the fact that NVDA explicitely disabled addons after restart.
Do you think this aplies to addons which are being installed in that running session?

**Comment by CyrilleB79** [comment]
Disabling add-ons is not the cause of this issue. Indeed, I have originally encountered the issue with add-ons normally enabled trying to install a new add-on. However, to reproduce the issue in clean conditions, I have taken the log after a restart with add-ons disabled to eliminate possible causes coming from add-ons or from previous NVDA usage.

Moreover, looking at the error, it does not seem to have something to do with disabled add-ons.

Also, I have checked (at least on 2019.3beta2), that you can install add-ons from explorer file without problem even if NVDA has been started with add-ons de-activated.

Anyway, if you do not have any other question about this, we may close this issue as explained before.

**Comment by Adriani90** [comment]
Thanks for the reporting. I am closing this as works for me.

**Comment by CyrilleB79** [comment]
Hello
Re-opening this issue as this has been seen on NVDA2019.3 and communicated on nvda-devel mailing-list. See [this link](https://nvda-addons.groups.io/g/nvda-addons/message/12036).
Jan, please feel free to comment.

**Comment by johnykulik4025** [comment]
We will see if it will have such behavior in the new version 2020.1. I doubt it will.

**Comment by DrSooom** [comment]
Here is the link for [NVDA 2020.1 Beta 1](https://ci.appveyor.com/api/buildjobs/7tih7jg3w06cyqn0/artifacts/output/nvda_2020.1beta1.exe) if you wanna test it.

**Comment by CyrilleB79** [comment]
Since the issue occurs sporadically, I recommand not closing this issue even if it is not reproduced with 2020.1. At the time, I have  accepted to close it after 2019.3 migration since this release had a lot of changes including Python3 transition. In 2020.1 there is nothing in release notes that would let think that this issue has been resolved.
I would recommand to track each occurrence of this issue here and to close it if nothing has been reported during many release cycles, not only one.

**Comment by CyrilleB79** [comment]
@Adriani90 would you mind to re-open this issue as per https://github.com/nvaccess/nvda/issues/9514#issuecomment-609483205 and https://github.com/nvaccess/nvda/issues/9514#issuecomment-609594879?
I cannot re-open it since I did not close it myself.
Thanks

**Comment by Adriani90** [comment]
Is anyone still able to reproduce this issue? Without any updates on this is is really hard to continue investigations.

**Comment by CyrilleB79** [comment]
I remember having had this issue once between March and July 2020, so with NVDA 2019.3 or an early 2020 version. Unfortunately, I did not report it here.

Regarding investigations, if someone is able to say something on the error, this would be useful for the next time I encounter the issue. What should I or someone else do if encountering this issue again?

As a record, the error in the [last available log](https://nvda-addons.groups.io/g/nvda-addons/message/12036) is the following:

> ```
> ERROR - gui.addonGui.installAddon (12:33:09.513) - MainThread (3200):
> Error installing  addon bundle from C:\Users\Janko\Downloads\tonysEnhancements-1.4.nvda-addon
> Traceback (most recent call last):
>   File "gui\addonGui.pyc", line 563, in installAddon
>   File "contextlib.pyc", line 119, in __exit__
>   File "gui\addonGui.pyc", line 546, in doneAndDestroy
> RuntimeError: wrapped C/C++ object of type IndeterminateProgressDialog has been deleted
> ```

**Comment by Adriani90** [comment]
cc: @seanbudd I am not sure but this issue might be fixed meanwhile.

**Comment by CyrilleB79** [comment]
This issue seems similar to #13042, which is much more easy to reproduce; I do not know if the causes are the same.

**Comment by CyrilleB79** [comment]
No new occurrence of this issue.

Given that:
* I have not had this issue for a very long time
* I have not heard of any such new report on the mailing lists during all this time
* the add-on framework has been largely reworked with the Add-on Store
* the issue was very rare and only affecting very few people

I will close this issue. If someone encounters it again, we may reopen this one or open a new one.
