### ISSUE TITLE
Rapid integration of multiple infrastructure changes may cause user-facing instability and decrease confidence

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#9539]
I am raising an issue which may have been already discussed, feel free to discard.

Looking at recent development it looks like both Python 3 and the large work on speech refactor will be landing pretty close together, potentially on the same release.
I absolutely understand wanting to perform all possible breaking changes concurrently, so staggering these temporally is not optimal.

With that considered, I propose both strong messaging around the eventual release, mentioning instability, and a much longer than usual Alpha period.

Really looking forward to this modernization work, and thank you for all you do.

**Comment by josephsl** [comment]
Hi, I second this motion. I will do the same for the add-ons community once Project Threshold officially kicks in. Thanks.

**Comment by leonardder** [comment]
I also agree that we need to test carefully. There are some things pretty hard to test, for example, braille display drivers that are in core but not used very widely, appModules for some pretty old apps. Some appModules and drivers might even perish during the process.

Note however that project threshold will be hosted in a stand alone branch. This means that the Python 2 based code base of NVDA can still be developed further. I think that it is unlikely that 2018.3 will be based on threshold, and I think that even a 2018.4 based on threshold would be a race against the clock. That, unless the release schedule is slightly modified/paused for this reason.

**Comment by Brian1Gaff** [comment]
Well as the resident ludite around here, I'm happy to test Outlook Express 
and maybe some older versions of Office etc, if I'm poked accordingly.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
I agree we should stay with two parallel master branches, python 2 and python 3. If someone wants to change to python 3, they can do that. If not, they can still stay to python 2 for a while. But in any case we must inform the community widely that testing under python 3 is very importnat because one day the python 2 branch will not exist anymore. Then, also people using older braille displays or older software will be incentived to test their things under python 3.
This work needs also a big contribution from translators worldwide. Because in many less developped countries people are still using old systems with old pieces of software or old braille displays. Even in Germany some people are still using 20 years old braille displays. So we have enough people to get feedback from. Don't forget to consider contacting translators from every country to promote this.

**Comment by zstanecic** [comment]
I as a croatian translator can help with this...

**Comment by leonardder** [comment]
I have the feeling that this issue is pretty hard to monitor, as it appeals on our attitudes rather than on a particular change in code. Therefore, I"m closing this issue for now. If you have the feeling that messaging from either NV Access or other NVDA Council isn't what you expect, feel free to reach out again.

**Comment by josephsl** [comment]
CC @MichaelDCurran, @feerrenrut and others.
