### ISSUE TITLE
When setting a key for a profile, NVDA does not save the configuration

### ISSUE THREAD

**Issue by diegomatos16** [nvaccess/nvda#9922]
When trying to set a key for a profile, and pressing ok, NVDA displays the following message:  Error: saving user defined gestures - probably read only file system. When pressing ok, it saves the key, but when restarting NVDA, the configuration is lost.
Steps to reproduce the problem:
1: Open the input gestures dialog, and set a command for a profile.
When you press ok, the message above will be displayed.
2: Even if you press ok and verify that the equal command has been saved, try restarting nvDA; the command will be lost.
NVDA 2019.2 beta 2, Windows 7 64 bit.

**Comment by XLTechie** [comment]
For what it's worth, I can not duplicate on Windows 10 1903 64bit, with NVDA 
beta-18028,e579eb02.

I will note, however, that gestures are saved separately from the configuration, 
in a file at %appdata%\nvda\gestures.ini

I consider the way gestures are currently handled to be a bug, since they are 
not saved as configuration, even though they are configuration material; and 
thus can not be saved and loaded in a configuration profile.

Anyway, it sounds as if your gestures.ini is read-only.

**Comment by XLTechie** [comment]
If the file or folder is not read-only, or denied permission to your user, 
try to save a gesture and post the debug level log of what happens.

**Comment by Brian1Gaff** [comment]
I've seen this in Windows 7, I assumed it might be that for some reason 
something has a file locked and cannot  release it in time. Similar to some 
windows 7 rebbots of nvda after an update get stuck with cannot write to 
the log file that one gets from time to time.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Brian1Gaff** [comment]
There is more to this issue than meets the ear. I just removed the profile, 
restarted nvda beta 3 and then recreated it and went to the key config and 
used just nvda/e as the one trigger, then checked it, and exited with save 
on, and when I reloaded nvda it was still working. However the problem now 
is that I used it to change the synth, and of course it only now changes or 
unchanges it if you are where you were before, otherwise it gets confused 
and you have to activate and de activate the profile to get the old synth 
back in the window you are in!


I'm confused. Is there a way to make the  profile globally work so that it 
does not  appear to be off but still on?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by bdorer** [comment]
Hi, I'm not able to reproduce this.
@Brian1 could you add Stepps to reproduce so I can test your case?

Am 13.07.2019 um 21:48 schrieb diegomatos16:

**Comment by leonardder** [comment]
@diegomatos16: Can you still reproduce this?

**Comment by diegomatos16** [comment]
2019.2.1 works correctly the feature

**Comment by diegomatos16** [comment]
Unfortunately, I just noticed that the bug is still going on with NVDA 2019.2.1.
I tested on 2 different systems, windows 7 and windows 10.

**Comment by bdorer** [comment]
Hi, this is a bug introduced by brailleExtender. I'm able to reproduce 
it with NVDA 2019.2.1 but not with latest NVDA-alpha so it has to do 
with python3 support I think.
@diegomatos16 please deactivate brailleExtender and try to reproduce.

Thanks

Am 04.11.2019 um 01:37 schrieb diegomatos16:

**Comment by diegomatos16** [comment]
Hi. I am not with the braille extender addon instaled in NVDA.
