### ISSUE TITLE
Provide VS Code support within NVDA"s git repository

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9971]
### Is your feature request related to a problem? Please describe.
Visual Studio Code is currently a pretty accessible IDE for code development. Most importantly, it allows you to apply real time linting and view the warnings/errors raised by the linter. #9958 will introduce flake8 as a linter within NVDA to check code quality and style. 

### Describe the solution you'd like
I propose including a basic visual studio code project within NVDA for people to get started with VS Code, using flake8 as the linter configured to use our specific flake8 configuration.

### Describe alternatives you've considered
Provide a community driven repository for this (i.e. don't include a project in the NVDA git repository itself).

### Additional context
Initial work was created by @bramd in his vscode branch. This work is based on pylinter. I forked this branch and am using a prototype implementation of a visual studio code project that uses flake8 as the linter, based on configuration from #9958.

**Comment by Adriani90** [comment]
cc: @pawelurbanski this could be of interest for you as well.

**Comment by francipvb** [comment]
Hello @leonardder 

> 
> Provide a community driven repository for this (i.e. don't include a project in the NVDA git repository itself).

I think that this is not necessary to separate VSCode-related files from the parent repository.

Just a thought: What about debugging with VSCode? Is it possible to debug NVDA without sight?

Cheers,

**Comment by pawelurbanski** [comment]
I created a module that improves how NVDA interacts with VS Core. It was accompanied with some fixes in the VS Code itself, I contributed as well.
The add-on is here:
https://github.com/pawelurbanski/nvda-for-vs-code

I plan to provide improvements. The VS Code core team is very much interested in accessibility and I will also start working on some bigger changes to the VS Code itself.
Due to the nature how VS Code is implemented using the Electron shell, I may always need an NVDA add-on to work best. Since Microsoft switched rendering Edge for the Chromium core, which happens to be the runtime for electron, they are working on swapping iAccessible2 for the native UIAutomation support. Therefore we can expect some welcome changes coming soon.
